src/screens/AvatarBuilder.js

Fix emojipicker in small devices plus better extend it in larger devices.
https://www.loom.com/share/18f25f4dd73f48ed814df7e685fe2ca0

EmojiPicker fix for screen height

---

src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
src/components/unique-token/UniqueTokenImage.js

Display NFTs in higher resolution and add progressive loading to them when available.

@nico/nft image size improvements

---

src/components/fab/ExchangeFab.js
src/components/fab/SendFab.js
src/components/savings/SavingsSheetEmptyState.js
src/hooks/useExpandedStateNavigation.js
src/redux/walletconnect.js
src/screens/SavingsSheet.js
src/utils/index.js
src/utils/watchingAlert.js

fixes RNBW-1307
ios: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-08-14-52-28.mp4
android: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-08-14-59-46.mp4

updated watching alert

---

ios/Podfile.lock
ios/Rainbow.xcodeproj/project.pbxproj
ios/fastlane/Fastfile
ios/fastlane/README.md
package.json
scripts/postinstall.sh
src/App.js
yarn.lock

- Sentry bump
- Remove ruby sentry-cli  and use node cli instead
- Remove all custom fastlane stuff
- Fix xcode project config
Before -  Bundle was an empty file
After - Bundle is being uploaded correctly

Fix sourcemaps

---

src/components/expanded-state/UniqueTokenExpandedState.js
src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
src/utils/buildRainbowUrl.js
src/utils/index.js

Nft expanded state was looking bland, especially with sparse metadata(ex. on polygon)
Added a share button a la christian
before: https://cloud.skylarbarrera.com/Screen-Shot-2021-07-13-12-53-11.64.png
PoW watch wallet: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-13-14-27-21.mp4
PoW external profile: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-13-14-29-49.mp4

NFT share sheet button

---

src/components/contacts/ContactRow.js

before: https://cloud.skylarbarrera.com/Screen-Shot-2021-07-13-12-42-04.47.png
after: https://cloud.skylarbarrera.com/Screen-Shot-2021-07-13-12-41-32.37.png

💆‍♂️ contact address design parity

---

src/components/settings-menu/SettingsSection.js

PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-13-11-35-07.mp4
Moved ScrollView and fixed some styling that was causing issues

fix settings scroll for tiny phones

---

src/components/coin-icon/ChainBadge.js
src/components/coin-icon/RequestVendorLogoIcon.js
src/screens/TransactionConfirmationScreen.js

fixes RNBW-1351
added chainBadge sizes: medium(vendor icon) & large(NFT cards)
Pow: https://user-images.githubusercontent.com/29204161/125712707-17eb90a6-abd2-4077-af87-d40cf1d81501.MP4
Mainnet Requests: https://user-images.githubusercontent.com/29204161/125712741-440a291b-a5ab-461d-b886-c578e7534843.PNG

l2 explainer for WC

---

src/components/walletconnect-list/WalletConnectListItem.js
src/helpers/findWalletWithAccount.js
src/helpers/walletConnectNetworks.js
src/screens/WalletConnectApprovalSheet.js
src/styles/colors.js

Not up to the most recent design spec but we should save for WC v2 as its a completely different flow and shouldnt block L2 release
TODO: need to double check Android, cant do today will check tomorrow AM
Fixes any blocking issues
- there was an issue finding account profile data due to how they're stored, i added a helper to solve this issue.
- Added network colors to colors.js so we can handle any dark mode issues. @brunobar79 lmk if  i missed any instances.
- UI clean up and additions 
PoW: 
https://user-images.githubusercontent.com/29204161/125690155-fa75db6c-d535-4804-936e-d962c28faffd.MP4
fixes fixes RNBW-1352

connected apps cleanup

---

src/components/coin-row/SendCoinRow.js
src/navigation/config.js
src/screens/SendConfirmationSheet.js
src/screens/SendSheet.js

fixes RNBW-1376
PoW:  https://user-images.githubusercontent.com/29204161/125725371-fe9a6ad0-80e7-4a6c-8233-57ebd8cf5ecb.MP4
fixes RNBW-1378
@brunobar79 feel free to change anything / get w me on this
PoW:  https://user-images.githubusercontent.com/29204161/125725586-0d0a311e-ee47-453d-b507-ff0c43702fc8.MP4
fixes RNBW-1379
PoW:  https://user-images.githubusercontent.com/29204161/125726053-98b87a20-a426-4582-874a-2e156fb62c17.MP4
fixes RNBW-1380
PoW:  https://user-images.githubusercontent.com/29204161/125725899-acda952e-4913-40c3-a59d-9200b23cf9de.MP4

L2 Send Sheet Bug Bonanza

---

android/app/build.gradle
src/screens/PinAuthenticationScreen.js
src/screens/WalletDiagnosticsSheet.js
src/utils/haptics.js

- add haptic feedback for PIN Entry
- request PIN if needed on wallet diagnostics
- Bump android version

Fix wallet diagnostics android

---

src/screens/SendConfirmationSheet.js

fixed a bunch of bugs related to account avatars, colors etc for the the send confirmation sheet.  Now we check the walletAccounts for accountInfo and handle the data in the following order.
contact info > account Info > hashed address data
centered the chevron as well
Pow: 
https://cloud.skylarbarrera.com/Screen-Shot-2021-07-19-20-17-02.98.png
https://cloud.skylarbarrera.com/Screen-Recording-2021-07-19-20-22-31.mp4

send confirmation profiles 

---

src/components/send/SendContactList.js

Optional chaining on close function that may not exist

Fix intermiitent send contact list crash

---

src/components/asset-list/AssetListHeader.js

Saw this crash on sim when switching between an empty wallet and one with assets:

Fix AssetListHeader crash

---

scripts/extract-metadata.js
src/utils/getUrlForTrustIconFallback.js

Update assets fallback url

---

ios/Gemfile.lock
ios/Podfile.lock

fastlane broke: https://github.com/fastlane/fastlane/releases/tag/2.188.0

bump fastlane

---

src/components/avatar-builder/ColorCircle.js
src/screens/AvatarBuilder.js

Fixes RNBW-1392 and RNBW-1373.

Fix color circle alignment on odd-pixel screen widths

---

src/hooks/useAdditionalAssetData.ts

crash: https://sentry.io/organizations/rainbow-me/issues/2533368587/?project=1855565&referrer=slack

prevent crash

---

src/hooks/useExpandedStateNavigation.js

fixes RNBW-1406
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-28-12-18-32.mp4

show watching alert for send action button

---

src/components/coin-row/CoinName.js
src/components/coin-row/ExchangeCoinRow.js

before: https://cloud.skylarbarrera.com/Screen-Shot-2021-07-26-22-04-24.57.png
after: https://cloud.skylarbarrera.com/Screen-Shot-2021-07-26-22-03-51.87.png

truncate token name - exchange coin row

---

src/components/L2Disclaimer.js
src/screens/ExplainSheet.js
src/screens/SendConfirmationSheet.js

UI tweaks for some of the L2 screens.

@nico/l2 explainer sheet and send sheet fixes

---

ios/Gemfile.lock
ios/Podfile.lock
src/references/chain-assets.json

more optimism tokens

---

src/components/ContactRowInfoButton.js
src/components/coin-row/CoinRowInfoButton.js
src/components/coin-row/TransactionCoinRow.js
src/components/expanded-state/asset/ChartExpandedState.js
src/components/expanded-state/asset/SocialLinks.js
src/components/expanded-state/chart/ChartContextButton.js
src/components/expanded-state/swap-details/SwapDetailsContractRow.js
src/components/transaction-list/TransactionList.js
src/handlers/web3.js
src/helpers/transactionActions.js
src/references/index.ts
src/utils/ethereumUtils.js

we now change the text to match the block explorer per network. 
- cleaned up some logic
- added isTestnet helper function
Transaction Coin Rows: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-26-15-04-22.mp4
Chart Expanded State Menu: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-26-15-10-24.mp4
Exchange Info Button: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-26-18-09-05.mp4
Social Links: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-26-18-18-46.mp4

block explorers per network

---

src/components/exchange/ConfirmExchangeButton.js
src/hooks/useColorForAsset.js
src/screens/SendConfirmationSheet.js
src/screens/SendSheet.js

fixing a la @christianbaroni , need to handle other greyish tokens. will make a linear ticket
send: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-26-21-38-45.mp4
swap: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-26-21-43-06.mp4

fix eth color

---

src/components/coin-row/CoinName.js
src/components/coin-row/ExchangeCoinRow.js

I put the logic where it should be now 🙇

Fix CoinName regression

---

src/hooks/useExpandedStateNavigation.js

fix watch wallet alert

---

src/components/asset-list/RecyclerAssetList/index.tsx
src/redux/arbitrumExplorer.js
src/redux/fallbackExplorer.js
src/redux/optimismExplorer.js
src/redux/polygonExplorer.js

- Update redux when explorer data really changes
- Instead of doing deep comparisions with massive objects on the `rowHasChanged` function, created a custom comparison criteria for each type of row based focusing on the user facing info only.

Improve RecyclerAssetList re-rendering

---

src/model/wallet.ts
src/screens/TransactionConfirmationScreen.js

We were showing (AND USING!!!) the current selected account in the app (the global one) instead of the connected account to the dApp.
PoW:  https://recordit.co/cSypZ7trex

Fix selected account in wc request

---

src/screens/WalletConnectApprovalSheet.js

In wallet connect connection sheet, close change wallet sheet on wallet change
https://recordit.co/AzLno3K3W1

WC close wallet sheet on wallet change

---

src/redux/walletconnect.js
src/screens/WalletConnectApprovalSheet.js

PoW cold start & bg: https://recordit.co/wLt8MfIJp9

Fix WC connect sheet not showing on cold start

---

src/components/walletconnect-list/WalletConnectListItem.js
src/helpers/networkInfo.js
src/helpers/walletConnectNetworks.js
src/redux/arbitrumExplorer.js
src/redux/optimismExplorer.js
src/redux/polygonExplorer.js
src/screens/WalletConnectApprovalSheet.js

This will filter L2 networks in WC prompt for now

move l2 flags to networkInfo

---

src/components/sheet/sheet-action-buttons/DepositActionButton.js
src/components/sheet/sheet-action-buttons/WithdrawActionButton.js

reference: https://app.uniswap.org/#/add/v2/ETH/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9

fix pool links

---

src/handlers/deeplinks.js
src/redux/walletconnect.js
src/screens/ExplainSheet.js
src/screens/WalletConnectApprovalSheet.js

Add an explainer sheet when users wait up to 10 sec to get a connection request
https://recordit.co/7eKvucH42b

WC add explainer on connection timeout

---

package.json
yarn.lock

release: https://github.com/xmldom/xmldom/discussions/270
package is currently not being deployed to npm so we're pulling from github, I've flagged the issue and am watching the repo for any updates.

xmldom audit

---

src/components/discover-sheet/DiscoverHome.js
src/components/walletconnect-list/WalletConnectListItem.js
src/hooks/useWalletConnectConnections.js
src/redux/walletconnect.js
src/screens/ConnectedDappsSheet.js

Use connector peerId instead of dapp name to modify and disconnect sessions 
PoW https://recordit.co/UMt8jFhlAZ

WC update session and disconnect by peer id

---

src/components/expanded-state/asset/SocialLinks.js
src/hooks/useSwapAdjustedAmounts.ts
src/navigation/Routes.android.js
src/screens/SendConfirmationSheet.js
src/screens/SendSheet.js

fixes a few bugs and clean up ui to match ios 
feel free to push any tweaks 
ios before: https://cloud.skylarbarrera.com/IMG_0645.PNG
ios after:  https://cloud.skylarbarrera.com/Screen-Shot-2021-08-04-17-44-38.05.png
android before: https://cloud.skylarbarrera.com/Screenshot_20210804-173550.png
android after: https://cloud.skylarbarrera.com/Screenshot_20210804-173436.png

android send confirm sheet 

---

src/redux/walletconnect.js

Add clearTimeout to the WC timeout for explainer

WC clearTimeout when event received

---

src/components/change-wallet/AddressRow.js
src/components/contacts/ContactAvatar.js
src/components/contacts/ContactRow.js
src/components/contacts/ImageAvatar.js
src/components/contacts/showDeleteContactActionSheet.js
src/components/expanded-state/ContactProfileState.js
src/components/expanded-state/WalletProfileState.js
src/components/expanded-state/profile/ProfileAvatarButton.js
src/components/send/SendHeader.js
src/components/showcase/ShowcaseHeader.js
src/helpers/accountInfo.js
src/helpers/emojiHandler.js
src/hooks/useColorForAsset.js
src/model/migrations.js
src/screens/SendConfirmationSheet.js
src/utils/defaultProfileUtils.ts

Adds new color/emoji support for contacts. Fixes RNBW-1349.
PoW: https://www.loom.com/share/b6bbd49f6df7427eb3ffaca009081b34
Contacts stored as ens domains would stay in their letter form (as shown in the video by nico.eth) if the migration happens while the user is not connected to the internet.

@nico/avatars in contacts

---

src/helpers/walletConnectNetworks.js
src/screens/WalletConnectApprovalSheet.js

fixes some WC related crashes on android and cleans up existing UI issues
android before: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-08-19-25-40.90.png
android after:  https://cloud.skylarbarrera.com/Screen-Shot-2021-08-08-19-24-33.70.png
ios before: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-08-19-22-34.69.png
ios after: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-08-19-25-51.70.png

wc android cleanup

---

ios/TransactionListView.swift

Hide avatar context menu for now.

Hide context menu in TransactionListView

---

src/components/gas/GasSpeedButton.android.js
src/components/gas/GasSpeedButton.ios.js

PoW: http://recordit.co/cDueMWFdVL

fix l2 gas price formatting

---

src/components/settings-menu/SettingsSection.js

PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-10-11-57-12.mp4

fix threshold for scroll in settings

---

src/redux/arbitrumExplorer.js
src/redux/optimismExplorer.js
src/redux/polygonExplorer.js

- Changed from 30 to 60 seconds if no assets found
- Prevent fetching prices when no optimism assets found

Fix l2 polling frequency

---

src/references/chain-assets.json

Announcement: https://twitter.com/optimismPBC/status/1425168955983925250

Add USDC on Optimism

---

ios/Podfile.lock
src/components/coin-icon/ChainBadge.js
src/components/coin-icon/CoinIcon.js
src/components/transaction-list/TransactionList.js
src/components/transaction/sections/TransactionConfirmationSection.js
src/helpers/dappNameHandler.js
src/parsers/requests.js
src/redux/requests.js
src/screens/TransactionConfirmationScreen.js
src/utils/ethereumUtils.js

- Txs were never marked as confirmed when submitted via WC (missing provider!)
- Show chain's native asset amount and balance on WC tx prompt  (previously hardcoded to ETH)
PoW:  https://recordit.co/GmQmfpkev7

Fix WC + L2 bugs

---

ios/fastlane/Fastfile

https://app.bitrise.io/build/1705b22f-8d16-4a88-bbb9-7e4e51651153#?tab=log

fix testflight BS

---

src/components/coin-row/ExchangeCoinRow.js

https://cloud.skylarbarrera.com/Screen-Recording-2021-08-11-11-16-47.mp4

fix exchange align

---

src/components/send/SendHeader.js

Fix spinner showing even if we already have contact. Now it only queries for the address when we don't already have it.
Demo: https://www.loom.com/share/2c1aa2dc027646d2b1d9cdaa77eee5ba

Don't fetch ENS if we have contact

---

ios/fastlane/Fastfile

This reverts commit 62f1586e8266cdde537c7f86a783cb74f92cb8c4.

Revert "bump version by 2 (#2293)"

---

src/components/transaction/sections/TransactionConfirmationSection.js
src/handlers/assets.js
src/hooks/useGas.js
src/parsers/requests.js
src/redux/data.js
src/redux/fallbackExplorer.js
src/redux/gas.js
src/redux/polygonExplorer.js
src/redux/requests.js
src/screens/SendSheet.js
src/screens/TransactionConfirmationScreen.js
src/utils/ethereumUtils.js

- Fixes broken e2e
- Remove tiny badge from WC prompt
- Fixes wrong wallet balance in WC tx request for L2s
- Fixes wrong native asset calculations in WC tx request
- Fix flash /  jumping on WC requests
PoW: https://recordit.co/1kkGM8YAoE

Fix e2e and wc

---

src/redux/arbitrumExplorer.js
src/redux/data.js
src/redux/optimismExplorer.js
src/redux/polygonExplorer.js

Add missing network property

---

src/components/walletconnect-list/WalletConnectListItem.js

Adding a context menu on the network pill to be able to prompt the switcher on press.
PoW https://recordit.co/fbHnVKpTbD

Connected dapps network context menu

---

src/apollo/queries.js
src/components/contacts/ContactRow.js
src/components/send/SendContactList.js
src/screens/SendSheet.js

- updated query to pull in the resolving address
- changes the UI logic accordingly
- fixed sorting( we were calling an unnecessary function, we do all needed logic when we receive the query)
- bumped the # of domains we pull in to improve the results ( cut off was how many we need to pull in to get dame.eth to come up first when searching "dame"  = 75 )
avatar PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-12-19-26-10.mp4
search results PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-12-20-21-05.mp4

@skylar/got excited - ens search

---

ios/fastlane/Fastfile

update deprecated automatic_code_signing to update_code_signing_settings

Fastfile update

---

src/helpers/networkInfo.js

disabling until they stop whitelisting EOA's

disable arbitrum

---

src/components/settings-menu/SettingsSection.js
src/screens/ExplainSheet.js

settings: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-13-12-03-43.22.png

settings learn button + L2 explainer link

---

src/components/header/DiscoverHeaderButton.js

this is very nice to have, only works in dev mode
https://cloud.skylarbarrera.com/Screen-Recording-2021-08-11-23-54-34.mp4

dev connected dapps shortcut

---

src/redux/arbitrumExplorer.js
src/redux/optimismExplorer.js
src/redux/walletconnect.js
src/screens/WalletConnectApprovalSheet.js

- Fix disappearing optimism assets
- Clean up optimism explorer
- Fix broken switch network wc sheet
PoW: https://recordit.co/bXBXqgY5su

More l2 fixes

---

src/screens/ConnectedDappsSheet.js

way too smol: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-13-18-23-47.84.png
very nice: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-13-18-29-53.98.png

add height - connected dapps

---

src/redux/walletconnect.js

If there's an exception we're not clearing the timeout

WC connection failed sheet fix

---

src/parsers/transactions.ts
src/redux/data.js
src/screens/SpeedUpAndCancelSheet.js
src/screens/TransactionConfirmationScreen.js

- Pending L2 txs were dissapearing if we received txs from zerion (disconnect or sending a new one after) 
PoW: https://recordit.co/JnCH7cD9AU
- Speed up & Cancel wasn't working for L2s ( Polygon mostly )
PoW: https://recordit.co/gMgbSX3Ws4
- Speed up WC requests on L2 dapps
PoW: http://recordit.co/8yWDc4GoOQ
- Mainnet still works.
PoW: http://recordit.co/JjU30LSXOJ

L2 txs bugs

---

src/screens/WalletConnectApprovalSheet.js

quickswap: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-14-10-35-08.mp4
sushi eth + polygon: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-14-10-33-55.mp4
network switch request: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-14-10-32-31.84.png

fix wc network switcher

---

src/hooks/useUserAccounts.js
src/screens/SendSheet.js

we now prepend any watched addresses that fit the query and then dedupe. 
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-16-11-23-37.mp4
for recipient < 2: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-16-11-48-31.mp4

send - prioritize watched addresses

---

src/components/contacts/ContactRow.js
src/screens/SendSheet.js

- case insensitive
- checksum addresses for comparison
- handle ens vs named contacts
https://cloud.skylarbarrera.com/Screen-Recording-2021-08-16-18-22-13.mp4

send sheet - ens edge cases

---

src/components/expanded-state/WalletProfileState.js
src/screens/ChangeWalletSheet.js

Fixes RNBW-1469.
Before: https://www.loom.com/share/42d83da3367c4a58b69ce87f0cb7291b
After: https://www.loom.com/share/5985a866124146c8bffdc8ee0e4f843a

Pick up image for wallets not currently selected

---

src/screens/SendConfirmationSheet.js

Check against stored ENSs to fill in label in confirmation sheet for accounts where label is auto-filled from our stored ENSs. Fixes RNBW-1466.

send confirmation falls back on auto ENS

---

src/hooks/useWallets.js
src/screens/TransactionConfirmationScreen.js

PoW: https://recordit.co/ZLpjahbu9L

Switch wallets after submitting WC tx if needed

---

src/redux/data.js
src/redux/editOptions.js

We won't hide it if the user has it pinned.
PoW: http://recordit.co/a416SSME1S

Hide L2 assets with price = 0

---

android/app/src/main/AndroidManifest.xml
e2e/deeplinks.spec.js
e2e/init.js
ios/Rainbow/Info.plist
package.json
src/handlers/deeplinks.js
src/hooks/useScanner.js
src/screens/SendSheet.js
src/screens/ShowcaseSheet.js
src/utils/ethereumUtils.js
yarn.lock

- Adds support for `ethereum:` urls via deeplinks, app scanner, and phone camera app
- includes e2e tests for all scenarios including L2s
- Includes e2e tests for rainbow.me universal links
To test it use: https://brunobar79.github.io/eip681-link-generator

EIP-681 support + Deeplinks e2e

---

src/screens/TransactionConfirmationScreen.js

Fixes: https://sentry.io/organizations/rainbow-me/issues/1658399576/events/5c8152c382f64616bb7f7d3372741c59/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow%401.5.19%2B7+level%3Afatal&statsPeriod=24h
PoW: https://recordit.co/8nWQBsVVCm

Prevent crash if walletconnector not found

---

src/components/discover-sheet/DiscoverSearch.js

Remove unnecessary currencyList logic and fadein animation.

Remove logic / fadein animation

---

src/components/backup/BackupCloudStep.js
src/components/backup/BackupConfirmPasswordStep.js
src/components/backup/BackupManualStep.js
src/components/expanded-state/WalletProfileState.js
src/hooks/useImportingWallet.js
src/model/backup.ts
src/model/wallet.ts
src/raps/actions/swap.ts
src/screens/BackupSheet.js
src/screens/ChangeWalletSheet.js
src/screens/RestoreSheet.js
src/screens/WalletDiagnosticsSheet.js
src/screens/WalletScreen.js
src/screens/WelcomeScreen.js

Tracking and errors

---

src/hooks/useWebData.js

Dont try to update web profile on readonly wallets

---

.github/workflows/stale.yml

runs every monday, marks and notifies of stale issues

add stale issue notifier

---

src/components/unique-token/UniqueTokenImage.js

Fix remote svg boders

---

android/app/build.gradle
android/build.gradle
src/components/expanded-state/asset/ChartExpandedState.js

Closes https://linear.app/rainbow/issue/RNBW-1522/social-links-are-cut-off-if-phone-has-soft-menu

Fix social links are cut off if phone has soft menu

---

src/hooks/useWalletConnectConnections.js

check for undefined peerMeta on connection 
seems like is causing https://sentry.io/share/issue/da94538575d74259bf647f92e1ca2153/

WC add formatDappData safety check

---

README.md

First PR! 👋 Sorry it's not more exciting.

Fix React Native intro link in readme

---

src/components/coin-icon/CoinIcon.js
src/components/coin-icon/CoinIconGroup.js
src/components/discover-sheet/UniswapPoolsSection.js
src/hooks/useScanner.js

Fix choppy scrolling over pools. Only noticeable in iOS device (you can't see it in sim). Fixes RNBW-1443.

@nico/choppy scroll over discover pools

---

src/components/expanded-state/asset/ChartExpandedState.js

bug: asset balance on wallet change doesn't update

---

src/redux/data.js
src/screens/SpeedUpAndCancelSheet.js

This callback is not being used anywhere

remove callback when watching transactions

---

src/hooks/useWebData.js

Web data was not getting saved in firebase -- Fixes RNBW-1628.

Include wallets as param in findWallet func

---

package.json
src/handlers/gasPrices.js
src/handlers/opensea-api.js
src/handlers/wyre.js
src/model/preferences.ts
src/rainbow-fetch/index.js
src/redux/additionalAssetsData.ts
src/screens/ShowcaseSheet.js
yarn.lock

This replaces axios with a small wrapper that does roughly the same thing, relying on fetch internally.

Remove axios

---

src/model/migrations.js
src/utils/reviewAlert.js

we've been getting very little reviews so after talking with jackson and christian we've decided to ask users for a review again. This will coincide with a twitter push.

reset reviews timers

---

package.json
src/redux/data.js
yarn.lock

we can delete instead but figured hiding is better for now, we should ideally handle all of this on our backend.
PoW:
:

hide assets with url names

---

src/components/expanded-state/CustomGasState.js
src/components/expanded-state/custom-gas/FeesGweiInput.js
src/components/expanded-state/custom-gas/FeesPanel.js
src/components/expanded-state/custom-gas/FeesPanelTabs.js
src/components/expanded-state/custom-gas/index.js
src/components/expanded-state/index.js
src/components/fields/SmallBubbleField.js
src/components/fields/index.js
src/components/gas/GasSpeedButton.ios.js
src/components/gas/GasSpeedEmoji.js
src/components/gas/GasSpeedLabelPager.js
src/components/gas/GasSpeedLabelPagerItem.js
src/navigation/Routes.ios.js
src/navigation/routesNames.js
src/screens/ExchangeModal.js
src/screens/ExpandedAssetSheet.js
src/utils/gas.js

UI first pass. Todos (in order being worked on):

initial gas UI

---

android/app/src/main/java/me/rainbow/MainApplication.java
android/settings.gradle
ios/Podfile
ios/Podfile.lock
package.json
src/components/error-boundary/Fallback.tsx
src/components/settings-menu/DevSection.js
yarn.lock

Force-close app instead of restarting app in error boundary -- avoid some straggler native issues on restart.
PoW: https://www.loom.com/share/c4b254071889487c85389df17ef66add

@nico/close app error boundary

---

ios/TransactionListLoadingViewCell.xib

Think this fixes/removes this light background that sometimes shows behind the profile screen loading state

Fix profile screen shimmer background

---

src/components/savings/SavingsListRow.js
src/helpers/buildWalletSections.js
src/hooks/useSavingsAccount.js
src/hooks/useSendSavingsAccount.js
src/redux/arbitrumExplorer.js
src/redux/data.js
src/redux/fallbackExplorer.js
src/redux/optimismExplorer.js
src/redux/polygonExplorer.js
src/screens/SavingsSheet.js

Fixes for savings and cleanup

---

src/helpers/assets.js

PoW: ![Screen Shot 2021-09-27 at 10 20 49 AM](https://user-images.githubusercontent.com/29204161/134947461-25881d31-e8d6-4d38-bc62-5b2fab0d50b4.png)

nft family sorting tweaks

---

android/app/build.gradle
android/build.gradle
src/components/token-info/TokenInfoBalanceValue.js

Closes https://linear.app/rainbow/issue/RNBW-1544/balance-coin-icon-is-off-center

Fix balance coin icon is off center

---

ios/TransactionListView.swift

forgot to nil check 🙃 
PoW:
https://user-images.githubusercontent.com/29204161/135315927-ee6560d0-bbb3-4451-bd77-2ffc8e74ef3b.mp4

change wallet crash - nil check

---

src/components/asset-list/RecyclerAssetList/index.tsx
src/components/change-wallet/WalletList.js
src/components/discover-sheet/ListsSection.js
src/components/discover-sheet/UniswapPoolsSection.js
src/hooks/useUniswapPools.js
src/model/migrations.js
src/parsers/requests.js
src/redux/data.js
src/redux/imageMetadata.js
src/redux/uniswap.js
src/redux/userLists.js
src/redux/usersPositions.ts
src/screens/AddTokenSheet.js

Attempts to fix: https://sentry.io/organizations/rainbow-me/issues/2640349436/?environment=Release&query=is%3Aunresolved+release.version%3A1.5.25+react+crash&sort=user&statsPeriod=14d

Add optional chaining for obj.id in places that could cause a crash

---

src/components/svg/SvgImage.js
src/components/unique-token/UniqueTokenImage.js

Fixes: https://sentry.io/organizations/rainbow-me/issues/2645275365/?environment=Release&query=is%3Aunresolved+release.version%3A1.5.25+react+crash&sort=user&statsPeriod=14d
PoW: http://recordit.co/YRER6tp7ia

Fix NFTs + bad SVG crash

---

src/hooks/useSavingsAccount.js

I had done my fun changes only for the savings “accounts” tokens and not the default “dai market data” that we show when there are no savings but we still show the default "deposit dai" to the user

Apply new underlying price changes for DAI savings market when no savings in wallet

---

.gitignore
package.json

I also added the .eslintcache to the cache files

Add caching flag to eslint

---

src/components/change-wallet/AddressRow.js

fixes a small UI regression on iOS & some code 🤫 
PoW:

fix padding & ugly code

---

src/components/expanded-state/CustomGasState.js
src/components/expanded-state/custom-gas/FeesGweiInput.js
src/components/expanded-state/custom-gas/FeesPanel.js
src/components/gas/GasSpeedButton.android.js
src/components/gas/GasSpeedButton.ios.js
src/handlers/web3.js
src/parsers/gas.js
src/parsers/index.ts
src/raps/actions/depositCompound.ts
src/raps/actions/swap.ts
src/raps/actions/unlock.ts
src/raps/actions/withdrawCompound.ts
src/redux/gas.js
src/references/index.ts
src/screens/SendSheet.js
src/screens/SpeedUpAndCancelSheet.js
src/screens/TransactionConfirmationScreen.js

Send both legacy and EIP1559 transactions through send flow and wallet connect
Fixes RNBW-1667

eip 1559 send transactions

---

src/redux/requests.js
src/redux/walletconnect.js

- Added optional chaining
- Remove and disconnect connectors in bad state, no `peerMeta`
https://sentry.io/organizations/rainbow-me/issues/2672039238/events/a3ca4ad08fcb4b40b385b470d413a6c4/?project=1855565&query=is%3Aunresolved+level%3Afatal+user.ip%3A174.241.64.253&statsPeriod=14d

prevent crash on WC sessions updates

---

src/components/expanded-state/LiquidityPoolExpandedState.js

Before:
https://streamable.com/27n3gw
After:
https://streamable.com/2jsb0x
I think this works, but I have more than a strong feeling that the current construction of the bottom sheet is v fragile so I'd rather consider this as a temporary solution. In a long term, I believe we should rethink this whole concept
no linear ticket

Fix jumping of LP tokens in DS

---

src/handlers/opensea-api.js

classic opensea not telling us situation, key already added to bitrise
rinkeby: https://cloud.skylarbarrera.com/Screen-Shot-2021-10-28-14-20-49.95.png
mainnet: https://cloud.skylarbarrera.com/Screen-Shot-2021-10-28-14-21-20.17.png

fix testnet NFTs

---

src/helpers/dappNameHandler.js

PoW: https://cloud.skylarbarrera.com/Screen-Shot-2021-10-29-18-57-47.19.png

remove override

---

src/components/unique-token/UniqueTokenAttributes.js
src/components/unique-token/UniqueTokenCard.js
src/handlers/poap.ts
src/helpers/networkTypes.ts
src/parsers/index.ts
src/parsers/poap.js
src/redux/uniqueTokens.js

for QA, make sure you update scripts
https://cloud.skylarbarrera.com/Screen-Recording-2021-10-29-16-29-15.mp4

display poapz 

---

src/components/Tag.js
src/components/expanded-state/UniqueTokenExpandedState.js
src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
src/components/token-info/TokenInfoHeading.js
src/hooks/usePersistentAspectRatio.ts
src/utils/getDominantColorFromImage.js
src/utils/getLowResUrl.js

- fix info icon
- full width action button
- center file image
- fix blur wrapper for sheet
- consistent vertical padding w/ ios
- fix low res image util
- fix aspect ratio calculation state
- fix dominant color on android
- fix share menu
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-11-04-15-38-02.mp4
- add android option menus
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-11-04-16-03-46.mp4
Android TODO:
- We need to check the existence of links for the context menus and change the options accordingly
- We need to fix android permission flow for saving images(currently does not work)

nft v2 clean up and android fixes

---

src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js

https://cloud.skylarbarrera.com/Screen-Recording-2021-11-05-17-39-39.mp4
QA: android family menu should adjust based on what options are available

check existence for collection links on android

---

src/apollo/queries.js
src/handlers/uniswap.ts
src/redux/uniswap.js

This reverts commit 77389df7bc26908746a1b84107e02da6ac190ba6.

Revert "uniswap tokens by volume (#2395)"

---

src/helpers/support.js

fix typo : ocurred -> occurred

---

e2e/deeplinks.spec.js
e2e/hardhatTransactionFlow.spec.js

We were calling `.tap` instead of `waitAndTap` but CI is slow most of the times.

Fix hardhatTransactionFlow flakiness

---

e2e/hardhatTransactionFlow.spec.js

Disable sad tests

---

android/app/src/main/java/com/swmansion/gesturehandler/react/RNZoomableButtonManager.java
src/components/context-menu/ContextMenu.android.js
src/screens/ExplainSheet.js

- Fix horizontal alignment on android explainer sheets
- not sure why we had animated button in an android action sheet https://github.com/rainbow-me/rainbow/compare/@esteban/some-android-bugs?expand=1#diff-5b7c089842857bffccb0c53f206cc6d340771e0841eb1219ac0e86dec0e15d1bR56 it was causing issues on all places this component was in
- some places where the `RNZoomableButtonManager` was being used was triggering the `onPress` callback twice, setting`mIsTaskScheduled` to false immediately after the event was triggered from the native context fixed it
Video of the bugs on https://linear.app/rainbow/issue/RNBW-1852/android-explain-sheet-got-it-and-showactionsheetwithoptions
Fixes RNBW-1852

some android bugs

---

src/components/expanded-state/asset/ChartExpandedState.js
src/redux/data.js

fixes 2 issues:
scam filtering wasnt working, not it does
ogAssets which we use to check if we should show swap - mainnet assets had an undefined address

@skylar/fix bruno ish

---

src/components/coin-row/CoinRowInfoButton.js
src/components/coin-row/ExchangeCoinRow.js
src/components/expanded-state/asset/ChartExpandedState.js
src/components/expanded-state/asset/SocialLinks.js
src/components/expanded-state/chart/ChartContextButton.js
src/helpers/assets.js
src/model/migrations.js
src/parsers/accounts.js
src/redux/data.js
src/screens/SendSheet.js
src/utils/ethereumUtils.js

- Fixes the dupe L2 balances on sendsheet
- Removes etherscan link for ETH
- Updates other places where we used uniqueId instead of addresses: 
- Chart Context Menu
- Coin Row Info Button on discover search

Fix uniqueId usage

---

package.json
yarn.lock

bump json-schema

---

src/redux/fallbackExplorer.js

PoW http://recordit.co/mAKYnU54JP

Fix ETH balance

---

src/redux/fallbackExplorer.js

ignore covalent mainnet prices

---

src/components/add-cash/AddCashForm.js

i think throwing 2 errors is too much, lmk if we disagree

add purchasing alert for purchases  < 50

---

src/handlers/covalent.ts
src/redux/data.js

We were accidentally hiding ALL the assets with price = 0
PoW: http://recordit.co/TEaRFfYAPl

Fix incorrect asset hiding

---

src/redux/settings.js

fixes RNBW-1900
POW: https://cloud.skylarbarrera.com/Screen-Shot-2021-11-23-15-41-20.92.png

add currency + language to user identity

---

src/references/chain-assets.json

This is temporary until we consume directly from https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/optimism.tokenlist.json
You can compare addresses, names, symbol and decimals with the link above

Add more optimism tokens

---

src/redux/data.js

PoW: <img width="391" alt="Screen Shot 2021-11-24 at 7 28 26 PM" src="https://user-images.githubusercontent.com/1247834/143329189-b0964af2-882f-4f45-83aa-eba374a9231b.png">

Fix pool balances

---

src/entities/transactions/transaction.ts
src/parsers/newTransaction.ts
src/screens/SendSheet.js
src/screens/SpeedUpAndCancelSheet.js

PoW: http://recordit.co/6hdS9dukpl

Store txTo in tx obj

---

android/app/build.gradle
package.json

idk how i keep forgetting to remove the update token list BS so we removing as we dont need
github god's pls merge on review

bump android

---

src/components/svg/SvgImage.js

lmk if there's any more but according to https://developer.mozilla.org/en-US/docs/Web/API/Window we should be covered now
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-12-02-16-17-08.mp4

overload problematic window functions

---

src/components/Spinner.js
src/screens/TransactionConfirmationScreen.js

Includes:
1. Android fixes
2. WaleltConnect bignumber issues

Bruno's speed up and cancel fixes

---

e2e/swapSheetFlow.spec.js
src/components/expanded-state/CustomGasState.js
src/components/expanded-state/custom-gas/FeesGweiInput.js
src/components/expanded-state/custom-gas/FeesPanel.js
src/components/expanded-state/custom-gas/FeesPanelTabs.js
src/components/expanded-state/custom-gas/GweiInputPill.js
src/components/gas/GasSpeedButton.js
src/helpers/gas.ts
src/utils/gas.ts

This is just here to confirm my rebase of Christian's branch over develop didn't miss anything - once good by Christian and Esteban, I can force push over Christian's original branch and we can continue the PR review there and close this one.

@jin/christian 1559 polish rebase

---

src/components/expanded-state/custom-gas/FeesPanel.js
src/components/gas/GasSpeedButton.js
src/navigation/config.js
src/screens/ExplainSheet.js

Fixes RNBW-1965 , RNBW-1938 , RNBW-1932
added the passing of network name to the explain sheet for use in the gas explainer.
added a BPA to the trend element so it opens the explainer
fixed a bug where if you opened miner tip or base fee it would switch to the current base fee explainer
tweaked heights for miner tip + base fee
https://cloud.skylarbarrera.com/Screen-Recording-2021-12-07-16-11-57.mp4
explainers should work as expected

eip-1559 explainer clean up + bug fixes

---

src/redux/gas.ts

Fixes RNBW-1947
Two things:
- When new price info data came to the app we were only updating some parts of the state `currentBlockParams`, `confirmationTimeByPriorityFee` and `gasFeeParamsBySpeed` but we needed to update the rest of the params as `selectedGasFee` and `gasFeesBySpeed` which are handled by `gasUpdateTxFee`. 
- I'm now saving the `gasLimit` param in state, before I wasn't using the right value, which is `updatedGasLimit || gasLimit || defaultGasLimit`
I wanted to do this in only one `dispatch` so i moved the logic to an aux method called `getUpdatedGasFeeParams` 
https://recordit.co/BFW7ncHksv
All views gas fees are being updated correctly

Fix gas fees not updating on fees panel

---

src/entities/index.ts
src/entities/userLists.ts
src/raps/actions/depositCompound.ts
src/raps/actions/swap.ts
src/raps/actions/unlock.ts
src/raps/actions/withdrawCompound.ts
src/redux/settings.ts
src/redux/userLists.ts
src/redux/web3listener.ts
src/references/index.ts

Here is some initial work on converting some files to TypeScript. I based most of the changes off of the patterns I saw in #2495.
As far as I can tell, these changes don't break any `yarn lint` rules, but it's definitely possible I'm missing something!

Update `userLists`, `web3listener`, and `settings` Redux files to use TypeScript

---

src/redux/gas.ts

not sure what happened here but this is wrong so removingh it

l1GasFeeOptimism in wrong place

---

src/App.js

Safely turn off tokenlist listener
none

Fix crash unmount

---

src/redux/gas.ts

Fixes error that was merged into develop

Fix: l1 gas fee optimism in wrong place

---

src/parsers/poap.js

forgot a commit in my poap branch, this change matches up with the website so img sharing works as intended
https://cloud.skylarbarrera.com/Screen-Recording-2021-12-12-22-49-08.mp4

fix poap uid and tweak image size

---

src/components/expanded-state/custom-gas/FeesPanel.js
src/components/expanded-state/custom-gas/GweiInputPill.js

Fixes RNBW-2022
Fixes RNBW-2026
Using same text mask input that we use on exchange
Using flex 1 did the trick to display the caret on the input (RNBW-2026)
https://recordit.co/SVERVQmsr2

fee panels input sanitize numbers and fix focus

---

src/components/expanded-state/custom-gas/FeesPanel.js

remove number rounding on miner tip and max base fee
related to https://linear.app/rainbow/issue/RNBW-2023/input-number-rounding-shouldnt-happen-till-input-loses-focus waiting for confirmation

fees panel remove input rounding

---

src/components/gas/GasSpeedButton.js

- Context manu showing `estimated gwei - max gwei` per speed
- selecting custom from context menu sends you to custom in the fees panel
https://recordit.co/qdTNXSqTRx

fees panel context menu improvements

---

package.json
patches/@gorhom+bottom-sheet+4.1.5.patch
src/components/discover-sheet/DiscoverSheet.android.js
src/components/discover-sheet/DiscoverSheetHeader.js
yarn.lock

Fixes RNBW-1977
I patched the library to accept `onScroll` worklet. The close should express clearly my idea.

Add animated background for "back" and "scanner" buttons just like on iOS

---

src/components/expanded-state/custom-gas/GweiInputPill.js

remove workaround to make the cursor appear 

remove delay on input

---

src/components/expanded-state/CustomGasState.js
src/components/expanded-state/custom-gas/FeesGweiInput.js
src/components/expanded-state/custom-gas/FeesPanel.js
src/components/expanded-state/custom-gas/GweiInputPill.js
src/components/gas/GasSpeedButton.js
src/components/gas/GasSpeedEmoji.js
src/components/send/SendAssetFormToken.js
src/screens/ExplainSheet.js

Fixes RNBW-1998
- the iOS styling really messed with android, android inputs are prob one of the most finicky things IMO. I changed the new styles to only be applied for iOS 
- tweaked a bunch of other stuff as well
https://cloud.skylarbarrera.com/Screen-Recording-2021-12-14-08-35-20.mp4

android eip-1559 polish

---

src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
src/components/expanded-state/unique-token/saveToCameraRoll.js

Fixes RNBW-2002, RNBW-2010
RNBW-2002: Added alert modal subtext for trying to access photo library after permission was denied by user.
RNBW-2010: Increased label (ChartPriceLabel) width for charts expanded state
RNBW-2002: 
https://user-images.githubusercontent.com/15272675/146126931-b9402099-ccf0-45cc-a6ee-c41e6692e42a.mp4
RNBW-2010:

@benisgold/android UI fixes

---

src/hooks/useCurrentNonce.ts
src/screens/SendSheet.js
src/screens/TransactionConfirmationScreen.js

Fixes RNBW-2052
we were not using the currentNetwork but whatever network the app was set to 
https://cloud.skylarbarrera.com/Screen-Shot-2021-12-15-22-49-55.60.png
Please test sending on L2s and confirm the txn nonces behave as expected and that the insufficient ETH error doesn't show up

fix insufficient eth label bug

---

src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx

Let's check if this will get better on Testflight lol 

Reduce renderAheadOffset on ios

---

src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts

Fixes RNBW-2058
I forgot to filter them out from the list, sorry! Now they should be removed from the list if are inside hidden list.
Additionally, I fix a minor bug not to display coin divider if there's nothing below 

Hide hidden coins

---

src/components/fields/BubbleField.js
src/components/send/SendAssetForm.js
src/components/send/SendAssetFormField.js
src/components/send/SendAssetFormToken.js
src/hooks/index.js
src/hooks/useSendSheetInputRefs.ts
src/screens/SendSheet.js

Fixes RNBW-2045
I added proper input focusing, this was broken already but was a lot more noticeable after adding the custom gas sheet
https://cloud.skylarbarrera.com/Screen-Recording-2021-12-16-18-47-14.mp4

fix send sheet focus handling

---

src/parsers/uniqueTokens.js
src/redux/uniqueTokens.js

Fixes RNBW-2072
some mainnet poaps we're not being filtered out, now we just filter them all out and use the poap endpoint
https://cloud.skylarbarrera.com/Screen-Shot-2021-12-16-14-05-17.18.png

tweak poap filtering

---

patches/@gorhom+bottom-sheet+4.1.5.patch
src/components/discover-sheet/DiscoverSheet.android.js

Fixes RNBW-2079
I remained the prop name to avoid collisions 

Fix patch in @gorhom/bottom-sheet

---

src/redux/walletconnect.js

This fixes the issue when the QR code scanner or some mechanism upstream calls `walletConnectOnSessionRequest` twice with the same walletconnect URI. When this happens, we do connect initially, but the second attempt will fail and display an error. We should not show any connection failed message in these instances because we're actually already connected.
The app will *and should* still show connection failed messages when:
- The QR code was already consumed and we no longer have an active session
- WalletConnect bridge servers are actually having issues
To reproduce the bug with develop or what's in production:
1. Go to any Dapp and start the WC flow
2. Take a screenshot of the QR code
3. Connect via WC using the Rainbow QR code scanner
4. Confirm successful connection (should show `1 …

Don't initiate a new WalletConnect session using an existing URI

---

src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts

Fixes RNBW-2080
The code is obvious

Hide nfts' header if no nfts

---

src/components/fields/BubbleField.js
src/hooks/useInitializeWallet.js
src/screens/CurrencySelectModal.js
src/screens/SendSheet.js

- Fixes current linting errors and warnings
Nothing

Fix linting errors

---

src/components/coin-divider/CoinDividerOpenButton.js

Removes red background on the All/Less button
before and after:

Remove red All/Less button background

---

src/screens/WalletConnectApprovalSheet.js
src/utils/ethereumUtils.ts

we we're showing the wc request network but in this case we want to show the network they are switching to 
casting chainId to number following: https://github.com/rainbow-me/rainbow/pull/2688
https://cloud.skylarbarrera.com/Screen-Shot-2021-12-16-12-13-07.01.png

fix display for network change requests

---

src/handlers/dispersion.ts
src/hooks/useUniswapCurrencyList.ts
src/utils/uniswapAssetsCache.ts

- Added cache for getUniswapTokens
- Added useCallback / useMemo inside useUniswapCurrencyList

improvements

---

ios/PriceWidget/Base.lproj/SelectTokenIntent.intentdefinition
ios/PriceWidget/English.lproj/SelectTokenIntent.strings
ios/PriceWidget/en.lproj/SelectTokenIntent.strings
ios/Rainbow.xcodeproj/project.pbxproj

We're getting an error from the AppStore after submitting a testflight build because we're missing some required descriptions. This PR fixes it
`ITMS-90626: Invalid Siri Support - Localized description for custom intent: 'SelectToken' not found for locale: en`

Fix localization warning

---

src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js

Fixes RNBW-2124
I realized that previously we were:
- immediately overriding `defaultValue` with `useEffect` (https://github.com/rainbow-me/rainbow/pull/2596/files#diff-9e38c4c350fb481bfc4462ab0f92f8385a2e948d50e9fef14ef66d9bec24e911L73).
- Hence, `overrideValue` was ignored.
I decided to simplify this logic. Also, `format` is not called every time (only for the default value, and then while scrubbing) .  
https://streamable.com/cs32rp

Default 1D % change in charts

---

src/helpers/buildWalletSections.js

I added more 💀 so it looks better when loading
before: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-04-13-12-41.mp4
after: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-04-17-35-58.mp4

add skeletons to loading state

---

src/screens/ExchangeModal.js

Fixes RNBW-2152
Quick fix for the gas button being cut off on iPhone 7
Before:
After:

Fix iPhone 7 swap gas button

---

e2e/hardhatTransactionFlow.spec.js
src/components/transaction/TransactionMessage.js
src/parsers/requests.js
src/screens/TransactionConfirmationScreen.js
src/utils/signingMethods.ts

We have to enable this to add compatibility for dapps following outdated practices.
[Video](https://recordit.co/fCr1fNgHzL)
List any NFT for sale on looksrare.org

Enable signTypedData_v4

---

ios/fastlane/Fastfile

We never told `match` we have new targets  😅

add new targets to fastlane match config

---

src/components/expanded-state/asset/ChartExpandedState.js

adding option chaining after the split to fix this crash:
https://sentry.io/organizations/rainbow-me/issues/2557756854/?project=1855565&query=user.ip%3A24.193.31.13&statsPeriod=14d

add optional chaining

---

package.json
yarn.lock

auditdotme
added mocha as it was breaking linting
e2e should pass 

auditdotme - markdown-it & follow-redirects

---

src/hooks/useUniswapAssetsInWallet.js

Very simple improvement to the `useUniswapAssetsInWallet` to reduce some calls to the filtering by using memoization / callbacks.
Confirmed less spinning of wheels in console logs when opening CurrencySelectionModal as well as the ChartExpandedState.
Confirm CurrencySelectionModal in swap and ChartExpandedState behave as expected.
[X] Assigned individual reviewers?
[X] Added labels?

useCallback and useMemo in useUniswapAssetsInWallet

---

src/components/discover-sheet/DiscoverSearch.js
src/components/discover-sheet/DiscoverSearchContainer.js
src/components/showcase/ShowcaseHeader.js
src/screens/ShowcaseSheet.js

Fixes RNBW-2158
fixes one case related to RNBW-1615
added input handling logic for navigation to the showcase sheet & importing wallet  
https://cloud.skylarbarrera.com/RPReplay_Final1641591422.MP4
Make sure Search Input handling works as expected, after importing a wallet keyboard should be dismissed & swiping to other screens should work properly

showcase sheet behavior fixes

---

src/handlers/dispersion.ts
src/handlers/tokenSearch.ts
src/hooks/useAdditionalAssetData.ts
src/hooks/useUniswapAssetsInWallet.js
src/hooks/useUniswapCurrencyList.ts
src/utils/uniswapAssetsCache.ts

Tweaks for API changes that should not directly affect functionality.
What to test:
- token search on discover and swap
- CurrencySelectModal by default shows uniswap assets in wallet
- ensure normal behavior on chart expanded state (swappable assets have a swap button)

[RNBW-2220] v2 tokens array -> map and token search versioning

---

src/components/add-cash/AddCashForm.js

Fixes RNBW-2165
switched the order

add cash - swap logic to show watching alert over < $50

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/pull_request_template.md

Trying to tick off the checklist didn't work because of the lack of bullets, so I fixed it.

Fix checklist formatting in PR template

---

src/components/coin-row/TransactionCoinRow.js

Fixes RNBW-2319
default behavior was wrong, etherscan button should open link, pressing off the menu should close
coming soon ™️

fix android tx menu - default behavior

---

src/components/send/SendAssetList.js

Fixes RNBW-2279
id imagine from the asset list changes, just added option chaining which should be fine 
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-20-at-2.20.34-PM.mov

send smol balances optional chaining

---

src/App.js
src/hooks/useCurrentNonce.ts
src/screens/TransactionConfirmationScreen.js

Fixes RNBW-2314
nonce was getting called w no address
also removed an xtra old alert (see video )
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-20-23-40-07.mp4

fix wc crash

---

src/handlers/opensea-api.ts

we're using a proxy now ty @welps 
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-26-10-50-22.mp4
nft's and floor price data should show up

new NFT keys + fix ts warnings

---

ios/Images.xcassets/transactions/icons/contractInteraction.imageset/Contents.json

Not sure why we removed this file in https://github.com/rainbow-me/rainbow/pull/2818/commits/07b67d239d8f46a7b09348a5c28fa863031cf337 but it was causing the icon to disappear
Is back again

add contractInteractions Contents.json again

---

README.md

Just noticed there is no link to Android.

Android beta link in Readme

---

src/components/header/DiscoverHeaderButton.js
src/components/profile/AvatarCircle.js
src/components/profile/ProfileMasthead.js

Fixes RNBW-2253
Fixed shadows
Before:
After:
See layouts

Fix shadows in Discover button and Avatar Circle

---

src/components/exchange/ExchangeInputField.js
src/components/exchange/ExchangeOutputField.js
src/screens/ExchangeModal.js

Fixes RNBW-2221
output input was focusable when it shouldn't be, added the logic and tweaked the inputCurrency to follow the same 
before: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-20-16-25-21.mp4
after: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-20-16-24-57.mp4

disable output currency focus

---

tsconfig.json

was exported twice and linter was complaining

fix styled-components ts alias

---

src/helpers/ens.ts
src/redux/ensRegistration.ts

Fixes RNBW-2353
Added a new redux file to handle the state of a registration process.
Also added fixed records the ens app has right now, we'll need to add `cover` and `pfp`  when we add support for it

@esteban/ens state manager

---

package.json
yarn.lock

audit - bump follow-redirects

---

src/screens/ENSAssignRecordsSheet.js

Fixes a small issue where the keyboard toggle button wasn't showing on android.

Profiles: Fix issue where keyboard toggle wasn't showing on android

---

src/screens/WalletConnectApprovalSheet.js

Fixes RNBW-2514
As @ibrahimtaveras00 pointed out in #2915, wallet name is being truncated in approve modal (issue for both iOS and Android).
I switched to text component from design system as it handles truncated text my better (otherwise dots on android are randomly cut without any control over it), but I didn't want to rewrite whole component with the new design system primitives.

Truncate wallet name in WC approval

---

src/screens/TransactionConfirmationScreen.js

Fixes RNBW-2532
This PR fixes wallet name not being truncated in tx request screen. See: https://cloud.skylarbarrera.com/Screen-Shot-2022-02-11-13-50-58.57.png.
Transaction request screen should have too long wallet name truncated.

Fix truncated wallet name on tx request screen

---

src/components/backup/BackupCloudStep.js

fixes RNBW-2457
we just needed to blur the inputs before navigating to the explain sheet

blur inputs for android cloud back up 

---

package.json
yarn.lock

Audit: bump `url-parse`

---

src/config/experimental.ts
src/helpers/ens.ts
src/navigation/Routes.android.js
src/navigation/Routes.ios.js
src/raps/actions/ens.ts
src/redux/ensRegistration.ts
src/references/ens/index.ts
src/references/index.ts
src/screens/ENSConfirmRegisterSheet.js
src/screens/ENSSearchSheet.js
src/screens/WalletScreen.js

Just review comments from main ens profiles branch

@esteban/ens profiles review comments

---

package.json
src/handlers/ens.ts
src/helpers/ens.ts
src/hooks/useENSRegistration.ts
src/hooks/useENSRegistrationCosts.ts
src/raps/actions/ens.ts
src/references/time-units.json
src/screens/ENSConfirmRegisterSheet.js

More comments on main profile PR

@esteban/more comments review

---

src/components/RadialGradientBackground.tsx
src/components/buttons/TintButton.tsx
src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
src/components/ens-registration/SearchInput/SearchInput.tsx
src/components/ens-registration/SearchResult/SearchResultGradientIndicator.tsx
src/components/ens-registration/TextRecordsForm/SelectableButton.tsx
src/components/inputs/InlineField.tsx
src/navigation/RegisterENSNavigator.js
src/screens/ENSAssignRecordsSheet.js
src/screens/ENSConfirmRegisterSheet.js

Addressing Bruno's PR comments on `@jxom/register-ens`

Register ENS: Inline style optimisation & PR comments

---

src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
src/components/gas/GasSpeedButton.js
src/screens/ENSConfirmRegisterSheet.js

Fixes RNBW-2600
- applied accent color to commit button and gas speed button

@benisgold/apply accent color

---

src/hooks/useENSProfileForm.ts

@jxom/ens-form-onchange

---

src/components/expanded-state/unique-token/ZoomableWrapper.js

Fixes RNBW-2680
I bisected and made random changes 
https://streamable.com/fs6rnz
check double tap

Fix NFT double tap to zoom no longer zooms to tapped coordinates

---

package.json
yarn.lock

something something ci happy world saved funds secured

Bump url-parse

---

src/components/fab/RegisterEnsFab.js

Fixes RNBW-2599
- Restrict user from entering ens profile registration flow if the current wallet is read only
https://user-images.githubusercontent.com/15272675/156249339-ee421e0c-1bf1-4238-b0f4-112718026297.mp4

@benisgold/restrict watching wallets

---

src/components/settings-menu/SettingsSection.js

Fixes RNBW-2746
only tested with dev flag on so we missed this smol change

fix visibility for dev settings

---

src/components/ens-registration/Cover/Cover.tsx
src/styles/colors.js

Just a couple of small fixes for dark mode:
- Making cover placeholder colors better for dark backgrounds
- Added placeholder color for text input

Profiles: Dark mode fixes for ENS registration

---

audit-ci.json

Fix audit again

---

audit-ci.json
src/components/expanded-state/unique-token/ZoomableWrapper.android.js

Fixes RNBW-2777
sorry 😓 
it's trivial

Remove blue background

---

src/handlers/ens.ts

Fixes RNBW-2760
- Implemented method that returns an address's reverse record ens, or an empty string if unavailable.

@benisgold/reverse record check

---

src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
src/handlers/web3.ts
src/helpers/ens.ts
src/hooks/useENSRegistrationActionHandler.ts
src/hooks/useENSRegistrationCosts.ts
src/languages/_english.json
src/screens/ENSConfirmRegisterSheet.js
src/screens/ENSSearchSheet.js

Fixes RNBW-2609
Fixes RNBW-2753
Fixes RNBW-2787
Added different components for each of the registration flows, we just need the animations now so I didn't put effort on the UI and added a simple loader
Added ability to send or not a reverse record tx, it will default to true only if the user doesn't have a reverse record already
Updated registration cost panel to latest design
https://recordit.co/dE2EYtj9Ou

profiles: two step flow screens & reverse records

---

src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
src/components/expanded-state/unique-token/ZoomableWrapper.android.js

Fixes RNBW-2777
MP3 nfts are no longer zoomable. It was not working on Android (and on iOS also this was not having an impact - and sense too).
Also, I fixed `ZommableWrapper.android.js`
https://streamable.com/jja2de
wallet = melvv.eth
NFT = Daniel Allan Overstimulated (EP) # 33

Fix mp3 nft

---

src/components/walletconnect-list/WalletConnectListItem.js
src/helpers/time.js
src/hooks/useWalletConnectConnections.js
src/screens/ConnectedDappsSheet.js

Fixes RNBW-2070
- ~~Added a timestamp to show the latest handshake with dapp~~
- Changed list sorting to be by most recent handshake
- Fixed L2 icon alignment on Android
- Fixed wallet icon shadow clipping at the bottom of the list on Android
- Fixed margin mismatch between Android and iOS
- Fixed name truncating for long wallet and app names
The order is properly sorted by most recent.
|  Before  |  After: Android  | After: iOS | After: iOS cont. |
|----------|------------------|------------|------------------|
| ![Screenshot_20220314-020831](https://user-images.githubusercontent.com/6843656/158088838-0daa3e44-da32-42d6-95e6-061e863e29e9.png) | ![Screenshot_20220316-180017](https://user-images.githubusercontent.com/6843656/158646983-5d21fa10-f954-4756-b19c-eb40534af8a9.png) | …

Sort connected dapps by most recent handshake

---

src/components/inputs/InlineField.tsx

Fixes RNBW-2789
- set fixed width for inline field to fix this bug. also disabled scrolling to make the text not jump every new line (ios fix only)

@benisgold/fix multiline spillage

---

audit-ci.json

- Reverts `ws` to use specific ids for reasons already discussed
- No
- Should pass CI

Revert audit-ci changes

---

src/hooks/usePersistentAspectRatio.ts
src/hooks/usePersistentDominantColorFromImage.ts

Fixes RNBW-2871
we handle undefined images fine for out image handling but mmkv doesn't like undefined keys so I've added a default case 
https://cloud.skylarbarrera.com/Screen-Recording-2022-03-20-12-37-48.mp4

handle null images

---

src/components/expanded-state/asset/ChartExpandedState.js

Fixes RNBW-2838
we we're getting a string of spaces but no real text so we're sanitizing for our logic check
https://cloud.skylarbarrera.com/Screen-Shot-2022-03-18-12-37-35.36.png
open DSD and make sure there's no description

sanitize expanded state description

---

src/model/migrations.ts

This reverts commit c9215369a0d348d58c53e9563043d74cd1dd0f9c.

Revert "Clean MMKV AspectRatio / dominant color (#3070)"

---

src/hooks/usePersistentAspectRatio.ts
src/hooks/usePersistentDominantColorFromImage.ts

fixes bad default logic, no need to migration
https://cloud.skylarbarrera.com/Screen-Recording-2022-03-22-11-30-57.mp4

fix bad default logic

---

src/components/ens-registration/RegistrationCover/RegistrationCover.tsx

Fixes RNBW-2876
Add ability to crop cover photo on upload

Profiles: Crop cover photo

---

ios/PriceWidgetExtension.entitlements
ios/Rainbow/Rainbow.entitlements
ios/Rainbow/RainbowDebug.entitlements
ios/Rainbow/RainbowRelease.entitlements
ios/SelectTokenIntent/SelectTokenIntent.entitlements
src/redux/settings.ts

Reverts rainbow-me/rainbow#3058 Temporary reverting this one to see if it solves the issue

Revert "@benisgold/widget regression fixes"

---

src/redux/data.ts

Lowercase addresses when doing comparison for address assets received

---

src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
src/components/inputs/InlineField.tsx
src/screens/ENSAssignRecordsSheet.js
src/screens/ExplainSheet.js

Exploring w/ adding a simple explainer sheet that pops up on first field focus... 
Copy might need some tweaking.
https://www.loom.com/share/26a5b4d1924643008dae175e16b04463

Profiles: On-chain text records data warning

---

src/hooks/useENSRegistrationCosts.ts
src/languages/_english.json
src/screens/ENSConfirmRegisterSheet.js

Fixes RNBW-2845
Add sufficient ETH validations to pay
- Total registration cost when starting the registration, network fee of up to 4 tx + rent price plus a buffer of 10%
- Network fee validation for each step
https://recordit.co/BVLeJDO1iw

Profiles: check enough eth for registration

---

package.json
yarn.lock

Fix plist and minimist

---

e2e/registerENSFlow.spec.js

I messed up the e2e with my last PR, this fixes it

Profiles: fix e2e

---

src/hooks/useOnAvatarPress.ts
src/languages/_english.json

Fixes RNBW-2880
On android we weren't using new profiles sheets, now we're doing the same than android
https://www.loom.com/share/96e5751335464a749fa0ee6e2740c0ba

Profiles: go to profile on avatar press android

---

src/model/migrations.ts

- Migration 13 was reading the keys to migrate from the keychain, causing an unwanted user auth when launching the app
- Migration 14 was broken (passing an object instead of the actual address)
If you run the app import a wallet, then delete the app and install it again, you shouldn't see face ID (or whatever user auth you have set) on iOS.

Fix migrations 13 and 14

---

.github/pull_request_template.md

Just tweaking the PR template to ask about tests

Where are your tests?

---

.github/pull_request_template.md

Reminder of updating CODEOWNERS when new files are added

---

src/hooks/useENSRegistrationForm.ts

Fixes RNBW-3110
Fixes an issue noticed in QA where the ENS avatar disappeared when updating ENS profile. Turns out it is a simple fix.

Profiles: Fix issue where ENS avatar was disappearing when updating profile

---

src/hooks/useENSRegistration.ts
src/hooks/useENSRegistrationActionHandler.ts
src/hooks/useSelectImageMenu.tsx

Fixes RNBW-3107
Fixing issue where a user could not upload ENS photos on Android

Profiles: Fix issue where couldn't upload photos on android

---

src/components/expanded-state/UniqueTokenExpandedState.tsx
src/screens/ENSConfirmRegisterSheet.js

Fixes RNBW-3111
Send user to Profile screen after editing

Profiles: QA send user after editing

---

src/screens/ENSSearchSheet.js

Fixes RNBW-3189
This PR adds ability to persist ENS search value between screens
https://www.loom.com/share/cbf2b8f556ee482eb23ad006ac205190

Profiles: Persist search value between ENS registration screens

---

src/screens/ENSAssignRecordsSheet.js

Fixes RNBW-3195
Pick color from avatar
https://user-images.githubusercontent.com/12115171/162080916-b1bd0889-4aec-4cb2-b002-4bc336ba23a8.mp4

Profiles: grab accent color from avatar in edit

---

src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
src/components/expanded-state/UniqueTokenExpandedState.tsx
src/hooks/useENSRegistration.ts
src/hooks/useENSRegistrationForm.ts
src/hooks/useSelectImageMenu.tsx
src/languages/_english.json

Fixes RNBW-3188
Adds ability to remove ENS image records (avatar & cover photos)
https://www.loom.com/share/48a8ca5f187f48d48de904a5c53e32d7

Profiles: Add ability to remove ENS image records

---

src/hooks/useENSRegistrationActionHandler.ts

Logging image upload errors to sentry

Profiles: Log upload image errors

---

e2e/registerENSFlow.spec.js
src/components/buttons/TintButton.tsx
src/handlers/localstorage/accountLocal.ts
src/helpers/ens.ts
src/languages/_english.json
src/screens/ENSConfirmRegisterSheet.js

Addressing all comments left on profiles PR

Profiles: phase two final review comments

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump for android and ios.
CHANGELOG for last release which was minor mostly bug fixes and improvements.

Bump ios and android version; update CHANGELOG

---

src/components/unique-token/UniqueTokenImage.js

This PR fixes the lines in the ENS SVG avatar

Profiles: Remove lines from gradient

---

src/components/discover-sheet/RegisterENSSection.tsx
src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
src/navigation/Routes.ios.js
src/navigation/config.js

Fixes RNBW-3239
Fixes RNBW-3235
This PR fixes the issue where we could not horizontally scroll the record tags, and also fixes another issue where the swipe would override the tap.
I also added the ability to extend the preview sheet from it's short form to a full span form.
https://www.loom.com/share/a36e61809a6a44fca722e2b9364bab29

Profiles: Intro Screen polishhh

---

src/components/unique-token/UniqueTokenCard.js
src/parsers/uniqueTokens.js
src/redux/uniqueTokens.ts

Profiles: Fix ENS NFT regressions from merge

---

src/components/step-indicator/StepIndicator.tsx
src/components/token-info/TokenInfoItem.js

Fixes RNBW-3180
- fixed unintended side effects caused by changes to TokenInfoItem

Profiles: fix unintended side effects

---

e2e/sendSheetFlow.spec.js

fix e2e - we got an ens

---

src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx

This reverts commit 48a540ca4e79028baf366273c23e07da09323a60. 
I'm unable to repro the bug with this revert. @terrysahaidak your changes def make sense but i'm thinking there's something in our implementation that is causing this to be an issue we should def revisit.

Revert "Do not remount rows of RecyclerListView (#3207)"

---

src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
src/hooks/useENSRegistration.ts
src/hooks/useENSRegistrationCosts.ts
src/hooks/useENSRegistrationForm.ts
src/hooks/useSelectImageMenu.tsx
src/screens/ENSConfirmRegisterSheet.js

This PR fixes an issue with inconsistent cover photo uploads (cover photo appearing again when it was removed).
Also fixes a few instances where we were experiencing infinite loops in some places

Profiles: Various fixes

---

src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
src/components/step-indicator/StepIndicator.tsx
src/screens/ENSSearchSheet.js

Fixes RNBW-3201
- normalize ens behind the scenes only, keep raw user input displayed in search
- lint fixed something unrelated
- added horizontal inset to pending registration divider
- moved divider inside PendingRegistrations component so it's only shown when there are pending registrations
https://user-images.githubusercontent.com/15272675/164295547-209a7608-6660-4800-90d0-9a713e065469.mp4

Profiles: don't normalize search input display text

---

src/components/animations/CheckmarkAnimation.tsx

Pulsing checkmark when visible for more than 2s

---

src/hooks/useENSSearch.ts
src/navigation/RegisterENSNavigator.js
src/raps/actions/ens.ts
src/screens/ENSConfirmRegisterSheet.js
src/screens/ENSIntroSheet.tsx
src/screens/ENSSearchSheet.js

Fixes RNBW-3375
before 
https://recordit.co/JCPETfEhtI
after 
https://recordit.co/o4L0EQ5yrx

Profiles: more fixes

---

src/screens/SelectENSSheet.tsx

Small tweak to props for the flat list in `SelectENSSheet`

Profiles: Fix SelectENSSheet FlatList props

---

src/components/contacts/showDeleteContactActionSheet.js
src/components/ens-profile/ActionButtons/MoreButton.tsx
src/languages/_english.json

Fixes RNBW-3418
This PR adds the ability to remove a contact from the profile sheet if you already have them as a contact.

Profiles: Add ability to remove contact from profile sheet

---

src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx

Fixes RNBW-3376
Fixes a small issue with the text record field state.

Profiles: Fix text record field state

---

src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx

Fixes RNBW-3419
NFT list in profile wasn't working well
@jxom I just made it work and seems like it didn't break anything else
before https://recordit.co/PTH3DAO32S
after https://recordit.co/f5O6FbHLkJ
i have the is_testing flag on that's why the nfts are just the names

Profiles: fix NFTs recycler list scroll handler in profiles sheet

---

src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
src/styles/colors.js
src/utils/getExchangeIconUrl.ts
src/utils/index.ts

Fixes RNBW-3425
piped up icons from the assets repo and added fallback logic
https://cloud.skylarbarrera.com/Screen-Recording-2022-04-27-16-23-59.mp4

swap exchange icons

---

src/components/fab/ExchangeFab.js
src/hooks/useSwapCurrencyHandlers.js

Fixes RNBW-3422
removed default eth from swap logic and FAB
https://cloud.skylarbarrera.com/Screen-Recording-2022-04-27-23-37-43.mp4

swap - rm default eth

---

src/navigation/RegisterENSNavigator.js
src/screens/ENSAssignRecordsSheet.js
src/screens/ENSConfirmRegisterSheet.js

- when selecting image from phone, ENSConfirm screen was overriding accent color
- when extending or setting primary name, the current registration name wasn't cleared on unmount so when you came back to the flow in search the name would still be in the input
- ens assign screen is scrollable again
- correct title label when creating or editing profile

Profiles: last bugs

---

src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx

Fixing issue where field would clear when navigating to confirm screen

Profiles: Fix issue where field would clear when navigating to confirm screen

---

package.json
yarn.lock

ahhh im auditing 
also bumped unstoppable resolver since they bumped it internally

audit - cross-fetch

---

src/navigation/RegisterENSNavigator.js

This PR fixes a small issue where the keyboard was flickering between the Intro & Search screens.

Profiles: Fix flickering keyboard between Intro & Search screens

---

src/components/expanded-state/WalletProfileState.js

Fixes RNBW-3362
It applies only to android when using face id/fingerprint.
When creating a new wallet, the goBack function conflicted with the native verification modal; I added a delay so that the modal with the new wallet name had time to close.
before: https://streamable.com/lc7c9c
after: https://streamable.com/ppu8zp
Try to create a new wallet with the existing wallet

Can't create a new wallet with biometry

---

CODEOWNERS

rm christian from code owners 

---

CODEOWNERS
src/performance/utils.tsx
tsconfig.json

These utils are helpful for debugging performance. Especially when trying to find problems or working on improving performance or components or functions.
The documentation is available [here](https://www.notion.so/rainbowdotme/Profiling-React-Native-application-66388365e9d7490d955d06ddd04906fb)

Add performance utils

---

src/components/AvailableNetworks.js
src/components/expanded-state/asset/ChartExpandedState.js
src/hooks/useAdditionalAssetData.ts
src/languages/_english.json
src/languages/_french.json

Fixes RNBW-3366
making new ticket for onPress since its up in the air still
https://cloud.skylarbarrera.com/Screen-Shot-2022-05-05-14-29-30.90.png

expanded state available networks

---

src/components/exchange/CurrencySelectModalHeader.js
src/components/exchange/NetworkSwitcher.js
src/hooks/useSwapCurrencyList.ts
src/languages/_english.json
src/languages/_french.json
src/redux/swap.ts
src/screens/CurrencySelectModal.js
src/screens/ExchangeModal.js
src/utils/ethereumUtils.ts

Fixes RNBW-3451
I added network switcher, refactored swap currency list a lil so it updates on network change, and added logic to reset inputs if the other input's network changes
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-05-16-57-51.mp4

network switcher

---

src/helpers/ens.ts

Fix: import Wallet from @ethersproject

---

src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
src/components/coin-icon/ChainBadge.js

Fast icons for rows

---

src/screens/TransactionConfirmationScreen.js
src/screens/WalletConnectApprovalSheet.js

Follow up PR based on earlier convos.
TBD
WC connection prompt will display all dapps the same way

Update WC dapp display treatment

---

src/components/discover-sheet/DiscoverSearch.js
src/components/ens-profile/RecordHyperlink/RecordHyperlink.tsx
src/components/send/SendHeader.js
src/handlers/deeplinks.ts
src/hooks/useOnAvatarPress.ts
src/hooks/useTrackENSProfile.ts
src/raps/actions/ens.ts
src/screens/ProfileSheet.tsx

Fixes RNBW-3543
Details in ticket

Profiles: update analytics

---

src/hooks/useSwapDerivedOutputs.ts
src/screens/ExchangeModal.js

Fixes RNBW-3587
resetting inputs now
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-11-12-55-08.mp4

reset swap inputs

---

src/components/expanded-state/swap-settings/SwapSettingsState.js
src/screens/ExchangeModal.js

Fixes RNBW-3474
removed from settings and fixed mainnet check
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-11-12-25-44.mp4

flashbots no l2

---

src/components/expanded-state/swap-details/CurrencyTile.js
src/components/expanded-state/swap-details/SwapDetailsContent.js
src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
src/utils/ethereumUtils.ts

Fixes RNBW-3565
removed native asset contract rows
fixed parsing for l2 exchange names & icons
fixed chain badge on the review sheet
rows: https://cloud.skylarbarrera.com/Screen-Recording-2022-05-13-15-28-52.mp4
names + icons: https://cloud.skylarbarrera.com/Screen-Recording-2022-05-13-15-32-57.mp4
badges: https://cloud.skylarbarrera.com/Screen-Shot-2022-05-13-15-36-48.62.png

swap - review clean up

---

src/components/expanded-state/unique-token/ZoomableWrapper.android.js
src/navigation/RegisterENSNavigator.js
src/screens/ENSIntroSheet.tsx

Fixes RNBW-3607
Fixes RNBW-3606
Fixes RNBW-3608
Fixes RNBW-3611
Fixing issues that we were seeing on smaller iPhone devices.
https://user-images.githubusercontent.com/7336481/168697663-cd135c90-2f23-420d-805b-9b1735707b55.mp4

Profiles: Fix small device UI issues

---

src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
src/components/coin-row/BalanceCoinRow.js
src/helpers/assets.js
src/hooks/useCoinListEditOptions.ts
src/hooks/useWalletSectionsData.js
src/model/migrations.ts
src/redux/data.ts
src/redux/editOptions.js
src/screens/CurrencySelectModal.js
src/screens/SendSheet.js

use object with pinned coins and hidden coins

---

src/components/expanded-state/swap-settings/SwapSettingsState.js
src/languages/_english.json
src/languages/_french.json

Fixes RNBW-3592
added defaults and i18n
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-16-11-51-28.mp4

swap settings - defaults

---

src/components/ens-profile/ActionButtons/SendButton.tsx
src/components/fields/AddressField.js
src/components/send/SendHeader.js
src/screens/SendConfirmationSheet.js
src/screens/SendSheet.js

Fixes RNBW-3609
- show ens name in send sheet header when coming from profile
- disable send header input when coming from profile
- use ens avatar in send confirmation sheet
- show hex address in send sheet header if no ens
https://user-images.githubusercontent.com/15272675/168877279-325fb7a9-4f99-4aba-ac14-352c51d673bf.mp4

Profiles: send sheet fixes

---

src/react-native-animated-charts/src/charts/linear/ChartPath.tsx

Fixes RNBW-2258
Rounding X for calculating Y is redundant 
Before:
https://streamable.com/fjw3yo
After:
https://streamable.com/s3vrf8

Make dot moving smoother in charts

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

version bump

---

src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
src/handlers/ens.ts

Fixes RNBW-3628, RNBW-3627
- fixed bug in `formatRecordsForTransaction` where record changes with false-y values were getting filtered out, including empty strings. this caused removal of existing records to get filtered out of profile edits.
- fixed bug that caused uploaded cover photos to not get displayed
https://user-images.githubusercontent.com/15272675/168934657-031f8dbe-8862-452d-b7c7-1541caa85d34.mp4

Profiles: assign record sheet fixes

---

src/navigation/RegisterENSNavigator.tsx
src/screens/ENSIntroSheet.tsx

Fixes RNBW-3637
This PR fixes issues we were seeing where the height of the content on the intro screen sheet would extend past the device height.

Profiles: Fix intro sheet height for small devices

---

src/components/step-indicator/StepIndicator.tsx

Fixes RNBW-3616
already talked about this with @jxom

Profiles: disable step indicator android

---

src/screens/ENSConfirmRegisterSheet.tsx

Fixes RNBW-3642
One liner changing height

Profiles: change ENSConfirmRenewSheetHeight on android

---

src/hooks/useInitializeWallet.js
src/performance/tracking/index.ts

* Added useInitializeWallet performance tracking
* Added `clearMeasure` function to PerformanceTracking
* review code

Add useInitializeWallet performance tracking

---

src/handlers/ens.ts
src/helpers/assets.js
src/hooks/useFetchUniqueTokens.ts
src/parsers/index.ts
src/parsers/uniqueTokens.js

This PR adds the ENS NFT fallback to the profile sheet & also adds `handleAndSignImages` to fallback implementation.

Profiles: add ENS NFT fallback to profile sheet & use `handleAndSignImages` in fallback

---

src/apollo/queries.ts
src/handlers/ens.ts
src/hooks/useENSModifiedRegistration.ts
src/parsers/poap.js
src/redux/wallets.js
src/screens/ENSConfirmRegisterSheet.tsx

Explanation of changes in lines of code

Profiles: more profiles

---

src/components/settings-menu/DevSection.js
src/languages/_english.json
src/screens/SettingsModal.js

@pugson  Fixed it for you - https://recordit.co/wOME9IFb7a
CC: @welps

Fix navigation for Notifications debug setting

---

src/App.js
src/components/settings-menu/DevNotificationsSection.tsx
src/components/settings-menu/DevSection.js
src/components/settings-menu/SettingsSection.js
src/components/settings-menu/index.js
src/helpers/isTestFlight.ts
src/languages/_english.json
src/screens/SettingsModal.js

Fixes RNBW-3517
Added a temporary test menu for firebase notifications testing.
| ![image](https://user-images.githubusercontent.com/6843656/169885117-6e281949-152b-44d0-a042-15bc0e7b9ad9.png) | ![image](https://user-images.githubusercontent.com/6843656/169431009-d0582aaf-5b0a-4481-b105-1931ba2bf637.png)   |
|----|----|

Push Notifications Dev Menu

---

src/components/settings-menu/DevNotificationsSection.tsx

Simple fix related to https://github.com/rainbow-me/rainbow/pull/3329

Fix notifications dev menu not scrolling

---

src/context/ThemeContext.tsx

remove the initial state.
note my ts chops are minimal so lmk if theres a better way to do this
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-25-14-58-17.mp4

fix theming

---

src/model/config.ts

config was fine but it assumed users would only have mainnet set but once we introduced testnets that was not the case. 
we still want to update the RPC's if they've changes but now we do it based on the current network vs defaulting to mainnet
before: https://cloud.skylarbarrera.com/Screen-Shot-2022-05-26-11-47-16.72.png
https://cloud.skylarbarrera.com/Screen-Shot-2022-05-26-11-47-42.49.png

fix config logic

---

CODEOWNERS
src/handlers/ens.ts
src/hooks/useENSRegistrationCosts.ts

nothing big, just estimation tweaks thanks to @benisgold  🚀

profiles set records estimations tweaks

---

src/components/AvailableNetworks.js
src/components/expanded-state/asset/ChartExpandedState.js
src/languages/_english.json
src/languages/_french.json
src/screens/ExplainSheet.js

Fixes RNBW-3556
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-31-15-01-32.mp4

swap - available networks explainooor

---

src/components/coin-row/CoinRowInfoButton.js
src/components/coin-row/ExchangeCoinRow.js
src/components/exchange/ExchangeAssetList.js
src/hooks/useSwapCurrencyHandlers.js
src/screens/CurrencySelectModal.js

fixes crash & disables favs and fixes rendering issues based on props
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-31-16-39-20.mp4

swap - disable l2 favs

---

src/components/ens-profile/ProfileSheetHeader.tsx
src/components/expanded-state/unique-token/ENSBriefTokenInfoRow.tsx
src/handlers/ens.ts
src/helpers/ens.ts
src/hooks/useENSRegistrationActionHandler.ts
src/hooks/useENSResolveName.ts
src/hooks/useImportingWallet.js
src/hooks/useOnAvatarPress.ts
src/raps/actions/ens.ts
src/raps/common.ts
src/redux/showcaseTokens.ts
src/screens/ENSConfirmRegisterSheet.tsx

Fixes RNBW-3722
Fixes RNBW-3741
Fixes RNBW-3728
Fixes RNBW-3727
- Fixes some issues above
- some instances of useENSProfile were enabled even tho the flag was off, so i cleaned it up
- some small refactors
- for RNBW-3728 and RNBW-3727 i added comments explaining the logic in the code https://github.com/rainbow-me/rainbow/compare/%40jxom/ens-phase-three...%40esteban/profiles-release-bugz?expand=1#diff-26ce1a9906e90da9fde476edb2180ed36f8b3d60d4b4bd5974bb6e9c1aef98fbR250

profiles: release bugz

---

src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
src/components/inputs/InlineField.tsx
src/helpers/ens.ts
src/screens/ENSAssignRecordsSheet.tsx

Fixes RNBW-3739, RNBW-3747
- use email keyboard for email record
- use autocorrect + first letter capitalization for display name, description, notice, keywords, pronouns records
- increase bottom padding of assign records sheet scroll view to accommodate for larger keyboard (turning on autocorrect adds a word suggestion bar above normal keyboard)
https://user-images.githubusercontent.com/15272675/171470266-a82e4d05-ccce-4f96-a3da-2f977531b9d3.mp4

Profiles: add spellcheck to some record inputs 

---

CODEOWNERS

Revisions to CODEOWNERs to aim for a more minimal set of critical files and directories that need to remain with CODEOWNERs.

Codeowners revision

---

src/components/expanded-state/UniqueTokenExpandedState.tsx
src/hooks/index.js
src/hooks/useENSProfileRecords.ts
src/hooks/useOnAvatarPress.ts
src/screens/ENSIntroSheet.tsx
src/screens/SelectENSSheet.tsx

This PR just introduces some performance tweaks. I have added prefetching of ENS records so a user doesn't have to wait for their records to load when they enter the "Edit Profile" screen.

Profiles: Prefetch ENS records for Edit Profile screen

---

audit-ci.json
package.json
yarn.lock

We're not using it anymore
none
nothing

Remove husky

---

e2e/registerENSFlow.spec.js
src/components/expanded-state/UniqueTokenExpandedState.tsx
src/components/fields/CheckboxField.tsx
src/handlers/ens.ts
src/helpers/ens.ts
src/hooks/useENSModifiedRegistration.ts
src/raps/actions/ens.ts
src/raps/registerENS.ts
src/screens/SendConfirmationSheet.tsx
src/screens/SendSheet.js
src/screens/WalletScreen.js

Fixes TEAM2-11
E2E are failing since there are still things to fix in the main branch

ENS send flow e2e

---

android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Cherry-picked from https://github.com/rainbow-me/rainbow/pull/3487
nothing

bump versions

---

src/components/expanded-state/swap-details/SwapDetailsContractRow.js

Fixes TEAM2-5
profiles bumped the `ContextMenuButton` package which removed the `menuVisible` prop, ive added to state and everything working as expected
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-10-10-30-12.mp4

swaps - fix swap details crash

---

src/components/settings-menu/DevNotificationsSection.tsx

Fixes RNBW-3815
| before | after |
| ------ | ----- |
| ![CleanShot 2022-06-08 at 07 38 36 PM@2x](https://user-images.githubusercontent.com/6843656/172681798-aab43428-e1f1-4a54-9546-247ccea3cd30.png) | ![CleanShot 2022-06-08 at 07 38 25 PM@2x](https://user-images.githubusercontent.com/6843656/172681817-a19e84d7-8e19-4b0e-ac41-9a47b36c02e1.png) |

Show wallet ENS for watched wallets in dev menu

---

src/components/settings-menu/DevNotificationsSection.tsx

Fixes TEAM2-69
No more crashing.

Remove containsEmoji from dev menu for notifs

---

src/hooks/useSwapDerivedOutputs.ts
src/screens/ExchangeModal.js

Fixes TEAM2-67
had to add some type checking for our input value handlers
also did the same for the logic to display gas button ( which should match with the confirm button )
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-12-18-40-42.mp4

swaps - fix savings flow regressions

---

src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx

Fixes TEAM2-12
No more bouncy bounce that was causing weird gaps at the top with the cover.
Can't record it in the simulator because touch gestures are wonky with a mouse. Try it on a real device.
Profile sheet scrolling and closing.

Disable Profiles sheet bounce

---

src/screens/ExplainSheet.js

Fixes TEAM2-100
- updated explainers as per https://www.notion.so/rainbowdotme/Revised-profiles-explainers-copy-5532448905d54d5ba9ae6ba894819cdb
- will modify "ENS configuration options" in https://github.com/rainbow-me/rainbow/pull/3389
https://user-images.githubusercontent.com/15272675/173706446-dbbc13b1-a02d-4aba-8700-6dc1a86c8953.mp4

Profiles: Update explainers

---

src/components/exchange/CurrencySelectModalHeader.tsx
src/components/expanded-state/asset/ChartExpandedState.js
src/components/sheet/sheet-action-buttons/SwapActionButton.js
src/screens/CurrencySelectModal.js

Fixes TEAM2-103
added conditional rendering logic for coin icon in title 
iOS: https://cloud.skylarbarrera.com/Screen-Shot-2022-06-14-21-35-57.97.png
android:

swaps - add coin icon to output title

---

src/components/exchange/ConfirmExchangeButton.js
src/components/expanded-state/SwapDetailsState.js
src/components/expanded-state/swap-settings/SwapSettingsState.js
src/screens/ExchangeModal.js

Fixes TEAM2-118
this view was broken
- flashbots above the confirm button
- settings height was too short
- used design system for these components 
- 
https://recordit.co/wxsLnWJU0K

swaps: flashbots UI

---

src/hooks/useENSRegistrationActionHandler.ts

Fixes TEAM2-34
This PR implements the ability to fetch ENS again in the users' wallet on the next block after a registration/set records action.

Profiles: update avatars after registration

---

src/screens/ExchangeModal.js

Fixes TEAM2-116
hook is working fine but the loading prop we pass in was not correct, not loading matches the fetching details behavior 
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-15-12-40-05.mp4

fix loading calc

---

src/components/expanded-state/SwapDetailsState.js
src/components/expanded-state/swap-details/SwapDetailsContent.js
src/languages/_english.json
src/languages/_french.json

Fixes TEAM2-123
This PR just polishes up the "More details" animation – cutting down the spring damping, as well as changing the color of the text to match the designs.
https://user-images.githubusercontent.com/7336481/173973721-2af2ef28-ff10-41fb-bf8d-7acb6ec78e86.mp4

Swaps: Polish more details animation

---

package.json
src/handlers/opensea-api.ts
src/rainbow-fetch/index.ts
yarn.lock

Fixes RNBW-3743
- limited opensea api requests

Profiles: Limit opensea api requests

---

src/components/exchange/ExchangeSearch.js
src/languages/_english.json

Fixes TEAM2-114 
Fixes TEAM2-102 
Fixes TEAM2-104
- Updated search input styling
- Updated copy on swap explainer modal
- Updated "Search" -> "Search tokens"
- Swap token search input

Swap aggregator styling + copy updates

---

src/hooks/useSwapCurrencyHandlers.js
src/screens/ExchangeModal.js

Fixes TEAM2-129
added handling for input focusing, disabled warning if no output currency set
iOS: 
https://user-images.githubusercontent.com/29204161/174197394-da040bb0-e3f7-40bd-962f-d6c568aa098a.mov
android: 
https://user-images.githubusercontent.com/29204161/174197403-24079e26-6d2d-4c37-a34d-4d146178b248.mov

swaps - arbis warning cleanup

---

src/hooks/useOnAvatarPress.ts

Fixes RNBW-3877
We weren't parsing the image path correctly
https://user-images.githubusercontent.com/12115171/174834966-30032f74-8d62-4718-8a85-eff28dd9ae19.mov
choose image and see it on the wallet

fix: avatar image picker

---

.github/workflows/macstadium-e2e.yml
package.json
yarn.lock

It wasn't configured to run correctly on every PR and push.
Also fixing 2 vulns by locking the patched version on resolutions.
It should trigger correctly on this PR
Nothing really

Fix e2e trigger

---

src/components/exchange/ExchangeSearch.js

Fixes TEAM2-149
Fixed the discover search bar issue, that was breaking e2e
BEFORE:
AFTER:
Discover search states: initial / focused / type some text states

Fix swaps e2e

---

src/components/numpad/PinValue.js

This was using reanimated v1, should use v2
create a new wallet from the empty state. Clear cache before and disable touchid

Wallet creation fix

---

src/components/buttons/TokenSelectionButton.js
src/components/exchange/ExchangeField.js
src/hooks/useColorForAsset.js

swaps - fix l2 fallback colors

---

src/components/send/SendAssetFormCollectible.js

Fixes RNBW-3878
https://user-images.githubusercontent.com/12115171/174892832-ecfc9828-0660-400f-97ad-1f94665e8c8f.mov

fix: android review send nft

---

src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
src/components/expanded-state/swap-details/SwapDetailsPriceRow.js
src/languages/_english.json
src/screens/ExplainSheet.js

Fixes TEAM2-162
Fixes TEAM2-163
- Using `convertRawAmountToDecimalFormat` on amounts before calculating the rate
- Fix percentage by using `convertAmountToPercentageDisplayWithThreshold`

Fix exchange rate in swap review modal 

---

src/components/exchange/ExchangeDetailsRow.js
src/hooks/useSwapCurrencyHandlers.js
src/redux/swap.ts
src/screens/ExchangeModal.js

Fixes TEAM2-160
Fixes TEAM2-164
updating flipping behavior following linear ticket
https://user-images.githubusercontent.com/12115171/175169593-eecd5c2c-6d74-45b1-a718-7df88fd860b4.mp4
switching to undefined bug was fixed in https://github.com/rainbow-me/rainbow/pull/3561

swaps: update flip behavior

---

src/components/discover-sheet/DiscoverSearchContainer.js
src/components/discover-sheet/DiscoverSearchInput.js

Fixes TEAM2-165
now we use 2 separate components 
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-23-13-31-59.mp4

swaps - revert discover input

---

src/screens/CurrencySelectModal.js

Fixes TEAM2-166
this broke it: https://github.com/rainbow-me/rainbow/pull/3313
https://cloud.skylarbarrera.com/Screen-Shot-2022-06-23-13-09-57.39.png

swaps - fix input filtering

---

src/components/expanded-state/SwapDetailsState.js
src/components/expanded-state/swap-details/CurrencyTile.js
src/components/expanded-state/swap-details/SwapDetailsContent.js
src/components/expanded-state/swap-details/SwapDetailsContractRow.js
src/components/expanded-state/swap-details/SwapDetailsMasthead.js
src/components/expanded-state/swap-details/SwapDetailsRow.js
src/components/expanded-state/swap-settings/SourcePicker.js
src/components/expanded-state/swap-settings/SwapSettingsState.js
src/languages/_english.json
src/screens/ExplainSheet.js

Fixes TEAM2-120 TEAM2-122
- Updated coin and $ display to match design spec
- Fixed token truncation to always show the symbol
- Fixed padding around swap button
- Fixed weird coin tile padding on Android
- Fixed chevron shadow between coin tiles
- Fixed icon clipping for contract rows on Android
- Updated text color for swap review
- Updated copy for the Rainbow Fee explainer sheet
- Refactored components to use more of the design system
- Added shadow to swap route picker
- Matched swap settings order with one in Figma
- Removed price difference row
> **Note**: Being unable to trigger touch events on some rows on Android from time to time is caused by the bottom sheet swipe threshold being too sensitive. Light taps are picked up as swipes that are trying to close the bottom sheet 🤷‍♀️ …

Swap review sheet UI updates

---

src/helpers/utilities.ts

we were using `toPrecision` causing some issues like showing `0.001000` as value for the input when pressing max

fix: rounding input on max to decimalPlaces

---

src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
src/components/expanded-state/swap-settings/SourcePicker.js
src/components/expanded-state/swap-settings/SwapSettingsState.js
src/languages/_english.json
src/screens/ExplainSheet.js

I fixed a few styles to match the designs here: https://www.figma.com/file/FNzceJrmBJMUPgSj0oVXm9/swap-v2?node-id=2688%3A44154 in swap settings state and I added the 3 explainer sheets.
https://recordit.co/VJw4CaVLNH
Make sure settings look pretty and that the explainers are there

[TEAM2-3] Update Swap explain sheets copy

---

src/apollo/queries.ts
src/components/ens-profile/RecordTags/RecordTags.tsx
src/handlers/ens.ts

Fixes TEAM2-29, RNBW-3820, RNBW-3863
- unfurl hex address to ens in discover search
- filter out ens that resolve to zero address from ens suggestions subgraph query (null resolver addresses are also filtered)
- use containsEmoji for profile record tags
https://user-images.githubusercontent.com/15272675/175359715-2feff3d7-ac55-4f23-8309-b9fc114be604.mp4

Profiles: Misc. fixes

---

src/hooks/useSwapCurrencyHandlers.js
src/hooks/useSwapDerivedOutputs.ts
src/navigation/ExchangeModalNavigator.js
src/redux/swap.ts

Fixes TEAM2-186
Fixes TEAM2-181
Fixes TEAM2-183
one commit per fix

swaps: fixes

---

src/components/expanded-state/WalletProfileState.js
src/model/wallet.ts

Fixes RNBW-3875
looks like the prompt doesn't like the animation at the same time.
why? idk
can this be done better? yes
why did profiles break it?  ¯\_(ツ)_/¯ 
https://streamable.com/dp52xm
(screen recording doesn't work)
- touchid on
- create a new wallet
- create another wallet 
- authenticate with a finger

Delay closing sheet until we're done with keychain on android 

---

src/App.js

We are now using chain id to determine the network value.
https://recordit.co/c8AzTJTgJr
Perform an L2 transaction and observe whether your balance is updated.

[TEAM2-173] balances not updating after L2 swap

---

src/languages/_english.json

Replaces PR #3606
Still Curious? -> Still curious?

resolved explainer sheet capitalization typos

---

e2e/hardhatTransactionFlow.spec.js
src/App.js
src/components/exchange/ExchangeAssetList.js
src/languages/_english.json
src/languages/_french.json
src/screens/CurrencySelectModal.js
src/screens/ExchangeModal.js
src/screens/ExplainSheet.js

Fixes TEAM2-204, TEAM2-211, TEAM2-182
changed alert to an explainer, update copy, tweaked some rendering logic in explain sheet 
unverified explainer: 
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-29-14-43-00.mp4
updated copy + styles: https://cloud.skylarbarrera.com/Screen-Shot-2022-06-29-16-14-35.80.png
android: 
no token explainer: (this still needs copy updates but I updated to the current state of the ticket for now
iOS: https://cloud.skylarbarrera.com/Screen-Shot-2022-06-29-16-50-44.37.png
android: 
copy update: https://cloud.skylarbarrera.com/Screen-Shot-2022-06-29-18-05-46.11.png
Output disabled copy update:
https://cloud.skylarbarrera.com/Screen-Shot-2022-06-29-18-03-48.11.png
explainer sheet should work as shown in video, other explainer sheets should not be affected …

swaps - explainer updates

---

src/components/sheet/sheet-action-buttons/SwapActionButton.js

Fixes TEAM2-222
small change, there's a before video in the ticket
with the fix
https://user-images.githubusercontent.com/12115171/176973518-c7653395-4c8f-41b8-9262-7a2b2ed111c7.mp4

asset: get asset from discover to swap

---

src/components/exchange/ExchangeField.js
src/components/exchange/ExchangeNativeField.js
src/components/gas/GasSpeedLabelPager.js
src/hooks/useSwapCurrencyHandlers.js

Fixes TEAM2-217
handle all cases for `flip` and `max` in mainnet and L2s including arbitrum
https://user-images.githubusercontent.com/12115171/176963577-98cf3d87-2eea-4e8a-bd63-e0cebc1d0ecf.mp4
- flip
- max
- type fast and delete characters to check if the input is not flickering
-

swaps: more input flip & max

---

src/components/expanded-state/swap-details/SwapDetailsContent.js
src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
src/hooks/useRainbowFee.js

Fixes TEAM2-226
Taking native asset when buyTokenAddress is the native asset, we were taking ETH for polygon swaps to MATIC

swaps: fix matic fees

---

src/hooks/useSwapCurrencyHandlers.js
src/screens/CurrencySelectModal.js

Fixes TEAM2-227
Changed behavior once a token is selected
- if input token changes, clear input field, which will trigger an update to the output and native fields
- if output token changes, clear output field which will trigger a new quote to be fetched with the input value
https://user-images.githubusercontent.com/12115171/177199003-94632ed1-69b6-47a5-af15-4392c8cd2e5b.mp4

swaps: currency selection updates

---

src/components/avatar-builder/EmojiSelector.tsx

- Fixed some callback and useEffect ESLint warnings, one silenced two simply fixed
- Changed styles name to sx since this is waht terry suggested in another PR 😄 
- check changes checkout code, perhaps run `yarn lint`

Fix ESLint warnings introduced in EmojiSelector PR

---

.github/pull_request_template.md
.github/workflows/codeqml.yml

Changes:
* Added a place for figma link
* Updated descriptions for screen recordings and what to test
* Added details for labels in the final checklist
* Added iOS/Android check and QA queue check to the final checklist

Update the PR template

---

src/components/exchange/ExchangeField.js
src/components/exchange/ExchangeInputField.js
src/hooks/useSwapSettings.ts
src/screens/ExchangeModal.js

explanation of the bug and fix is on the video
https://www.loom.com/share/4fe5702a42934f0681de15c340930da1
- press max
- flip currencies
- change output and inputs, if you change output the output field should clear, if you change input the output and input fields should clear

swaps: fix switching currency with max input

---

.github/pull_request_template.md
.github/workflows/codeqml.yml

We often forget about testing our changes on both dark and light theme, i added a reminder to the PR's template about that

Add notice about dark and light theme to PR's template

---

.github/pull_request_template.md

Screen recordings can also be helpful for showing reviewers what to test for.
Please be thorough about what to test to help reviewers. You might want to emphasize potential regressions to check for, if your code relies on a feature flag for checking both paths of the feature flag, other parts of the code that may have been impacted by your changes, etc.

Minor updates to to pull request template

---

src/hooks/useFetchUniqueTokens.ts

Fixes RNBW-3802
- fetch poaps in `useFetchUniqueTokens` so they show up in profiles
https://user-images.githubusercontent.com/15272675/177887198-77ebea0a-eee3-4e63-9e37-2d1ff71c3905.mp4

Profiles: poaps

---

src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
src/components/exchange/ExchangeAssetList.js
src/components/exchange/exchangeAssetRowContextMenuProps.js
src/components/exchange/exchangeAssetRowContextMenuProps.ts
src/hooks/useAccountAsset.js
src/hooks/useClipboard.js

Fixes RNBW-3675, RNBW-1892
I refactored this list. Now rows are light. I focused on Exchange Row (not contact). This impacts the ist in Search, but also this is the same list in Currency Selection (in Swap Flow) 
- Search
- Swap
Before:
- Receive
Before:
- Search
Before:
After:
- Swap
Before:
After:
-Receive:
Before:
After:
Check if all pixels are correct. I was trying to replicate this perfectly. I use LayerX for this,. 
E2E should pass and this is already a lot 😅

FastCurrencySelectionRow

---

src/components/expanded-state/swap-details/SwapDetailsContractRow.js

https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1657550240854639
* helperFixes RNBW-####

fix: crash expanded state  (#3563)

---

src/components/transaction/TransactionMessage.js

Fixes TEAM2-248
I moved the padding around so it doesn't impact the scroll view but its contents 
https://cloud.skylarbarrera.com/Screen-Recording-2022-07-12-09-55-47.mp4
signing long messages, Opensea App

fix element padding

---

src/utils/methodRegistry.ts

https://github.com/rainbow-me/rainbow/pull/3608

Contract signatures metadata cherry-pick for rc

---

src/components/expanded-state/swap-details/SwapDetailsContractRow.js

This was included and verified in the RC branch: https://github.com/rainbow-me/rainbow/pull/3693/commits/e4dad538f45494a42c7f9ce50f30a908c5edd9b6

Adding cherry pick for fix: crash expanded state

---

src/components/gas/GasSpeedLabelPager.js

gas section accent color wasn't changing according to output amount
before
https://user-images.githubusercontent.com/12115171/176961581-aef5ed78-d53c-451a-ae7c-6ca054bbdbf8.mp4
after
https://user-images.githubusercontent.com/12115171/176961503-e7311801-4237-4719-9676-100cdb37904c.mp4

fix: GasSpeedLabelPager update deps to get correct accent color

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json
src/utils/methodRegistry.ts

* Version bump
* Cherry pick of the contract signatures metadata PR

rc-v1.6.15 release for contract signatures metadata

---

CHANGELOG.md
src/helpers/validators.ts
src/redux/explorer.ts

* Updated CHANGELOG for v1.6.15 hotfix release
* Fixed minor typo
* Added blockchain tld for UD as it is now supported

Changelog update and minor cleanup

---

ios/fastlane/Fastfile

Includes the commit message into the fastlane pilot changelog

Include git commit message into fastlane pilot changelog

---

src/screens/CurrencySelectModal.js

Fixes TEAM2-220
added footer spacing to the list on android
https://user-images.githubusercontent.com/29204161/179066994-883aabec-8bb7-4527-85cf-868044fd964d.mov

swaps: android currency select modal footer spacing

---

e2e/hardhatTransactionFlow.spec.js
src/components/savings/SavingsListHeader.js
src/components/savings/SavingsListRow.js
src/screens/DepositModal.js
src/screens/SavingsSheet.js
src/screens/WithdrawModal.js

Fixes TEAM2-205
added e2e tests for savings flows
https://cloud.skylarbarrera.com/Screen-Shot-2022-07-14-15-11-12.52.png
e2e passes we gucci

swaps: savings flow e2e

---

src/redux/data.ts

some tokens have passed thru our filter via some edge cases (our checks are pretty minimal tbh)
ive added some extra handling so they are removed now
after(tokens are hidden): https://cloud.skylarbarrera.com/Screen-Shot-2022-07-18-12-14-30.38.png
check for the tokens in PoW in skillet.eth

add extra handling for scam tokens

---

src/redux/gas.ts
src/utils/gas.ts

Fixes TEAM2-263
- bump to 6
- fix `maxPriorityFeePerGas.gwei` to use the number correctly

swaps: fix flashbots tip

---

src/hooks/useSwapDerivedOutputs.ts

found this little bug
https://user-images.githubusercontent.com/12115171/180053940-802fe6f5-6678-4be9-9ed2-d7466867fce1.MP4
https://user-images.githubusercontent.com/12115171/180053996-ff5e2a21-92d1-4325-bfb0-0274e1502b63.mp4

swaps: fix 0. value in inputs behavior

---

src/components/expanded-state/custom-gas/FeesGweiInput.js
src/components/expanded-state/custom-gas/FeesPanel.js
src/components/expanded-state/custom-gas/GweiInputPill.js
src/components/gas/GasSpeedButton.js
src/screens/ExchangeModal.js

Not allowing users modify miner tip to less than 6 if they're in a flashbots tx
https://user-images.githubusercontent.com/12115171/180086331-cd066e02-892c-4105-a78a-5776061ad54b.mp4

swaps: block flashbots swaps miner tip

---

src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
src/components/expanded-state/swap-settings/SwapSettingsState.js
src/screens/ExchangeModal.js

Fixes TEAM2-279
using default values now, using a helper function cause TS doesn't like the remote config.

swaps: fix slippage reset

---

e2e/deeplinks.spec.js

fix deeplink e2e

---

e2e/init.js
src/handlers/uniswap.ts

- Fix swap default gas limit logic
Green tests is all we need

Fix swaps e2e again

---

src/hooks/useSwapDerivedOutputs.ts

Fixes TEAM2-294
https://cloud.skylarbarrera.com/Screen-Recording-2022-07-25-11-26-46.mp4

swaps: dont round max

---

src/components/exchange/ExchangeField.js
src/components/exchange/ExchangeInputField.js
src/components/exchange/ExchangeNativeField.js
src/components/exchange/ExchangeOutputField.js
src/components/exchange/PriceImpactWarning.js
src/handlers/uniswap.ts
src/hooks/useSwapCurrencyHandlers.js
src/hooks/useSwapDerivedOutputs.ts
src/hooks/useSwapSettings.ts
src/redux/swap.ts
src/screens/ExchangeModal.js

- including https://github.com/rainbow-me/rainbow/pull/3783
- fixed flipping behavior
- block trace calls to estimate gas when testing
- only call updateGasLimit from ExchangeModal when gas params change, before it was depending on trade details so we were estimating gas more times than needed

swaps: inputs PRs

---

package.json
src/hooks/useSwapDerivedOutputs.ts
yarn.lock

Use isTestflight helper instead of NativeModules
sent via slack

Fix swaps for testflight

---

src/hooks/useSwapCurrencyList.ts
src/redux/data.ts
src/utils/ethereumUtils.ts

Just guarding against empty values here.
I don't think there's a good way to test these corner cases. Let's just make sure the code is solid.

[TEAM2-292] Fix Sentry Bugs

---

src/components/exchange/ConfirmExchangeButton.js

Fixes TEAM2-293
follow up pr for android
https://www.loom.com/share/62d10ca2ecc14eb79273f74af83eed1a

swaps: android fix confirm button submitting state

---

src/components/settings-menu/AppIconSection.js
src/featuresToUnlock/optimismNftAppIconCheck.ts

Fix after recent changes
This should be defined globally according to MMKV docs 
no testing needed

Move MMKV instances to the global scope

---

src/redux/walletconnect.ts
src/screens/TransactionConfirmationScreen.js

Fixes RNBW-3574
adding some extra data for analytics

add xtra deets to wc analytics

---

src/components/transaction-list/TransactionList.js

[TEAM2-303] Fix unguarded string manip again

---

src/components/settings-menu/AppIconSection.js
src/featuresToUnlock/optimismNftAppIconCheck.ts

Cherrypicking https://github.com/rainbow-me/rainbow/pull/3824

Fix mmkv usage

---

src/hooks/useSwapCurrencyHandlers.js
src/redux/swap.ts

[RNBW-4059] swaps: fix arbitrum flipping

---

src/handlers/uniswap.ts

Fixes TEAM2-308
just bump of the gas limit
send a swap and it should work well

swap: bump gas estimation padding

---

src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx

Fixes TEAM2-300
regression from fast component changes
before: https://cloud.skylarbarrera.com/Screen-Shot-2022-07-26-12-33-17.45.png
after: https://cloud.skylarbarrera.com/Screen-Recording-2022-07-26-12-32-11.mp4
swap input + output selection & discover, changes should only impact input token name truncating

swaps: fix currency row truncating

---

src/screens/SpeedUpAndCancelSheet.js

Fixes TEAM2-309
https://user-images.githubusercontent.com/12115171/181273233-d79272b2-40cf-42ba-a2ea-1410ecef236f.mp4

swaps: use flashbots miner tip when speeding up or cancelling

---

src/components/expanded-state/swap-details/SwapDetailsFeeRow.js

swaps: ignore threshold

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.6.22 and Android 138

Version bump iOS v1.6.22 and Android 138

---

src/hooks/useSwapDerivedOutputs.ts

swaps: fix swaps sheet leak 

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.6.23 and Android 139

Version bump iOS v1.6.23 and Android 139

---

src/hooks/useSwapDerivedOutputs.ts

We have to be more aggresive with quote polling to increase slippage
http://recordit.co/uxK7GGKa2L
Should see a new quote coming in every 5 sec

Increase polling interval to 5 sec

---

src/components/native-context-menu/contextMenu.android.js
src/components/profile/AvatarCircle.js
src/components/profile/ProfileMasthead.js
src/hooks/useOnAvatarPress.ts

Fixes RNBW-4008
I added a better menu for the avatar. 
https://streamable.com/p4vrhb
See if those buttons are working. MErge after merging the main branch.
No impact on iOS

Avatar menu

---

src/screens/WelcomeScreen.tsx

Fixes RNBW-4021
I added the elevation (cause we don't have shadows on Android) and looks ok. I removed the displacement on Android (not needed). I made the whole component visible on both platforms
no impact on IOS
Just observe if there is a shadow changing color

Add a shadow to Get a new wallet in Onboarding flow

---

patches/@react-native-menu+menu+0.5.2.patch
src/components/context-menu/ContextCircleButton.android.js
src/components/expanded-state/chart/ChartContextButton.js

Fixes RNBW-4008
Continuing my work about migration to context menus.
I added small changes in patches due to the error that this is was not possible to open the same menu for the second time, cause this was getting immediately dismissed. Now, we firstly dismiss, then open 
https://rainbowhaus.slack.com/archives/CGUNEHL9K/p1658925277791579?thread_ts=1658923631.982649&cid=CGUNEHL9K

Context menu on Expanded state

---

ios/Podfile.lock
src/components/coin-row/FastTransactionCoinRow.tsx
src/helpers/buildTransactionsSectionsSelector.tsx
src/helpers/transactionPressHandler.ts
src/hooks/useAccountTransactions.ts

Fixes RNBW-4062
This PR migrates the popup that appears on Android when pressing transaction row from current system to the context menu introduced by @osdnk in #3831.
The code for achieving context menu for both iOS and Android requires quite a bit of structure:
1. We have to calculate menu items.
2. We have to create iOS callback (it is applied to animated button and programmatically invokes context menu which receives callback for item presses).
3. We have to create Android callback (it is applied to ContextMenuButton and it is direct callback for item presses).
So basically we need items, we need item press callback, we need a wrapper for iOS that invokes proper API and we need to supply them in two different places. This probably asks for an abstraction layer.
I …

Add context menu for android transactions

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.7.0 & android 140

Version bump iOS v1.7.0 & android 140

---

.github/workflows/macstadium-e2e.yml

PRs with special chars are breaking the step "post message to slack", so I'm now escaping it
If this PR is green, it means my fix works

Escape slack msg with "quotes" or other symbols like +

---

src/components/ens-registration/ConfirmContent/EditContent.tsx
src/screens/ENSAssignRecordsSheet.tsx
src/screens/ENSConfirmRegisterSheet.tsx

Fixes RNBW-4113
- change size of ens confirm update sheet depending on if avatar exists and if primary ens switch exists

Profiles: dynamic sizing of confirm update sheet

---

src/components/discover-sheet/DiscoverSearchContainer.js
src/languages/_english.json
src/languages/_french.json

Fixes RNBW-4088
This was not looking good with just reduced margins, see below (tho colors of the border are not very nicely preserved, but the search icon is touching the border) :
See on some narrow phone, e.g., fold. This cannot be breaking.

Short Search Ethereum copy

---

src/components/AddFundsInterstitial.js
src/utils/deviceUtils.ts

Fix AddFundsInterstitials on narrow phones

---

src/screens/SelectENSSheet.tsx

Fixes TEAM2-361
- fixed avatar placeholder color
- fixed sheet height
https://user-images.githubusercontent.com/15272675/182690665-4bd9a125-02e3-49b2-9bf4-a9089d9e0a71.mp4

Profiles: My ENS Names sheet fixes

---

src/components/send/SendAssetForm.js

Fixes RNBW-4128
broke via https://github.com/rainbow-me/rainbow/commit/1da11c042e90761613774fec0fce888345702cc7 
https://user-images.githubusercontent.com/29204161/182730279-9c376e70-545d-4ca4-a1fd-0150ed69d88d.mov
-10 points gets u a free subdomain btw
try to send an nft

profiles: fix sendable nft preview

---

src/components/buttons/MiniButton.js
src/components/discover-sheet/DPICard.tsx
src/components/discover-sheet/DiscoverHome.js
src/components/discover-sheet/ENSCreateProfileCard.tsx
src/components/discover-sheet/ENSSearchCard.tsx
src/components/discover-sheet/GasCard.tsx
src/components/discover-sheet/ListsSection.js

Fixes TEAM2-358
Fixes RNBW-4171
- Fixed 'Max' button not appearing on Android when focused in the input inside the send sheet while keeping _MiniButton_ the same when importing a wallet.
- Fixed ugly shadow clipping for Discover cards on Android
| Android Discover Before | Android Discover After |
|-------------------------|------------------------|
|        ![Screenshot_20220804-023357](https://user-images.githubusercontent.com/6843656/182741362-ad6b7bd0-6f8a-4c21-9567-1b19d73d59b6.png)                 |           ![Screenshot_20220804-030603](https://user-images.githubusercontent.com/6843656/182741436-61b9d6e9-d2e9-489c-be54-0c66871f75c9.png)             |
| iOS 'Max' | iOS Import Wallet | iOS Discover Cards |
|-----------|-------------------|--------------------|
|    ![CleanShot …

Profiles: Fix for Android Discover shadows & Max button in send input

---

src/analytics/index.ts

segment is logging every event in debug, very hard to follow other tings, this disables
https://cloud.skylarbarrera.com/Screen-Shot-2022-08-03-15-17-44.67.png

silence segment logging

---

package.json
yarn.lock

audit: bump undici

---

src/hooks/useImportingWallet.ts

Fixes RNBW-4168
- fixed bad method call when importing wallet
https://user-images.githubusercontent.com/15272675/182947864-0fd7b948-6cb2-4ac9-b375-893877ae6653.mp4

Profiles: fix android crash when switching wallets

---

src/components/send/SendAssetForm.js

Fixes RNBW-4012
#3916 but to develop. Sorry for the chain of clicking through links. Ask any questions if anything is unclear.

Fix send sheet layout

---

src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
src/components/asset-list/RecyclerAssetList2/index.tsx
src/navigation/Routes.android.js
src/screens/SelectUniqueTokenSheet.tsx

Fixes RNBW-4172
* disabled pull down to refresh which was causing issues. When refresh was triggered and sheet dismissed the sheet won't appear again. Disabled the refresh since it doesn't seem to be necessary there and the problems gone away.
* Added a border radius on Android to match the rest of sheets
* Changed the padding style on Android to match the rest of sheets
Caveats:
* The Recycler list doesn't play with bottom sheet on Android nearly as well as on iOS. It is not continous and the festure sometimes relates to the list and sometimes to the bottom sheet. But when you hold the handle it always works for the bottom sheet and is possible to dismiss with 100% success rate
https://rainbowhaus.slack.com/files/U033TRAHD96/F03T6VCRHNU/screen-20220805-125249.mp4
* …

Fix select NFT modal on Android

---

src/hooks/useENSRecordDisplayProperties.tsx

Better menu for ENS records 

---

src/screens/ENSIntroSheet.tsx

Better menu for 'choose NFT'

---

src/components/ens-profile/ActionButtons/MoreButton.tsx

'More' button menu for android

---

src/hooks/useBlockBackButton.ts
src/screens/PinAuthenticationScreen.js

Fixes RNBW-4090
trivial fix
https://user-images.githubusercontent.com/25709300/183044343-349457c3-c56d-493f-a515-64a9535651c4.mov

Enable back button if the pin is prompted but not during creation

---

src/screens/ChangeWalletSheet.js

Fixes RNBW-4029
Before:
https://user-images.githubusercontent.com/7809008/182672530-30a601e4-3cc1-47b9-938a-add2a24cd22d.mov
After:
https://user-images.githubusercontent.com/7809008/182672394-0aa718c2-5747-41d9-b2c7-3953d6271118.mov
- Open select wallet sheet
- Pull the sheet up - there should be no line under "Add wallet"

Remove choose wallet bottom divider

---

src/navigation/bottom-sheet/constants.ts

Fixes RNBW-4214
This is sooo random. I don't get it
https://streamable.com/111x99
Check if send sheet is always visible. Try many times

Fix for disappearing bottom sheet

---

src/components/ens-profile/ProfileSheetHeader.tsx
src/components/ens-registration/PendingRegistrations/PendingRegistrations.tsx
src/screens/ENSAssignRecordsSheet.tsx
src/screens/ENSConfirmRegisterSheet.tsx
src/screens/ENSIntroSheet.tsx
src/screens/SelectENSSheet.tsx
src/utils/abbreviations.ts

Profiles: Truncate long ENS names

---

src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx
src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx
src/components/asset-list/RecyclerAssetList2/index.tsx
src/navigation/Routes.android.js
src/navigation/effects.js
src/screens/SelectUniqueTokenSheet.tsx

Fixes RNBW-4228
use reg stack for `SelectUniqueTokenSheet` + behavior tweaks so scrolling, etc works well on android
https://user-images.githubusercontent.com/29204161/183522775-49dfb79a-0ee0-468a-9641-737e90193a7f.mov

profiles: SelectUniqueTokenSheet android tweaks

---

src/components/Spinner.tsx
src/components/coin-row/FastTransactionStatusBadge.tsx

Fixes RNBW-4219
|Before|After|
|--|--|
|![Screenshot_20220808-201847_Rainbow](https://user-images.githubusercontent.com/5769281/183477632-afaf2ea4-8373-4450-8d36-40c4c6ea913c.jpg)|![Screenshot_20220808-202427_Rainbow](https://user-images.githubusercontent.com/5769281/183477652-8682830b-9bfe-4cb6-9b7a-110c2bae4672.jpg)|
Open some test wallet. Swap some tiny amount of money with custom gas set very low so it will get stuck in the list as pending sufficiently long for the test.
Compare current vs fixed.

Fix sending status badge position on Android

---

src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
src/hooks/useSelectImageMenu.tsx
src/languages/_english.json
src/languages/_french.json

Fixes TEAM2-355
added a loading/uploading state (usually pretty quick but fixes the lack of user feedback )
https://user-images.githubusercontent.com/29204161/183518995-779e6527-01ec-4409-b20d-0751c9599a50.mov
upload cover photos

profiles: cover uploading state

---

src/components/ens-registration/IntroMarquee/IntroMarquee.tsx
src/screens/ENSIntroSheet.tsx

Fixes TEAM2-404
supports small devices up to ~666 height
666 height - 
pixel 4 -

profiles: intro screen smog screen sizing

---

src/screens/SendSheet.js

Fixes TEAM2-407
Fixes an issue where pasting an ENS wouldn't register

Profiles: Send sheet - check if address is valid when pasting

---

src/handlers/deeplinks.ts
src/hooks/useScanner.ts

Fixes TEAM2-409
- route qr code to profile sheet

Profiles: route qr code to profile sheet

---

src/utils/ethereumUtils.ts

Fixes RNBW-4242
applied changes from https://github.com/rainbow-me/rainbow/pull/3972 it was the same issue
https://www.loom.com/share/fd83d213b7d1403c82da49eee3dbeed4
scan qr codes of the linear ticket

fix: android scan payment link

---

e2e/registerENSFlow.spec.js
src/utils/ens.ts

Fixes RNBW-4253
- fixed the bug
- added to e2e

profiles: special characters e2e

---

src/components/expanded-state/UniqueTokenExpandedState.tsx

Profiles: Temporarily disable cover photo zoom on Android

---

src/components/discover-sheet/DiscoverHome.js

Fixes RNBW-4256
https://user-images.githubusercontent.com/12115171/184028759-f9a8adba-6b22-40c3-94ed-4a836abad143.mp4

profiles: disable profiles cards on testnets

---

src/hooks/useENSRecordDisplayProperties.tsx

Fixes RNBW-4260
https://www.loom.com/share/c8e423b8f564436bb66ed3fd38466fb5

fix: profiles typo

---

src/screens/ImportSeedPhraseSheet.js

Added some missing props to the text input.
e2e should be green
importing a wallet via seed, pkey and ens name.

Update text input props

---

e2e/swapSheetFlow.spec.js
src/components/context-menu/ContextMenuButton.js
src/components/exchange/NetworkSwitcher.js
src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
src/components/expanded-state/swap-settings/SourcePicker.js
src/components/expanded-state/swap-settings/StepButtonInput.js
src/components/expanded-state/swap-settings/SwapSettingsState.js
src/screens/CurrencySelectModal.js
src/screens/ExplainSheet.js

Fixes TEAM2-429 TEAM2-430
handles all settings functionality and currency selection network switching
toggling flashbots, adjusting route, editing slippage, & resetting to defaults 
also renamed some callbacks for readability
green = gucci

swaps: settings e2e

---

src/screens/SendConfirmationSheet.tsx

Fixes RNBW-4254
I replaced text components with new design system. ~~The "trade off" is that DS doesn't support 26px size which is used here (max is 23).~~

Fix spacing issues on transaction review sheet

---

package.json
yarn.lock

Bumping `undici` to fix audit check.

bump undici

---

e2e/swapSheetFlow.spec.js
src/components/expanded-state/SwapDetailsState.js
src/components/expanded-state/swap-details/SwapDetailsContent.js
src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
src/components/expanded-state/swap-details/SwapDetailsFeeRow.js

Fixes TEAM2-428
added review sheets to e2e
- mainnet
- polygon
- optimism
- arbitrum is commented now since the test wallet doesn't have enough funds 😓 
- run e2e locally

swaps: add review sheet to e2e

---

e2e/discoverSheetFlow.spec.js
src/components/discover-sheet/DiscoverSearch.js
src/components/exchange/ExchangeAssetList.js
src/hooks/useSwapCurrencyList.ts

Fixes RNBW-4117
Adding E2E for ordering of discover search list.

Profiles: Add E2E for discover search ordering

---

android/build.gradle

Fix detox build

---

CODEOWNERS

After recent problems with navigation,e g.,
- non-consistent sheets with swap aggregator (android)
- last minute problems on profiles
and the general observation that a lot of changes are quite nonsense here (e.g., some presents clearly doing nothing, because they should be used for a different type of navigator) I hope this is a good idea to have at least temporarily some lock over those files.
I talked with @jinchung and she shares my understanding. Additionally, this is a good indicator we need to have a knowledge about the navigation better distributed

Update CODEOWNERS to include navigation

---

src/components/secret-display/SecretDisplayCard.tsx
src/components/secret-display/SecretDisplaySection.tsx
src/components/settings-menu/BackupSection/AlreadyBackedUpView.tsx

Fixes RNBW-4265
Fixes TEAM2-470
Fixes TEAM1-133
- Fixed button shadow clipping on Android
- Fixed secret phrase display container on Android
- Fixed secret phrase display container dark mode on iOS
- Fixed secret phrase button having the wrong color with dark mode
- Fixed biometrics explainer position and padding
- Discovered and reported RNBW-4339
| Android Button Before | Android Button After |
|-----------------------|----------------------|
| ![Screenshot_20220819-224223](https://user-images.githubusercontent.com/6843656/185712370-1fedb7fc-00a7-4cad-a38b-59264527ca82.png) | ![Screenshot_20220819-231618](https://user-images.githubusercontent.com/6843656/185712400-b9083756-a832-4ab0-ab83-d7e800fb786f.png) |
| Android Secret Before | Android Secret After (Light) | Android Secret After …

Fix secret phrase display

---

src/campaigns/swapsPromoCampaign.ts

Fixes RNBW-4409
added a network check so we dont show on goerli 
logs: https://cloud.skylarbarrera.com/Screen-Shot-2022-08-29-17-35-51.61.png
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2022-08-29-17-36-29.mp4

swaps promo: add network check

---

e2e/hardhatTransactionFlow.spec.js
src/redux/uniqueTokens.ts

Fixes RNBW-4416
The logic we have here is not the best, this PR fixes the bug but we need better code for sure
watch a wallet and make sure NFTs are loading

fix RNBW-4416

---

src/components/settings-menu/DevSection.tsx
src/config/experimental.ts

Fixes RNBW-4423
- prefixed `AsyncStorage.clear()` with `await`
https://www.loom.com/share/9964fc36dfbe458bb25cf404882bffba
- make sure it doesn't crash
- make sure async storage is actually cleared

fix clear async storage crash

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v.1.7.4 & Android 144

Version bump iOS v.1.7.4 & Android 144

---

package.json
yarn.lock

Includes https://github.com/rainbow-me/eslint-config-rainbow/pull/93 and https://github.com/rainbow-me/eslint-config-rainbow/pull/83.
Lint should pass (and we should have fewer warnings now).

chore: upgrade eslint-config-rainbow

---

e2e/walletAvatarOptions.spec.js
src/components/discover-sheet/DiscoverHome.js
src/hooks/useOnAvatarPress.ts

https://www.loom.com/share/812f309342024b7f87d904708211b27d video with audio for the cases

update ENS registration entries

---

src/components/settings-menu/BackupSection/AlreadyBackedUpView.tsx
src/components/settings-menu/BackupSection/NeedsBackupView.tsx
src/screens/SettingsSheet.tsx

Watch wallet backup scenario

---

src/components/settings-menu/BackupSection/AlreadyBackedUpView.tsx
src/components/settings-menu/BackupSection/NeedsBackupView.tsx
src/screens/SettingsSheet.tsx

Cherry picking commits from https://github.com/rainbow-me/rainbow/pull/4146

Fix: Watch wallet backup scenario

---

CHANGELOG.md
src/components/backup/RestoreCloudStep.js
src/handlers/authentication.ts
src/model/backup.ts

Reverts rainbow-me/rainbow#4012

Revert backup PIN

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.7.5 & android 145

Version bump iOS v1.7.5 & android 145

---

src/redux/wallets.ts

Fix default account selection

---

src/components/exchange/CurrencySelectionList.tsx
src/components/exchange/ExchangeAssetList.tsx
src/components/exchange/ExchangeSearch.tsx
src/screens/CurrencySelectModal.tsx

Fixes TEAM2-494
This PR tackles the child components of CurrencySelectModal. 
Pleas test the currency select modal that can be accessed through swaps, deposit, discover tab.

Part 2: conversion of CurrencySelectModal to TS and new DS components

---

.github/workflows/macstadium-android-e2e.yml

This is the initial work to have our tests running for android on macstadium

Create macstadium-android-e2e config

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.7.6 & android 146

Version bump iOS v1.7.6 & android 146

---

e2e/swapSheetFlow.spec.js
globals.d.ts
src/hooks/useSwapDerivedOutputs.ts

Fixes RNBW-4491
with https://github.com/rainbow-me/rainbow/commit/38071a2cd36309ecf515e3f4ffac06caa82739fd#diff-d7555f0c12b00ac091459b5a69d184f5582cd342c0c77b2bfc1d42a18c315c29 we removed some needed env vars for swaps, i added them back and left a comment to not remove these in the future
waiting for TF to confirm

fix: add swaps env vars back

---

src/components/settings-menu/BackupSection/NeedsBackupView.tsx
src/screens/SettingsSheet.tsx

Pkeys are not considered primary so we have to use the non watched wallet instead of the primary as a default.
Slack

use non watched wallet instead of primary

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.7.7 & android 147

Version bump iOS v1.7.7 & android 147

---

src/screens/ExchangeModal.tsx

Fixes TEAM2-493
To calculate the USD value of the swap we no attempt to calculate the value from the output token if it cannot be derived from the input token. We also perform another check to explicitly return an empty string from the result as other functions dont throw but instead return invalid string values.
If you have access to segment you can perform some swaps to see if the `amountInUSD` value is coming through accurately.

Add extra USD amount calculation and add explicit check invalid values for analytics

---

src/components/expanded-state/CustomGasState.js
src/components/expanded-state/custom-gas/FeesGweiInput.tsx
src/components/expanded-state/custom-gas/FeesPanel.tsx
src/components/expanded-state/custom-gas/FeesPanelTabs.tsx
src/components/expanded-state/custom-gas/GweiInputPill.tsx

Fixes RNBW-4508
just UI alignments and linear ticket
before https://www.loom.com/share/c1ca01c2424249969dfc6bfafce1b353
after https://www.loom.com/share/a700bfb8fa394043b24ec4afcce2fb9f
- test sizes are the same (16 px)
- gas component opens on right on top of keyboard, it had additional padding between keyboard and gas buttons
- icons are text are aligned correctly

gas: UI alignments and tweaks

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump iOS v1.7.8 & android 148

Version bump iOS v1.7.8 & android 148

---

.github/workflows/macstadium-android-e2e.yml
e2e/jest.e2e.config.js

Fixes RNBW-4540
Switching max workers from 4 to 1 since we can't parallelize hardhat related tests.
NO
CI should be green

Avoid parallelizing tests

---

package.json
yarn.lock

audit - vm2

---

package.json
yarn.lock

https://github.com/advisories/GHSA-36jr-mh4h-2g58

audit d3-color

---

src/references/ens-intro-marquee-names.json

e2e failing in original external PR
Closes https://github.com/rainbow-me/rainbow/pull/4204

Add worm.eth to ENS marquee

---

e2e/walletAvatarOptions.spec.js

Remove 3rd arg from walletAvatarOptions.spec.js

---

src/handlers/transactions.ts

fix: transaction press while sending ens 

---

src/notifications/analytics.ts
src/notifications/settings.ts

Fixes TEAM2-516
- Added event tracking for subscribing/unsubscribing to notification topics when the settings are changed.
- Refactored / DRY'd some code.
No visual changes.
- Changing notification settings.
- Checking if events roll through to segment.

Feat: Track changed settings for Notifications

---

src/components/expanded-state/swap-details/SwapDetailsContent.js
src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
src/languages/_english.json
src/languages/_french.json
src/references/swap/bridges.ts

Fixes TEAM2-466
for cross chain swaps we now show the new ui elements. this does not affect same network swaps. 
https://cloud.skylarbarrera.com/Screen-Recording-2022-10-05-14-40-49.mp4
NOTE: still needs android PoW
cross network and same network swaps, check review sheet for the correct ui elements

swaps: new swapping via 

---

src/components/coin-row/TransactionCoinRow.js
src/handlers/transactions.ts
src/helpers/transactionActions.ts
src/helpers/transactionPressHandler.ts

Fixes TEAM2-519
* Added new analytics event (Tapped Transaction Details Menu Item)
* Check if the event is logged properly in the segment debug panel

add tracking new event Tapped Transaction Details Menu Item

---

CODEOWNERS

feat: update codeowners

---

src/components/discover-sheet/DiscoverSearch.js
src/components/exchange/ExchangeAssetList.tsx
src/components/list/NoResults.tsx

Fixes RNBW-4618
- fixed android crash (see linear ticket)
- fix no search results ui on discover search
https://www.loom.com/share/6fa11c1efdbe420caa2945b361d39322
1. no crashes (see linear ticket for steps to reproduce crash)
2. no search results ui is correct on discover search (not the same as swaps token search)

Two fixes for release

---

yarn.lock

Ran [yarn-deduplicate](https://yarnpkg.com/package/yarn-deduplicate#readme) and it looks like it cleaned up the deps a bit. e2e are still passing so that's a good sign too.
This should make installing faster along with reducing the number of deps.

yarn-deduplicate

---

package.json
yarn.lock

https://github.com/advisories/GHSA-f8q6-p94x-37v3

audit minimatch

---

src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx

Fixes RNBW-4625
js type in ts :smileyfaceemoji:

fix: add xtra type check for accountColor

---

src/navigation/Routes.android.js
src/navigation/Routes.ios.js
src/screens/RestoreSheet.js

* Changes some code in the RestoreSheet screen
* Made it platform-specific to address the issue
Before on my Pixel 6
After on pixel and iOS:
https://user-images.githubusercontent.com/16062886/195832119-4d53d487-0317-4392-b487-42923e26ce67.mp4
https://user-images.githubusercontent.com/16062886/195832234-1f44eecb-54d7-4ad1-8685-a2cc8386d8e7.mov
* Test Restore Sheet functionality, and mainly it's looks on Both Android and iOS

Fix Restore sheet gap on Android

---

index.js
src/App.js
src/init.ts

Reverts rainbow-me/rainbow#4306

Revert "feat: async init App"

---

.github/workflows/macstadium-e2e.yml

issue that is making the step fail is fixed here: https://github.com/slackapi/slack-github-action/releases/tag/v1.23.0

chore: bump slack version for e2e

---

src/hooks/useSwapDerivedOutputs.ts

Slack thread: https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1666570461390639

Restore internal swaps

---

package.json

iPhone 11 sim is no longer shipped with latest xcode versions.

Bump sim to iPhone 13

---

src/components/settings-menu/AppIconSection.tsx
src/featuresToUnlock/unlockableAppIconCheck.ts
src/featuresToUnlock/unlockableAppIcons.ts
src/screens/ExplainSheet.js
src/screens/WalletScreen.js

Fixes RNBW-4614
added custom icon tracking 
should be a no op, but u can spoof a check and double check the logic

add icon analytics

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

Version bump 1.8.1 / versionCode 152

---

src/helpers/tokenSectionTypes.ts
src/hooks/useSwapCurrencyList.ts
src/languages/_english.json
src/languages/_french.json
src/screens/CurrencySelectModal.tsx

Fixes TEAM2-525
adding i18n for token section types
https://cloud.skylarbarrera.com/Screen-Shot-2022-10-14-14-17-34.58.png

swaps: i18n token sections

---

src/screens/RestoreSheet.js

Fixes APP-149
Kuba made a fix for the first screen ( #4297 ) in our "I already have a wallet" flow, but it broke another flow.
On Linear
Test Backup screen flow

Fix backup flow keyboard height

---

package.json
yarn.lock

Only a `0.0.2` patch increment. Treats https://github.com/advisories/GHSA-crh6-fp67-6883

fix: resolve patched @xmldom/xmldom

---

src/components/coin-divider/CoinDivider.js

very smol, a stray log got in from the Home Screen PR and its ruining local logs

rm stray log

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

version bump 1.8.2 / 153

---

src/languages/_english.json

Fixes APP-189
not sure what happened here, key exists in French but not in English 
merci beaucoup 👨‍🍳 😘

i18n: add English no thanks key 

---

src/helpers/networkInfo.ts
src/helpers/networkTypes.ts
src/references/chains.json
src/references/ethereum-units.json
src/references/index.ts
src/screens/ExchangeModal.tsx
src/styles/colors.ts
src/utils/ethereumUtils.ts

1st pr that will allow me to open subsequent scoped down BSC PRs
no op 
no op

bsc: add types, refs, & helpers

---

src/languages/_french.json
src/languages/index.ts

We were missing translations in French, and had some additional French translations that weren't in English. **This is assuming that the English translations are correct and should serve as our source of truth.**
Moving forward, TypeScript will throw and error if any translations are mismatched. So if we're missing some, we should fix-forward.

fix: align translations using english as truth

---

src/components/gas/GasSpeedButton.js
src/entities/assetTypes.ts
src/entities/gas.ts
src/handlers/gasFees.ts
src/redux/explorer.ts
src/redux/gas.ts

adding logic to handle bsc gas estimations 
nothing yet 
nothing yet

bsc: gas + add asset type

---

src/components/expanded-state/swap-details/SwapDetailsRefuelRow.js
src/screens/ExchangeModal.tsx
src/screens/ExplainSheet.js
src/utils/ethereumUtils.ts

Fixes APP-208
logic didnt handle BSC properly, fixed and added some extra props that should be there 
fixed the swap details refuel row as well 
refuel sheet
bsc: https://cloud.skylarbarrera.com/Screen-Shot-2022-11-10-17-58-58.02.png
not bsc: https://cloud.skylarbarrera.com/Screen-Shot-2022-11-10-18-33-49.64.png
refuel row: 
https://cloud.skylarbarrera.com/Screen-Shot-2022-11-10-18-34-04.31.png
peep pows

fix: bsc refuel icon

---

src/screens/CurrencySelectModal.tsx

I failed to test from before navigation, you can't scroll to an index if there is no data in the list yet.
I've added a check and now it doesn't crash
before: https://cloud.skylarbarrera.com/RPReplay_Final1668534525.MP4
after: https://cloud.skylarbarrera.com/Screen-Recording-2022-11-15-13-23-39.mp4

fix: new scroll behavior crash

---

src/helpers/buildWalletSections.tsx

iirc we only want to show the saving row if a user HAS savings. 
plan is to move this to a card so there's still a user option 
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-17-16-19-11.mp4

home: fix savings render logic

---

e2e/hardhatTransactionFlowSwaps.spec.js
e2e/swapSheetFlow1.spec.js
e2e/swapSheetFlow2.spec.js
src/components/exchange/NetworkSwitcherv2.tsx
src/config/experimental.ts

feat: cross chain swaps

---

src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
src/components/exchange/ExchangeTokenRow.tsx

Fixes APP-202
- adjusted font weights
Uploading Simulator Screen Recording - iPhone 14 Pro Max - 2022-11-17 at 13.06.02.mp4…

Adjust coin row text

---

src/components/gas/GasSpeedButton.js

Fixes APP-237
must have messed this up during BSC work 
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-22-11-10-42.mp4
PoW

fix: l2 speed options

---

ios/Podfile
ios/Podfile.lock
ios/Rainbow.xcodeproj/project.pbxproj

I broke dev builds by default after the flipper PR. This should fix it.

Fix dev builds after flipper PR

---

src/screens/LearnWebViewScreen.tsx

Fixes APP-236
- remove learn article header
- fix webview flash in dark mode
https://user-images.githubusercontent.com/15272675/203409001-07962ccb-5aed-4961-a400-b3305613cce5.mp4

Learn card webview fixes

---

src/screens/ExchangeModal.tsx

Fixes APP-253
disabling refuel feature

rug refuel

---

src/design-system/color/palettes.ts
src/screens/transaction-details/SingleLineTransactionDetailsRow.tsx
src/screens/transaction-details/ThinSymbolRow.tsx
src/screens/transaction-details/TransactionDetailsContent.tsx
src/screens/transaction-details/__tests__/shortenTxHashString.test.ts
src/screens/transaction-details/shortenTxHashString.ts

Fixes APP-34
* Implemented a transaction hash row for the upcoming new Transaction Details sheet
**More details in Linear**

Implement transaction hash row for new transaction details sheet

---

src/screens/ExplainSheet.js

Fixes APP-254
- icon unlock explainer wasn't navigating to app icon settings, fixed that
- small ui adjustments
https://www.loom.com/share/76b718759ac84abc81926049ce5f9355

Icon unlock explainer fix

---

src/components/expanded-state/swap-details/SwapDetailsContent.js
src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
src/hooks/useRainbowFee.js

Fixes APP-####
had no handling for diff native assets on other chains (matic & bnb)
eth -> matic on polygon: https://cloud.skylarbarrera.com/Screen-Shot-2022-12-01-13-22-05.53.png
l2 erc20 -> l2 erc20: https://cloud.skylarbarrera.com/Screen-Shot-2022-12-01-13-26-05.08.png
swap eth to dai: https://cloud.skylarbarrera.com/Screen-Shot-2022-12-01-13-25-23.34.png
fees should calculate properly

fix: multichain fee calc

---

src/helpers/isTestFlight.ts
src/logger/index.ts
src/logger/sentry.ts

feat: add separate TF env for Sentry

---

ios/Rainbow/Info.plist

rebase of https://github.com/rainbow-me/rainbow/pull/4444 
also removed all unused permission descriptions

fix: permissions strings

---

ios/Rainbow/Info.plist

revising to follow the following instructions
`Please revise the purpose string in your app’s Info.plist file for the camera to explain why your app needs access and include an example of how the user's data will be used.`
input encouraged

chore: fix camera permissions copy again

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

version bump - 1.8.4 / 155

---

src/components/cards/DPICard.tsx
src/components/cards/EthCard.tsx
src/components/coin-icon/ChainBadge.js
src/components/coin-icon/ChainBadgeSizeConfigs.ts
src/components/coin-icon/CoinIcon.tsx
src/components/exchange/DepositInfo.tsx
src/components/exchange/ExchangeField.tsx
src/components/exchange/NetworkSwitcherv2.tsx
src/components/expanded-state/AvailableNetworksv2.tsx
src/components/settings-menu/CurrencySection.tsx

* Changed Coin Icon to Typescript
* Removed a bunch of ts expect error comments where it was used in TS files

Refactor CoinIcon and related to TypeScript

---

package.json
patches/@ledgerhq+react-native-hw-transport-ble+6.27.2.patch
yarn.lock

Fixes APP-288
just adding deps + the patch since its broken without
CI should pass

chore: add ledger deps

---

CHANGELOG.md
android/app/build.gradle
ios/Rainbow.xcodeproj/project.pbxproj
package.json

version bump 1.8.5 / 156

---

package.json

just bumping our dev builds to use a newer device 
nit
nit

chore: bump iOS dev device 

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/me/rainbow/MainApplication.java
android/settings.gradle
ios/Rainbow/Info.plist

Fixes APP-292
added bluetooth permissions, piped up android deps

ledger: permissions + android deps 

---

src/languages/_english.json
src/languages/_french.json
src/screens/transaction-details/components/TransactionDetailsAddressRow.tsx
src/screens/transaction-details/components/TransactionDetailsStatusActionsAndTimestampSection.tsx

Fixes APP-302
* Changed the subtitle to now be ENS or formatted address
* Moved leftover copies to translations file

Fix context menu subtitle in new transaction details sheet

---

src/components/expanded-state/LiquidityPoolExpandedState.js
src/components/expanded-state/chart/ChartExpandedStateHeader.js
src/components/value-chart/Chart.js
src/hooks/charts/useChartData.ts
src/hooks/charts/useChartDataLabels.ts

Remove last chart price override and related cleanup

---

src/components/expanded-state/LiquidityPoolExpandedState.js
src/components/expanded-state/TokenIndexExpandedState.js
src/components/value-chart/Chart.js
src/components/value-chart/TimespanSelector.js
src/hooks/charts/index.ts
src/hooks/charts/useChartData.ts
src/hooks/charts/useChartInfo.ts
src/hooks/charts/useChartThrottledPoints.ts
src/hooks/index.ts
src/redux/charts.ts
src/utils/ethereumUtils.ts

Followup on removing last chart price overrides

---

src/logger/debugContext.ts
src/redux/walletconnect.ts
src/screens/ConnectedDappsSheet.js
src/screens/TransactionConfirmationScreen.js
src/utils/walletConnect.ts

Adds `walletconnect` debug context and swaps in the new logger in our wallet connect related files. We could def do more logging, but in this PR I've only migrated what was there.
None
If it builds and runs it should be fine.

feat: add `walletconnect` debug context, swap in logger

---

src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
src/components/cards/EthCard.tsx
src/components/expanded-state/asset/ChartExpandedState.js
src/model/config.ts

Update remote config

---

src/screens/transaction-details/components/TransactionDetailsValueAndFeeSection.tsx

Fixes APP-342
* Managed to fix transaction badges and coin icons in L2 transactions

Fix L2 transaction badges in transactions history

---

src/logger/README.md
src/logger/__tests__/logger.test.ts
src/logger/index.ts

Now that we've used the new logger for a couple months I've decided we need more data. This PR introduces `logger.log`, and now sends `logger.log` and `logger.warn` to Sentry as separate **Issue*s in the top-level list view.
See the README in this directory for more info.
Added tests 👍

feat: add logger.log, send log/warn to Sentry
