src/handlers/uniswap.ts
Fixes TEAM2-335
Use binary search to find out the ideal gas estimation for approve + swap scenarios using trace_call.
We were only going up to 450k gas before and now we go up to 1M with the same amount (or less requests)
https://recordit.co/SCeP50PbCz
Test any approval + swap and you should see something similar to my PoW. Other types of swaps are not affected.
=> improve approve+swap gas estimation algo

src/handlers/uniswap.ts
bumping from 5% to 10% with the hope of preventing this kind of failures https://etherscan.io/tx/0x4985c95b3a8803c96971aaf8369ca0f29f39e375916b37a6fb8114ec45708014
None
Shouldn't be any noticeable change. We're just bumping the const that's the padding multiplier.
=> Bump gas estimation padding for swaps

src/components/asset-list/RecyclerAssetList2/core/ExternalENSProfileScrollView.tsx, src/hooks/useAndroidScrollViewGestureHandler.ts
Fixes TEAM2-357
This PR fixes an issue on Android where a user was unable to dismiss the profile sheet.
https://www.loom.com/share/e2ad9aa71d57468ea5e269df47e623ab
Make sure you can dismiss the profile sheet on Android & iOS
=> Profiles: Unable to swipe down on Profile Sheet on Android

src/components/discover-sheet/DiscoverSearch.js
Fixes TEAM2-356
Updated the order of search results based on feedback from @christianbaroni to include Profiles above _unverified_ and _low liquidity_ tokens.
| Search | Search |
| ------ | ------ |
| ![CleanShot 2022-08-03 at 09 46 30 PM@2x](https://user-images.githubusercontent.com/6843656/182697191-15d24681-9a96-47e7-b01c-10e0111a7c60.png) | ![CleanShot 2022-08-03 at 09 46 49 PM@2x](https://user-images.githubusercontent.com/6843656/182697241-40873c62-85df-4246-8027-6792efe44cc8.png) |
Searching and checking the results.
=> Reorder search groups to highlight profiles

src/components/images/ImagePreviewOverlay.tsx
Fixes TEAM2-352
This PR fixes an issue where our `ImagePreviewOverlay` component was not aware of the scroll view. Causing wack things to happen if you were to scroll up fast initially.
iOS:
https://www.loom.com/share/daf23a12056c4c52912796247e1bbaa8
Android: 
https://www.loom.com/share/5035fb59c7484c718eccf78d9b403d95
Ensure avatar/cover photos are still zoomable on the expanded ENS NFT view, and also the profile sheet.
=> Profiles: Fix ENS expanded state zoomable cover photo

src/components/ens-profile/ProfileSheetHeader.tsx
Fixes RNBW-4134
we now resize the cover image, looks like it gets used in a p smol view so 400 should still look crisp
https://cloud.skylarbarrera.com/Screen-Recording-2022-08-03-18-45-55.mp4
^ note example is at width of 200 so it looks kinda blurry
load up brdy.eth and make sure cover loads fast asf
=> profiles: resize + sign cover photo

src/components/discover-sheet/DiscoverSearchInput.js
Fixes RNBW-4051
see if it works, and is centered. 
I checked on many phones, but just on those narrow this is really noticeable
=> Center search icon on android discover

src/components/fields/AddressField.js, src/components/send/SendHeader.js, src/helpers/validators.ts, src/screens/SendSheet.js
Fixes RNBW-3948
Fixed issues around typing/selecting addresses in the Send flow:
- Debounced the input value so we aren't spamming the RPC & confusing the UI
- Eagerly validating the address (via checking if it's in the right format), so we aren't waiting for ENS names to resolve
- note: the user still won't be able to send the transaction until the address has been validated
https://www.loom.com/share/f721767c58a9477eab727c6cdefb1f03
- Ensure that an ENS name correctly resolves & still able to send transaction,
- Ensure that an Unstoppable Domain name correctly resolves & still able to send transaction,
- Ensure that a plain address correctly resolves & still able to send transaction
- Ensure that you can't send a transaction if the ENS name, UD name or plain address is invalid
=> Fix Send flow contact issues

src/helpers/assets.ts, src/hooks/useCollectible.ts, src/hooks/useFetchUniqueTokens.ts, src/redux/uniqueTokens.ts
Fixes TEAM2-369
Fixes RNBW-4159
This PR fixes an issue where a user would see an "undefined #undefined" NFT just after registering their ENS.
Also fixes RNBW-4159 as we now use `id` as a unique identifier on the asset list.
https://www.loom.com/share/c4c01e80728e4ce48c4c516a1d027dbf
After registering an ENS, ensure that you correctly see your ENS NFT in your wallet, as well as in the profile sheet (when you search for your wallet)
=> Profiles: Fix undefined ENS NFT after registering an ENS

src/apollo/client.ts
Fixes TEAM2-367
We are eagerly caching every The Graph ENS response in-memory via Apollo, however, we don't need to do this since we are already implementing in-memory caching via React Query for everything that uses the ENS client apollo instance, so the apollo cache is redundant.
=> Profiles: Fix ENS owner caching issue

src/components/ens-profile/ActionButtons/MoreButton.tsx
Fixes TEAM2-384
Discover Search blocks interactions, so when we navigate off of it we need to tell it to turn tf off
I had added this for the showcase sheet, just needed to add to the new one 
https://cloud.skylarbarrera.com/Screen-Recording-2022-08-04-18-09-05.mp4
try to open wallet from search, try to open from anywhere else -> get to swipin
=> profiles: turn off search -> renable interactions

src/hooks/useENSPendingRegistrations.tsx, src/screens/ENSConfirmRegisterSheet.tsx
Fixes TEAM2-360
- Fixed the keyboard showing unexpectedly when you try to finish your ENS registration because it was trying to focus on the input below.
- Dismiss function was only scoped for Android — it's now being called on Android and iOS. 
- Dismiss function was running before navigation finished its thing, so the search input managed to catch focus and pull up the keyboard again while the sheet was being loaded. 
- It's now being called only after the navigation event happens and the sheet is properly loaded.
https://user-images.githubusercontent.com/6843656/182961821-412c4cb8-a1c4-4c66-be02-8538daf51984.mp4
1. Search for an available ENS and start registering.
2. Kill the app.
3. Launch the app and go back to the ENS search view from the card in Discover.
4. Tap on 'Finish' for …
=> Fix keyboard not dismissing when registering ENS

src/hooks/useOnAvatarPress.ts, src/languages/_english.json, src/languages/_french.json
Fixes RNBW-4108
On Android we revert back to emoji shuffle. Check linear ticket for more context.
https://user-images.githubusercontent.com/5769281/182895113-2a8aee17-3013-4d82-9d7d-377ebb622055.mp4
iOS video coming tomorrow.
Verify that emoji picker works on iOS and on Android is replaced with shuffle.
=> Revert to emoji shuffle on Android

src/components/change-wallet/AddressRow.js, src/components/coin-row/FastTransactionCoinRow.tsx
Fixes RNBW-4197
Prop name changed but it wasn't reflected in PRs that followed the change.
Before: crash. After: no crash.
Context menu in transactions (speed up etc.) and editing wallets in switch wallet sheet.
=> Fix context menu post prop rename

src/hooks/useENSRecordDisplayProperties.tsx
I notice this trick works for Samsung devices. Probably the earth icon is somehow wrongly evaluated for size 
Before:
After:
=> Fix URL wrapping

src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx, src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
Fixes TEAM2-385
adds image sizing for avatar uploads + moves fn to callback & adds error reset
header/avatar should upload normally
=> profiles: header + avatar tweaks

src/components/expanded-state/ens/InfoRow.tsx, src/components/expanded-state/ens/ProfileInfoSection.tsx, src/hooks/useENSRecordDisplayProperties.tsx, src/utils/ens.ts
Fixes RNBW-4191
Fixes RNBW-4190
This PR opens the NFT expanded state for NFT cover photos.
Android:
https://www.loom.com/share/0334e8e55ebf44ba9b26cabebaf69bd4
iOS:
https://www.loom.com/share/785ce1fa7d3c46959b80f88f109cfafa
- Ensure that NFT cover photos open up the NFT expanded state of the cover NFT.
- Ensure that normal cover images are still zoomable.
=> Profiles: Make cover NFTs open NFT expanded state

src/navigation/RegisterENSNavigator.tsx
Fixes RNBW-4158
we were not reseting the avatarMetadata so the image was still being loaded in after resetting the navigator. now we reset
https://cloud.skylarbarrera.com/Screen-Recording-2022-08-05-13-50-08.mp4
issue was only works with images, NFTs were never broken. so follow the flow in the ticket
=> profiles: fix da colors

src/screens/ExchangeModal.js
Fixes TEAM2-329
there was some old logic from the first gen of swaps that was blocking gas being updated when only 1 token was selected, removed in the first commit. 
the second commit is my attempt to fix the layer2 gas showing layer 1 estimations, `defaultGasLimit` should update as expected per network
before: https://cloud.skylarbarrera.com/Screen-Recording-2022-08-01-17-29-48.mp4
after: https://cloud.skylarbarrera.com/Screen-Recording-2022-08-01-17-35-27.mp4
gas should update normal for swaps, & savings. switching networks should trigger an update in gas price
=> swaps: adjust gas default logic

e2e/hiddenTokensFlow.spec.js, src/helpers/assets.ts, src/hooks/index.ts, src/hooks/useExternalWalletSectionsData.ts, src/hooks/useFetchHiddenTokens.ts
Fixes TEAM2-389
This PR makes Hidden NFTs work with profiles. Since we don't use redux for data fetching on the profiles screen, need to add interop. Obviously having duplicate code in 2 diff places is not good, but we will need to refactor this in Code Foundations to be universal.
https://user-images.githubusercontent.com/7336481/183329744-cf4a3386-625e-4636-84c7-055ea80fcae5.mp4
Hide an NFT in a wallet, and ensure that it is hidden on the profiles screen.
=> Profiles: make hidden nfts work with profiles

src/components/ens-profile/ProfileSheetHeader.tsx, src/components/expanded-state/ens/InfoRow.tsx, src/components/expanded-state/ens/ProfileInfoSection.tsx, src/hooks/index.ts, src/hooks/useENSUniqueToken.ts, src/hooks/useExternalWalletSectionsData.ts, src/hooks/useFetchUniqueTokens.ts, src/hooks/useOpenENSNFTHandler.ts, src/redux/uniqueTokens.ts, src/screens/ProfileSheet.tsx
Fixes TEAM2-387
This PR fixes an issue where pressing on ENS NFTs wouldn't open the expanded state (and instead open a zoomable preview instead). I also composed our usages of the logic to do this into a hook (since we were repeating a lot of code).
I also refactored `useFetchUniqueTokens` to be a bit more performant (we were previously fetching unnecessarily), and made it possible to only fetch tokens in-memory when needed (instead of infinite fetching every time). We can definitely make this hook better for infinite fetching, but we can rethink that for the Code Foundations project.
https://www.loom.com/share/51502d82859d4c45974e3ce9f1e28b25
- On the profile screen, ensure that NFT avatar/cover opens the NFT expanded state,
- On the profile screen, ensure that image avatar/cover opens a …
=> Profiles: Refactor & fix opening ENS NFTs

src/hooks/useImportingWallet.ts, src/screens/WalletScreen.js
Fixes RNBW-4201
I changed the way we remove the stack so this is not vulnerable to the race condition while creating the wallet. Previously this was possible that we wanted to remove the Welcome screen before having a new screen set up. Here, I moved the logic to the wallet component so this is 100% that the other component exists and we can remove the one beneath. 
https://user-images.githubusercontent.com/25709300/183224801-e8400fde-149c-42f4-a2a8-e3bc8389f31d.mov
Create a wallet from seeds, try to "dismiss" the wallet sheen (see if there's a welcome screen below), and check if the navigation is generally not broken.
=> Remove the screen under wallet screen after navigating after creating a wallet from seeds

src/screens/ENSIntroSheet.tsx
Fixes RNBW-4205
- added extra bottom padding to ens intro sheet for android
Pixel 3a sim:
Physical galaxy a52:
=> Profiles: Tweak android padding

src/components/ens-registration/TextRecordsForm/SelectableButton.tsx, src/components/inputs/InlineField.tsx, src/screens/ENSAssignRecordsSheet.tsx
Fixes RNBW-4185
- Fixed alignment of the dismiss keyboard button in ENS text records form on Android & iOS
- Fixed alignment of buttons for choosing ENS text records in the form on Android
- Tweaked vertical alignment of @ and input on both iOS and Android
Did not manage to fix the `Name` and `Bio` inputs shifting when going from placeholder to text. It requires a bigger design system change that touches all inputs, so I made a different ticket for that issue in Linear to do after release.
ENS registration text records form.
=> Android: Fix non-centered buttons in ENS reg

src/screens/PinAuthenticationScreen.js
Fixes RNBW-4093
Due to the delay, we were skipping PIN confirmation. But Pin worked fine
https://linear.app/rainbow/issue/RNBW-4093/android-skipping-pin-confirmation
Before: https://user-images.githubusercontent.com/48593211/183376678-d780d9ab-4cb6-42b9-850e-8148d793c634.mp4
After: https://user-images.githubusercontent.com/48593211/183376211-4e6ab3ce-fee9-402d-b6d6-3f557f1625d2.mp4
Go to wallet creation and quick enter PIN, you should fill PIN and be able to confirm it
=> PIN confirmation skipping

src/components/ens-registration/SearchInput/SearchInput.tsx
Fixes RNBW-4223
Removed the `showAfterInteractions` option for iOS which was causing keyboard issues when bottom sheets in the ENS registration flow popped up.
https://user-images.githubusercontent.com/6843656/183540155-2ff70f1a-ced4-4ae8-a0b8-b98c31860d5b.mp4
Trying to finish ENS registration.
=> Fix ENS registration keyboard popping up in sheet

src/components/expanded-state/UniqueTokenExpandedState.tsx, src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Fixes TEAM2-402
we were using `accountENS` by default to "View on web" links, now we use `cleanENSName` to open the ens name according to the NFT
https://www.loom.com/share/c6c986fd3bba404fae55eba3116c4a28
- watch account a.eth
- go and search for b.eth profile
- go to an ENS NFT and press "View on web", on android choose a browser and the app to open the link, both should open the ENS profile
=> profiles: view on web ens name

src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx, src/components/ens-profile/ProfileCover/ProfileCover.tsx, src/components/ens-profile/ProfileSheetHeader.tsx, src/components/images/ImagePreviewOverlay.tsx, src/ens-avatar/src/specs/erc1155.ts, src/ens-avatar/src/specs/erc721.ts, src/utils/getLowResUrl.ts
Fixes TEAM2-395
Fixes TEAM2-401
Fixes TEAM2-400
This PR fixes 3 bugs that were observed with large sized cover photos & SVG-based cover photos.
- Refactored `getLowResUrl` to better utilize CDN resizing (added in replacing the existing `=w` value)
- Use `getLowResUrl` instead of `maybeSignUri` to take advantage of google CDN resizing
- Convert ENS image SVGs to PNGs
- Fixed an issue where the cover photo would overlap the avatar on the profile sheet if it took longer to load.
Android:
https://www.loom.com/share/773568badfb7427299ef18cf4300b97a
iOS:
https://www.loom.com/share/1c1f65815aa44d45aa85f5667970647a
- Ensure avatar/cover photos still load and render properly
- Ensure SVG cover photos load properly
- Ensure large cover photos load properly
Good test wallets are 0xtester.eth and …
=> Profiles: Image edge cases

src/components/ens-profile/ActionButtons/SendButton.tsx
Fixes RNBW-4235
See file: `src/components/sheet/sheet-action-buttons/SendActionButton.js`
IMO the `if` should only check for `isNativeStackAvailable`.
I tested on Android and now it works.
No visual differences, just behavior.
Run on iOS and Android. Go to some ENS profile and press send button. On both platforms it should pre-fill the address of the profile.
=> Fix send button not pre-filling address in ENS profile

src/components/ens-profile/ActionButtons/ActionButton.tsx
Fixes RNBW-4233
Shadows of action buttons in ENS profile sheet were cropped on Android.
|Before|After|
|--|--|
|![Screenshot_20220809-121908_Rainbow](https://user-images.githubusercontent.com/5769281/183623816-033c0f70-222a-4a3e-a808-e5ee9d2fe16d.jpg)|![Screenshot_20220809-131300_Rainbow](https://user-images.githubusercontent.com/5769281/183623933-19087802-90c0-453c-9a6b-eaa562a61ec9.jpg)|
Check shadows.
=> Fix cropped shadow on Android in ENS profiles

src/components/send/SendAssetFormCollectible.js
Fixes TEAM2-397
regression from https://github.com/rainbow-me/rainbow/pull/3829 , missed during dev QA. menu pkg doesn't play well with touchables + we needed to add elevation.
https://user-images.githubusercontent.com/29204161/183689811-1cf3250c-6405-4c65-bee8-716be74a47d0.mov
open the gas speed menu for erc20 + NFT on both platforms
=> fix NFT gas button rm touchable + elevation

src/hooks/useENSRegistrationActionHandler.ts
https://sentry.io/organizations/rainbow-me/issues/3299115626/?query=is%3Aunresolved+release%3Ame.rainbow%401.7.0%2B40&statsPeriod=14d
happening because we don't have callback defined for executeRap for renewAction, just adding fallback, this is not a bug making the user see something wrong
=> profiles: clean up sentry logs

src/languages/_english.json, src/languages/_french.json, src/utils/__tests__/ens.test.ts, src/utils/ens.ts
Fixes TEAM2-412
added validation for empty subdomain and apostrophe
also added lang.t to that file
https://www.loom.com/share/c55678d54d3d49b9a0ae45d7a644efd1
=> profiles: name validations

hardhat.config.js
The e2e flow e2e/hardhatTransactionFlow.spec.js has been flaky since day one in the scenarios where the gas goes down since the test start.
We start with base fee of Y when we fork mainnet and then we keep getting updates from meteorology with real amounts (lower) so we underpay and txs fails, making the whole test fail and adding a few extra minutes. This PR fixes it.
This only affects e2e so if it's green it's good.
=> Make hardhat related tests less flaky

src/model/preferences.ts
See Slack: https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1660078639708399?thread_ts=1660078216.499479&cid=CGUDDJYNL
Sends two new messages to Sentry with `Error` level severity.
=> Capture Sentry message on web preference API failures

src/components/ens-registration/ConfirmContent/EditContent.tsx, src/components/ens-registration/ConfirmContent/RegisterContent.tsx, src/components/expanded-state/ens/InfoRow.tsx
Fixes TEAM2-415
Making it so we can actually see the toggle on light mode.
=> Profiles: darken track color of switch on android

src/components/expanded-state/ens/InfoRow.tsx
Fixes RNBW-4246
disabling on android for now 
https://user-images.githubusercontent.com/29204161/183943102-0e4473f7-d66f-4f45-8417-6ef24fe74689.mov
try to press it 🔫
=> profiles: disable image overlay on android

src/components/send/SendAssetForm.js, src/screens/SendSheet.js
Fixes RNBW-4241
Context:
https://rainbowhaus.slack.com/archives/C01GD1F2ZTL/p1660083877054629
I changed the way keyboard is handled. I think it was done a bit weird, probably added separately for Android and iOS. After unifying it it seems to work better.
Another difference is that I restore `flex: 1` for Android token send sheet.
(I checked on iOS and no changes there)
Before:
https://user-images.githubusercontent.com/5769281/183881188-037ede54-af34-4c64-8e3e-77283b5e83a8.mp4
After:
https://user-images.githubusercontent.com/5769281/183881147-f05cd8f5-72c7-4e47-9eaa-8698ca925b72.mp4
Check send sheet on iOS, Android, sending NFT, sending token. The layout (placing of elements) should look ok. Both with keyboard on (both platforms) or dismissed (Android).
=> Fix keyboard layout issues in SendSheet on Android

src/screens/SendConfirmationSheet.tsx, src/screens/SendSheet.js
Fixes RNBW-4244
consolidated the confirmation screen height in one method `getSheetHeight`
https://www.loom.com/share/b938a874173e4dd1a770c684d0962a1d
- send mainnet token
- send L2 token to a wallet you own
- send L2 token to a wallet you don't own, you should see a checklist here
- send ens
- send nft
=> fix: confirmation screen height

src/components/ens-registration/RegistrationCover/RegistrationCover.tsx, src/hooks/useSelectImageMenu.tsx
Fixes RNBW-4251
- `coverUrl` is set to the empty string when the image is removed. this is a false-y value which caused the condition on the modified line to fail fast, with `coverUrl` as the return value. as a result, this string was trying to render as a RN component which caused the crash.
- @estebanmino found a bug that prevented cover images from uploading after removing a previous cover image. this is because `isRemoved.current` was set to true after any cover photo removal, with the intended goal of preventing `onUploadSuccess` from being called if the image was removed while being uploaded. to fix this, i set `isRemoved.current` to false upon selecting a new image.
https://user-images.githubusercontent.com/15272675/184008435-508a58f6-e90b-479a-9ca7-a237ff58740f …
=> Profiles: fix header removal crash

src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx, src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
fixing this issue
https://linear.app/rainbow/issue/TEAM2-403#comment-5e59da70
https://github.com/rainbow-me/rainbow/blob/develop/src/components/ens-registration/RegistrationCover/RegistrationCover.tsx#L58  is being triggered right after removing the image with the old url
=> profiles: improve photo removal

src/entities/uniqueAssets.ts, src/handlers/opensea-api.ts, src/parsers/uniqueTokens.js, src/references/opensea/index.ts, src/references/opensea/opensea-payment-tokens.json
Fixes TEAM2-340
Since the release of Seaport the OS api now returns active listings in a `seaport_sell_orders` object on the api response, this PR adds seaport order data to the api response and then also uses current_price from within the object to set the `currentPrice` property that is returned in the `UniqueAsset` type. 
This now means active listings should appear in the Expanded NFT sheet.
Find an actively listed NFT on ETh & Polygon and look to see if the NFT in the app displays sale price rather than "Last sold". 
Check that the correct amount is displayed and that the correct token symbol is used e.g ETH or DAI.
=> Fix missing active sale price in NFT expanded sheet

src/components/expanded-state/ens/InfoRow.tsx
=> Profiles: Fix description overflow

src/utils/ethereumUtils.ts
Fixes TEAM2-210
fetching on chain balances was fetching 'eth' as the address
(https://cloud.skylarbarrera.com/Screen-Recording-2022-08-03-13-59-25.mp4)
connect to rainbow buttond dapp or hop exchange with a wallet that had L2 ETH, create a new wallet with 0 balances. while using the new wallet try to send a TX from the dapp, it should now fetch the balances for the connected wallet it was undefined previously
=> fix L2 WC balances

src/hooks/useWatchWallet.ts
Fixes TEAM2-421
we weren't handle the case where you would only have a `watching` wallet and then you went to the profile and pressed unwatch
i followed what we're doing on the wallets sheet when deleting wallets, from here https://github.com/rainbow-me/rainbow/blob/develop/src/screens/ChangeWalletSheet.js#L327
ios https://www.loom.com/share/a65fc048302a4ea3b1956cd1c3b2a936
android https://www.loom.com/share/038bc343cf1a4360842864a4fb529d32
- have only 1 wallet in watching mode
- go to profile and unwatch
- it should send you to the welcome screen as we normally do when deleting wallets
=> profiles: fix unwatch last wallet in app

src/components/unique-token/Tag.js, src/parsers/uniqueTokens.js
Fixes TEAM1-100
Figma link (if any): N/A
Arbitrum NFTs that have Trove as their main marketplace will now show "View in Trove" in the action button on the NFT detail sheet. Their properties will also link to Trove's site with appropriate filters.
https://user-images.githubusercontent.com/16931094/184255723-e1b3b2dd-b9e8-473a-873d-9507e51d1c54.mov
^^ can use frannyverse.eth, and collection "Arbitrum Odyssey NFT"
open the NFT details sheet on an Arbitrum NFT that has Trove as main marketplace. you should see "View on Trove" as the button, and it should take you to the NFT's detail page on trove.treasure.lol. If the NFT has properties, you can check those direct you to Trove's site with the correct filters turned on.
=> fix: pull in Trove marketplace URL

src/screens/WalletScreen.js
Fixes RNBW-4055
Removed unused Animated.Code tag and Animated.Value
It was left out after some refactorings of RecyclerAssetList and is not used anymore. Confirmed the old usage in history of RecyclerAssetList, pre TypeScript migration migration.
Check revision 130c0b80a08c1654191bff3c517b5853e2a6354b for reference
* Check if recycling still works the same in wallets like `vitalik.eth` or `dom.eth` for the asset list
=> Remove unused Animated.Code call

src/raps/actions/swap.ts, src/redux/additionalAssetsData.ts, src/redux/explorer.ts
OP+GMX do not have mainnet addresses. When updating L2 balances we now create a unique id to check account assets or generic assets for pricing information when adding the updated balance. I verified with @brunobar79 that this is, unfortunately for now, a common pattern within the app.
Swapping for OP with an existing OP balance: https://recordit.co/NtihedGx0a
Swapping for OP without an OP balance: https://recordit.co/EPF3Cm3Yuf
Test that OP/GMX do not disappear from the assets list when:
* Swapping OP on optimism (input and output)
* Swapping GMX on arbitrum (input and output)
* I included a video of swapping for OP without an existing OP balance to show that this logic doesn't mess with asset discovery, but we should probably check that too.
I opened this in favor of the previous PR: …
=> [TEAM2-328] Use Unique Id Pattern to Grab No Mainnet Addy Prices

src/screens/WalletScreen.js
This PR is in support of #4001 : we want to handle situations where a user has a deprecated testnet set in state. This code gracefully reverts back to mainnet. I separated this onto its own branch for ease of testing.
=> Revert Unsupported Testnets To Mainnet

src/helpers/validators.ts
Fixes RNBW-2851
When someone pressed `.` a new empty item was created in the array, the parseDomain function read this empty string as valid which would cause the validation to work. This PR adds a check that the ENS suffix string should have a length greater than 0. This also applies to the unstoppable domain validation for consistency.
Add a new wallet to the app, when entering a ENS or unstoppable domain does the import button correctly become enabled after a valid domain is entered
Add a 0x address does this enable the import button
Add a seedphrase, does this enable the import button
Add a ENS name name does adding the `.` but nothing else enable the import button (it shouldnt)
=> Add check that ENS suffix is not empty string

src/components/expanded-state/custom-gas/GweiInputPill.js
Gwei input was covering part of the text input, detox gets really mad when components are covered
https://cloud.skylarbarrera.com/Screen-Shot-2022-08-17-13-41-37.25.png
ive stopped rendering it and we passing now
https://cloud.skylarbarrera.com/Screen-Shot-2022-08-17-13-44-31.74.png
this is what it looks like after the change: https://cloud.skylarbarrera.com/Screen-Shot-2022-08-17-13-41-55.33.png
green = gucci
=> chore: e2e -> hide gwei label for testing

src/apollo/queries.ts, src/handlers/ens.ts, src/hooks/useAccountENSDomains.ts
Fixes RNBW-4283
There was a bug where some users who do not have any ENS NFTs would not see their NFT collections. Seems like the cause of this was due to 2 related issues:
1. `fetchEnsTokens` returning a nullish value even though TypeScript says it is not nullish (`UniqueAsset[]`).
2. Seems like the typings for the ENS subgraph were incorrect, as `account` can be nullish, which caused the above issue to arise as TypeScript thought it was always defined. We should probably find a way to automate type syncing (and [use something like this](https://www.graphql-code-generator.com/)) between a remote GraphQL schema & the app. I can add this to the Data Fetching subproject in Code Foundations.
I fixed the above TypeScript issue, and also ensured `fetchEnsTokens` returns …
=> Profiles: Fix issue where a user could not see their NFTs

src/components/fields/BubbleField.js
Fixes TEAM1-105
Line height was specified here for Android but it seems to me that currently it behaves just ok without it while it causes problem when specified.
https://user-images.githubusercontent.com/5769281/184876457-07041852-8330-4665-8ca7-48a2e7139b0b.mov
If the bug from ticket is still present.
=> Fix line height in send form bubble input

src/components/token-family/TokenFamilyHeaderIcon.tsx, src/helpers/assets.ts
Fixes TEAM2-431
Figma: https://www.figma.com/file/O2iH8h2H00ycicwUHIfBah/profiles-spec?node-id=351%3A7681
- Fixing alignment of NFTs under the "Selling" row.
- Added the proper emoji for "Selling" as per the designs.
=> Profiles: Fix "Selling" NFTs alignment

src/hooks/useENSRecordDisplayProperties.tsx
We were using the incorrect telegram link
=> Profiles: fix telegram link

src/components/expanded-state/swap-details/SwapDetailsContent.js, src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
Fixes TEAM2-414
- Added invisible padding around the `More details` button in swap review sheet to make it easier to tap with your finger.
Going into swap review sheet and tapping on `More details` on Android and iOS.
=> Improve ‘more details’ tap target area for swaps

src/components/profile/ProfileMasthead.js
Adding a note about this view in case anyone ends up wasting a bunch of hours wondering why nothing is happening on iOS when you make changes to this file. Related to TEAM2-418.
=> Note about ProfileMasthead being used by Android

src/hooks/useInitializeWallet.ts
Fixes RNBW-3959
- Added a new parameter to wallet initialize time tracking, that adds three statuses to wallet
- `old` – Wallet was already there
- `new` – Wallet is newly created from scratch
- `imported` – Wallet imported from seed phrase
- Check if all the possible combinations for old new and imported wallets are logged properly in segment console
=> Add wallet statuses `new` `imported` and `old` to wallet initialize time tracking

.eslintrc.js
Fixes RNBW-4310
Separate PR for Linear's benefit. Set to `warn` for now because we have 525 violations in the codebase.
=> 🏛 Add lint rule to prevent spreading props

.github/workflows/macstadium-e2e.yml
Looks like gh action for slack messages started to fail
ail recently so I'm bumping it to the latest version
CI passing is the PoW
All CI checks should be green.
- [] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [] If your changes are visual, did you check both the light and dark themes?
- [] Added e2e tests? If not, please specify why
=> Bump slack api github action

e2e/registerENSFlow.spec.js, src/components/ens-profile/ActionButtons/EditButton.tsx, src/components/inputs/InlineField.tsx, src/helpers/ens.ts, src/screens/ENSAdditionalRecordsSheet.tsx, src/screens/ENSAssignRecordsSheet.tsx
Fixes RNBW-4107
Fixes RNBW-4115
This PR adds more E2E coverage for profiles, including:
- Validating the "View Profile" sheet,
- Validating the "Edit Profile" sheet,
- Validating addition of more records updates the UI on the "Edit Profile" sheet,
- Validating that the field validations of inputs works on the "Edit Profile" sheet,
- Validating that adding, updating and removing records replicates changes on the blockchain on the "Edit Profile" sheet.
=> Profiles: Add more E2E test coverage for view/edit profile

ios/Podfile.lock, ios/Rainbow.xcodeproj/project.pbxproj, ios/Rainbow/AppDelegate.mm, package.json, src/react-native-cool-modals/ios/RNCMScreen.h, src/react-native-cool-modals/ios/RNCMScreenStack.h, yarn.lock
Fixes TEAM2-341
* Reverted some of the hacks from #3710
* Bumped segment and sovran to latest available
* Doing this because https://github.com/segmentio/analytics-react-native/issues/609 got fixed
* Check both Android and iOS and see in the Segment Debugger if the events still make it to Segment
=> Bump segment SDK to the latest version and remove ObjC++ build flags

src/components/change-wallet/WalletList.js
Fixes RNBW-4259
* Rewrote some animations from `react-native-reanimated` layout animations to standard reanimated animations
* Changed the layout of `WalletList`, right now the loader UI and wallet entries are always rendered and what is visible is controlled with opacity animations
Before:
https://user-images.githubusercontent.com/16062886/184649290-256e5afc-c6df-4319-b021-2829f0a593fb.mov
After:
https://user-images.githubusercontent.com/16062886/184649362-ac8aae74-9e54-4927-9633-c8e0fd169558.mov
* Take a look how the loading shimmer to wallet list crossfade animation works
* Check basic functionality of wallet switcher
=> Fix iOS change wallet sheet animations regression

src/components/exchange/ConfirmExchangeButton.js, src/components/icons/DoubleChevron.tsx, src/components/icons/index.js, src/hooks/useSwapCurrencyList.ts, src/hooks/useSwapDerivedOutputs.ts, src/languages/_english.json, src/languages/_french.json, src/redux/swap.ts, src/screens/ExchangeModal.js, src/screens/ExplainSheet.js, src/utils/exchangeErrorCodes.ts
Fixes TEAM2-327
I added a helper to handle all error cases from the sdk, piped up the no quotes explainer and set it as the default so it acts as a catch all if the client doesn't have an up to date mapping
https://cloud.skylarbarrera.com/Screen-Recording-2022-08-18-11-57-29.mp4
best way to trigger no quotes naturally is to try to sell stETh
normal swap inputs + quotes should be unaffected 
- [] Did you test both iOS and Android?
=> swaps: handle sdk errors + no quotes explainer

android/app/src/main/res/mipmap-anydpi-v26/smol.xml, android/app/src/main/res/mipmap-anydpi-v26/smol_round.xml
https://github.com/rainbow-me/rainbow/pull/4059 broke android bc of bad filepaths
=> Fix bad custom icon filepaths on android

package.json, src/model/config.ts, src/screens/ExchangeModal.js, src/screens/TransactionConfirmationScreen.js, yarn.lock
I have added `flashbots_enabled` to remote config. Prior the merge we should have this set to `false` because we expect transactions using flashbots to fail for a brief period after moving to proof of stake. After receiving confirmation that things are back in order we should set this back to true and promptly remove the code added in this PR.
scenario 1 (flashbots_enabled: true && pre merge): https://recordit.co/ZsMQfQNid7
scenario 2 (flashbots_enabled: false && post merge): https://recordit.co/EhtoTvVxXm
Ensure that the flashbots setting still works as usual on this build. Unfortunately, because we do not support swaps on Goerli, the post-merge scenario must be tested via hardcoding.
Here is an example of the code I used to simulate a post-merge scenario (inserted at this line: …
=> [TEAM2-443] Disable Flashbots Post Merge (temporarily)

src/components/expanded-state/SwapDetailsState.js
Fixes TEAM2-305
useEffect callback was being triggered when it shouldn't be, with this logic it seems to be gucci
https://cloud.skylarbarrera.com/PoWandroid.mov
gotta really spam open and close the swap review sheet
=> swaps: fix android swap details focus

src/entities/transactions/zerionTransaction.ts, src/parsers/transactions.ts
This change is to remove field fragmentation created in #3032. The backend was updated to use the same field as l1 instead of introducing a new field.
=> BACK-200: Use the same field on l1/l2s for transaction history

src/hooks/useWebData.ts
Fixes TEAM1-87
We have a toggle in Privacy Settings that enables sync of a user's showcased NFTs to their public ENS profiles. This was also controlling whether or not hidden NFTs were synced to public ENS profiles.
This PR updates that functionality so that hidden NFTs are always synced i.e. even if the toggle in Privacy Settings is disabled, if a user hides and NFT it will be hidden from their ENS profile.
Disable showcase toggle and hide an NFT. Check your web profile to see if it's there.
=> feat: always sync hidden NFTs to remote db

src/components/contacts/ContactAvatar.js
Fixes RNBW-4009
We use shadow stack for many icons. When shadow stack is used to display text and there is no background color property - it will display this weird glitch.
I'm not sure what's causing the missing background color. But since we are gonna refactor this component (Contact Row) in the future anyway, I decided to fix it in place.
This is what was causing the glitch:
https://user-images.githubusercontent.com/7809008/186415458-8627a611-d344-4887-ba16-a591accbe69e.mov
This is how it will look like during "loading" states when we don't have the background color for the row:
- Choose wallet sheet should have emojis with no glitches
- Contact row should have no glitches
=> Fix contact row avatar glitches

.eslintrc.js
Fixes RNBW-4394
This PR adds a warning when someone imports directly from `react-navigation`. We do a lot of customizations in the navigation code, and I am not sure if everyone is always aware of that.
As you can see, imports of `useNavigation` look a bit random:
**Q: Why to this repo and not to our shared eslint config?**
A: This is specific to the app.
**Q: Why warning and not error?**
A: I think we will want to make it an error, but I just wanted to start discussion first. Maybe it's not really needed, maybe it's not as dangerous to mix those import as I think.
This is how this warning looks in VSCode:
-
=> 🏛 [RNBW-4394] Add a warning about importing directly from react-navigation

src/components/AvailableNetworks.js, src/components/exchange/NetworkSwitcher.js, src/components/gas/GasSpeedButton.js, src/components/toasts/TestnetToast.js, src/screens/ExplainSheet.js, src/utils/ethereumUtils.ts
There are a few places in the app where we confidently access `networkInfo[network].someStuff`. This wasn't an issue until `networkInfo` was mutated and certain keys were no longer accessible. This prevents a crash when switching to an app with fewer testnet options when having selected a deprecated testnet on the previous build.
=> [RNBW-4408] Remove unsafe access to networkInfo

src/components/settings-menu/components/MenuItem.tsx, src/config/experimental.ts
Fixes RNBW-4415
- added elevation prop to icons to make shadows visible on android
https://www.loom.com/share/8349080853bd40fb93242e1d23bfc8a5
- just make sure the shadows look alright!
=> fix settings StatusIcon shadows on android

src/App.js, src/components/promos/PromoSheet.tsx, src/screens/ChangeWalletSheet.js
This PR disables campaigns for tests so they don't accidentally break e2e tests in CI. The assumption is that campaigns are temporary and we prefer to avoid adjusting e2e for them all the time.
=> Disable campaings in e2e and fix testID of PromoSheet

src/components/exchange/ExchangeInputField.js, src/components/exchange/ExchangeNativeField.js
Fixes TEAM2-489
noticed the native input cursor color was wrong, this fixes it 
after: https://cloud.skylarbarrera.com/Screen-Shot-2022-08-31-15-22-28.91.png
check the native input cursor color for l2 assets
=> swaps: fix native input cursor color

.github/workflows/macstadium-e2e.yml
Fixes RNBW-4331
With the new ESLint setup, we have >4k warnings. These only useful when commiting changes locally via the `lint-staged` `pre-commit` git hook. In CI, we should only surface errors. This is what the `--quiet` option does.
Since yarn's handling of passed arguments to npm scripts might not be clear to everyone, I opted to spell out the whole command in the GitHub Action instead of `yarn lint --quiet`.
=> 🏛 fix: quiet logs when linting in CI

src/hooks/useENSRegistrationActionHandler.ts, src/screens/ENSConfirmRegisterSheet.tsx
Fixes RNBW-4455
This PR fixes an issue where renewing an ENS would not work on Android. Turns out we should be awaiting on the action.
https://www.loom.com/share/85e0dfa34bc0433caba2d832488ac465
- Try to renew/extend an ENS on the ENS NFT expanded sheet
=> Fix renew ENS on Android

src/parsers/uniqueTokens.js
Fixes TEAM2-492
Added more rigorous checks to check that the OS api returns enough data to construct the sale price. 
Please check wallets to see if the collectibles list appears/ disappear, see below for a list of known wallets with issues in prod are on linear
=> Fix issue with Collectibles not showing if opensea doesn't return consideration

src/model/wallet.ts, src/utils/ethereumUtils.ts
Fixes TEAM2-141
When discovering wallets after importing the seed phrase, we currently use Etherscan, on a paid plan, that is still excessively rate limited. A new endpoint has been introduced by backend that can now be used for this purpose.
- Import a seed phrase with multiple active addresses. It should pick them up.
=> fix: Use new endpoint for discovering wallets

src/screens/SettingsSheet.tsx
Fixes RNBW-4339
- fixed clipped subheader (subheader is text that says "Backed up manually" in screenshots below)
- kind of a bandaid fix, since it only works on nav screens that aren't scrollable– currently we don't have any settings screens that are scrollable AND have a subheader. i'm slowly working on a redesign of the settings nav architecture on another branch, so i think the bandaid is ok for now.
iPhone 13 Pro
Pixel 2
- android & ios
- double check there aren't any cases where a screen is scrollable AND has a subheader, since this fix wouldn't work in that case
=> fix clipped subheader on Backup sheets

src/components/sheet/sheet-action-buttons/BuyActionButton.js
Add wyre degradation navigation in expanded state "Buy more ETH"
https://www.loom.com/share/3ae071afcf0546cfa91e5dae4ddcf19d
test on video https://www.loom.com/share/3ae071afcf0546cfa91e5dae4ddcf19d
=> add wyre degradation explainer to buy action buttons

.github/workflows/macstadium-e2e.yml, .prettierignore, bitrise.yml, package.json, src/components/expanded-state/custom-gas/FeesPanel.tsx, src/components/expanded-state/custom-gas/FeesPanelTabs.tsx, src/components/expanded-state/custom-gas/GweiInputPill.tsx, src/graphql/README.md, src/languages/_english.json, src/languages/_french.json
Fixes RNBW-4482
Right now we have a couple of related issues in CI:
- Prettier isn't being run in CI even though it's included in the `yarn lint` script.
- The Prettier/ESLint/TypeScript checks aren't running against develop which means that breakages can slip through if a PR is lagging behind develop but doesn't have any merge conflicts, e.g. the PR is depending on an earlier version of types defined elsewhere in the codebase, causing type errors when merged.
This PR ensures that all lint steps are run against PRs and develop in CI.
I've also included some fixes for issues that were causing lint failures.
=> chore: run lint and Prettier on all branches in CI, apply fixes

patches/react-redux+7.2.1.patch
Jest is choking on this `import` since we aren't transpiling `node_modules` and it's patched into a commonjs transpiled file.
I'm not familiar enough with Metro to say why this has been working for us, but I think we should fix this patch to use commonjs `require` syntax instead since that's a more technically correct patch to this file.
=> fix: redux patch use require

src/env.ts
Terry pointed this out [in Slack the other day](https://rainbowhaus.slack.com/archives/C03SS7N997H/p1662728163927909) 👍 
Basically, `IS_TESTING` is an env var so it's always a string. Therefore, `!!IS_TESTING` will always be truthy. That's not the intention. This PR fixes that.
=> fix: `IS_TEST` assignment

src/components/expanded-state/custom-gas/GweiInputPill.tsx, src/components/gas/GasSpeedButton.js
with https://github.com/rainbow-me/rainbow/commit/da80e482226c785f52431bd3d44fcb122db6a637 i forgot to update the gas context menu to use `maxBaseFee` instead of `maxFeePerGas`
https://www.loom.com/share/7913752e9037475db96a9a3ddd614b6f
- i also added this change https://github.com/rainbow-me/rainbow/compare/%40esteban/update-gas-context-menu-with-maxBaseFee?expand=1#diff-6d1386f1c8843e0be3c4181db6d938038e4b4c549c5f7d8cd6760bfc1d9e14d3R39 to see if it fixes the bug i showed on the loom video, for some reason is happening on TF but not on dev
-
=> fix: gas context menu max fee

jest.config.js, src/helpers/__tests__/utilities.test.ts, src/helpers/utilities.ts
Fixes RNBW-4474
According to the unit tests defined here, two utils were broken: `addDisplay` and `convertBipsToPercentage`. This PR fixes those two implementations to match the unit tests. If this is incorrect behavior, we need to update the implementation and the unit tests to reflect that.
Run `yarn test src/helpers/__tests__/utilities.ts`
=> fix: helpers/utilities tests

src/components/floating-panels/FloatingPanel.tsx
Fixes RNBW-4497
I updated the `style` prop in `FloatingPanel.tsx` so that it can support arrays of styles. Previously it was being spread into a single style object, but this breaks if an array is passed in.
Before:
After:
Before:
After:
=> Fix import wallet modal padding

src/components/unique-token/Tag.js, src/components/unique-token/UniqueTokenAttributes.tsx, src/entities/uniqueAssets.ts, src/handlers/ens.ts, src/handlers/simplehash.ts, src/navigation/useUntrustedUrlOpener.ts, src/parsers/uniqueTokens.js
Fixes RNBW-4478
Quixotic rebranded to Quix and we were matching on `marketplace_name` in two places to provide deeplinks for:
- The NFT's page on that marketplace
- The marketplace's results for a selected trait in that collection
SimpleHash introduced `nft_url` field so we don't have to match for this at all anymore and `marketplace_id` so we have a field guaranteed not to change to handle the selected trait search. Once this PR is merged, released, and propagates, SimpleHash will update Quixotic -> Quix and the correct marketplace name will be displayed.
- Screen recording demonstrating that we continue to show a marketplace's name (`View on OpenSea`) and the link works: [nft-marketplace-urls.webm](https://user-images.githubusercontent.com/677680/190522481-5a030a6b-d907-49d7-b39a-c68b629 …
=> Use SimpleHash's nft_url and marketplace_id fields instead of matching on marketplace name

src/parsers/uniqueTokens.js
Fixes RNBW-4479
We switched out the logic for fetching currentPrice on ETH mainnet however we didnt copy that same logic over to Polygon tokens. This adds that same code, which should stop polygon NFTs dissappearing in the app.
Find a wallet that has polygon NFTs that are for sale on OS and check to see if the NFT list loads
=> Use same check for unique tokens on polygon as ETH mainnet

.eslintignore, .gitignore, .prettierignore, config/test/jest-setup.js, globals.d.ts, jest.config.js, src/logger/README.md, src/logger/__tests__/logger.test.ts, src/logger/debugContext.ts, src/logger/index.ts
Fixes RNBW-4477
This is the first pass at a new logger, [based on our spec](https://www.notion.so/rainbowdotme/Tracking-635a7da3d0cc413b9cf390f1c3c48f88#3952ebba01114a80a6366c5fc9272656).
**Features:**
- unified interface
- log levels: `debug`, `info`, `warn`, and `error`
- deeper integration with Sentry, automatic breadcrumbs, exception handling for errors
- differentiation between dev/test/prod modes
- no logs in test mode by default
- filtered logs, no spamming of console
- only see logs that are relevant to what you're working on
- documentation
- full test suite
**Key notes:**
- log level defaults to `warn` in dev (i.e. only `warn` or `error` are logged to console), and we should set it to `info` in prod to capture more breadcrumbs
- `debug`, `info`, and `warn` are all capable of …
=> feat: new `@/logger` interface

src/components/backup/RestoreCloudStep.js, src/redux/wallets.ts
We were updating the backup meta after restoring. This is no longer necessary.
See slack msg
=> dont update backup meta when restoring

.github/workflows/macstadium-android-e2e.yml
This is just allowing running android CI from more branches and this will unblock our work on  android e2e
=> lean restrictions on branch name for Android e2e runner on CI

src/App.js, src/design-system/color/palettes.docs.tsx, src/design-system/color/palettes.ts, src/design-system/components/Box/Box.docs.tsx, src/design-system/components/Box/Box.examples.tsx, src/design-system/components/Separator/Separator.examples.tsx, src/design-system/components/Text/Text.examples.tsx, src/design-system/docs/.playroom/FrameComponent.js, src/design-system/playground/BackgroundDemo.tsx, src/screens/PairHardwareWalletIntroSheet.tsx, src/screens/PairHardwareWalletSearchSheet.tsx
Fixes TEAM1-138
Surfaces have been re-categorized into two tiers, each with a base color and an elevated color. This also means that the set of "fill" colors has been reduced from 3 to 2 since `fillTertiary` was really intended to be used as another surface color.
The colors being modified have only recently been added and have only used on the Ledger Nano X connection sheet which is currently behind a feature flag.
=> Rename surface colors, update usages

package.json, yarn.lock
Fixes an issue I was having locally running Detox after macOS updated the simulators. More info [in the Detox repo.](https://github.com/wix/Detox/issues/3593)
Should have no effect.
=> fix: upgrade detox for iOS 16

.github/workflows/macstadium-e2e.yml
=> fix: run Jest tests in CI

src/components/change-wallet/AddressRow.tsx
https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1664296008378029
- `AddressRow` was attempting to get emoji from wallet label after the emoji had already been stripped
https://user-images.githubusercontent.com/15272675/192622382-5697128c-5cff-47f4-b797-51e9cc331ec9.mp4
- when you change the wallet's emoji, it should be reflected in the list of wallets
=> Fix wallet avatar bug

src/navigation/config.js, src/screens/SettingsSheet.tsx
Fixes RNBW-4541
The main settings screen had a transparent header on ios, which caused text overlays while scrolling. I added a bg color to the header so this doesn't happen anymore.
Before:
https://user-images.githubusercontent.com/15272675/192586933-1ea6ed9d-4042-446a-ab29-46e115d76b08.mp4
After: 
https://user-images.githubusercontent.com/15272675/192587083-4d20adb1-ce81-434f-8ca1-13418ea2c834.mp4
- scrolling looks normal on main settings screen
=> Fix settings header

android/app/src/main/java/com/swmansion/gesturehandler/react/RNZoomableButtonManager.java
Our scale animation button, which uses GH 1.10.3, was showing a ripple effect for some reason on press events, even though we used transparent color for it. This PR disables all kinds of feedback except for our own animation.
Before:
https://user-images.githubusercontent.com/7809008/192878323-7009fb11-543a-4327-bc1e-850b41208709.mov
After:
https://user-images.githubusercontent.com/7809008/192878376-f78c792c-49da-4b31-89b5-6735f86bc280.mov
All the buttons should still have scale animations.
=> Fix ripple on Android 13

src/components/header/BackButton.js
- app crashes if you long press the back button in the currency select modal (see video below)
crash example:
https://user-images.githubusercontent.com/15272675/192890645-a8100ab0-d4fa-4d66-9bae-c97814005b4e.mp4
fix:
https://user-images.githubusercontent.com/15272675/192890700-c02d6b3d-0ebb-4348-9fc9-6b0e6ebd08c3.mp4
crash doesn't happen anymore
=> Fix BackButton crash on long press

src/components/Pill.js, src/components/expanded-state/swap-details/SwapDetailsContent.js, src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js, src/languages/_english.json, src/languages/_french.json
Fixes TEAM2-502
Figma link (if any): https://www.figma.com/file/SFfYzRoHlapEecS0LTLwhQ/Swap-Aggregator-V2?node-id=57%3A25694
- fixed row sizing/spacing in swap details sheet
- add "flashbots protect" row when flashbots are enabled
https://user-images.githubusercontent.com/15272675/192642239-9cd66685-949d-4c30-b9ac-403fd084c057.mp4
- flashbots protect row only appears when flashbots are enabled
- tapping leads to correct explain sheet
- rows are equally spaced
- tapping "swapping via" row still works well when there are multiple LPs
=> Add Flashbots Protect row to swaps details

src/hooks/useAccountProfile.ts, src/notifications/NotificationsHandler.tsx, src/redux/wallets.ts
Fixes RNBW-4468
Fixes TEAM2-508
explanation in ticket video
video in ticket https://linear.app/rainbow/issue/RNBW-4468#comment-53e7f528
1. switch accounts flow: kill the app, open it and switch the account very quickly, before this PR you would be able to see the initialized bug but this  shouldn't be happening anymore
2. notifications flow: leave the app in wallet "A", kill the app, open a notification for another account (account B), you should see the app is switching accounts automatically and you don't get to this initializing state
3. ENS flow: kill the app, update ens avatar for the wallet from ens app, open the app again, you should see the new avatar correctly updated in your wallet
=> fix: initializing stuck state

android/app/src/main/AndroidManifest.xml, android/build.gradle
Fixes TEAM2-510
in order to not have the issue described on the ticket seems like we need to bump the target sdk https://developer.android.com/develop/ui/views/notifications/notification-permission
building an APK with this branch fixed the issue
not much to add, now i don't see the dialog on launch
- you don't see the notifications dialog on app launch
=> android: bump target sdk

src/components/settings-menu/DevSection.tsx, src/components/settings-menu/NotificationsSection.tsx, src/model/mmkv.ts
Fixes TEAM2-511
- Notification settings reset to a default state like on first app launch after clearing them from Dev Settings.
- Prevented the app from crashing when going to Notification settings for a wallet after clearing storage / MMKV.
- Fixed app not unsubscribing from notifications when clearing storage / MMKV.
- Fixed toggles in `Settings → Notifications` showing wrong state after clearing storage / MMKV.
- Removed some leftover functions from https://github.com/rainbow-me/rainbow/pull/4165
No visual changes.
1. Clearing local storage as a normal user and checking if notification settings are reset to default (owned ON, watched OFF) and correctly displayed.
2. Checking if notifications arrive properly based on selected settings.
3. Changing settings for wallets and checking if …
=> Fix: Notifications not unsubscribing when clearing storage + crashing

src/handlers/tokenSearch.ts, src/hooks/useSwapCurrencyList.ts
Crosschain searches now provide a `fromChainId` query param. This filters the resulting list based on Socket's available routes.
[This](https://recordit.co/BpFFLcY2xI) is an example of a crosschain search for 'aave'. Aave is a good test case because it has a lot of token derivates, many of which have low liquidity and are not supported by Socket. You'll notice in the video that L2 search UI contain mainnet's results for tokens outside of `verifiedAssets`. This is not related to my changes, but rather an existing issue with the feature branch we will need to address. I addressed it [here](https://github.com/rainbow-me/rainbow/pull/4221/files#r982904122).
We should ensure that search functionality and the swap modals themselves still behave as they have in the past. Helping to verify that …
=> [TEAM2-499] Currency Select Modal Crosschain Search

src/handlers/tokenSearch.ts, src/hooks/index.ts, src/hooks/useSwapCurrencyList.ts, src/hooks/useSwappableUserAssets.ts, src/redux/swap.ts, src/screens/CurrencySelectModal.tsx
When a destination network can be determined based on output token selection
https://recordit.co/avBPAe34ie
The team 2 wallet contains a currency (Pikatic) that does not currently possess on supported cross chain routes. This is the most accessible test case. You can also use the curl example below to verify which tokens are supported for a given chain combination, swap for something unsupported, and attempt the flow I illustrated above with Pikatic.
```
curl --location --request GET 'https://api.socket.tech/v2/token-lists/from-token-list?fromChainId=10&toChainId=1' --header 'API-KEY: 645b2c8c-5825-4930-baf3-d9b997fcd88c'
```
This request returns tokens that can be swapped from optimism (10) to mainnet (1).
=> [TEAM2-500] Filter User Assets By Socket Support In Currency Select Modal

src/App.js
I'm doing some research into our app initialization **so that we can unlock some soon-to-happen state updates,** like bootstrapping initial application state.
This is a first of a few PRs. All it does is extract the context providers into a new component, and re-wrap with instrumentation. The order of components in this tree should be loosely:
1. State, like Redux, Recoil, Jotai, and React Query
2. Library context, like `SafeAreaProvider` or something that _might_ depend on application state
3. Internal context, like `MainThemeProvider` — again may depend on state, and needs to wrap `ErrorBoundary` and other UI
4. `ErrorBoundary` — handles UI errors, needs to be further down the tree in order to reference context
5. UI components
**A few reasons for this PR:**
First, we need to be able to …
=> fix: extract App.js providers, fix redux usage

src/notifications/NotificationsHandler.tsx, src/notifications/analytics.ts
Fixes TEAM2-514
* Implemented a new analytics event that fires when users tap on push notifications called "Tapped Push Notification"
* Make sure you have notifications feature flag enabled
* Send a transaction that will trigger a new push notification
* Once you have the push notification, go to segment debugger
* Press on a notification when the app:
* Is in foreground
* Is in background
* Is killed
* Try to catch that event in the debugger
Use the dev mode so that the dev source is used in segment
=> Analytics Tapped Push Notification event

.github/dependabot.yml
See [discussion in Slack](https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1664524373501989), and related PRs #4251 and #4187.
**Why add Dependabot?**
Our current workflow with `audit-ci` only alerts us to issues, it doesn't help us fix them. Also, `yarn audit fix` doesn't exist. So Dependabot can help fill this gap and open PRs with lockfile patches for vulnerabilities.
If a dependency vuln is deemed acceptable, we can close the PR and ask Dependabot to ignore it. If it's something we need to fix, then we've got a PR ready to go for testing.
Our workflow otherwise stays the same, and `audit-ci` will block merging PRs until we either merge an Dependabot PR to fix it, or ignore it in the `audit-ci.jsonc` config file.
=> feat: configure Dependabot

.github/dependabot.yml
My bad, learned that I need to disable version updates (with [this strange config](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file)) in order to ONLY get security updates. As it is, it's going to get very noisy, and we don't need that right now.
=> fix: only enable Dependabot for security updates

jest.config.js, package.json, tsconfig.jest.json, yarn.lock
Fixes RNBW-4513
Adds `@testing-library/react-native` and sets up a separate `tsconfig.jest.json` based on our root `tsconfig.json` so that we can test React code in Jest.
I extracted this PR from #4209 for easier reviewing.
=> feat: enable react testing with jest

src/parsers/transactions.ts, src/redux/data.ts
Fixes TEAM2-496
Originally i thought the issue on the ticket was produced because we weren't parsing txs correctly for crosschain swaps but the issue on the ticket was produced because zerion txs were overwriting txs on state, so crosschain swaps happening from mainnet as source network 
https://www.loom.com/share/93fae4714d5a453580a27aa11bb4f189
In the video you'll see a mainnet <> OP swap that is not bridged yet, so the tx is on "Swapping" state while the bridge is confirming
- i didn't add android since i'd have to pay for another swap on mainnet and this is only a data change
- send a mainnet <> L2 swap and you shouldn't see a "Sent Token" tx confirmed below the pending "Swapping" tx described on the ticket
=> crosschain swaps: handle transaction confirmation status

src/handlers/tokenSearch.ts, src/helpers/tokenSectionTypes.ts, src/hooks/useSwapCurrencyList.ts, src/screens/CurrencySelectModal.tsx
https://www.figma.com/file/SFfYzRoHlapEecS0LTLwhQ/Swap-Aggregator-V2?node-id=898%3A56888
https://www.figma.com/file/SFfYzRoHlapEecS0LTLwhQ/Swap-Aggregator-V2?node-id=28%3A28566
The currency select modal will now display exact matches on other networks when no applicable results are returned for the current network selection. Additionally, we now display a 'bridge' section when a verified asset is selected as the input and the selected network's results contain the corresponding bridged version of the asset in the verified section.
iOS PoW
https://recordit.co/rxuKudh6ov
https://recordit.co/fjxphs6IFH
Android PoW
http://recordit.co/mVuqNV9blJ
Confirm that network's with verified assets in common display the bridge asset section when applicable.
Confirm that crosschain …
=> [TEAM2-476][TEAM2-472] Display Crosschain Exact Matches and Add Bridge Asset Section

src/notifications/NotificationsHandler.tsx, src/notifications/analytics.ts, src/notifications/permissions.ts, src/notifications/settings.ts
Fixes TEAM2-522
* Added an identify call that will update the user property for notification permission status on every app launch and whenever the user grants or denies push notification
* Check if the identify call makes it to segment properly
=> Implement identify call with notifications permission status

src/screens/ExchangeModal.tsx
The 'Get ${asset}' flow from expanded state did not previously support crosschain selections and would clear the output in the ExchangeModal. This now works.
Bridge Case: https://recordit.co/MWdPKfXc9n
Crosschain: https://recordit.co/yh6i0iZXxS
Single chain: https://recordit.co/Fd9VGmxVHt
Ensure the cases above behave appropriately and swaps are possible in each case after proceeding through the 'Get ${asset}' flow.
=> [TEAM2-520] Allow Crosschain Token Selection in Get $ASSET Expanded State Flow

src/components/settings-menu/NotificationsSection.tsx, src/notifications/NotificationsHandler.tsx, src/notifications/analytics.ts, src/notifications/settings.ts
Fixes TEAM2-521
* Added identify call which tracks the number of wallets for watched and imported that have notifications turned on and updates it every time something changes in the settings
* Check if it works and causes no issues
* Observe if the identify calls make it to segment (with segment debugger)
=> Implement tracking number of wallets with notifications enabled

e2e/swapSheetFlow2.spec.js, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx, src/components/exchange/ExchangeAssetList.tsx, src/helpers/tokenSectionTypes.ts, src/hooks/useSwapCurrencyList.ts, src/screens/CurrencySelectModal.tsx
Figma link (if any):  https://www.figma.com/file/SFfYzRoHlapEecS0LTLwhQ/Swap-Aggregator-V2?node-id=975%3A58443
This PR displays a disabled list with reduced opacity representing tokens the user holds that can not be swapped to the target network. We did not update designs to reflect the decision to move from grayscale to reduced opacity. Additionally the designs do not reflect the updated section header (I confirmed the copy with Daniel recently).
It's probably worth noting that we are not guaranteeing that a route is available for all tokens outside of the disabled list. We need to query the quotes endpoint after selection to confirm this, but they are at least swappable to the target network.
https://recordit.co/h6EQoCyEZj
Select an output token then navigate to the input selection …
=> [TEAM2-504] Spec swaps: Update CurrencySelectModal assets list UI when selecting input token

src/components/AddFundsInterstitial.js
Fixes RNBW-4610
regression from : https://github.com/rainbow-me/rainbow/commit/3ae8b949d8b9068c1b492501e94b0231a6b19ff5#diff-2449fdb4f4521419f1bfb0af536a96993ae87dedcb49e9295119813b548d7ccdR254
https://cloud.skylarbarrera.com/Screen-Shot-2022-10-14-10-49-05.62.png
=> fix: restore add cash interstitial colors

src/components/exchange/ExchangeAssetList.tsx
Makes a couple adjustments to the section headers in the swaps selection list view:
- gradient text was sitting lower than non-gradient, so I added a little extra padding to the top for non-gradient text
- gradient was overlaying first list item in default state
- moved gradient start further down
- shortening the gradient itself started to look bad, so added a little bottom padding to give it room so that it doesn't overlay the first list item
Screen recordings / screenshots
I don't think this should affect anything else.
=> fix: adjust background gradient in ExchangeAssetList headers

src/storage/README.md, src/storage/__tests__/storage.test.ts, src/storage/index.ts, src/storage/schema.ts
Fixes RNBW-4319
Adds a more standardized, _strongly typed_, local storage interface. See the [README](https://github.com/rainbow-me/rainbow/blob/9bfbba2089449da3a8a8541f77baa098231dd653/src/storage/README.md) for more info. Looks like this (similar to React Query):
- `set([...scope, key], value)`
- `get([...scope, key])`
- `remove([...scope, key])`
- `removeMany([...scope], [...keys])`
For example, using our `device` store looks like this, since it's scoped to the
device (the most base level scope):
```typescript
import * as storage from '@/storage'
storage.device.set(['doNotTrack'], true)
storage.device.get(['doNotTrack'])
storage.device.remove(['doNotTrack'])
storage.device.removeMany([], ['doNotTrack'])
```
1. We can create scoped stores (see …
=> feat: local storage interface for MMKV

src/logger/README.md, src/utils/logger.ts, src/utils/sentry.ts
Deprecates the old `@/utils/logger` and `@/utils/sentry` utils in favor of the new `@/logger`. No runtime code has been edited in this PR.
I've also added some collapsible sections to the logger docs to help with this transition.
=> chore: deprecate `@/utils/logger` and `@/utils/sentry`

src/model/keychain.ts
Started doing this to help debug a problem and figured I'd finish it up. Only logger/Sentry changes. Note the difference between `info` and `warn`, and that `error` in turn calls `captureException`.
=> feat: replace old logger in `model/keychain`

src/components/expanded-state/swap-details/SwapDetailsContent.js, src/languages/_english.json, src/languages/_french.json
Fixes RNBW-4621
- hide flashbots protect detail row when swapping on L2s
Uploading Simulator Screen Recording - iPhone 14 Plus - 2022-10-18 at 17.32.26.mp4…
make sure it shows up for mainnet swaps but not for L2 swaps
=> hide flashbots protect detail row when swapping L2s

src/components/expanded-state/asset/ChartExpandedState.js, src/handlers/dispersion.ts, src/hooks/useAdditionalAssetData.ts
Fixes BACK-286
The token expanded state will now show the following data if availablle for tokens on L2/sidechains:
- 24h volume
- Market cap
- Description
- Socials
The code I touched only affects token expanded state so look at tokens on different networks.
=> feat: Token expanded state should show additional asset data on L2s/sidechains

index.js, src/App.js, src/init.ts
Prepping for some small updates to the initialization flow that will require a small amount of async (may be sync) work up front i.e. load device ID, init Sentry, init Segment, then run app.
Originally I was going to do this in a single file, but I want to make sure that as little code as possible runs prior to Sentry instantiation, so I pulled it out of `App.js`.
Basically check if it runs.
=> feat: async init App

CODEOWNERS, config/test/jest-setup.js, src/analytics/__tests__/utils.test.ts, src/analytics/utils.ts, src/storage/schema.ts
Adds a util that:
1. Returns the device ID from local storage if it exists
2. If it doesn't exist, tries to load one from keychain (where we previously stored this)
3. If nothing else exists, it's a new user, and we create an fresh ID
We then identify the user in Sentry immediately, and in all cases, return the device ID.
There's a test suite.
=> feat: add new device ID handling

src/logger/__tests__/logger.test.ts, src/logger/index.ts
@brunobar79 brought up a good point that JS code without type-guards might unintentionally pass in nullish/falsy values and we'll end up with thrown errors. This adds fallbacks and test cases to ensure we don't regress in the future.
=> feat: add falsy test cases to logger metadata

src/screens/ExplainSheet.js
fixes e2e 😅 
thought this https://github.com/rainbow-me/rainbow/pull/4310 has passed e2e other than slack previously I was mistaken 
this is sad but follows the pattern here until we can refactor this 🧶 
https://github.com/rainbow-me/rainbow/blob/0ae3218255baef535b1e15fb218614b9a75f1477/src/screens/ExplainSheet.js#L868
e2e should pass
=> fix e2e: add existence check

src/screens/ExplainSheet.js
* Managed to reproduce the error while developing, it appeared in ExplainSheet
* Apparently there was no fallback when there was no color in the case where you had a profile pic, but no ENS profile
Just look at code, it is just a fallback, the same fallback color is supplied in wrapper function, it was not supplied in an inline function inside of the style
=> Fix `Error: unknown format:` error in ExplainSheet

src/components/settings-menu/DevSection.tsx, src/components/settings-menu/TransactionDetailsPlayground.tsx, src/components/settings-menu/index.ts, src/screens/SettingsSheet.tsx
Fixes APP-28
* Implementing playground for new transaction details development
=> implement TX Details playground with empty tx details entries

src/components/qrcode-scanner/QRCodeScanner.tsx, src/hooks/useScanner.ts
???
new Scanner doesn't need to goBack() on any calls, i've  removed that logic entirely and added it to the only place needed. 
you can see in develop that when u scan a profile code it will navigate correctly and then run onSuccess, which then called goBack(), dismissing the sheet
added a follow up ticket to combine scan/deeplink handling: https://linear.app/rainbow/issue/APP-89/standardize-scanner-deeplink-logic
=> fix: tweak scanner logic

src/components/settings-menu/AppIconSection.tsx, src/featuresToUnlock/unlockableAppIconCheck.ts
fixes an issue in https://github.com/rainbow-me/rainbow/pull/4332 found by @benisgold after it being merged 😓 
the event wasn't properly reporting the campaign key, changed it and also addressed his other comment
=> @skylar/app icon followup

src/references/index.ts
Fixes APP-####
dog Easter eggs were built off of develop where DOG_ADDRESS existed, because the dog favorite revert took so long to get merged I missed the scenario where there is no DOG_ADDRESS
so this just adds back the reference 
🙃 
https://cloud.skylarbarrera.com/Screen-Recording-2022-10-25-13-18-42.mp4
=> fix: re-add dog nft to reference

src/hooks/useOnAvatarPress.ts, src/hooks/useUpdateEmoji.ts
Fixes APP-144
Fixed the remove photo action by adding `image: null` to emoji selection action. This makes sure that when you press remove photo and avatar picker comes up, when you actually pick an emoji the photo is removed
**Screen recordings and test instructions in linear**
=> Fix "Remove Photo" avatar context menu option

src/App.js, src/analytics/README.md, src/analytics/__tests__/index.test.ts, src/analytics/event.ts, src/analytics/index.ts
Fixes APP-122
Consolidates event enums and replaces usages. Add usage docs.
Copied from docs:
```typescript
import { analyticsV2 } from '@/analytics';
analyticsV2.identify({
...userProperties,
})
analyticsV2.track(analyticsV2.event.applicationDidMount)
analyticsV2.track(analyticsV2.event.appStateChange, {
category: 'app state',
label: 'foo',
})
analyticsV2.screen(Routes.SWAPS_PROMO_SHEET, {
...metadata,
})
```
Tests pass, app runs.
=> feat: analytics docs, simplify events

ios/Rainbow.xcodeproj/project.pbxproj, ios/ThemeModule.m, src/components/ens-profile/ActionButtons/SendButton.tsx, src/components/expanded-state/SupportedCountriesExpandedState.js, src/components/expanded-state/profile/ProfileModalContainer.js, src/components/sheet/sheet-action-buttons/SendActionButton.js, src/components/showcase/ShowcaseHeader.js, src/helpers/isNativeStackAvailable.ts, src/hooks/useMagicAutofocus.ts, src/navigation/Routes.ios.js, src/navigation/routesNames.js, src/react-native-cool-modals/ios/RNCMPortal.m, src/react-native-cool-modals/ios/RNCMScreen.m, src/screens/AddCashSheet.js, src/screens/ImportSeedPhraseSheet.js, src/screens/SendSheet.js, src/utils/ethereumUtils.ts
Fixes APP-76
* Bumped iOS Deployment target from 11 to 13 on all Xcode Targets
* Removed `isNativeStackAvailable` variable and removed its usages or replaced it with `IS_IOS`
* Removed `@available(iOS 13.0)` checks in native iOS code (we always have minimum iOS 13 now so it's not needed)
=> Bump iOS target to iOS 13 and remove version checks

__mocks__/react-native-mmkv.ts, config/test/jest-setup.js, src/logger/debugContext.ts, src/migrations/__tests__/index.test.ts, src/migrations/index.ts, src/migrations/migrations/deleteImgixMMKVCache.ts, src/migrations/types.ts
Fixes APP-174
Adds new migrations setup to the app. Problems with **current migrations**:
- run within `useInitializeWallet`
- rely on remote data being loaded
- run after app initializes, could cause race conditions (if not already)
- checking for `length` of migrations is a little flimsy (remove one, add another, it won't get run (not that we'd do this))
- error handling seems sketch? does this mark as completed it a migration throws? I don't see recovery handling 🤔 
This approach:
- run immediately upon app startup
- agnostic of other data
- gracefully handles errors
- full test suite
There's a test suite. I wrote my own MMKV mock since the provided one doesn't actually function the same way as MMKV does in production (shared memory referenced by `id`).
=> feat: add new migrations handling

ios/Podfile.lock, package.json, yarn.lock
* @brunobar79 I reverted to use the fork I would be grateful for a review of what I have there https://github.com/rainbow-me/react-native/commits/%40jkadamczyk/rebased-fixes-0.68.5
* Everyone else please test and try building the android app
=> Revert to using updated react-native fork rebased from 0.68.1 to 0.68.5

src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Fixes APP-172
- eye icons for hide/unhide were reversed
- see ticket for figma
=> Fix "hide NFT" icon

src/analytics/userProperties.ts, src/hooks/usePortfolios.ts, src/redux/data.ts
Fixes APP-187
- updated `trackPortfolios` callback from `usePortfolios` hook to include asset values for optimism and arbitrum
- updated `ZerionPortfolio` object (we use this to map zerion api response)
sample zerion response
=> Add asset values for l2 networks

src/redux/swap.ts
Fixes APP-196
we were checking based on address but we want to check based on uniqueId since assets can have the same address on diff networks 
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-09-19-53-13.mp4
read the code and press the green button 🔫
=> swaps: compare assets with uniqueId

src/screens/ExplainSheet.js
while looking into another issue I noticed this sheet height was too low, ive bumped it so it looks better
https://cloud.skylarbarrera.com/Screen-Shot-2022-11-10-13-20-41.67.png
screen shot
=> fix: bump cross chain gas explainer height

src/screens/CurrencySelectModal.tsx
Fixes APP-205
behavior was a lil off, now we reset the list to the top when a user switches networks 
note the following PoW is animated, I disabled that so the behavior is a lot quicker than shown.
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-10-16-42-54.mp4
N/A
=> swaps: scroll up when changing networks 

src/screens/SendSheet.js
As seen in [APP-182](https://linear.app/rainbow/issue/APP-182/[android-only]-failure-to-send-txn), failures in the `SendSheet` resulting from failed `sendTransaction` calls get ignored, and no user feedback is provided.
This PR short-circuits the handler in order to utilize existing error handling.
=> fix: handle transaction errors in SendSheet

src/entities/tokens.ts, src/parsers/accounts.js, src/utils/getTokenMetadata.ts
Fixes APP-191
we have a token list that gives us metadata on tokens that looks like this: https://cloud.skylarbarrera.com/Screen-Shot-2022-11-14-10-57-19.09.png
previously we were allowing this to overwrite data we get for the backend, this was affecting our balance calculations for L2 assets when the decimals didnt match.
ex: USDT on mainnet has 6 decimals of precision, on bsc it has 18(standard), we use this to calculated balance value so things were looking funky for BSC USDT. 
should be a no op, we're just removing chain specific metadata now (which are unneeded since we have this data already)
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-14-11-02-23.mp4
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-14-11-02-23.mp4
=> fix: rm chain specific metadata 

globals.d.ts, src/analytics/index.ts, src/logger/debugContext.ts, src/utils/logger.ts
Adds `QUIET_OLD_LOGGER` to silence our old console logs. Does not affect new logger.
Also fixes issue where any debug context (i.e. `LOG_DEBUG=migrations`) specified would trigger debug mode in the Segment analyticsv2 instance, which was additional noise we don't need. Now you have to pass either `LOG_LEVEL=debug` or `LOG_DEBUG=analytics` explicitly.
=> feat: add QUIET_OLD_LOGGER, fix analytics debug

src/config/experimental.ts, src/handlers/transactions.ts, src/redux/data.ts
Fixes APP-80
handling regarding bridge tx statuses was kinda wonky 👇 
1. we we're checking token approvals via the socket api, this isn't handled by them and was causing issues. now we just check like we do a normal tx
2. if we got any type of error from socket we were marking the tx as failed -> their api seems kinda wonky atm and would throw errors when it shouldn't. we should only mark as failed if socket explicitly tells us the tx failed, otherwise we should continue watching the tx status
^ ive kept the `IS_TEST` logic as this api wont work on e2e tests since they're simulated tx's
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-14-14-05-22.mp4
imma let ibrahim do his thing on this one so code review is 👌
=> fix: bridging tx's statuses

src/migrations/__tests__/migrations-prod.test.ts, src/migrations/__tests__/migrations.test.ts, src/migrations/index.ts, src/migrations/types.ts
Realized that it's nice to have a way to test migrations as you're running them. Setting `debug: true` in the migration config allows it to run every time your local app refreshes.
To protect against accidentally merging a migration in debug mode, I added a check that exits early and sends an error to Sentry.
Have a look at the tests for more details.
=> feat: add debug mode to migrations

src/components/cards/GenericCard.tsx
Fixes APP-238
* Added `skipTopMargin` prop to `ButtonPressAnimation` which makes the top margin smaller, the shadows are small enough on top so that it works fine
* check if you can press on discover search
=> Fix overly large touchable area in new cards preventing focusing discover search field

src/components/exchange/ExchangeTokenRow.tsx
Fixes RNBW-4649
fixed regression of token symbol/balance color in swaps
=> Fix swaps token symbol/balance color

src/entities/gas.ts, src/entities/index.ts, src/handlers/gasFees.ts, src/redux/gas.ts
Fixes APP-233
we were using free and ruggable endpoints for polygon and bsc gas, we now run through meteorology like we do for mainnet, which will allow us to fall back if we have any issues and avoid rate limiting. 
https://cloud.skylarbarrera.com/Screen-Shot-2022-11-21-12-42-10.11.png
if gas loads for polygon we're good 2 go since bsc isn't hooked up yet, shown in PoW
=> chore: use meteorology for polygon & bsc

src/components/svg/SvgImage.js
Fixes APP-229
our animated svg checks were pretty 💩. from here on out we will show a web view for SVG's on the expanded state so we can ensure things look like they should.
for any other preview images we already show the low res png's we generate so this wont impact perf at all. 
in linear ticket since this is super top secret 
in ticket
=> fix: animated svgs

src/handlers/swap.ts
Fixes APP-240
sometimes socket's gas limit estimate fails and returns us a value of 120k which is very low, especially for L2s and when there may be a swap happening as well.
We now use our own network specific gas limits if its > than the value socket gives us. We over estimate by `1.5` so this should fix any issues
Bunch of xc swaps ig
=> fix: xc swap gas limit logic

src/helpers/assets.ts, src/helpers/buildWalletSections.tsx
Fixes APP-235
I could repro when switching wallets as it was getting triggered while assets were still loading, added a loading check and we gucci 
https://cloud.skylarbarrera.com/Screen-Recording-2022-11-29-12-17-27.mp4
switch wallets a bunch
=> fix: eth placeholder loading check

src/components/asset-list/AssetList.js
Fixes APP-255
- android wallet screen wasn't fully loading on app launch bc of some weird recycler asset list shit
- this fix prob isn't *ideal* but is fine given amount of work it would take to investigate asset list memoization
- this works bc it prevents the recycler asset list from rendering until all the assets are loaded in
https://www.loom.com/share/ee3d9354ad574347af43b2dc407bf6ce
=> Android loading fix

src/languages/index.ts
Fixes APP-257
- added support for template literals in `@/languages`
=> Add lang template literal support

src/hooks/useSwapCurrencyList.ts, src/screens/CurrencySelectModal.tsx, src/screens/discover/components/DiscoverSearch.js
we were showing bridging on discover search because we use the same hook to generate the list. ive added variable to check if its from discover. we should revisit this and seperate the logic
https://cloud.skylarbarrera.com/Screen-Recording-2022-12-01-12-57-32.mp4
open l2 asset other than eth, go to discover search
=> fix search: add discover check

src/App.js, src/config/experimental.ts, src/handlers/deeplinks.ts, src/hooks/useScanner.ts, src/languages/_english.json, src/languages/_french.json, src/redux/walletconnect.ts, src/utils/walletConnect.ts
Now that #4439 is in, the next step is to enable pairing with WC v2 dapps. All of this is behind a flag that's toggle-able in Developer Settings.
This PR enables you to scan the QR code and connect. It doesn't do anything else.
First, enable WC v2 in dev settings. Make sure you have `WC_PROJECT_ID` in your env.
Then use the [v2 test dapp](https://react-app.walletconnect.com/). Test on mobile too!
- When connected, you should see the buttons for things like `personal_sign`. These don't do anything right now.
- Try disconnecting, then reconnecting using the existing connection you just created.
Use the [v1 test dapp](https://example.walletconnect.org/) to test the existing flows. Nothing should have changed there.
=> feat: set up initial WC v2 pairing

package.json, src/parsers/requests.js, src/redux/requests.ts, src/screens/TransactionConfirmationScreen.js, src/utils/walletConnect.ts, yarn.lock
Once paired with a dapp, handles signing and transaction requests using our existing UI. Basically just event plumbing.
See #4443 for testing details. Once enabled, you can use the V2 test dapp to send requests to your connection.
=> feat: handle signing requests

src/handlers/deeplinks.ts
Fixes APP-####
Addresses two bugs introduced in https://github.com/rainbow-me/rainbow/pull/4443
1. `uri` passed to `handleWalletConnect` can be null
2. `dispatch(walletConnectSetPendingRedirect())` was previously called at the top of the function so it would always be executed, now added to the `else` block
=> [APP-297] Fix wc deeplink regression

package.json, yarn.lock
* Added a new resolution to package.json which patches the json5 vulnerability.
* We used various versions of json5, looking at changelogs of json5 there were no breaking changes from the lowest version to the newest we used so we should probably be fine
* json5 is used by some TS compiler related packages and in babel related packages, so if it builds we are fine
=> Fix json5 vulnerabilities

src/helpers/assetSelectors.ts, src/helpers/buildWalletSections.tsx, src/hooks/useWalletSectionsData.ts, src/parsers/accounts.js, src/parsers/index.ts, src/screens/ShowcaseSheet.js, src/screens/WalletScreen.js
* Back when we created RecyclerAssetList2, there were some constraints that caused us to keep around the original buildWalletSections logic (in addition to the new "brief" versions). After the profiles changes were finished, we decided we would clean it up. This is that cleanup finally.
* There are 2 pieces of info that needed to be taken care of by the new "brief" versions:
1. sections data used for prefetching chart data for the top above-the-fold assets (for now, I have just removed this functionality; I can follow up with a list of assets provided by the "brief" version)
2. isEmpty (which now just uses the "isEmpty" that was in one of the "brief" wallet data selectors)
* Test standard wallet data behaves as expected
* Test Showcase behaves as expected
=> Remove non-brief wallet sections data selector

src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx, src/components/walletconnect-list/WalletConnectV2ListItem.tsx, src/helpers/walletConnectNetworks.ts, src/languages/_english.json, src/languages/_french.json, src/redux/walletconnect.ts, src/screens/ConnectedDappsSheet.js, src/screens/WalletConnectApprovalSheet.js, src/utils/walletConnect.ts
This PR shows the active WC v2 sessions in the ConnectedDappsSheet. It allows for updating the wallet, but not the chain, since WC v2 doesn't support chain switching. Instead, you connect to multiple chains from the dapp.
This PR required a new way to display multiple networks, so we borrowed the networks pill from the token expanded state. I used it in the ConnectedDappsSheet, as well as in the WalletConnectApprovalSheet.
See #4443 for details. New things:
- dapps sheet should show both v1 and v2 sessions
- note the different handling of switch networks
- overflow menu on homescreen should only show "Connected Dapps" if there are active sessions
- should hide if none
- even when viewing the list of dapps, if you disconnect in a v2 dapp, it should update
- session approval sheet should …
=> feat: wc v2 connected dapps, ui polish

src/components/walletconnect-list/WalletConnectV2ListItem.tsx, src/languages/_english.json, src/languages/_french.json, src/redux/walletconnect.ts, src/screens/ConnectedDappsSheet.js, src/screens/ExplainSheet.js, src/screens/WalletConnectApprovalSheet.js, src/utils/walletConnect.ts
Adds some additional logging and error handling e.g. TIL `pairing.pair()` throws if it fails, and that we should restrict the RPC methods to only those we support. The latter is obvious in hindsight, but wasn't possible at the time of our original v1 implementation, and wasn't clear from the v2 docs.
Only visual change is adding another explainer to the `ExplainSheet` so that we can show the user different error messages.
I manually threw some errors here and there to simulate these. Nothing in this PR should be evident when testing it locally.
New error screen. Need some copy feedback.
=> feat: more error handling for invalid RPC or failed pairing

src/screens/transaction-details/TransactionDetails.tsx, src/screens/transaction-details/components/TransactionDetailsStatusActionsAndTimestampSection.tsx
Fixes APP-310
* There is a rare case where for tx details for failed swaps, under the condition that we have all of the data for that transaction, on small devices like iPhone SE there's not enough space for everything. In order to be able to show all the data in one go on iPhone SE we will disable the status Icon and leave just text (this will work this way only for such large sheets)
* Scroll will also be enabled, it will be scrollable only when the content is larger than the device height, so it is handling another edge case where a device is smaller than iPhone SE
* This case is so rare that it almost never happens because for transactions we dispatch from the app, there's usually gas data missing, but just in case there is everything we have to make it scrollable in some way to be …
=> Add scroll enabled back and disable status icon for short phones

android/app/src/main/java/me/rainbow/MainApplication.java, package.json
fixes android builds, dep is unneeded and unused with the latest of the BLEpackage
https://cloud.skylarbarrera.com/Screen-Shot-2023-01-04-16-07-14.20.png
=> chore: remove com.polidea.reactnativeble.BlePackage import

src/redux/walletconnect.ts, src/screens/WalletConnectApprovalSheet.js, src/utils/walletConnect.ts
From a [comment from Ben](https://github.com/rainbow-me/rainbow/pull/4476#discussion_r1049006205), it makes sense to align these props now.
This would affect v1 connections moreso than v2. Here's [the v1 example dapp.](https://example.walletconnect.org/)
=> feat: align approval sheet navigation params

audit-ci.jsonc
ignore debug audit 
I tried to bump the package but then the audit-ci process hangs so opting to ignore since its low severity 
https://github.com/advisories/GHSA-9vvw-cc9w-f27h
=> audit: ignore debug

src/screens/ExchangeModal.tsx
Fixes APP-311
logic was changes in https://github.com/rainbow-me/rainbow/commit/38d23b6c15682d43388ead25017cb313b0f69b5b , this is the missing piece to ensure the `Signer` is on the current network for the transactions
https://cloud.skylarbarrera.com/Screen-Recording-2023-01-11-12-18-38.mp4
=> fix swaps: load the correct provider when loading wallet

src/handlers/LedgerSigner.ts, src/logger/debugContext.ts
Fixes APP-267
adds first pass of the ledgerSigner, this handles sending the transaction signing requests to the actual device
not being used yet just getting the file in 
note: we are pushing most of the error handling out of this flow since this will be triggered within our rap structure which does not have the capabilities to handle such cases without a massive rewrite. We will be doing most of this checking up front, only relying on basic retry logic here in case theres a small hiccup. 
also adds debug context for ledger logging
nit
nit
=> ledger: init ledgerSigner + logger context

src/raps/actions/ens.ts
* added a hardcoded NetworkType.mainnet to temporary RainbowTransactio before we have upstream data
=> Fix ENS transactions bug, missing network parameter in RainbowTransaction

src/languages/_english.json, src/languages/_french.json, src/screens/transaction-details/components/TransactionDetailsAddressRow.tsx
Fixes APP-341
* Changed the copy from View Contact to Edit Contact in new transaction details when you already added an address to contacts
=> Change copy from View Contact to Edit Contact to avoid confusion

package.json, yarn.lock
Fixes APP-399
See linked Linear ticket. This will resolve the Dependabot PRs as well.
=> fix: ReDoS Vulnerability in ua-parser-js version

src/model/wallet.ts
Fixes APP-417
instanceof check was using a file with BT lib imports which is what triggers permissions, now just checking if the opposite is true 
n/a
no BT permission request
=> fix: bt permissions signTypeData

src/redux/explorer.ts
Fixes APP-407
removed old logic that was preventing us from updating certain L2 token pricing info 
no
OP price should update after some time
=> fix stale L2 pricing 

src/languages/_english.json, src/languages/_french.json, src/screens/ExplainSheet.js, src/screens/WalletScreen.js, src/screens/rewards/RewardsSheet.tsx, src/screens/rewards/components/RewardsAvailable.tsx, src/screens/rewards/components/RewardsContent.tsx, src/screens/rewards/components/RewardsDuneLogo.tsx, src/screens/rewards/components/RewardsEarnings.tsx, src/screens/rewards/components/RewardsStats.tsx, src/screens/rewards/components/RewardsStatsCard.tsx
* Fixed Android shadows after adding button press animation
* Added explainer sheets with temporary content to all cards with i marks
* Exmplainer sheets will work only for OP rewards and are hardcoded
More in LInear
=> Rewards explainer sheets

src/screens/rewards/RewardsSheet.tsx
* Commented out the asset price retrieval and hardcoded undefined as asssetPrice value, this causes fallback usage of backend provided usd values
=> Revert to using all prices in USD

src/model/config.ts, src/screens/discover/components/DiscoverHome.js
Fixes APP-####
changes Discover screen logic to follow our remote config logic instead of on device balance checks 
had to add profiles to remote config as well 
https://cloud.skylarbarrera.com/Screen-Recording-2023-02-13-15-41-44.mp4
remote config
=> add profiles to config and edit logic

src/design-system/components/Text/Text.tsx, src/screens/rewards/components/RewardsLeaderboardItem.tsx
* Truncating long ens names int the leaderboard
=> Truncate long leaderboard ENS names

src/languages/_english.json, src/languages/_french.json, src/screens/rewards/components/RewardsStats.tsx, src/screens/rewards/constants.ts
* Fixed improper names on stats cards – Swap -> Swapped , Bridge -> Bridged
=> Fix wrong my stats cards titles

ios/Rainbow.xcodeproj/project.pbxproj
* Removed `DiscoverSheet` group from XCode project. It was there in the PBXProj as a leftover from cleaning done some time ago
Extracted from https://github.com/rainbow-me/rainbow/pull/4641 to be a separate more granular PR
=> Remove DiscoverSheet XCode Group

patches/react-native-palette-full+1.2.0.patch, src/components/asset-list/RecyclerAssetList2/profile-header/ProfileAvatarRow.tsx, src/components/ens-profile/ProfileCover/ProfileCover.tsx, src/components/expanded-state/ContactProfileState.js, src/components/expanded-state/UniqueTokenExpandedState.tsx, src/components/unique-token/UniqueTokenCard.js, src/hooks/index.ts, src/hooks/useAccountAccentColor.ts, src/hooks/usePersistentDominantColorFromImage.ts, src/screens/ENSAssignRecordsSheet.tsx, src/screens/ENSConfirmRegisterSheet.tsx, src/screens/ProfileSheet.tsx
Fixes APP-437
* Changed hook code, to run in a more optimized way and cause less component re-renders.
* Problems stemmed mostly from the way `useMMKVString` works, it updates its internal state exactly one render after, which caused double effect calls, that then caused double expensive color calculation. On top of that it wasn't grabbing the initial state from MMKV properly causing to alwasy run color logic on first render. Right now it should run once and be saved in MMKV forever for an instance of a passed URL.
* Added option to sign urls inside the hook instead of having to remember to pass a signed url to the hook
* Left signing as an option because we sometimes use public urls with low resolution that don't need to be resigned.
=> Optimize usePersistentDominantColorFromImage hook

src/screens/SendSheet.js
chainAssets no longer holds any info for the L2s, so this codepath is unused. This is just removing the code and pulling it out as a normal utility and it does not need to be async.
=> Remove unused codepath for L2 chain assets check in SendSheet

package.json, src/handlers/cloudBackup.ts, src/screens/AddWalletSheet.tsx, yarn.lock
* Patched the `react-native-cloud-fs` library to properly handle logout
* Added a logout call to be the first thing to do when user clicks on restore from backup button
=> Add logic to log user out properly when trying to restore backups while having no wallets

src/screens/AddCash/providers/Ramp/index.tsx
Fixes APP-468
Just configures [swapAsset](https://docs.ramp.network/configuration#swapasset) for Ramp URL, restricts purchasers to only networks we support for now.
=> feat: restrict Ramp to supported networks

src/raps/common.ts
Fixes APP-272
our logic did not handle the scenario where a rap had a starting nonce of 0, if this was the case we wouldnt send the rest of the actions 
https://cloud.skylarbarrera.com/Screen-Recording-2023-02-27-11-47-38.mp4
create a new wallet, send assets, try to do a swap
=> raps: fix 0 nonce scenario 

src/navigation/Routes.android.js, src/utils/authentication.ts
Fixes APP-469
Adds a util to prompt and determine if a user is the controlling user (passes FaceID, or pin code on Android).
```typescript
import { isAuthenticated } from '@/utils/authentication';
const authed = await isAuthenticated() // => boolean
```
=> feat: add isAuthenticated util

src/components/buttons/TokenSelectionButton.js, src/components/exchange/ExchangeField.tsx, src/components/exchange/ExchangeInputField.tsx, src/components/exchange/ExchangeMaxButton.tsx, src/components/exchange/ExchangeNativeField.tsx, src/components/exchange/ExchangeOutputField.tsx, src/hooks/useColorForAsset.ts, src/screens/ExchangeModal.tsx
didnt consider the case for assets that are not in our wallet, added handling for that case and refactored some props to keep it clean 
https://cloud.skylarbarrera.com/Screen-Shot-2023-03-02-11-14-17.13.png
colors in swaps
=> fix: asset colors for assets not in wallet

src/analytics/index.ts
Nit: I like to leave debug mode on for the most part, but I almost never need to introspect where we call analytics events.
=> fix: only show analytics debug if explicitly enabled

src/handlers/authentication.ts, src/handlers/dispersion.ts, src/handlers/imgix.ts, src/handlers/localstorage/common.ts, src/handlers/localstorage/removeWallet.ts, src/handlers/opensea-api.ts, src/handlers/poap.ts, src/handlers/tokenSearch.ts, src/handlers/walletReadyEvents.ts, src/handlers/web3.ts
Actually, promoted this PR to update all logs in `@/handlers`. Basically tl;dr:
- caught errors should be `RainbowError`s, and give specific context, not just pass the `Error` object in
- old `logger.log` only works in dev, so most of those are `debug` now
- old `logger.sentry` is a breadcrumb, so those are `info` now, unless they were within a `catch` in which case `logger.error` also adds a breadcrumb in addition to the Sentry issue
=> feat: use new logger in localstorage handlers

src/notifications/tokens.ts, src/redux/walletconnect.ts, src/utils/walletConnect.ts
Just cleaning up local dev logs and updated `getFCMToken`.
I don't think `getFCMToken` should throw, I think we should handle the errors closer to call-site so we get better context on what happened.
=> fix: getFCMToken handling, logging

src/handlers/localstorage/common.ts
So I guess the reason were were swallowing errors before my recent changes was because most of them we don't need to report. But some we might.
=> fix: quiet known storage errors

src/handlers/cloudinary.ts
Noticed I was getting dozens (or more) of [these errors](https://rainbow-me.sentry.io/issues/3984585080/?query=is%3Aunresolved+imgix&referrer=issue-stream&statsPeriod=14d) locally, and this was the culprit.
=> fix: cloudinary signing error

android/build.gradle
I noticed in React Native docs, that with version 0.68 (we use it) Kotlin version was bumped to 1.6.10, we were still using an old version. I used the same version as in the docs, the app still builds fine.
https://reactnative.dev/blog/2022/03/30/version-068#breaking-changes-and-version-bumps
=> Bump Kotlin version 1.6.10

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/layout/launch_screen.xml, android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/styles.xml
Change the accent color in the android app config to get rid of default teal color that we had before
Here's what it changes + will change that teal color in all other places it is used by default, like native time pickers etc.
=> Change android accentColor to blue60, match color names with RDS

src/react-query/queryClient.ts
So we have `persisterVersion` which ensures that if we change data shape, we don't get old data from the cache. But we don't have a way to evict old data from the cache once it's there.
This PR changes the default cache from `Infinity` to one week, to ensure that even old data is garbage collected eventually.
=> fix: no infinite cache in React Query

src/components/walletconnect-list/WalletConnectV2ListItem.tsx
Fixes APP-504
I fixed this. Requests to unsupported networks are rejected and the user is alerted. I don't think we need to show them here.
Looks like this now:
=> fix: only show supported network icons in connected dapps sheet

src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
Fixes APP-522
* NFT floor price in app currency showed NaN if floor price value was "< 0.001 ETH"
* this occurred b/c parseFloat doesn't work if the string starts with a character that is not a number or whitespace
=> Release: Fix floor price bug

src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
Fixes APP-524
* when old, pre-simplehash poap data was transformed into a `UniqueAsset`, the nft image was assigned to the `animation_url` attribute. since this is no longer the case, nft expanded state was failing to find the poap image by checking `animation_url`.
=> Release: Fix POAP NFT expanded state bug

src/components/svg/SvgImage.js
Fixes APP-523
The bug: Some svgs aren't rendering properly in the nft expanded state
After some research, it appears that svgs that contain `foreignObject` tags containing other images are the affected group. The svg itself will render, but these nested images do not. The only known examples are all NFTs in this collection: https://opensea.io/collection/toadstoolz. Here's an example svg provided by simplehash https://cdn.simplehash.com/assets/bc47ebcd09dbd93ac932a5fcf0c69625bf23422a2f540fde7f3f7b4f3697038c.svg
I've also tested this with trivial svgs I created and found the same result.
The fix until I investigate further: 
If the svg html contains a foreignObject tag, fallback to displaying the nft as a png.
Created a follow-up ticket: …
=> Release: Fix SVG rendering bug

src/handlers/transactions.ts
Fixes APP-####
IDK when but the endpoint changed. See https://docs.flashbots.net/flashbots-protect/rpc/status-api
So this is currently broken and flashbots transaction are getting stuck for longer even if they were mined earlier.
Before: https://protect.flashbots.net/0x4201de095d7bf8cefd521e387e40497222cfddfffec0a97c2fc617416347179f
After: https://protect.flashbots.net/tx/0x4201de095d7bf8cefd521e387e40497222cfddfffec0a97c2fc617416347179f
Flashbots txs
=> Fix flashbots tx status endpoint

src/components/gas/GasSpeedButton.js
Fixes APP-480
mainnet gas estimates are in seconds, L2's are in milliseconds 😠 
this should be refactored but after changing it at the source it broke a bunch of shit, there seems to be logic to support this disconnect -> going to leave this for my larger networks refactor
https://cloud.skylarbarrera.com/Screen-Shot-2023-03-30-16-43-06.13.png
cross chain swap time estimates
=> fix bridge time estimates

src/navigation/Routes.android.js, src/navigation/Routes.ios.js, src/navigation/config.js, src/navigation/routesNames.js, src/screens/Explain/index.tsx
Fixes APP-512
New Explain sheet. Usage:
```tsx
import * as ex from '@/screens/Explain';
const { open } = ex.useExplainSheet();
open(() => (
<>
<ex.Title>This is the title component</ex.Title>
...etc
</>
), { sheetHeight: 400, ...options });
```
I've been pasta-ing this into `ProfileActionButtonsRow` when clicking on the `BuyButton`.
```tsx
open(() => (
<>
<ex.Emoji>👋</ex.Emoji>
<ex.Title>New Sheet Who Dis</ex.Title>
<ex.Body>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed ex id lacus tempor hendrerit eu sit amet dolor. Curabitur arcu nisl, aliquam nec risus id, laoreet consequat magna.</ex.Body>
<ex.Body>Etiam pharetra nulla non est finibus, ut luctus nisi viverra. Nunc id sem sit amet ipsum posuere pharetra ut id nisl. Pellentesque a suscipit nisl.</ex.Body> …
```
=> feat: new Explain sheet

src/navigation/Routes.android.js, src/navigation/Routes.ios.js, src/navigation/config.js, src/navigation/routesNames.js, src/screens/Explain/README.md, src/screens/Explain/index.tsx, src/screens/Portal/README.md, src/screens/Portal/index.tsx
Renames `Explain` to `Portal`, adds a non-hook way to open a Portal, and ensures that new DS components show up correctly within it i.e. dark/light mode.
```typescript
import * as portal from '@/screens/Portal'
portal.open(() => <>...</>, {...options}) // new non-hook API
```
=> feat: rename new `Explain` sheet to `Portal`

src/model/backup.ts, src/model/wallet.ts, src/screens/AddWalletSheet.tsx
* Changed `createWallet` function to use an object to pass params instead of a chain of optional params.
* Updated its usages accordingly
=> Refactor `createWallet` function to use object params structure

src/components/backup/BackupManualStep.js, src/components/secret-display/SecretDisplayCard.tsx, src/components/secret-display/SecretDisplayError.tsx, src/components/secret-display/SecretDisplaySection.tsx, src/components/secret-display/SeedWordGrid.tsx, src/components/secret-display/index.ts, src/components/secret-display/states.ts, src/languages/_english.json, src/languages/_french.json, src/screens/SettingsSheet/components/ShowSecretView.tsx
* Added a new message that is shown in case there's any issue retrieving seed. That takes care of the issue that we always displayed a message that the seed was secured with biometrics.
* Refactored the whole secret display section to be easier to reason about, now it has clear states instead of multiple booleans that then make the state
* Broke it down into smaller components
* Refactored styles to not use styled components
* Removed a state that was unreachable, that was essentially dead code
=> Improve error messages when revealing seed phrase fails

ios/Podfile.lock, src/components/backup/RestoreCloudStep.js, src/redux/wallets.ts
Fixed issue with wrong backup status for wallets when restoring specific backup (from backup section in settings). The issue was because we had a sort of race condition when dispatching redux thunks. When there were multiple wallets we dispatched all thinks in the same time with the same initial state, but inside only updated one wallet's data, which caused only the last wallet to be updated. I added a new thunk which takes an array of wallet IDs to update instead of dispatching multiple times for just one wallet ID
=> Fix incorrect backup status after restoring backup from backups settings section

src/components/backup/RestoreCloudStep.tsx, src/handlers/authentication.ts, src/languages/_english.json, src/languages/_french.json, src/model/backup.ts, src/model/wallet.ts
* Refactored the code to show incorrect password error immediately instead of first asking for PIN code
* Refactored `restoreCloudBackup` function to return clear statuses stating whether the restore was successfull or what is wrong
* Changed RestoreCloudStep to use typescript
* Fixed TypeScript in PIN code handling related code
=> Change behavior to report wrong backup password immediately

src/components/change-wallet/WalletList.tsx, src/walletConnect/sheets/AuthRequest.tsx
Fixes APP-555
I was misled by what watchOnly meant, so ledger wa showing up when it shouldn't, also added the param so a user can't create new wallets via wc auth flows
=> fix ledger import visibility + wc auth nav param 

src/App.js, src/handlers/deeplinks.ts, src/logger/debugContext.ts, src/utils/branch.ts
Fixes APP-548
See comments in file for details. This was initially motivated by WC connections failing when the app was not running (see ticket). Along the way, I developed a better understanding of how all this works and improved our initial startup handling of deeplinks as well as improved our logging around this stuff. Hopefully more clear in the future.
=> fix: deeplinks

src/keychain/index.ts, src/model/keychain.ts
I noticed that I introduced a regression: `loadAllKeys` does need to be able to return a falsy value. For example, in backups, if a user cancels auth, that nullish value is what we're using to show an alert to the user. Edge case, but need to fix this.
=> fix: maintain fn signature for loadAllKeys

src/walletConnect/index.tsx
Fixes APP-615
So v2 functionality wasn't actually broken. Previously, we allowed unsupported methods (even though listed as required) and then later rejected any requests to them. This was a decision made based on v1 functionality.
In v2, in the new `buildApprovedNamespaces` util from the WC team, unsupported required methods result in that utility method throwing an exception, which needs to be handled. **So what we saw when we couldn't connect to v2 was actually more strict validation of the session, which was throwing an exception that wasn't being handled** (bc it didn't need to be before). This isn't mentioned in the docs but I've requested the addition.
[WC doesn't throw specific errors](https://github.com/WalletConnect/walletconnect-monorepo/blob/1cbfa29ca0e27589b71efdfbcbfb5f98b01b …
=> fix: fail on unsupported methods, and reject thrown session builder errors

src/handlers/swap.ts
Fixes APP-609
we not use the allowance target and fallback to the rainbow router contract if there is no allowance target (regular swaps)
n/a
=> swaps gas: use allowanceTarget

src/utils/authentication.ts
In testing a separate PR, Ibrahim noticed that if biometrics are disabled on iOS, we fail auth for Ratio. This PR fixes that.
=> fix: ensure we can fallback on iOS with no bio

src/handlers/deeplinks.ts
Opensea noticed that we weren't always redirecting back to their mobile app after signing. This was because of the dedupe logic I added a while back to prevent trying to pair the same topic multiple times. We need to only dedupe fully qualified URLs, not the simple deeplinks that are used to send the user back to our app to sign.
=> fix: only cache fully qualified WC URIs

e2e/swapSheetFlow1.spec.js, e2e/swapSheetFlow2.spec.js
I can't seem to get these swipe views to first swipe, then click. We're already testing toggling between networks and selecting options, so I think we can just remove these here and ideally move them into integrations tests one day.
=> fix: remove broken/redundant swaps tests

src/design-system/components/Text/Text.tsx, src/screens/WalletConnectApprovalSheet.js
Fixes APP-610
This may have always been an issue for long account names, hard to say. Only way I could get it to work is to force it with a maxWidth and lose the middle elllipsis, which wasn't being calculated correctly (always overflowed).
=> fix: overflowing account name in approval sheet

src/notifications/NotificationsHandler.tsx
Wayne noticed this. Since we don't have a reliable way of determining if the notification originated on desktop or mobile, we need to not assume. Setting the pending redirect is only needed for mobile dapp connections.
Deeplinks handling is correct since that only affects mobile.
=> fix: don't add back redirect to notifications handler

src/helpers/networkTypes.ts, src/networks/gnosis.ts, src/networks/index.ts, src/networks/types.ts, src/screens/ExchangeModal.tsx, src/styles/colors.ts
realized I broke poaps with my network refactor, this adds a gnosis network obj with everything disabled except for NFTs to fix the issue
=> fix poaps: gnosis dummy network

src/handlers/web3.ts, src/screens/TransactionConfirmationScreen.js
we had a very small hardcoded gasLimit  that was causing failed txs when estimates fail and there is no limit give from the dapp
ive gone ahead and adjusted our gasEstimation logic to fallback to the latest blocks gas limit which seems to be standard practice, this should ensure we don't underestimate gas. see notes section here: https://docs.alchemy.com/reference/eth-estimategas
I also added logic to check which of the following gas limits is higher and use that one in the tx: out estimate & gas limits passed from the dapp
=> improve gas estimates

package.json, src/analytics/event.ts, src/handlers/__tests__/deeplinks.test.ts, src/handlers/deeplinks.ts, src/hooks/useScanner.ts, src/hooks/useWalletConnectConnections.ts, src/redux/walletconnect.ts, src/walletConnect/index.tsx
- new `wcNewPairing` and `wcNewPairingTimeout` tracking events
- added `connector` param to existing walletconnect tracking events
- improved typing for `handleWalletConnect` `uri`, skipping missing uris, and debug logging
- refactor `handleScanWalletConnect` to more clearly describe the expected params
- parsing optional `connector` query param from deep link, https, and qr data uris
- passing optional `connector` param through walletconnect tree
- tests for `&connector=` addition to walletconnect uris
- removed unnecessary `@ts-ignore` on `dappUrl` tracking events
- WalletConnect v1 and v2 on iOS and Android
- Deep link, https, and wc: uris were modified
=> walletconnect connector attribution

src/components/cards/NFTOffersCard/Offer.tsx, src/screens/mints/PoapSheet.tsx
Fixes APP-####
Problem:
* when offers RQ cache is updated, offers shown in the card sometimes display outdated/incorrect time until expiration
* to make things more confusing for the user, when they click one of these offers, the expanded state shows correct data
Cause:
* Since `Offer` (the offer component of the discover screen card) is recycled by `FlashList` where the key equals the uniqueId of the underlying NFT, `Offer` **does not unmount** as long as the NFT remains present in the list of offers. It just rerenders based on its updated props.
* Since `timeRemaining` is stored in state, it does not get re-initialized based on the new offer
* The effect of this is
1. expiring `Offer`s don't update to reflect new data until at least 1 minute later (according to pre-existing countdown …
=> Fix NFT Offers card bug

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
- Added back keyboard area #5000
- Added the ability to accept NFT Offers #4965
- Get NFT expanded state floor price from Reservoir if available #5006
- React Native version bump #4955
- Improved image performance #5001
- Goerli support #4986
- Updated Base network icon #4992
- ERC-20 charts haptics fix #5004
- Fixed some crashes in appstate #5002
- Fix WC app redirects #5005
=> Version bump 1.9.0

src/components/PromoSheet.tsx, src/screens/hardware-wallets/PairHardwareWalletAgainSheet.tsx
when we moved away from fast image we started using the vanilla RN image component everywhere
turns out it doesnt like having any children, in those cases we need to use ImageBackground  instead
=> images: use imagebackground where applicable

src/handlers/web3.ts
Shea from Flashbots confirmed that this will not have any side effects on the Flashbots Transaction Status API. Including all builders while only exposing the hash should allow for generally faster inclusion when the transaction is valid.
=> chore: Update flashbots protect RPC to include all builders

.github/workflows/macstadium-e2e.yml
we are blocked from using detox until they update with support for RN 72, this should at least our CI merge restrictions for now
=> CI: temp disable e2e

src/parsers/gas.ts, src/redux/gas.ts
Fixes APP-799
we were not adding the l1 fee to 1559 gas estimations since this code was initially only for mainnet 
now we add it 
https://cloud.skylarbarrera.com/Screen-Shot-2023-09-26-14-47-56.04.png
gas should match p close with the bx for op chain gas estimations
=> gas: l1 optimism fee estimation

src/App.js
Method removeEventListener was removed from AppState in ReactNative v0.71
The OldApp component needs to keep EventSubscription in it's state, and then call remove method on in componentWIllUnmount.
This PR will stop the TypeError in componentWillUnmount crashes.
=> handling appstate Event subscription correctly

android/app/src/main/java/me/rainbow/MainActivity.java
As per the react-native-screens documentation on Android setup: Discards any Activity state persisted during the Activity restart process, to avoid inconsistencies that lead to crashes.
Linear ticket has broader context
Fixes APP-850
Requires this update to android preinstall hook: https://github.com/rainbow-me/rainbow-scripts/pull/133
=> Fix crashes resulting from react-native-screens Activity restart on Android

android/app/src/main/AndroidManifest.xml
Fixes APP-851
Additional context in Linear ticket. 
What to test: deeplinking still working as expected
=> Remove deprecated InstallListener in Android manifest which is causing a ClassNotFoundException crash for Android users

e2e/deeplinks.spec.js, e2e/watchedWalletCollectionActionsFlow.spec.js
1. When opening deeplinks with cold start, the account assets state comes back empty, find a fix and then change these tests to cold-start again
2. Profile deep links in e2e tests needed to be updated according to the latest URL changes in the app deep links handler.
3. Added check if wallet-screen is fully visible for watchedWalletCollectionActionsFlow test before progressing to the next test, hopefully this will make this test less flaky. (not 100% confirmed, just a guess atm)
=> fixed deeplink test by avoiding cold start

src/screens/CurrencySelectModal.tsx
Fixes APP-746
we were using the wrong chainID to set the decimals, was using the input instead of the output. now we use the correct one and quotes are 💯
https://cloud.skylarbarrera.com/Screen-Shot-2023-10-19-12-13-12.56.png
=> swaps: fix crosschain chainID in seach

src/screens/SendSheet.js
Fixes APP-651
we just need to keep updating max value as gas changes 
https://cloud.skylarbarrera.com/Screen-Recording-2023-10-16-13-26-58.mp4
=> send: fix max send for native balances

src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.tsx
Fixes APP-867
Changed the default prop for `<ButtonPressAnimation />` => `disallowInterruption` on Android to `true`. This prevents the tap event passing through to anything underneath it.
=> [Android] Fix: ButtonPressAnimation not stopping tap event propagation

patches/react-native+0.72.0.patch, patches/react-native-pager-view+5.4.24.patch, src/components/activity-list/ActivityList.js, src/components/asset-list/RecyclerAssetList2/index.tsx, src/screens/discover/DiscoverScreen.tsx
- Sets `delaysContentTouches = NO` on the scroll view underlying `SwipeNavigator`, which fixes button press animations within tabs on iOS
- Fixes scroll indicator positioning
- Brings back smooth rounded corners
=> Fix button press animation, scroll indicators

src/screens/PointsScreen.tsx
The interval triggering the animation on the Points screen causes detox tests to hang due to "unfinished action", we need to disable the animation for detox to synchronize and move on with the tests.
=> Disabling animation interval when IS_TESTING is true

src/utils/reviewAlert.ts
Review alert blocks E2E tests. Turning the popup off when IS_TESTING=true.
=> Review Alert blocks E2E tests, disabling when IS_TESTING=true

src/model/wallet.ts, src/parsers/requests.js, src/screens/TransactionConfirmationScreen.js, src/utils/signingMethods.ts, src/walletConnect/index.tsx, src/walletConnect/types.ts
Fixes APP-853
we are disabling eth_sign 
n/a
wc connections to a bunch of dapps to make sure this doesn't mess with the connection logic
=> wallet: rm legacy eth_sign

e2e/discoverSheetFlow.spec.js, src/navigation/SwipeNavigator.js
Added TestID to SwipeNavigator tabs, which allowed us to use tapping navigation for a test that was freezing the App while attempting to swipe out of Discover screen.
=> Fixed E2E test DiscoverSheetFlow

e2e/deeplinks.spec.js, e2e/sendSheetFlow.spec.js
Re-enabling previously failing tests for which the underlying issues were addressed.
=> Re-enabled tests in deeplinks and sendSheetFlow

src/screens/mints/MintSheet.tsx
Fixes APP-886 APP-885
adds l1fee for OP networks that should have been there intially 
now we use the raw eth value for tx value 
https://cloud.skylarbarrera.com/Screen-Shot-2023-10-26-10-04-13.33.png
OP gas fee should be greater than $.01
=> mints: l1fee + value fix

src/components/transaction/TransactionMessage.js, src/model/wallet.ts, src/utils/signingUtils.ts
Fixes APP-810
added sanitation for EIP 712 signs to match the BX
=> walletconnect: sanitize 712 signs

src/migrations/index.ts
Fixes APP-907
I caused a regression on the new migrations that was causing them to run on every app load 🙃 😅 
thankfully they're pretty harmless atm
this fixes the language revert on open
=> lang: fix english revert

src/entities/nonce.ts, src/redux/nonceManager.ts, src/screens/SettingsSheet/components/DevSection.tsx
Fixes APP-659
adds nonce reset to clear pending txs
=> nonces: reset nonces

src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinBadge.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx, src/components/coin-icon/CoinIcon.tsx, src/components/coin-icon/CoinIconFallback.js, src/components/coin-row/FastTransactionCoinRow.tsx, src/components/exchange/ExchangeTokenRow.tsx, src/utils/getUrlForTrustIconFallback.ts
Fixes APP-872
* Fixes coin icons on the Activity screen that were falling back to text instead of icon images
* Migrates some components to start using network instead of assetType
What to test is mentioned in Linear ticket
=> Fixes for activity list coin icons and migrating some components to network instead of assetType

src/helpers/support.ts, src/languages/en_US.json
Fixes APP-913
Changed the copy to reflect the linear issue. Also, changed the hierarchy of the buttons to be more CTA friendly.
=> Update copy for an Error Occurred message for Support

src/screens/mints/MintSheet.tsx
gas was erroring and overriding the insufficient balance state, this is fixed now 
I also removed the disabling of the quantity button as it was letting users get in a stuck state when a mint only supports minting 1 but we are unaware
=> mints: fix insufficient eth check

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
- Tx Simulation
- RPC Proxy updates
- Remote promo sheet capabilities
- ‘An error occurred’ popup changes
- ‘An error occurred’ popup changes
- Android navigation bar now matches app theme
- Infinite render on swaps modal bug fix
=> v bump 1.9.11

src/screens/SignTransactionSheet.tsx
Some dapps using ethers are sending us tx types as a hex value but ethers doesn't like this and throws and error: 
https://cloud.skylarbarrera.com/Screen-Shot-2023-11-30-15-39-54.82.png
added handling to convert if we run into them
=> wc: handle hex tx types

src/notifications/NotificationsHandler.tsx, src/notifications/types.ts
Fixes APP-934
added simple handling for marketing focused notifications, we already technically had support for them but now it allows us to navigate to different screens
https://cloud.skylarbarrera.com/RPReplay_Final1701273411.MP4
android, can't build locally atm 😮‍💨
=> notifications: general marketing

src/navigation/SwipeNavigator.js, src/screens/discover/components/DiscoverSearch.js
Fixes APP-883
Fixes the height issue on the search component not accounting for the newly added bottom tab bar
https://github.com/rainbow-me/rainbow/assets/6284525/b7d1bdc9-8a3e-4699-9414-363d126207fb
=> [APP-883]: Fix scroll issue on discover search

src/helpers/utilities.ts, src/languages/en_US.json, src/resources/points.ts, src/screens/SignTransactionSheet.tsx, src/screens/points/constants.ts, src/screens/points/content/PointsContent.tsx, src/screens/points/content/ReferralContent.tsx, src/screens/points/content/console/calculate.tsx, src/screens/points/content/console/initialize.tsx, src/screens/points/content/console/review.tsx, src/screens/points/content/console/share.tsx, src/screens/points/contexts/PointsProfileContext.tsx
Fixes APP-971, APP-963, APP-975, APP-967, APP-965, APP-964, APP-986, APP-988
=> Bug bash fixes

src/components/cards/FeaturedMintCard.tsx
Fixes APP-962
tweaked some css to allow for special characters in featured mint titles
=> [APP-962]: Fix special characters overflowing due to lineHeight

src/App.js, src/handlers/LedgerSigner.ts, src/model/wallet.ts, src/navigation/Routes.android.tsx, src/navigation/Routes.ios.tsx, src/screens/points/contexts/PointsProfileContext.tsx
Fixes APP-970
https://cloud.skylarbarrera.com/RPReplay_Final1702316398.MP4
=> add ledger

src/screens/points/content/PointsContent.tsx
Fixes APP-993
Apparently the `maskElement` prop of `MaskedView` does not rerender on android unless the `androidRenderingMode` prop is set to `"software"`. This was causing the total points display to not _immediately_ update when switching wallets. If you switch tabs and return to the points tab, it displays the correct amount.
see: https://github.com/react-native-masked-view/masked-view/issues/132
https://www.loom.com/share/4aae0f4d260f41ffadb53cabc9038d24
=> Points: Fix total points not updating when switching wallets [ANDROID]

src/screens/points/contexts/PointsProfileContext.tsx
Fixes APP-1001
When the user signs in, `signPersonalMessage` is called. This function calls `loadWallet` which calls `loadAddress`. The error was occurring because `loadAddress` was loading the wrong address. I investigated this, but wasn't able to get to the bottom of it. To circumvent this issue, the user's `accountAddress` (which is correct) is now passed into a call to `loadWallet` which is passed into `signPersonalMessage`.
Ticket for overarching issue:
https://linear.app/rainbow/issue/APP-1010/loadaddress-may-return-wrong-address-after-wallet-creation
https://www.loom.com/share/02f23fa6cfcc4d7e82617ec903dd26cb
To repro on `develop`:
1. switch to a watched wallet
2. create a new wallet
3. onboard to points
4. error should occur when signing in
=> Points: Fix onboarding error

src/screens/points/components/LeaderboardRow.tsx
Fixes APP-998
- just had to change the max width on the ens name to account for mask view on rank 3 and below
=> [APP-998]: Fix for leaderboard formatting issue

src/helpers/utilities.ts, src/screens/points/content/PointsContent.tsx
Fixes APP-1015
abbreviate total users and rank (in rank card only) if x >= 1,000,000
ex. 1,234,567 => 1.23m
=> Points: Tweak rank card formatting

src/screens/points/content/ReferralContent.tsx
Fixes APP-1007
- added parsing of red code from ref links
- disabled `maxLength={7}` temporarily until I can figure out how to use both
=> [APP-1007]: Add parse ref code from ref link

src/languages/en_US.json, src/screens/points/constants.ts
Fixes APP-1016
* display minutes in next drop time (mike wants it to say 4:20pm in EST)
* say "Today" instead of day of week if drop is happening today
=> Points: date formatting in next drop card

src/languages/en_US.json, src/screens/points/components/InfoCard.tsx, src/screens/points/content/PointsContent.tsx
Fixes APP-1017
* change "out of" to "of"
* if small phone, don't show icon if 8 fig total users
* for user rank:
* if 8 figs, size = "17pt"
* if 7 figs, size = "20pt"
* else, size = "22pt"
=> Points: format large numbers in rank card

src/resources/points.ts, src/screens/points/contexts/PointsProfileContext.tsx
Fixes APP-1008, APP-1009
* fixed logic to refetch on next drop. useEffect was never getting executed
* added 5 min stale time (aka refetch every 5 min) to match bx
* added refetch of points data 5s after sign in to accommodate backend changes (https://rainbowhaus.slack.com/archives/C02C8JQ313N/p1702424983615549)
=> Points: points query fixes

src/screens/points/constants.ts, src/screens/points/content/PointsContent.tsx
Fixes APP-1006, APP-999
- add commas to rank card rank in points tab
- add commas to # of pts distributed in tweet intent
=> Points: some number formatting

src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx, src/components/sheet/sheet-action-buttons/SwapActionButton.js, src/screens/ExchangeModal.tsx
Fixes APP-956 APP-954
changes the swap entry point to be the main swap screen instead of the currency select modal 
3 cases -> swap button, swap existing asset, swap to a new asset(discover)
added subtitle only to the receive current select list as well
https://cloud.skylarbarrera.com/Screen-Recording-2023-12-12-15-00-55.mp4
cases
=> swaps: revert entry point

src/hooks/useSwapDerivedOutputs.ts
Fixes APP-860
Unable to trace the origin of this, so going to add some logging so we can have more info on what's going on
=> [APP-860]: Add debug logs for cross-chain bug discovery

src/screens/points/constants.ts
Fixes APP-####
* due to potential encoding differences, newlines are not showing up on android. quick fix is to replace newlines with spaces on android
follow-up: https://linear.app/rainbow/issue/APP-1029/investigate-encodeuricomponent-cross-platform-differences
=> Points: fix tweet intent

src/screens/points/content/ReferralContent.tsx
Fixes APP-####
* fix bug that makes it possible for read-only wallets to enter onboarding flow after deeplinking in from a referral link
https://www.loom.com/share/d5004d1751ba4c26b9e58ff4f8819e97
=> Points: block read-only wallets from onboarding after deeplinking

src/screens/points/constants.ts
https://rainbow-me.sentry.io/issues/4709955399/?project=1855565&query=is:unresolved&statsPeriod=7d&stream_index=0
Fixes `TypeError: Cannot read property 'trigger' of null` flooding our Sentry logs.
=> fix haptics null issue

src/helpers/statusBarHelper.ts
Android navigation bar was set to match the theme color in gesture mode which made all pop-up sheets contain (most of the time) the wrong color. This sets it to transparent if using the gesture mode which should use the color of the background of whatever sheet is underneath it.
=> fix navbar not being transparent on android gesture mode

src/components/asset-list/RecyclerAssetList2/WrappedCollectiblesHeader.tsx, src/components/asset-list/RecyclerAssetList2/WrappedPositionsListHeader.tsx, src/components/expanded-state/UniqueTokenExpandedState.tsx, src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx, src/components/list/ListHeader.js, src/components/list/ListHeaderMenu.tsx, src/handlers/ens.ts, src/helpers/assets.ts, src/languages/en_US.json
- Sort UI polish
- Enables last sale/floor price for all networks
- Now only fetching Reservoir floor price when necessary, as a fallback, to align the floor price in the expanded state with the sorted floor prices
=> NFT sort cleanup

src/graphql/queries/metadata.graphql, src/languages/en_US.json, src/screens/points/components/InfoCard.tsx, src/screens/points/content/PointsContent.tsx
Fixes APP-1031
* display that user is "unranked" if points < 750. `unranked` is a property provided by backend so app doesn't actually check the user's point count.
* see figma here
=> Points: UI for "unranked" users

src/hooks/useSwappableUserAssets.ts
=> fixes for assets not refreshing

src/model/remoteConfig.ts
Fixes APP-####
* prevent app from getting stuck while awaiting remote config (default wait limit is 1min)
=> Add 3s limit when awaiting remote config

e2e/discoverSheetFlow.spec.js, src/screens/SettingsSheet/components/DevSection.android.tsx, src/screens/SettingsSheet/components/DevSection.tsx, src/screens/SettingsSheet/components/SettingsSection.tsx
Fixes APP-890
removing testnet settings from user facing since its been rugged for like 6 months
keeping it all there in case we reprioritize it
=> chore: hide testnet settings

src/hooks/useInitializeWallet.ts
=> switch to breadcrumbs

src/screens/points/content/PointsContent.tsx, src/screens/points/content/console/view-weekly-earnings.tsx
Fixes APP-1081
fixes a weekly earnings bug i mentioned in [#backend](https://rainbowhaus.slack.com/archives/C02C8JQ313N) and adds https://linear.app/rainbow/issue/APP-1081/replace-total-points-users-w-change-in-rank-in-rank-card
https://cloud.skylarbarrera.com/Screen-Recording-2024-01-18-12-39-28.mp4
unranked user: https://cloud.skylarbarrera.com/Screen-Shot-2024-01-18-12-44-49.31.png
=> weekly earnings fix and leaderboard diff

src/screens/points/components/LeaderboardRow.tsx, src/screens/points/content/PointsContent.tsx
Fixes APP-####
* if rank increases, should show red text with negative slope graph
* if rank decreases, should show green text with positive slope graph
* formatting for large rank changes (ex. 1234 -> 1,234)
* remove negative sign from rank change display in case of rank decrease
* also fixed an issue that is evident in screenshots below where neither the ens nor wallet address is displayed in the leaderboard row
1. current rank - last week rank = 1234
2. current rank - last week rank = -1234
3. current rank - last week rank = 0
=> Points: rank card fixes

src/resources/assets/assets.ts
Fixes APP-1097
new balances endpoint is sending non compatible asset types which was causing issues. were not forcing the legacy types assumed by the codebase until we switch over all of those instances
=> chore: force asset types

src/components/expanded-state/asset/ChartExpandedState.js, src/components/expanded-state/chart/ChartExpandedStateHeader.js, src/languages/en_US.json
Fixes APP-1090
this exposed a few regressions that came from us allowing search of L2 only assets, before search ran under the assumption that all results were on mainnet which is no longer the case. working on a few smol tweaks rn
there's some more work that can be done but its contingent on us moving off out zerion websockets first
https://cloud.skylarbarrera.com/Screen-Recording-2024-01-22-12-57-56.mp4
=> search: l2 clean up

src/components/svg/SvgImage.js
Fixes APP-1096
xtra svg sanitization 
https://cloud.skylarbarrera.com/Screen-Recording-2024-01-24-11-18-41.mp4
=> svgs: sanitization

src/handlers/swap.ts, src/hooks/usePriceImpactDetails.ts
Fixes APP-1109
context in the ticket. most of the code is adapted from the BX
did a lot more QA this time 
wrap eth: ![](https://cloud.skylarbarrera.com/Screen-Shot-2024-01-25-15-16-25.75.png)
eth to erc20: 
erc20 to eth: 
erc20 bridge: 
eth bridge: 
culprit eth bridge:
=> @skylar/price impact followup

src/analytics/event.ts, src/languages/en_US.json, src/screens/points/ConsoleSheet.tsx, src/screens/points/constants.ts, src/screens/points/content/console/require-wallet-balance.tsx, src/screens/points/contexts/PointsProfileContext.tsx
Fixes APP-1032
* added ConsoleSheet step for handling backend error type that rejects user from onboarding due to not having a wallet balance
* tweaked some error handling, we were unnecessarily logging errors
https://github.com/rainbow-me/rainbow/assets/15272675/6bbdef83-a184-4911-9cef-165cfe7519e6
https://github.com/rainbow-me/rainbow/assets/15272675/3ba7103c-e79d-4c23-8d9c-00a36cb7e938
If you have a wallet w/ a balance that has not onboarded to points yet, would be good to test that
=> Points: require wallet balance UI

e2e/deeplinks.spec.js
hoping this fixes some flake with deeplink tests, if this passes ill revisit enabling some of the other ones in this flow
=> e2e: deeplinks - use 0x addresses

src/notifications/NotificationsHandler.tsx
=> notifications: fix marketing route props

src/graphql/index.ts, src/resources/cards/cardCollectionQuery.ts, src/resources/cards/cardQuery.ts, src/resources/mints.ts, src/resources/pointsTweetIntent/pointsTweetIntentCollectionQuery.ts, src/resources/pointsTweetIntent/pointsTweetIntentQuery.ts, src/resources/promoSheet/promoSheetCollectionQuery.ts, src/resources/promoSheet/promoSheetQuery.ts, src/resources/reservoir/mints.ts, src/resources/reservoir/nftOffersQuery.ts, src/screens/mints/PoapSheet.tsx, src/utils/poaps.ts
Fixes APP-####
I noticed that a bunch of places in the app use the incorrect arc client which is very dangerous. To fix this, and avoid this in the future, I centralized the arc client selection to one location that exports the proper client to use.
=> chore: centralize arc client selection

android/gradle.properties
This enables me to now build Android on release and debug mode
Did a sanity check on QR code scanning (payment request, rainbow profile and WC) and all looked good!
=> Disable frame processor for vision camera 

src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinBadge.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx, src/components/coin-row/FastTransactionCoinRow.tsx, src/components/exchange/ExchangeTokenRow.tsx
the fast coin icon component was created to be used in certain coin rows, with that being the case there was extra spacing being added to the component that causes unforeseen formatting issues when used elsewhere
i've moved this out and added that spacing where it was intended to be
=> coin icon: pull out spacing

src/hooks/useSwapInputHandlers.ts
Fixing max native swaps
we were subtracting gas 2.5 times so users would get the "not enough balance" error when they shouldnt be 
now we allow full max balance swaps
=> swaps: fix max native check

src/migrations/index.ts, src/migrations/migrations/migratePinnedAndHiddenTokenUniqueIds.ts, src/migrations/types.ts
Fixes APP-1166
uniqueIds for mainnet are not `address_network` instead of just `address`
=> chore: migrate pinned + hidden tokens

src/screens/SendSheet.js
erc20 sends have accent colors and nfts did not so im adding for funzies
=> fun: add color to nft sends

src/components/expanded-state/UniqueTokenExpandedState.tsx, src/languages/en_US.json
Fixes APP-####
added sell button to nft expanded state if offer exists. opens offer expanded state.
https://github.com/rainbow-me/rainbow/assets/15272675/e30a811c-c3cd-4a07-bee7-5f4b73bc2d35
=> nft expanded state sell button

src/components/expanded-state/UniqueTokenExpandedState.tsx, src/components/send/SendAssetFormCollectible.js, src/components/unique-token/UniqueTokenCard.js, src/components/unique-token/UniqueTokenImage.js, src/resources/nfts/simplehash/utils.ts, src/utils/handleNFTImages.ts
Fixes APP-1169
we may need to revisit the lowResUrls and make sure we are signing gifs  ✅
NFTs should load and display properly
=> chore: reduce imgix usage - nfts

src/analytics/userProperties.ts, src/hooks/useTrackENSProfile.ts, src/notifications/analytics.ts, src/screens/WalletScreen/index.tsx
identify calls without deviceID were cuasing MAU issues on segment, this uses the new analytics client that adds this under the hood
=> analytics: fix identify calls

src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx, src/components/expanded-state/unique-token/saveToCameraRoll.js, src/utils/getFullResUrl.ts
Fixes APP-101, APP-428
* update import from camera roll package
* switch unique asset image url that was being saved. before, some ipfs uris were sneaking thru
need to test on android still
=> fix saving nft images

src/components/exchange/ExchangeField.tsx, src/components/exchange/ExchangeInput.js, src/components/exchange/ExchangeNativeField.tsx
run into this intermittently figured i'd throw some null safety in there
=> input field focus null safety

package.json, src/helpers/statusBarHelper.ts, yarn.lock
=> [FIX]: Increase number of pixel difference needed to qualify as non-gesture mode navigation

src/components/coin-row/FastTransactionCoinRow.tsx
adds fallback icons for contract interactions and where we may not have nft images
=> txs: fallback icons

src/components/coin-row/FastTransactionCoinRow.tsx
=> mints: fix mint pending label

package.json
Fixes APP-####
Everyone should be using Xcode 15 which no longer has the 14 pro sim, but it has the 15 pro sim by default.
=> Bump sim version

src/screens/SendConfirmationSheet.tsx
- property should be theme.isDarkMode
- error was hidden by the comment in the above line
- only impacted ens confirmation screen
=> property should be theme.isDarkMode

ios/Podfile.lock, package.json, yarn.lock
- Includes this fix for a crash we're seeing on Android:
https://github.com/software-mansion/react-native-reanimated/pull/5759
=> Bump reanimated to v3.8.0

src/hooks/usePendingTransactions.ts, src/navigation/SwipeNavigator.tsx
Fixes APP-1225
Added pending tx indicat0r
https://github.com/rainbow-me/rainbow/assets/29204161/bb78606c-7a18-4a67-aa31-6e467a7ff2eb
=> txs: add pending tx indicator

src/analytics/userProperties.ts, src/resources/reservoir/nftOffersQuery.ts
Fixes APP-####
* fixes this crash https://rainbowhaus.slack.com/archives/C0468CDBE75/p1710885267376909
* the crash was occurring when NaN values were being passed into `analytics.identify`. segment apparently didn't complain, but rudderstack does NOT like this
* in the nft offers hook, the mean/median floor difference percentage is calculated for all offers. this involves accessing arrays and dividing those accessed values by other numbers. the problem occurred when there were no NFT offers - trying to access an empty array yields undefined, and dividing undefined by a number yields NaN
* the fix: added some length checks to the array before trying to access + utilize its values. also renamed some analytics properties bc they were confusing
BEFORE: …
=> NFT Offers: crash fix

src/hooks/useWatchPendingTxs.ts
=> balances: fetch twice tx confirm

src/components/DappBrowser/search-input/SearchInput.tsx
- menuConfig was missing the `isGoogleSearch` dependency
=> Fix browser context menu not updating

src/components/DappBrowser/BrowserContext.tsx, src/components/DappBrowser/BrowserTab.tsx, src/components/DappBrowser/search-input/SearchInput.tsx, src/components/DappBrowser/search/SearchBar.tsx
- This fixes the issues causing the link to the active tab ref to break in certain cases, particularly when going from the homepage to a URL
- The ref (with a null value) was being set in webViewRefs in certain cases before the WebView was mounted, for instance when going from the homepage to a website
- Added a forward button to the context menu
- Reloading should now always work
- Back/forward buttons should now show and work correctly, and persist through reloads and tab switches
=> Browser: fix ref assignment, back/forward navigation

src/components/DappBrowser/BrowserContext.tsx, src/components/DappBrowser/BrowserTab.tsx
- Deletes `webViewRefs` entirely — no reason to hold all of the refs in the context as far as I can tell
- `activeTabRef` takes its place and is assigned the correct ref from the tab itself when that tab becomes active
- This is cleaner and faster and should work equally
=> Browser: remove webviewRefs

ios/Podfile.lock, package.json, src/components/DappBrowser/BrowserTab.tsx, yarn.lock
- Passing `screenshotSource.value` to the `source` prop rather than `screenshotSource` prevents the screenshot from being set immediately — this PR fixes that
- Also bumps faster-image from 1.3.4 to 1.4.3 for some Android fixes
=> Fix instant screenshot setting

src/components/DappBrowser/BrowserTab.tsx
Fixes APP-####
Websites with cloudflare protection weren't working. for ex. dexscreener.com
This PR fixes this
https://github.com/rainbow-me/rainbow/assets/1247834/f3fadea6-2559-441f-bebf-f822191fc628
=> Fix cloudflare protection

src/components/exchange/ExchangeDetailsRow.tsx, src/components/exchange/PriceImpactWarning.tsx, src/components/expanded-state/SwapDetailsState.js, src/components/expanded-state/swap-details/SwapDetailsSlippageMessage.js, src/hooks/usePriceImpactDetails.ts, src/languages/en_US.json, src/screens/ExchangeModal.tsx
Fixes APP-1295
it appears that when we have no pricing data, the price impact always severe at 100%
if we haven't gotten the price impact response yet, it's NaN
~pending final copy from @christianbaroni~
that this message is not shown when we do have price impact data
=> added warning for unknown price impact

src/components/backup/RestoreCloudStep.tsx, src/components/backup/useCreateBackup.ts, src/components/backup/usePasswordValidation.ts, src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx, src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
=> Fix: Wallets being marked as backed up by walletLoadState()

src/model/remoteConfig.ts
Fixes APP-####
boolean remote config values need to be explicitly parsed as booleans. otherwise, they'll get parsed as strings. this is bad bc "true" and "false" are both truthy values
=> Fix network remote config stuff

src/screens/WelcomeScreen/index.tsx
- I built with `IS_TESTING=false` and the screen worked fine
- I built with flag on and animations were gone
- can confirm this is not the behavior on current develop
- this change is what fixed CI-8 i believe
=> Disable welcome screen animations when IS_TESTING

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
bump iOS and Android versions to v1.9.22
=> bump iOS and Android versions to v1.9.22

ios/Podfile.lock, ios/Rainbow.xcodeproj/project.pbxproj, package.json, src/logger/__tests__/logger.test.ts, src/logger/index.ts, src/utils/sentry.ts, yarn.lock
Fixes APP-1370
Bumped sentry sdk to latest
context to what this fixes: https://rainbowhaus.slack.com/archives/C0468CDBE75/p1713454106026279
=> [APP-1370]: bump sentry sdk to latest

ios/Rainbow.xcodeproj/project.pbxproj, src/__swaps__/screens/Swap/components/TokenList/TokenList.tsx, src/__swaps__/screens/Swap/components/controls/SwapActions.tsx, src/__swaps__/screens/Swap/components/controls/SwapInputAsset.tsx, src/__swaps__/screens/Swap/components/controls/SwapOutputAsset.tsx, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/hooks/useSwapWarning.ts
- Fixed some edge cases when user chooses to swap assets
- Fixed some missing logic in the useSwapWarning hook that prevented warnings from being reset
=> Fix random quote edge cases

package.json, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, yarn.lock
Fixes APP-1357
- Adds a call to fetch the slippage if the user hasn't defined their own just before executing a swap.
=> Add backend provided slippage

src/components/DappBrowser/Homepage.tsx
Fixes APP-1339
fixes android card overflow
=> browser: fix android card images

src/components/DappBrowser/BrowserTab.tsx, src/components/DappBrowser/ErrorPage.tsx, src/languages/en_US.json
Fixes APP-####
https://github.com/rainbow-me/rainbow/assets/1247834/7ea1c0f2-a60a-4025-85ec-43919432a8e4
=> Add default error page

src/hooks/useSyncSharedValue.ts, src/worklets/comparisons.ts
- Adds a new `useSyncSharedValue` hook that makes it easy to keep a shared value in sync with equivalently typed state
=> useSyncSharedValue

src/hooks/useAccountTransactions.ts, src/hooks/usePendingTransactions.ts, src/hooks/useWatchPendingTxs.ts
using smoller state subscriptions for current zustand stores outside of the browser
=> zustand: use smol subscriptions

src/components/DappBrowser/BrowserTab.tsx, src/components/DappBrowser/DappBrowser.tsx, src/components/DappBrowser/types.ts
Fixes APP-####
Fixes the issue where there's no web3 provider injected on the current tab when doing an app cold start.
=> Delay tab rendering till injectedJS is in memory

src/components/DappBrowser/constants.ts, src/components/DappBrowser/types.ts, src/state/browser/browserStore.ts
- First part of the new browser architecture
- Creates `browserStore`, which is used to manage and persist the browser state
- Uses a new custom zustand+MMKV store purpose-built for the browser data, with lazy serialization and background persistence
- Leverages latest zustand APIs
- Handles the necessary conversion of the `tabsData` `Map` to an `Array` when persisting and reading from storage, since JSON serialization doesn't handle them properly by default
- We can probably extract some of this to make it reusable and improve our other stores
=> Browser: browserStore

src/hooks/reanimated/useAnimatedInterval.ts, src/hooks/reanimated/useAnimatedTime.ts, src/hooks/reanimated/useAnimatedTimeout.ts
- New hooks for working with time in Reanimated
- `useAnimatedInterval` and `useAnimatedTimeout` are both built on top of `useAnimatedTime`
**Example:**
```
const { reset } = useAnimatedInterval({
intervalMs: 5000,
onIntervalWorklet: () => {
'worklet';
console.log('Logging once every 5 seconds');
},
});
const onPress = () => {
reset();
}
```
=> useAnimatedTime, useAnimatedInterval, useAnimatedTimeout

src/components/DappBrowser/handleProviderRequest.ts, src/languages/en_US.json
Fixes APP-1409
- We were not accepting chainIds in hex format (etherscan does that) which was causing the incorrect "unsupported chain id" message.
- Match the behavior with the BX where we ask the user to start a session first before we're able to switch chains.
https://github.com/rainbow-me/rainbow/assets/1247834/4d2ccf5d-9231-4674-83ad-1de902918e73
=> Fix supported chains bugs

package.json, src/raps/unlockAndCrosschainSwap.ts, yarn.lock
Upgraded sdk version to 0.19.0, now supporting reservoir relay instant bridges.
Supported networks:
* socket
* mainnet
* OP
* BSC
* Arbitrum
* Polygon
* Base
* Avalanche
* relay
*  mainnet: eth, usdc
* OP: eth, usdc
* Arbitrum: eth, usdc
* Base: eth, usdc, degen
* Blast: eth
* Zora: eth
* Degen: degen
Swaps, crosschain swap and bridges flows
* relay supports bridging eth <-> eth, usdc <-> usdc and degen <-> degen
* For relay's ERC20 bridging, no approval tx is needed
Need to publish new sdk version on [npm](https://www.npmjs.com/package/@rainbow-me/swaps)
=> feat: upgrading swap sdk to 0.19.0

src/components/DappBrowser/BrowserTab.tsx, src/components/DappBrowser/Homepage.tsx, src/components/DappBrowser/search-input/AccountIcon.tsx, src/components/DappBrowser/search-input/SearchInput.tsx, src/components/DappBrowser/search/results/SearchResult.tsx, src/components/DappBrowser/search/results/SearchResults.tsx, src/languages/en_US.json, src/state/browserHistory/index.ts
Fixes APP-1342
Fixes APP-1436
Fixes APP-1340
also added i18n where missing, fixed some small android style issues
=> browser: android fixes v2

src/components/DappBrowser/BrowserContext.tsx, src/components/DappBrowser/BrowserTab.tsx, src/components/DappBrowser/CloseTabButton.tsx, src/components/DappBrowser/DappBrowser.tsx, src/components/DappBrowser/Homepage.tsx, src/components/DappBrowser/ProgressBar.tsx, src/components/DappBrowser/WebViewBorder.tsx, src/components/DappBrowser/control-panel/ControlPanel.tsx, src/components/DappBrowser/hooks/useAnimatedTab.ts, src/components/DappBrowser/hooks/useScreenshotAndScrollTriggers.ts, src/components/DappBrowser/hooks/useSmoothScrollView.ts, src/components/DappBrowser/hooks/useTabScreenshotProvider.ts, src/components/DappBrowser/search-input/SearchInput.tsx, src/components/DappBrowser/search-input/TabButton.tsx, src/components/DappBrowser/search/Search.tsx, src/components/DappBrowser/search/results/SearchResult.tsx, src/components/DappBrowser/search/results/SearchResults.tsx, src/components/animations/animationConfigs.ts, src/languages/en_US.json, src/resources/metadata/dapps.tsx, src/state/internal/createRainbowStore.ts
- Fixes ScrollView jitter that previously occurred when closing tabs, and on Android when zooming into tabs
- Fixes control panel wallet list sorting — new ordering:
- Imported/hardware wallets (from highest balance to lowest)
- Watched wallets (also adds “Watching” labels)
- Fixes initial tab view scroll position
- Fixes tearing when creating new tabs
- Improves disabled control panel button styles
- Disables the “Favorite” control panel button on the homepage
- Improves tab closing animations
- Adds a few missing i18n strings
- Removes unnecessary usages of `React.memo` where it was used on components that aren’t susceptible to re-renders
- Fixes Android homepage card layout
- Fixes Android search input text alignment
- Improves background contrast in the light mode tab view
- Fixes …
=> Browser: release fixes

src/components/DappBrowser/control-panel/ControlPanel.tsx, src/components/DappBrowser/handleProviderRequest.ts, src/components/DappBrowser/search-input/AccountIcon.tsx, src/redux/walletconnect.ts, src/screens/WalletConnectApprovalSheet.js, src/state/appSessions/index.ts, src/utils/requestNavigationHandlers.ts
Fixes APP-####
Small refactor of account switching that solves the following issues:
- Switching accounts doesn't force connect anymore.
- Accounts can be switch even if not connected
- The account that's currently selected by the tab is what will be selected by default when the connect prompt shows up
Account switching demo:
https://github.com/rainbow-me/rainbow/assets/1247834/f1761bc0-7be1-43f5-b4b8-dc9d552e3ab0
Select account respected on the connect flow
https://github.com/rainbow-me/rainbow/assets/1247834/5e20addd-29c9-4ca1-9d92-b8344e77a891
=> Account switching fixes

src/components/DappBrowser/DappBrowser.tsx, src/components/DappBrowser/Homepage.tsx, src/components/DappBrowser/ProgressBar.tsx, src/components/DappBrowser/control-panel/ControlPanel.tsx, src/components/DappBrowser/handleProviderRequest.ts, src/components/DappBrowser/hooks/useAnimatedTab.ts, src/components/DappBrowser/hooks/useSmoothScrollView.ts, src/components/DappBrowser/search-input/AccountIcon.tsx, src/redux/walletconnect.ts, src/screens/WalletConnectApprovalSheet.js, src/state/appSessions/index.ts, src/utils/requestNavigationHandlers.ts
- Fixes a crash that occurred in the control panel caused by the `appSessions` store
- Fixes account selection logic to make the selected account consistent between the avatar and the control panel
- Fixes control panel account colors
- Adjusts account switching logic to only emit events to the dapp when connected to the dapp
- Fixes an issue where switching accounts when not connected would put the control panel in the connected state
=> Browser: control panel fixes

src/components/DappBrowser/control-panel/ControlPanel.tsx, src/resources/metadata/dapp.ts
Fixes RNBW-4720
https://github.com/rainbow-me/rainbow/assets/1247834/5f2caa7c-68b3-44be-86d1-23c885756d94
=> swaps and bridge checks on control panel

src/__swaps__/screens/Swap/Swap.tsx, src/__swaps__/screens/Swap/components/AnimatedChainImage.tsx, src/__swaps__/screens/Swap/components/AnimatedSwapCoinIcon.tsx, src/__swaps__/screens/Swap/components/CoinRow.tsx, src/__swaps__/screens/Swap/components/SwapBottomPanel.tsx, src/__swaps__/screens/Swap/components/SwapCoinIcon.tsx, src/__swaps__/screens/Swap/components/SwapCoinIconTextFallback.tsx, src/__swaps__/screens/Swap/components/SwapInputAsset.tsx, src/__swaps__/screens/Swap/components/SwapOutputAsset.tsx, src/__swaps__/screens/Swap/components/SwapSheetGestureBlocker.tsx, src/__swaps__/screens/Swap/components/SwapSlider.tsx
Fixes APP-1455
- converted swap coin icon to be use AnimatedFasterImage impl.
- coverted fallback to be an Animated.View
=> add animated coin icons and text fallbacks

src/__swaps__/screens/Swap/components/SwapWarning.tsx, src/__swaps__/screens/Swap/constants.ts, src/__swaps__/screens/Swap/hooks/useSwapWarning.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/languages/en_US.json
=> Swap Warning / Price Impact component

src/__swaps__/screens/Swap/Swap.tsx, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/hooks/useSwapNavigation.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/resources/assets/externalAssetsQuery.ts
Fixes APP-1343
Fixes APP-1457
Added asset price fetching and some react-query external token handling.
=> Asset Prices

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
bump iOS and Android versions to v1.9.24
=> bump iOS and Android versions to v1.9.24

src/__swaps__/screens/Swap/components/AnimatedSwitch.tsx, src/__swaps__/screens/Swap/components/ExchangeRateBubble.tsx, src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/__swaps__/screens/Swap/components/SwapBottomPanel.tsx, src/__swaps__/screens/Swap/hooks/useNativeAssetForChain.ts
=> Cleanup Review Panel + formatting issues

src/hooks/useUniqueToken.ts
Fixes APP-####
some changes i made to the UniqueAsset type caused some issues w/ detecting whether an nft had video/audio/3d model content or not. also caused crashes in some cases
=> NFT expanded state fixes

src/__swaps__/screens/Swap/components/ExchangeRateBubble.tsx, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/utils/swaps.ts
This is preliminary work to make life easier (and more readable) for later. 
This updates 2 formatter util functions: `valueBasedDecimalFormatter` and `niceIncrementFormatter` to switch from using a list of params to an object with named params.
It also updates all places these functions are used.
Expected behavior is that is a no-op.
Commits can be read in order for easier review (first commit updates `niceIncrementFormatter` and the second commit updates `valueBasedDecimalFormatter`)
- Test in the swap flow that the formatting of the input values, output values, exchange rate bubble and slider still behave as expected.
- How I tested: had simulator with my code and the existing testflight on my physical device and compared the input / output / slider / exchange rate bubbles for various …
=> Preliminary work: Update formatter functions to take in object params

src/__swaps__/safe-math/SafeMath.ts, src/__swaps__/safe-math/__tests__/SafeMath.test.ts
- Fixes the `isNumberString` regex check to allow negative number strings
- Updates `scaleUp` and `formatResult` to handle negative numbers correctly — previously they were failing when passed a negative number string
- Adds number comparison functions and tests:
- `equal`
- `greaterThan`
- `greaterThanOrEqualTo`
- `lessThan`
- `lessThanOrEqualTo`
- Converts all functions to worklets — confirmed that tests still run successfully
- Adds a `Worklet` suffix to the safe math function names
=> Swaps: fix safe math negative number support, add comparison functions

src/model/remoteConfig.ts
Fixes APP-####
- enabled `base_swaps_enabled` by default
- enabled `blast_swaps_enabled` by default
- enabled `dapp_browser` by default
=> fix: base blast swaps, dapp browser firebase defaults

src/__swaps__/safe-math/SafeMath.ts, src/__swaps__/safe-math/__tests__/SafeMath.test.ts
Fixes APP-####
Adds more methods:
- log10
- toFixed
- round
- floor
- ceil
Accepts parameters of type `number` or `string`
=> Safemath pt 2

src/__swaps__/screens/Swap/components/EstimatedSwapGasFee.tsx, src/__swaps__/screens/Swap/components/GasButton.tsx, src/__swaps__/screens/Swap/components/GasPanel.tsx, src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/__swaps__/screens/Swap/hooks/useEstimatedGasFee.ts, src/__swaps__/screens/Swap/hooks/useSelectedGas.ts, src/__swaps__/screens/Swap/hooks/useSwapEstimatedGasLimit.ts, src/__swaps__/screens/Swap/hooks/useWhyDidYouUpdate.ts, src/__swaps__/utils/meteorology.ts, src/hooks/useWhyDidYouUpdate.ts
=> Gas optimizations

src/__swaps__/screens/Swap/components/TokenList/TokenToBuySection.tsx
=> Fix other networks section

src/__swaps__/screens/Swap/components/AnimatedSwapCoinIcon.tsx, src/components/images/ImgixImage.tsx
Fixes APP-1534
borderRadius supplied to FasterImage needs to be multiplied by the device's pixel ratio on android
=> fix fasterimage border radius android

src/components/cards/ENSCreateProfileCard.tsx, src/hooks/useOnAvatarPress.ts, src/redux/wallets.ts
Fixes RNBW-4786
- Remove unnecessary fetchWalletNames  and fetchWalletENSAvatars calls from walletLoad
- Move ens prefetch calls inside `onPress` events instead of running every time with useEffect.
This was happening  on `UseOnAvatarPress` and `ENSCreateProfileCard`
WIth 3 wallets we used to have 88 requests on launch.
After the fix with the same 3 wallets we have 16 requests on launch
BEFORE:
AFTER:
=> Reorg and reduce ens related calls

src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/__swaps__/screens/Swap/resources/assets/userAssets.ts, src/handlers/web3.ts, src/hooks/useRefreshAccountData.ts, src/networks/arbitrum.ts, src/networks/avalanche.ts, src/networks/base.ts, src/networks/blast.ts, src/networks/bsc.ts, src/networks/degen.ts, src/networks/gnosis.ts, src/networks/goerli.ts, src/networks/index.ts, src/networks/mainnet.ts, src/networks/optimism.ts, src/networks/polygon.ts, src/networks/types.ts, src/networks/zora.ts, src/resources/assets/useSortedUserAssets.ts, src/resources/assets/useUserAsset.ts, src/resources/assets/useUserAssetCount.ts, src/screens/NFTSingleOfferSheet/index.tsx, src/screens/mints/MintSheet.tsx, src/utils/ethereumUtils.ts
Fixes APP-1567
- Fixes an issue where `getProviderForNetwork` was being repeatedly called throughout the app, for every network, due to the `getProvider` function within the network objects being invoked any time `getNetworkObj` or `getXNetworkObj` was invoked
- Additionally, when `getProviderForNetwork` was called for a not-yet-cached network, the calling of `getNetworkObj` from within `getProviderForNetwork` would then again call `getProviderForNetwork` due to `getProvider` within the network object being invoked, leading to a recursive loop that would run until the provider eventually made it into the cache
- Fixes the return types of the `getProviderForNetwork` and `getCachedProviderForNetwork` functions
- Adds a `getIsHardhatConnected` helper function
=> Fix provider recursion bug, provider function types

src/__swaps__/safe-math/SafeMath.ts, src/__swaps__/screens/Swap/components/AnimatedChainImage.tsx, src/__swaps__/screens/Swap/components/AnimatedSwapCoinIcon.tsx, src/__swaps__/screens/Swap/components/CoinRow.tsx, src/__swaps__/screens/Swap/components/ExchangeRateBubble.tsx, src/__swaps__/screens/Swap/components/FlipButton.tsx, src/__swaps__/screens/Swap/components/GestureHandlerV1Button.tsx, src/__swaps__/screens/Swap/components/SwapCoinIcon.tsx, src/__swaps__/screens/Swap/components/SwapInput.tsx, src/__swaps__/screens/Swap/components/TokenList/ListEmpty.tsx, src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx, src/__swaps__/screens/Swap/components/TokenList/TokenToSellList.tsx, src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/__swaps__/screens/Swap/hooks/useSwapInputStyles.ts, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/__swaps__/utils/swaps.ts, src/utils/deviceUtils.ts
Fixes APP-1538
Fixes APP-1552
Fixes APP-1582
Fixes APP-1583
Fixes APP-1591
Fixes RNBW-4755
- Fixes division by zero crashes
- Fixes exchange rate bubble button presses
- Removes hardcoded decimal places from stablecoin input amounts
- Fixes NaN issues (the `toLocaleString` changes are temporary and will be superseded by Ben's changes)
- Improves buy list data memoization (removes an unnecessary extra useMemo)
- Adds `PIXEL_RATIO` to `deviceUtils`
- Allows flipping when only one asset is selected and speeds up flipping (no longer using `setAsset` which adds a bit of duplicate code but prevents complicating `setAsset`
- Adjusts buy list sorting to ensure the chain's native asset is listed first
- Fixes buy list empty state layout
- Improves performance of the animated input styles, …
=> Swaps: fix crashes, logic and UI fixes

src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/__swaps__/screens/Swap/constants.ts, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/languages/en_US.json
- Hides the Flashbots row in the review sheet outside of mainnet
- Capitalizes review sheet labels
- Cleans up the swap bottom sheet heights — some had decimals
- Moves the sheet height definitions outside of the animated style
=> Hide Flashbots outside of mainnet

src/__swaps__/screens/Swap/components/AnimatedSwapCoinIcon.tsx, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
Fixes APP-1605
- Fixes the input native currency value being 0 initially, due to separators in the input value added by `useGrouping`
- Fixes the light mode swap coin icon placeholder
- Resets the slider position to 50% when the input asset changes
=> Swaps: fix initial input native currency value, light mode coin icon placeholder

src/__swaps__/screens/Swap/components/AnimatedSwitch.tsx, src/__swaps__/screens/Swap/components/CoinRow.tsx, src/__swaps__/screens/Swap/components/EstimatedSwapGasFee.tsx, src/__swaps__/screens/Swap/components/GasButton.tsx, src/__swaps__/screens/Swap/components/GasPanel.tsx, src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/__swaps__/screens/Swap/components/SearchInput.tsx, src/__swaps__/screens/Swap/components/SwapBottomPanel.tsx, src/__swaps__/screens/Swap/components/SwapInput.tsx, src/__swaps__/screens/Swap/components/SwapInputAsset.tsx, src/__swaps__/screens/Swap/components/SwapNumberPad.tsx, src/__swaps__/screens/Swap/components/SwapOutputAsset.tsx, src/__swaps__/screens/Swap/components/SwapSlider.tsx, src/__swaps__/screens/Swap/components/TokenList/TokenList.tsx, src/__swaps__/screens/Swap/constants.ts, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/__swaps__/screens/Swap/hooks/useBottomPanelGestureHandler.ts, src/__swaps__/utils/meteorology.ts, src/references/index.ts, src/state/assets/userAssets.ts, src/utils/gas.ts
Fixes APP-1548
- Adds new gas icons
- Cleans up review sheet styles, hit boxes, gestures, and animations
- Fixes an issue in input asset search where token contract addresses were being searched no matter the query — now only returning exact address matches
- Fixes the input Close button visibility
- Disables some Android borders that weren't rendering correctly, minor Android style fixes
- Fixes paste button styles
- Fixes a crash that occurred on Android when selecting an asset, due to `event.stopPropagation` not existing
- Tested on both iOS and Android
=> Swaps: gas icons, review sheet cleanup

src/handlers/transactions.ts
Fixes RNBW-4748
I was testing #5869 and realized that when sending a transaction that gets rejected by the flashbots API (ex. gas=0) we still continue monitoring it as if it was received ok and we wait forever,  messing up nonces.
This PR considers tx status UKNOWN by the flashbots api as failed, which means the node never received the transaction.
I've tested the whole flow and executed a swap https://etherscan.io/tx/0x6979ab9040f846e5d6b7df09c0fe7dd8314ca7ee05a247485c9935b0c3fa752b without any problems which is why I'm closing RNBW-4748
=> add flashbots unknown type as failed

src/__swaps__/screens/Swap/__tests__/NiceIncrementerFormatter.test.ts, src/__swaps__/screens/Swap/hooks/useEstimatedGasFee.ts, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/__swaps__/utils/swaps.ts
NOTE:
Please see the comments inline of the code to better map out where each of the fixes below correspond in the code.
NOTE: will attach screen recordings / screenshots in comments below so as not to blow up this description section.
Fixes in this branch:
1. typing in an input amount that causes insufficient funds and then deleting the input amount to 0 still displays Insufficient Funds
2. relying on the quote as a source of truth for the sell amount can cause the button to flicker because the quote can still technically have a value / not have an error, even though it is now out of date
3. previously: the `sellAmount` calculation was returning two different orders of magnitude in the response which was incorrect. e.g, when there's a quote error, it would return the input amount (like …
=> Fixes for review button states

src/__swaps__/screens/Swap/components/SliderAndKeyboard.tsx
Fixes APP-####
We were asumming all android phones have the softMenu enabled and that's not the case for my Pixel 4.
I've added a check and adjusted the padding accordingly.
BEFORE
AFTER
=> fix android padding calc

.gitignore, package.json, scripts/graph-ens-key.sh, src/graphql/utils/getFetchRequester.ts
Fixes APP-####
Added a script to override the URL of the new ENS graph and use our API key.
This will work on CI and locally and will prevent us from getting rate limited for using the public url.
Also removed the old url override since the url is the correct one at the config level
=> Use graphql ens key everywhere

src/__swaps__/screens/Swap/components/SwapActionButton.tsx, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/languages/en_US.json
Fixes APP-1614
- Fixes the missing swap button press animations and haptic feedback
- Adjusts the review button state logic to allow entering the review sheet when `isFetching.value === true`, except for the first quote fetch
- When the review sheet is open, if a new quote is being fetched, the `tapToSwap` button now becomes disabled until the new quote is applied
- Moves the `tapToSwap` button state condition further down so that if assets are flipped while in the review sheet, or gas conditions change, the `tapToSwap` button can become disabled
Also:
- Switches the initial `inputMethod` to `inputAmount` if an input asset is selected on mount, which fixes a bug that was causing the input values to change when the swap screen was first opened (very likely due to the animated reaction that …
=> Fix swap button presses, adjust button state logic

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
1. Removed all places where we relied on `typeof` for the input value amounts. This was making things brittle / difficult to maintain / easy to get into scenarios you did not intend.
2. Updated the initial values for native currency to not need to worry about formatting since we have formattedNativeInput to handle that
3. Removed the conditional for the default input method to have it back to be slider based
https://github.com/rainbow-me/rainbow/assets/1285228/82b3f2df-9091-4bc2-a224-abeefa44cabc
=> Remove input value typeof checks

scripts/run-retry-tests.sh
Fixes APP-####
- we were previously rerunning the whole suite if a test failed
- this runs all tests then keeps a note of the failed ones
- it then reruns the failed ones up to the amount of retries set.
=> [e2e] rerun only failed tests

src/__swaps__/screens/Swap/components/SwapNumberPad.tsx, src/__swaps__/screens/Swap/components/SwapSlider.tsx, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/SyncSwapStateAndSharedValues.tsx, src/__swaps__/utils/swaps.ts
- Refactors the swap number pad logic to work without the old string vs. number checks, which are no longer reliable
- This was causing a bug where if for example you dragged the slider, waited for the quote to fetch, and then typed into the output field, the amount in the input would switch to the unformatted, much longer number (the underlying input value)
- Increases the gas buffer from `+/- 0.25x` to `+/- 0.5x` — was changing a bit too often
- Improves the Max button and `formattedInputAmount` checks that determine whether max amount is being swapped, to explicitly check if the underlying input value is exactly the max swappable amount
- Fixes bugs causing the input amount to sometimes exceed the max available balance when swapping max
- Improves slider/max button logic in the case …
=> Fix maxSwappableAmount bugs, remaining string type check bugs

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/utils/numbers.ts
Fixes APP-1627
1. The formatting for max input value was using the `valueBasedDecimalFormatter` which is slightly different from the logic that the balance badge uses. This PR ports over the essential logic of the balance badge into a worklet and uses that for formatting.
2. This also fixes an issue with the non-worklet `handleSignificantDecimals` function that was copied over from helpers/utilities. A comment is added inline below describing the issue.
- Tap max on various input assets (native and non-native) across multiple networks. 
- For non-native assets, the max formatted input value should match the balance badge.
- For native assets, the max formatted input value should look similarly formatted to the balance badge, though the max input amount will be slightly less than what is …
=> Match logic of balance badge to format max input value

src/__swaps__/utils/swaps.ts
Fixes APP-1613
* added comments inline below!
* issue: if the value of the output field is something like "123.00567", the output was displaying "123" instead of "123.00"
* this is because in the `valueBasedDecimalFormatter`, we only specified max decimals and not min decimals, and while the max decimals would be 2, in the instance where we round down for output based values, it was rounding to 123.00 and then just displaying 123
* this PR adds support for minimum and maximum decimals and will serve as a base for future improvements to our decimal formatting. 
* other than the stablecoin change, everything else should be a no-op.
* decimal formatting should not be impacted except for stablecoins as output assets
* at various stablecoin output amounts, any value that is "XXX.00" should …
=> Display 2 decimals at a minimum for stablecoins in valueBasedDecimalFormatter

src/model/remoteConfig.ts
Fixes APP-####
- turned `rewards_enabled` on by default to mitigate issues for users with VPNs that block Firebase APIs
=> chore: amend `rewards_enabled` default

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-1619
Issue: in the Review Panel when you update slippage, it wasn't immediately triggering a quote refetch and would update the minimum received / max sold only at the next interval of fetching.
This triggers a debounced quote refetch on updates to slippage.
Update slippage in the review panel - you should see the actual quote update as well as the minimum received / maximum sold amount for input-based and output-based trades.
https://github.com/rainbow-me/rainbow/assets/1285228/0067acbd-3a2f-4e95-b760-9c9251f279a8
=> Debounce fetch quote after updating slippage

src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/__swaps__/screens/Swap/resources/search/index.ts
Fixes APP-####
the polygon and bsc native assets uniqueIds where wrong (?)
pow native network tokens on top of lists (avax was good already)
should we also sort it to top on input token?
=> sort native network token to top of list

src/components/sheet/sheet-action-buttons/SwapActionButton.tsx
- Should fix the bug causing assets in swap to sometimes not reflect your balance
=> Prefer user asset when prefilling swap assets

src/__swaps__/safe-math/SafeMath.ts, src/__swaps__/screens/Swap/__tests__/NiceIncrementerFormatter.test.disabled.ts, src/__swaps__/screens/Swap/components/ExchangeRateBubble.tsx, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/utils/__tests__/decimalFormatter.test.ts, src/__swaps__/utils/decimalFormatter.ts, src/__swaps__/utils/swaps.ts
1. The `valueBasedDecimalFormatter` now takes into account the magnitude of the asset amount by default. It balances between significant decimals, value-based decimals, and magnitude.
2. Moved out the `valueBasedDecimalFormatter` into a separate file to make it easier to test
3. Added test cases for the `valueBasedDecimalFormatter` for various asset amounts and asset prices, no prices, stablecoins, etc
4. Added an optional param to `valueBasedDecimalFormatter` that the `niceIncrementFormatter` can pass in such that it guarantees that the `valueBasedDecimalFormatter` is always at least +1 more than the `niceIncrementFormatter` number of decimals. This helps resolve scenarios where the "jumps" between increments might end up rounding funnily on the snapping points.
5. Removed …
=> Improve decimal formatter functions

src/components/cards/remote-cards/RemoteCard.tsx, src/state/remoteCards/remoteCards.ts
Fixes APP-1640
There was a cast forcing an object to be treated as `TrimmedCard` while this could be undefined [here](https://github.com/rainbow-me/rainbow/pull/5924/files#diff-24d1832ca4c86c1f5d2420b730c090533428bf3da59142ad6bc64b335aff9ac0L71)
Once I removed it, all the types error showed up and dealt with each of those by using optionals.
The first commit from christian also added some safety checks at the store level.
The app works the same way, it won't crash if we unpublish a card that was already stored in zustand.
Remote cards feature.
=> Prevent crashing on remote cards code

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- This work is a precursor for adding in logic for handling native amount changes
- This removes redundant code and simplifies the logic, making it easier to modify and grok in the future
- Easiest way to review this PR is going commit-by-commit
- Updating input amount, slider, output amount should behave as expected
https://github.com/rainbow-me/rainbow/assets/1285228/61452c8e-95e0-4316-bdaf-c02ef599294b
=> Simplify SwapInputController animated reaction logic for responding to input value changes

src/__swaps__/screens/Swap/hooks/useSwapWarning.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-1671
- updated the swap warning to be a derived value instead of an animated reaction
- removed the unused `SwapTimeEstimate` from the `useSwapWarning` hook
- simplified the logic for calculating the swap warning states
- update the output amount to 0 and then to "0.1" - there should be no flashing of a swap warning
- updating the inputs from the slider / input amount / output amount should behave as expected without any weird flashes
- updating an input amount to some crazy high amount should show a swap warning as expected
https://github.com/rainbow-me/rainbow/assets/1285228/845d7389-4794-4918-b439-b1d3c47efa94
=> Convert swap warning to derived value

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
Fixes APP-1670
- previously, when the output asset changes, we were updating everything except for the `inputMethod` which led to some discrepancies in the behavior. I now update the `inputMethod` regardless of whether the input or the output asset is updated
- updated the function to return early if neither asset was changed, instead of keeping everything in an if statement 
- update the output amount (remove or add numbers)
- change the output asset
- the values should update as expected (based on the input amount)
https://github.com/user-attachments/assets/76b6787f-3eac-475c-8194-06d21afd2079
=> Fix funkiness after output asset change after updating output amount

.github/workflows/macstadium-e2e.yml
Temporarily targets CI-8 and CI-9 which are ready to build with the latest stack required for RN 0.74.3
Here's a run on CI-8 where it got as far as running the tests which is everything we need
https://github.com/rainbow-me/rainbow/actions/runs/10046640311/job/27766537609
=> target ci-8

.github/workflows/macstadium-e2e.yml
Fixes APP-1651
Removing the targeting since now all machines support RN 0.74.3
Here's a run where the build passed on CI-7
https://github.com/rainbow-me/rainbow/actions/runs/10047236016/job/27769406454
CI green
=> Enable CI-7

src/screens/ExplainSheet.js
Fixes APP-1686
We had optionals everywhere except  here
None
Explainer sheets
=> prevent crash on explainer sheet if no read more link

android/settings.gradle, ios/Podfile, ios/Podfile.lock, ios/Rainbow.xcodeproj/project.pbxproj, package.json, src/components/error-boundary/ErrorBoundary.tsx, src/components/error-boundary/Fallback.tsx, src/logger/index.ts, src/logger/sentry.ts, yarn.lock
Fixes APP-1659
Biggest change that needs tested here is the version bump of `react-native-exit-app` from 1.1.0 to 2. I verified it quits the app in develop mode on iOS, but we need to test all environments thoroughly.
Other changes:
- Changed the existing error boundary to use `Sentry.ErrorBoundary` when not `IS_TEST`.
- Also added more error context to the logger report when the user chooses restarts the app.
=> Fix ErrorBoundary Sentry reports

src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/__swaps__/screens/Swap/hooks/useSwapNavigation.ts, src/__swaps__/screens/Swap/hooks/useSwapSettings.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/state/swaps/swapsStore.ts
Fixes APP-1634
added `degenMode` to the swaps store, added a toggle for it (thats not rendered anywhere rn) and made the button skip the review panel when it's active, didn't change the button label for that case tho
=> Degen mode

android/app/src/main/AndroidManifest.xml
Fixes APP-####
Google Play Store is complaining about this permission which we're not using but some dep is requiring it by default so I've explicitly removed from the manifest
=> remove FULL_SCREEN_INTENT permission

src/__swaps__/screens/Swap/components/SwapInputAsset.tsx, src/__swaps__/screens/Swap/components/SwapOutputAsset.tsx, src/__swaps__/screens/Swap/components/SwapSlider.tsx, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-1557
Adds balance badge press setting max swappable amount for asset if user has balance.
Note I also added the functionality to output balance badge.
https://github.com/user-attachments/assets/d123c20e-914d-496d-87ab-3729aa14e1e5
=> Add max swappable amount on balance badge tap

e2e/8_manualBackup.spec.ts, package.json, src/components/asset-list/RecyclerAssetList2/index.tsx, src/components/backup/BackupChooseProviderStep.tsx, src/components/backup/BackupSheet.tsx, src/components/secret-display/SecretDisplaySection.tsx, src/design-system/components/Inset/Inset.tsx, src/screens/SettingsSheet/components/Backups/BackUpMenuButton.tsx, src/screens/SettingsSheet/components/Backups/SecretWarning.tsx, src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx, src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx, src/screens/SettingsSheet/components/Menu.tsx, src/screens/SettingsSheet/components/MenuHeader.tsx, src/screens/SettingsSheet/components/MenuItem.tsx, src/screens/SettingsSheet/components/SettingsSection.tsx
- added coverage for manual wallet backups
- does it pass?
=> [e2e] Manual backup e2e test

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/utils/flipAssets.ts
Fixes APP-1675
Fixes APP-1699
More comments are inline in the code files changed below.
- Moved a couple functions to a separate file to make setting up testing easier later
- Moved the animatedReaction for reacting to asset changes / flips to be done before the animatedReaction that changes the `maxSwappableAmount` value as this was causing the reliance of "did the user intend to use max" check unreliable
- Fixes an issue where from wallet list for testmar27.eth: select BOOMER and swap → the output amount is just 0.0 and when you flip, the input amount goes to "7.5e-8" bc of an unnecessary Number conversion
Overall, the flipping logic will try to figure out which values to used in this priority order:
- base the updated values on the native input amount (requires that there is a valid …
=> Update flipping logic in SwapInputsController

src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-1643
- Prevents intermittent states where tapping can incorrectly trigger submitting a swap
=> Improve hold to press reliability

src/hooks/useLoadGlobalLateData.ts, src/migrations/index.ts, src/migrations/migrations/migrateFavoritesToV2.ts, src/migrations/types.ts, src/resources/favorites.ts
Fixes APP-1683 APP-1676
we can't store based on just the address because for example the degen token in the degen network is address zero, same we use sometimes for eth in mainnet, found lots of lil weird bugs like that I think this fixes it all, probably good to QA this one
=> index favorites by uniqueId instead of address

src/__swaps__/screens/Swap/components/GestureHandlerButton.tsx
- Should prevent a race condition on iOS where the native `ButtonPressAnimation` component that wraps the GH button cancels the press event before the `GestureHandlerButton` long press events are fired
- Makes the `GestureHandlerButton` gesture handler more lightweight when long press functionality isn't needed
- Adds optional `tapRef` and `longPressRef` props to GH button
=> GH button/hold to swap improvements

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
bump iOS and Android version to v1.9.35
=> bump iOS and Android version to v1.9.35

src/__swaps__/screens/Swap/Swap.tsx, src/components/DappBrowser/control-panel/ControlPanel.tsx, src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx, src/state/assets/userAssets.ts, src/state/sync/UserAssetsSync.tsx
Fixes APP-1765
According to swaps spec, the default input asset should be ETH on the network that the user has the most ETH. See this discussion: https://rainbowhaus.slack.com/archives/C0468CDBE75/p1723050551013059
https://github.com/user-attachments/assets/b153a76b-15ba-4cb4-ab00-75aef9af3648
=> Default the Swap input currency to ETH 

.github/workflows/macstadium-e2e.yml
- this will make it easier to expand the test suites in the future by adding different categories to the test jobs
-  suite in the future and will allow Swarmia to see the different categories of jobs so we can see how often e2e fails bc of lint, versus build, and actual tests.
=> Test ci job split

src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/design-system/color/AccentColorContext.tsx, src/design-system/components/Border/Border.tsx, src/design-system/components/Box/Box.tsx, src/design-system/components/Inline/Inline.tsx, src/design-system/components/Stack/Stack.tsx, src/design-system/components/private/ApplyShadow/AndroidShadow.tsx, src/design-system/components/private/ApplyShadow/ApplyShadow.tsx, src/design-system/components/private/ApplyShadow/IOSShadow.tsx
- Updates `Stack` and `Inline` to use the `gap` property, which reduces the number of views the app needs to render by around 10%
- Now skipping mapping over `children` when no separators need to be rendered
- Removes unnecessary flattening and ineffective memoization of `children`
- Adds new border props to `Box` that allow for rendering equivalent cross-platform view borders:
- `borderColor`
- `borderWidth`
- Fixes the `Box` `overflow` prop and its type — previously it wasn't being applied anywhere
- Updates the `height` and `width` `Box` props to allow directly passing in a number
- Adds validation of account accent colors — had seen a few errors complaining about an invalid color being used in `AccentColorContext`
=> Design system improvements

src/__swaps__/screens/Swap/resources/assets/userAssets.ts, src/__swaps__/utils/assets.ts
Fixes APP-1774
* removed asset filter, was causing moxie fan tokens to get filtered out by userAssetsQuery bc ens names were not passing the `isValidDomain` check. see this convo: https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1723248357542129
=> swaps bug fix: missing asset balance for some tokens

src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/resources/favorites.ts
Fixes APP-####
Reverting fallback usage of backend pricing till we can guarantee it's always coming back from BE.
Loading...
=> Fix missing pricing swaps

package.json, src/__swaps__/screens/Swap/components/ReviewPanel.tsx, yarn.lock
Fixes APP-####
- SDK bump supporting the right types for quotes
- Make feeTokenAsset optional
Fixes the crash for WETH < = > ETH in release mode.
https://github.com/user-attachments/assets/5e958c8a-bf39-4392-8c7a-66ca963c6f9d
Wrap & Unwrap
=> Fix Wrap / Unwrap

src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/hooks/useWalletBalances.ts
Fixes APP-1799
* shortened popular tokens list from 6 to 3
* unrelated: added `isLoading` dependency to memoized wallet balances
=> shorten popular tokens list from 6 to 3

src/model/migrations.ts
- There was a previously deleted v19 migration that was preventing the browser favorites migration from running on devices that had already run the old v19 migration
=> Fix browser favorites migration

android/app/build.gradle, package.json, patches/react-native-text-input-mask+2.0.0.patch, yarn.lock
Fixes APP-####
Without this changes we're no longer able to build android for the following reasons:
- BIP39 is no longer found unless we do this https://github.com/NovaCrypto/BIP39/issues/43#issuecomment-1089757699
- react-native-tooltips and react-native-text-input-mask both have similar issues
Nuke and try to build android from scratch
=> fix android deps errors

src/parsers/transactions.ts
Fixes APP-1823
Fixes #5678
- pulls ERC-20 to address from change direction === 'out' for `meta.type === 'send'`
=> Fix improper `to` address for ERC-20 sends

src/hooks/useWatchPendingTxs.ts, src/resources/assets/UserAssetsQuery.ts, src/state/staleBalances/index.test.ts, src/state/staleBalances/index.ts
Fixes APP-1703
When a pending transaction is detected as confirmed, we are flagging the affected assets' addresses and refetching updated user assets balances from BE.
Ensure the token params sent to BE reflect the correct addresses when the app attempts to update user asset balances.
Suggestions from Jin:
multiple transactions, different assets
multiple transactions, impacting same assets
Swap 1: ETH → USDC
Swap 2: SHITCOIN → ETH
=> Implement perceived finality

package.json, src/resources/transactions/firstTransactionTimestampQuery.ts, yarn.lock
fixes APP-1829
See ticket description for slack thread detailing the 3 crashes found during regression
Should be able to press pfp on home. Should be able to advance through the send flow from expanded state and via send button w/o issues
=> fix: remove p-queue

src/walletConnect/index.tsx
Fixes APP-1843
- fixes bad merge from network -> chainId rework
Error was being thrown in the `getRequestDisplayDetails` because it was looking for a chainId and receiving a network
=> fix bad merge from network -> chainId work

src/screens/SendConfirmationSheet.tsx, src/screens/SendSheet.js
Fixes APP-1844
`@ts-expect-error` silenced a ts error that `network` was not defined. replaced network w/ chainId, removed the ts-expect-error, and explicitly passed in the missing props as `undefined`
also added the following conditions to be met before attempting gas estimation:
* accountAddress is defined
* `amountDetails.assetAmount` is not an empty string (the default value)
* the `selected` asset to send is not an empty object ( the default value)
https://github.com/user-attachments/assets/4e09897b-4b85-43a6-a378-104c7d5412a6
=> ens send fix

src/redux/gas.ts
Fixes APP-1846
incorrect chainId was used to estimate gas, it was using the chainId from state which was mainnet, and then trying to set mainnet chainId to state even tho the tx was in a different chain
=> fix: use correct chainId for send

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
bump iOS and Android version to v1.9.38
=> bump iOS and Android version to v1.9.38

.github/workflows/macstadium-tests.yml
Fixes APP-####
My theory is that detox is leaving some process hanging whenever the tests fail so the runner is stuck trying to wait for that process to finish before completing the job as you can see [here](https://github.com/rainbow-me/rainbow/actions/runs/10745539430/job/29804928441?pr=6088)
None
Unfortunately we can test this again until there's a failure on e2e but the timeout should just kill the job whenever this happens
=> add 60 min timeout for e2e jobs

.github/workflows/macstadium-builds.yml
Fixes APP-####
- Adds a 75 minute timeout for the entire build job which is more than enough for a normal run.
- Prevents running the job if the PRs were already merged. We don't need test builds if we decided to merge the PR already.
None
I'll let @jinchung  admin merge this PR as soon as I we change it from draft to ready for review,  so we can confirm it works correctly.
=> Fix tophat triggers

package.json, scripts/rc-push.sh
Fixes APP-####
Added a script that automates the following tasks:
- Creating a github tag for the active rc branch
- Pushing the tag to github
- Force pushing the RC branch into master
- Notifying swarmia about the release.
Requires https://github.com/rainbow-me/rainbow-env/pull/71
No need to test it. Confirmed locally working on the last release.
=> Add rc-push script

src/navigation/config.tsx
Fixes APP-1852
fixes opacity on route source for mwp
recordings / screenshots
test that both mobile wallet protocol & wallet connect have a solid background on the SignTransaction sheet.
=> Fixes opacity on mwp sign txn sheet

.github/workflows/macstadium-tests.yml
Reverts rainbow-me/rainbow#6072
=> Revert "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"

src/keychain/index.ts, src/model/wallet.ts, src/screens/SignTransactionSheet.tsx, src/utils/ethereumUtils.ts
Fixes APP-1857
Fixes APP-1854
A few things were happening with MWP causing this issue:
- We were incorrectly handling the keychain errors so any cancellation would trigger the alert about phones swapping.
- Sometimes (?) we were looking up the pkey using a lowercase version while the original is stored checksummed resulting in "unavailable" error.  I am not sure why but I believe this was on Warpcast side sending different versions of the address, which is why reconnecting fixed the issue (they sent the right one there) but somewhere else they were breaking it.  We're now checksumming it so we don't care anymore.
- We were passing through a `chainId` parameter that was making the L1 fee estimation fail
https://github.com/user-attachments/assets/eab2408d-4304-4268-8850-4b9dd37fd1e6
- MWP …
=> Fix wrong messages during MWP Flow

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
bump to 1.9.39 and version code 231
=> version bump - 1.9.39

src/state/assets/userAssets.ts
Fixes APP-1866
After adding try & catch to all the `runOnJS` calls the error that was happening in release mode only surfaced
These two values can be undefined and cause a crash that happens only in release mode (due to being a side effect triggered by runOnJS
https://github.com/user-attachments/assets/f1031578-aba0-44a8-963b-468fb9d66cab
Swap search by selecting the input and typing anything
=> Fix swaps search crash 

src/react-native-cool-modals/ios/RNCMScreen.m
Fixes APP-1818
- Fixes the bug on iOS 18 causing context menu dismissals to wrongly trigger dismissals of cool-modals view controllers
https://github.com/user-attachments/assets/05eff6c8-e3a7-4868-9e9a-bf83a0739f74
=> Fix iOS 18 cool-modals context menu bug

src/__swaps__/screens/Swap/components/SearchInputButton.tsx
Fixes APP-1883
- Seems `hasClipboardData` isn't reliable or fully reactive to clipboard changes on Android — this doesn't solve that core issue, but should resolve the immediate problem as the button is now always pressable on Android
=> Swaps: fix disabled paste button on Android

src/__swaps__/screens/Swap/components/SearchInputButton.tsx, src/components/fields/CheckboxField.tsx, src/components/send/SendHeader.js, src/screens/SendConfirmationSheet.tsx, src/screens/SendSheet.js
Fixes APP-1879
A boundary check we added prevented the initial render to perform gas estimations on the network. Will put up a follow up PR that converts the SendSheet over to typescript so we can quit messing up sends.
https://github.com/user-attachments/assets/0a9803b1-4b6a-4dcd-9e41-3fa3af88f124
send flow e2e
=> Fix send sheet stuck on loading 

src/walletConnect/index.tsx
* As part of the network > chainId changes, there was a default moved from mainnet > arbitrum, so I'm just putting it back.
* Should not affect functionality as it is only for message signing which doesn't rely on a specific chain ID to work.
* Message signing via WalletConnect should still work as expected.
=> Update arbitrum default back to mainnet for WC message signing

src/resources/defi/types.ts, src/resources/defi/utils.ts
Fixes APP-####
uses BE `omit_from_total` tag to ignore adding certain positions value into the users total wallet balance
before/after
~note: Im looking into that first token in the list ($125.73) not being accounted~(it was BE wayne fixed it 🎉)
=> omit certain defi positions from users wallet balance

src/components/DappBrowser/BrowserTab.tsx, src/components/DappBrowser/handleProviderRequest.ts
- Changed navigation updates logic to allow SPA updates only for the current domain.
- Removed unused event handlers
- Moved appMessenger creation from onLoadStart to onLoadEnd
Check slack
Check slack
=> Dapp browser url updates fix

scripts/networks.js, src/chains/types.ts, src/chains/utils/backendNetworks.ts
Filters out backend driven networks meant to remain internal when not in development
=> Internal networks filtering

CHANGELOG.md, src/components/asset-list/RecyclerAssetList2/Claimable.tsx, src/components/asset-list/RecyclerAssetList2/ClaimablesListHeader.tsx, src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx, src/helpers/buildWalletSections.tsx, src/hooks/useWalletSectionsData.ts, src/resources/addys/claimables/query.ts, src/resources/addys/claimables/types.ts, src/resources/addys/claimables/utils.ts, src/resources/defi/PositionsQuery.ts, src/screens/WalletScreen/index.tsx
Fixes APP-####
* update Claimable types to support sponsored claims + add more attributes for use in Claim Panel (which does not exist yet in this branch)
* add response types for claim api (which is not yet used in this branch)
* modify wallet screen section builder such that it responds to changes in positions/claimables
* pass `navigate` callback into `Claimable` component for future use in button onPress
https://github.com/user-attachments/assets/904bb45c-72bb-4185-ade3-384affe9f4e3
i dont think testing is necessary but you could test:
* claimables appear properly on wallet screen
* app doesn't crash
=> Claimables [PR #1]: updates to query, types, utils, wallet screen rendering logic + wallet screen components

src/rapsV2/actions/claimTransactionClaimableAction.ts
The claimable modal, when doing tx claims, will now wait to display success until after the tx has been mined.
Proof of Work: https://www.loom.com/share/7ffbf88141274341974d0d5685f6a32c
I wouldn't worry about logging tx confirmation since the code is so simple. Just check out the diff and maybe do a test claim to further ensure that I did not break anything.
=> [APP-1909] Await Claimable TX Before Resolving Rap

.github/workflows/comments-watchdog.yml
Fixes APP-####
Action to monitor spammy comments and delete them automatically.
- It will monitor comments on PRs, issues and discussions and if spam detected based on a keyword list it would delete the comment (and saved in an artifact so we can review later)
- It won't affect org memebers.
None
Can be tested once it's merged
=> comments watchdog action

.github/workflows/macstadium-builds.yml, .github/workflows/macstadium-tests.yml
Fixes APP-####
Whenever pod repo update fails, it nevers remove the lock from git internally so I've added a line to remove that file (in case it still exists from a previously failed run) which should solve the issue
PoW is CI being all green
Nothing really
=> Fix CI: Pods git unlock

src/components/walletconnect-list/WalletConnectV2ListItem.tsx, src/walletConnect/index.tsx
Fixes APP-1712
Fixes a few issues that were longstanding with walletconnect v2 connections. I noticed that certain dapps send over a `requiredNamespace:{}` so we were never entering the logically loops to handle switching accounts properly. Separate from that, and after I fixed that, the list item never updated the address shown until closing the `ConnectedDappsSheet` and reopening it. I added some react `useState` to fix this. 
Also, I noticed that the `chainIds` were referencing the `requiredNamespace` in `WalletConnectV2ListItem` so we weren't showing those for v2 connections.
https://github.com/user-attachments/assets/2a4c6c1a-a5ea-4a9f-8338-97b664ac81ed
https://github.com/user-attachments/assets/2b015a9b-be28-43c7-b001-cbc54f482626
- walletconnect v2 and v1 pipeline
=> Fix WalletconnectV2 changeAccount issues

src/screens/WalletConnectApprovalSheet.js
Fixes APP-1714
At some point we moved to an external fetch to rely on malicious dapps, but we should respect fallback to wcv2 `isScam`. This should work on walletconnect AND rainbowkit now.
https://github.com/user-attachments/assets/a27b7c4e-5584-40fa-b6e7-ebc9601cf8b1
- Walletconnect and Rainbowkit valid / malicious dapps
=> Fix ApprovalSheet not using WCV2 `isScam` flag 

src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/analytics/event.ts, src/helpers/runWatchedWalletCohort.ts, src/hooks/useApplicationSetup.ts, src/hooks/useImportingWallet.ts, src/resources/favorites.ts, src/screens/AddWalletSheet.tsx, src/screens/ImportOrWatchWalletSheet.tsx, src/storage/index.ts, src/storage/schema.ts
Fixes APP-1672
Fixes APP-1807
Fixes APP-1849
- Fixes an analytic event missing for watching wallets button.
- Adds tracking to favorites
- Cleans up swaps event data
n/a
nothing really? but could test swaps to make sure nothing is broken there
=> Analytics changes

src/screens/points/content/PointsContent.tsx
Fixes APP-1906
Fixes weird `<Box />` behavior inheriting the width but not respecting it? Maybe a design system bug, but this fixes it.
https://github.com/user-attachments/assets/710e57c0-69b8-4dfc-8061-1ff2f7cc51a8
Points weekly recap panel on Android && iOS
=> Fix Points Breakdown Panel Not Prompting

src/components/expanded-state/asset/ChartExpandedState.js, src/graphql/queries/metadata.graphql, src/resources/assets/assets.ts, src/resources/assets/types.ts
Fixes APP-####
https://github.com/user-attachments/assets/e7df2774-53e6-4eac-97d7-fe8757fa24a5
=> hide send button when token is not transferable

src/screens/claimables/ClaimingClaimableSharedUI.tsx
Fixes APP-####
* debounce
* long -> short press (grant thought it was unclear that the button required long press, which led to button mashing)
=> Claim button fixes

.github/workflows/macstadium-tests.yml
Fixes APP-####
I think artifacts were being stored with the same name for all branches so having multiple builds running could cause pulling the wrong cache.
Using the branch name on the artifact name should prevent this while maintaining the benefits of cashing between runs.
None
CI should be green
=> store artifact per branch

src/analytics/event.ts, src/components/asset-list/RecyclerAssetList2/Claimable.tsx, src/screens/claimables/ClaimingSponsoredClaimable.tsx, src/screens/claimables/ClaimingTransactionClaimable.tsx
Fixes APP-1929
forgot to add claimables analytics
=> Claimables analytics

src/walletConnect/index.tsx
Fixes APP-####
Temporarily disabling one click auth flow for WC 
For context: https://rainbowhaus.slack.com/archives/C02SU6XKFD0/p1728689410030729
None
Nothing.
=> disable one click auth on WC

src/components/coin-icon/ChainBadge.js, src/components/gas/GasSpeedButton.tsx, src/languages/en_US.json, src/redux/gas.ts, src/screens/ExplainSheet.js, src/utils/ethereumUtils.ts
Missing price unit accessor led to apechain using mainnet prices since it defaulted to eth on mainnet
=> Fix apechain using mainnet gas prices

.github/workflows/macstadium-builds.yml
Fixes APP-####
Tophat job is failing because of a bug in fastlane.  See https://github.com/fastlane/fastlane/issues/21460#issuecomment-2428565479
This PR forces fastlane to update to the latest version before running
None
The tophat build job should be green.
=> force fastlane update

src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/navigation/Navigation.js
Fixes APP-####
edge case if the users previous screen was an Expanded Sheet, navigate to the Wallet Screen instead of back to the Expanded Sheet
pow
https://github.com/user-attachments/assets/4446ab8d-ab87-4814-a0cf-7970f76f6a23
=> completing a swap navigates back to previous screen

src/notifications/settings/firebase.ts, src/notifications/settings/types.ts
Fixes APP-985
Backend changes have fixed APP-985; this PR itself is a no-op, it only reduces the payload we send to the backend for notifications subscription.
Previously, we would send a notification subscription for each wallet on each chain. Now, the backend will handle managing the supported chains, so we only need to send a subscription for each wallet.
TODO: will update once build completes
Confirm that subscribing and unsubscribing to notifications still behaves as expected (there should be no change.)
=> Remove chain ID from notifs payload as it is no longer needed

src/resources/transactions/transaction.ts
Fixes APP-1947
seems this has been there for a while. when a user taps on a notification, we grab the txn hash and fetch via the addys txn endpoint. if a txn is not found by this endpoint, then the `transaction` param in the response is `null`. Unfortunately we have a check here from a long time ago that would default `tx` to `{}` but then immediately after, check `if(!tx)`: https://github.com/rainbow-me/rainbow/blob/develop/src/resources/transactions/transaction.ts#L48 which means the transaction would continue and get parsed and have a default `type` of `contract_interaction` and have a missing `status` and therefore result in lang trying to access: `{i18n.t(i18n.l.transactions.type[transaction?.title])}` - where `transaction?.title` is `contract_interaction.`
TODO
Do a transaction, …
=> Remove empty object fallback when txn not found from addys endpoint

src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx, src/__swaps__/screens/Swap/components/TokenList/TokenToSellList.tsx
Fixes APP-####
should we add some animation/separator/fade/idk to the list clipping behind this header?
https://github.com/user-attachments/assets/bca523e0-4933-48c7-901e-63190eb44f8e
=> swap: make ChainSelector row fixed to top of list

src/components/AnimatedComponents/extendedPropsAllowlists.ts, src/react-native-animated-charts/src/index.ts
Fixes APP-1916
whitelisting text as native prop was causing a few runtime crashes that are hard to reproduce but there's a bunch of reports on sentry.  After chatting with @christianbaroni  he suggested we disable it.
https://sentry.io/organizations/rainbow-me/issues/5961374042/events/b5e18c03728340b9aa2e32b8887e4421/
No
make sure it doesn't break the animated inputs that use it, eg dapp browser input / expanded state chart % change label when pressing the chart
=> Fix reanimated crash

yarn.lock
Reverts rainbow-me/rainbow#6221
There's a dep resolution issue going on that's crashing the app in testflight
=> Revert "Bump secp256k1 from 4.0.3 to 4.0.4"

src/components/sheet/sheet-action-buttons/SendActionButton.js, src/navigation/Routes.ios.tsx
Fixes APP-1974
Fixes the missing asset param in send sheet flow from expanded state
=> fix initial asset missing on expanded state navigation

.github/workflows/macstadium-tests.yml
Fixes APP-####
Seems like this is taking longer now and we need more runtime.
e2e should pass just fine
=> Bump e2e job timeout

src/resources/defi/PositionsQuery.ts
Fixes APP-####
when removing moxie locked positions from the total wallet balance I introduced a new `positions.totals.totalLocked` that the `useWalletBalances` subtract from the total, when the user has old persisted data this prop does not exist while it's refetching/reparsing the positions, making it try to subtract undefined and returning NaN
instead of bumping the persister version (which may cause the user to have the wrong balance, without any positions value, for a couple seconds while it refetches it for the first time after this change is released)
we could do like `positions.totals.totalLocked || '0'` defensive style but I ~think~ in this case I like to have and keep the type contract, not a strong opinion tho
=> bump positions query persister version

src/parsers/transactions.ts, src/screens/transaction-details/components/TransactionDetailsValueAndFeeSection.tsx
Fixes APP-1982
We now look for native asset on the chain to determine symbol and decimals and fallback to eth mainnet whenever necessary.
test all chains to make sure chain native asset symbol and amount is correct
=> Fix native asset symbol always being `ETH` in transaction details

src/__swaps__/screens/Swap/resources/assets/index.ts, src/__swaps__/screens/Swap/resources/assets/userAssets.ts, src/__swaps__/screens/Swap/resources/assets/userAssetsByChain.ts, src/state/assets/userAssets.ts, src/state/sync/UserAssetsSync.tsx
Fixes APP-1977
There is a race condition that can happen when we first start the app and do a user assets query function call without the address. We weren't disabling the query function call, resulting in us to just return an empty state and therefore empty objects. There could be a race condition from when we set the incorrect data but before we get the latest data with the account address, when a user could open the swap state, preventing further updates from the user assets store from getting synced.
There were a few different issues happening at the same time, but the retry errors we were getting were not causing this - they were other issues.
This will also be improved once we have Ben's user assets consolidation work in place - we should just make sure to keep some of the changes …
=> Fix userAssets query enabled config

src/resources/metadata/backendNetworks.ts
Fixes APP-1986
As part of the inclusion of `notifications` enabled flags from the backend networks, I had missed the persist config version bump. Unclear how this got passed initial testing when we were going back and forth from prod builds to TF builds repeatedly - may have been that we didn't delete the app but just reinstalled.
Screenshot after deleting app, installing prod version, then without deleting, downloading TF 1.9.45 (38)
Delete app, install latest prod, then without deleting the app, install the latest TF with this commit. Should not have any issues.
=> Bump persist version on backend networks support for notifs

src/__swaps__/screens/Swap/Swap.tsx, src/components/DappBrowser/control-panel/ControlPanel.tsx, src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx, src/components/context-menu-buttons/ChainContextMenu.tsx, src/state/assets/userAssets.ts, src/state/sync/UserAssetsSync.tsx
Noticed that Apecoin wasn't being set as the inputAsset when the preferred network was set to apechain. This should fix it. Also renamed the function to be more specific, not just ETH but native token on that chain.
https://github.com/user-attachments/assets/2024a70a-be61-4a51-9109-f28a6a14a9c3
nothing really needs testing tbh
=> fix native assets outside of eth not working with preferred network

src/components/change-wallet/AddressRow.tsx, src/hooks/useWalletBalances.ts
Fixes missing balance in the change wallet sheet. Was missed in the hidden balance asset fixes that were just merged in.
n/a
=> Fixes change wallet sheet missing balance

bitrise.yml, globals.d.ts, src/model/remoteConfig.ts
Fixes APP-1994
Cleaned up a bunch of unused env configs.
Many of the RPC configs are now handled by the backend networks endpoint instead.
Corresponds with PR: https://github.com/rainbow-me/rainbow-env/pull/72
* Wallet data behaves as expected on ios and android
* Add cash flow behaves as expected on ios and android
=> Remove unused env configs

src/raps/execute.ts
* Simplifies node ack check to being before any rap action past the first one needs it (means we no longer need to check if there is more than 1 action after the first action; it also means we don't unnecessarily do this check after the last action)
* Simplifies the node ack check to only be for non-mainnet transactions
* Caps the number of retries for node ack to 10
=> Skip node ack check if txn params are for mainnet

src/handlers/swap.ts, src/raps/actions/swap.ts, src/raps/execute.ts, src/raps/unlockAndSwap.ts, src/raps/utils.ts
Fixes APP-2023
Fixes APP-2017
Two separate issues:
- Supporting permit in a few tokens was conflicting with gas estimation causing different issues, resulting in incorrect gas estimations and onchain failures running out of gas (see ticket 2017)
- We have a check that waits for node ack before continuing on to the next rap action; any failure to find the tx (ex. private mempool) would make the rap fail and subsequent actions would never execute (see ticket 2023). Historical context for this node ack in general: https://github.com/rainbow-me/browser-extension/pull/740
Changes:
- Disable permit support for now as there are pros and cons to this; we can revisit this separately
- Simplifies node ack check to being before any rap action past the first one needs it (means we no longer need to …
=> Fix approval + swaps

src/__swaps__/screens/Swap/hooks/useSwapEstimatedGasLimit.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/handlers/swap.ts, src/handlers/web3.ts, src/raps/actions/crosschainSwap.ts, src/raps/actions/swap.ts, src/raps/unlockAndCrosschainSwap.ts, src/raps/unlockAndSwap.ts, src/raps/utils.ts, src/screens/SpeedUpAndCancelSheet.tsx, src/state/nonces/index.ts
Fixes APP-2036
Fixes APP-2037
- The swap and crosschain swap actions do one final gas estimation before submitting the transaction. The function they were using was not taking into account the metadata endpoint which has more accurate gas predictions. Moved them both over to use this function instead.
- The fallback logic of trying different gas limits for estimating gas was failing because trace call complains about formatting of block tag or block number
- The `getNonceAndPerformSwap` function was not actually getting the nonce, causing the provider to default to its own calculated nonce, which was causing issues once we removed the "wait for node ack"
=> Update handling of flashbots flow

src/handlers/tokenSearch.ts
Fixes APP-1674
- Incorrectly named variable "params" was replaced with correctly named variable "queryParams", which fixed mainnet address searches throwing an error.
- tokenSearch function logic was changed to more closely match search logic in `src/__swaps__/screens/Swap/resources/search/search.ts` which fixed cross-chain address search. 
- Search for an exact address on the discover screen (ex "0x6982508145454Ce325dDbE47a25d4ec3d2311933")
- Search normally
=> fix token address searches on discover screen

src/App.tsx, src/analytics/__mocks__/index.ts, src/analytics/__tests__/index.test.ts, src/analytics/__tests__/utils.test.ts, src/analytics/index.ts, src/analytics/utils.ts, src/hooks/useInitializeWallet.ts, src/redux/__mocks__/store.ts
Fixes APP-1956
- added `walletType` param to `identify` and Sentry user
- setting up Sentry and Rudderstack identify in `useInitializeWallet` to absorb wallet switches
- added `getWalletContext` util to prepare hashes and wallet types consistently throughout the codebase
- added `walletContext` overrides in `track` and `screen` to support scenarios where the actioned wallet is different than the global selected wallet
- confirmed proper hash switching on Rudderstack's side ✅ 
- `walletType` appears to be undefined directly after import because of the following snippet; alternative approach may be necessary 
```
const { wallets } = store.getState();
const wallet = findWalletWithAccount(wallets.wallets || {}, address);
```
=> fix: wallet telemetry identify

src/analytics/userProperties.ts, src/screens/WalletScreen/index.tsx
Fixes APP-1998
We now identify wallet types during wallet screen initialization. Similar to the BX: https://github.com/rainbow-me/browser-extension/blob/df46dc44e45f8466c2960eb35b8d19bf9d9edb90/src/analytics/identify/walletTypes.ts#L59
n/a
Verify new data being sent satisfies the ticket's requirements.
=> Update the mobile app's id'ing of number of wallets to match the BX

src/components/cards/CarouselCard.tsx
Fixes APP-1906
There's a flashlist bug that prevents touch events for horizontal containers with only a single item. https://github.com/Shopify/flash-list/issues/1327
https://github.com/user-attachments/assets/2b3b119d-ae81-4baa-8dff-c193ae72d28c
=> Fix card carousel horizontal with single item

src/hooks/useWalletsWithBalancesAndNames.ts
Fixes APP-1971
Guards the currency conversion until totalBalance is calculated
https://github.com/user-attachments/assets/54570654-d7e6-4d9e-bbd3-88792ba697b7
one way to trigger this is by adding a new wallet
should show the loading skeleton until the balance is loaded
=> Fixes `$NaN` wallet balance

src/components/positions/PositionsCard.tsx, src/helpers/buildWalletSections.tsx, src/hooks/useWalletBalances.ts, src/languages/en_US.json, src/navigation/types.ts, src/resources/defi/PositionsQuery.ts, src/resources/defi/types.ts, src/resources/defi/utils.ts, src/screens/positions/LpPositionListItem.tsx, src/screens/positions/LpRangeBadge.tsx, src/screens/positions/PositionSheet.tsx, src/screens/positions/SubPositionListItem.tsx
Fixes APP-2047
What changed
- Refactored [defi/utils.ts](https://github.com/rainbow-me/rainbow/blob/65b94cd885c2082e6f5d146d9bc28884bac924e8/src/resources/defi/utils.ts) to support parsing staked tokens and LP positions
- `LpPositionListItem` component for displaying LP positions
- All dapp positions are grouped across versions, with a version badge on the PositionSheet delineating the version
Context
- Currently marking an LP position with `isConcentratedLiquidity: true` is hard coded to check against an array of dapps that *only* support concentrated liquidity, such as uniswap-v3. This array should be updated with other protocols. Ideally some checking is done on the backend based on the pool info to determine if it's a concentrated liquidity pool or not.
- For out of position LP …
=> Add support in positions for LP positions & staked deposits

src/components/DappBrowser/BrowserTab.tsx
Fixes APP-
Exposed a new method `setActive` on the webview
Requires https://github.com/rainbow-me/rainbow-scripts/pull/186
Available on rainbow-scripts related PR
Instructions available on rainbow-scripts related PR
(e2e is expected to fail until the other PR gets merged in)
=> Implement Active Tab flag for dapp browser

src/hooks/useCoinListEditOptions.ts
- The empty default object was being recreated every time this hook re-rendered, which then triggered additional updates due to `pinnedCoinsObj` changing
=> Fix useMMKVObject initial value

src/__swaps__/screens/Swap/components/SwapBottomPanel.tsx, src/__swaps__/screens/Swap/hooks/useSwapNavigation.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-1928
We have added the ledger bluetooth sheet back to the swap flow. Ledger transactions were working, however we were not displaying the various bluetooth connection states.
https://github.com/user-attachments/assets/c5441890-464f-4208-ae69-b16cd3832cb6
Attempt a swap with a ledger device. Make sure you see the bluetooth connection sheet.
=> fix: present hw pairing sheet during swap

.github/workflows/macstadium-builds.yml, ios/fastlane/Fastfile
Fixes APP-####
This should fix all the failures we see every month on the build job
None
The build step should be green
=> use appstore connect key for CI

src/components/change-wallet/WalletList.tsx, src/design-system/components/DebugLayout/DebugLayout.tsx, src/screens/ChangeWalletSheet.tsx
Fixes APP-2039
There was a race condition happening in the flatlist that would calculate the list height before the entire list was rendered, this was preventing the user from scrolling on the wallet list.
https://github.com/user-attachments/assets/42cde1ef-74ae-4aad-a669-fd5f88c29af2
Android – I loaded but didn't thoroughly test it.
OG thread: https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1732045158373479
=> Fix broken `scrollEnabled` check in ChangeWalletSheet

src/__swaps__/screens/Swap/hooks/analyticsTrackQuoteFailed.ts, src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/analytics/event.ts, src/components/error-boundary/ErrorBoundary.tsx, src/components/expanded-state/UniqueTokenExpandedState.tsx, src/components/expanded-state/asset/ChartExpandedState.js, src/hooks/useTimeout.ts
Fixes APP-2068, APP-2066, APP-2064
- viewing token details, erc20s and nfts
- added a timeout to send the event 5s after the component is mounted
- as a buffer to wait for all different sources to load, like chart, price, description etc
- if the user closes the sheet before 5s it sends the event with the state it had at the time
- quote failed, sends `error_code`, `reason`, `inputAsset`, `outputAsset`, `inputAmount`, `outputAmount`
- Crash/something went wrong screen sends an event on error and on reset
=> adds a couple more analytics events

src/resources/defi/PositionsQuery.ts
Fixes APP-####
- revert change that enabled third party positions on PositionsQuery
=> revert third party positions enabled

src/model/backup.ts, src/screens/SettingsSheet/components/SettingsSection.tsx, src/screens/SettingsSheet/useVisibleWallets.ts
Fixes APP-2116
We weren't filtering out the wallets based on the `visible` criteria before sorting them and showing them.
n/a
=> [<< 1297] - Fix non-visible wallets from showing on backups breakdown

src/screens/positions/LpPositionListItem.tsx, src/screens/positions/LpRangeBadge.tsx
Fixes APP-####
Small UI bug fixes
- Prevent linear gradient overflow on LP badge asset items
- Fix bad key creation on LP badge items
- Fix android shadow offset on LP range status badge and LP badge
=> fix lp badge gradient overflow and android shadows

src/resources/defi/PositionsQuery.ts, src/resources/defi/utils.ts, src/screens/positions/LpPositionListItem.tsx
Fixes APP-####
- re-enables third party positions
- removes staked deposits from token list exclusion
- only adds deposit to exclusion list if asset.defi_position is true
- fix NaN% for LP pools where total assets value is 0. 
Before
After
- if you have defi positions in your wallet, ensure if you have a token deposited in one of those positions and also have that token in your wallet that it is not missing in the main token list. If you don't a wallet with defi positions, grunt.eth is a good one.
- Check any pool positions such as Uniswap for incorrect asset allocation percentages. grunt.eth has a uniswap position that originally surfaced the bug related to both assets in the pool being worth 0.
=> Enable third party defi positions & fix token list exclusion logic

src/resources/defi/PositionsQuery.ts
Fixes APP-####
- one line, bumps persist version for positions query. Otherwise, app will crash when serving stale query that does not have new parser that guarantees non-null array fields.
=> fix: bump positions query cache persist version

src/components/asset-list/RecyclerAssetList2/index.tsx, src/components/asset-list/RecyclerAssetList2/profile-header/ProfileNameRow.tsx, src/components/navbar/Navbar.tsx, src/components/navbar/NavbarTextIcon.tsx
Fixes APP-2134
A change in [PR #5496](https://github.com/rainbow-me/rainbow/pull/5496) made the wallet name button in the WalletScreen navbar non-interactive. While attempting to ensure the QR and settings buttons remained pressable by adding a negative zIndex to the wallet name component, the wallet name button was inadvertently placed behind the navbar, making it inaccessible.
* Removed the negative zIndex from the wallet name component
* Adjusted its incorrectly calculated maxWidth constraint to prevent the wallet name from overlapping with QR and settings buttons
https://github.com/user-attachments/assets/a39b9793-299f-46ab-aa8a-3b2408787053
* long wallet names are properly displayed/truncated
* long wallet names do not interfere with other navbar buttons
* pressing wallet name on …
=> chore: fix WalletScreen navbar onPress while scrolled

src/components/change-wallet/WalletList.tsx, src/screens/AddWalletSheet.tsx, src/screens/ChangeWalletSheet.tsx
Noticed that we were shy on wallet height calculation on a list with one or two wallets.
Test that the wallet sheet doesn't have weird height on any number of wallets
=> Fix missing header height from wallet list height calculation

src/state/nonces/index.ts, src/state/pendingTransactions/index.ts
This change sets the default "currentNonce" to -1 to distinguish between an actual current nonce of 0 vs an unknown current nonce (e.g, for a fresh wallet we just created that has no outgoing txns, or a freshly imported wallet that we hadn't previously tracked.) 
This helps us treat nonces vs txn counts accurately.
=> Update default currentNonce value to -1 (use case: fresh wallet or freshly imported wallet)

src/screens/points/content/PointsContent.tsx
Noticed that this was causing a crash in develop (not in prod). The reason being on initial render it was rendering an empty string and for whatever reason it was passing `size: undefined` through to the Text component.
n/a
n/a
=> Fix TextShadow crash

package.json, src/raps/actions/swap.ts, yarn.lock
This removes the dependency on hardcoded addresses for wrapped native assets
=> chore: update swaps sdk + use new getWrappedAssetAddress method

src/hooks/useFarcasterAccountForWallets.ts, src/hooks/useWalletBalances.ts, src/hooks/useWalletsHiddenBalances.ts, src/resources/summary/summary.ts
This hook retrieves the farcaster id for the first found non-watched wallet for personalization
will write some unit tests for this momentarily
=> Retrieve FID for wallet addresses

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
bump iOS and Android to v1.9.50
=> bump iOS and Android to v1.9.50

src/components/sheet/sheet-action-buttons/SwapActionButton.tsx
We were relying on build time networks in a spot where I'm fairly certain we will always have a chain id value. I left the original value as a fallback to hopefully ensure this causes no widespread change other than that we aren't using an `undefined` chain id value for networks we are unfamiliar with at build time.
https://www.loom.com/share/e89efd56894245388718959facf44b1f
Try to navigate to swaps from asset expanded state after clicking on a trending token row.
=> [APP-2194] Navigation to swaps isn't working after opening expanded state

src/components/Discover/TrendingTokens.tsx, src/helpers/strings.ts
Fixes APP-2203
Reusing the swaps native amount formatter for when we are formatting a non-fractal amount.
token formats should either be:
1. decimal fraction with zero subscript
2. decimal fraction without zero subscript (max 3 zeros)
3. Whole number > 1
=> Fix non fractal price data formatter

src/components/Discover/TrendingTokens.tsx
Fixes APP-2209
Fixes spacing in areas of trending tokens and cleans up a few things in the process
n/a
=> Fix spacing to 28px in latest TestFlight version

src/components/NetworkSwitcher.tsx, src/state/networkSwitcher/networkSwitcher.ts
Fixes APP-2207
Added default initialPinned that gets set if we either:
1. can't parse most used from nonces
2. if the user sets the pinned to no chains (aka, this shouldn't be allowed)
see if you can get into a state where the network switcher opens with no initial pinned networks.
=> Fixes initialPinned being empty in certain cases

src/components/Discover/TrendingTokens.tsx, src/languages/en_US.json, src/state/trendingTokens/trendingTokens.ts
Fixes APP-2222
Default option to 3 day timeframe. order chronologically in the list.
el
n/a
=> Fix time filters and default to D3

src/components/NetworkSwitcher.tsx
Fixes APP-2199
We were using an old util that requires us to add entries to foregroundColors that is no longer supported. Changed it to pull directly from the theme instead.
@christianbaroni noticed that our Arbitrum color doesn't correspond to what's in the Figma. Didn't want to change the hex without consulting you first.
Here's the FIgma:
Here's our current hex: `#2D374B` 
https://github.com/user-attachments/assets/c330991f-e36d-425d-bacd-6fe0a99cf248
https://github.com/user-attachments/assets/f65e2b0e-30e4-4948-a3dc-e268e6786626
=> Fix network colors in NetworkSelector

src/helpers/strings.ts
Fixes APP-2203
Previously we were only checking for numbers with no fractal value, but we should actually use our native formatter whenever the whole number is > 0. 
https://github.com/user-attachments/assets/a9fcb08d-aa69-423f-8ba5-9aa7734b838b
test each network and see if you can get a funky number
=> Change logic on when we should use native formatter for trending tokens

src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/__swaps__/screens/Swap/resources/search/discovery.ts, src/__swaps__/screens/Swap/resources/search/search.ts
Fixes APP-2142
* Update the swap search endpoint from v2 to v3 which is more efficient and update corresponding handling of data to make it match prod / BX (we can later consolidate our separate calls to the v3 endpoint for verified vs not, but will be part of a follow up PR)
* Update the popular in Rainbow search endpoint (it's the same data, just backend renamed it to a more accurate name)
https://github.com/user-attachments/assets/f421ee6b-35a0-4807-9c08-81a9da98ba58
Testflight: v1.9.49 (30)
* Searching behaves similar to prod / BX across networks
=> Update swaps search endpoint from v2 to v3

src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/__swaps__/screens/Swap/resources/search/discovery.ts, src/__swaps__/screens/Swap/resources/search/search.ts
Fixes APP-2163
* We DO want to persist the initial result list (per network)
* We don't want to persist the results of search when you type something
* After loading the default lists for a network, killing the app and coming back to search should still show default lists
https://github.com/user-attachments/assets/8bdb5dc2-095a-4d5f-bab2-edc9bb1aed37
* After typing in a search query, closing swap (not killing the app) and searching for the same query should be quick
https://github.com/user-attachments/assets/b308505f-5486-4639-8faf-0d55ea6d4c8c
* Testing situations below can happen after installing the TF after having prod version installed (no need to delete the app in between)
* After loading the default lists for a network, killing the app and coming back to search should still show …
=> Support only persisting when search query is undefined (the default lists)

src/hooks/useWalletBalances.ts, src/resources/summary/summary.ts
Fixes APP-1808
- Change total balance calculation to use positions value returned from summary endpoint rather than fetching each accounts positions individually and calculating the total from that.
- That your total account balance is correct
=> Migrate from addys positions -> summary endpoint for total wallet balance

src/components/Discover/TrendingTokens.tsx
Fixes APP-####
Fixes missing `and other(s)` copy from showing
=> fix and others i18n

src/handlers/walletReadyEvents.ts, src/hooks/useImportingWallet.ts
Fixes APP-2223
Just removed an entry point into the backup prompt since it runs on wallet ready now, this one is redundant and unnecessary
// wip
you should no longer be asked for backup on import/creation if backed up
=> Prevent backup prompt from firing on import

src/components/Discover/TrendingTokens.tsx, src/components/NetworkSwitcher.tsx, src/languages/en_US.json
- Cleans up the trending tokens and network switcher UIs
- Fixes an Android text wrapping bug caused by `alignItems: 'baseline'` in trending tokens coin rows
- Simplifies the trending tokens loading skeleton
- Fixes an issue causing the last selected network to be forgotten in the network switcher
- Fixes x/y positioning of dragged networks in the network switcher
- Improves network switcher animations and corrects sheet sizing
- Adds haptics to the network switcher
- Minor code cleanup
=> Trending tokens / network switcher cleanup

CHANGELOG.md, android/app/build.gradle, ios/Rainbow.xcodeproj/project.pbxproj, package.json
1.9.51 >> 1.9.52
244 >> 246 (had to resubmit so skipping a version)
- Retrieve FID for wallet addresses (#6330)
- Network Expansion (#6334)
- Track token lists (#6303)
- Add default option to dropdown menu for sort (#6359)
- User assets migration (#6038)
- Trending tokens polishes (#6331)
- Convert `networkColors` to backendNetworks (#6353)
- Trending tokens / network switcher cleanup (#6372)
- Backups V2 Follow-up Fixes / Improvements (#6213)
- Change logic around when to parse into our native formatter (#6360)
- Support only persisting when search query is undefined (#6358)
- Use positions value from summary for wallet balance (#6358)
- Remove zustand selectors that return objects (#6355)
- Add trending tokens flag to remote config.ts (#6373)
- Fix and others i18n (#6367)
- Trending …
=> version bump to 1.9.52 / versionCode 246 + changelog

src/handlers/walletReadyEvents.ts, src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
Fixes APP-2240
Prevents the backup prompt from firing for imported wallets
backup prompt annoyances
=> add imported check on backup prompt

src/components/Discover/TrendingTokens.tsx, src/resources/trendingTokens/trendingTokens.ts
the actually pass the unique id now
n/a
=> [APP-2235] Verify functionality of isSwappingToTrendingAsset flag

src/featuresToUnlock/unlockableAppIconCheck.ts, src/handlers/walletReadyEvents.ts
Fixes APP-2241
- Prioritizes showing backup sheet on app startup over nft icon unlocks
- Wraps nft icon unlock sheet navigation in `triggerOnSwipeLayout`, removing previous setTimeout hack.
=> Fix nft icon sheet present & prioritize backup sheet 

src/state/assets/userAssets.ts
- `isLoadingUserAssets` was being reset to `true` during app launch, and not set to `false` until user assets data was next fetched and set via RQ, resulting in the swap submit button often getting stuck in a 'Fetching' state after a fresh app launch (until the next user assets fetch)
- This is where it's causing the swap submit button issue: https://github.com/rainbow-me/rainbow/blob/3bb8e9af8c124215641750f0e4e12dffc5da2a39/src/__swaps__/screens/Swap/providers/SyncSwapStateAndSharedValues.tsx#L192
=> Fix swap submit button getting stuck on 'Fetching'

src/appIcons/appIcons.ts
Fixes APP-2242
- adopted new adworld token contract after previous contract was deprecated
=> fix: icon unlock for new adworld nft contract

src/screens/SignTransactionSheet.tsx, src/utils/ethereumUtils.ts
Fixes APP-2247
Strips non standard params `extParams` causing transactions to fail on virtuals.io
virtuals.io transactions
=> Fix virtuals.io transactions in app browser

package.json, src/handlers/cloudBackup.ts, src/state/backups/backups.ts, yarn.lock
Fixes APP-2239
If the user had pending OAuth permissions, our backups sync would spam them due to the nature of how we retry on failures. We now prevent the prompt if they don't have permissions enabled, and if it does prompt we detect the cancellation and only prompt once instead of falling through the `try...catch` block.
will try to capture one soon
https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1735921689825149?thread_ts=1735501963.465679&cid=C02C2FVC6N6
=> Prevent Google OAuth prompt on app launch

android/app/src/main/AndroidManifest.xml
Fixes APP-2204
There was a typo on the activity name, which was preventing the icon to be selected on Android.
https://github.com/user-attachments/assets/e440f092-8a5e-471f-b11d-638f01f1e57c
Select the redacted icon on android
=> Fix redacted icon on Android

src/components/DappBrowser/Homepage.tsx, src/components/DappBrowser/search/results/SearchResults.tsx, src/resources/metadata/dapps.tsx
- Migrates the browser dapps query to `createQueryStore`
- Removes the need to pull the full `dapps` object into each homepage `Card` component
=> Migrate dapps query to createQueryStore

src/components/Discover/TrendingTokens.tsx
Fixes APP-2227
Fixes long token symbols causing overflows. We now calculate width of name, symbol, and price so that they never overlap.
https://github.com/user-attachments/assets/938dedc0-87a9-48da-97c8-03c14821f262
=> Fix long token symbol overflow

src/components/backup/BackupSheet.tsx, src/components/backup/CloudBackupPrompt.tsx, src/components/backup/ManualBackupPrompt.tsx, src/components/backup/useCreateBackup.ts, src/handlers/walletReadyEvents.ts, src/helpers/walletBackupStepTypes.ts, src/hooks/useImportingWallet.ts, src/hooks/useInitializeWallet.ts, src/navigation/Routes.android.tsx, src/navigation/config.tsx, src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx, src/state/backups/backups.ts
Fixes APP-2237
- Added `CloudBackupPrompt` component for cloud backup flows
- Added `ManualBackupPrompt` component for manual backup flows
- Improved separation of concerns between backup types
- Renamed and consolidated backup step types
- Removed redundant step types
- Added new step types for different prompt scenarios:
- `backup_prompt_manual`
- `backup_prompt_cloud`
- `create_cloud_backup`
- Added tracking for backup prompt frequency
- Implemented `timesPromptedForBackup` counter
- Added `lastBackupPromptAt` timestamp tracking
- Added persistence for backup prompt state
- Added weekly prompt schedule
- Implemented progressive delay between prompts
- Added proper cleanup on component unmount
- Added automatic cloud backup prompt after wallet import
- Added conditions to skip prompt …
=> Implement new logic for backup prompt

src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-2254
- Added `showWalletErrorAlert` helper function import
- Implemented wallet error alert when wallet is not available during swap
- Maintained existing error feedback (haptic notification)
- Added error handling in swap provider's wallet check
- Integrated with existing haptics feedback system
- Improved user feedback for wallet-related errors
- Utilized centralized `showWalletErrorAlert` from support helpers
- Standardized wallet error messaging across the app
- Improved error handling consistency
- Added clear error messaging for wallet-related issues
- Maintained haptic feedback for error states
- Improved user guidance during error scenarios
- Added new import for support helper
- Maintained existing haptics implementation
- Integrated with existing swap provider logic …
=> Add wallet error alert to swaps flow

src/components/Transactions/TransactionSimulationCard.tsx, src/screens/SignTransactionSheet.tsx
Fixes APP-2256
- Removed `walletBalance` prop interface with multiple fields
- Replaced with `nativeAsset` prop using `ParsedAddressAsset` type
- Updated component to use new prop structure throughout
- Modified native asset retrieval logic in `SignTransactionSheet`
- Added fallback to `getChainsNativeAsset` when network native asset is unavailable
- Improved type safety with proper null checks and fallbacks
- Added conditional check for object type and 'balance' property
- Implemented better fallback values for balance display
- Maintained backward compatibility with existing symbol display
- Reordered useMemo dependencies for better performance
- Removed redundant dependencies from dependency arrays
- Simplified string template usage for balance display
- Updated error message handling …
=> Fix wrong native asset being displayed on SignTransactionSheet

src/react-query/queryClient.ts
- Turns out `cacheTime` is the time after which inactive query data is garbage collected, not the time that data is stored for
- This sets the default `cacheTime` back to 5 minutes, which is RQ's default
=> Adjust default queryClient cacheTime

src/resources/transactions/transaction.ts, src/state/nonces/index.ts
Fixes APP-2265
* Treat an addy's txn API response object that doesn't have a valid status as not existing yet, so that we don't override the pending transaction with incomplete data and remove it prematurely from the pending txns list. We had been treating txn status of `""` as the same as "not pending" and removed the pending transaction before its time. This impacted the getNextNonce logic when it tries to go through pending transactions and check timestamps against the privateMempool time.
* Bumped the nonce persist version for users who may have been negatively impacted by the previous logic
* Removed the nonce migration function as nonce isn't a user preference that needs to be stored; it can always be refreshed
You can see it healed here: …
=> Fix nonce issue for dropped transactions

src/resources/summary/summary.ts
Fixes APP-2273
Add field to address summary request that lets endpoint know to add third party positions to address total balance
=> enable third party positions to be calculated in address summary

src/components/Discover/TrendingTokens.tsx
fixes misaligned tt chain badge
make sure chain image looks fine on tt
=> fix chain image in tt

src/components/DropdownMenu.tsx
Don't wrap `DropdownMenu` component children in `ButtonPressAnimation` if the menu condition is long-press. Fixes issue this causes where on Android any further `ButtonPressAnimation`s are ignored. 
Can you switch wallets
=> Fix Android wallet switch buttons not working

src/__swaps__/screens/Swap/navigateToSwaps.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-2255
- Added slippage parameter handling in `getSwapsNavigationParams`
- Improved default value handling for input/output assets
- Added chainId fallback to mainnet
- Added validation for slippage parameter
- Implemented conversion from basis points to string format
- Added integration with remote config for default slippage values
- Moved state retrieval to top of function
- Consolidated asset parameter handling
- Added proper type safety for parameters
- Removed direct worklet call for default slippage
- Now uses navigation parameters for initial slippage value
- Maintained existing haptics and analytics integration
- Removed unused imports
- Simplified parameter initialization
- Improved type definitions
This PR improves the swap navigation parameter handling by adding proper …
=> Fix inconsistencies between swaps store slippage and shared value

src/components/floating-emojis/FloatingEmoji.tsx, src/components/floating-emojis/FloatingEmojis.tsx, src/components/floating-emojis/GravityEmoji.tsx, src/components/sheet/sheet-action-buttons/SheetActionButton.tsx, src/components/text/Emoji.tsx, src/components/text/types.ts
Fixes APP-2277
- Properly typed the `Emoji` component, removed the string casting of the number prop `size`
=> Fix emoji size type causing crash for Android

src/components/DappBrowser/handleProviderRequest.ts, src/components/Transactions/TransactionMessageCard.tsx, src/helpers/buildTransaction.ts, src/screens/SignTransactionSheet.tsx, src/walletConnect/types.ts
Fixes APP-2248
- Removed dependency on `RPCMethod` from walletConnect types
- Changed `method` prop type from `RPCMethod` to `string` for better flexibility
- Added new file `src/helpers/buildTransaction.ts`
- Implements two main functions:
- `getGasLimitForSuggestedGas`
- `buildTransaction`
- Moved gas estimation logic from `SignTransactionSheet` to dedicated helper
- Implements padding and validation for gas estimates
- Handles fallback scenarios for gas limit calculations
- Centralizes transaction building logic in one location
- Handles gas parameters, nonce management, and transaction type conversion
- Provides a cleaner interface for creating transaction objects
- Removed duplicated gas estimation logic
- Simplified transaction payload handling
- Improved error handling and logging …
=> Make transaction request parameters less rigid

src/handlers/walletReadyEvents.ts
If the user isn't signed into a google account yet the status will be NotAvailable, so we need to remove this clause and just fall through to the prompt always.
=> Fix Android prompt

e2e/helpers.ts, e2e/parallel/4_discoverSheetFlow.spec.ts, src/components/Discover/DiscoverSearch.tsx
There are a few fixes that come along in this PR.
1. In e2e Discover flow: include a `scrollUntilVisible` check for the profiles section and the high liquidity unverified section, as these are below the fold given that there are more verified results when searching for keyword "bitcoin" in e2e now.
2. The `scrollUntilVisible` e2e util has a while loop that would keep going until it found what it wanted - so if in the future some functionality broke and the element could not be found, it would keep trying to scroll forever until the whole test times out. I added an optional param of `maxAttempts` of scrolls for erroring out early if the item hadn't been found within those `maxAttempts` scrolls. I did not update all the places already using `scrollUntilVisible` outside of the Discover …
=> Fixes related to Discover Search and e2e

src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.tsx, src/components/value-chart/ExtremeLabels.tsx, src/safe-math/SafeMath.ts, src/safe-math/__tests__/SafeMath.test.ts
- Fixes handling of scientific notation in the `SafeMath` functions
- Fixes rounding of negative numbers (up = away from zero)
- Adds new test cases that failed previously, primarily due to the two issues above
- Fixes the `divWithExp` result which was previously incorrect
- Fixes the chart price formatting bug where numbers would be chopped at e.g., `0.000`, as a result of these bugs
---
_(Have since fixed the grouping of tests in the logs — the test results are unchanged.)_
=> SafeMath fixes

src/state/internal/createQueryStore.ts, src/state/internal/queryStore/classes/SubscriptionManager.ts
- Follow-up to #6435
- `hasAllRequiredParams` was iterating over indices instead of values — **`key in`** should have been **`key of`**
- This was causing false negatives (params complete, but deemed not) that unnecessarily duplicated the param resolving work
- Fixes an `enabled` edge case where if a store was persisted with an `enabled` value different from its `enabled` config value, the `subscriptionManager` could possibly start out with a different `enabled` value than the store. Also fixes a similar issue affecting dynamic enabled params.
- (Neither of these issues affect the query stores currently in use as they're always enabled)
- Removes `cancel` from the args passed to `fetcher`, as it was simply calling `abort()` on the `abortController` already provided to `fetcher`. And for …
=> Additional query store improvements / fixes

src/raps/actions/claimBridge.ts
Fixes APP-2253
Surfacing more information about bridging failures after points claims and using our slippage config within the claim bridge logic.
<div>
<a href="https://www.loom.com/share/3af0bd251fff42c0a8923da3ef76a529">
<p>Testing Slippage Changes - Watch Video</p>
</a>
<a href="https://www.loom.com/share/3af0bd251fff42c0a8923da3ef76a529">
</a>
</div>
Bridging after claim is not currently working and there is not a great way to test it at the moment either. So we're blocked from testing the slippage change, but I think that's fairly safe to include. Otherwise this PR is just meant to improve the information in Sentry.
=> Claim Bridge Slippage Adjustment to Follow Config & Better Error Logging

config/test/jest-setup.js, jest.config.js, package.json, src/resources/tokenMetadata/tokenMetadata.ts, src/state/internal/createQueryStore.ts, src/state/internal/createRainbowStore.ts, src/state/internal/queryStore/tests/queryStore.test.ts
- Cleans up the params typing to properly require params if `TParams` are declared
- If `TParams` are declared and all params are optional, an empty object in the config is accepted as valid:
- `params: {}`
- Adds missing params to `useTokenMetadataStore` (this store isn't used yet)
- Exposes the `getQueryKey` function
- Adds some basic `createQueryStore` unit tests
- Now defaulting to updating the `queryKey` for manual fetch calls if an explicit `updateQueryKey` option isn't specified and `skipStoreUpdates: true` is also not used, to avoid edge cases if the `queryKey` hasn't yet been set internally
=> Add query store tests

src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts, src/__swaps__/screens/Swap/resources/search/searchV2.ts, src/__swaps__/screens/Swap/resources/search/utils.ts
Fixes APP-2321
1. Consolidate calls that were being done separately for verified and unverified results. The new v3 endpoint allows consolidation across chains as well as "lists" (e.g, verified, high liquidity unverified, and low liquidity unverified). We can reduce the number of calls we were doing.
2. Re-introduce crosschain search results when there's an exact match on the query.
Example showing crosschain results:
Another example showing crosschain results:
Example showing result for address search:
* Test that swap search results still behave as expected, with the addition of crosschain search results showing up when there is an exact match (in name or symbol)
* Test that pasting in a full address still works as expected
=> Reintroduce support for crosschain search results in swaps search

src/graphql/queries/arc.graphql, src/graphql/queries/metadata.graphql, src/hooks/useImportingWallet.ts, src/screens/ImportOrWatchWalletSheet.tsx
Fixes APP-2352
Fixes a misplaced `.trim()` causing manual entry of seedphrases to not allow whitespace.
https://github.com/user-attachments/assets/8ecf3733-9a85-4cb5-bee4-5f15686c95c4
pasting should still trim whitespace
typing it out should not remove whitespace
=> Fix: Manual seed phrase entry removes spaces automatically

src/state/backendNetworks/backendNetworks.ts
I noticed this issue on the browser extension when implementing runtime networks. There exists an edge case where `createSelector` would update the reference to `lastNetworks` **before** `createParameterizedSelector` which would lead to out of date backendNetworks / backendChains referenced wherever we use `createParameterizedSelector`.
Simply moving the cached reference into each selector will guarantee that both selectors update when there's a network change. This guarantees non-stale data whenever we detect a change.
n/a
n/a
=> Fix: Sync backendNetworks sync issue

src/resources/addys/claimables/query.ts, src/resources/addys/client.ts, src/resources/defi/PositionsQuery.ts, src/resources/summary/summary.ts, src/screens/claimables/sponsored/context/SponsoredClaimableContext.tsx, src/state/assets/utils.ts
Fixes APP-####
We had several instances of the addys http client, now there's a singleton pattern and there's only one being reused everywhere.
This also solves the race condition where environment variables weren't available on runtime
=> Addys refactor

src/model/remoteConfig.ts
Fixes APP-2369
Changes default config local value to false when network status is offline.
idfa prompt checks
=> Default idfa check to false when network fails

ios/OpenInRainbow/ActionViewController.swift, ios/ShareWithRainbow/ShareViewController.swift
Fixes APP-2353
> BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(:) needs to migrate to the non-deprecated UIApplication.open(:options:completionHandler:). Force returning false (NO).
Apple released a breaking change in iOS 18 that broke the method I was using to open the UIResponder. This uses the new `application.open` API on iOS 18 and the old logic for older iOS versions for both the Share and Open extensions.
https://github.com/user-attachments/assets/6effef82-42ea-45db-9cef-afad51a7634d
does it work for you?
=> Fix broken 'open in Rainbow' option in Safari share menu

src/__swaps__/screens/Swap/components/GestureHandlerButton.tsx, src/__swaps__/screens/Swap/components/SettingsPanel.tsx, src/__swaps__/screens/Swap/components/TokenList/ChainSelection.tsx, src/__swaps__/types/assets.ts, src/analytics/event.ts, src/components/Discover/TrendingTokens.tsx, src/components/NetworkSwitcher.tsx, src/components/buttons/NetworkSelectorButton.tsx, src/languages/en_US.json, src/navigation/Routes.android.tsx, src/navigation/Routes.ios.tsx, src/navigation/types.ts, src/screens/NetworkSelector.tsx, src/screens/WalletConnectApprovalSheet.tsx, src/screens/claimables/transaction/components/ClaimCustomization.tsx
Fixes APP-2341, APP-2342, APP-2343, APP-2344, APP-2345, APP-2346
With our growing list of networks, we need to enable scrolling on the network switcher to prevent the sheet from overflowing off the top of the screen.
Swaps now will utilize the new NetworkSwitcher route to change output / input token lists. The token to sell list is filtered down show networks that the user has tokens on. Output is sorted by balance. This is the same functionality as we had before in the dropdown menus.
Adds a variant of NetworkSwitcher to the WalletConnectApprovalSheet. We needed to add the following functionality (or rather remove?)
- the ability to select a network
- we don't want to show which network was selected because technically it's all the networks
- We also want to fill the amount of space in …
=> Network Switcher Implementations

ios/PriceWidget/Providers/TokenProvider.swift, scripts/postinstall.sh, src/handlers/dispersion.ts, src/handlers/gasFees.ts, src/resources/metadata/backendNetworks.ts
* Resolves the conflict happening with react-native-dotenvs and xcconfigs. 
* Reverts previous changes in order to remove hardcoded urls.
After this PR gets merged, we can remove some of the overrides in the CI workflow.
* Confirmed that "env var analysis" shows metadata URL correctly and in full
* Confirmed token widget behaves as expected
* Open "env var analysis" in internal dev settings and confirm metadata URL
* Install token widget and that it behaves as expected
=> Resolve dotenv xcconfig conflict

src/graphql/queries/metadata.graphql, src/hooks/useAdditionalAssetData.ts, src/screens/expandedAssetSheet/components/AssetContextMenu.tsx, src/screens/expandedAssetSheet/components/sections/AboutSection.tsx, src/screens/expandedAssetSheet/context/ExpandedAssetSheetContext.tsx
* Support rainbow field for isRainbowToken
* Add rainbow url as part of metadata links
* Fallback to rainbow link if homepage link on token does not exist
=> Support rainbow field for isRainbowToken

src/components/Discover/TrendingTokens.tsx, src/components/expanded-state/chart/ChartExpandedStateHeader.js, src/graphql/queries/metadata.graphql, src/hooks/useAdditionalAssetData.ts, src/resources/addys/claimables/utils.ts, src/screens/Airdrops/ClaimAirdropSheet.tsx, src/screens/Airdrops/useClaimAirdrop.ts, src/screens/Airdrops/utils.ts, src/screens/expandedAssetSheet/components/AssetContextMenu.tsx, src/screens/expandedAssetSheet/components/SheetContent.tsx, src/screens/expandedAssetSheet/components/sections/AboutSection.tsx, src/screens/expandedAssetSheet/context/ExpandedAssetSheetContext.tsx, src/state/claimables/airdropsStore.ts
Fixes APP-2476
- Adds stale balance handling for claims
- Keys optimistic claims by account address, to avoid conflicts if you have two wallets that were airdropped the same token
- Adjusts the expanded state coin icon animation display logic to show it in prod only for Rainbow tokens
- Not currently seeing this data in the metadata response, so instead using a check based on the asset's `icon_url`, which isn't ideal but works for now, until the data becomes available via the API
- Updates the expanded state Buy section icon
- Fixes the Rainbow list icon alignment
- Improves long symbol handling in `ClaimAirdropSheet`
=> Claim improvements, adjust coin icon animation display condition

src/components/icons/svg/WarpcastIcon.tsx, src/screens/token-launcher/helpers/inputValidators.ts
- Right side of Warpcast svg was getting clipped
- Allow '.eth' suffix on warpcast ftl input
Before:
After:
=> Fix Warpcast icon clipping and input validation

src/languages/en_US.json, src/screens/points/content/console/share.tsx
Fixes APP-2515
- Removed api call to monitor for twitter post to award bonus
- Changed copy to reflect no additional posting bonus
https://github.com/user-attachments/assets/8998df7e-a563-4c4c-b902-aa1ced704d2d
This flow is only in the points onboarding flow, which can only be reached on a wallet group that has not onboarded yet and that has at least a $5 balance.
=> Remove twitter post bonus points

e2e/parallel/4_discoverSheetFlow.spec.ts, src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
Moved the `testID` to the surrounding `View` of the `ButtonPressAnimation` component inside of the `FastCurrencySelectionRow`
When running locally, found that I didn't need to do the extra delay before waiting for the row to be visible. Confirming the tests pass here first.
=> Update testID placement for fast currency selection row

src/analytics/index.ts
Wrap the deprecated analytics usage in class that respects disabling collection. CI was accounting for non insignificant amount of "new users" on iOS. 
old analytics should work as normal
=> Prevent analytics from logging in CI

src/components/asset-list/RecyclerAssetList2/Claimable.tsx, src/resources/addys/claimables/query.ts, src/resources/addys/claimables/types.ts, src/resources/addys/claimables/utils.ts, src/screens/claimables/ClaimPanel.tsx, src/screens/claimables/transaction/components/ClaimCustomization.tsx, src/screens/claimables/transaction/components/TransactionClaimableFlow.tsx
I added an enum to keep track of our current `AddysClaimable` types. We were treating `type` and `action_type` similarly in the past because our conditionals depended chiefly upon 1 of 2 action types. We want to have more flexibility to make changes based on `type` as well, so I made sure to better separate these values in the logic. `Claimable.type` is now `Claimable.actionType` and `Claimable.type` now accurately reflects the type provided by backend (e.g. "clanker", "rainbow_super_token_creator_fees" etc).
Here is a small sanity check to confirm that the display of our typical claimables has not changed:
https://www.loom.com/share/25100eb9731e4e4d96dc939b899f6818
This change is made in anticipation of BE's release of rainbow creator lp fee claims. There should be no discernible …
=> [APP-2520] Rainbow Creator LP Fee Claimables V1

src/utils/openInBrowser.ts
Fixes APP-2276
Prevents calls to `Linking.openURL` if the url parameter is undefined
n/a
n/a
=> Fix: Invariant Violation: Invalid URL: should be a string. Was: undefined

src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx, src/react-native-animated-charts/src/helpers/ChartContext.ts
Removes flat detection and just relies on padding in the fall through case. Because we were using a reduce to sum / average it was causing weird behavior.
[Check here for before screenshots](https://rainbowhaus.slack.com/archives/C0468CDBE75/p1744045819806949?thread_ts=1744044398.701409&cid=C0468CDBE75)
=> Fix chart Y overflow caused by isFlatDetection

src/__swaps__/screens/Swap/Swap.tsx, src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-2360
Adds tracking to all token to buy asset list sections. Simply filter based on `sectionId === 'verified'`
n/a
n/a
=> Add tracking of "Verified Assets" swaps to Amplitude

src/__swaps__/screens/Swap/components/CoinRow.tsx, src/components/ContactRowInfoButton.js, src/components/DappBrowser/search-input/SearchInput.tsx, src/components/DappBrowser/search-input/TabButton.tsx, src/components/context-menu-buttons/ChainContextMenu.tsx, src/components/exchangeAssetRowContextMenuProps.ts, src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx, src/components/send/SendHeader.tsx, src/components/unique-token/Tag.js, src/components/walletconnect-list/WalletConnectV2ListItem.tsx, src/handlers/localstorage/theme.ts, src/helpers/walletConnectNetworks.ts, src/hooks/useManageCloudBackups.ts, src/hooks/useOnAvatarPress.ts, src/hooks/useSelectImageMenu.tsx, src/screens/SettingsSheet/components/GoogleAccountSection.tsx, src/screens/SettingsSheet/components/SettingsSection.tsx, src/screens/change-wallet/ChangeWalletSheet.tsx, src/screens/token-launcher/components/TokenLauncherHeader.tsx, src/theme/ThemeContext.tsx, src/utils/actionsheet.ts
Fixes APP-2502
culprit of the fatal exception was in the walletconnect options where we were mapping chainIds. I just wrapped that in a string template. Also took the opportunity to improve the type safety of the `showActionSheetWithOptions` function. I noticed that the actual callback function could be a number or undefined which isn't what their types declare, so I made sure to check that as well where it applies.
~~Also, been a nitpick of mine, but the action sheets don't follow the current app theme, so I took care of that in this PR as well.~~ This didn't work on Android so I removed it.
I don't believe these are needed. Nothing functionally changed, just improved type safety and fixed the crash
major test should be to test the walletconnect options action sheet on Android
=> Fix: ClassCastException: java.lang.Double cannot be cast to java.lang.String

src/helpers/assets.ts, src/hooks/useCoinListEditOptions.ts, src/screens/expandedAssetSheet/components/AssetContextMenu.tsx, src/screens/token-launcher/context/TokenLauncherContext.tsx
Fixes APP-2545
In the initial release of token launcher, the tokens were getting auto-pinned with cased uniqueIds which prevented them from appearing in the pinned section of the wallet list. To fix this for previously created tokens, I made the pinned tokens section explicitly lowercase the uniqueIds. The issue is that this prevents those tokens from being unpinned, as their real uniqueId in the pinned coins object was still cased for the tokens created before the fix. 
This fix has the consequence of losing the auto pin for those tokens created before the fix and those cased uniqueIds will be "stuck" in the pinned coins object unless we run a migration to remove them / fix their casing. Given the small number of users effected and the small number of tokens per user I don't think a …
=> Fix broken unpinning for some tokens auto-pinned from token launcher

src/entities/transactions/transaction.ts, src/handlers/web3.ts, src/hooks/useWatchPendingTxs.ts, src/languages/en_US.json, src/navigation/types.ts, src/resources/addys/interactions.ts, src/resources/metadata/sharedQueries.js, src/screens/SendConfirmationSheet.tsx, src/state/backendNetworks/backendNetworks.ts, src/state/backendNetworks/types.ts
Fixes APP-1299
Implements the addys endpoint to receive interactions between two wallets. This can be used in other places, but right now is only used in our send confirmation sheet to let the user know if they've sent to that address before or not. It also is used to show the checks for layer 2 networks if necessary.
https://github.com/user-attachments/assets/e9d30adb-4d57-42be-b007-75d03d4b1532
sends on different networks with different account types
should probably test nft sends / ens sends since I strengthened some types there and might've tweaked something wrong
=> Fix logic for "First time send" that we show in Send flow

index.js, src/analytics/event.ts, src/analytics/index.ts, src/components/Discover/DiscoverScreenContext.tsx, src/components/Discover/DiscoverSearch.tsx, src/components/Discover/DiscoverSearchInput.tsx, src/components/remote-promo-sheet/localCampaignChecks.ts, src/components/walletconnect-list/WalletConnectV2ListItem.tsx, src/hooks/useHiddenTokens.ts, src/hooks/useHideSplashScreen.ts, src/hooks/useImportingWallet.ts, src/hooks/useOnAvatarPress.ts, src/hooks/useWalletCloudBackup.ts, src/performance/tracking/index.ts, src/screens/AddWalletSheet.tsx, src/screens/ProfileSheet.tsx, src/screens/SendSheet.tsx, src/screens/SettingsSheet/components/AppIconSection.tsx, src/screens/SettingsSheet/components/Backups/ShowSecretView.tsx, src/screens/SettingsSheet/components/CurrencySection.tsx, src/screens/SettingsSheet/components/LanguageSection.tsx, src/screens/SettingsSheet/components/NetworkSection.tsx, src/screens/WalletConnectApprovalSheet.tsx, src/screens/WelcomeScreen/index.tsx, src/screens/change-wallet/ChangeWalletSheet.tsx
Fixes my last PR which missed a few conversions and caused some type errors.
This one is straightforward, I just missed a few areas. This should finish the conversion and fix type issues. I am seeing one type error:
```
src/resources/metadata/tokenInteractions.ts:23:43 - error TS2339: Property 'interactionsWithToken' does not exist on type '{ getContractFunction(variables: Exact<{ chainID: number; hex: string; }>, options?: Options | undefined): Promise<GetContractFunctionQuery>; getEnsMarquee(variables?: Exact<...> | undefined, options?: Options | undefined): Promise<GetEnsMarqueeQuery>; ... 15 more ...; trendingDApps(variables?: Exact<...> | undefine...'.
23     const response = await metadataClient.interactionsWithToken({
~~~~~~~~~~~~~~~~~~~~~
Found 1 error in …
```
=> fix analytics missing conversions

src/raps/actions/swap.ts
Fixes APP-2549
We needed to store `swap.data` rather than the quote data to include the referrer fingerprint when attempting to execute the transaction again in the speed up flow.
Also saw a question in our comments and made a small fix.
https://etherscan.io/tx/0xb050e4b36f8c23f7f831a96f0f24d35528522630775f83c25c0f0ad2a8907e18
Attempt a slow transaction, proceed through the speed up flow, check Input Data on the explorer afterwards.
`keccak256(toUtf8Bytes('native-app')).substring(2, 10) === 'd7e44d53'`
=> fix: properly append referrer fingerprint during speed up

src/screens/expandedAssetSheet/components/sections/BuySection.tsx, src/screens/expandedAssetSheet/components/sections/HistorySection.tsx
Fixes APP-2567
Fix spacing on Android history section. It's because ButtonPressAnimation component doesn't accept a gap prop but accepts a style prop. I don't know why this worked on iOS to be honest lol.
no regressions on iOS
=> Fix: Expanded State History spacing off on Android

src/screens/expandedAssetSheet/components/sections/HistorySection.tsx
Noticed an overflow when symbols took up too much space that pushed the native currency amount off screen.
none really needed, small change here
=> Fixes long symbol overflow on asset expanded state history section

src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx, src/navigation/config.tsx, src/screens/Explain/index.tsx, src/screens/Portal/index.tsx, src/walletConnect/index.tsx
Fixes APP-1913
Fixes up the Portal screen to no longer use SlackSheet and instead opt to use a a fullscreen cool modal with desired sheet height. the body of the portal will overflow a scrollview if needed.
BEFORE
AFTER
no tests really needed for this.
=> Fix walletconnect error sheet overflow

src/helpers/buildWalletSections.tsx
- Fixes an issue from #6521 where switching wallets caused the total balance row to be removed while loading, instead of displaying a loading state
=> Fix wallet screen layout shift

src/resources/nfts/index.ts
Increased internal NFT cache duration.
n/a
Nothing, however any input on whether this change could have unintended consequences would be helpful.
=> Increase NFT Cache Duration [APP-2583]

src/state/internal/createQueryStore.ts
- There were a few spots internally where `setWithEnabledHandling` should've been used over `set`, which is a reference to the original `api.setState` and lacks the extra handling around changes to `enabled`
- Specifically, `setData`, `onFetched`, and the user's `customStateCreator` now receive `setWithEnabledHandling` instead of the original `set`, so changes to `enabled` that occur within those functions are properly reacted to
- Shoutout @maxbbb for discovering this
=> Adjust query store's internal set usage to cover all enabled changes

src/components/backup/BackupWalletPrompt.tsx, src/components/backup/ChooseBackupStep.tsx, src/components/backup/CloudBackupPrompt.tsx, src/components/backup/RestoreCloudStep.tsx, src/components/secret-display/SecretDisplaySection.tsx, src/hooks/useImportingWallet.ts, src/react-native-cool-modals/Portal.tsx, src/screens/SettingsSheet/components/Backups/ViewCloudBackups.tsx, src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx, src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx, src/screens/SettingsSheet/components/SettingsSection.tsx
Small changes to a few Zustand store selectors that were constructing objects but not using shallowEqual.
n/a
n/a really?
=> fixes object selectors that don't use shallowEqual

src/components/secret-display/SecretDisplayCard.tsx
Fixes APP-2269
box height from 90 > 120 to accommodate 3 lines of pkey text. previously a large amount of user pkeys were being cut off by the box height.
longest and shortest a pkey can be:
=> change height of pkey box

src/utils/formatDate.ts
We are currently showing '1 hours' in the app. This tweak fixes it.
=> Account for '1 hour' in formatDate [APP-2593]

README.md
Fixes APP-####
In the `.nvmrc` file, we use version 18, whereas the Readme document still indicates version 16.
N/A
N/A
=> Update the Readme to specify the version of Node required.

e2e/onboarding/WatchedWallet.yaml, e2e/screens/Discover.yaml, src/components/Discover/DiscoverScreenContext.tsx, src/screens/DiscoverScreen.tsx
Fixes APP-####
There was some changes made between the time we ran the tests in the PR branch and the time it was merged that caused the e2e tests to break.
One change is https://github.com/rainbow-me/rainbow/pull/6575, which changed the search UI a little bit.
The other one I am not sure, the test wallet used to have a cell of type FAMILY_HEADER for ENS, but it doesn't seem to be there anymore. Maybe someone can confirm if this is ok, for now I just removed that part of the test.
N/A
N/A
=> Fix e2e tests

src/components/cards/EthCard.tsx
Fixes APP-####
This fixes an error that happens when transitioning from having no wallet to having a wallet (create or import). It is a regression from https://github.com/rainbow-me/rainbow/commit/a8e41768f8a7fb9eeab95898b25ceea9ae717941#diff-67e8a63e75cf95c7772f41b5c98ea2e4952fd074e00fa7996d4a84d7b48e7cff.  If `ethAsset` is undefined then it will crash in `useChartThrottledPoints`. This bring back the previous behaviour of making it so `ethAsset` can never be undefined.
```
ERROR  TypeError: Cannot read property 'address' of undefined
This error is located at:
in EthCard (created by ViewRenderer)
in RCTView (created by View)
```
Before
https://github.com/user-attachments/assets/86e852db-cb0c-4d95-84c9-3fc544af4904
After
https://github.com/user-attachments/assets/d7ccffba-8e61-47cc-9539-45 …
=> Fix error when creating wallet

src/screens/expandedAssetSheet/components/sections/marketSection/MarketStatsCard.tsx
Fixes APP-####
I found a bug that caused e2e tests to fail, it happens when opening an asset page. The MarketStats component had an early return that caused number of hooks to change so react errors. This splits the component into 2 so we can early return properly.
N/A
Open asset screen
=> Fix MarketStatsCard hooks error

src/analytics/event.ts, src/hooks/useRefreshAccountData.ts
Fixes APP-2589
- Adds analytic for pull to refresh 
- Moves some of the fetches to the awaited `Promise.all` so that the pull to refresh activity indicator exiting more accurately reflects the refresh completion.
=> Add tracking for wallet screen pull to refresh 

src/helpers/buildWalletSections.tsx, src/hooks/useWalletSectionsData.ts
- Fixes failing lint from #6583
- `remoteConfig` in the wallet list data doesn't seem to be used anywhere, so removed instead of changing the type
=> Fix lint error

src/keychain/index.ts
Fixes APP-2622
When upgrading `react-native-keychain` to v9 it now uses instead `BLOCK_MODE_GCM` of `BLOCK_MODE_ECB` which supports biometrics authentication. This means that it will prompt for biometrics when trying to encrypt or decrypt values. 
The issue is that when restoring multiple wallets from a backup it executes many operations requiring encryption in a row and it seems like pixel device rate limit how often the prompt can be shown and the encryption key generated is only valid for 5 seconds because of the config in react-native-keychain. This means that sometimes the generated key is expired, but the system will not allow showing a biometrics prompt yet.
To fix this we can increase the validity of the key to 5 minutes to reduce the number of prompts, and I think this still …
=> Fix keychain biometric prompts on Android

.eslintrc.js, e2e/dapp-connections/WalletConnect.yaml, e2e/onboarding/SecretPhraseWallet.yaml, e2e/settings/SettingsFlows.yaml, e2e/utils/ImportSecretPhrase.yaml, src/components/AppVersionStamp.tsx, src/screens/SettingsSheet/components/SettingsSection.tsx, src/screens/SignTransactionSheet.tsx
- This is part of expanding maestro to cover more of the critical path 
- This PR covers Secret Phrase importing and Settings flows
- Settings flow covers currency, theme, and diagnostics
- We have a separate settings test that covers Manual Backups
also included a change to our pre-commit for yaml files to match the styles we have been using.
- Do they pass?
=> tests for import secret and basic settings flows

ios/fastlane/Fastfile
Issue with bitrise that started yesterday; this is a workaround
=> Update Fastfile match action flag from force to readonly

android/app/build.gradle
Fixes APP-####
This causes dev builds to fail since I do not have access to the sentry org. We don't need to run it for debug builds.
N/A
N/A
=> Don't run sentry gradle plugin for debug builds

src/logger/index.ts
Fixes APP-2695
In dev mode errors that were created like `new RainbowError('this err message', parentErr)`  the parentErr wouldn't log at all. This was causing bad error messages in initializeWallet / walletStore stuff.
After this change it will log the original error message and then ↠ and the cause error message:
Make sure Sentry/dev errors are properly formatted.
=> improve RainbowError toString to show cause toString

android/app/src/main/AndroidManifest.xml
Fixes APP-####
- Fixed `rainbow.me/points` app link capture on Android
- This change mirrors the behavior of the iOS AASA file, but sadly cannot be amended remotely. Historically we've treated all rainbow.me links as app links and would capture all new routes as a redirect and inadvertently block web access to rainbow.me paths on Android; now we'll need to be considerate and add routes with releases.
=> fix: codified android app link intent filter matching

src/__swaps__/screens/Swap/components/GasPanel.tsx, src/__swaps__/screens/Swap/constants.ts, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/__swaps__/screens/Swap/providers/swap-provider.tsx, src/__swaps__/utils/meteorology.ts, src/components/FeesGweiInput.tsx, src/components/FeesPanel.tsx, src/components/expanded-state/CustomGasState.js
Fixes APP-2679
- there were some small discrepancies between the send and swaps gas menus
- this PR looks to bring them in sync and fix a few layout issues
- the changes in https://github.com/rainbow-me/rainbow/pull/6667/files#diff-ccc8719fedf209705f516661417d59204aef0b19c8473ec3e06c1dc0573c032aR421-R437 are designed to make the swaps bottom sheet height dynamic. the review and settings sheets never had any height issues bc their content was static but the gas sheet was dynamic. depending on the network (Arbitrum, BSC, Polygon all were effected) the amount of items you can modify for the gas price shrinks. The gas panel had a static heigh set in `src/__swaps__/screens/Swap/constants.ts` though. This should now be dynamically calculated. The behavior should be identical. i checked on both …
=> fix layout for swaps gas menu / remove the priority fee for L2s that don't use it

src/components/backup/useCreateBackup.ts
Fixes APP-2682
If the sync completes too early then the timeout that sets the syncing state will happen after and the state will never be set back to success. To fix it we can cancel the timeouts once the sync is done.
Before:
https://github.com/user-attachments/assets/97ccc1ac-1a77-4255-b827-29987df3979c
After:
https://github.com/user-attachments/assets/2acf6a5f-2b7d-44f5-8941-7dbe4dfc881a
Create a new backup and check that it doesn't stay stuck in syncing state
=> Fix backup stuck in syncing state

src/components/expanded-state/unique-token/saveToCameraRoll.ts
Fixes APP-####
While testing another PR I noticed a bug with downloading SVG NFTs. The code assumes the images are PNGs, but it is not always the case. Adding this option will convert the image to PNG if it is not already.
https://github.com/user-attachments/assets/b49f187d-0568-4280-9d15-5582a4cd6e86
- Go to an SVG NFT (rainbowtestwallet.eth -> Arun Cattybinky is one)
- Click ... and Save to Photos
=> Fix saving SVG NFTs

src/model/backup.ts
Fixes APP-####
When adding a wallet this function gets all keychain values that must be saved https://github.com/rainbow-me/rainbow/blob/3680f0bb83929127bc95e587a62f180fe17c3038/src/model/backup.ts#L169. The problem is that it filters the values differently from the function that backs up all wallets, and more keys are included. In itself this isn't a big problem, but some of these keys are encrypted using rainbow password (signature_ keys). The code that tries to decrypt values that might be encrypted with rainbow PIN then incorrectly tries to decrypt those and prompts for rainbow PIN, even if the user doesn't have one.
Note that the backup still works, since the keys it tries to decrypt are not used.
This fixes the key filtering to only include private keys and secret phrases, making it …
=> Fix incorrect ask of rainbow pin when backing up new wallet

src/components/backup/RestoreCloudStep.tsx, src/components/backup/useCreateBackup.ts, src/handlers/authentication.ts, src/model/backup.ts
Fixes APP-2682
This fixes the issue in 2 steps:
- If the rainbow PIN screen is shown twice in a row, the second time it will not work, and any promise that depends on it will hang forever. This is because 2 navigation actions too close to each other for the same screen will cause one of them to be ignored. This adds a short delay to resolving or rejecting the promise so it never happens.
- We should actually not prompt for PIN twice, this happens because we try to get the backup password from keychain, and also fetch all secrets. To fix this we can explicitly ask for PIN and pass it down to the functions that will need it so it won't prompt.
After first fix:
https://github.com/user-attachments/assets/de1cbddd-98f1-4560-9637-ef6ef4aabb8a
After second fix: …
=> Fix backup when using rainbow PIN

patches/react-native-keychain+10.0.0.patch
Fixes APP-####
https://rainbow-me.sentry.io/issues/6582602973/?query=is%3Aunresolved%20createWallet&referrer=issue-stream&stream_index=1
We're getting this exception when trying to read a value in keychain on old android versions `java.lang.IllegalArgumentException: Authenticator combination is unsupported on API 28: BIOMETRIC_STRONG | DEVICE_CREDENTIAL`. This is because of our RN keychain patch. This adjusts it so we only pass `BIOMETRIC_STRONG | DEVICE_CREDENTIAL` on versions where it is supported.
Tested creating a wallet on moto8 on Android 9.
=> Fix RN keychain crash on android api <= 29

e2e/transactions/SwapTransaction.yaml, e2e/transactions/WrapTransaction.yaml, e2e/utils/ImportWalletWithKey.yaml, scripts/e2e-android.sh, src/__swaps__/screens/Swap/Swap.tsx, src/__swaps__/screens/Swap/components/ExchangeRateBubble.tsx, src/__swaps__/screens/Swap/components/FlipButton.tsx, src/__swaps__/screens/Swap/components/GasButton.tsx, src/__swaps__/screens/Swap/components/GasPanel.tsx, src/__swaps__/screens/Swap/components/ReviewPanel.tsx, src/__swaps__/screens/Swap/components/SettingsPanel.tsx, src/__swaps__/screens/Swap/components/SwapBottomPanel.tsx, src/__swaps__/screens/Swap/components/SwapNavbar.tsx, src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts, src/design-system/components/Inline/Inline.tsx, src/helpers/RainbowContext.tsx, src/references/testnet-assets-by-chain.ts, src/resources/assets/anvilAssets.ts, src/resources/favorites.ts, src/state/assets/utils.ts
This PR adds one flow and several test case assertions.
Added:
- Eth > Weth wrapping
- flipping assets
- review sheet
- changing gas
- degen mode
- slippage
- activity screen
- preferred network
- home screen balance updates
I decided to split these tests through the two swaps flows we currently have so that no one is super long and maybe to also reduce flakiness if possible.
=> Add wrap test and go through settings flows

src/App.tsx
- Set enabled flag for `PerformanceProfiler` to true in prod only. Fast refresh can cause errors and we don't need to be measuring the performance in dev anyway.
=> Disable react native performance in dev

ios/Button.swift
iOS 26 removed accessing a private `_state` field on the `UILongPressGestureRecognizer`, but it never needed to be accessed this way. Changing it to normal public access fixes the crash.
=> Fix iOS 26 touches crash

src/components/contacts/ContactRow.js, src/components/send/SendContactList.js
Fixes APP-2680
We had an erroneous `ensName` prop that was resolving to the shorthand of the address field (e.g. - `0x1231...123123`) that was throwing an invalid address which put users into an infinite loading button state. This fixes it by always using the address.
https://github.com/user-attachments/assets/5b70df61-3439-4aed-8d43-41336c658d27
ERC 20 sends to addresses, ens names, contacts, etc.
=> Fix: ERC20 Token Transfer Stuck on "Loading"

.github/workflows/android-e2e.yml, .github/workflows/macstadium-ios-e2e.yml
Fixes RNBW-4879
Make test run on develop pushes. Also make sure concurrency settings doesn't cancel in progress runs to make sure it runs on every commit when running on develop.
N/A
Check that tests run on develop properly once merged.
=> Run e2e tests on develop

src/model/migrations.ts, src/react-query/queryClient.ts
Fixes APP-854
just another migration that should wipe out any unused nfts storage.
n/a
nothing really to test here, just unused keys being wiped
=> Fix: Clean up old react-query keys for legacy nft store

package.json, src/components/activity-list/ActivityList.tsx, src/hooks/useAccountTransactions.ts, yarn.lock
Fixes APP-2855
I had seen pending transactions showing "empty" yesterday while working on king of the hill, but was unable to reproduce it today on either koth or develop branch.
While I was there I upgraded to the latest legend-list and tested it, and removed some unused code I found.
No changes visually:
LegendList is upgraded so it's useful to test it:
- ActivityList
- AirdropsSheet
=> small cleanup on activity list

src/components/tab-bar/BrowserTabIcon.tsx, src/components/tab-bar/TabBarIcon.tsx, src/components/tab-bar/dimensions.ts, src/navigation/RecyclerListViewScrollToTopContext.tsx, src/navigation/SwipeNavigator.tsx, src/state/navigation/navigationStore.ts
Fixes APP-2871
- Restyles the tab bar to be a floating pill
- Previously the tab bar re-rendered for every route change due to receiving the navigation state. As a temporary fix, now wrapping the state in a ref and passing that instead, as it doesn't need to react to the state. Will address this properly later, to avoid needing the memo shield, but this lightens the tab bar quite a bit as it now doesn't re-render.
- Minor code cleanup in `RecyclerListViewScrollToTopContext`
https://github.com/user-attachments/assets/b087153d-310f-4291-b252-0523c292b4a4
Light mode:
=> New tab bar

ios/AppDelegate.swift, ios/Rainbow.xcodeproj/project.pbxproj, ios/Rainbow/Base.lproj/LaunchScreen.xib, ios/RainbowSplashScreen.m, ios/RainbowSplashScreen.swift
Fixes APP-2904
- Seems the RN upgrade broke the iOS splash screen animation. The native module wasn't being picked up by RN.
=> Fix splash screen animation

ios/AppDelegate.swift
Fixes APP-####
I wasn't using the API properly to set the default color space, we need to override `defaultColorSpace`, otherwise the value was getting overriden later.
Before:
After:
Compare colors before and after change
=> Fix P3 colors

src/model/remoteConfig.ts, src/screens/points/claim-flow/ClaimRewardsPanel.tsx
- Move Rainbow rewards claimable chains to remote config, limit to Optimism only. 
- Fix claim button layout, which was cutoff below bottom of panel
- Rainbow ETH rewards claimable - should only see OP Mainnet
=> Move allowed rainbow rewards claimable chains to remote config

.github/workflows/macstadium-builds.yml, ios/Podfile, ios/Podfile.lock, ios/Rainbow.xcodeproj/project.pbxproj
Fixes APP-2912
Before, you had to install rosetta to build on iphone simulator since arm64 was excluded both in `Podfile` and directly in `project.pbxproj`. They were needed on some old Xcode that prolly didn't support it back then: https://github.com/rainbow-me/rainbow/pull/1146. Should work correctly now when building without rosetta on arm64. I suggest clearing DerivedData, `Pods` and `build` folder in `ios` directory before testing it.
(not sure why `react-native-udp` got updated in `Podfile.lock`, prolly because I deleted `Podfile.lock` while testing)
Nothing to pass here really.
That the app builds correctly on iOS simulator with ARM64 architecture (not using rosetta)
=> fix: restore arm64 as proper platform

src/components/rainbow-toast/RainbowToast.tsx, src/components/rainbow-toast/RainbowToastExpandedDisplay.tsx, src/components/rainbow-toast/constants.ts, src/components/rainbow-toast/useRainbowToasts.ts, src/components/rainbow-toast/useVerticalDismissPanGesture.ts
Fixes APP-2873
Added useVerticalDismissPanGesture so you can swipe up/down the mini toasts.
https://github.com/user-attachments/assets/9a4b2af4-e353-4302-b21c-8f3815d3328b
All interactions on toasts both mini and expanded, especially:
- pull down to dismiss
- push up to dismiss
=> Toasts - improved dismiss gestures

.github/workflows/android-e2e.yml, e2e/README.md, scripts/e2e-android-ci.sh, scripts/e2e-ios-ci.sh, scripts/e2e-run.sh
Fixes APP-2923
Automatically start recording retries when the test fails the first time. This will help debugging a lot. I think recording only retries for now will be good, and avoid overhead of always recording.
Check that a video recording is available when a test fails in the run artifacts on both iOS and Android.
=> Record e2e test failures

src/components/rainbow-toast/constants.ts, src/components/rainbow-toast/useRainbowToastsStore.ts, src/hooks/useTransactionWatcher.ts, src/hooks/useWatchPendingTxs.ts, src/state/pendingTransactions/index.ts
Fixes APP-3041
The problem here was that when multiple pending transactions were added in a row, it would cause the watcher to fetch only the first one, then set the pending transactions state with that, overriding any transactions that came in after.
To avoid this we can pass an abort signal that will be called whenever a new transaction watcher function is called. Any previous execution can then return instead of continuing to process.
Send an ens, should now generate 3 pending transactions in the activity list as well as 3 toasts.
=> Fix pending transactions when multiple are added at once

package.json, shim.js, src/features/charts/candlestick/components/CandlestickChart.tsx, src/features/charts/candlestick/hyperliquid/hyperliquidCharts.ts, src/features/charts/candlestick/types.ts, src/features/charts/candlestick/utils.ts, src/features/charts/constants.ts, src/features/charts/stores/candlestickStore.ts, src/features/charts/stores/chartsStore.ts, src/features/charts/types.ts, src/features/charts/utils.ts, yarn.lock
Fixes APP-2987
- Integrates Hyperliquid candlestick charts via a forked `fetcher` in the candlestick store
- If the `token` in the charts store is a string (a `HyperliquidSymbol`), it uses adapter functions to build an analogous Hyperliquid API request and maps the response to the existing charts system
- We can alter the Hyperliquid token IDs as needed
- Adds a polyfill for `AbortSignal.any` which seems to be needed for Hyperliquid charts requests
- Not blocking this PR, but need to verify behavior if a non-USD currency is selected as Hyperliquid only supports USD (USDC). Will likely need to account for this in the charts components, which currently rely exclusively on the global `currency` setting.
_With charts hardcoded to HYPE for testing:_ …
=> Hyperliquid charts

src/features/perps/screens/perps-account-screen/PerpsAccountScreen.tsx, src/navigation/Routes.android.tsx, src/navigation/Routes.ios.tsx
Fixes APP-3089
- Added lazyPreloadDistance which causes the immediate neighbor screens next tab to mount in the background. In our Perps stack, that means the full markets list screen mounts while you’re on the account tab. It doesn’t render offscreen list items or prefetch data by itself. It simply mounts the screen component(s). Any fetching happens if the mounted screen subscribes to data (which in our case it does via the store).
- For the Scroll freeze on first load: Removed the inner flex constraint from the Perps account screen and moved padding to the ScrollView’s content container. This lets the content grow naturally so it scrolls the first time markets render.
=> Fix flash/scroll issue on market screen

src/components/Transactions/TransactionSimulationCard.tsx, src/hooks/useHasEnoughBalance.ts, src/screens/SignTransactionSheet.tsx, src/utils/ethereumUtils.ts
Fixes APP-2715
- Enhanced `getNetworkNativeAsset` to accept an optional wallet address parameter, allowing it to fetch assets for specific wallets rather than just the global wallet
- Modified `getAccountAsset` to support retrieving assets from a specific wallet's cache
- Updated `SignTransactionSheet` to use the improved native asset fetching with the correct wallet address
- Added comments to explain the purpose and behavior of the asset retrieval functions (cached vs not-cached fetching)
https://github.com/user-attachments/assets/8fa24f59-c3fe-4604-b57c-23ab001d518c
- Verify that the correct native asset is displayed when signing transactions from different wallets
- Confirm that wallet selection in the dapp browser correctly shows the native asset balance for the selected wallet
- …
=> fix: native asset wallet alignment in dapp browser control panel

scripts/e2e-android-perf-ci-report.sh
Fixes APP-####
The name of the artifact should be `perf-results-develop`, the one that is currently there was the test branch I was using when working on the initial PR.
N/A
See that baseline now appears in the perf report.
=> Fix perf tests baseline

src/navigation/bottom-sheet/views/BottomSheetRoute.tsx, src/screens/change-wallet/ChangeWalletSheet.tsx
Fixes APP-3135
The issue was caused by the snap points being set to 100%. This made the sheet occupy the full screen, so when dragging a smaller sheet (around 30% of the screen), it wasn’t enough to trigger handleClose from Gorhom.
I also added an isLayoutMeasured check since there was a flicker on the first render.
=> Fix bottom sheet issue for change wallet for Android

src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx, src/components/asset-list/RecyclerAssetList2/core/RawRecyclerList.tsx, src/languages/en_US.json, src/screens/WalletScreen/WalletScreen.tsx, src/screens/expandedAssetSheet/components/sections/BalanceSection.tsx, src/state/liveTokens/liveTokensStore.ts
Fixes APP-3038
- Added "~" to any balance value on the wallet screen that is capped due to low liquidity 
- Added disclaimer below balance section on expanded state stating the uncapped value
- Slightly related fixes
- Fixed issue with live token subscriptions on wallet screen being removed immediately on mount. 
- Force live token refetch immediately after adding token subscriptions from wallet list
https://github.com/user-attachments/assets/9a1d5cd2-0149-44ce-b447-19c5a25d0fde
=> Visual indicators for token balance liquidity capping

src/components/DappBrowser/DappBrowser.tsx, src/components/DappBrowser/screenshots.ts
Fixes APP-3142
- Ensures proper cleanup of cached browser tab previews from local device storage. There were a few ways for the registry to lose track of cached images to delete.
- Now using a queue to prevent conflicts between save and prune operations.
- Also added a periodic deep prune to be safe, though the queue likely addresses the original root problem.
=> Make browser tab preview cleanup more robust

src/react-native-animated-charts/README.md
Replaced the outdated and broken link to the React Native Reanimated installation documentation in the README with the current official URL:
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/
This ensures users can access the latest installation instructions.
=> Fix broken link to React Native Reanimated installation docs
