- package.json
Fixes APP-####
- i re-added a change (that i mistakenly removed) by jake from his pr that i just merged
> fix android build

- src/handlers/dispersion.ts
- src/hooks/useInitializeWallet.ts
- src/redux/additionalAssetsData.ts
- src/references/chain-assets.json
> Remove coingecko id fetching from additional asset data

- src/screens/op-rewards/OpRewardsSheet.tsx
- src/screens/op-rewards/mocks/getMockOpData.ts
- src/screens/op-rewards/types/OpRewardsResponseType.ts
* Implemented an async function that returns OP rewards mock data after a second
> Mock OP rewards data

- src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
- src/components/cards/EthCard.tsx
- src/components/expanded-state/asset/ChartExpandedState.js
- src/model/config.ts
> Move flagging out of features object in config

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS v1.8.7 & android 158
> Version bump iOS v1.8.7 & android 158

- src/languages/_english.json
- src/languages/_french.json
- src/screens/rewards/components/RewardsContent.tsx
- src/screens/rewards/components/RewardsPendingEarnings.tsx
- src/screens/rewards/components/RewardsSectionCard.tsx
- src/screens/rewards/components/RewardsTotalEarnings.tsx
* Implement Pending Earnings Card
More in Linear
> Pending Earnings Card

- src/model/wallet.ts
forgot to fix the alias back to `@`
na
ci will pass
> chore: clean up wrong alias

- src/screens/AddWalletSheet.tsx
- src/screens/ImportOrWatchWalletSheet.tsx
Fixes APP-387
- this was probably a side effect of one of my recent PRs
- fixed it by adding a bg color
https://www.loom.com/share/25a8009bfada4e9da762452f696bd65f
> AddWalletNavigator bg color fix android

- src/model/wallet.ts
Fixes APP-346
removing custom ledger naming handling, more info in the ticket 
n/a
> ledger: rm naming handling

- src/utils/ledger.ts
- src/utils/wallet.ts
Fixes APP-403
moving some logic to control when bluetooth permissions are being requested  
will move most of the smaller utils/error handling here in a bigger PR
> ledger: utils file + bluetooth permission fix

- src/handlers/localstorage/accountLocal.ts
To be paired with fix for double ETH bug.
> Bump storage version for acct assets data and assets data

- src/languages/_english.json
- src/languages/_french.json
- src/screens/rewards/components/RewardsContent.tsx
- src/screens/rewards/components/RewardsPendingEarnings.tsx
- src/screens/rewards/components/RewardsProgressBar.tsx
- src/screens/rewards/components/RewardsStats.tsx
- src/screens/rewards/components/RewardsStatsCard.tsx
- src/screens/rewards/components/RewardsTotalEarnings.tsx
Implemented My Stats rewards section based on mock data. The section doesn't have the info sheet actions just yet because the copies for that are not yet prepared. Will address that separately
> My Stats rewards section

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> version bumps

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> version bumpz

- src/redux/data.ts
> Modify merging of assets for mainnet assets

- src/languages/_english.json
- src/languages/_french.json
- src/screens/rewards/RewardsSheet.tsx
- src/screens/rewards/components/RewardsContent.tsx
- src/screens/rewards/components/RewardsProgramStatus.tsx
Fixes APP-421
* Added error status
* Added program ended status
* Changed Content component to make the decision what to render as content instead of relying on nested ternary in main component, code looks better no change other than that
More in Linear
> Add Rewards finished and error status

- src/App.js
- src/analytics/userProperties.ts
- src/storage/schema.ts
- src/utils/branch.ts
Calls Branch's SDK for first install referrer params and sets user properties in metrics
> Include branch ref params in metrics

- src/analytics/event.ts
- src/languages/_english.json
- src/languages/_french.json
- src/model/config.ts
- src/screens/discover/components/DiscoverHome.js
- src/screens/rewards/RewardsSheet.tsx
- src/screens/rewards/components/RewardsAvailable.tsx
- src/screens/rewards/components/RewardsContent.tsx
- src/screens/rewards/components/RewardsEarnings.tsx
- src/screens/rewards/components/RewardsLeaderboard.tsx
- src/screens/rewards/components/RewardsLeaderboardItem.tsx
- src/screens/rewards/components/RewardsStats.tsx
* Implemented a remote config flag to control whether the rewards card is visible
* Added a way to override remote flag and enable the card anyway if we want to in Dev
> Rewards remote config flag

- src/parsers/accounts.js
- src/parsers/index.ts
- src/parsers/uniqueTokens.js
- src/redux/data.ts
- src/redux/explorer.ts
- src/redux/uniqueTokens.ts
- src/redux/uniswapLiquidity.ts
More cleanup post fallback explorer removal
> Explorer cleanup

- package.json
- yarn.lock
Fixes APP-443
added resolution for APP-@sideway/formula
minor bump, deets in linear
n/a
CI
> audit @sideway/formula

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS v1.8.10 & android 161
> Version bump iOS v1.8.10 & android 161

- src/languages/_english.json
- src/languages/_french.json
* Small followup to fix 30k OP to be 28k OP every week
> Change OP explainer sheet copy

- src/languages/_english.json
> update one 30,000 > 28,000

- src/redux/explorer.ts
- src/screens/TransactionConfirmationScreen.js
- src/utils/ethereumUtils.ts
Fixes APP-445
fixed loading native asset for testnets and cleaned up the logic to be a lil more readable 
https://cloud.skylarbarrera.com/Screen-Recording-2023-02-10-09-56-55.mp4
alpha.ens.domains
> fix goerli WC

- src/design-system/color/palettes.ts
Fixes APP-446
updating design systems tokens cause design told me to 
https://cloud.skylarbarrera.com/Screen-Shot-2023-02-10-15-51-04.94.png
> RDS: update dark mode bg tokens

- src/entities/nativeCurrencyTypes.ts
- src/helpers/bigNumberFormat.ts
- src/helpers/uniswapLiquidityTokenInfoSelector.ts
- src/parsers/gas.ts
- src/parsers/newTransaction.ts
- src/parsers/transactions.ts
- src/redux/gas.ts
- src/redux/settings.ts
- src/utils/ethereumUtils.ts
* Replaced usages of manual native currency key retrieval with an already expored type alias
> Replace manual native currency key types to use a type alias

- src/graphql/queries/metadata.graphql
* Added a newly added ENS reverse record query from metadata API.
Tis was previously part of #4621 but was extracted to a smaller more granular PR
> Add ENS reverse record metadata API query

- CHANGELOG.md
- android/app/build.gradle
> update android v + make changelog meaningful

- src/languages/_english.json
- src/languages/_french.json
- src/screens/WalletConnectApprovalSheet.js
Fixes APP-331
Implemented new designs for the networks on this sheet.
> feat: upgrade WC approval sheet designs

- src/screens/WelcomeScreen/WelcomeScreenRainbowButton.tsx
- src/screens/WelcomeScreen/index.tsx
* Moved WelcomeScreen to its own direcotry
* Extracted `RainbowButton` to be a `WelcomeScreenRainbowButton` and in a separate file
It was previopusly a part of #4616 but after discussion with @estrattonbailey I decided to split it into smaller chunks
> Move WelcomeScreen to separate screens directory and split components into separate files

- src/config/experimental.ts
> turn on l2 txs

- src/featuresToUnlock/unlockableAppIcons.ts
> another pooly app icon unlock nft

- src/screens/WalletConnectApprovalSheet.js
Fixes APP-331
Handles long ENS/wallet addys and long network names
V1:
V2:
> [WCv2] fix: wallet/network spacing

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS v1.8.13 & android 165
> Version bump iOS v1.8.13 & android 165

- src/screens/WalletDiagnosticsSheet.js
Fixes APP-476
missed when we updated analytics
https://cloud.skylarbarrera.com/Screen-Shot-2023-02-27-18-12-03.59.png
> fix: show uuid on wallet diagnostic

- src/entities/tokens.ts
- src/hooks/useColorForAsset.ts
- src/hooks/useImageMetadata.ts
Fixes APP-271
we not take advantage of the BE doing some hard compute for us, can still be improved but this is a first pass to unblock BSC.
https://cloud.skylarbarrera.com/Screen-Recording-2023-02-27-17-28-20.mp4
token colors
> chore: use token colors from the BE

- src/languages/_english.json
- src/languages/_french.json
Minor copy change to reflect backend value
> Update OP rewards copy

- src/redux/walletconnect.ts
Trying to squash a bug, unsure where it's coming from but might be one of these.
> fix: remove unhandled exceptions

- src/languages/_english.json
- src/languages/_french.json
> changed it to be less wordy and fixed a double space

- src/logger/debugContext.ts
- src/model/keychain.ts
Just tryna quiet Sentry a bit, we get 100k+ errors per fortnight related to keychain stuff that aren't really errors at all.
> feat: clean up keychain logging

- src/storage/legacy.ts
- src/storage/schema.ts
> feat: subclass storage for legacy values

- ios/PriceWidget/Info.plist
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Rainbow/Info.plist
- src/components/text/ErrorText.js
- src/components/text/Monospace.js
- src/components/text/index.js
- src/components/unique-token/UniqueTokenImage.js
- src/styles/buildTextStyles.js
- src/styles/fonts.js
removing as its only used in one location, in old DS,  and will help reduce bundle size
rm monospace fonts and instances, replaced with our standard font
> fonts: rm monospace fonts

- src/handlers/simplehash.ts
- src/helpers/RainbowContext.tsx
- src/helpers/alert.ts
> feat: move helpers to new logger

- src/utils/dimensionsPropType.ts
- src/utils/directionPropType.ts
- src/utils/ethereumUtils.ts
- src/utils/getBlocksFromTimestamps.ts
- src/utils/getDominantColorFromImage.ts
- src/utils/index.ts
- src/utils/ledger.ts
- src/utils/memoFn.ts
- src/utils/platform.ts
Just replacing old logger in the `/utils` directory
> feat: move utils to new logger

- package.json
- src/components/backup/BackupCloudStep.js
- yarn.lock
replacing [zxcvbn](https://www.npmjs.com/package/zxcvbn) with [check-password-strength](https://www.npmjs.com/package/check-password-strength) since its such a large package and to keep parity with BX
context: https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1670881743447599
> chore: replace password checker

- src/App.js
Noticed we swallow some deeplink errors. Also replaced the old logger while I was at it.
> fix: replace logging and add error log to deeplinks

- src/resources/nfts/index.ts
- src/resources/nfts/simplehash/index.ts
- src/screens/WalletScreen/index.tsx
> feat: test out infinite query

- src/screens/AddCash/providers/Ramp/index.tsx
> fix: update Ramp fees

- src/components/coin-row/SendCoinRow.js
- src/components/send/SendAssetForm.js
- src/screens/SendConfirmationSheet.tsx
- src/screens/SendSheet.js
Fixes RNBW-4676
logic is handled in the hook now so we just want to pass the whole asset in and let it do the rest
https://cloud.skylarbarrera.com/Screen-Recording-2023-03-14-15-04-03.mp4
> chore: fix send asset colors

- android/app/src/main/java/me/rainbow/MainApplication.java
- src/navigation/Routes.android.js
- src/screens/AddCash/index.tsx
- src/screens/AddCash/providers/Ramp/index.tsx
- src/utils/authentication.ts
fixes APP-489
plaid package was getting loaded twice and causing issues: https://github.com/plaid/react-native-plaid-link-sdk/pull/306#issuecomment-1458940785
fixed an issue with the isAuthenticated logic that didnt handle android devices properly as well as a edge case where the user has only imported a watch wallet and wants to fund that wallet (no pin set up yet)
https://cloud.skylarbarrera.com/Screen-Recording-2023-03-15-16-38-43.mp4
lfg
> f2c: ratio android

- ios/Podfile.lock
- package.json
- src/handlers/cloudBackup.ts
- src/hooks/useManageCloudBackups.ts
- src/languages/_english.json
- src/languages/_french.json
- src/redux/additionalAssetsData.ts
- src/redux/wallets.ts
- src/screens/SettingsSheet/components/BackupSection.tsx
- src/screens/SettingsSheet/components/GoogleAccountSection.tsx
- src/screens/SettingsSheet/components/MenuItem.tsx
- src/screens/SettingsSheet/index.tsx
- yarn.lock
* change backups section behavior to always open a wallet list (to make space for the google account element)
* Add google account switcher in the backups settings section
> Google account switching for Google Drive backups

- src/utils/walletConnect.ts
Fixes APP-491
Hit this twice in testing, so maybe needs some more time for deeplinks.
> fix: increase pairing timeout

- src/utils/walletConnect.ts
Whoopsies their docs were wrong again 🙃 Did some CURLs with Wayne and this should handle errors for us.
> [WC v2] fix: remove red herring error log

- src/languages/_english.json
- src/languages/_french.json
Cherrypicked typo fixes made by @omahs in #4593
> Translations typo fixes

- src/screens/TransactionConfirmationScreen.js
> fix: handle ledger/wc rejection first before closing screen

- src/hooks/useLedgerConnect.ts
- src/utils/ledger.ts
Fixes APP-519
added some more error reporting so we get more logs in sentry, confident we have enough logging already just want to make sure we get them
n/a
n/a
> ledger: add more reporting

- src/hooks/useImportingWallet.ts
- src/screens/SettingsSheet/components/SettingsSection.tsx
- src/screens/hardware-wallets/PairHardwareWalletAgainSheet.tsx
Fixes APP-499
added handling for missing back up related handling, also removed the hardcoded ledger #
n/a
n/a
> ledger: back up clean up

- src/hooks/useLedgerConnect.ts
- src/hooks/useLedgerImport.ts
- src/languages/_english.json
- src/languages/_french.json
- src/screens/hardware-wallets/PairHardwareWalletAgainSheet.tsx
- src/screens/hardware-wallets/PairHardwareWalletSigningSheet.tsx
- src/utils/ledger.ts
added some extra handling for import flow to retry connecting without xtra user input
fixed some styling tings
moved some debug logs to info logs to prepare for release
n/a
n/a
> ledger: final lil tweeks

- package.json
- yarn.lock
> audit: vm2

- audit-ci.jsonc
Fixes APP-541
ignoring for now since there is no patched version
> ignore xml2js

- src/screens/AddCash/providers/Ratio/index.tsx
> fix: update ratio fees

- package.json
- yarn.lock
Fixes APP-540
they released an update that fixes 
https://github.com/advisories/GHSA-xj72-wvfv-8985
> audit vm2: patch it 

- src/redux/wallets.ts
Change `logger.sentry` to `logger.info` everywhere where we are not handling errors and to `logger.error` everywhere where we are actually handling errors
> Refactor wallet.ts to use new logger

- audit-ci.jsonc
- package.json
- yarn.lock
> @benisgold/rctest2

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> version bump 1.8.17 / 169

- src/components/backup/RestoreCloudStep.js
- src/handlers/cloudBackup.ts
* Brings Terry's changes over on top of PIN code changes
* Makes sure local backup file path is always correct
> Fix issue with Error Code 2 when backing up caused by filepath mismatch

- package.json
- yarn.lock
Fixes APP-558
Same library, prev patch also vuln: https://github.com/advisories/GHSA-ch3r-j5x3-6q2m
> fix: patch vm2

- CODEOWNERS
Removing Bruno and Esteban from Codeowners files for now
> Remove Bruno and Esteban from CODEOWNERS file for now

- src/redux/data.ts
Fixes APP-531
This PR debounces requests to the Ratio API to ideally AT MOST one every 10 seconds. This handling here gets peppered with many requests in quick succession sometimes, so more than one every 10 seconds might happen. But this should be better than it was.
I tested this by building locally and making a few purchases through Ratio.
> fix: debounce Ratio API lookups

- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- src/featuresToUnlock/unlockableAppIcons.ts
> fix podfile test

- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
This reverts commit 59c97513117d276885f4d7f87ca745433ce160d6.
Fixes APP-####
> Revert "Fix develop (#4806)"

- src/analytics/__mocks__/index.ts
- src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
- src/components/cards/EthCard.tsx
- src/components/coin-row/BalanceCoinRow.js
- src/components/expanded-state/asset/ChartExpandedState.js
- src/handlers/__tests__/deeplinks.test.ts
- src/handlers/deeplinks.ts
- src/helpers/utilities.ts
- src/helpers/validators.ts
- src/redux/__mocks__/store.ts
- src/screens/discover/components/DiscoverSearch.js
- src/screens/discover/components/ListsSection.js
- src/testing/utils.ts
- src/utils/__mocks__/delay.ts
- src/utils/delay.ts
- src/utils/profileUtils.ts
> feat: deeplinks unit tests

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS v1.8.18 & android 171
> Version bump iOS v1.8.18 & android 171

- src/screens/TransactionConfirmationScreen.js
Fixes APP-456
adding network field
> analytics: walletconnet network property

- e2e/swapSheetFlow1.spec.js
- src/components/expanded-state/swap-settings/SwapSettingsState.js
- src/hooks/useSwapCurrencyHandlers.ts
- src/screens/ExchangeModal.tsx
Fixes APP-556
app catching up with backend/sdk changes, output based quotas are now supported so just removing the logic that was changed to handle this difference 
https://user-images.githubusercontent.com/29204161/236516651-631b64f7-4fed-48fb-898e-c75ab4bcab70.mov
> swaps:  arbitrum output based quotes

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS v1.8.19 & android 172
> Version bump iOS v1.8.19 & android 172

- src/screens/TransactionConfirmationScreen.js
> fix: only send tx hash in response to sendTransaction

- package.json
- src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
- src/utils/CoinIcons/CoinIcon.js
- yarn.lock
Fixes APP-598
removing the react coin icon which uses token symbol matching instead of addresses
> rm coin icon package

- src/logger/sentry.ts
> Update release string for sentry sourcemaps auto mapping

- src/components/AddFundsInterstitial.js
- src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
- src/components/sheet/sheet-action-buttons/BuyActionButton.js
- src/languages/_english.json
- src/languages/_french.json
> Remove deprecated wyre related flags

- src/languages/_english.json
- src/languages/_french.json
- src/screens/WalletConnectApprovalSheet.js
- src/utils/__mocks__/ethereumUtils.ts
- src/utils/ethereumUtils.ts
> Remove deprecated cryptoscams db

- package.json
- yarn.lock
Fixes APP-608
https://github.com/advisories/GHSA-whpj-8f3w-67p5
> fix: patch vm2 for audit

- src/screens/AddCash/providers/Moonpay/index.tsx
> fix: update MoonPay fees

- package.json
- src/parsers/transactions.ts
- src/raps/unlockAndCrosschainSwap.ts
- yarn.lock
Fixes APP-####
See https://github.com/rainbow-me/swaps/pull/36 
- Tested ARB -> OP swap and OP->ARB swap (where token approval is involved). All good.
> fix: update swaps to 0.4.0

- src/screens/AddCash/index.tsx
> bump moonpay ranking

- package.json
- yarn.lock
> Fix socket.io vulnerability

- src/languages/_english.json
- src/languages/_french.json
- src/screens/SettingsSheet/components/DevSection.tsx
> clear txs: fix dev item copy and icon

- src/handlers/cloudBackup.ts
- src/handlers/dispersion.ts
- src/handlers/web3.ts
- src/keychain/index.ts
- src/model/preferences.ts
- src/notifications/tokens.ts
- src/utils/branch.ts
- src/walletConnect/index.tsx
Just cleaning a few things up. I think we should move towards using `warn` for errors we want to observe and track, and reserving `error` levels for critical bugs that need to be fixed. That way we can filter in the GUI for real (unexpected) issues.
> A few Sentry cleanups

- package.json
- src/model/config.ts
- src/resources/f2c/index.ts
- src/screens/AddCash/components/ProviderCard.tsx
- src/screens/AddCash/index.tsx
- src/screens/AddCash/providers/Coinbase/index.tsx
- src/screens/AddCash/providers/Moonpay/index.tsx
- src/screens/AddCash/providers/Ramp/index.tsx
- src/screens/AddCash/providers/Ratio/index.tsx
- src/screens/AddCash/types.ts
- yarn.lock
Fixes APP-366
Hooks up the app to the F2C API. The API simply returns the configs that we've had in the app for months. No geolocation or anything, but it'll help us change copy and stuff faster. Plus, adding geolocation and translations is pretty easy from this point.
https://github.com/rainbow-me/rainbow/assets/4732330/33a009d0-e025-43b0-87cd-0127d46f0848
> [F2C] hook up F2C API

- src/screens/Diagnostics/index.tsx
Was getting a cannot read property of undefined error. Might help 662 🤷
> fix: smol wd sheet bug

- globals.d.ts
- src/graphql/config.js
- src/graphql/index.ts
- src/graphql/utils/getFetchRequester.ts
Fixes APP-661
Integrates a simple authorization scheme for our Arc clients.
> feat: add api key header to arc clients

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.22
> Version bump iOS & Android v1.8.22

- audit-ci.jsonc
> audit ignore word-wrap

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.23
> Version bump iOS & Android v1.8.23

- src/components/expanded-state/swap-details/SwapDetailsMasthead.js
- src/components/large-countdown-clock/LargeCountdownClock.tsx
Fixes APP-673
https://cloud.skylarbarrera.com/Screen-Shot-2023-06-27-19-07-50.77.png
> fix:  swap masthead arrows

- src/screens/SettingsSheet/components/AlreadyBackedUpView.tsx
Fixes APP-672
https://cloud.skylarbarrera.com/Screen-Shot-2023-06-27-17-32-49.76.png
> fix back up to google drive

- e2e/hardhatTransactionFlowSendAndWC.spec.js
> disable wc v1 tests for now

- src/components/cards/NFTOffersCard/Offer.tsx
- src/components/cards/NFTOffersCard/index.tsx
- src/components/nft-offers/SortMenu.tsx
- src/design-system/color/palettes.ts
- src/helpers/utilities.ts
- src/languages/_english.json
- src/languages/_french.json
- src/resources/nftOffers/index.ts
- src/screens/NFTOffersSheet/OfferRow.tsx
- src/screens/NFTOffersSheet/index.tsx
- src/screens/NFTSingleOfferSheet/index.tsx
Fixes APP-####
* filter out expired offers every 1 min by resetting react query cache. this automatically triggers a rerender of dependent components
* had to hardcode a height into an offers card component bc it seems to get clipped like 1 render out of every 10
* added logic to animate out the offers card if their are no offers. ex: a user has 1 offer but then it expires
* added fallback component on nft offers sheet if user somehow has 0 offers here. added refresh button that allows user to invalidate query cache if age of data is older than 30s (to prevent spamming)
* UPDATED GLOBAL RDS COLORS (they were just incorrect???? fixed based on https://www.figma.com/file/wFXhL8ZcaBnIlWSSQTLWPA/RDS-Core?type=design&node-id=120%3A21&mode=design&t=hRZ9Y3Eadoj1Nwtn-1)
* updated some image …
> NFT Offers: finishing touches

- src/screens/SendSheet.js
we were checking on chain balances for nfts like they were erc20s and it was causing issues
proof of send: https://cloud.skylarbarrera.com/Screen-Shot-2023-06-30-14-22-00.89.png
> send: fix nft sends

- src/analytics/event.ts
- src/components/cards/NFTOffersCard/Offer.tsx
- src/screens/NFTOffersSheet/OfferRow.tsx
- src/screens/NFTSingleOfferSheet/index.tsx
Fixes APP-####
* added version number
* added token id
> NFT Offers: updated analytics

- src/screens/AddCash/providers/Ratio/index.tsx
- src/utils/emailRainbow.ts
Fixes APP-####
switching over support emails to ratio as requested
> f2c: switch over 2 ratio support

- src/networks/zora.ts
Skylar tested and confirmed this works
> feat: Enable zora swaps/bridging

- src/components/positions/PositionsCard.tsx
- src/hooks/useScanner.ts
- src/languages/_english.json
- src/languages/_french.json
- src/redux/data.ts
- src/redux/explorer.ts
- src/resources/defi/types.ts
- src/resources/defi/utils.ts
- src/screens/mints/PoapSheet.tsx
- src/screens/positions/SubPositionListItem.tsx
Fixes APP-688 APP-695 APP-691 APP-693 APP-694
fixes poap crash, unrecognized qr, + lab mismatch
fixes position erc20 filtering and adds proper l2 coin icons
> @skylar/rc fixes

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.25
> Version bump iOS & Android v1.8.25

- src/hooks/useScanner.ts
fixes an issue where POAP uses POAP.xyz instead of poap.xyz
> lowercase poap checks

- src/handlers/web3.ts
- src/parsers/requests.js
- src/screens/TransactionConfirmationScreen.js
- src/utils/ethereumUtils.ts
we were padding gas data to estimate gas bc we were overwriting the tx object in a few places
also currentNetwork and provider were sometimes undefined which causes us to estimate on mainnet for L2s
> WC: fix gas estimation issues

- src/handlers/assets.ts
- src/hooks/useGas.ts
- src/hooks/useMaxInputBalance.ts
- src/hooks/useSwapInputHandlers.ts
- src/utils/ethereumUtils.ts
Fixes APP-660
native assets were hardcoded and missed for base + zora, removed the hardcoded refs in favor of the new network config
max sends on base or zora
> send: fix max send on base & zora 

- src/components/L2Disclaimer.js
- src/components/coin-icon/ChainBadge.js
- src/components/expanded-state/UniqueTokenExpandedState.tsx
fixed dark mode issue with chain badge in a dark context
fixed properties display issue if the only properties were null
> ui bugs: mike nft tings

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.26
> Version bump iOS & Android v1.8.26

- CODEOWNERS
> codeowners updates

- package.json
- yarn.lock
Tested on testflight and confirmed behavior
> feat: Upgrade swaps to 0.5.0 for lower bridging costs

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.27
> Version bump iOS & Android v1.8.27

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.28
> Version bump iOS & Android v1.8.28

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.8.29
> Version bump iOS & Android v1.8.29

- src/screens/TransactionConfirmationScreen.js
> wc: fix cancel button

- src/components/send/SendAssetForm.js
Fixes APP-723
add back the keyboard area
https://cloud.skylarbarrera.com/Screen-Shot-2023-08-15-11-20-24.31.png
> add back keyboard area

- src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
- src/resources/nfts/utils.ts
- src/screens/NFTSingleOfferSheet/index.tsx
> Get NFT expanded state floor price from Reservoir if available

- src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
fixes chart haptics crash from RN bump
> charts: haptics fix

- src/App.js
> appstate: optional chaining

- src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
- src/components/asset-list/RecyclerAssetList2/WrappedPositionsListHeader.tsx
- src/components/expanded-state/unique-token/ZoomableWrapper.android.js
- src/components/expanded-state/unique-token/ZoomableWrapper.js
- src/components/images/ImgixImage.tsx
- src/hooks/useUniqueToken.ts
rm fast image to prevent crashes
> perf: images

- package.json
- src/resources/nftOffers/utils.ts
- src/screens/NFTSingleOfferSheet/index.tsx
- yarn.lock
> Fix L2 offers

- src/components/coin-icon/CoinIcon.tsx
- src/components/coin-icon/CoinIconFallback.js
> swaps: use fastcoinicon

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- Turn on gif support
- Fix Base swaps
- Fix cache key
> Version bump 1.9.2

- src/networks/base.ts
> base: reenable swaps

- src/components/coin-icon/ChainBadgeSizeConfigs.ts
- src/components/expanded-state/CustomGasState.js
- src/components/expanded-state/custom-gas/FeesPanel.tsx
- src/components/gas/GasSpeedButton.js
- src/entities/gas.ts
- src/handlers/web3.ts
- src/helpers/gas.ts
- src/hooks/useGas.ts
- src/networks/arbitrum.ts
- src/networks/base.ts
- src/networks/optimism.ts
- src/networks/zora.ts
- src/parsers/gas.ts
- src/raps/actions/swap.ts
- src/redux/gas.ts
- src/screens/ExplainSheet.js
> gas: 1559 for l2s

- src/components/backup/BackupCloudStep.js
- src/components/coin-row/FastTransactionStatusBadge.tsx
- src/components/expanded-state/custom-gas/FeesPanelTabs.tsx
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
- src/components/gas/GasSpeedButton.js
- src/helpers/assets.ts
- src/helpers/buildTransactionsSectionsSelector.tsx
- src/helpers/support.ts
- src/helpers/transactionActions.ts
- src/helpers/transactions.ts
- src/helpers/walletConnectNetworks.ts
- src/hooks/useWalletCloudBackup.ts
- src/languages/_english.json
- src/languages/_french.json
- src/languages/index.ts
- src/notifications/permissions.ts
- src/parsers/accounts.js
- src/raps/common.ts
- src/screens/AddCash/components/ProviderCard.tsx
- src/screens/AddCash/index.tsx
- src/screens/SettingsSheet/components/notificationAlerts.ts
- src/screens/SpeedUpAndCancelSheet.js
- src/screens/discover/DiscoverScreen.tsx
- src/screens/transaction-details/helpers/formatTransactionDetailsDate.ts
- src/utils/emailRainbow.ts
- src/utils/gas.ts
> i18n: missing strings

- src/screens/LearnWebViewScreen.tsx
Fixes APP-####
- moved injected JS outside of WebView to const
- moved to useMemo for performance
- sometimes there was a delay between the webview loading and the styles loading. moving to injecting css stylesheet seemed to fix this
- fixed darkmode text colors (has been broken a long time)
- fixed the height issue (large amounts of blank space at bottom / some content cut off at bottom)
CURRENT DEVELOP / APP STORE EXPERIENCE:
<div style={display:flex}>
</div>
WITH MY FIXES:
<div style={display:flex}>
</div>
Make sure card content looks good. shouldn't impact anything else.
> Small fixes to Learn Cards

- src/featuresToUnlock/featureUnlockChecks.ts
- src/featuresToUnlock/unlockableAppIcons.ts
Fixes APP-####
https://rainbowhaus.slack.com/archives/C0468CDBE75/p1693521091944319
> Support more fini nfts for app icon unlock

- src/resources/nftOffers/utils.ts
this will give us better on chain tracking for our offer txs
> nfts: add reservoir source

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.9.3
> Version bump iOS & Android v1.9.3

- src/walletConnect/index.tsx
removed some object deconstruction, using optional chaining with a fallback now 
added some error handling so we get reporting on any issues that come up here since this is an integral part of the app
> wc: optional chaining & error handling

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.9.4
> Version bump iOS & Android v1.9.4

- src/components/coin-icon/CoinIconFallback.js
- src/utils/CoinIcons/CoinIcon.js
before: https://cloud.skylarbarrera.com/Screen-Recording-2023-09-19-15-37-35.mp4
after: https://cloud.skylarbarrera.com/Screen-Recording-2023-09-19-15-36-38.mp4
> icons: fix text fallback

- src/utils/ethereumUtils.ts
Fixes APP-767
we use asset types for networks and that's no good, added handling for `compound` asset type
https://cloud.skylarbarrera.com/Screen-Shot-2023-09-22-11-48-25.59.png
> send: fix cToken network type

- src/languages/en_US.json
- src/navigation/Routes.android.tsx
- src/navigation/Routes.ios.tsx
- src/screens/SendConfirmationSheet.tsx
Fixes APP-####
- removed network checkbox
- reworded the other checkbox from `"The person I’m sending to has a wallet that supports %{networkName}",` to `"The address I’m sending to supports %{networkName}",`
- fixed some linting errors
- unsure if i need to make more changes to other lang docs
- sending on L2s works fine
- checkboxes go away if sends to a certain address on that network is > 3
> Remove exchange checkbox, reword other checkbox, fix some linting (fixes [APP-771])

- src/components/qrcode-scanner/EmulatorPasteUriButton.js
- src/components/transaction/TransactionMessage.js
- src/parsers/requests.js
- src/walletConnect/index.tsx
> Updates to personal_sign and fix QR code paste emulator button

- src/screens/TransactionConfirmationScreen.js
Fixes APP-768
2 year old bug from when we added L2 support 
we now prioritize the requests asset and fallback to native if we don't have any info 
https://cloud.skylarbarrera.com/IMG_59B5B59B7DA6-1.jpeg
make sure the wallet you use has 20 usdc in it
can connect here: https://drops-csnm0duda-rainbowdotme.vercel.app/drops/zorb
and press the send me money button 😉
> wc: transfer token display

- src/App.js
this has been an issue for a bit, we fixed in an old RC but never on develop and it got forgotten 
fixes a crash
> crash: fix unmount error

- src/handlers/nftOffers.ts
- src/references/ethereum-units.json
- src/screens/NFTSingleOfferSheet/index.tsx
Fixes APP-####
arc pr: https://github.com/rainbow-me/arc/pull/245
> nft offers: support additional networks

- src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
small regression been around for a bit 
before: https://cloud.skylarbarrera.com/Screenshot-2023-09-26-at-5.32.05-PM.png
after: https://cloud.skylarbarrera.com/Screenshot-2023-09-26-at-5.31.59-PM.png
> ui: fix swap percents formatting

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS & Android v1.9.5
> Version bump iOS & Android v1.9.5

- package.json
- yarn.lock
> audit: get-func-name

- audit-ci.jsonc
> More audit updates

- src/walletConnect/index.tsx
> Fallback to supported session events for wallet in WC v2

- src/handlers/deeplinks.ts
- src/hooks/useScanner.ts
Fixes APP-833
context is in the ticket 
https://cloud.skylarbarrera.com/Screen-Recording-2023-10-02-20-54-27.mp4
web profiles should open in the app as expected
> links: fix profiles

- src/handlers/__tests__/deeplinks.test.ts
this was merged without looking at e2e: https://github.com/rainbow-me/rainbow/pull/5088
this fixed the failing unit tests
> tests: fix deeplink tests

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> Bump Android & iOS to v1.9.6

- src/languages/en_US.json
- src/walletConnect/index.tsx
Minor tweaks to help make the error messages to users for walletconnect v2 clearer
> Improvements to the WC v2 error messages we show to users

- src/redux/data.ts
- src/resources/f2c/index.ts
> Cleanup unnecessary fetching for ratio txn history which is causing errors in Sentry

- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Fixes APP-852
Additional context in ticket
> Bump react-native-community/blur to fix a crash for some Android users

- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
Introduces some .vscode configuration to run Android outside of Studio
> feat: add vscode android launch files

- .github/workflows/macstadium-e2e.yml
- e2e/deeplinks.spec.js
- package.json
- src/hooks/useImportingWallet.ts
- yarn.lock
A few tests from deeplinks.spec.js are failing consistently. Disabled the tests allowing automated tests to pass
> skip failing tests + detox upgrade

- package.json
- yarn.lock
> audit: babel & undici

- src/migrations/index.ts
- src/migrations/migrations/fixHiddenUSDC.ts
- src/migrations/types.ts
manually removes usdc from the current wallets hidden tokens 
https://cloud.skylarbarrera.com/Screen-Recording-2023-10-18-13-23-19.mp4
> migration: fix hidden usdc

- src/resources/assets/UserAssetsQuery.ts
- src/resources/assets/assets.ts
> assets: rm scam url filter

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> Bump Android & iOS to v1.9.7

- src/components/exchange/NetworkSwitcherv2.tsx
- src/networks/index.ts
Should fix APP-856 along with a flash when switching networks
removed some over engineering on my part 🙂
> networks: rm override

- src/helpers/buildWalletSections.tsx
Fixes APP-859
just fixing the sorting of positions
> positions: sort by value

- README.md
> readme: update download links

- src/components/asset-list/RecyclerAssetList2/index.tsx
- src/languages/en_US.json
- src/screens/ConnectedDappsSheet.js
Fixes APP-874
there was an issue with showing connected dapps showing/visibility updating especially within the contextMenu
we're just gonna always show the option so I added an empty state: https://cloud.skylarbarrera.com/Screen-Shot-2023-10-23-13-19-18.75.png
> wc: always show connected dapps

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> bump iOS & Android to v1.9.8

- src/screens/mints/MintSheet.tsx
Fixes APP-882
adding a buffer to the tx fee we use to calculate sufficient native balances 
more info in the ticket
> mints: add tx fee buffer

- ios/Rainbow.xcodeproj/project.pbxproj
- src/walletConnect/index.tsx
Removes app review prompt during wallet connect flow.
Ref: https://rainbowhaus.slack.com/archives/C0468CDBE75/p1698290750950599
> remove prompt during wallet connect flow. it's not feasible

- src/screens/mints/MintSheet.tsx
This reverts commit 8224e4cf8d83078f55d62c4b511508cadff1c134.
Merged too soon
> Revert "mints: l1fee + value fix (#5162)"

- package.json
- yarn.lock
> audit: browserify-sign

- package.json
- src/languages/en_US.json
- src/resources/reservoir/client.ts
- src/screens/mints/MintSheet.tsx
- yarn.lock
Fixes APP-886 APP-885
dont need to do any value calc since the lib does it for us, previously this wasn't memoized so it was causing the effect to trigger a bunch. this was causing us to spam reservoir and led to us getting 4xx errors
I also fixed a smol issue with the mintAvailable check so we're more optimistic about mints being open if we are missing some information, gas estimation errors will handle disabling if they are not mintable
I also tweaked the mint.fun branding as they requested it be lowercase
> mints: l1fee + value fix

- package.json
- shim.js
- src/components/info-alert/info-alert.tsx
- src/graphql/queries/metadata.graphql
- src/languages/en_US.json
- src/redux/walletconnect.ts
- src/resources/metadata/dapp.ts
- src/screens/WalletConnectApprovalSheet.js
- src/utils/connectedApps.ts
- src/walletConnect/index.tsx
- src/walletConnect/sheets/AuthRequest.tsx
- yarn.lock
Fixes APP-879 APP-878 APP-877
scam: https://cloud.skylarbarrera.com/Screen-Shot-2023-10-23-14-02-29.97.png
verified: https://cloud.skylarbarrera.com/Screen-Shot-2023-10-23-14-02-48.12.png
> WC: dapp warnings

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> bump iOS & Android to v1.9.9

- src/screens/TransactionConfirmationScreen.js
- src/utils/methodRegistry.ts
Fixes APP-904
just adding non mainnet network support
> WC: methodRegistry on all networks

- src/languages/en_US.json
- src/parsers/requests.js
- src/screens/TransactionConfirmationScreen.js
- src/utils/signingMethods.ts
- src/walletConnect/index.tsx
- src/walletConnect/types.ts
Fixes APP-904
Adding back eth_sign but with no real functionality 
wallertconnect will reject those requests immediately 
are info in the ticket/slack thread
> WC: enabled eth_sign but only for connections

- src/utils/reviewAlert.ts
bumping the threshold so it doesn't get hit by new users
> reviews: bump watch wallet threshold

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> bump iOS & Android to v1.9.10

- package.json
- src/screens/NFTSingleOfferSheet/index.tsx
- src/screens/mints/MintSheet.tsx
- yarn.lock
Fixes APP-918
bump axios and also bumped the reservoir client which is the culprit here
> audit: axios + reservior client bump

- src/hooks/useSwappableUserAssets.ts
> Fix: Infinite render bug on swaps modal

- src/components/asset-list/RecyclerAssetList2/profile-header/ProfileActionButtonsRow.tsx
> revert onpress

- src/config/experimental.ts
> add experimental flag for remote cards

- src/App.js
- src/components/cards/remote-cards/RemoteCardProvider.tsx
- src/components/cards/remote-cards/index.ts
- src/graphql/config.js
- src/graphql/queries/arc.graphql
- src/resources/cards/cardCollectionQuery.ts
- src/resources/cards/cardQuery.ts
- src/storage/index.ts
- src/storage/schema.ts
> [APP-929]: Add `RemoteCardProvider` and react-query calls

- src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
- src/components/cards/remote-cards/RemoteCard.tsx
- src/components/cards/remote-cards/RemoteCardProvider.tsx
- src/components/cards/remote-cards/index.ts
> [APP-930]: Add `<RemoteCard />` component

- globals.d.ts
- src/graphql/utils/getFetchRequester.ts
> chore: supply metadata graphql api key

- scripts/eas-build-pre-install.sh
> fix: prebuild.sh files not working with eval

- scripts/eas-build-pre-install.sh
> [APP-940]: Add `.easignore` creation step

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
- package.json
- patches/react-native-tcp+4.0.0.patch
- scripts/eas-build-pre-install.sh
- yarn.lock
> Android Expo build

- src/screens/SignTransactionSheet.tsx
enabling tx sim for zora network
> tx sim: enable zora

- src/languages/en_US.json
- src/screens/SignTransactionSheet.tsx
Fixes APP-939
added warnings to tx sim
https://cloud.skylarbarrera.com/Screen-Shot-2023-12-06-17-02-58.40.png
> tx sim: warnings

- src/screens/points/content/ReferralContent.tsx
- src/screens/points/content/console/calculate.tsx
> [APP-972]: Fix back button being under the bottom tab bar

- src/components/asset-list/RecyclerAssetList2/FastComponents/FastBalanceCoinRow.tsx
- Fixes a crash that occasionally happened when switching wallets
> Fix intermittent wallet switching crash

- src/screens/points/constants.ts
> add a hardcoded version of tweet intent to build copy

- src/screens/points/content/ReferralContent.tsx
> [APP-977]: Fix Android referral code placeholder color on dark mode

- src/model/config.ts
> points flag = true

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Version bump iOS and Android to v1.9.12
> Version bump iOS and Android to v1.9.12

- src/screens/points/content/ReferralContent.tsx
Fixes APP-992
Prevent input autofocus if referral code is already validated
https://www.loom.com/share/605b24e76b4b45b8aae74ad5e16fdf2f
https://www.loom.com/share/a913fe0edc7e40a383a796b73f0d5803
> Points: fix keyboard hiding "get started" button after deeplink

- src/screens/points/constants.ts
Fixes APP-1005
rm rainbow emojis from tweet intent bc they look sus
> Points: rm rainbow emojis from tweet intent

- src/screens/points/content/PointsContent.tsx
> [APP-1004]: Hide referral section on watched wallets

- src/components/remote-promo-sheet/RemotePromoSheetProvider.tsx
- src/components/remote-promo-sheet/check-fns/hasOnboardedPoints.ts
- src/components/remote-promo-sheet/check-fns/index.ts
- src/model/config.ts
> add points check fn and enable remote config promo sheets

- src/components/walletconnect-list/WalletConnectV2ListItem.tsx
> [APP-1018]: Fix displaying WalletConnect v2 list items that don't have an icon

- src/model/wallet.ts
- src/screens/points/contexts/PointsProfileContext.tsx
> Points: refactor signIn

- src/screens/points/content/ReferralContent.tsx
> fix www.rainbow.me not being parsed from ref links

- src/languages/en_US.json
- src/screens/points/contexts/PointsProfileContext.tsx
Fixes APP-####
* currently we only handle known error types return from backend, all others will silently succeed. added support for handling unknown error types
* handle "NO_BALANCE" error type which backend plans on adding
see: https://rainbowhaus.slack.com/archives/C0348RZR952/p1702666964710699
> Points: handle NO_BALANCE error type + unknown error types during signIn

- src/screens/SendSheet.js
> [APP-1025]: fix: `.length` on undefined

- src/hooks/useSwappableUserAssets.ts
> [APP-1024]: Fix `.filter` on undefined

- src/App.js
- src/helpers/assets.ts
> Fix nft sort by floor price

- src/hooks/useSwappableUserAssets.ts
- src/networks/index.ts
> fix useSwappableUserAssets not including all networks

- src/hooks/useMaxInputBalance.ts
- src/screens/SendSheet.js
> [APP-1023]: Fix `.replace` on a number

- src/hooks/usePriceImpactDetails.ts
> [APP-1026]: Fix input/output token address undefined

- src/components/qrcode-scanner/QRCodeScanner.tsx
- src/screens/QRScannerScreen.tsx
> [APP-171]: Fix camera staying on issue

- src/resources/reservoir/client.ts
@skylarbarrera pointed out that this was originally added in https://github.com/rainbow-me/rainbow/pull/5035 but got lost somewhere
> chore: add reservoir source

- src/hooks/useInitializeWallet.ts
Fixes APP-1011
- Removed conditional to hideSplashscreen function
- added more logging to hopefully catch more of why this is happening.
> [APP-1011]: Fix Android splashscreen issue

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to 1.9.13
> bump iOS & Android to version to 1.9.13

- ios/Rainbow.xcodeproj/project.pbxproj
- src/migrations/index.ts
- src/migrations/migrations/setInitialBackupMethod.ts
- src/migrations/types.ts
- src/storage/index.ts
- src/storage/schema.ts
Fixes APP-1051
Added backups settings global config to be used in the new backups flow
> [APP-1051]: (feat): add backups global config

- src/featuresToUnlock/unlockableAppIcons.ts
they added the ability to migrate your old Smol to a new contract on chain, so i added the new contract address to the array to unlock icon.
> [APP-742] update smol contract address

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android versions to v1.9.14
> bump iOS & Android versions to v1.9.14

- package.json
- yarn.lock
> audit: follow-redirects

- package.json
- yarn.lock
> audit mmkv

- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Fixes APP-####
bumping this to fix xcode 15 crash
> bump react-native-linear-gradient

- src/notifications/settings/constants.ts
> rename points topic

- android/build.gradle
> bump android minSdkVersion

- CHANGELOG.md
- android/app/build.gradle
- ios/.xcode.env.local
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to v1.9.15
> bump iOS & Android version to v1.9.15

- src/components/exchange/ExchangeAssetList.tsx
- src/hooks/useSwapDerivedOutputs.ts
- src/screens/ExchangeModal.tsx
Fixes APP-1099
removing generic assets refs in swap flows 
swap flows should work normally
> assets: rm swaps generic asset refs

- src/components/exchange/ExchangeTokenRow.tsx
- src/hooks/useAccountAsset.ts
- src/hooks/useAsset.ts
Fixes APP-1107
cleaning up asset hooks,  useAsset has only been working for mainnet assets since day one 🤯 
we dont use the zeroETH shiz anymore so removing that as well
> @skylar/clean account asset

- src/handlers/swap.ts
- src/hooks/usePriceImpactDetails.ts
Reverts rainbow-me/rainbow#5351
> Revert "@skylar/price impact followup"

- src/handlers/swap.ts
- src/hooks/usePriceImpactDetails.ts
> @skylar/price impact followup

- src/hooks/useOnAvatarPress.ts
- src/hooks/usePriceImpactDetails.ts
account asset used to fallback to generic assets which is super weird, this just fixes the check that was crashing
> chore: fix zero eth check

- src/components/cards/NFTOffersCard/Offer.tsx
> offers: ignore network badge

- src/components/cards/remote-cards/RemoteCard.tsx
> Remote card icon fix

- src/components/backup/BackupCloudStep.tsx
- src/components/backup/RestoreCloudStep.tsx
- src/components/buttons/rainbow-button/RainbowButton.tsx
- src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
> @matthew/app 1135

- src/hooks/useSwapCurrencyList.ts
- src/screens/CurrencySelectModal.tsx
curated tokens have no data, this adds the data needed
curated tokens are only used for mainnet, rest are backend driven
> swaps: fix curated tokens

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> bump iOS & Android to v1.9.16

- src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
- src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
- src/screens/SettingsSheet/useVisibleWallets.ts
> add menu item being the entire context menu boundary

- src/languages/en_US.json
- src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
- src/screens/SettingsSheet/useVisibleWallets.ts
Fixes APP-1157 APP-1160
Changed Secret Phrase => Wallet Group to match BX. Also added numeric incrementing to match. This PR now also groups Secret Phrases and Private Keys together and pushes non-backed up of both wallet types to the top.
> @matthew/app 1157

- src/screens/SignTransactionSheet.tsx
Fixes APP-1163
showUSD wasnt a boolean and was causing issues
> txSim: price clean up

- src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
> ENS display changes + css tweaks

- package.json
- yarn.lock
> audit: undici

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> bump iOS & Android to v1.9.17

- src/languages/ar_AR.json
- src/languages/es_419.json
- src/languages/fr_FR.json
- src/languages/hi_IN.json
- src/languages/id_ID.json
- src/languages/ja_JP.json
- src/languages/ko_KR.json
- src/languages/pt_BR.json
- src/languages/ru_RU.json
- src/languages/th_TH.json
- src/languages/tr_TR.json
- src/languages/zh_CN.json
Fixes APP-####
- Points, Weekly Earnings updates
- Deprecated Card strings
- Notification strings
- New WalletConnect strings
> chore: i18n updates

- package.json
- yarn.lock
> deps: bump ip

- src/components/backup/useCreateBackup.ts
- src/hooks/useWalletCloudBackup.ts
- src/model/backup.ts
- src/screens/Diagnostics/index.tsx
- src/screens/SettingsSheet/components/Backups/ViewWalletBackup.tsx
- src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
> impl. backing up all wallets at once

- src/featuresToUnlock/featureUnlockChecks.ts
> farcaster icon fix

- src/components/rainbows-background/SingleRainbow.tsx
Fixes APP-1187
regression from https://github.com/rainbow-me/rainbow/pull/5433
> fix single rainbow animation

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS & Android version to v1.9.18
> Bump iOS & Android version to v1.9.18

- src/screens/SignTransactionSheet.tsx
> remove duplicate rows

- src/config/experimental.ts
- src/model/remoteConfig.ts
Fixes APP-1210
firebase + local feature flags
> Dapp browser feature flags

- src/components/coin-row/FastTransactionCoinRow.tsx
Fixes APP-1192
fixed approval number formatting
> txs: approval formatting

- src/components/fields/PasswordField.tsx
- src/languages/en_US.json
- src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
> Fix Android ShadowStack causing TextInputs to be funky... and not in a fun way

- src/screens/SettingsSheet/SettingsPages.ts
- src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
- src/screens/SettingsSheet/components/SettingsSection.tsx
- src/screens/SettingsSheet/utils.ts
> [FIX]: We're showing the option to back up on imported ledger wallet

- src/components/backup/ChooseBackupStep.tsx
- src/screens/SettingsSheet/components/Backups/ViewCloudBackups.tsx
Fixes APP-1201
Consumed hook for showing backups instead of passed route params which seemed to not be up to date accurately
> Older backups only show on welcome screen but not in settings

- src/components/secret-display/SecretDisplaySection.tsx
- src/handlers/authentication.ts
> Android only - previous back up with pin code requires a new creation each time to view

- src/hooks/useManageCloudBackups.ts
- src/hooks/useWalletCloudBackup.ts
- src/languages/en_US.json
- src/screens/SettingsSheet/components/Backups/WalletsAndBackup.tsx
Fixes APP-1205
Fixes APP-1199
Better userData handling around restoring what wallets are backed up to which google account
[Screen_recording_20240308_140049.webm](https://github.com/rainbow-me/rainbow/assets/6284525/cd0d54e0-ca16-43e7-8cd3-6900cda24878)
> Fixes to Android Google Account Management

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to v1.9.19
> bump iOS & Android version to v1.9.19

- src/components/walletconnect-list/WalletConnectV2ListItem.tsx
> wc: fix null deconstruction

- package.json
- yarn.lock
> Fix audit ci

- .gitignore
- scripts/postinstall.sh
> ignore webview changes correctly

- src/handlers/localstorage/theme.ts
- src/theme/ThemeContext.tsx
- Changes the default theme from light to system
> Default to system theme

- src/components/DappBrowser/AddressBar.tsx
- src/components/DappBrowser/BrowserTab.tsx
- src/components/DappBrowser/BrowserToolbar.tsx
- src/components/DappBrowser/DappBrowser.tsx
- src/components/DappBrowser/DappBrowserShadows.tsx
- src/components/DappBrowser/Dimensions.ts
- src/components/DappBrowser/WebViewBorder.tsx
- src/components/DappBrowser/address-bar/AccountIcon.tsx
- src/components/DappBrowser/address-bar/AddressInput.tsx
- src/components/DappBrowser/address-bar/TabButton.tsx
- src/design-system/components/Cover/Cover.tsx
- src/navigation/SwipeNavigator.tsx
- Some minor cleanup of the main browser UI
- Fixes webview sizing/padding
- Adds light mode
> Browser UI cleanup

- src/migrations/migrations/migratePersistedQueriesToMMKV.ts
> fix edge case where there may not be data inside of async storage

- CODEOWNERS
> Dapp Browser CODEOWNERS

- ios/Podfile.lock
- package.json
- patches/react-native-dark-mode+0.2.2.patch
- src/theme/ThemeContext.tsx
- yarn.lock
Fixes APP-####
Darkmode / light mode on Android / iOS
> Add react-native-dark-mode back

- src/components/DappBrowser/AddressBar.tsx
- src/components/DappBrowser/address-bar/AddressInput.tsx
- src/components/DappBrowser/address-bar/TabButton.tsx
- Fixes the `AddressBar` styles on Android
> Dapp Browser: Fix Android AddressBar styles

- src/screens/SignTransactionSheet.tsx
- src/utils/requestNavigationHandlers.ts
> wc: remove some logs 😅

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android versions to v1.9.20
> bump iOS & Android versions to v1.9.20

- src/state/browserState/index.test.ts
- src/state/browserState/index.ts
> init browser state

- src/components/DappBrowser/BrowserToolbar.tsx
- src/components/DappBrowser/Homepage.tsx
- src/components/DappBrowser/search-input/SearchInput.tsx
- src/state/favoriteDapps/index.test.ts
- src/state/favoriteDapps/index.ts
Fixes APP-1239 APP-1255
added fav state + menu 
https://github.com/rainbow-me/rainbow/assets/29204161/d1d045b7-ce4a-471f-bc5e-79e2207cb84e
> browser: favorites state + menu

- src/navigation/config.tsx
- src/screens/SignTransactionSheet.tsx
> browser: requests background color

- ios/Podfile.lock
- package.json
- yarn.lock
This resolves the issue with NaN values causing a crash.
> Bump Rudderstack version to v1.12.12

- src/hooks/useSearchCurrencyList.ts
- src/hooks/useSwapCurrencyList.ts
Fixes APP-1190
fixes token metadata issues for searching by contract address
> fix: search by contract address

- package.json
- src/handlers/swap.ts
- src/raps/actions/unlock.ts
- src/raps/unlockAndSwap.ts
- yarn.lock
> bump swaps sdk (inc. Blast & Zora support) #1442

- src/screens/SignTransactionSheet.tsx
> fix sheet bg

- src/screens/SignTransactionSheet.tsx
Fixes APP-1171
adds support for other native currencies in tx sim
> tx sim: other natives

- package.json
- yarn.lock
Fixes APP-1291
bumping swap sdk for blast + zora swaps
> swaps: bump sdk

- src/components/DappBrowser/BrowserContext.tsx
- src/components/DappBrowser/search-input/AccountIcon.tsx
Fixes APP-1260
https://github.com/rainbow-me/rainbow/assets/29204161/e072892f-ff17-4360-a94a-00fd77bc08ed
> browser: add account context menu

- src/components/DappBrowser/search-input/AccountIcon.tsx
- src/languages/en_US.json
Fixes APP-####
Hooked up all these actions to the provider:
- Connect / Disconnect working 
- Wallet switching working
- Network switching working
https://github.com/rainbow-me/rainbow/assets/1247834/9a2418ad-6273-4ea1-82f5-a7f5cd27d4fc
> make account network switcher work

- src/components/cards/remote-cards/RemoteCard.tsx
> fix scrolltoindex firing on last card dismissal

- src/components/DappBrowser/BrowserContext.tsx
- src/components/DappBrowser/DappBrowser.tsx
Fixes APP-####
From now on we can open any link in the dapp browser just by calling
```
navigate(Routes.DAPP_BROWSER_SCREEN, { url });
```
Here I'm calling `navigate(Routes.DAPP_BROWSER_SCREEN, { url: 'https://rainbow.me' });` 5 seconds after the app launches.
https://github.com/rainbow-me/rainbow/assets/1247834/a53c4569-cec8-4158-921c-3d4c95692651
> allow open in new tab

- package.json
- yarn.lock
> audit: phin

- src/walletConnect/index.tsx
Fixes APP-1276
fix remaining dapp metadata issues
> tx requests: metadata

- src/screens/SendSheet.js
Fixes APP-1195
checks current token to ensure user isnt sending to the contract address
> send: check contract address

- src/design-system/components/Heading/Heading.tsx
- src/design-system/components/Text/Text.tsx
ONE WARNING ON MOUNT IS ENOUGH
> so tired of this log

- src/components/SmoothPager.tsx
- src/components/animations/animationConfigs.ts
- Adds a new Reanimated-based pager component, which will be used by the browser control panel (demoed in the video below but coming in a second PR)
https://github.com/rainbow-me/rainbow/assets/7061887/55ccbe23-880a-4bd8-bc9b-a91d558b6523
> Browser: SmoothPager

- src/components/change-wallet/AddressRow.tsx
- src/hooks/useWalletBalances.ts
- src/hooks/useWalletsWithBalancesAndNames.ts
- src/languages/en_US.json
- src/resources/summary/summary.ts
> chore: use native currency balances

- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/__swaps__/screens/Swap/hooks/useSwapWarning.ts
> Cover a few more edge cases with showing the swap warnings

- src/App.js
moves the review prompt check inside of auth so unauthenticated users don't get prompted.
> review prompt changes

- src/__swaps__/screens/Swap/components/ReviewPanel.tsx
- src/__swaps__/utils/numbers.ts
- src/languages/en_US.json
> Add rainbow fee to review panel

- src/__swaps__/screens/Swap/components/ReviewPanel.tsx
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
> simplify logic for rainbow fee display in review panel

- src/hooks/useSyncSharedValue.ts
- Small fix to use the correct type for `sharedValue`
> useSyncSharedValue: type fix

- src/components/DappBrowser/BrowserTab.tsx
Fixes APP-####
Fixes the issue where google login button won't load on certain sites
https://github.com/rainbow-me/rainbow/assets/1247834/9e0cbd8a-72f1-42b3-8f11-f5d51c961b37
> use current safari UA

- src/components/DappBrowser/control-panel/ControlPanel.tsx
- src/components/DappBrowser/search-input/AccountIcon.tsx
- src/languages/en_US.json
- src/state/appSessions/index.ts
Fixes APP-####
Working but I will refactor the HomePanel component to make usage of the shared values instead of state variables.
https://github.com/rainbow-me/rainbow/assets/1247834/3c8ae1e1-d670-431a-85eb-ba4d82d01bd7
> Control panel for dapp browser

- src/components/DappBrowser/DappBrowser.tsx
- src/components/DappBrowser/screenshots.ts
- src/components/DappBrowser/types.ts
- src/state/browser/browserStore.ts
> fix screenshot prunning

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android versions to v1.9.23
> Bump iOS and Android versions to v1.9.23

- src/components/contacts/ContactRow.js
> APP-1384: fix wallet balance in send flow

- src/components/DappBrowser/BrowserTab.tsx
- src/components/DappBrowser/DappBrowser.tsx
- src/components/DappBrowser/types.ts
Fixes APP-####
- use the right user agent per platform
- handle injection natively
Blocked by two PRs on internal repos
> handle injection natively

- src/components/DappBrowser/control-panel/ControlPanel.tsx
- src/state/appSessions/index.ts
Fixes APP-####
- Fixes crash when trying to switch networks without a session
- Fixes bug where trying to switch network, the selection wasn't updating due to wrong selectors being cached
> Network switch fixes

- src/components/DappBrowser/control-panel/ControlPanel.tsx
- src/components/DappBrowser/handleProviderRequest.ts
- src/components/DappBrowser/search-input/AccountIcon.tsx
- src/state/appSessions/index.test.ts
- src/state/appSessions/index.ts
Fixes APP-1408
Partially Fixes APP-1449
- Refactor AppSessionsStore to use RainbowStore
- Fixes all the issues related to account / network switching
- The connection prompt doesn't show anymore when force connecting to a dapp
https://github.com/rainbow-me/rainbow/assets/1247834/f037d354-4e5c-4e78-9f80-67dc7e263b4e
> Connect Panel improvements

- src/entities/transactions/transaction.ts
- src/parsers/transactions.ts
- src/resources/transactions/types.ts
- src/screens/transaction-details/components/TransactionDetailsHashAndActionsSection.tsx
> add explorer_url and explorer_label to txn types and consume

- src/screens/LearnWebViewScreen.tsx
> fix: learn more webview clipped

- src/components/DappBrowser/BrowserTab.tsx
> browser: combine animated styles

- src/components/DappBrowser/BrowserTab.tsx
- src/components/DappBrowser/DappBrowser.tsx
Fixes APP-####
This is a hack but it works, will try to do it properly tomorrow.
> Open in new tab

- src/__swaps__/screens/Swap/Swap.tsx
- src/__swaps__/screens/Swap/components/FlipButton.tsx
- src/__swaps__/screens/Swap/components/SearchInput.tsx
- src/__swaps__/screens/Swap/components/SliderAndKeyboard.tsx
- src/__swaps__/screens/Swap/components/SwapActionButton.tsx
- src/__swaps__/screens/Swap/components/SwapBottomPanel.tsx
- src/__swaps__/screens/Swap/components/SwapInput.tsx
- src/__swaps__/screens/Swap/components/SwapInputAsset.tsx
- src/__swaps__/screens/Swap/components/SwapNumberPad.tsx
- src/__swaps__/screens/Swap/components/SwapOutputAsset.tsx
- src/__swaps__/screens/Swap/components/SwapSlider.tsx
- src/__swaps__/screens/Swap/components/TokenList/TokenList.tsx
- src/__swaps__/screens/Swap/hooks/useAnimatedSwapStyles.ts
- src/__swaps__/screens/Swap/hooks/useBottomPanelGestureHandler.ts
- src/__swaps__/screens/Swap/hooks/useSwapInputStyles.ts
- src/__swaps__/screens/Swap/providers/swap-provider.tsx
- src/__swaps__/types/assets.ts
- src/__swaps__/utils/swaps.ts
> Integrate new arch into asset colors

- src/screens/WalletConnectApprovalSheet.js
- src/walletConnect/index.tsx
- src/walletConnect/sheets/AuthRequest.tsx
> wc: rug verified context

- src/components/DappBrowser/Homepage.tsx
- src/components/DappBrowser/control-panel/ControlPanel.tsx
- src/components/DappBrowser/search-input/SearchInput.tsx
- src/resources/metadata/dapps.tsx
- src/screens/SignTransactionSheet.tsx
- improves dapp query to allow selectors
- switched the more button on the control panel to favorites 
- added the fetching of onchain native balances for the tx sheet to reduce stale data
- hide and resizes control panel when on the hompage
> browser: final fixes 

- src/__swaps__/screens/Swap/components/ExchangeRateBubble.tsx
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/__swaps__/types/assets.ts
- src/__swaps__/utils/swaps.ts
https://github.com/rainbow-me/rainbow/assets/6284525/687568c4-db79-4178-b1a2-6d4066bac5c2
> Exchange Rate Bubble

- src/components/DappBrowser/search/SearchContext.tsx
- src/components/DappBrowser/search/results/SearchResult.tsx
- src/components/DappBrowser/search/results/SearchResults.tsx
- src/resources/metadata/dapps.tsx
Fixes APP-1467
Uploading Simulator Screen Recording - iPhone 15 Pro - 2024-05-13 at 18.13.47.mp4…
> browser: fix direct search

- src/components/DappBrowser/control-panel/ControlPanel.tsx
Fixes APP-####
https://github.com/rainbow-me/rainbow/assets/1247834/e14e49ed-e355-4d89-8f89-59267d6ea2ad
> Fix account switching

- src/components/DappBrowser/control-panel/ControlPanel.tsx
- src/components/DappBrowser/search-input/AccountIcon.tsx
- src/utils/connectedApps.ts
- Fixes a crash that occurred when opening the control panel after creating/importing a wallet from a fresh install
> Browser: fix control panel crash

- ios/PrivacyInfo.xcprivacy
- ios/Rainbow.xcodeproj/project.pbxproj
- Adds a privacy manifest in accordance with: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
> Add privacy manifest

- src/components/DappBrowser/DappBrowserShadows.tsx
- src/components/DappBrowser/Homepage.tsx
- src/components/DappBrowser/TabViewToolbar.tsx
- src/components/DappBrowser/search/results/SearchResult.tsx
- src/components/DappBrowser/search/results/SearchResults.tsx
- src/components/DappBrowser/utils.ts
- src/components/icons/TabBarIcon.tsx
- src/navigation/SwipeNavigator.tsx
- src/utils/deviceUtils.ts
- Adds a basic homepage empty state
- Fixes dynamic tab bar positions and styles (e.g. when browser tab is enabled/disabled — was previously buggy)
- Improves light mode browser button shadows
- Improves search logic
- Fixes search result styles
> Browser: homepage empty state, search logic fixes

- src/resources/defi/PositionsQuery.ts
> Fix addys API error when no address is provided

- src/__swaps__/screens/Swap/components/TokenList/ChainSelection.tsx
- src/__swaps__/screens/Swap/components/TokenList/ListEmpty.tsx
- src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx
- src/__swaps__/screens/Swap/components/TokenList/TokenToBuySection.tsx
- src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts
- src/__swaps__/screens/Swap/providers/swap-provider.tsx
- src/components/backup/RestoreCloudStep.tsx
- src/state/swaps/swapsStore.ts
> Output ChainId Selection

- src/components/expanded-state/swap-settings/SourcePicker.js
- src/components/expanded-state/swap-settings/SwapSettingsState.js
Fixes APP-1479
thanks javascript
> rm references to old redux swaps const

- CODEOWNERS
> add myself to CO for PR approvals

- src/components/DappBrowser/DappBrowser.tsx
Fixes APP-####
We'll fix this properly later on but does the trick
https://github.com/rainbow-me/rainbow/assets/1247834/5792b23f-a161-4882-bcd1-76084475d914
> increase timeout to open in new tab

- src/__swaps__/screens/Swap/components/CoinRow.tsx
> Swaps: fix coin row layout issues

- src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts
- src/__swaps__/screens/Swap/resources/search/index.ts
Fixes APP-1369
* consolidated verified assets fetches + added stale/cache time
https://github.com/rainbow-me/rainbow/assets/15272675/8ff5eb46-8e05-4ba0-8570-5fcd18eeef17
> Swaps: Token to buy list performance

- src/__swaps__/screens/Swap/components/SwapInputAsset.tsx
- src/__swaps__/screens/Swap/components/SwapOutputAsset.tsx
> Fix icon sizing

- src/__swaps__/safe-math/SafeMath.ts
- src/__swaps__/safe-math/__tests__/SafeMath.test.ts
Fixes APP-####
Wrote basic math functions to safely deal with big numbers operations without any extra dependency (so it can be used in worklets).
Added tests including comparing results with BigNumber.js library which we know it's accurate
> add safe math fns

- src/__swaps__/screens/Swap/components/CoinRow.tsx
- src/__swaps__/screens/Swap/components/CoinRowButton.tsx
Fixes APP-1493
Prevents coin from being selected when being favorited/unfavorited
https://github.com/rainbow-me/rainbow/assets/15272675/4af01b6c-770c-41d1-8b66-4ae783fba441
https://github.com/rainbow-me/rainbow/assets/15272675/01d93845-a8a9-48bb-8bb0-198744b3cc47
> Swaps: fix favorite button press

- src/__swaps__/screens/Swap/components/CoinRow.tsx
- src/__swaps__/screens/Swap/components/CoinRowButton.tsx
- src/__swaps__/screens/Swap/components/SearchInput.tsx
- src/__swaps__/screens/Swap/hooks/useEstimatedGasFee.ts
- src/languages/en_US.json
Fixes APP-1527
https://github.com/rainbow-me/rainbow/assets/15272675/5c5e2710-4c13-4b1a-bc2f-182558cc9427
https://github.com/rainbow-me/rainbow/assets/15272675/b04231a5-e7dc-4075-a08c-e21a7092b77c
> Swaps: coin row info button

- src/__swaps__/screens/Swap/components/TokenList/TokenToBuySection.tsx
> remove limit from token to buy list

- src/__swaps__/utils/swaps.ts
> Fix Rounding Issue On Small Magnitude Decimals

- .github/workflows/macstadium-e2e.yml
> [e2e] install pods last

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to 1.9.26
> bump iOS & Android version to 1.9.26

- src/__swaps__/screens/Swap/components/ReviewPanel.tsx
- src/screens/ExplainSheet.js
> review panel wasn't awaiting a promise

- src/__swaps__/safe-math/SafeMath.ts
- src/__swaps__/safe-math/__tests__/SafeMath.test.ts
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/__swaps__/utils/swaps.ts
Fixes APP-1565
- Add support for small numbers (low prices) with negative exponents
- Fixes crash when the input value is `0.`
Vid shows all the 3 issues fixed
https://github.com/rainbow-me/rainbow/assets/1247834/f43741c5-17d8-45af-af4c-f4203cad140b
> more Safemath fixes

- src/__swaps__/types/search.ts
- src/__swaps__/utils/assets.ts
- src/components/sheet/sheet-action-buttons/SwapActionButton.tsx
> add type to SearchAsset type and add into type possibilities

- src/__swaps__/screens/Swap/components/ReviewPanel.tsx
> Fix wrong chain name in review panel

- src/__swaps__/screens/Swap/components/GasPanel.tsx
Fixes APP-1575
Adds base fee condition and removes the info icon on max transaction fee since we don't have spec for that.
> Add base fee condition to gas panel

- package.json
- yarn.lock
Fixes APP-####
Bump to fix vuln
> CI FIX - bump braces

- src/__swaps__/screens/Swap/components/AnimatedChainImage.tsx
> Fix chain badge not respecting pixel ratio on android

- src/__swaps__/screens/Swap/hooks/useSelectedGas.ts
> default to fast suggestion if custom gas is selected but not set

- src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes RNBW-4790
- added a try/catch block around the execution step to reset if we error
https://github.com/rainbow-me/rainbow/assets/6284525/49b18bdd-a495-417d-9155-39ba70d82f1c
> Fix isSwapping not being reset

- src/App.js
- src/__swaps__/screens/Swap/providers/swap-provider.tsx
- src/components/DappBrowser/handleProviderRequest.ts
- src/handlers/web3.ts
- src/helpers/validators.ts
- src/hooks/useENSRegistrationActionHandler.ts
- src/hooks/useENSRegistrationStepHandler.tsx
- src/hooks/useImportingWallet.ts
- src/hooks/useSearchCurrencyList.ts
- src/hooks/useSwapCurrencyList.ts
- src/hooks/useWatchPendingTxs.ts
- src/networks/types.ts
- src/raps/actions/crosschainSwap.ts
- src/raps/actions/swap.ts
- src/raps/actions/unlock.ts
- src/redux/explorer.ts
- src/redux/gas.ts
- src/resources/ens/ensAddressQuery.ts
- src/screens/ExchangeModal.tsx
- src/screens/SendSheet.js
- src/screens/SignTransactionSheet.tsx
- src/screens/SpeedUpAndCancelSheet.js
- src/screens/points/contexts/PointsProfileContext.tsx
- src/state/nonces/index.ts
- src/utils/ethereumUtils.ts
- src/walletConnect/index.tsx
Fixes APP-####
Fixes 2 issues:
- We were incorrectly using `getCachedProviderForNetwork` in a few places which was causing bugs like https://rainbowhaus.slack.com/archives/C06NDH4FQTB/p1718232669117889
- `getProviderForNetwork` return type was wrong, it's not a promise so we have to remove the await everywhere where it is used.
> fix getProviderForNetwork type

- .eslintignore
- package.json
- tsconfig.json
This reverts commit d56ed46e7772cd51e54a0f8214947de01e48dd47.
Fixes APP-####
> Revert "Lint on pre-commit (#5836)"

- audit-ci.jsonc
Fixes APP-####
Ignore to unblock CI. We can't bump because there are pkgs using versions that are too old and not compatible.
> Add new advisory to allowlist

- src/__swaps__/screens/Swap/components/CoinRow.tsx
- src/__swaps__/screens/Swap/components/SearchInput.tsx
> add back close button to swap input select asset

- src/__swaps__/screens/Swap/components/CoinRow.tsx
Fixes APP-####
the missing optional makes it crash
> fix handler on android

- src/raps/actions/claimBridge.ts
> Take into account l1 op  gas fee for claimBridge

- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android to version 1.9.27
> bump iOS & Android to version 1.9.27

- src/components/sheet/sheet-action-buttons/SwapActionButton.tsx
Fixes APP-####
Fixes https://rainbowhaus.slack.com/archives/C01GD1F2ZTL/p1719269686205969
https://github.com/rainbow-me/rainbow/assets/1247834/a664f7db-82ed-4e08-a39b-c75bd92d1dc9
> input asset regression fix on v1

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android versions to v1.9.28
> bump iOS & Android versions to v1.9.28

- src/__swaps__/screens/Swap/components/SearchInput.tsx
- src/__swaps__/screens/Swap/components/SearchInputButton.tsx
> Swaps: hide output paste button if clipboard is empty

- src/__swaps__/screens/Swap/providers/swap-provider.tsx
- src/languages/en_US.json
Fixes APP-1612
* replace with haptic feedback
will test on TF
https://app.bitrise.io/build/ddf119ed-f2a9-4e45-a8d7-7ce74dd34fc0
> Swaps: Remove authentication failure message

- src/__swaps__/screens/Swap/components/GasPanel.tsx
- src/__swaps__/screens/Swap/hooks/useEstimatedGasFee.ts
- src/__swaps__/utils/meteorology.ts
- src/languages/en_US.json
- src/resources/assets/useUserAsset.ts
> fix polygon swap (gasPrice)

- src/__swaps__/screens/Swap/components/TokenList/ChainSelection.tsx
- src/__swaps__/screens/Swap/components/TokenList/TokenToSellList.tsx
- src/state/assets/userAssets.ts
Fixes APP-####
not related to this pr but you can see in the video, it takes all this time to switch accounts and then updates the values in like batches not all at once
https://github.com/rainbow-me/rainbow/assets/6232729/47148550-9416-4bfd-9e33-363a211d790b
> filter by network hide irrelevant chains

- src/__swaps__/screens/Swap/components/ReviewPanel.tsx
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/__swaps__/screens/Swap/providers/swap-provider.tsx
This PR may not be needed - pushing here just in case.
> Fallback for minimum display values for wrap unwraps

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump Android & iOS versions to v1.9.29
> bump Android & iOS versions to v1.9.29

- src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx
- src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts
>  fix TokenToBuyList crash 

- src/__swaps__/screens/Swap/hooks/useSearchCurrencyLists.ts
Fixes APP-####
This was breaking local and cross network search
> revert broken search

- src/__swaps__/utils/swaps.ts
- src/handlers/swap.ts
- src/raps/actions/swap.ts
- src/raps/unlockAndCrosschainSwap.ts
- src/raps/unlockAndSwap.ts
Fixes APP-####
Same fixes as the bx
- Fix gas limit for weth unwrapping
- remove unnecessary approval
https://github.com/rainbow-me/rainbow/assets/1247834/4d4a51c1-97f7-4a19-acc8-3dd1ae7f738b
> Fix weth wrapping/unwrapping on other networks

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to v1.9.31
> bump iOS & Android version to v1.9.31

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to v1.9.32
> bump iOS & Android version to v1.9.32

- audit-ci.jsonc
- package.json
- yarn.lock
Audit ci fixes for:
- ws: https://github.com/advisories/GHSA-3h5v-q93c-6h6q
- requirejs: https://github.com/advisories/GHSA-x3m3-4wpv-5vgc
- ip: https://github.com/advisories/GHSA-2p57-rm9w-gvfp
> fix audit: ws, requirejs, ip

- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
Consolidate repeated code around `niceIncrementFormatter`
This should be a no-op - updating the slider / input / output amounts should behave as expected.
> Tidy up swapInputsController repeated logic around `niceIncrementFormatter`

- bitrise.yml
Keeping our bitrise.yml up to date with the one directly downloaded from bitrise.io
> Update bitrise.yml with latest from bitrise.io

- src/__swaps__/screens/Swap/providers/swap-provider.tsx
Fixes APP-####
https://github.com/user-attachments/assets/6c418fab-4b75-428a-9b6d-5a84d6832047
> maxFeePerGas = maxBaseFee + maxPriorityFee

- src/raps/actions/claimBridge.ts
- src/raps/actions/crosschainSwap.ts
- src/references/index.ts
> chore: set referrer for claims

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
changelog!
Had to bump `versionCode` an extra num bc i had to submit twice.
> changelog 1.9.32

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
version bump / changelog 1.9.33
> version bump / changelog 1.9.33

- src/__swaps__/screens/Swap/components/SwapNavbar.tsx
- src/config/experimental.ts
- src/model/remoteConfig.ts
> degen mode feature flag

- src/__swaps__/screens/Swap/hooks/useSwapSettings.ts
- src/__swaps__/screens/Swap/providers/swap-provider.tsx
- src/analytics/event.ts
- src/languages/en_US.json
- Adds Degen Mode tracking
- Adjusts Degen Mode copy
- Removes unused `swapsToggledFlashbots` event
> Degen mode analytics, copy adjustment

- e2e/jest.e2e.config.js
- scripts/run-retry-tests.sh
- Created this script several weeks ago to rerun only failed tests
- I did bad and it was outputting passed no matter what the test results
- Revert for now, and follow up with a PR to get the original intention working again
> Revert CI script changes

- src/components/DappBrowser/control-panel/ControlPanel.tsx
Fixes APP-1736
Right now we're going to treat bridges like swaps, left a todo comment for when we properly do the bridge flow
> DappBrowser Bridge button sends users to old swap flow

- .github/workflows/macstadium-e2e.yml
Reverts rainbow-me/rainbow#5993
I have a feeling that this might have broken CI
> Revert "Test ci job split" 

- package.json
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/__swaps__/utils/swaps.ts
- src/hooks/useSwapDerivedOutputs.ts
- src/raps/actions/claimBridge.ts
- yarn.lock
> update swaps sdk

- src/components/backup/ChooseBackupStep.tsx
> fix runtime error

- src/components/DappBrowser/constants.ts
- src/components/DappBrowser/scripts.ts
Fixes APP-1569
- rotated UA to bypass cloudflare checks on Android
> Fix cloudflare block

- src/components/DappBrowser/Dimensions.ts
- src/components/DappBrowser/search/Search.tsx
> Fix DApp Browser Webview Height

- android/app/src/main/java/me/rainbow/NativeModules/SystemNavigationBar/SystemNavigationBarModule.java
- src/handlers/localstorage/theme.ts
- src/theme/ThemeContext.tsx
> Fix Android Button Navigation Colors

- src/__swaps__/screens/Swap/components/CoinRow.tsx
- src/__swaps__/screens/Swap/components/TokenList/TokenToBuyList.tsx
- src/components/asset-list/RecyclerAssetList2/WrappedCollectiblesHeader.tsx
Fixes APP-####
before/after
https://github.com/user-attachments/assets/5883c2f2-c008-4df2-9918-6c2eb835817d
https://github.com/user-attachments/assets/57bfb30a-43ed-4431-9661-f2444a57d830
> fix TokenToBuyList weirdness when favoriting

- scripts/postinstall.sh
Fixes APP-####
prevent this file to be tracked by github after running `yarn setup`
> ignore graphql changes

- src/App.tsx
https://github.com/user-attachments/assets/ecf7b99b-ae89-4263-bdb1-1c0adeb7ccf3
> Fixes wc flickers

- src/components/cards/remote-cards/RemoteCard.tsx
- src/model/remoteConfig.ts
Fixes APP-1783
Actual root of this problem was the remote config was setup to use the app default (changed August 8th). The app default is false, so this is why they weren't shown in prod.
I also noticed after they. were shown they weren't pressable, so I fixed up some of the conditional wrapping logic.
> Remote Card Fixes

- src/logger/sentry.ts
> Fix Sentry Logging Filter

- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/hooks/useSwapDerivedOutputs.ts
Fixes APP-1794
I mistakenly assumed we would not set the quote when it errored, but we need to set it to with the error state to know what to info to display
> fix sdk bump broke swaps

- src/logger/sentry.ts
> fix default integrations

- src/logger/sentry.ts
> remove filter

- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
> Using version of getAssetNativePrice before the chainId conversions

- .github/workflows/macstadium-e2e.yml
Fixes APP-####
We never rolled back this change after the RN upgrade and this is preventing us from taking the current changes that have been merged to the main branch
> Fix CI Scripts

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- src/__swaps__/screens/Swap/components/ReviewPanel.tsx
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/hooks/useSwapDerivedOutputs.ts
- src/hooks/useWalletBalances.ts
- src/logger/sentry.ts
- src/resources/summary/summary.ts
- yarn.lock
> Push rc-v1.9.36 to master

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS & Android version to v1.9.37
> bump iOS & Android version to v1.9.37

- src/__swaps__/screens/Swap/Swap.tsx
- src/__swaps__/screens/Swap/components/NavigateToSwapSettingsTrigger.tsx
- src/navigation/types.ts
Fixes APP-1806
adds link ability to open swaps with settings panel open
> Add swaps settings trigger

- src/screens/discover/components/DiscoverFeaturedResultsCard.tsx
adjusts featured card aspect ratio on discover home
> change aspect ratio

- ios/Rainbow/Info.plist
Fixes APP-1518
- Fixes http dapp browser issue
> Fix dapp browser http loads

- src/App.tsx
- src/walletConnect/index.tsx
Fixes APP-####
- Initialize listeners earlier
- Modify logic for client initialization
This seems to fix the race condition when connecting from a dapp and rainbow is cold starting,  sometimes the connection prompt would never show up.
More context: https://rainbowhaus.slack.com/archives/C02SU6XKFD0/p1724909257794719?thread_ts=1724742752.294839&cid=C02SU6XKFD0
Cold start + connect (3x)
Note: I can't upload a video showing 5x cold start without problems because it's more than 100mb so I trimmed it to 3 
https://github.com/user-attachments/assets/3adc3010-7ffa-4904-8dfb-7863cad8254f
App already running + msg signing
https://github.com/user-attachments/assets/66596f94-29ef-4769-b174-4b043e333141
WC v2 connections cold start and app already running
> More WC changes

- src/components/asset-list/RecyclerAssetList2/WrappedCollectiblesHeader.tsx
- src/components/list/ListHeaderMenu.tsx
- src/components/native-context-menu/contextMenu.js
- src/components/native-context-menu/contextMenu.tsx
- src/hooks/useNFTsSortBy.ts
- src/hooks/useRefreshAccountData.ts
- src/hooks/useWalletSectionsData.ts
- src/hooks/useWatchPendingTxs.ts
- src/languages/en_US.json
- src/resources/nfts/index.ts
Reverts rainbow-me/rainbow#6045
> Revert "nfts sorting direction"

- src/components/FeaturedResult/FeaturedResultCard.tsx
context: https://rainbowhaus.slack.com/archives/C07JS649B6C/p1725479511312919
> fix wrong id

- src/hooks/useColorForAsset.ts
- src/utils/pseudoRandomArrayItemFromString.ts
Fixes APP-1878
Fixes APP-1874
Fixes a few rogue issues with some color utils that were changed recently.
https://github.com/user-attachments/assets/baeb81de-8db9-4812-b662-918874bbb9fe
creenshots
send flow should pass e2e which should be a decent enough indicator that things are fixed, but testing sends manually couldn't hurt
> Fix send crashes / blank screen

- src/components/DappBrowser/Homepage.tsx
Fixes APP-####
uses the device pixel ratio to pick a good enough image variant
> DappBrowser: fixes Spindl featured image resolution

- src/helpers/buildWalletSections.tsx
- src/raps/actions/claimClaimable.ts
- src/raps/actions/claimSponsoredClaimable.ts
- src/raps/claimSponsoredClaimableAndSwapBridge.ts
- src/raps/execute.ts
- src/raps/references.ts
- src/resources/addys/claimables/utils.ts
- src/screens/claimables/ClaimClaimablePanel.tsx
> sponsored rap

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.40
> Bump iOS and Android to v1.9.40

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to v1.9.41
> bump iOS and Android to v1.9.41

- src/components/asset-list/RecyclerAssetList2/Claimable.tsx
- src/screens/claimables/ClaimingClaimableSharedUI.tsx
- src/screens/claimables/ClaimingSponsoredClaimable.tsx
- src/screens/claimables/ClaimingTransactionClaimable.tsx
Fixes APP-####
* display amount of claimable using backend provided field
* fix gas estimation by passing in chain id to `startPollingGasFees`
* make `isButtonDisabled` logic more clear and use that value to determine button opacity
* fix border radius for claimable dapp icon (on wallet screen row and claim panel header)
* add haptic feedback
* disable button text shadows when button is disabled
https://www.loom.com/share/985d9c9696024602bc913c1aa3006a4e
> Claimables fixes

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump android and iOS to version v1.9.42
> bump android and iOS to version v1.9.42

- src/walletConnect/index.tsx
> cleanup walletkit ts-ignores

- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/hooks/useWatchWallet.ts
- src/screens/hardware-wallets/PairHardwareWalletSigningSheet.tsx
Something got merged and passed lint when it shouldn't have. This fixes it up.
> Fix lint issues on develop

- src/components/MobileWalletProtocolListener.tsx
- src/utils/requestNavigationHandlers.ts
Fixes APP-1911
Wrapped the fetchClientDappMetadata call in a try...catch so we can proceed if it fails.
N/A
mwp flow should work as expected but be less rigid
> Fix MWP from failing to prompt if dapp metadata retrieval fails

- src/resources/addys/claimables/utils.ts
lint on develop is broken for whatever reason, this fixes it.
> Fix lint issue

- package.json
- src/__swaps__/screens/Swap/hooks/useSwapInputsController.ts
- src/__swaps__/screens/Swap/providers/swap-provider.tsx
- src/__swaps__/utils/swaps.ts
- src/handlers/swap.ts
- src/hooks/usePriceImpactDetails.ts
- src/hooks/useSwapDerivedOutputs.ts
- src/raps/actions/claimBridge.ts
- src/raps/actions/swap.ts
- src/raps/unlockAndCrosschainSwap.ts
- src/raps/unlockAndSwap.ts
- src/screens/ExchangeModal.tsx
- yarn.lock
- **chore: update swaps**
- **chore: replace extraneous crosschain logic with needsAllowance field**
- **chore: get rid of all WRAPPED_ASSET references and use quote swap type**
- **chore: remove swapType as a param to get quotes**
- **chore: replace swap unlock logic with needsAllowance field**
---
Tested paths on testflight:
- Wrap DEGEN
- Unwrap DEGEN
- Wrap ETH 
- Unwrap ETH
- Eth to Token Swap
- Token to Eth Swap
- Crosschain bridge using Relay
- Native 
- ERC20
- Crosschain swap using Socket
> chore: use new fields from swap sdk and remove extraneous code

- src/navigation/PairHardwareWalletNavigator.tsx
Fixes APP-####
the ledger image was blocking the "next" button
before/after
> fix ledger image blocking text

- package.json
- src/components/ActivityIndicator.tsx
- yarn.lock
fixes issue with local images not working due to yarn lock changes
> fix crash swaps / local images

- src/analytics/event.ts
- src/components/DappBrowser/Homepage.tsx
- src/state/browser/favoriteDappsStore.ts
Fixes APP-1922 & APP-1923
added analytics events on the dapp browser for adding to favorites and clicking favorite card
> add favorites analytics

- src/model/remoteConfig.ts
Fixes APP-####
- enabled degen mode, claimables, and featured results by default to mitigate Firebase blocks for VPN users
> chore: enable new features by default

- src/components/DappBrowser/BrowserTab.tsx
- src/state/browserHistory/index.ts
Fixes APP-1934
see assigned ticket for details
> clean up featured results

- src/components/gas/GasSpeedButton.tsx
Fixes APP-####
gas button wasn't working due to defaulting to empty array.
> Fix gas button

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android version to v1.9.43
> bump iOS and Android version to v1.9.43

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
update iOS and Android to version v1.9.44
> update iOS and Android to version v1.9.44

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to version v1.9.45
> bump iOS and Android to version v1.9.45

- src/hooks/useWalletBalances.ts
- src/resources/defi/types.ts
- src/resources/defi/utils.ts
Fixes APP-####
some positions are omitted from the total wallet balance, but should still display the position value in the position card
before/after
> fix position total value display

- src/references/index.ts
just a small code block removal now that they're unused
n/a
n/a
> remove rest of references now that swaps v1 cleanup is merged

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to version v1.9.46
> bump iOS and Android to version v1.9.46

- src/components/asset-list/RecyclerAssetList2/Claimable.tsx
Fixes APP-2019
Just switched two lines.
> Add null guard for claimable data

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- Remove unused environment configurations (#6254) 
- Added a null check guard to the claimable flow (#6257)
- Fixed an issue in our approve and swap flow that should help overall swap success (#6259)
- Changed the way we handle flashbots gas so less transactions should fail due to insufficent gas (#6265)
> v1.9.47 bump

- src/graphql/queries/arc.graphql
- src/resources/trendingTokens/trendingTokens.ts
adds trending tokens react-query hooks
n/a just functional
n/a no implementation yet
> Add trending tokens query

- src/state/backups/backups.ts
Fixes APP-2078
adds a 10s timeout to the sync process
> [1297] - Fix infinite sync

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to version 1.9.48
> bump iOS and Android to version 1.9.48

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to v1.9.49
> bump iOS and Android to v1.9.49

- src/screens/WalletScreen/index.tsx
Fixes APP-####
- Current code results in initializeWallet being called multiple times. I don't think this causes any explicit bugs, just extra re-renders and calling the heavy initializeWallet function more than once. Fixed by using refs instead of state.
- The trackWallets function was called directly after the initializeWallet, but it is not guaranteed that all the wallets have loaded at that point, and in most testing cases they were not, resulting in incorrect analytic logging. 
That initializeWallet doesn't get called more than once.
> fix duplicate wallet initialization and wallet type tracking

- src/components/Discover/TrendingTokens.tsx
- src/hooks/useFarcasterAccountForWallets.ts
- src/resources/trendingTokens/trendingTokens.ts
Added sort direction
Make sure sort functions
> [APP-2183] Trending tokens polish: Sort functionality is broken

- src/featuresToUnlock/tokenGatedUtils.ts
- src/featuresToUnlock/unlockableAppIconCheck.ts
- Handle raw data response properly from provider.call
- Fix logic on icon checks
- Backwards compatibility
https://github.com/user-attachments/assets/55805daf-af1c-4012-aef3-7e32349b1ab5
https://rainbowhaus.slack.com/archives/C0468CDBE75/p1734465096538089
> Icons hotfix

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Update iOS and Android to v1.9.51
> Update iOS and Android to v1.9.51

- src/components/sheet/sheet-action-buttons/SwapActionButton.tsx
I think network xp broke this again.
> [APP-2194] fix nav to swap from tt row 

- src/components/NetworkSwitcher.tsx
Fixes APP-2208
one line change to switch the chainName to chainLabel
not really needed
> Use chain label instead of name

- src/components/NetworkSwitcher.tsx
- src/languages/en_US.json
Fixes APP-2214
Changed the more button to be a network chip when odd number of networks are pinned
https://github.com/user-attachments/assets/87a93c57-3d08-4e80-91eb-22ba66d34c38
all edge cases of number of networks
> Fix more button

- src/components/Discover/TrendingTokens.tsx
- src/components/NetworkSwitcher.tsx
- src/screens/ExplainSheet.js
We introduced a few more local networkColors reliances with the trending tokens + network selector work, so cleaning those up
n.a
n.a
> More backendNetworks networkColors removal

- src/model/remoteConfig.ts
> chore: add trending tokens flag to remote config.ts

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and android to v1.9.53
> bump iOS and android to v1.9.53

- src/components/backup/ChooseBackupStep.tsx
- src/screens/SettingsSheet/components/Backups/ViewCloudBackups.tsx
- src/screens/SettingsSheet/utils.ts
- Added `dateFormatter` utility function in `SettingsSheet/utils.ts`
- Provides centralized date formatting with error handling
- Uses `date-fns` format function with fallback to 'Unknown Date'
- Removed direct `date-fns` imports from component files
- Consolidated date formatting logic into a single utility function
- Default format string set to "M/d/yy 'at' h:mm a"
- Added try-catch blocks around timestamp parsing logic
- Returns 0 as fallback when timestamp parsing fails
- Implemented in both `ChooseBackupStep` and `ViewCloudBackups` components
- Improved type safety with explicit `LoadingTextProps` interface
- Better error handling for backup file timestamp parsing
- Consistent sorting behavior across backup-related components
- Added proper typing for theme props
- Introduced …
> Fixes improper time formatter causing crashes

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Update iOS and Android to v1.9.54
> Update iOS and Android to v1.9.54

- ios/Podfile.lock
- package.json
- yarn.lock
Required by APP-2243
See original ticket for more info
None
Analytics should work as usual
> Bump rudderstack

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
update iOS and Android to v1.9.56
> update iOS and Android to v1.9.56

- src/handlers/walletReadyEvents.ts
Fixes APP-2301
Our runChecks function was preferring local campaigns over backups prompt so the user wouldn't see the backup prompt on fresh creation until the second launch (after notifications prompt). This fixes it by deferring the notifications prompt 15 seconds which gives backups prompt plenty of time to prompt and be active. 
attached linear ticket repro steps
> fix bottom sheet stacking order

- src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
Fixes APP-2130
Fixes NFT expanded state using ETH mainnet native pricing always
https://github.com/user-attachments/assets/f1de8e8a-97fb-4427-8308-f7039c278bfd
test more chains if possible, but should be good honestly
> Floor price displayed incorrectly in latest version for asset

- src/raps/actions/crosschainSwap.ts
- src/raps/actions/swap.ts
Fixes APP-####
Added extra checks to make sure we're not sending swaps through the wrong flow
> Add extra checks for swap types

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to v1.9.57
> bump iOS and Android to v1.9.57

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
update iOS and Android to v1.9.58
> update iOS and Android to v1.9.58

- package.json
- yarn.lock
> chore: update swaps sdk to 0.32.0

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to v1.9.60
> bump iOS and Android to v1.9.60

- src/analytics/index.ts
Fixes APP-2243
Fixes android devices not working properly with rudderstack
N/A but here's my Nothing Phone (2) that was previously showing up as (none)
```
{"device_brand": "Nothing", "device_manufacturer": "Nothing", "device_model": "A065"}
```
not sure how to test this properly
> Fix: Majority of Android devices show as "none" in analytics events

- src/hooks/useTokenLauncher.ts
- src/screens/token-launcher/components/NetworkField.tsx
- src/state/backendNetworks/backendNetworks.ts
Calling setData again
store.getData() contains the data we care about
> Fix BE Network Getters [ftl]

- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
> chore: bump version to 1.9.61

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
update iOS and Android to v1.9.61
> update iOS and Android to v1.9.61

- src/languages/en_US.json
- src/screens/ExplainSheet.js
- src/screens/token-launcher/components/TokenAllocationSection.tsx
Fixes APP-2429
Adds info breakdown sheet to explain sheet
> Add allocation breakdown info sheet

- src/screens/token-launcher/components/SingleFieldInput.tsx
- Adds missing `subtitle` prop to `LabelContent` and corrects its optional types
> Fix TL field subtitle

- src/safe-math/SafeMath.ts
Fixes APP-####
Stolen from https://github.com/rainbow-me/rainbow/pull/6504/files#diff-10c6bfd2e6aa2ce2d2e93638a354e13cffcbf1fc0e2f9861f401c072e91fdb2fL398-R398
> Prevent Expanded State Crash

- package.json
- yarn.lock
Fixes APP-####
Bump swaps SDK to 0.33 to enable fallback quotes
> bump swaps sdk to 0.33

- package.json
- src/handlers/swap.ts
- src/raps/actions/swap.ts
- src/raps/unlockAndSwap.ts
- src/raps/utils.ts
- src/screens/Airdrops/ClaimAirdropSheet.tsx
- src/screens/Airdrops/utils.ts
- yarn.lock
* Swaps sdk bump
* Fix for legacy gas params route to use toHex in Claims flow
* Use getTargetAddress result from swaps sdk
> Use target address from swap

- src/graphql/queries/metadata.graphql
- src/languages/en_US.json
- src/screens/expandedAssetSheet/components/SheetContent.tsx
- src/screens/expandedAssetSheet/components/sections/AboutSection.tsx
- src/screens/token-launcher/components/LinksSection.tsx
- src/screens/token-launcher/helpers/inputValidators.ts
- src/screens/token-launcher/types/index.ts
Fixes APP-2492, APP-2493
- Add support for showing Farcaster (Warpcast) and Other type links in about section of expanded state
- Show buy section at top when asset is unowned.
- Fix ftl input validators for twitter & farcaster allowing string to start with "@"
> Ftl links fixes

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
bump iOS and Android to v1.9.63
> bump iOS and Android to v1.9.63

- package.json
- yarn.lock
Fixes APP-####
Bump swaps SDK to 0.35.0
> Bump swaps SDK

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.64
> Bump iOS and Android to v1.9.64

- src/languages/en_US.json
- src/screens/token-launcher/helpers/tokenLaunchErrorToErrorMessage.ts
- src/screens/token-launcher/state/tokenLauncherStore.ts
Created a helper to return copy based on error codes. This needs product review to determine the final copy.
This is mostly to validate that the copy seems appropriate.
> [APP-2487] Readable TL Error Alerts

- package.json
- yarn.lock
including https://github.com/rainbow-me/swaps/pull/105
> bump swaps to 0.36.0

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.66
> Bump iOS and Android to v1.9.66

- src/__swaps__/screens/Swap/components/NavigateToSwapSettingsTrigger.tsx
- src/components/FeesPanel.tsx
- src/components/backup/BackupCloudStep.tsx
- src/components/backup/BackupSheet.tsx
- src/components/backup/RestoreCloudStep.tsx
- src/components/icons/svg/RainbowText.js
- src/hooks/useImportingWallet.ts
- src/navigation/AddWalletNavigator.tsx
- src/navigation/Navigation.tsx
- src/navigation/types.ts
- src/screens/AddWalletSheet.tsx
- src/screens/ChooseWalletGroup.tsx
- src/screens/RestoreSheet.tsx
- src/screens/WalletScreen/index.tsx
- src/screens/WelcomeScreen/index.tsx
- src/screens/change-wallet/ChangeWalletSheet.tsx
- src/screens/transaction-details/TransactionDetails.tsx
> progress on getting all routes to be type safe

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.67
> Bump iOS and Android to v1.9.67

- src/screens/RestoreSheet.tsx
https://rainbow-me.sentry.io/issues/6580661453/events/recommended/events/?project=1855565&query=release:me.rainbow@1.9.67%2020&stream_index=1
> fixes crash when entering into restore sheet

- src/hooks/useWatchWallet.ts
Fixes BX-1791, APP-2632
Fixes edge case coming into import using watched wallet in the profile sheet.
> fixes profile sheet infinite importing portal

- src/graphql/queries/metadata.graphql
- src/helpers/validators.ts
- src/hooks/useAdditionalAssetData.ts
- src/languages/en_US.json
- src/screens/Airdrops/ClaimAirdropSheet.tsx
- src/screens/expandedAssetSheet/components/sections/marketSection/AssetInfoList.tsx
- src/utils/abbreviations.ts
Fixes APP-2614
Added created by section to asset info breakdown.
https://github.com/user-attachments/assets/69a82a29-7a41-4937-be19-c958651b10d3
different asset types
> Add Token Creator to Expanded State

- .github/workflows/android-e2e.yml
- .github/workflows/macstadium-ios-e2e.yml
- .github/workflows/unit-test.yml
Fixes APP-####
- Did make sure e2e test don't run on Draft
- Put the linting/unit-test on Blacksmith.sh which is faster from: **6m 2s** to **3m 17s**
> Make sure e2e don't run on draft and run unit test on Blacksmith.sh

- src/components/Discover/DiscoverHome.tsx
- src/components/Discover/KingOfTheHill.tsx
- src/components/cards/skia-cards/KingOfTheHillCard.tsx
- src/config/experimental.ts
- src/graphql/queries/metadata.graphql
- src/handlers/imgix.ts
- src/model/remoteConfig.ts
- src/screens/expandedAssetSheet/context/ExpandedAssetSheetContext.tsx
- src/state/kingOfTheHill/kingOfTheHillStore.ts
- Changes made for new king of the hill response shape
- Changed feature flag to "prince_of_the_hill" as turning on old feature flag with different types would break app
https://github.com/user-attachments/assets/555301f1-cca0-4ed3-9277-fdc1f9af4065
- Turn on prince of the hill feature flag, make sure it looks right on discover screen
> Update king of the hill types

- e2e/onboarding/CreateWallet.yaml
- e2e/onboarding/WatchedWallet.yaml
- e2e/screens/Discover.yaml
- e2e/screens/Home.yaml
- e2e/screens/MaliciousDappTransactionWarning.yaml
- e2e/settings/ManualBackup.yaml
- e2e/transactions/EditContact.yaml
- e2e/transactions/SendTransaction.yaml
- e2e/transactions/SwapTransaction.yaml
- add retries to each test to counteract flakiness / false positives.
- also fixes the SendTransaction test which was just failing on iOS.
> retry wrap

- .github/actions/android-emulator/action.yml
- .github/workflows/android-e2e.yml
- e2e/onboarding/CreateWallet.yaml
- e2e/utils/ImportWalletWithKey.yaml
Fixes APP-####
- Test to see if this version is more stable.
- Fix test failing because of new nft on test account
> Update blacksmith runner to 2404

- .eslintrc.js
- package.json
- yarn.lock
> yaml linting on commit

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.70
> Bump iOS and Android to v1.9.70

- ios/Podfile.lock
- src/helpers/assets.ts
- src/helpers/buildWalletSections.tsx
Fixes APP-2788
Fixes watched wallets being shown user's hidden tokens
https://github.com/user-attachments/assets/c85474e1-3c3d-498b-9b03-b40be82951b2
can you view hidden tokens as a read only wallet?
> fix watched wallets showing hidden tokens

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.71
> Bump iOS and Android to v1.9.71

- .github/actions/android-emulator/action.yml
- .github/workflows/android-e2e.yml
Fixes APP-####
Go back to github runner to test stability.
N/A
E2e tests are passing
> Run e2e android tests on github runner

- src/components/expanded-state/DevTestBackupState.tsx
- src/hooks/useImportingWallet.ts
- src/keychain/index.ts
- src/screens/ImportOrWatchWalletSheet.tsx
Fixes APP-2724
and sometimes not navigating to main screen.
This fixes the keyboard loading focus on seed import.
It may also fix the intermittent issue of not going to home screen after seed import (staying on import modal). I see no reason to wait for animations to complete to do that since it will happen at a time when they really wouldn't be touching anything (it's showing a "Importing" modal above the screen).
> fix import bugs - blur after focusing seed input

- e2e/transactions/SendNft.yaml
> Fix send button regex

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.73
> Bump iOS and Android to v1.9.73

- .gitignore
- e2e/transactions/SendNft.yaml
> Enhance SendNft flow with retry logic for send action visibility

- package.json
- yarn.lock
Fixes APP-####
Fixed a crash I found on older android versions related to turbo haptics.
N/A
- App no longer crashes on moto g8 plus
> Bump turbo haptics to fix android crash

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v1.9.74
> Bump iOS and Android to v1.9.74

- ios/Podfile.lock
Fixes APP-####
Forgot to run pod install after turbo haptics update.
> Fix podfile lock after turbohaptics update

- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v2.0.0
> Bump iOS and Android to v2.0.0

- src/analytics/event.ts
- src/analytics/userProperties.ts
- src/components/value-chart/Chart.tsx
- src/features/charts/stores/candlestickStore.ts
Fixes APP-2833
- Adds tracking of both chart type and candle resolution
> Candlestick charts analytics

- src/screens/points/claim-flow/ClaimRewardsPanel.tsx
Fixes APP-3046
- Fixed small styling issues causing button to not be pressable Android
> fix: rainbow rewards claim button not pressable on Android

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v2.0.1
> Bump iOS and Android to v2.0.1

- e2e/flows/transactions/SendTransaction.yaml
- src/components/rainbow-toast/constants.ts
- src/components/rainbow-toast/useRainbowToastEnabled.ts
- src/hooks/useDelayedValueWithLayoutAnimation.ts
- src/screens/DiscoverScreen.tsx
> Fix issue with e2e

- src/features/perps/components/CollapsibleSection.tsx
- src/features/perps/screens/PerpDetailScreen.tsx
- src/features/perps/stores/hlTradesStore.ts
> Add history and liquidation section for PerpsDetailsScreen

- src/config/experimental.ts
- src/hooks/useWalletSectionsData.ts
> Add perps feature flag

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v2.0.4
> Bump iOS and Android to v2.0.4

- .github/workflows/android-e2e.yml
- .github/workflows/ios-builds.yml
- .github/workflows/ios-e2e.yml
- rock.config.mjs
> Remove env log

- src/App.tsx
- src/components/expanded-state/ContactProfileState.js
- src/components/layout/KeyboardFixedOpenLayout.tsx
> Fix modal flick for contact

- CHANGELOG.md
- android/app/build.gradle
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
Bump iOS and Android to v2.0.8
> Bump iOS and Android to v2.0.8
