rainbow-me/rainbow

- src/screens/ImportSeedPhraseSheet.js
- src/screens/ImportSeedPhraseSheetWithData.js
[https://trello.com/c/CjEAp6Jb/10-%F0%9F%8C%B1when-importing-seed-phrase-should-cease-any-other-interactions](https://trello.com/c/CjEAp6Jb/10-%F0%9F%8C%B1when-importing-seed-phrase-should-cease-any-other-interactions)
> Disable interactions while actively importing a seed phrase

- src/components/buttons/PasteAddressButton.js
[https://trello.com/c/SdWbs1ti/76-remove-delay-from-paste-button-validation-in-send-flow](https://trello.com/c/SdWbs1ti/76-remove-delay-from-paste-button-validation-in-send-flow)
> Remove delay from paste button validation in Send flow

- src/components/expanded-state/asset-panel/AssetPanelAction.js
[https://trello.com/c/gRxvOi3S/81-send-icon-missing-from-send-to-row-in-asset-expanded-state](https://trello.com/c/gRxvOi3S/81-send-icon-missing-from-send-to-row-in-asset-expanded-state)
> Add missing “Send” icon back to TokenExpandedState

- package.json
- yarn.lock
> Revert "Fix jumping index in react-navigation-tabs"

- src/components/asset-list/RecyclerAssetList.js
Need to animate expanding / hiding
Decided to use LayoutAnimation mechanism which appears to be a perfect match for our case.
Added interpolation following source code of `RecycleListView`z.
Fixed propTypes
Fixed few code style issues
> Animate collectibles group

- ios/Podfile.lock
- package.json
- yarn.lock
Includes 🌈️ overrides for following tokens:
bat
dai
eth
gnt
knc
lpt
mana
mkr
omg
rep
spank
usdc
usdt
wbtc
zrx
> Update to latest react-coin-icon

- metro.config.js
It should help a bit with startup time.
Try with `react-native start —reset-cache`
> Add inline requires support

- ios/Podfile.lock
- src/components/investment-cards/UniswapInvestmentCard.js
- src/parsers/gas.js
- src/screens/SendSheet.js
- Fix incorrect ordering of Gas speed options
- Update background gradient color values for UniswapInvestmentCard
>  Fix incorrect ordering of Gas speed options

- src/components/expanded-state/AddContactState.js
- src/components/send/SendContactList.js
Made a few spacing and copy adjustments:
1) Moved character in avatar up 1pt
2) Changed deletion action sheet copy
3) Adjusted AvatarWrapper margins to add more space at the top of the list
Probably a better way to make some of these changes so feel free to redo differently if you prefer @wojciechstaniszswmansion.
> Design adjustments

- ios/Podfile
- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Reverts rainbow-me/rainbow#143
> Revert "Bump to RN 0.60.4"

- src/components/SendComponentWithData.js
- src/components/contacts/SwipeableContactRow.js
- src/components/expanded-state/AddContactState.js
- src/components/send/SendContactList.js
- src/components/text/PlaceholderText.js
and refactor logic for auto closing to use refs instead of rerendering of components
> Refactor contact modal modal for faster placeholder disappearance  

- src/navigation/transitions/effects.js
- src/screens/Routes.js
Speeds up open/close transition
> Improve stack modal transitions

- src/screens/ImportSeedPhraseSheet.js
- src/screens/SendSheet.js
Fixes:
1. Top margin issue concerning import seed phrase sheet
2. After half-closing send sheet it refocused always on header for no reason - fixed to refocus on last touched input
> Bunch sheet fixes

- ios/Podfile.lock
- src/components/exchange/ExchangeInput.js
- src/components/exchange/ExchangeInputField.js
- src/components/exchange/ExchangeNativeField.js
- src/components/exchange/ExchangeOutputField.js
- src/screens/ExchangeModal.js
- yarn.lock
The actual issues were:
**1. These checks were being used to clear inputs, causing issues when typing zeros:**
`const isInputZero = Number(inputAmount) === 0;`
`const isNativeZero = Number(nativeAmount || 0) === 0;`
`const isOutputZero = Number(rawOutputAmount) === 0;`
Now instead it checks if the focused input is empty or has a value of 0. If it does, the opposite input's state is cleared.
**2. Input states weren't being properly updated if you typed a number, deleted it, and typed the same number again**
Clearing `inputAmount`/`outputAmount` states instead of clearing the inputs also fixed this.
**3. `ExchangeOutputField` wasn't correctly updating `isSufficientBalance`**
The actual cause seems to be that when you type in `ExchangeOutputField`, the `inputAmount` value (which informs …
> Improve swap inputs

- src/components/animations/ButtonPressAnimation.js
Rewrite button press animation to support always go to half of the transition no matter how long the interaction was
> rewrite button press animation logic

- src/components/asset-list/EmptyAssetList.js
- src/components/exchange/CurrencySelectModalHeader.js
- src/components/exchange/CurrencySelectionList.js
- src/components/exchange/ExchangeAssetList.js
- src/components/exchange/ExchangeSearch.js
- src/components/exchange/index.js
- src/components/inputs/ClearInputDecorator.js
- src/screens/CurrencySelectModal.js
Fixes RAI-9 https://linear.app/issue/RAI-9
Fixes RAI-22 https://linear.app/issue/RAI-22
Fixes RAI-25 https://linear.app/issue/RAI-25
> Fix shimmer effect in CurrencySelectModal list

- src/components/SendComponentWithData.js
- src/components/animations/ButtonPressAnimation.js
- src/components/contacts/SwipeableContactRow.js
- src/components/fields/AddressField.js
- src/components/fields/UnderlineField.js
- src/components/send/SendContactList.js
- src/components/send/SendHeader.js
- src/components/text/ErrorText.js
- src/hoc/withDataInit.js
- src/hoc/withSelectedInput.js
- src/redux/reducers.js
- src/redux/selectedInput.js
- src/screens/SendSheet.js
- src/screens/WalletScreen.js
Change wallet init to load open asset first so there is not transition after loading all assets in wallet screen
Change logic for keyboard reload in send sheet to use redux
> Change wallet init and keyboard in send

- src/components/SendComponentWithData.js
- src/components/animations/ButtonPressAnimation.js
- src/components/contacts/SwipeableContactRow.js
- src/components/fields/AddressField.js
- src/components/fields/UnderlineField.js
- src/components/send/SendContactList.js
- src/components/send/SendHeader.js
- src/components/text/ErrorText.js
- src/hoc/withDataInit.js
- src/hoc/withSelectedInput.js
- src/redux/reducers.js
- src/redux/selectedInput.js
- src/screens/SendSheet.js
- src/screens/WalletScreen.js
Reverts rainbow-me/rainbow#220
> Revert "Revert "Change wallet init and keyboard in send""

- ios/Podfile.lock
- package.json
- src/components/coin-icon/CoinIcon.js
- yarn.lock
Fixes RAI-43 https://linear.app/issue/RAI-43
> Update swap token icons

- ios/Podfile.lock
- src/components/coin-row/ExchangeCoinRow.js
- src/components/exchange/ExchangeAssetList.js
- src/screens/CurrencySelectModal.js
- yarn.lock
Fixes RAI-69 https://linear.app/issue/RAI-69
> Fix stars showing up on unfavorited items

- ios/Podfile.lock
- src/components/coin-row/ExchangeCoinRow.js
- src/components/exchange/ExchangeAssetList.js
- src/screens/CurrencySelectModal.js
- yarn.lock
This reverts commit 6b8f65b1d3560fae7499d29070dc165d2053d1e4, reversing
changes made to 3cee6490216dc38cb23a9b1c8bf59bab08f24c82.
> Revert "Merge pull request #230 from rainbow-me/fix-favorite-stars"

- src/hoc/withUniswapAssets.js
- src/redux/uniswap.js
- src/screens/ExchangeModal.js
Remove redundant approval amount checks
Fix: https://linear.app/issue/RAI-77
> Fix: ExchangeModal should update on pending approvals change

- src/components/activity-list/ActivityList.js
- src/components/activity-list/RecyclerActivityList.js
- src/components/coin-row/TransactionCoinRow.js
- src/components/contacts/SwipeableContactRow.js
- src/components/contacts/showDeleteContactActionSheet.js
- src/components/expanded-state/AddContactState.js
- src/components/fields/AddressField.js
- src/components/send/SendContactList.js
- src/components/send/SendHeader.js
- src/handlers/localstorage/contacts.js
- src/helpers/emojiHandler.js
- src/helpers/transactions.js
- src/hoc/index.js
- src/hoc/withContacts.js
- src/hoc/withDataInit.js
- src/redux/contacts.js
- src/redux/reducers.js
- src/redux/send.js
- src/screens/ExpandedAssetScreen.js
- src/screens/SendSheet.js
Improves code clarity for contacts
Fixes: https://linear.app/issue/RAI-86
> Create contacts redux and enable searching via emoji

- src/components/send/SendAssetForm.js
add padding to the transaction container to keep buttons away from very bottom of the screen
> add padding to the transaction container

- src/parsers/transactions.js
Fixes: https://linear.app/issue/RAI-95
> Fix: override token params for transactions

- src/components/send/SendHeader.js
- src/navigation/transitions/effects.js
- src/screens/SendSheet.js
> Unify keyboard handling on send sheet, increase displacement and speed threshold

- src/screens/ExchangeModal.js
https://linear.app/issue/RAI-112
> Check if asset exists in wallet before overwriting input currency

- src/components/send/SendHeader.js
- src/navigation/transitions/effects.js
- src/screens/SendSheet.js
Reverts rainbow-me/rainbow#270
> Revert "Unify keyboard handling on send sheet, increase displacement and speed threshold"

- ios/Podfile.lock
- src/App.js
- src/screens/ExchangeModal.js
- yarn.lock
Fixes RAI-140 https://linear.app/issue/RAI-140
> Fix the broken initial autofocus effect on Swap Modal

- src/components/exchange/ConfirmExchangeButton.js
Fixes RAI-111 https://linear.app/issue/RAI-111
> Prevent unlock button getting disabled when !isSufficientBalance

- ios/Podfile
- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Rainbow.xcodeproj/xcshareddata/xcschemes/Rainbow.xcscheme
- yarn.lock
Follows advice laid out by @kelset in this gist 👉️ https://gist.github.com/kelset/2eb61161a68d1ab35337d1eaa9a05e78
> Attempt to optimize xcode build times by tweaking compiler settings

- ios/Podfile.lock
- package.json
- src/handlers/localstorage/uniswap.js
- src/hoc/withUniswapAssets.js
- src/hooks/useStorage.js
- src/redux/uniswap.js
- src/references/index.js
- yarn.lock
Sets the default "favorite" assets to:
```
ETH
DAI
SOCKS
```
Fixes RAI-130 https://linear.app/issue/RAI-130
> Add defaults for "favorited" assets in Swap flow

- src/navigation/transitions/effects.js
This solution fixes modal overlay background change color issue, by adding a new layer that cannot be changed by outside component
> Cover glitched background

- src/App.js
- src/components/OfflineBadge.js
Fixes RAI-143 https://linear.app/issue/RAI-143
> Fix missing OfflineBadge

- src/helpers/buildWalletSections.js
- src/helpers/utilities.js
- src/hoc/withUniswapAssets.js
- src/parsers/accounts.js
- src/parsers/transactions.js
- src/redux/data.js
- src/screens/CurrencySelectModal.js
- src/screens/ExchangeModal.js
* Fix for deduping pending transactions using nonce 
* Rename assetsAvailableOnUniswap to uniswapAssetsInWallet for clarity
* Remove assets with 0 quantity after merge with existing assets
* Replacing parseFloat with bignumber operations for swap
> Fixes for swap and pending transactions

- src/components/fields/UnderlineField.js
> Remove blurring from UnderlineField

- src/model/keychain.js
@jinchung  Adding the same changes that we did for codepush earlier today.
> Add sentry logging for keychain errors

- src/screens/Routes/Routes.ios.js
Before
https://streamable.com/u6frn
After
https://streamable.com/cwoup
> Fix overlay asset screen in not native stack

- ios/Rainbow.xcodeproj/project.pbxproj
This PR modifies the build phase "Bundle React Native Code and Images" script to run successfully on both Debug & Release mode
> Bugfix: Debug mode builds

- src/screens/ExchangeModal.js
- src/screens/SendSheet.js
This is an improvement for the dismissal of the send sheet & exchange modal.
> Bugfix: Run actions after interactions

- src/redux/data.js
Added a check before trying to unsubscribe. This prevents the crash and looks like everything else works normally.
> Bugfix: Import key error

- ios/Podfile.lock
- src/components/coin-icon/CoinIcon.js
- src/components/coin-row/ExchangeCoinRow.js
- src/components/exchange/ExchangeInputField.js
- src/components/exchange/ExchangeOutputField.js
- src/navigation/ExchangeModalNavigator.js
- src/screens/CurrencySelectModal.js
- src/screens/ExchangeModal.js
- Fix crash on swap input selection
- Default to png icons when available
- Get all uniswap exchanges after interactions (improves modal initial animation delay)
- Fix input focus after going through SendSheet first
> Exchange modal fixes

- src/components/settings-menu/NetworkSection.js
- src/components/settings-menu/SettingsSection.js
- src/handlers/localstorage/globalSettings.js
- src/handlers/localstorage/uniswap.js
- src/handlers/uniswap.js
- src/handlers/web3.js
- src/hoc/withAccountSettings.js
- src/hoc/withDataInit.js
- src/redux/explorer.js
- src/redux/settings.js
- src/redux/testnetExplorer.js
- src/redux/uniqueTokens.js
- src/redux/uniswap.js
- src/redux/web3listener.js
- src/references/balances-checker-abi.json
- src/references/index.js
- src/references/testnet-assets.json
- src/references/uniswap-pairs-testnet.json
- src/screens/AvatarBuilder.js
- src/screens/WalletScreen.js
This enables multi network support (only mainnet / rinkeby) with the following features:
- Send ETH
- Send Token
- Swap (ETH, DAI, BAT, ZRX, MAKER)
Transaction History works only after making 1 transaction. Can be improved in the future.
This doesn't modify any existing functionality and adds the ability to add other networks in the future .
> Rinkeby Testnet Support

- src/helpers/assets.js
Add a new flag to support a maximum of 5 coins above 1$
> Add new flag to support maximum 5 coins

- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- src/components/coin-row/ExchangeCoinRow.js
- src/components/exchange/CurrencySelectionList.js
- src/components/exchange/ExchangeAssetList.js
- yarn.lock
Create 'showBalances' variant of ExchangeCoinRow
> Create 'showBalances' variant of ExchangeCoinRow

- src/components/activity-list/ActivityList.js
- src/components/activity-list/TestnetEmptyState.js
- src/redux/data.js
- src/redux/explorer.js
- src/redux/testnetExplorer.js
- src/screens/WalletScreen.js
- Fix the bug that prevented the assets from loading while switching to Rinkeby
- Adds the empty state for the activity list while on testnet.
> Network changing fix

- src/components/exchange/SwapInfo.js
- src/screens/ExchangeModal.js
- src/screens/SavingsSheet.js
This fixes https://linear.app/issue/RAI-224/ui-include-swapping-for-___-dai
> Show swap info on savings modal

- src/App.js
- src/components/AddFundsInterstitial.js
- src/components/TestnetBadge.js
- src/components/activity-list/ActivityList.js
- src/components/asset-list/AssetList.js
- src/components/asset-list/EmptyAssetList.js
- src/components/coin-row/ContractInteractionCoinRow.js
- src/components/coin-row/TransactionCoinRow.js
- src/components/fab/ExchangeFab.js
- src/components/settings-menu/NetworkSection.js
- src/components/settings-menu/SettingsSection.js
- src/components/transaction-list/TransactionList.js
- src/handlers/localstorage/globalSettings.js
- src/helpers/networkInfo.js
- src/helpers/networkTypes.js
- src/hoc/withAccountData.js
- src/hoc/withDataInit.js
- src/redux/explorer.js
- src/redux/settings.js
- src/redux/testnetExplorer.js
- src/redux/uniqueTokens.js
- src/redux/uniswap.js
- src/references/testnet-assets.json
- src/screens/ProfileScreen.js
- src/screens/WalletScreen.js
- src/utils/ethereumUtils.js
- Enable all the testnets
- Show network badge only when on testnets
- Fix etherscan link for testnets
- Hide exchange fab for networks that don't support it
- Show button to request from faucet when balance === 0
> Enable all networks

- src/components/coin-row/ExchangeCoinRow.js
- src/screens/CurrencySelectModal.js
- Fix missing modal title
- Fix balance UI in the currency selection list.
> swap modal fixes

- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- src/components/exchange/CurrencySelectionList.js
- src/hoc/withDataInit.js
- src/redux/data.js
- src/references/index.js
- src/screens/CurrencySelectModal.js
- src/utils/search.js
- Minor version bump
- Shitcoin blacklist
- Uniswap search now excluding repeated tokens (symbol & name)
- Uniswap search now using "contains" matching  for stricter matching criteria
- Loading assets for uniswap search now happening on app load (fixed the nothing here ghost problem)
> Minor fixes pre-release

- src/handlers/web3.js
- src/hoc/withUniswapAssets.js
- src/redux/settings.js
- src/redux/uniqueTokens.js
- src/redux/uniswap.js
- src/references/index.js
- src/screens/CurrencySelectModal.js
- Fix network switching bug where it would stay in the wrong network after switching
- Fix currency modal not loading assets on rinkeby
- Fix assets not loading in testnets due to missing shitcoin blacklist key for each network.
> Fix testnets asset loading

- src/navigation/transitions/effects.js
This fixes the issue where the modals are not being unmounted properly.
> Fix background interpolator

- src/components/activity-list/RecyclerActivityList.js
- src/components/asset-list/RecyclerAssetList.js
- src/components/coin-row/BalanceCoinRow.js
Add padding to the first object in the list and reduce padding between swapped and received items in the activity list
> Design improvements lists

- src/screens/Routes/Routes.ios.js
Remodel routes.ios to support multiple modals backdrops
> Remodel routes.ios to support multiple modals backdrops

- src/components/exchange/ConfirmExchangeButton.js
- src/components/savings/SavingsListRow.js
- src/screens/ExchangeModal.js
- Fix the extra savings rows that show up in the wallet
- Fix the copy of the CTA while doing a deposit
> Savings fixes

- ios/Button.swift
- ios/Extensions.swift
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/TransactionListBaseCell.swift
> Change haptics from touchBegin to touchEnd

- src/raps/actions/depositCompound.js
- src/screens/ExchangeModal.js
- Fix input amount validation
- Hardcode gas price to 350k to prevent out of gas scenarios due to short estimations
> Fix deposits

- src/components/coin-row/TransactionStatusBadge.js
- src/handlers/wyre.js
- src/hooks/useWyreApplePay.js
- Podfile lock
- Fix margins for Transaction Status Badges
- Clean up sentry logging
> Apple pay fixes

- src/components/expanded-state/AddContactState.js
- src/components/layout/KeyboardFixedOpenLayout.js
Connected issue: https://linear.app/issue/RAI-204/center-contact-modal-vertically-in-send-flow
> Add padding in contact modal and recognize when to use it

- src/helpers/buildWalletSections.js
- src/hooks/useSavingsAccount.js
- Set intervals for compound queries
- Fix total balance errors on brand new wallet
> set polling interval

- ios/Extensions.swift
- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/TransactionListViewCell.xib
- ios/UIImageViewWithPersistentAnimations.swift
- ios/ViewWithPersistentAnimations.swift
Fixes: https://linear.app/issue/RAI-384/native-txn-list-spinner-stops-after-visiting-etherscan-url-and-coming
DEMO: http://recordit.co/TfdADkOSwm
> Fix spinner animation when coming from BG

- src/components/coin-row/ExchangeCoinRow.js
- src/screens/CurrencySelectModal.js
- Fix an issue with not animated stars in exchange rows
- Fix asset starring not update after changing search query (https://linear.app/issue/RAI-185/improve-asset-starring)
> Swap improvements star fix

- src/components/send/SendAssetList.js
Just realized we are not using this anymore
> Remove unused fn

- src/helpers/transactionStatusTypes.js
- src/raps/actions/swap.js
- src/raps/actions/unlock.js
- src/raps/swapAndDepositCompound.js
- src/screens/ExchangeModal.js
- Fix swap stuck receipts
- Fix unlock
- Add missing statuses and types for pending txs
> Savings clean up

- src/components/savings/SavingsPredictionStepper.js
- src/screens/SavingsSheet.js
> Fix savings predictions

- src/components/savings/SavingsPredictionStepper.js
> Fix for the three commas club

- src/App.js
- src/hooks/useInternetStatus.js
- src/raps/common.js
Also disabled analytics in dev mode.
> Added tracking for raps

- src/components/activity-list/ActivityList.js
- src/components/asset-list/RecyclerAssetList.js
- src/components/avatar-builder/ColorCircle.js
- src/components/avatar-builder/EmojiSelector.js
- src/components/avatar-builder/TabBar.js
- src/components/header/ProfileHeaderButton.js
- src/components/investment-cards/InvestmentCard.js
- src/components/profile/AvatarCircle.js
- src/components/profile/ProfileMasthead.js
- src/components/profile/index.js
- src/screens/ProfileScreen.js
Realized the avatar builder changes had a bunch of out-of-order imports
> Clean up imports

- src/components/savings/SavingsListRow.js
- yarn.lock
This change doesn't affect iOS but it does fix a crash on Android + the saving list row layout.
Before: ![Screen Shot 2020-04-01 at 3 37 26 PM](https://user-images.githubusercontent.com/1247834/78179165-c1628b80-742e-11ea-9206-162ae6b3b417.png)
After:
> Fix savings list row on Android

- src/components/coin-divider/CoinDivider.js
- src/components/investment-cards/UniswapInvestmentCard.js
- src/components/list/ListHeader.js
- src/config/debug.js
- src/styles/colors.js
but might make your eyes happy
> This is not darkmode

- src/components/coin-divider/CoinDivider.js
- src/styles/colors.js
Small balances button background disappeared, this brings it back
> Dark mode fix

- src/components/coin-row/TransactionCoinRow.js
We discussed this one today. This was fixed on the native tx list only.
Fixes https://linear.app/issue/RAI-431/
> Fix tx pending status for savings

- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Transaction.swift
- ios/TransactionListView.swift
- ios/TransactionListViewCell.swift
Changes:
--
- Reduce spacing between swap transactions
> RAI-436: Variously sized rows

- src/redux/data.js
We learned from `@bruno/savings-redux` that we were not removing subscriptions properly
> Fix uniswap subscription removal

- src/components/savings/SavingsListHeader.js
- src/components/savings/SavingsListWrapper.js
- src/hooks/useAppState.js
- src/hooks/useClearAccountData.js
- src/hooks/useInitializeAccountData.js
- src/hooks/useLoadAccountData.js
- src/hooks/useSavingsAccount.js
- src/redux/reducers.js
- src/redux/savings.js
- src/screens/ExchangeModal.js
That way we can reuse the subscription across the app
> Move savings state to redux

- src/handlers/uniswap.js
- src/helpers/utilities.js
- src/screens/ExchangeModal.js
- src/screens/SendSheet.js
- src/utils/ethereumUtils.js
There were two separate issues:
a) Zerion not returning the exact balance amount - Now defaulting to onchain value
b) Number conversion affecting decimals precision
Fixes: 
https://linear.app/issue/RAI-399/swap-max-logic-doesnt-reflect-the-total-amount
https://linear.app/issue/RAI-427/copy-pasted-max-value-does-not-work-in-swap-input
> Fix max swap logic

- src/redux/data.js
- src/redux/savings.js
We need to save the subscription and the query separate.
- We need the query to be able to call `refetch`
- We need the subscription to be able to call `unsubscribe`
> Fix graphql subscriptions

- src/components/add-cash/AddCashFooter.js
- src/components/add-cash/AddCashForm.js
- src/components/add-cash/AddCashSelector.js
- src/components/add-cash/AddCashStatus.js
- src/components/coin-row/ExchangeCoinRow.js
- src/components/expanded-state/SupportedCountriesExpandedState.js
- src/components/expanded-state/SwapDetailsState.js
- src/components/expanded-state/index.js
- src/components/floating-emojis/FloatingEmojis.js
- src/components/jelly-selector/JellySelector.js
- src/handlers/localstorage/accountLocal.js
- src/handlers/wyre.js
- src/hoc/withAccountData.js
- src/hooks/index.js
- src/hooks/useAddCashLimits.js
- src/hooks/useClearAccountData.js
- src/hooks/useLoadAccountData.js
- src/hooks/useWyreApplePay.js
- src/parsers/transactions.js
- src/redux/addCash.js
- src/redux/data.js
- src/redux/reducers.js
- src/references/index.js
- src/references/wyre/supportedCountries.js
- src/screens/AddCashSheet.js
- src/screens/ExpandedAssetScreen.js
- src/screens/Routes/Routes.ios.js
- src/screens/SavingsSheet.js
Fixes RAI-357 https://linear.app/issue/RAI-357/if-attempted-enter-amount-is-greater-than-dollar1500-yearly-limit-is
Fixes RAI-373 https://linear.app/issue/RAI-373/disable-dai-if-you-have-an-empty-wallet
> Disable DAI in Add Cash flow if you have an empty wallet 

- ios/Podfile.lock
- package.json
- yarn.lock
the problem was i never ran `yarn build` after adding the `React.forwardRef` fix 🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️🤦️https://github.com/rainbow-me/react-native-shadow-stack/commit/88a35dc5b344604fd5d2ca67c4be0a81cbe6c1c2
> Fix broken animated ShadowStack

- src/components/activity-list/RecyclerActivityList.js
> Fix profile screen isLoading check

- src/helpers/transactions.js
> Fix calculateTimestampOfThisYear function

- ios/Button.swift
- ios/Extensions.swift
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/TransactionListView.swift
- Buttons no longer block scrolling
- Tap events are no longer blocked
- Shuttering is removed on all buttons
> RAI-462: Native activity list: reimplement native list header buttons

- src/screens/Routes/Routes.ios.js
> Change status bar to black when add cash sheet is closed

- src/screens/ExchangeModal.js
- src/utils/ethereumUtils.js
Right now if you open the modal and tap max it shows 0. This PR fixes that
> Fix broken swap max logic

- src/components/add-cash/AddCashStatus.js
- src/components/coin-row/ExchangeCoinRow.js
- src/components/expanded-state/SupportedCountriesExpandedState.js
- src/components/expanded-state/SwapDetailsState.js
- src/components/floating-emojis/FloatingEmojis.js
- src/screens/SavingsSheet.js
Had some more changes locally, meant to push with previous work. Also added the emoji -> emojis rename.
> FloatingEmojis: add disableRainbow prop, rename emoji prop to emojis

- src/components/savings/SavingsListHeader.js
- src/helpers/buildWalletSections.js
- src/references/native-currencies.json
- src/screens/SavingsSheet.js
Fixes RAI-487, RAI-488, RAI-490
> Fix native currency display issues

- src/components/exchange/ConfirmExchangeButton.js
- src/handlers/uniswap.js
- src/redux/gas.js
- src/references/ethereum-units.json
- src/screens/ExchangeModal.js
- src/utils/contract.js
> Check if sufficient gas when input is not ETH

- src/hooks/index.js
- src/hooks/useCheckEthBalance.js
- src/hooks/useInitializeWallet.js
- src/hooks/useLoadAccountData.js
Fixes RAI-481
DEMO: http://recordit.co/zMRh2mMyj9
> Check eth balance when switching networks

- src/components/settings-menu/BackupSection.js
- src/helpers/validators.js
- src/hooks/useClipboard.js
- src/screens/ImportSeedPhraseSheet.js
Fixes RAI-477 https://linear.app/issue/RAI-477/import-sheet-paste-button-is-broken
> Fix broken Import sheet paste button

- src/components/coin-icon/CoinIcon.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1585255288/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> Prevent coinicon rerenders

- src/screens/ExchangeModal.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1607852557/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> Fix analytics crash while switching input asset

- src/utils/ethereumUtils.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1612655049/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
and also https://sentry.io/organizations/rainbow-me/issues/1607852474/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> Fetch onchain balance for ERC20 only

- src/handlers/localstorage/walletconnect.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1613709149/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> WC: Check available ts or ignore request

- src/helpers/utilities.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1613715235/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> Prevent crash when asset is null

- src/components/asset-list/RecyclerAssetList.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1607861489/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> Safe checks for rowHasChanged in RecyclerAssetList

- src/components/add-cash/AddCashFooter.js
> Clarify debit card support, make AddCashFooter more pressable

- src/raps/actions/unlock.js
- src/screens/ExchangeModal.js
- src/utils/allowancesCache.js
- src/utils/index.js
> Fix swap max ux issues

- src/components/animations/OpacityToggler.js
- src/components/fields/UnderlineField.js
- src/components/send/SendAssetForm.js
- src/components/send/SendAssetFormCollectible.js
- src/components/send/SendAssetFormToken.js
- src/screens/SendSheet.js
- Set height of NFT in send flow based on device height and not only on containerHeight. 
- Fix funky behavior of Input in send flow
- Replace Input with Exchange Masked Text Input to support comma in digital-pad keyboard
> Fix send flow behavior

- ios/Extensions.swift
- ios/Podfile.lock
- ios/TransactionListBaseCell.swift
- ios/TransactionListViewCell.swift
- ios/TransactionRequestSection.swift
- ios/TransactionSection.swift
- ios/TransactionViewModelProtocol.swift
- ios/TransactionViewModelTransactionItem.swift
- package.json
> RAI-449: "Pending" section for transaction list screen

- src/components/exchange/ExchangeInput.js
- src/components/exchange/ExchangeInputField.js
- src/components/exchange/ExchangeNativeField.js
- src/components/exchange/ExchangeOutputField.js
- src/components/fields/UnderlineField.js
Follow-up to https://github.com/rainbow-me/rainbow/pull/565
> Clean up send flow changes

- src/languages/index.js
- src/redux/settings.js
Fixes https://linear.app/issue/RAI-502/disable-language-settings
> Disable language settings

- src/model/wallet.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1623751752/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.9&statsPeriod=14d
and https://sentry.io/organizations/rainbow-me/issues/1606935598/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.9&statsPeriod=14d
> Add missing export for saveAddress

- src/screens/ExchangeModal.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1626280935/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.9&statsPeriod=14d
> Fix createMissingAsset crash

- src/components/coin-row/TransactionCoinRow.js
- src/components/transaction-list/TransactionList.js
- src/utils/abbreviations.js
if you click on a "purchasing" transaction in the transactionslist the app would crash from an undefined exception
> prevent undefined error when opening the actionsheet on a "purchasing" transaction

- disable-flipper.patch
This is useful for CI so we can save a lot of time while running pod install
> add patch to disable flipper if needed

- src/screens/Routes/Routes.ios.js
> Fix incorrect name of the route

- src/screens/Routes/Routes.ios.js
- src/screens/Routes/onNavigationStateChange.ios.js
Looks like nesting them makes some issues
> flatten native navigation structure

- src/references/token-overrides.json
- src/references/uniswap/uniswap-pairs.json
* Remove MANA (this is overwritten by the assets-override list, but it is not needed here)
* Update TrueUSD contract and exchange contract address
> Update Uniswap pairs list

- src/components/discover-sheet/DiscoverSheet.js
- src/handlers/topMovers.js
- src/hooks/index.js
- src/hooks/useTopMovers.js
This is for the list of top 10 gainers and losers (stored separately). It currently has USD pricing information from CMC but I will do a separate PR for consolidating with Uniswap subgraph prices.
It is attached to the DiscoverSheet which is currently hidden (experimental flag).
> Set up top movers hook

- src/handlers/localstorage/globalSettings.js
- src/references/native-currencies.json
@christianbaroni from my test I can't reproduce changing to ETH breaking anything in rewritten Wallet Screen.
> Add ETH to rewritten RLV

- src/hooks/useUniswapAssetsInWallet.js
After the fix: http://recordit.co/dFS2cBUStC
> Fix swap input currency list for rinkeby

- src/redux/data.js
- src/redux/explorer.js
- src/redux/uniswap.js
Confirmed that the swap max updates both input and output assets on wallet screen after txn confirmed
> Listen to address asset removes from Zerion

- src/redux/uniswap.js
This PR fixes the bug that was making the app  incrementally slower after running for some time.
> Fix uniswap liquidity dupes

- src/components/ContextMenu.js
- src/components/expanded-state/asset-panel/AssetPanelHeader.js
- src/components/list/ListHeader.js
- src/components/walletconnect-list/WalletConnectListItem.js
> Fix missing WalletConnect context menu, simplify ContextMenu component

- ios/TransactionViewModelTransactionItem.swift
- src/components/activity-list/RecyclerActivityList.js
- src/parsers/transactions.js
- src/raps/actions/swap.js
- src/raps/actions/unlock.js
- src/redux/data.js
* Order incoming transactions by minedAt and nonce
* Fix pending transactions from showing up in Today
* Fix incorrect type when adding a new swap pending txn
> Fix more transactions list related issues

- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Rainbow/RainbowDebug.entitlements
- ios/Rainbow/RainbowRelease.entitlements
- src/handlers/wyre.js
- src/hooks/useAccountTransactions.js
- src/hooks/useWyreApplePay.js
- src/screens/ProfileScreen.js
Previously, we only supported Mainnet in release mode and Kovan in debug mode.
Now, it doesn't matter which mode you're in, testwyre will always be available for Kovan and wyre will always be the default for Mainnet.
> Support testwyre for Kovan and wyre for Mainnet

- package.json
- src/components/coin-icon/CoinIcon.js
- src/components/coin-icon/CoinIconFallback.js
- src/components/coin-icon/index.js
- yarn.lock
Fixes initial "flash" seen on tokens which arent included in our token icon pack
Fixes RAI-599 https://linear.app/issue/RAI-599/fix-initial-flash-on-coinicon-fallback
> Improve CoinIcon's fallback image loading process

- src/styles/buildTextStyles.js
Prevent line-height from breaking emojis on android phones.
Also: fix copy address animation
> Fix emojis on Android 

- package.json
- src/components/copy-tooltip/CopyTooltip.android.js
- src/components/profile/ProfileMasthead.js
- yarn.lock
Fix address not showing in ProfMastHead and add simple copy tooltip for android
> Fix Address not showing in ProfMastHead 

- ios/TransactionListViewCell.swift
- src/components/activity-list/RecyclerActivityList.js
- src/components/coin-row/ContractInteractionCoinRow.js
- src/components/coin-row/TransactionCoinRow.js
- src/components/coin-row/TransactionStatusBadge.js
- src/parsers/transactions.js
> Fixes for txn list swap bugs

- src/components/change-wallet/WalletList.js
- src/handlers/localstorage/walletBalanceNames.js
- src/hooks/index.js
- src/hooks/useInitializeWallet.js
- src/hooks/useLoadAccountData.js
- src/hooks/useLoadGlobalData.js
- src/hooks/useWalletsWithBalancesAndNames.js
- src/model/wallet.js
https://recordit.co/fRrHKVAwli
> Use react-query for wallet balances and names

- src/components/icons/Svg.js
- src/components/layout/Flex.js
- src/components/layout/InnerBorder.js
- src/components/layout/PrimitiveWithoutOmittedProps.js
- src/components/layout/index.js
- src/components/unique-token/UniqueTokenCard.js
- src/components/unique-token/UniqueTokenImage.js
Fixes RAI-630 https://linear.app/rainbow/issue/RAI-630/collectible-and-investment-card-styles-are-no-good-after-optimize-core
> Fix broken InnerBorder styles

- ios/TransactionListBaseCell.swift
- ios/TransactionListRequestViewCell.swift
- ios/TransactionListRequestViewCell.xib
- src/screens/Routes/Routes.ios.js
- src/screens/TransactionConfirmationScreen.js
- fixes request icon masking in native activity list
- migrates tx confirmation screen to cool-modals
> WalletConnect fixes

- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/CoinRow.js
- src/components/coin-row/ExchangeCoinRow.js
- src/components/coin-row/SavingsCoinRow.js
- src/components/coin-row/SendCoinRow.js
- src/components/coin-row/TransactionCoinRow.js
- src/components/send/SendAssetFormCollectible.js
Fixes RAI-627 https://linear.app/rainbow/issue/RAI-627/coin-row-issues-after-optimize-core-pr
> Fix CoinRow issues after optimize-core PR

- src/components/activity-list/ActivityListHeader.js
- src/components/animations/OpacityToggler.js
- src/components/asset-list/AssetListItemSkeleton.js
- src/components/asset-list/RecyclerAssetList.js
- src/components/asset-list/RecyclerViewTypes.js
- src/components/coin-divider/CoinDivider.js
- src/components/coin-divider/CoinDividerAssetsValue.js
- src/components/coin-divider/CoinDividerButtonLabel.js
- src/components/coin-divider/CoinDividerEditButton.js
- src/components/coin-divider/CoinDividerOpenButton.js
- src/components/coin-divider/SmallBalancesWrapper.js
- src/components/coin-divider/index.js
- src/components/coin-icon/CoinIcon.js
- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/CoinCheckButton.js
- src/components/coin-row/CoinRow.js
- src/components/coin-row/CoinRowFavoriteButton.js
- src/components/coin-row/CollectiblesSendRow.js
- src/components/coin-row/ContractInteractionCoinRow.js
- src/components/coin-row/ExchangeCoinRow.js
- src/components/coin-row/index.js
- src/components/contacts/ContactAvatar.js
- src/components/exchange/ExchangeAssetList.js
- src/components/fab/MovableFabWrapper.js
- src/components/header/CameraHeaderButton.js
- src/hooks/index.js
- src/hooks/useCoinListEditOptions.js
- src/hooks/useCoinListEdited.js
- src/hooks/useOpenSmallBalances.js
Fixes RAI-647 https://linear.app/rainbow/issue/RAI-647/make-wallet-edit-mode-animation-smooth-again
> Make "edit mode" animation smooth again

- src/hooks/useWalletsWithBalancesAndNames.js
For clarification: this is for when a user has never opened the wallet list before, has no internet and then opens the wallet list. If they had ever opened the wallet list before with internet access, then we will always use the stored values from localstorage the next time around.
> Default to wallet data without ENS or balances if no internet

- src/hooks/useInitializeWallet.js
- src/screens/ChangeWalletSheet.js
A more ideal solution will require improvements to the useInitializeWallet hook.
Video in comments here: https://linear.app/rainbow/issue/RAI-637/reduce-delay-when-switching-wallets
> Reduce delay when switching wallets

- src/components/change-wallet/AddressRow.js
- src/screens/ModalScreen.js
- fix AddressRow positioning
- fix long wallet name truncation
- remove light status bar from ModalScreen
> WalletList style fixes

- src/components/gas/GasSpeedButton.js
- src/components/gas/GasSpeedEmoji.js
- src/components/gas/GasSpeedLabelPager.js
- src/components/gas/GasSpeedLabelPagerItem.js
- src/components/savings/SavingsPredictionStepper.js
- src/components/text/AnimatedNumber.js
- Minor cleanup/optimization of GasSpeed-related components
- applied our new `styled-components` pattern some places
Fixes RAI-28 https://linear.app/rainbow/issue/RAI-28/remove-trailing-zeros-from-gas-fees
> Remove trailing zeros from gas fees

- src/components/Link.js
> Fix link padding

- src/components/exchange/ExchangeNativeField.js
- src/components/layout/LayoutWithMargins.js
- src/hooks/useUniswapCurrencies.js
Also fixes an issue with opening swap from Deposit when you don't have the underlying asset
> Fixes for swap from expanded state

- src/components/buttons/index.js
- src/components/buttons/rainbow-button/RainbowButton.js
- src/components/buttons/rainbow-button/RainbowButtonBackground.js
- fix crashes
- re-add missing props
> Fix RainbowButton issues

- src/components/copy-tooltip/CopyTooltip.ios.js
- src/redux/navigation.js
- src/screens/Routes/Routes.android.js
- src/screens/Routes/Routes.ios.js
- src/screens/Routes/helpers.js
This value is not used anywhere but for one place where it's not really needed.
> Remove isTransitioning from redux to avoid rerenders while dismissing

- src/utils/logger.js
Probably it's pointless to have it as a class cause all properties are static
> Refactor logger

- package.json
need to add `GITHUB_TOKEN` to local path or `export GITHUB_TOKEN` each time. 
https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
> Add script for fetching .env automatically

- src/components/coin-divider/SmallBalancesWrapper.js
- src/components/sheet/SheetHandle.js
- src/screens/Routes/Routes.android.js
Fix small balances not being touchable on android
Fix closing send sheet when entering contact modal
Fix NFT modal not opening at all
> Android contact modal and small balances fixes

- ios/Rainbow.xcodeproj/project.pbxproj
- patches/@react-native-firebase+app+6.7.1.patch
- Removed old Fabric phase script which was deprecated (now running through firebase)
- Removed unused firebase setup (we're not using firebase.json config) also this step makes the build unreliable https://github.com/invertase/react-native-firebase/issues/3706
> Clean up build phases scripts

- src/hooks/useWallets.js
- src/redux/wallets.js
- src/screens/ChangeWalletSheet.js
- src/screens/ProfileScreen.js
- src/screens/WalletScreen.js
Show overlay while creating account (same as we do while importing)
> Show loading overlay while creating account

- ios/Podfile
- ios/Podfile.lock
- patches/react-native-cool-modals+0.0.9.patch
- src/screens/Routes/Routes.ios.js
fix scrollbar flickers when you first open a sheet and scroll
fix keyboard dismissing
add ignore bottom offset prop
> Fix cool-modals issues

- patches/react-native-cool-modals+0.0.9.patch
- src/components/discover-sheet/DiscoverSheet.js
- src/navigation/Navigation.js
- src/redux/reducers.js
- src/screens/QRScannerScreen.js
- src/screens/QRScannerScreenWithData.js
- src/screens/Routes/onNavigationStateChange.ios.js
- yarn.lock
I've got rid of all hacks and wrappers. Now there's no need to hide a content of discover page while opening another sheet.
> Make cool-modals and discover sheet even better friends

- ios/Rainbow.xcodeproj/project.pbxproj
- ios/SafeStoreReview.m
- src/components/settings-menu/SettingsSection.js
We're asking for a review from `SKStoreReviewController` and if fails, opening URL
> Add checker for review open and alternative URL

- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
We need to bump if we want to release
> Bump to v1.2.15

- src/components/header/ProfileHeaderButton.js
accountColor can be 0 so we need to check if it's a number instead of if it's falsey
> Fix bg color in profile header btn

- src/components/sheet/SlackSheet.js
- removed borderRadius from bottom of the sheet
- increased padding at bottom of the list for notchless phones
> Fix SlackSheet appearance on notchless phones

- src/components/exchange/ExchangeAssetList.js
Fixes RAI-684 https://linear.app/rainbow/issue/RAI-684/fix-broken-list-headers-in-currencyselectionlist
> 🥴 Fix ferkedurp list headers in CurrencySelectionList

- src/handlers/deeplinks.js
- src/redux/walletconnect.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WalletConnectApprovalSheet.js
- src/screens/WalletConnectRedirectSheet.js
We were not handling session rejections correctly on our end, so this PR fixes it
Also now we have custom redirect sheets for each request and action (approve & reject for connection, message signing and transactions).
> Handle WC rejections properly

- android/app/src/main/AndroidManifest.xml
- ios/Rainbow/Rainbow.entitlements
- ios/Rainbow/RainbowDebug.entitlements
- ios/Rainbow/RainbowRelease.entitlements
We're still waiting to hear from branch regarding the new domain config
> Add mobile deeplinking support for domain to rnbwapp.com

- ios/TransactionListBaseCell.swift
- ios/TransactionListViewCell.swift
- src/utils/pseudoRandomArrayItemFromString.js
> Add colors for not available assets in swift and refactor JS logic

- src/components/coin-row/CoinCheckButton.js
https://linear.app/rainbow/issue/RAI-686/edit-mode-bugs
> Fix check button alignment and blinking

- ios/Rainbow.xcodeproj/project.pbxproj
- ios/RainbowText.m
- src/components/savings/SavingsListRow.js
- src/components/savings/SavingsListRowAnimatedNumber.js
- src/config/experimental.js
- src/helpers/isRainbowTextAvailable.js
- src/redux/savings.js
> Optimize savings animation :car:

- src/components/AddFundsInterstitial.js
- src/components/modal/LoadingOverlay.js
- src/screens/ChangeWalletSheet.js
- src/screens/ImportSeedPhraseSheet.js
This PR shouldn't have any impact on iOS
> Make import screen work on Android 🤖

- src/components/coin-row/RequestCoinRow.js
- src/components/transaction-list/TransactionList.js
FIx crash while pressing on a WC request
> Fix navigate to requests

- src/components/expanded-state/WalletProfileCreator.js
- src/screens/ImportSeedPhraseSheet.js
- src/screens/WalletScreen.js
> remove console.log

- ios/Rainbow-Bridging-Header.h
- src/react-native-cool-modals/ios/RNCMScreen.h
- src/react-native-cool-modals/ios/RNCMScreen.m
- src/react-native-cool-modals/ios/RNCMScreenStack.m
- src/react-native-cool-modals/ios/UIViewController+slack.swift
Probably it's not the only one but def important
Before changes the number of allocated `RNCMScreen` was incremented by each push but never decremented
I made this condition fro some reasons that I don't remember now but I haven't found any regressions
> Fix memory leak in Cool Modals

- src/screens/ImportSeedPhraseSheet.js
- src/screens/ProfileScreen.js
- src/screens/WalletScreen.js
In previous implementation, components were unmounted while displaying portal thus and then effect for hiding was not called.
Now I moved it to cleaup function what seems to be an expected place for this behavior.
> Move hiding of portal to effect's cleanup

- src/components/asset-list/RecyclerAssetList.js
The refresh function was not binding this and unable to find this.state
> Fix crash on pull down to refresh

- src/screens/ImportSeedPhraseSheet.js
> Fix crash while opening non-native import sheet

- src/raps/swapAndDepositCompound.js
- src/raps/unlockAndSwap.js
In the normal swap flow, we append the exchangeAddress to each of the asset items, but we don't do the same for the expanded state flow.
> Fetch Uniswap exchange address from global list

- src/components/expanded-state/WalletProfileCreator.js
- src/react-native-cool-modals/ios/RNCMPortal.m
> Fix initial keyboard focusing

- src/components/coin-row/CoinRow.js
- src/components/contacts/ContactRow.js
- src/components/inputs/Input.js
- src/styles/buildTextStyles.js
- src/styles/colors.js
- src/styles/fonts.js
Fix fonts on an Android by adding some Android-specific logic.
> Change 🤖 fonts

- src/react-native-cool-modals/ios/UIViewController+slack.swift
- src/screens/CurrencySelectModal.js
- src/screens/ExpandedAssetSheet.js
- src/screens/SendSheet.js
- src/screens/SettingsModal.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WalletConnectApprovalSheet.js
- src/screens/WalletConnectRedirectSheet.js
> Probably fix NSInternalInconsistencyException crash

- src/screens/CurrencySelectModal.js
Fixes RAI-710 https://linear.app/rainbow/issue/RAI-710/cant-type-in-swap-search-fields
> Fix swap search input autodeleting as user types

- src/components/exchange/ExchangeInput.js
updateInputAmount was being stale because one of the subcomponents (exchangeInput) was not updating when the function would update after a new input currency was selected.
PoW: https://recordit.co/1c41QwdB2h
> Update exchange input when onChangeText function changes

- src/components/profile/ProfileMasthead.js
https://linear.app/rainbow/issue/RAI-733/copy-address-button-on-test-networks-doesnt-work
> Fix copy address in profile masthead on test networks

- src/components/savings/SavingsListRowAnimatedNumber.js
It wasn't working anyway so it actually does not change anything
> Remove usage of react-native-animated-number in SavingsListRowAnimatedNumber

- src/redux/data.js
- src/redux/savings.js
Reverts rainbow-me/rainbow#877
> Revert "Reduce number of calls to the graph for compound and uniswap"

- src/debugging/network.js
- src/model/migrations.js
- src/model/wallet.js
- src/raps/common.js
There's no need to create objects if we can access the same method statically
> replace new Date().getTime() by Date.now()

- src/components/AppVersionStamp.js
This will help us identify if a user is running a specific codepush version.
> Show codepush version under settings

- src/redux/explorer.js
- src/redux/savings.js
I change the interval poll to 120 sec. Also, I made compound fetches happens more ofter after the transaction happens
> Decrement usage of compound and uniswap graph

- src/components/AddFundsInterstitial.js
- src/components/change-wallet/AddressRow.js
- src/components/icons/svg/ThreeDotsIcon.js
- src/components/modal/ModalHeaderButton.js
- src/components/profile/AvatarCircle.js
- src/navigation/effects.js
- src/screens/ChangeWalletSheet.js
> Minor fixes for Android

- src/helpers/buildWalletSections.js
https://linear.app/rainbow/issue/RAI-690/eth-in-savings-showing-dollar0-value
> Show ETH savings values

- patches/react-native-tab-view+2.14.4.patch
- src/components/send/SendHeader.js
- src/hooks/useMagicAutofocus.js
- src/hooks/useSwapInputRefs.js
- src/navigation/ExchangeModalNavigator.js
- src/navigation/Routes.ios.js
- src/navigation/config.js
- src/navigation/nativeStackHelpers.js
- src/react-native-cool-modals/ios/UIViewController+slack.swift
- src/screens/CurrencySelectModal.js
- src/screens/ExchangeModal.js
- src/screens/ImportSeedPhraseSheet.js
- src/screens/SendSheet.js
@osdnk can you take a look at these when you have a sec? remaining to-dos:
**swap**
**savings**
> Port swap and savings to cool-modals

- src/components/coin-divider/CoinDividerButtonLabel.js
> Fix All/Less position on Android

- src/components/fields/UnderlineField.js
Recording: https://recordit.co/wECJgPetjA
> Fix one-off delay on send sheet inputs

- src/screens/SettingsModal.js
> Fix Settings nav header

- src/components/value-chart/ValueChart.js
Add this behavior: 
Also, alphabetize reanimated imports 🤭
> Add modifiers to touchX variable in charts

- ios/Rainbow.xcodeproj/project.pbxproj
- ios/TestFlight.m
- src/App.js
Let's push it prod and see what will happen
> Add TestFlight check

- src/utils/gas.js
Was unable to find the showActionSheetWithOptions export
> Fix crash when pressing gas speed button

- src/components/exchange/ExchangeInputField.js
- src/screens/ExchangeModal.js
> Fix deposit/withdraw modal corners

- src/components/send/SendTransactionSpeed.js
clock icon was missing, switched to a font icon
> Restore missing icon in send gas button

- src/screens/QRScannerScreenWithData.js
Fixes RAI-764
https://linear.app/rainbow/issue/RAI-764/qr-scanner-doesnt-stop-scanning-after-successfulfailed-scan
Fixes 2 separate issues:
a)  Stop scanning while unknown qr code until confirming alert
b) Stop scanning until the user decides to connect or reject on the WC prompt
> Fix qrcode scanner behavior

- package.json
- yarn.lock
Fixes vuln https://github.com/rainbow-me/rainbow/network/alert/yarn.lock/elliptic/open
> Bump elliptic dep

- ios/Button.swift
- patches/react-native-keychain+6.1.1.patch
- src/App.js
- src/components/settings-menu/SettingsSection.js
- src/handlers/localstorage/globalSettings.js
- src/helpers/utilities.js
- src/hooks/useAccountProfile.js
- src/hooks/useInitializeWallet.js
- src/model/keychain.js
- src/model/wallet.js
- src/redux/wallets.js
- src/screens/SettingsModal.js
5 seconds after initializing the wallet, run the checks once.
> keychain integrity checks

- src/components/AddFundsInterstitial.js
- src/components/profile/ProfileMasthead.js
- src/components/settings-menu/BackupSection.js
- src/components/transaction-list/TransactionList.js
- src/helpers/support.js
- src/model/wallet.js
- src/screens/ChangeWalletSheet.js
- src/screens/ExchangeModal.js
Show alert in the following places:
- instead of receive modal
- instead of copying address
- instead of add cash sheet
- if signing a tx fails
- if ‘show seed phrase/private key’ fails (button in settings)
- if creating a wallet fails
- add funds interstitial
> Wallet error alert

- src/App.js
- src/model/migrations.js
- src/model/wallet.js
- src/redux/wallets.js
This PR removes the damaged flag from wallets that hasn't been migrated yet.
> Add migration v3

- babel.config.js
- src/components/icons/BiometryIcon.js
- src/components/settings-menu/BackupSection.js
https://linear.app/rainbow/issue/RAI-666/include-biometry-icon-to-show-private-key-button-in-backup-section-in
> Add biometry icon to backup button

- src/components/expanded-state/ChartExpandedState.js
- src/helpers/dappNameHandler.js
- src/redux/walletconnect.js
https://linear.app/rainbow/issue/RAI-673/allow-dapp-name-overriding
https://linear.app/rainbow/issue/RAI-763/distinguish-between-assets-that-are-not-swappable-in-the-asset
> Change dapp names and hide swap button for not swappable tokens

- src/hoc/assetSelectors.js
BEFORE: ![IMG_8899](https://user-images.githubusercontent.com/1247834/90038874-e942e500-dc93-11ea-9ee4-ffb5bb45d129.PNG)
AFTER: ![IMG_8901](https://user-images.githubusercontent.com/1247834/90038871-e942e500-dc93-11ea-9792-a56d0cbc692b.PNG)
> Dont show percentage change if zerion returns null

- ios/Rainbow/Info.plist
- ios/TransactionListViewHeader.xib
- src/components/backup/BackupConfirmPasswordStep.js
- src/components/backup/BackupIcloudStep.js
- src/handlers/cloudBackup.js
- src/hooks/useWalletCloudBackup.js
Includes
* Update backup iCloud password strength emojis
* Update FaceID usage description
* Replace DEADBEEF with "Initializing..." and blank gray avatar background
* Prevent crash when accessing walletId from undefined params in dependency list
* Fix default checkmarks in backup password confirmation
> Small tweaks

- src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
- src/components/coin-row/CollectiblesSendRow.js
- src/components/coin-row/SendCoinRow.js
- src/components/coin-row/SendSavingsCoinRow.js
- src/components/fields/UnderlineField.js
- src/components/send/SendAssetForm.js
- src/components/send/SendAssetFormField.js
- src/components/send/SendAssetFormToken.js
- src/components/send/SendHeader.js
- src/screens/SendSheet.js
> Fix iPhone SE send flow

- ios/Button.swift
- src/navigation/Navigation.js
- src/navigation/routesNames.js
- src/react-native-cool-modals/ios/RNCMPortal.m
- src/react-native-cool-modals/ios/UIViewController+slack.swift
1. I observed that it's possible to open two modals in the same time by pressing quickly two buttons. I fixed it and it probably will stop some problems with class casting.
2. I fixed sone problems with swift optional to make sure they're always present when needed.
I think it can also reduce (or remove) the issue with freezing of buttons, but I'm not sure!
> Fix inconsistency native crash

- src/components/coin-row/SendCoinRow.js
- src/handlers/assets.js
- src/hooks/index.js
- src/hooks/useUpdateAssetOnchainBalance.js
- src/screens/SendSheet.js
And update if balance is different to what we have from zerion.
DEMO with a fake onchain balance of 10 AMPL and 10 ETH: https://recordit.co/6exXm1q0wu
> Check onchain balance while selecting asset in send flow

- package.json
- src/handlers/cloudBackup.js
- src/hooks/useWalletCloudBackup.js
- yarn.lock
> Detect if iCloud drive is enabled before backing up

- src/components/backup/BackupConfirmPasswordStep.js
We are already doing it before redirecting the user to that sheet.
> Don't fetch pass on backup confirm step

- ios/Podfile.lock
- src/components/AppVersionStamp.js
- src/components/backup/BackupManualStep.js
- src/components/settings-menu/SettingsSection.js
- src/hooks/index.js
- src/hooks/useAppVersion.js
- src/screens/SettingsModal.js
- tsconfig.json
- yarn.lock
Fixes RAI-777 https://linear.app/rainbow/issue/RAI-777/settings-version-label-needs-to-be-repositioned
> Fix positioning of App Version stamp shown in Settings modal

- src/hooks/useInitializeWallet.js
Reverts rainbow-me/rainbow#1009
While this looks good, we didn't have a chance to analyze the consequences of sending the user to the wallet while some of the stuff isn't ready.
There are scenarios to consider like:
- an user who reinstalled the app (there's no cached data)
- new users (no cached data)
I'm gonna revert and keep the PR open to review and test it properly.
> Revert "Tweak logic make emergency exit after 10 sec timeout on splash screen "

- package.json
- src/components/coin-row/ExchangeCoinRow.js
- src/components/expanded-state/SupportedCountriesExpandedState.js
- src/components/floating-emojis/ComingSoonFloatingEmojis.js
- src/components/floating-emojis/FloatingEmojis.js
- src/components/settings-menu/SettingsSection.js
- src/components/text/Emoji.js
- src/references/emojis.json
- src/references/index.js
- src/references/wyre/supportedCountries.js
- tsconfig.json
- yarn.lock
this one emoji package i use was unstable, but now all the emojis should work
> stablize emoji related deps + fix missing emojis

- src/helpers/walletLoadingStates.js
- src/hooks/useWalletCloudBackup.js
The idea is to improve the UX for the scenario when two authentication requests trigger right after the other.
> Better UX on password auth + backup auth requests

- src/screens/TransactionConfirmationScreen.js
Validates amount + txFee before letting a WC transaction to be sent.
(before we were only checking that the balance was enough to pay for gas, ignoring the TX amount)
> Validate balance before wc tx

- src/components/backup/BackupManualStep.js
- src/components/expanded-state/WalletProfileState.js
- src/components/floating-emojis/CopyFloatingEmojis.js
- src/components/profile/ProfileMasthead.js
- src/components/savings/SavingsListRow.js
- src/components/secret-display/SecretDisplaySection.js
- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/settings-menu/BackupSection/NeedsBackupView.js
- src/components/settings-menu/BackupSection/WalletSelectionView.js
- src/handlers/walletReadyEvents.js
- src/hooks/useWalletCloudBackup.js
- src/hooks/useWallets.js
- src/navigation/index.js
- src/screens/BackupSheet.js
- src/screens/ImportSeedPhraseSheet.js
- src/screens/QRScannerScreen.js
- src/screens/RestoreSheet.js
- src/screens/SavingsSheet.js
also exports useNavigation from src/navigation/index.js
thats it.. thats all this PR does
> Update imports to utilize @rainbow-me/ alias shortcuts

- src/components/buttons/BiometricButtonContent.js
- src/components/buttons/Button/Button.ios.js
- src/components/buttons/index.js
- src/components/expanded-state/WalletProfileState.js
- src/styles/buildFlexStyles.js
- Fixes way core `<Button />` component handles style prop
- Creates BiometricButtonContent which handles the logic for deciding which biometric icon to use within buttons.
> Create reusable BiometricButtonContent component

- src/components/AddFundsInterstitial.js
- src/hooks/useWalletCloudBackup.js
- The fetching password modal was stuck. Using the hook instead of dispatching fixed the issue.
- Removed an old console.log
> Minor fixes icloud

- src/components/secret-display/SecretDisplayCard.js
still gonna change it to something better tho just didnt want to forget
> better react keys in secretdisplaycard

- package.json
- yarn.lock
Fixes this warning: https://github.com/rainbow-me/rainbow/network/alert/yarn.lock/bl/open
> Fix bl dep vuln

- src/components/toasts/TestnetToast.js
Proof of work: http://recordit.co/fdCdmbiSxv
> Fix testnet toast

- src/components/expanded-state/chart/ChartContextButton.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/references/token-overrides.json
Links to token contract on Etherscan:
> Add 'View on Etherscan' to expanded state action sheet, add $BASED

- .eslintrc.json
- global.js
- src/components/settings-menu/DevSection.js
- src/components/settings-menu/SettingsSection.js
- src/config/experimentalHooks.js
- src/helpers/DevContext.js
- src/screens/SettingsModal.js
Blocked by https://github.com/rainbow-me/rainbow-env/pull/3
> Enable ganache release mode

- ios/Button.swift
Maybe it will help with not blocking buttons, but I'm not sure
> Block animation on moving when button gets invalidated

- ios/Button.swift
- src/model/keychain.ts
- src/model/wallet.ts
Fix this:
https://streamable.com/4ev0rk
> Don't show error box when user cancel touchId

- .gitignore
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Rainbow/AppDelegate.mm
if you add `DISABLE_REANIMATED_IN_DEV=YES` it will compile w/o reanimated
> Add DISABLE_REANIMATED basing on ENV

- src/navigation/config.js
- src/react-native-cool-modals/NativeStackView.js
- src/react-native-cool-modals/ios/RNCMScreen.m
- src/react-native-cool-modals/ios/UIViewController+slack.swift
I made it available by default
> Make TEMPORARY_autoJumpToNewHeight no longer needed

- src/components/settings-menu/SettingsSection.js
- src/redux/addCash.js
- src/utils/reviewAlert.js
Closes RAI-522
@christianbaroni @jinchung Please check copies
> Ask for review after adding cash

- src/screens/SettingsModal.js
>  Fix aligning of header nav bar in SettingsModal on Android

- src/components/list/ListFooter.js
- src/components/settings-menu/SettingsSection.js
> Fix App version stamp in Settings

- e2e/importFromSeed.spec.js
- src/screens/WelcomeScreen.js
I know it's not perfect and it's nothing compared to https://github.com/rainbow-me/rainbow/pull/856/files, but maybe worth to include to unblock CI
> Temporarily fix e2e

- src/components/fields/UnderlineField.js
doesn't break the sheet anymore!
> Fix broken send sheet

- src/components/send/SendAssetFormToken.js
- src/components/send/SendHeader.js
> Fix send sheet on iPhone 8

- src/components/savings/SavingsSheetEmptyState.js
Proof of work: 
- ![Screen Shot 2020-09-22 at 7 26 04 PM](https://user-images.githubusercontent.com/1247834/93947365-82d8ca00-fd09-11ea-8152-d6842da030d6.png)
- ![Screen Shot 2020-09-22 at 7 26 17 PM](https://user-images.githubusercontent.com/1247834/93947366-82d8ca00-fd09-11ea-901a-9c5b38ad084a.png)
> Fix params for empty savings sheet

- src/components/backup/BackupIcloudStep.js
- src/components/sheet/SlackSheet.js
- src/hooks/useMagicAutofocus.js
https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1600445261038300?thread_ts=1600370627.083600&cid=CGUDDJYNL
> Refocus on inputs on backup sheet

- src/navigation/Routes.ios.js
https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1600776243039400
> Fix import sheet on old iOS devices

- src/handlers/web3.js
- src/parsers/uniqueTokens.js
- src/references/smartcontract-methods.json
DEMO: http://recordit.co/ZXQ9nVpCDq
> Add support for sending ERC-1155

- src/components/fields/UnderlineField.js
- src/components/send/SendAssetFormField.js
- src/components/send/SendAssetFormToken.js
this fixes the crash but breaks the underline's animation -- trying to figure out how to fix animation now
> fix send crash caused by rea2

- src/config/experimental.js
> Remove newOnboardingFlow from experimental flags

- e2e/importPrivateKeyFlow.spec.js
- e2e/importSeedFlow.spec.js
- e2e/newWalletFlow.spec.js
- e2e/sendSheetFlow.spec.js
- src/components/animations/ButtonPressAnimation/NativeButton.js
- src/components/buttons/AddContactButton.js
- src/components/buttons/PasteAddressButton.js
- src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
- src/components/coin-row/CoinRow.js
- src/components/coin-row/CollectiblesSendRow.js
- src/components/coin-row/SendCoinRow.js
- src/components/coin-row/SendSavingsCoinRow.js
- src/components/expanded-state/ContactProfileState.js
- src/components/expanded-state/profile/ProfileAvatarButton.js
- src/components/expanded-state/profile/ProfileNameInput.js
- src/components/fab/ExchangeFab.js
- src/components/fab/SendFab.js
- src/components/fields/AddressField.js
- src/components/icons/Icon.js
- src/components/send/SendAssetForm.js
- src/components/send/SendAssetFormField.js
- src/components/send/SendAssetFormToken.js
- src/components/send/SendAssetList.js
- src/components/send/SendButton.js
- src/components/send/SendContactList.js
- src/components/send/SendHeader.js
- src/screens/ExchangeModal.js
- src/screens/ProfileScreen.js
Full e2e testing for sendSheet interaction flow
> @skylar/send sheet interaction flow final

- src/components/savings/APYPill.js
I observed that this leads to blocking UIThread from some unknown to me reason. However, I think it's not a big problem to leave is as a regular text.
Before: 
https://streamable.com/bii7cy
After:
https://streamable.com/jllw5u
Those lines represent visual updates on a native thread
> Update APYPill not to use MaskedView on Android

- src/components/settings-menu/SettingsSection.js
video of what it looks like https://share.getcloudapp.com/qGuv1K72
> add Share Rainbow button to Settings

- src/components/coin-row/CoinName.js
- src/components/coin-row/CoinRow.js
- src/components/fields/AddressField.js
- src/components/fields/UnderlineField.js
- src/components/modal/LoadingOverlay.js
- src/components/send/SendAssetForm.js
- src/components/send/SendAssetFormField.js
- src/components/send/SendAssetFormToken.js
- src/components/send/SendHeader.js
- src/screens/ImportSeedPhraseSheet.js
- src/styles/fonts.js
- SendSheet layout fixed
- ImportSeedPhraseSheet layout fixed
- Changed spinner on LoadingOverlay
> More Android fixes

- src/components/modal/Modal.js
- src/navigation/Routes.android.js
- src/screens/SettingsModal.js
> Redesing settings on Android

- src/handlers/walletReadyEvents.js
- src/navigation/config.js
- src/react-native-cool-modals/NativeStackView.js
- src/redux/data.js
- src/screens/ImportSeedPhraseSheet.js
https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1601468875059700
> Add single param to cool-modals + make backup sheet not interact with other modals

- patches/@rainbow-me+react-native-payments+1.1.5.patch
Fixes: https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1601364964038800
> Add payments' patch

- android/app/build.gradle
- android/app/src/main/java/me/rainbow/MainApplication.java
- android/app/src/main/java/me/rainbow/RNBip39/RNBip39Module.java
- android/app/src/main/java/me/rainbow/RNBip39/RNBip39Package.java
- ios/Podfile.lock
- package.json
- src/handlers/web3.js
- src/helpers/walletLoadingStates.js
- src/model/wallet.ts
- src/screens/ChangeWalletSheet.js
- src/screens/ImportSeedPhraseSheet.js
- src/utils/ethereumUtils.js
- yarn.lock
- Changed the libraries used to generate wallet seeds based on mnenonics
- Wrote RNBip39 native module to run generate the wallet seed natively which is +100x faster (120ms vs 14s)
Those two changes result in much faster wallet creation during:
- Welcome screen => Get a new Wallet
- Welcome Screen => I already have one => Restore with a recovery phrase
- Change wallet => Import an existing wallet
- Change wallet => Create a new wallet.
Other minor changes:
- Minor UI fix for the ImportSeedPhraseSheet that was breaking iOS styles
- Added LoadingOverlay while creating wallets.
> Faster wallet creation

- package.json
- src/App.js
- src/components/buttons/PasteAddressButton.js
- src/components/send/SendContactList.js
- src/components/settings-menu/DevSection.js
- src/components/toasts/InvalidPasteToast.js
- src/components/toasts/Toast.js
- src/components/toasts/ToastPositionContainer.js
- src/components/toasts/index.js
- src/config/experimentalHooks.js
- src/helpers/RainbowContext.js
- src/hooks/index.js
- src/hooks/useClipboard.js
- src/hooks/useInvalidPaste.js
- src/screens/ImportSeedPhraseSheet.js
- src/utils/deviceUtils.js
- yarn.lock
- Removes excessive triggering of the new iOS 14 alert that happens when accessing clipboard
- Shows a Toast on iOS 14 when the user tries to paste something thats an invalid entry for the currently focused field
GIF of the new `InvalidPasteToast`
> Fix iOS 14 related Clipboard bugs + UX weirdness

- src/hooks/useClipboard.js
oops my first PR broke iOS 13 but this fixes it fosho
> fix clipboard regression for ios 13 devices

- src/raps/actions/depositCompound.js
Fixes RAI-601 https://linear.app/rainbow/issue/RAI-601/investigate-savings-deposit-button-not-working-maybe-just-for-touchid
> Fix broken Deposit functionality in 🌻️ Savings flow

- patches/recyclerlistview+3.0.0.patch
> Add patch for RLV 3.0

- src/screens/ReceiveModal.js
> Fix QR code in Receive modal on Android

- src/components/expanded-state/chart/chart-data-labels/ChartChangeDirectionArrow.js
- src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
> Use better arrow in charts on android

- src/components/savings/AndroidAnimatedNumbers.js
- src/components/savings/SavingsListRowAnimatedNumber.js
- src/components/sheet/sheet-action-buttons/SheetActionButton.js
- src/helpers/savings.js
For now w/o colors
https://streamable.com/ytwkrt
> Savings animation on Android

- package.json
- src/components/expanded-state/ChartExpandedState.js
- src/components/sheet/SlackSheet.js
- src/screens/BackupSheet.js
- src/screens/SavingsSheet.js
- yarn.lock
> Fix savings sheet layout

- bitrise.yml
This has no effect in our build process. It's just a backup of the current working config
> Update Bitrise config

- src/components/exchange/ExchangeAssetList.js
- src/handlers/uniswap.ts
- src/screens/CurrencySelectModal.js
DEMO: https://recordit.co/KZwT7VPS11
Also fixes the query for the uniswap graph that wasn't running.
> New headers on token search

- src/screens/WelcomeScreen.js
> Fix welcome screen on android

- src/components/asset-list/RecyclerAssetList.js
It should be removed before some merge
> Remove invalid comments

- src/components/savings/AndroidAnimatedNumbers.js
Initially, I made each character animated separately to make it easy to add colors. But for now, we don't support it anyway and I observed some weird behavior (cutting come characters) – I'll just revert this PR if we'd like to have colors implemented
> Simplify code for savings

- src/components/backup/BackupSheetSection.js
- src/components/buttons/rainbow-button/RainbowButton.js
- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/sheet/sheet-action-buttons/SheetActionButton.js
Fixes ripples in the import sheet and change colors of a bottom button in BackupSheet on Android (because it has no shadows so far)
> Fix more ripples + change colors of buttons

- src/components/expanded-state/LiquidityPoolExpandedState.js
- src/components/unique-token/UniqueTokenCard.js
- src/components/unique-token/UniqueTokenRow.js
- src/helpers/buildWalletSections.js
- src/navigation/Routes.android.js
- src/navigation/routesNames.js
> Fix polls layout on Android

- src/components/coin-divider/CoinDivider.js
- src/components/coin-icon/CoinIcon.js
- src/components/coin-icon/CoinIconIndicator.js
- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/CoinCheckButton.js
- src/components/coin-row/CoinRow.js
- src/hooks/useCoinListEdited.js
- src/redux/editOptions.js
I observe that entering the "edit" mode is not optimized. It takes a few seconds in dev mode. 
I rewrote it using Reanimated instead of modifying the React hierarchy
> Optimize coin list's edit

- src/handlers/walletReadyEvents.js
- src/navigation/onNavigationStateChange.js
- src/redux/data.js
We don't want to display backup sheet e.g. on Exchange modal
> Delay showing backup sheet

- src/components/modal/Modal.js
- src/navigation/onNavigationStateChange.js
- src/screens/DepositModal.js
- src/screens/ExpandedAssetSheet.js
- src/screens/SettingsModal.js
- src/screens/WalletScreen.js
- src/screens/WithdrawModal.js
It does not fix all issues. Send flow is still broken, but it conflicts with other changes
> Simplify status bar handling

- src/components/activity-list/ActivityList.js
- src/components/activity-list/RecyclerActivityList.js
- src/components/coin-row/TransactionCoinRow.js
- src/helpers/transactions.js
- src/hooks/useAccountTransactions.js
- src/screens/ProfileScreen.js
I see it might be a bit faster, but I'm still not sure about the performance 
(imagine that icons are not dropped)
> Rewrite activity list for using section list + Add pagination

- src/components/avatar-builder/Categories.android.js
- src/components/avatar-builder/EmojiSelector.js
- src/components/profile/AvatarCircle.js
- src/components/profile/ProfileMasthead.js
- src/config/experimental.js
And Improve performance of emoji picker on android when available.
Also fix photo avatar on android.
> Fix Avatar Picker on Testnets

- src/raps/actions/swap.js
- src/raps/actions/unlock.js
- src/raps/swapAndDepositCompound.js
- src/raps/unlockAndSwap.js
- src/redux/multicall.ts
- src/screens/ExchangeModal.js
- src/screens/TransactionConfirmationScreen.js
- src/utils/measureText.js
- Fix custom gas for WC requests
- Fix custom gas for Swap,  Savings Deposit & Withdraw
- Fix custom gas for unlock (Use max between selectedGasPrice & Fast)
> Fix custom gas issues

- src/components/buttons/rainbow-button/RainbowButton.js
- src/components/modal/Modal.js
- src/components/settings-menu/BackupSection/NeedsBackupView.js
> Fix NeedsBackupView layout on android

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
https://linear.app/rainbow/issue/RAI-851/edit
> Remove cancel button from UniqueTokenExpandedStateHeader

- src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/components/expanded-state/profile/ProfileNameInput.js
- src/components/gas/GasSpeedButton.js
- src/components/savings/AndroidAnimatedNumbers.js
- src/styles/buildTextStyles.js
- src/styles/index.js
I found that it's possible to use bold `SF-pro-rounded` on Android (it text inputs) so I've refactored the code to make it workable
> Fix fonts in Text inputs

- src/components/buttons/rainbow-button/RainbowButtonBackground.js
> Fix overlay in import button

- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartHeaderSubtitle.js
- src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
> Adjust header in ChartExpandedState on android

- src/helpers/utilities.ts
I was trying to be clever while I was doing the initial TS migration for the utilities file - I'm reverting the logic changes I did for now while keeping the typings.
Fixes: https://linear.app/rainbow/issue/RAI-900/number-formatting-issues
> Fix decimal formatting

- src/components/coin-row/ExchangeCoinRow.js
closes https://linear.app/rainbow/issue/RAI-890/fav-button-is-not-exclusive
> Fix fav button on Android in currency selection modal

- e2e/ganacheTransactionFlow.spec.js
- e2e/swapSheetFlow.spec.js
e2e flakiness is due to slower search results in CurrencySelection, this fixes
> fix e2e flakiness due to slower search

- ios/Podfile.lock
- package.json
- src/components/contacts/ContactAvatar.js
- src/components/contacts/ImageAvatar.js
- src/components/fields/PasswordField.js
- src/components/secret-display/SecretDisplayCard.js
- src/react-native-shadow-stack/ShadowItem.js
- src/react-native-shadow-stack/ShadowStack.js
- src/react-native-shadow-stack/ShadowView.js
- src/react-native-shadow-stack/index.js
- tsconfig.json
- yarn.lock
> Fix shadows on Android

- src/components/expanded-state/ChartExpandedState.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/config/experimental.js
- src/redux/explorer.js
saw this while adding a debug flag, look's like its hardcoded to true and isnt changed anywhere
> remove chartExpandedAvailable flag

- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/settings-menu/BackupSection/WalletSelectionView.js
Added an option to delete all backups with double confirmation.
PoW - single wallet: http://recordit.co/ZOyLbMTjig
PoW - multiple wallets: http://recordit.co/XqZLVwvzwz
> Allow to delete all backups

- android/app/src/main/java/me/rainbow/MainActivity.java
- android/app/src/main/java/me/rainbow/MainApplication.java
- package.json
- src/components/AddFundsInterstitial.js
- src/components/profile/ProfileMasthead.js
- src/handlers/wyre.js
- src/hooks/useWyreApplePay.js
- src/navigation/Routes.android.js
- src/navigation/routesNames.js
- src/screens/ProfileScreen.js
- src/screens/WyreWebview.js
- yarn.lock
This re-enables all Apple Pay features for Android but defaults to wyre checkout widget through a webview instead of showing the Add Cash sheet.
DEMO: http://recordit.co/Ifgq4vEupX
@christianbaroni  Waiting for your feedback on how to make the navbar look better
> Wyre widget android

- patches/react-native-slack-bottom-sheet+0.5.0.patch
- src/components/discover-sheet/DiscoverSheet.js
- src/components/discover-sheet/DiscoverSheetContext.js
- src/components/discover-sheet/DiscoverSheetHeader.js
> Make buttons workable in discover header

- patches/react-native-slack-bottom-sheet+0.5.0.patch
- src/components/discover-sheet/DiscoverSheet.js
- src/components/discover-sheet/DiscoverSheetContent.js
- src/components/discover-sheet/DiscoverSheetContext.js
- src/components/discover-sheet/DiscoverSheetHeader.js
- src/components/discover-sheet/PulseIndexSection.js
- src/components/discover-sheet/SearchHeader.js
- src/components/discover-sheet/StrategiesSection.js
- src/components/discover-sheet/TopMoversSection.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/list/MarqueeList.js
- src/components/sheet/SlackSheet.js
I created a skeleton of Discover sheet
> @osdnk/skeleton

- package.json
- src/App.js
- src/components/activity-list/ActivityList.js
- src/components/coin-row/RequestCoinRow.js
- src/components/gas/GasSpeedLabelPager.js
- src/components/walletconnect-list/WalletConnectListItem.js
- src/helpers/buildTransactionsSectionsSelector.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WalletConnectApprovalSheet.js
- yarn.lock
There were a bunch of problems from deeplinks to missing logic and UI issues.
After fixes:
Fixes RAI-871
> Fix WC on android

- src/components/buttons/rainbow-button/RainbowButton.js
> Fix shadows with Rainbow Button on Android

- src/hooks/useTopMovers.js
1. Remove top movers with missing price info.
2. Log to Sentry those with missing price info as this likely means there is a discrepancy in the contract addresses used between Zerion and CMC.
> Remove and Sentry log top movers with missing price info.

- src/components/expanded-state/LiquidityPoolExpandedState.js
> fix LP expanded state height on android

- src/react-native-shadow-stack/ShadowStack.js
> Fix broken shapes with shadows on Android

- src/components/gas/GasSpeedButton.android.js
- src/components/gas/GasSpeedButton.ios.js
During android dev. this component was completely refactored, breaking some of the look & feel (animation, styling) of this component.  I'm keeping the old version as the iOS one since it works exactly how we want.
If in the future we keep evolving it, we might want to consider unifying but for now it's not worth the effort.
> split GasSpeedButton for each OS

- src/screens/WyreWebview.js
Made the navbar android standar.
Before:
After:
> Fix wyre webview header

- src/react-native-shadow-stack/ShadowStack.js
Gotta be careful when testing this because hot reload doesn't always reflect the change. 
It's better to restart the app
After fix:
> Fix shadows again

- android/app/src/main/java/me/rainbow/MainApplication.java
- android/app/src/main/java/me/rainbow/NativeModules/RNTextAnimatorPackage/RNTextAnimatorPackage.java
- src/components/savings/AndroidAnimatedNumbers.js
`tabular-numms` does not work for some reason, but we can skip it I guess for now.
> Fix animated numbers on savings in Android

- android/app/src/main/java/me/rainbow/NativeModules/RNTextAnimatorPackage/RNTextAnimatorPackage.java
- src/components/savings/SavingsListRowAnimatedNumber.js
Now it looks like
https://streamable.com/jyjgvg
I think that I need to unify it and make it a coherent cross-platform native module
> Make savings animation respecting tabular-nums and green

- src/model/wallet.ts
- src/screens/ImportSeedPhraseSheet.js
- src/utils/ethereumUtils.js
I broke the watch address logic which caused importing a different read only address than the want you input.
To verify it works, just import `vitalik.eth` and you should see ~ 1M USD in that account.
Before the fix that wallet was empty
> Fix watch adddress flow

- src/components/expanded-state/LiquidityPoolExpandedState.js
- src/components/expanded-state/liquidity-pool/LiquidityPoolExpandedStateHeader.js
- src/components/token-info/TokenInfoBalanceValue.js
- src/handlers/uniswapLiquidity.ts
- src/screens/SavingsSheet.js
> Uniswap LP token fixes

- src/components/Link.js
- src/components/coin-divider/CoinDividerOpenButton.js
- src/components/coin-row/BalanceCoinRow.js
- src/components/expanded-state/WalletProfileState.js
- src/components/send/SendAssetList.js
> Fix ripple in few more places on Android

- src/components/secret-display/SecretDisplaySection.js
- src/screens/SettingsModal.js
- src/screens/WyreWebview.js
- Fixes RAI-941 - Manual Backup freezes the app
- Centers the title and use correct font styles in settings & Wyre Webview
> Backup fixes android

- src/components/AddFundsInterstitial.js
- src/components/profile/ProfileMasthead.js
- src/navigation/Routes.android.js
- src/navigation/config.js
- src/navigation/routesNames.js
- src/screens/WyreWebview.js
> use real navigator header for WyreWebview

- ios/Rainbow.xcodeproj/xcshareddata/xcschemes/Rainbow.xcscheme
- src/components/AddFundsInterstitial.js
- src/navigation/routesNames.js
> Fix shadows in AddFundsInterstitial on android

- ios/Rainbow.xcodeproj/xcshareddata/xcschemes/Rainbow.xcscheme
- src/components/AddFundsInterstitial.js
- src/navigation/routesNames.js
> Add Cash text/button gradient

- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
Fix native characters in Android's charts
> Fix native characters in Android's charts

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/sheet/sheet-action-buttons/SheetActionButton.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WalletConnectApprovalSheet.js
> Fix WC sheets

- src/components/exchange/ExchangeAssetList.js
- src/components/exchange/ExchangeSearch.js
- src/components/expanded-state/ChartExpandedState.js
- src/components/secret-display/SecretDisplaySection.js
- src/components/send/SendHeader.js
- src/navigation/effects.js
- Adjust chart expanded state height
- Fix CurrencySelectList header to fit in one line
- Fix exchange search icon alignment
- Fix spinner for android on SecretDisplaySection
- Fix SendSheet crash
- Add Sheet handle to SendSheet
> Minor fixes

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/savings/SavingsListRow.js
A hack on top of @osdnk hack to get the ripple effect working without breaking the onPress behavior
PoW: http://recordit.co/nhFgwONFaP
> Fix savings on android

- src/screens/PinAuthenticationScreen.js
Added a delay at the end of pin entry
Before: https://cloud.skylarbarrera.com/Screen-Recording-2020-11-20-12-21-13.mp4
After: https://cloud.skylarbarrera.com/Screen-Recording-2020-11-20-12-16-15.mp4
> add a quick timeout to pin screen

- src/components/send/SendHeader.js
> Fix sendsheet handle

- src/components/walletconnect-list/WalletConnectList.js
> Fix keyExtractor of WalletConnectList

- src/components/settings-menu/SettingsSection.js
- src/hooks/useSendFeedback.js
Changed the copy on android for the beta, added OS & app version to feedback email subject line
@christianbaroni looks the same as before on iOS. I was initially gonna add another list item but I think this makes more sense.
I prefer with the extra comma but it's a personal preference, lmk you thoughts
no comma: https://cloud.skylarbarrera.com/Screen-Shot-2020-11-20-12-34-12.16.png
with comma: https://cloud.skylarbarrera.com/Screen-Shot-2020-11-20-12-34-50.55.png
> Android Bug Reporting Copy

- src/navigation/Routes.android.js
- src/navigation/effects.js
- src/screens/ImportSeedPhraseSheet.js
PoW 1: https://recordit.co/HvvCjQmdWk
PoW 2: http://recordit.co/1GbFXZTfCp
> Import sheet fixes

- package.json
- scripts/update-token-list.sh
- src/references/uniswap/rainbow-token-list.json
The idea is to run `yarn update-token-list` after running `yarn install` on CI
> Add update token list script

- src/components/backup/RestoreSheetFirstStep.js
Icons were cut off on android
Before: https://cloud.skylarbarrera.com/Screenshot_20201123-101402_Rainbow.jpg
After: https://cloud.skylarbarrera.com/Screenshot_20201123-102356_Rainbow.jpg
> fix import icons on android

- src/entities.ts
- src/handlers/uniswap.ts
- src/parsers/accounts.js
- src/parsers/transactions.js
- src/redux/data.js
- src/redux/savings.js
- src/redux/uniswap.js
- src/references/index.ts
- tsconfig.json
tokenOverrides was in redux and being passed along as a parameter unnecessarily.
Also started an entities file for some shared wallet-data-related types I'd like to add on to.
> Cleanup tokenOverrides usage

- src/screens/SendSheet.js
PoW: http://recordit.co/YHbjPlWiZ5
> Fix sendsheet keyboard behavior on Android

- patches/@react-native-community+viewpager+4.1.0.patch
Let's leave it like this until this is not merged https://github.com/callstack/react-native-viewpager/pull/245
> Fix viewpager not scrolling smoothly

- src/components/buttons/TokenSelectionButton.js
- src/components/exchange/ExchangeField.js
- src/components/profile/ProfileMasthead.js
- src/components/qr-code/ShareButton.js
- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/sheet/sheet-action-buttons/SheetActionButton.js
- src/screens/SavingsSheet.js
- src/screens/WalletConnectApprovalSheet.js
Fixes:
- shadows charts: https://cloud.skylarbarrera.com/Screenshot_20201125-125236_Rainbow.jpg
- shadows receive: https://cloud.skylarbarrera.com/Screenshot_20201125-125523_Rainbow.jpg
- shadows WC: https://cloud.skylarbarrera.com/Screenshot_20201125-125415_Rainbow.jpg
- size issue swap: https://cloud.skylarbarrera.com/Screenshot_20201125-125059_Rainbow.jpg
- text overflow due to sizing: https://cloud.skylarbarrera.com/Screenshot_20201125-125442_Rainbow.jpg
- Add cash shadows
- Savings Sheet button shadows
> shadow fixes

- src/components/sheet/SlackSheet.android.js
- src/components/token-family/TokenFamilyHeader.js
- src/navigation/Routes.android.js
- src/navigation/effects.js
- Fix flash on Collectibles Family Header
- Fix bottom rounder corners on SlackSheet
- Fix WC prompts (only connect & redirect to browser) opacity.   - it was all black and changed it to 0.7 to match iOS
> More android tweaks

- src/components/settings-menu/SettingsSection.js
aesthetics change 🦋 🐛  🐝  🐞  🐜  🕷️ 🕸️  🦂  🦗 🦟
https://cloud.skylarbarrera.com/Screenshot_20201127-120335_Rainbow.jpg
> change android bug emoji

- src/components/qrcode-scanner/QRCodeScanner.js
instead of mounting and unmounting I used imperatively methods for this case
> Fix pausing and restoring preview on Android

- src/components/qrcode-scanner/CameraDimmer.js
Now it's not getting all c=black after the transition
> Fix camera dimming on Android

- src/components/gas/GasSpeedButton.android.js
> Fix gas button placeholder

- src/components/backup/BackupSheetKeyboardLayout.js
The button was hiding before the keyboard.
After the fix:
> Fix backup / restore sheets keyboard

- src/components/gas/GasSpeedButton.android.js
This got introduced while accepting a commit suggestion via gh comment
> Fix linter error

- src/components/coin-row/BalanceCoinRow.js
- src/components/expanded-state/ChartExpandedState.js
not the most eloquent solution but will work for now
before: https://cloud.skylarbarrera.com/Screenshot_20201123-170316_Rainbow.jpg
after:
android: https://cloud.skylarbarrera.com/Screen_Recording_20201123-165848.mp4
ios: https://cloud.skylarbarrera.com/Screen-Recording-2020-11-23-16-54-54.mp4
> fix sheet height for no data on charts - android

- src/screens/QRScannerScreen.js
Before the fix: http://recordit.co/KmqfIUzdvB
After the fix: http://recordit.co/oW1sHbK90U
> Fix camera init on Android

- src/screens/RestoreSheet.js
Before: https://cloud.skylarbarrera.com/Screen-Recording-2020-11-30-12-28-25.mp4
After: http://recordit.co/4H9HoqCkzW
> Fix import sheet overlay again

- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/settings-menu/BackupSection/WalletSelectionView.js
> Fix cloud platform name on Android

- src/components/sheet/sheet-action-buttons/SheetActionButton.js
- src/screens/TransactionConfirmationScreen.js
> Fix wc low balance msg on Android

- src/screens/ImportSeedPhraseSheet.js
Just got a crash because this ref was null
> Fix import sheet crash

- src/components/backup/BackupCloudStep.js
- src/components/backup/BackupConfirmPasswordStep.js
- src/components/backup/RestoreCloudStep.js
- src/helpers/samsung.js
Opening for @skylarbarrera to test
> Tiny phone android keyboard sheets magic

- src/components/buttons/MiniButton.js
> Fix minibutton for android

- src/components/expanded-state/ExpandedStateSection.js
- src/components/expanded-state/profile/ProfileAvatarButton.js
- src/components/savings/SavingsListRow.js
- src/components/sheet/sheet-action-buttons/SheetActionButtonRow.js
Unique Expanded State styling:
before: https://cloud.skylarbarrera.com/Screenshot_20201202-114409_Rainbow.jpg
after: https://cloud.skylarbarrera.com/Screenshot_20201202-124457_Rainbow.jpg
Profile Avatar Button:
before: https://cloud.skylarbarrera.com/Screenshot_20201202-113244_Rainbow.jpg
after: https://cloud.skylarbarrera.com/Screenshot_20201202-141828.png
> android beta tweaks

- src/components/asset-list/RecyclerAssetList.js
Attempt to prevent this: https://sentry.io/organizations/rainbow-me/issues/2071834308/?project=1855565&query=release%3Ame.rainbow%401.0%2B5&statsPeriod=24h
> Prevent wallet crash

- src/screens/CurrencySelectModal.js
Support searching for contract addresses (regardless of case sensitivity and regardless of 0x prefix)
> Support separate logic for address search in swap

- src/helpers/assets.js
Fixes RAI-956 📌 Pinning issues
Proof: https://cloud.skylarbarrera.com/Screen_Recording_20201124-141642.mp4
> 📌  Pinning issues 

- src/screens/TransactionConfirmationScreen.js
remove bottom round borders and adjust margin top
> Fix WC modal on android

- src/components/AddFundsInterstitial.js
- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/backup/BackupManualStep.js
- src/components/buttons/rainbow-button/RainbowButton.js
- src/components/expanded-state/ChartExpandedState.js
- src/components/numpad/PinValue.js
- src/components/savings/SavingsListRow.js
- src/components/secret-display/SecretDisplayCard.js
- src/components/secret-display/SecretDisplaySection.js
- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/settings-menu/BackupSection/NeedsBackupView.js
- src/components/settings-menu/BackupSection/WalletSelectionView.js
- src/components/sheet/sheet-action-buttons/BuyActionButton.js
- src/components/sheet/sheet-action-buttons/SheetActionButton.js
- src/components/sheet/sheet-action-buttons/SheetActionButtonRow.js
- src/components/transaction/TransactionMessage.js
- src/components/transaction/TransactionSheet.js
- src/components/transaction/sections/TransactionConfirmationSection.js
- src/screens/BackupSheet.js
- src/screens/SavingsSheet.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WalletConnectApprovalSheet.js
- src/screens/WelcomeScreen.js
this should fix all remaining button and WC modal issues
> Fix develop-android UI bugs

- src/components/buttons/rainbow-button/RainbowButtonBackground.js
> Fix warning

- ios/TransactionListBaseCell.swift
- ios/TransactionListView.swift
think they were broken by changes to UITableView in iOS 14
> Fix native activity list coin icon shadows

- src/components/animations/OpacityToggler.js
- src/components/asset-list/RecyclerAssetList.js
- src/hooks/useOpenSavings.js
- src/hooks/useOpenSmallBalances.js
- src/redux/openStateSettings.js
- src/redux/reducers.js
Before:
https://streamable.com/tuef97
After:
https://streamable.com/6wumtn
I know it looks slow after fixes anyway, but it's faster than before. Also, it's not a good phone, the list is very long and it's not a release mode.
> Optimize open savings and open small balances in AssetsList

- android/app/build.gradle
Sorry, I'm too impatient. .9 coming this evening.
> Bump android version to 8

- src/components/send/SendAssetForm.js
Just needed to add a backgroundColor, @christianbaroni you may want to tweak the shadow values on android at some point but this returns to the previous state
http://cloud.skylarbarrera.com/Screen-Shot-2020-12-16-16-46-53.26.png
> fix sendSheet asset on android

- android/app/build.gradle
> Bump android version to 9

- src/hooks/useSavingsAccount.js
Example scenario with issue:
- Clearing all localstorage
- Load a wallet that has savings (e.g, poopcoin.eth)
- Load a wallet that does not have savings (e.g, 0x7044a3E6bf3baf4F0d2F8884A2Ee4E2D838f8902)
- Previously, you would see poopcoin's Savings show up in the second wallet
We were not resetting the results when switching between wallets, so there would be some delay before the next wallet's data would be fully fetched. Now, I just reset the result.
> Reset savings data when switching accounts

- src/components/settings-menu/CurrencySection.js
Proof of Work: http://cloud.skylarbarrera.com/Screen-Shot-2020-12-17-17-35-51.38.png
Will want to refactor native currency list if we ever add DAI, or other assets
> update coinIcon in currencySection

- src/components/coin-row/ExchangeCoinRow.js
- src/components/exchange/ExchangeAssetList.js
- src/helpers/tokenSectionTypes.js
- src/screens/CurrencySelectModal.js
Shows an alert whenever you choose an unverified token in the list.
@christianbaroni The copy is almost identical to Uniswap. Feel free to tweak
DEMO: http://recordit.co/IfKajdbo9p
> add alert for unverified tokens

- src/components/contacts/ContactAvatar.js
- src/components/contacts/ContactRow.js
- src/components/expanded-state/profile/ProfileAvatarButton.js
- src/components/send/SendContactList.js
This PR fixes some overflow issues on 🤖  and adds colored shadows to iOS while dealing with resulting overflow issues there as well (Contact List)
iOS before: http://cloud.skylarbarrera.com/Screen-Recording-2020-12-21-17-11-24.mp4
iOS after: http://cloud.skylarbarrera.com/Screen-Recording-2020-12-21-17-10-50.mp4
🤖  before: http://cloud.skylarbarrera.com/Screenshot_20201221-151147_Rainbow.jpg
🤖  after: http://cloud.skylarbarrera.com/Screenshot_20201221-151202_Rainbow.jpg
> fix avatar shadows 

- shim.js
> Path's d updates as native props instead of ui props

- src/components/sheet/SheetHandle.js
the blur effect stopped working at some point
this fixes it fo sho
> fix broken blur effect in SheetHandle

- package.json
- scripts/check-env.sh
I'll add the same script for iOS on CI
> check .env values before building for the stores

- src/components/sheet/SlackSheet.js
Purely a cleanup of components / style declarations
i built to both iOS and android to confirm there are no regressions, visual or otherwise
> minor cleanup of SlackSheet.js

- src/components/gas/GasSpeedButton.android.js
- src/components/gas/GasSpeedButton.ios.js
- src/components/gas/GasSpeedEmoji.js
- src/components/gas/GasSpeedLabelPager.js
- src/components/gas/GasSpeedLabelPagerItem.js
- src/components/sheet/sheet-action-buttons/SheetActionButtonRow.js
- src/components/text/Emoji.js
- src/screens/SpeedUpAndCancelSheet.js
- src/styles/fonts.js
> Polish speed up cancel

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
Before:
https://streamable.com/fipkje
After:
https://streamable.com/e9yli4
> Fix zooming of background of buttons on Android

- src/components/discover-sheet/DiscoverSheetHeader.js
Before: https://streamable.com/wzhel9
After: ~https://streamable.com/46dp85~ https://streamable.com/z8ole0
> Fix buttons' paddings on Discover Sheet

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-06-11-32-57.25.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-06-11-33-26.75.png
> fix transparent background on SimpleScaleButton

- src/components/discover-sheet/DiscoverSheet.js
- src/components/discover-sheet/DiscoverSheetHeader.js
- src/components/qrcode-scanner/CameraDimmer.js
- src/screens/QRScannerScreen.js
https://linear.app/rainbow/issue/RNBW-343/disable-camera-when-discover-sheet-is-open
> Disable camera on closed bottom sheet

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
PoW: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-07-14-22-45.98.png
> fix android bpa

- patches/react-native-slack-bottom-sheet+0.5.0.patch
- src/components/discover-sheet/DiscoverSearch.js
- src/components/discover-sheet/DiscoverSearchContainer.js
- src/components/discover-sheet/DiscoverSheet.js
- src/components/discover-sheet/DiscoverSheetContent.js
- src/components/discover-sheet/DiscoverSheetHeader.js
- src/components/discover-sheet/TopMoversSection.js
- src/components/exchange/CurrencySelectionList.js
- src/components/exchange/ExchangeAssetList.js
- src/components/exchange/ExchangeSearch.js
- src/components/sheet/SlackSheet.js
- src/navigation/SwipeNavigator.js
Partially https://linear.app/rainbow/issue/RNBW-972/improve-search-mode-interactions
> Disable short form and main pager's swiping if search is enabled

- src/redux/walletconnect.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WalletConnectApprovalSheet.js
Added some tracking on mixpanel and sentry to see if there's some funky stuff going on that we don't know about.
@skylarbarrera  Just need to make sure WC still works.
> WC logging

- ios/fastlane/Fastfile
This reverts commit cfb824109955a7a156623bfd65bd77ca9714bbde.
> Revert "temp fix (#1574)"

- src/components/header/Header.js
- src/screens/ProfileScreen.js
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-15-12-19-02.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-15-12-56-16.52.png
> align profile header items

- src/helpers/buildWalletSections.js
- src/hooks/useSendSavingsAccount.js
- src/hooks/useUniswapCurrencies.js
- src/redux/data.js
- src/redux/gas.js
- src/screens/TransactionConfirmationScreen.js
- src/utils/ethereumUtils.js
When using generic ETH asset for pricing, use the other ethereumUtils function
> Fix for generic eth price usage

- src/components/coin-row/ListCoinRow.js
- src/components/discover-sheet/ListsSection.js
> Fix lists' buttons on android

- src/handlers/web3.js
Just removing something that has been bothering me
> Removing unnecessary recipient address fallback

- src/components/qrcode-scanner/QRCodeScanner.js
- src/screens/QRScannerScreen.js
Closes https://linear.app/rainbow/issue/RNBW-343/disable-camera-when-discover-sheet-is-open
> Do not turn on camera on presented DiscoverSheet

- src/components/discover-sheet/ListsSection.js
- src/handlers/localstorage/userLists.js
- src/hooks/useUserLists.js
- src/redux/userLists.js
Fixes RNBW-997
PoW: http://recordit.co/meUtm04UNu
> Improve lists UX

- src/screens/TransactionConfirmationScreen.js
> Fix sheet height for android approval wc requests

- babel.config.js
- e2e/helpers.js
- global.js
- package.json
- shim.js
- src/App.js
- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.ios.js
- src/components/asset-list/RecyclerAssetList.js
- src/components/contacts/showDeleteContactActionSheet.js
- src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/components/investment-cards/UniswapInvestmentRow.js
- src/handlers/uniswap.ts
- src/handlers/wyre.js
- src/helpers/assets.js
- src/helpers/utilities.ts
- src/react-native-animated-charts/src/interpolations/bSplineInterpolation.js
- src/screens/TransactionConfirmationScreen.js
- src/styles/buildFlexStyles.js
- src/styles/buildLayoutStyles.js
- src/utils/formatters.js
- yarn.lock
Also includes fixes for other improvements from the prettier upgrade
> Upgrade prettier to support export types

- src/screens/ChangeWalletSheet.js
https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1611929423085400
> Fix wallet deleting

- src/model/wallet.ts
- src/screens/ChangeWalletSheet.js
Instead of calling `wipeKeychain` we can just manually delete the keys that are left
> Fix last wallet deletion scenario

- src/screens/SendSheet.js
This would help preventing "out of gas" errors
> Re-run gas estimation before sending tokens

- src/screens/ChangeWalletSheet.js
PoW:  http://recordit.co/EtL7dWmHOJ
> Fix wallet deletion crash

- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/styles/colors.js
Noticed I didn't handle long token names properly, this fixes. Plus a small pixel tweak 👨‍🍳 
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-31-20-02-42.91.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-31-20-44-58.50.png
> smol chart tweaks

- src/hooks/useUniswapCurrencies.js
> Fix keyboard focusing on Exchange modal

- src/components/exchange/ExchangeSearch.js
i have no idea how is it possible
> Fix keyboard focucing on swap sheet

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateImage.js
We were using the preview image, now we're using the original
before:  http://cloud.skylarbarrera.com/Screen-Shot-2021-02-02-00-10-59.14.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-02-02-00-08-53.09.png
> Open Sea - High Quality Images

- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- fixes a truncated text issue: http://cloud.skylarbarrera.com/IMG_4112.PNG
- fixes the logic on what we should hide if we don't have price data &/or charts are disabled
- pixel tweak on android
> More charts tweaks

- package.json
- src/App.js
- src/components/activity-list/ActivityList.js
- src/components/add-cash/AddCashStatus.js
- src/components/asset-list/AssetListItemSkeleton.js
- src/components/coin-row/CollectiblesSendRow.js
- src/components/copy-tooltip/CopyTooltip.ios.js
- src/components/exchange/SlippageWarning.js
- src/components/list/ListItem.js
- src/components/list/ListItemArrowGroup.js
- src/components/radio-list/RadioListItem.js
- src/components/walletconnect-list/WalletConnectLearnMoreButton.js
- src/helpers/buildWalletSections.js
- src/utils/recompactAdapters.js
- yarn.lock
remove recompact, get rid of `withThemeContext` where possible
> clean-up code

- src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
> Do not show NaN in charts

- ios/Rainbow.xcodeproj/xcshareddata/xcschemes/Rainbow.xcscheme
https://stackoverflow.com/questions/60884993/high-cpu-load-of-diagnosticd-process-while-running-react-native-app-on-ios-simul
It happens exactly to me
> Hide strange unwanted Xcode logs

- src/components/walletconnect-list/WalletConnectLearnMoreButton.js
User reported that it wasnt working, now it does
PoW: http://cloud.skylarbarrera.com/Screen-Recording-2021-02-08-20-48-40.mp4
> fix learn more button

- src/components/coin-row/ExchangeCoinRow.js
Disables the unverified warning for tokens you already own
> Disable unverified warning for owned tokens

- src/helpers/dappNameHandler.js
Tweaked a few and added some new ones based on our metrics
PoW: http://cloud.skylarbarrera.com/Screen-Shot-2021-02-08-19-25-02.80.png
> update verified dapps

- src/components/discover-sheet/ListsSection.js
> Animate switching lists

- src/components/discover-sheet/DiscoverSheetHeader.js
before/after: http://cloud.skylarbarrera.com/Screen-Recording-2021-02-09-11-42-55.mp4
> discover header dark mode tweak

- patches/react-native-slack-bottom-sheet+0.5.0.patch
- src/components/discover-sheet/DiscoverSheet.js
- src/components/sheet/SlackSheet.js
It is especially visible on iPhone SE
https://user-images.githubusercontent.com/25709300/107392288-2f251c80-6b02-11eb-8795-782d16e2e505.mov
> Fix sometimes not scrollable content of discover sheet

- src/navigation/ExchangeModalNavigator.js
> Fix background in stack

- ios/TransactionListView.swift
Possibly fix https://sentry.io/organizations/rainbow-me/issues/1975624887/?project=1855565&query=is%3Aunresolved
> Fix crash with image in the picker 

- src/components/discover-sheet/PulseIndexSection.js
Before it was not even visible
>  Fix DeFiPulse Index on Android

- src/components/discover-sheet/DiscoverSheet.js
- src/components/discover-sheet/DiscoverSheetContent.js
- src/components/discover-sheet/DiscoverSheetHeader.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/discover-sheet/androidCustomComponents/customBackground.tsx
- src/components/discover-sheet/androidCustomComponents/customHandle.tsx
- src/components/discover-sheet/customHandle.tsx
- src/components/expanded-state/ChartExpandedState.js
- src/components/expanded-state/TokenIndexExpandedState.js
- src/components/sheet/SheetHandle.js
Changes:
- Fixed Uni Pools logo alignment on android
- Added fullWidth Props on SheetActionButtons
- Fixed underlying Assets "graph" for DPI on android
- before: http://cloud.skylarbarrera.com/Screenshot_20210210-181400.png
- after: http://cloud.skylarbarrera.com/Screenshot_20210210-181546.png
- Tweaked sheetHandle color opacity on android to match iOS
- Added custom components for react-native-bottom-sheet
- Custom Handle(Uses our sheetHandle)
- Custom Background(fixes dark mode issues on android)
- before: http://cloud.skylarbarrera.com/Screenshot_20210210-181437.png
- after: http://cloud.skylarbarrera.com/Screenshot_20210210-181520.png
> discover android tweaks

- src/components/expanded-state/SwapDetailsState.js
- src/entities/index.ts
- src/entities/tokens.ts
- src/hooks/useSwapDetails.js
- src/hooks/useSwapDetails.ts
- src/hooks/useUniswapCurrencies.js
- src/hooks/useUniswapMarketDetails.ts
- src/redux/swap.ts
- src/screens/ExchangeModal.js
Moving over the "extra trade details" to redux
> Move over extra trade details to redux

- src/hooks/useSwapDetails.ts
- src/hooks/useSwapInputOutputTokens.ts
- src/hooks/useUniswapMarketDetails.ts
- src/raps/actions/unlock.ts
- src/redux/swap.ts
- src/screens/ExchangeModal.js
Also update some hooks to use data directly from redux when possible
> Move trade details to redux

- src/components/coin-icon/CoinIcon.js
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-02-12-12-18-49.71.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-02-12-12-18-02.21.png
> fix 🤖  square token icons

- src/components/expanded-state/ChartExpandedState.js
- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/components/expanded-state/chart/chart-data-labels/ChartHeaderSubtitle.js
Adds a commit that I hadnt pushed from my last charts fix 🙃 
adds base height for charts
PoW: http://cloud.skylarbarrera.com/Screen_Recording_20210212-152431.mp4
> chart tweaks pre discover fixes

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/coin-row/TopMoverCoinRow.js
- src/components/list/MarqueeList.js
> Fix marquee list on Android

- package.json
- src/components/backup/RestoreSheetFirstStep.js
- src/components/buttons/PasteAddressButton.js
- src/components/coin-row/TransactionCoinRow.js
- src/components/fields/AddressField.js
- src/components/transaction-list/TransactionList.js
- src/handlers/web3.js
- src/helpers/validators.js
- src/screens/ImportSeedPhraseSheet.js
- src/screens/SendSheet.js
- src/utils/abbreviations.js
- src/utils/address.js
- yarn.lock
Fixed copy & a bunch of implementation errors. 
Works as expected now
> Unstoppable Domainz

- src/redux/topMovers.ts
> Filter top movers with incorrect data

- src/references/uniswap/rainbow-token-list.json
Updated the token list based on the top Defi Pulse index projects, our verified dapps, & a few personal opinions tokens
Feel free to veto any you think are 💩
> add verified tokens 

- src/components/backup/BackupCloudStep.js
- src/screens/BackupSheet.js
Same logic we use for Apple pay, receive modal, copy address, etc applied to the backups for obvious reasons.
> prevent backup if missing info

- src/components/discover-sheet/ListsSection.js
- src/components/discover-sheet/PulseIndexSection.js
- src/components/discover-sheet/TopMoversSection.js
- src/components/investment-cards/UniswapPoolListRow.js
- src/navigation/Navigation.js
- src/navigation/nativeStackConfig.js
- src/navigation/onNavigationStateChange.js
- src/screens/ExpandedAssetSheet.js
Now it's not changing on opening the sheet and closing!
> Fix status bar handling in Discover Sheet

- package.json
- src/components/expanded-state/LiquidityPoolExpandedState.js
- yarn.lock
1.2.5 wasnt working in release, 1.2.2 works 👌
> downgrade android extra dimensions package

- src/components/coin-row/TopMoverCoinRow.js
It's a kinda special case here, cause we're interacting with any other additional GH-s
> Fix TopMovers haptic feedback

- src/components/discover-sheet/DiscoverSearch.js
- src/components/discover-sheet/DiscoverSearchContainer.js
- src/components/discover-sheet/DiscoverSheetContent.js
- src/components/exchange/CurrencySelectionList.js
- src/components/exchange/ExchangeAssetList.js
- src/screens/QRScannerScreen.js
Make it not restoring on scroll to top as discussed with @christianbaroni.
> Change keyboard behavior on Discover Search

- android/app/build.gradle
Had to rebuild and google doesnt let you delete a build
> bump android 1.0-23

- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/ListCoinRow.js
- src/components/coin-row/TopMoverCoinRow.js
- src/components/discover-sheet/BottomSpacer.js
- src/components/discover-sheet/DiscoverHome.js
- src/components/discover-sheet/DiscoverSearchContainer.js
- src/components/discover-sheet/DiscoverSheet.js
- src/components/discover-sheet/DiscoverSheetHeader.js
- src/components/discover-sheet/ListsSection.js
- src/components/discover-sheet/PulseIndexSection.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/exchange/ExchangeSearch.js
- src/components/expanded-state/TokenIndexExpandedState.js
- src/components/fab/SearchFab.js
- src/components/header/DiscoverHeaderButton.js
- src/components/investment-cards/UniswapInvestmentRow.js
- src/components/investment-cards/UniswapPoolListRow.js
- src/components/sheet/SheetHandle.js
- src/components/sheet/SlackSheet.js
- src/components/sheet/sheet-action-buttons/WithdrawActionButton.js
- src/hooks/useUniswapPools.js
- src/navigation/config.js
- src/references/default-token-lists.json
- src/screens/AddTokenSheet.js
- src/styles/colors.js
todo: fix list coin rows--bottom row now contains price and % change, but the price is only passed in currently if you have the asset in your wallet
> Discover polish

- src/components/expanded-state/LiquidityPoolExpandedState.js
> Fix navigating to Uniswap from depositing pool

- src/components/exchange/ExchangeSearch.js
Fixes https://linear.app/rainbow/issue/RNBW-1029/search-spinner-is-broken-in-discover-and-swap
> Fxi spinner on Discover Page

- src/navigation/Routes.android.js
closes https://linear.app/rainbow/issue/RNBW-1014/dpi-sheet-interaction-issues.
It is not perfect, I know, but it will be better with #1605.
> Fix scrolling in DPI sheet

- src/apollo/queries.js
- src/entities/index.ts
- src/entities/tokens.ts
- src/handlers/uniswap.ts
- src/hooks/useUniswapAssets.ts
- src/hooks/useUniswapAssetsInWallet.js
- src/redux/uniswap.js
- src/screens/CurrencySelectModal.js
- Use the new pagination method after The Graph fixed performance issues
- Parse and update subgraph results as the pages arrive instead of waiting until the end to update redux
- Always use the Rainbow token list even if subgraph may have issues
> Use new pagination method and always use the Rainbow token list

- package.json
- yarn.lock
ran an audit and had them update their deps
🎉   http://cloud.skylarbarrera.com/Screen-Shot-2021-02-23-10-56-19.86.png
> bump unstoppable domains 

- src/components/exchange/ConfirmExchangeButton.js
- src/components/savings/SavingsListRow.js
- src/hooks/useSwapCurrencyHandlers.js
- src/hooks/useSwapInputHandlers.ts
- src/redux/swap.ts
- src/screens/DepositModal.js
- src/screens/ExchangeModal.js
- src/screens/SavingsSheet.js
- src/screens/WithdrawModal.js
- Improves the logic for determining the default input and output currencies depending on swap, deposit, withdraw
- Fixes max withdraw calculation
> Fix default input output currency selection

- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/expanded-state/LiquidityPoolExpandedState.js
- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
- src/components/investment-cards/UniswapPoolListRow.js
- src/components/value-chart/Chart.js
- Fixes RNBW-1030
- Fixes RNBW-1031
- Fixes RNBW-1032
> Pool related fixes

- src/components/exchange/ExchangeDetailsRow.js
- src/components/expanded-state/SwapDetailsState.js
- src/hooks/useSwapDerivedOutputs.ts
- src/hooks/useSwapInputHandlers.ts
- src/redux/swap.ts
- src/screens/ExchangeModal.js
Reverts rainbow-me/rainbow#1787
> Revert "Add default values to transaction details sheet"

- src/components/discover-sheet/DiscoverSearch.js
Follow up for https://github.com/rainbow-me/rainbow/commit/1aca0b6e243bce29080af0e32910a8641e21cc74
> Fix globalVerifiedAssets in DiscoverSearch

- src/components/expanded-state/LiquidityPoolExpandedState.js
- src/hooks/charts/useChartThrottledPoints.js
> Fix LiquidityPoolExpandedState height with/without uniBalance

- src/components/expanded-state/swap-details/SwapDetailsContent.js
- src/handlers/uniswap.ts
- src/hooks/index.js
- src/hooks/useSwapAdjustedAmounts.ts
- src/redux/swap.ts
PoW: https://recordit.co/JsFm9g3URZ
> Show max sold or min received in swap details content

- src/components/expanded-state/swap-details/SwapDetailsRow.js
> Fix fonts in SwapDetailsRow on Android

- src/components/expanded-state/swap-details/SwapDetailsContractRow.js
> Add action sheet fallback on SwapDetailsContractRow for Android

- src/components/exchange/ConfirmExchangeButton.js
- src/components/exchange/DepositInfo.js
- src/components/expanded-state/SwapDetailsState.js
- src/components/expanded-state/swap-details/SwapDetailsContractRow.js
- src/screens/ExchangeModal.js
Centered Deposit Details text: http://cloud.skylarbarrera.com/Screen-Shot-2021-03-01-21-07-58.31.png
fix gas button width: http://cloud.skylarbarrera.com/Screen-Recording-2021-03-01-22-07-16.mp4
Display Trade Details on deposit if needed(may want to change this a bit but i think its better to have than not)
http://cloud.skylarbarrera.com/Screen-Recording-2021-03-01-22-18-00.mp4
removed unnecessary "token contract" text since its duplicated, lmk and ill revert this one
http://cloud.skylarbarrera.com/Screen-Recording-2021-03-01-22-35-53.mp4
> 🔀   tweaks

- src/components/exchange/ConfirmExchangeButton.js
> Fix shadows in ConfirmExchangeButton

- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/expanded-state/TokenIndexExpandedState.js
- src/hooks/charts/useChartData.js
- src/hooks/charts/useChartDataLabels.js
- src/hooks/charts/useChartThrottledPoints.js
- src/hooks/useDPI.ts
- src/redux/charts.js
A bit hacky, but for now it's sufficient.
> Fix DPI loading state while navigating back from underline asset expanded state

- src/components/discover-sheet/ListsSection.js
- src/components/discover-sheet/PulseIndexSection.js
- src/components/discover-sheet/TopMoversSection.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/expanded-state/TokenIndexExpandedState.js
- src/hooks/useUniswapPools.js
- src/parsers/accounts.js
- src/parsers/transactions.js
- src/redux/data.js
- src/redux/explorer.js
- src/redux/fallbackExplorer.js
- src/references/index.ts
- src/utils/index.js
- src/utils/tokensListenedCache.ts
This PR makes discover working even if zerion is down.
The way it works is:
- If we don't have pricing info from zerion in 10 seconds after launching the app it will use the fallback.
- It will refresh data every 1 minute.
- If we hear back from zerion, the fallback will be cancelled.
To test set `forceFallbackProvider` to true in the debug config.
> Fallback generic assets

- src/screens/AddTokenSheet.js
Did my best to keep the styling/formatting as is on iOS, the main objective was to fix android
before: http://cloud.skylarbarrera.com/Screen-Recording-2021-03-01-16-24-52.mp4
PoW: http://cloud.skylarbarrera.com/Screen-Recording-2021-03-01-16-21-37.mp4
(current iOS is on the right)
> 🤖  "Add token" sheet's styling 

- package.json
- patches/@gorhom+bottom-sheet+3.3.1.patch
- src/components/radio-list/RadioList.js
- src/components/sheet/SlackSheet.js
- src/hooks/index.js
- src/hooks/useForceUpdate.ts
- src/navigation/bottom-sheet/actions.ts
- src/navigation/bottom-sheet/constants.ts
- src/navigation/bottom-sheet/contexts/internal.ts
- src/navigation/bottom-sheet/createBottomSheetNavigator.tsx
- src/navigation/bottom-sheet/hooks/useBottomSheetNavigator.ts
- src/navigation/bottom-sheet/index.ts
- src/navigation/bottom-sheet/router.ts
- src/navigation/bottom-sheet/types.d.ts
- src/navigation/bottom-sheet/views/BottomSheetBackground.tsx
- src/navigation/bottom-sheet/views/BottomSheetNavigatorView.tsx
- src/navigation/bottom-sheet/views/BottomSheetRoute.tsx
- yarn.lock
Credits to @gorhom.
For now, this is a no-op and we will be gradually adding new things.
> Basic version of BS integration

- patches/react-native-sound+0.11.0.patch
I didn't wait for CI to run on the previous PR because none of us were able to build. This one should pass before merging
> Fix linter

- src/components/expanded-state/SwapDetailsState.js
fixes keyboard offset for android
before:  http://cloud.skylarbarrera.com/Screen-Recording-2021-03-08-13-28-42.mp4
after: http://cloud.skylarbarrera.com/Screen-Recording-2021-03-08-13-30-55.mp4
> fix offset on android

- src/hooks/useSwapDerivedOutputs.ts
PoW Recording: https://recordit.co/mpqBdBJnmN
Before:
https://user-images.githubusercontent.com/1285228/110415661-7a721280-804f-11eb-9cf0-6b7afe08954f.mov
> Ignore trade details when output independent value is zero

- src/hooks/useSwapDerivedOutputs.ts
Apply the same logic for any output of value 0, to ignore calculating trade details and derived output values.
PoW: https://recordit.co/b4L5bJHZAk
> Ignore deriving trade detail outputs for 0 value inputs

- src/components/coin-icon/CoinIcon.js
> Fix icon's caching on swap modal

- src/components/exchange/ConfirmExchangeButton.js
- src/styles/colors.js
Before:
https://streamable.com/v4901s
After:
https://streamable.com/qx6hw5
> Make "Enter an amount" not transparent while dismissing sheet

- src/redux/swap.ts
PoW recording: https://recordit.co/1lAhIVScyM
Previously, it was crashing
> Fix crash when native input empty and focused then flipped

- src/references/index.ts
> Include SOCKS back in favorites and reuse addresses in references

- src/components/add-cash/AddCashForm.js
- src/components/backup/BackupCloudStep.js
- src/components/backup/BackupSheetSection.js
- src/components/exchange/ConfirmExchangeButton.js
- src/components/exchange/ExchangeSearch.js
- src/components/exchange/PriceImpactWarning.js
- src/components/expanded-state/swap-details/CurrencyTile.js
- src/components/gas/GasSpeedLabelPager.js
- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/components/settings-menu/BackupSection/NeedsBackupView.js
- src/components/text/Smallcaps.js
- src/components/transaction/sections/DefaultTransactionConfirmationSection.js
- src/components/value-chart/Chart.js
- src/screens/SpeedUpAndCancelSheet.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/WelcomeScreen.js
- src/styles/colors.js
Fixes color issues from flip-button branch
> Color fixes, make ETH default purchase option

- src/components/expanded-state/UniqueTokenExpandedState.js
http://cloud.skylarbarrera.com/Screen-Shot-2021-03-11-13-58-18.60.png
> Bio -> Description

- ios/Rainbow/AppDelegate.mm
A bit of discussion here: https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1615909036005000
> Send update to Sentry about memory warning

- ios/Podfile.lock
- src/components/AddFundsInterstitial.js
bumped to 100 - 200 - 300
also includes a podfile update that was missing
POW:    http://cloud.skylarbarrera.com/Screen-Shot-2021-03-17-11-48-03.11.png
> bump add cash amounts

- src/entities/index.ts
- src/entities/transactions/index.ts
- src/entities/transactions/transaction.ts
- src/entities/transactions/zerionTransaction.ts
- src/entities/wallet.ts
- src/model/wallet.ts
- src/parsers/newTransaction.ts
- src/parsers/transactions.ts
- src/screens/SendSheet.js
- src/screens/TransactionConfirmationScreen.js
- src/utils/ethereumUtils.js
This is a follow up to the first general transaction data Typescript PR.
> Typescript for newTxn parsing

- src/components/discover-sheet/DiscoverSheet.android.js
- src/components/expanded-state/ChartExpandedState.js
- src/components/qrcode-scanner/ConnectedDapps.js
- src/screens/QRScannerScreen.js
- src/screens/RestoreSheet.js
- src/screens/SavingsSheet.js
old PR with @osdnk comments fixed
• android sheet tweaks
• android discover sheet height tweak
• add QR Scanner header to Camera Dimmer
> disco tweaks

- src/components/coin-icon/CoinIconGroup.js
- src/components/coin-row/CoinRow.js
- src/components/discover-sheet/DiscoverSheet.android.js
- src/components/discover-sheet/DiscoverSheet.ios.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/images/ImgixImage.tsx
- src/components/investment-cards/UniswapPoolListRow.js
- src/components/send/SendAssetList.js
- src/components/sheet/SlackSheet.js
- src/handlers/imgix.ts
- src/helpers/buildWalletSections.js
- src/hooks/useUniswapPools.js
- src/redux/data.js
- optimize a few components: CoinIconGroup, CoinRow, UniswapPoolListRow
- add removeClippedSubviews to DiscoverSheet scrollview
- pass dimensions to CDN for optimal assets
- optimize UniswapPoolListRow.js
- refactor useUniswapPools hook
- use no-cache in uniswap queries
Before:
After:
> Optimize discover memory usage

- src/components/add-cash/AddCashStatus.js
- src/components/add-cash/NeedHelpButton.js
- src/components/expanded-state/SupportedCountriesExpandedState.js
- src/handlers/wyre.js
- src/hooks/useWyreApplePay.js
- src/redux/addCash.js
- src/references/index.ts
- src/references/wyre/index.js
- src/references/wyre/supportedCountries.js
- src/screens/AddCashSheet.js
Also includes Order ID in the subject of the support email
> Display order ID on Add Cash error message

- src/components/exchange/ConfirmExchangeButton.js
- src/components/exchange/DepositInfo.js
- src/screens/ExchangeModal.js
> show slippage warning on DepositModal

- src/navigation/Routes.android.js
- src/navigation/effects.js
> Fix DPI preset on Android

- package.json
- yarn.lock
fixes yearn issue, downgraded a la @mikedemarais . Can rebump once its fixed.
> downgrade coin-icon

- e2e/discoverSheetFlow.spec.js
- e2e/ganacheTransactionFlow.spec.js
- src/components/coin-row/ListCoinRow.js
- src/components/coin-row/TopMoverCoinRow.js
- src/components/discover-sheet/DiscoverSearchContainer.js
- src/components/discover-sheet/DiscoverSheetContent.js
- src/components/discover-sheet/ListsSection.js
- src/components/discover-sheet/PulseIndexSection.js
- src/components/discover-sheet/TopMoversSection.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/expanded-state/TokenIndexExpandedState.js
- src/components/expanded-state/chart/ChartAddToListButton.js
- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/components/expanded-state/chart/chart-data-labels/ChartHeaderSubtitle.js
- src/components/header/DiscoverHeaderButton.js
- src/components/list/MarqueeList.js
- src/components/settings-menu/SettingsSection.js
- src/components/sheet/SlackSheet.js
- src/components/text/TruncatedText.js
- src/components/value-chart/Chart.js
- src/screens/AddTokenSheet.js
- src/screens/QRScannerScreen.js
Discover e2e & added a Dark Mode toggle
> discover e2e

- scripts/postinstall.sh
This broke a few things (codepush & branch)
> fix post-install

- src/components/discover-sheet/UniswapPoolsSection.js
- src/hooks/useUniswapPools.js
PoW: https://recordit.co/ZZjNBzIDxr
> show 15 pools then 40

- src/screens/TransactionConfirmationScreen.js
We'll get error logs grouped per dapp and with all this info:
> add more logging for wc tx failures

- src/components/savings/SavingsSheetEmptyState.js
- src/handlers/zeroEx.ts
- src/screens/CompoundDepositModal.js
- src/screens/CompoundWithdrawModal.js
- src/screens/ExchangeModal.js
- src/screens/SavingsSheet.js
* Include pool name in Deposit title
* Fix: bypass zeroEx quote when buy and sell token are the same
> More fixes and improvements to LP

- src/react-native-cool-modals/ios/UIViewController+slack.swift
The force unwrap was causing two different crashes while opening the modals.
> Prevent cool modals crash

- patches/react-native-reanimated+2.1.0.patch
@osdnk  as discussed, added the missing part
> Update rea patch

- src/components/sheet/SheetHandle.js
before http://cloud.skylarbarrera.com/Screen-Recording-2021-04-12-23-50-15.mp4
after http://cloud.skylarbarrera.com/Screen-Recording-2021-04-12-23-48-49.mp4
> sheet handle with transparency

- src/apollo/queries.js
- src/hooks/usePoolDetails.js
- src/hooks/useUniswapPools.js
- src/redux/additionalAssetsData.ts
- src/redux/charts.js
- src/redux/data.js
- src/redux/explorer.js
- src/references/shitcoins.json
- src/utils/getBlocksFromTimestamps.js
- src/utils/index.js
Also added the fake CVR token to the shitcoins list.
Pending: need to decide on if we want to add an additional constraint to limit by total liquidity.
> Fix the fallback to using the subgraph for missing prices

- e2e/swapSheetFlow.spec.js
- src/screens/ExchangeModal.js
we have e2e for this so if it's green it's good.
PoW: http://recordit.co/73F7Y4oO4Z
> Remove slow speed in exchange modal

- src/handlers/uniswap.ts
- src/handlers/web3.js
- src/raps/actions/swap.ts
We were doing this only for WC requests. Now it's also done for swaps using the same logic.
> Estimate gas with padding for swaps

- src/components/discover-sheet/DiscoverSearch.js
the debounce of 250 is too low & search stutters for me
> upped discover search debounce timeout

- src/components/contacts/ContactRow.js
- src/components/contacts/SwipeableContactRow.js
- src/components/send/SendContactList.js
- src/components/send/SendHeader.js
- src/hooks/index.js
- src/hooks/useUserAccounts.js
- src/screens/SendSheet.js
Now we're showing your own accounts.
PoW: http://recordit.co/VhdHDm6sfS
> Sendsheet improvements

- package.json
- yarn.lock
Fixes https://github.com/advisories/GHSA-h4j5-c7cj-74xg
> Lock xmlhttprequest-ssl

- package.json
- yarn.lock
add new Friends With Benefits Pro token to verified, and also properly label old deprecated FWB token to distinguish between them
> bump rainbow-token-list for FWB fix

- src/hooks/index.js
- src/hooks/useInitializeWallet.js
- src/hooks/useLoadAccountData.js
- src/hooks/usePortfolios.js
- src/redux/data.js
- src/redux/explorer.js
- src/screens/WalletScreen.js
Fetch portfolio totals and store it in redux.
> added portfolios to redux

- src/components/expanded-state/UniqueTokenExpandedState.js
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
- src/helpers/assets.js
- src/parsers/uniqueTokens.js
fixes unidentified contract issue from opensea, uses collection.name instead of asset_contract.name
adds extra image fallbacks 
Checked a few NFT heavy wallets but could use some extra testing cc: @mikedemarais 
Unidentified Contract case would be PILLS
> adjust opensea

- src/components/AppVersionStamp.js
> fix version stamp press

- src/components/expanded-state/WalletProfileState.js
- src/helpers/assets.js
> Fix new wallet color

- src/components/list/ListHeader.js
- src/helpers/signingWallet.ts
- src/hooks/useShowcaseTokens.js
- src/hooks/useWebData.js
- src/model/migrations.js
- src/model/wallet.ts
- src/redux/showcaseTokens.js
- src/redux/wallets.js
- src/references/index.ts
- src/utils/keychainConstants.js
- Signing wallets and signatures are now generated on wallet creation.
- Web profiles are on by default
- For existing users - showcase is initialized once they share or add a new item to showcase
- For new users - it's enabled by default.
- Updated vercel url to main website
> Enable web profiles

- src/hooks/useWebData.js
To test have the latest web master branch pulled
> Update profile symbol only in the symbol is an emoji

- src/components/asset-list/RecyclerViewTypes.js
- src/components/showcase/ShowcaseHeader.js
regular wallet: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-18-15-59-56.25.png
read only wallet: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-18-16-00-23.33.png
calculateHeight needs a function so i just left the ternary
> showcase ui changes

- ios/Podfile.lock
- src/components/showcase/ShowcaseHeader.js
- src/hooks/useScanner.js
- support scanning rainbow profiles
- Fix "watch this wallet" from showcase sheet
> Web profiles bugfixes

- src/components/list/ListHeader.js
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-19-08-48-21.88.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-19-08-49-26.50.png
> one url for sharing

- src/components/discover-sheet/DiscoverSearchContainer.js
- src/components/exchange/ExchangeAssetList.js
Prevents https://sentry.io/organizations/rainbow-me/issues/2322026883/?environment=Release&project=1855565&query=is%3Aunresolved+level%3Afatal&sort=user&statsPeriod=14d
> Prevent discover crash

- src/components/expanded-state/asset/ChartExpandedState.js
- src/components/sheet/sheet-action-buttons/SwapActionButton.js
PoW: https://recordit.co/CgXITmEuiR
> Add non verified warning from expanded state => swap

- src/components/list/ListHeader.js
PoW: http://cloud.skylarbarrera.com/Screen-Recording-2021-05-21-13-01-11.mp4
non-ens wallet: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-21-13-06-50.03.png
> enable share for ReadOnlyWallets + add ENS 

- src/components/expanded-state/SwapDetailsState.js
> Fix jumping in SwapDetailsState

- yarn.lock
Reverts rainbow-me/rainbow#2051
This was fixed in the hermes branch
> Revert "Bump browserslist from 4.14.5 to 4.16.6"

- src/components/buttons/TokenSelectionButton.js
> Fix exchange sheet after RN bump

- src/components/buttons/BiometricButtonContent.js
- src/components/exchange/ExchangeDetailsButton.js
- src/components/expanded-state/WalletProfileState.js
- src/components/gas/GasSpeedButton.android.js
- src/components/header/DiscoverHeaderButton.js
Discover Button: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-26-16-57-57.15.png
import modal buttons: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-26-16-59-24.90.png
Flip + Swap Details: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-26-16-58-53.86.png
Custom Gas Button: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-26-16-58-29.70.png
> android line height fixes

- src/components/add-cash/AddCashForm.js
> Add warning about adding cash to wallet you have not imported

- android/app/build.gradle
- android/build.gradle
- android/gradle.properties
- ios/Podfile.lock
Some detox related code needed to be updated.
Also the pod lockfile was outdated
> Fix android release mode

- src/components/gas/GasSpeedButton.android.js
- src/components/investment-cards/PoolValue.js
- src/components/savings/APYPill.js
APY pill
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-06-02-15-34-26.66.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-06-02-16-28-18.65.png
Gas info icon
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-06-02-15-32-59.12.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-06-02-16-20-54.49.png
Pool value label
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-06-02-15-33-47.01.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-06-02-16-12-31.00.png
> android tweaks

- src/screens/ExchangeModal.js
> Track completed swaps only

- src/components/exchange/ExchangeAssetList.js
- src/components/gas/GasSpeedButton.android.js
- src/components/gas/GasSpeedButton.ios.js
- src/navigation/config.js
- src/screens/ExplainSheet.js
fixes RNBW-1175
POW 
ios: http://cloud.skylarbarrera.com/Screen-Recording-2021-06-03-17-50-33.mp4
android: http://cloud.skylarbarrera.com/Screen-Recording-2021-06-03-17-38-09.mp4
> verified tooltip

- e2e/helpers.js
- ios/Podfile.lock
- package.json
- src/components/expanded-state/UniqueTokenExpandedState.js
- src/components/text/MarkdownText.js
- src/components/text/index.js
- yarn.lock
Copy of @sbauch's https://github.com/rainbow-me/rainbow/pull/1990 PR but caught up over `develop` and including a minor cleanup of  `<MarkdownText />`. component
See https://github.com/rainbow-me/rainbow/pull/1990 for more
This code was already approved, the only code that needs to be reviewed in this PR is my commit https://github.com/rainbow-me/rainbow/commit/b28052968305236878bb315635e948368cb3b312
> Support rendering markdown from OpenSea API 

- src/components/unique-token/UniqueTokenCard.js
- src/components/unique-token/UniqueTokenImage.js
> Better ENS profiles

- e2e/watchAddressFlow.spec.js
vitalik.eth got heavy with doges, memes, and booterin
> change e2e watch address

- src/navigation/config.js
- src/screens/ExplainSheet.js
fixes RNBW-1230
ios: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-06-00-33-58.58.png
android: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-06-23-01-52.47.png
> update copy - verified explainer

- e2e/swapSheetFlow.spec.js
- src/screens/ExchangeModal.js
fixes RNBW-1178
PoW: http://cloud.skylarbarrera.com/Screen-Recording-2021-06-03-18-39-43.mp4
> gas > input alert

- src/App.js
- src/handlers/walletReadyEvents.js
- src/hooks/useInitializeWallet.js
> Move keychain integrity checks earlier

- shim.js
This PR is opening for research purposes only, so we can test the stability with LayoutAnimations off.
> [DO NOT MERGE] - disable layout animations

- src/components/coin-row/CoinRowInfoButton.js
- src/components/coin-row/ExchangeCoinRow.js
- src/components/exchange/ExchangeAssetList.js
- src/components/toasts/CopyToast.js
fixes RNBW-1156
swap: https://cloud.skylarbarrera.com/Screen-Recording-2021-06-07-16-23-21.mp4
discover: https://cloud.skylarbarrera.com/Screen-Recording-2021-06-07-16-24-00.mp4
copy toast update(a la christian): https://cloud.skylarbarrera.com/Screen-Recording-2021-06-07-16-47-05.mp4
> exchange context info 

- src/components/expanded-state/asset/ChartExpandedState.js
PoW: http://recordit.co/ZK4zBVOGyd
Fixes RNBW-1167
> Fix dissapearing balances in expanded state

- src/screens/QRScannerScreen.js
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-06-17-20-01-30.mp4
> delay camera permissions

- ios/Podfile.lock
- package.json
- yarn.lock
The dashboard is complaining we're using an old version.
> Bump sentry

- src/components/discover-sheet/DiscoverSheet.android.js
- src/components/qrcode-scanner/ConnectedDapps.js
Fixes
1. apps connected button alignment https://www.notion.so/rainbowdotme/Android-9a185c5d9b4240c48174c0896871feaf#8be47c77b51048a99fa3cfa492fc1c1a
2. Discover sheet wasn't scrolling up when the search input was focused on android 
https://www.notion.so/rainbowdotme/Android-9a185c5d9b4240c48174c0896871feaf#817b0832060f4e57a21126726429aa02
Fixes RNBW-1278
Fixes RNBW-1279
> Bugfix: android discover view

- src/components/unique-token/UniqueTokenImage.js
PoW:   http://recordit.co/LpgUNFf55c
Fixes #2040
> Support svgs NFTs from opensea

- e2e/ganacheTransactionFlow.spec.js
> update wc bridge for e2e

- src/components/expanded-state/UniqueTokenExpandedState.js
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
- src/components/send/SendAssetFormCollectible.js
- src/components/unique-token/UniqueTokenCard.js
- src/components/unique-token/UniqueTokenImage.js
- src/helpers/assets.js
- src/parsers/uniqueTokens.js
> Simplify ENS collection name, polish ENS cards

- src/components/coin-row/ExchangeCoinRow.js
PoW: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-24-12-00-29.29.png
> fix info on input selection

- ios/fastlane/Fastfile
- src/screens/WalletDiagnosticsSheet.js
This reverts commit 6cbfc9cc69591ce8027a612f5ae8834beab327a5.
> Revert "soucemaps test (#2144)"

- src/components/badge/NumberBadge.js
fixes RNBW-1304
single digit: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-28-11-53-44.01.png
double digit: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-28-11-56-25.19.png
> fix android number badge

- src/components/unique-token/UniqueTokenImage.js
- src/parsers/uniqueTokens.js
- src/references/index.ts
We started rendering SVGs lately but the UNI-v3 animated one hit different, so I had to exclude them.
Also moved contract addresses under references, which is where it should be.
PoW: http://recordit.co/myYC2HPkEs
> Fix UNI-v3 NFTs crash

- ios/DiscoverSheet/UIViewController+PanModalPresenter.swift
- src/react-native-cool-modals/ios/RNCMScreenStack.m
This might be a fix. Rather not regression, unless very obvious. 
@skylarbarrera, please test it against iOS 12, 13, and 14.
> Fix UITransitionView inconsistency 

- e2e/sendSheetFlow.spec.js
- src/components/coin-row/CoinRowAddButton.js
- src/components/coin-row/CoinRowFavoriteButton.js
- src/components/coin-row/CoinRowInfoButton.js
- src/components/expanded-state/chart/ChartAddToListButton.js
Got rid of some radial gradients that were slowing out e2e and were probably leading to test's timing out.
switched an issue from checking Dai -> Eth as if dai = usd we have two elements with the same value.
added a clearField to a contact modal test
> detox tweaks

- src/components/contacts/ContactRow.js
- src/components/expanded-state/ContactProfileState.js
- src/components/send/SendHeader.js
- src/components/text/TruncatedENS.js
- src/components/text/index.js
- src/utils/abbreviations.js
Contacts added via ENS will display their ENS address just like contacts added via 0x address in the contacts list and in the create/edit modal.
PoW: https://www.loom.com/share/bc28150c1e64417ea85121b370a5d03b
> Make ENS contacts behave like 0x address contacts
