rainbow-me/rainbow

- src/components/activity-list/RecyclerActivityList.js
1. With this Recycler Activity List (for the Profile screen), the currency/language selection changes don't seem to update the Profile screen right away (for instance, I choose USD--> ETH and it still shows me USD prices only on the Profile Screen while the Balance screen seems fine)
2. after the fixes you put in for popping / not popping the profile header, I noticed that after I import the seed phrase, the user's address doesn't update on the Profile header
Fix detecting different data mechanism on RecyclerActivityList.
> Fix refreshing currency and header's data

- ios/Podfile.lock
- src/components/activity-list/ActivityList.js
- src/components/activity-list/RecyclerActivityList.js
- src/components/asset-list/AssetListItemSkeleton.js
- src/components/asset-list/index.js
- src/hoc/index.js
- src/hoc/withAccountRefresh.js
- src/hoc/withAreTransactionsFetched.js
- src/hoc/withAreTransactionsFetching.js
- src/model/wallet.js
- src/redux/initialFetch.js
- src/redux/reducers.js
- src/screens/ProfileScreen.js
- src/screens/ProfileScreenWithData.js
There're a lot of things happened before making a list of transactions visible and especially when there's a lot of them it's reasonable to display feedback indicating that user is supposed to wait for a while.
Some conditions have to be filled in a situation when spinner has to be displayed. Transactions have not to be fetched for the first time, there have to be not loaded from storage (array of them has to be empty) and `AddFundsInterstitial` shouldn't be visible.
I achieved it by hooking into the fetching process and tracking the state of fetching in store by special hoc.
> Add spinner for fetching transactions 

- src/components/exchange/ExchangeInput.js
As per discussion on Slack #dev channel:
- Let's add the 18 9's as the default prop mask in ExchangeInputField
- We can pad the part before the decimal with more 9s
A separate task has been created to update the mask prop more dynamically given the decimals of an asset.
There is further discussion in the Slack #dev channel regarding the first part of the mask before the decimal regarding ellipses
> default exchange input mask to support 18 decimals max

- src/handlers/uniswap.js
- src/hoc/withDataInit.js
- src/hoc/withUniswapAllowances.js
- src/redux/uniswap.js
- src/redux/web3listener.js
- src/screens/ExchangeModal.js
- Issue: performance slowdown when requesting token reserve information
for all Uniswap tokens every 15 seconds
- Solution: remove this bulk interval call and fetch only the needed token
reserves once a user has selected currencies to swap. Set up a listener
that updates token reserve information only for these selected currencies on any new block. Once the swap modal is closed, stop listening for the token reserve info.
> fetch token reserve info only after user has selected currencies to swap

- src/components/unique-token/UniqueTokenAttributes.js
Fixes RAI-52 https://linear.app/issue/RAI-52
look! its fixed!
> Re-center NFT attributes in the ExpandedState

- src/components/GestureBlocker.js
- src/components/gas/GasSpeedLabelPagerItem.js
- src/screens/ExchangeModal.js
It ws pretty easy to accidentally dismiss snap stack,  especially when trying to change the transaction speed, so the tap to dismiss is dismissed.
> Disable tap to dismiss for swap modal

- src/components/coin-row/ExchangeCoinRow.js
- src/parsers/transactions.js
https://linear.app/issue/RAI-51
This also includes a fix for the ExchangeCoinRow (in Asset selection) to display only the balance if the pricing data is unavailable for an asset.
> fix: removal of pending unlock transactions once they are confirmed

- src/components/exchange/SlippageWarning.js
- src/helpers/__tests__/utilities.test.js
- src/helpers/utilities.js
- src/screens/ExchangeModal.js
https://linear.app/issue/RAI-57
Fix: convert slippage bips to percentage format
Changes made:
- Updated slippage warning thresholds to use bips for clarity
- Fix slippage bips to percentage format before being displayed
- Use execution rate slippage instead of market rate slippage
Market rate slippage is the slippage between the pre and post trade
market rates. (Market rates only take into account the input / output
token reserves.)
Execution rate slippage is the slippage between the pre-trade market
rate and the execution  rate. (Execution rates take into account the
actual trade itself as well as fees.)
The main difference between these two slippage rate is the fee.
> fix: convert slippage bips to percentage format

- src/components/settings-menu/SettingsSection.js
- src/handlers/localstorage/uniswap.js
multiRemove is only available directly on AsyncStorage, not through the react-native-storage package we are using. We will use multiGet/multiRemove once we move over to the AsyncStorage package directly.
> Fixes for multiRemove and network capitalization in Settings

- src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
- src/components/exchange/ConfirmExchangeButton.js
- src/screens/ExchangeModal.js
- src/screens/TransactionConfirmationScreen.js
New behavior:
- Will not navigate away when authorization fails (either by failure or
user cancel)
- Fix for Hold to Send/Swap/Sign buttons to animate back from
Authorizing state (for the Send, Swap, and WalletConnect flows)
> Fix: do not hide swap modal or send modal when canceling authentication

- src/redux/uniswap.js
- src/screens/ExchangeModal.js
https://linear.app/issue/RAI-55
Inverted and renamed "force" flag to be clearer (it used to represent when the currency selection was programmatically done. Now it indicates when a currency selection is from a user's selection action.)
Also removed the additional check for output currency which used to check that an asset would exist in the user's wallet when we auto-updated the input currency. This is not needed as this would imply the user could have set this in their input currency in the first place, which they can't.
> Fix: swap input / output currencies when selection causes match

- ios/Dummy.swift
- ios/Podfile
- ios/Podfile.lock
- ios/Rainbow-Bridging-Header.h
- ios/Rainbow.xcodeproj/project.pbxproj
- package.json
- yarn.lock
Used the RNTextInputMask branch that includes a podspec but followed the instructions on the README for RN 60 (instead of RN 61) so as not to use !use_frameworks (which causes issues for other dependencies)
> Autolink RNTextInputMask without the use of !use_frameworks

- src/screens/ExchangeModal.js
https://linear.app/issue/RAI-73
- The initial focus of the input was not happening, causing issues with
the keyboard transition
- Added extra logic to handle the case when an asset and null are
swapped during currency selection; the input focus should not be on the
last focused at that point as it will be unselectable without a currency
> Fix: input focus after selecting currencies 

- src/hoc/withUniswapAssets.js
https://linear.app/issue/RAI-71
> Fix: alphabetization of swap receive inputs

- src/helpers/__tests__/utilities.test.js
- src/helpers/utilities.js
- src/redux/send.js
- src/screens/ExchangeModal.js
Bug 1: DGX —> MKR typing into the native input doesn't update the output amount
Cause: We were not taking into account the input asset's decimals when converting from native prices to input prices, causing "raw" values with decimals in the end.
Bug 2: ETH —> Matic or WCK doesn't work when typing in input
Cause: We were not overwriting the prices from Uniswap for output prices (which we want to have for displaying decimals based on native price)
> Fix: swap bugs for output assets without a price + non-18 decimal input assets

- src/components/layout/KeyboardFixedOpenLayout.js
- src/handlers/localstorage/globalSettings.js
- src/helpers/keyboardHeight.js
- src/screens/WalletScreen.js
Save keyboard height to local storage to avoid jumps and overlays in modals using keyboard
Since it has to save the height of the keyboard in runtime, this fix won't affect the very first keyboard appearance after introducing it, but the issue won't happen ever since.
> save keyboard height to local storage

- src/screens/ExchangeModal.js
This is so we can update the focused input appropriately after a user selects from input: ETH, output: null, to selecting output of ETH (which causes the input currency to be null)
> Update location for finding the native tag on input ref

- src/screens/ProfileScreenWithData.js
I realized that when you have an empty wallet and want to receive something, the AddFundsInterstitial doesn't disappear as it should.
Just added some flag to make it disappear.
> add pending request count to determine isEmpty variable

- src/model/wallet.js
The current keychain config prevents the simulator from reading the PKEY while signing transactions so I've added a workaround for it.
> Bugfix: Make send flow work in the simulator

- ios/Podfile.lock
- package.json
- patches/react-native-svg+11.0.1.patch
- yarn.lock
- Bump `react-native-svg` from v9 to latest (v11)
- Patch `react-native-svg` to fix memory leak on iOS
> Bugfix: Fix memory leak caused by react-native-svg

- src/handlers/web3.js
- src/hoc/withDataInit.js
- src/model/wallet.js
- src/redux/data.js
Once there's a new transaction in pending state,  query the node to see when it's confirmed ASAP.
> Feat: Watch pending transactions

- src/hoc/withDataInit.js
- src/hoc/withGas.js
- src/redux/gas.js
- src/screens/ExchangeModal.js
- src/screens/SendSheet.js
- src/screens/TransactionConfirmationScreenWithData.js
- Use recursive setTimeout instead of setInterval
- Change always polling to polling while: 
-  On send flow
- On exchange flow
- On WC call
- Stop polling when components get unmounted
- Bump all gas prices x 1.101  to get ahead in the pool (faster confirmations)
> Feat: Optimize gas price

- patches/react-native+0.62.0-rc.1.patch
I've also submitted a PR to react-native [here](https://github.com/facebook/react-native/pull/27951), so we can delete this patch once it's gets merged
> Patch react-native vibration module

- package.json
- yarn.lock
The precommit hook was running eslint in the entire codebase every time you try to commit.
This PR modifies that behavior so it only runs against the files that were modified, which saves a lot of time.
> Feat: Precommit hook should only lint staged files

- src/App.js
- src/config/debug.js
- src/config/experimental.js
- src/debugging/network.js
- src/helpers/buildWalletSections.js
- src/helpers/isNativeButtonAvailable.js
- src/helpers/isNativeTransactionListAvailable.js
- src/screens/QRScannerScreen.js
This PR does a couple of things that will improve our debugging experience:
- Created a new `config` folder for `experimental` (previously at `./experimentalConfig.js`) and `debugging`
- Added ability to enable HTTP Requests and / or responses monitoring  by switching a debug config flag, which looks like this: 
- Ability to turn on the new LogBox from RN 0.62+ that's much more helpful than the previous yellow warnings by switching a debug config flag, which looks like this:
https://twitter.com/janicduplessis/status/1206645712869560320?lang=en
> Feat: Add networking debugging

- src/config/debug.js
- src/debugging/network.js
- Turn off all the debugging flags by default
- Improve timeout detection (some times the flag is true but the status is 200)
> Networking debugging

- src/screens/CurrencySelectModal.js
- src/screens/QRScannerScreenWithData.js
- src/screens/Routes/Routes.android.js
- src/screens/Routes/Routes.ios.js
- src/screens/WalletScreen.js
The problem:  Once you go to a view like SendSheet the isFocused property it's not updated anymore,
causing a lot of problems for the screens that depend on it, like QRScanner not starting, Wallet not re-rendering & Uniswap list not loading in the CurrencySelect modal.
The "solution":   Pass a parameter to the route that has been presented as `{ focus: true }` and disable it for the previous route by passing `{ focus: false }`
Those 3 issues mentioned above have been fixed without the need to turn off the NativeStack
> Bugfix: Native stack navigation related issues

- package.json
- src/components/value-chart/Chart.js
- src/components/value-chart/ValueChart.js
- src/config/experimental.js
- Add support for reloading chart after a change of input data JSON
- Add data JSON proptypes
- Add support for isImportant flag in points objects
> New value charts updates

- e2e/importFromSeed.spec.js
- e2e/init.js
- ios/Podfile
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Rainbow.xcodeproj/xcshareddata/xcschemes/Rainbow.xcscheme
- package.json
- react-native.config.js
- yarn.lock
- Removed "React" target, which fixed the command `react-native run-ios`
- Enabled the `Bundle react native and images` build step to run always
- Removed  build warnings (dupe imports,  linked packages and rnpm)
> Fix build issues

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.ios.js
- src/components/sheet/SheetActionButtonRow.js
Now all the other buttons are not square anymore, and the savings sheet ones work fine:
http://recordit.co/a8q9TvOutd
Fixes https://linear.app/issue/RAI-316/bpa-props-weirdness
> Fix buttons

- src/screens/Routes/Routes.ios.js
observed that this commit 1d5a130
made a regression. "Normal" stack animation is no longer visible when transitioning out (with no gesture)
According to the purpose of this commit, there's no reason for having this logic when routes are not inside the native stack. I' adding a proper check for this.
> Set focused as a param only in native stack

- src/components/token-family/TokenFamilyWrap.js
Removing the `withFabSendAction` HOC  from the TokenFamilyWrap which was causing this issue.
> Fix white screen bug in release mode

- src/screens/ExchangeModal.js
We were using the wrong flag to determine when to show the swap details modal.
> Add missing swap info modal

- src/components/send/SendHeader.js
https://linear.app/issue/RAI-363/when-you-add-a-contact-we-should-show-a-cancel-button-instead-of
> Fix contact flag to render 'Cancel' button instead of 'Delete Contact'

- patches/react-native-gesture-handler+1.6.0.patch
This removes the delay on presses inside Gesture Handler ScrollViews
> Fix button presses in swap lists

- src/screens/QRScannerScreenWithData.js
- src/screens/WalletScreen.js
https://linear.app/issue/RAI-131/when-send-sheet-opens-after-scanning-a-qr-code-status-bar-doesnt
> Remove hoc to reduce amount of status bar logic

- src/components/send/SendAssetFormToken.js
- src/screens/SendSheet.js
- change default focus to USD in send flow
- fix keyboard unnecessary dismiss while selecting asset directly from wallet screen, and omitting SendAssetList
Linear:
https://linear.app/issue/RAI-339/default-input-focus-to-focus-on-the-usd-input-in-send-flow
> Change default focus to USD in send flow, and fix keyboard dismiss issue

- ios/Button.swift
- ios/ButtonManager.m
- ios/Extensions.swift
- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.ios.js
- src/components/animations/TouchableScale.js
- src/components/fab/FloatingActionButton.js
As agreed, I added a new flag `useLateHaptic` to allow developers to decide if they want to delay haptics till `touchesEnded` event or not (`false` by default).
> useLateHaptic flag for buttons

- src/components/savings/SavingsSheetHeader.js
Fixes: https://linear.app/issue/RAI-381/savingssheet-for-non-stablecoin-tokens-have-more-than-2-decimals-for
> Set saving sheets decimals to 2

- src/components/activity-list/LoadingState.js
- src/components/activity-list/RecyclerActivityList.js
- src/components/transaction-list/TransactionList.js
- src/screens/ProfileScreen.js
Same behavior we added last week but applied to the native tx list.
Also downgrade the delay from 7 to 5 seconds.
This helps the bootstrap of the app tremendously and it's not noticeable for users 99% of the time.
> Defer the load of the native tx list

- src/components/coin-row/CoinRow.js
- src/parsers/transactions.js
We were not passing the address property to the CoinIcon component
After the fix:
> Fix coinicon on activity list

- src/utils/logger.js
Looks like RN is doing some bad shimming and it's preventing from call the logging functions with `.apply`
> Fix logging

- package.json
- src/components/transaction/TransactionMessage.js
- src/components/transaction/sections/MessageSigningSection.js
- src/model/wallet.js
- src/parsers/requests.js
- src/screens/TransactionConfirmationScreen.js
- src/screens/TransactionConfirmationScreenWithData.js
- src/utils/ethereumUtils.js
- src/utils/signingMethods.js
- yarn.lock
This PR add support for signTypedData (latest and legacy implementations) through WalletConnect.
Can be tested here: https://brunobar79.github.io/js-ethereum-signature-examples/
Fixes RAI-383
> Walletconnect signTypedData support

- ios/Podfile
- ios/Podfile.lock
Initially on RN 0.62 the recommended flipper integration was accidentally including all the transitive deps into release builds. This PR fixes this  (same as https://github.com/facebook/react-native/pull/28504)
> Exclude flipper deps from release builds

- src/hooks/useCheckEthBalance.js
This check prevents to sent an early and invalid request to get the balance while the address is still not set.
> Check eth balance only if address is set

- src/redux/testnetExplorer.js
Fixes https://sentry.io/organizations/rainbow-me/issues/1607861356/?environment=Release&project=1855565&query=is%3Aunresolved+release%3Ame.rainbow-1.2.7&statsPeriod=14d
> Retry fetching testnet prices if network not ready

- src/components/buttons/hold-to-authorize/HoldToAuthorizeButton.js
- I tested it only on iPhone X and simulators so it would be really cool if somebody will check this one out on the physical iPhone 8 or below.
- BTW I realized that every time I fail my FaceID check there instantly appears the second one. Is it desired behavior?
Fixes RAI-217 https://linear.app/issue/RAI-217/a-long-press-on-the-tap-to-send-button-should-trigger-a-press
> Fix behavior for long press in exchange modal

- ios/Podfile.lock
- package.json
- src/components/buttons/PasteAddressButton.js
- src/components/copy-tooltip/CopyTooltip.ios.js
- src/components/fields/AddressField.js
- src/components/send/SendHeader.js
- src/components/transaction-list/TransactionList.js
- src/hoc/withSendFeedback.js
- src/hooks/useClipboard.js
- yarn.lock
Since It has been deprecated from `react-native` as part of the "Lean Core" effort.
This PR removes the warning, which help us fixing RAI-466
> use Clipboard from react-native-community pkg

- package.json
Latest xCode version doesn't have iPhone X installed by default so I'm changing the default to be iPhone 11 when running `yarn ios`
> Update default sim to iPhone 11

- src/handlers/uniswap.js
We are now looking up the info on `eth-contract-metadata` first instead of going directly to the blockchain
> Avoid  unnecessary  eth_calls on Uniswap liquidity info

- src/screens/Routes/Routes.ios.js
Attemp to prevent: https://sentry.io/organizations/rainbow-me/issues/1626320675/?project=1855565&referrer=slack
> Prevent routes crashing if index missing

- src/screens/SavingsSheet.js
Fixes RAI-503 https://linear.app/issue/RAI-503/savings-prediction-stepper-values-are-incorrect
> Fix incorrect SavingsPredictionStepper values for non-stablecoins

- src/handlers/opensea-api.js
- src/parsers/transactions.js
- src/redux/data.js
- src/redux/uniqueTokens.js
Currently, it is set with a 1 minute delay after receiving a txn before refetching from OpenSea. For the cases I did, it was able to get the correct update by the 1 minute. This delay could potentially be reduced.
The recurring 15 second interval has been removed.
This has been tested on sending an ETH transaction (will not refresh), an ERC20 that was sent or received (will refresh), and a trade execution (will not refresh). I decided against checking these new transactions against an existing list of ERC20s for now, as I can do these preliminary checks with just the transaction data itself.
I tested the addresses of users with a ton of NFTs on simulator. It works! However, there was one user who had close to 2000 Cryptokitties, and the app became unusable after opening the token family …
> Use paging for OpenSea requests to fetch more unique tokens

- src/components/discover-sheet/DiscoverSheet.js
This is making the linter to throw an error, making all the test builds to fail
> Disable warning

- package.json
This PR addresses two separate things:
- Prevent linting of json files (linter fails when making changes to json files)
- Remove unnecessary `git add` per recommendation of @Kureev
> Update lint-staged config

- patches/react-native-cool-modals+0.0.7.patch
https://linear.app/issue/RAI-564/send-flow-input-refocusing-is-broken
> Fix calling onAppeared in cool-modals

- src/handlers/wyre.js
- src/hooks/useWyreApplePay.js
* Pass along error category and code for items without an order ID
* Track when a purchase is incomplete but not failed
Axios by default throws an error whenever a response is not in the 200 range. I had this default overridden for the Wyre API requests, but realize I only need to override it for the initial submitting of the order (where they come back with a non-200 status and some error information we want to pick up.) So I removed this check for the other Wyre API requests where we don't need it.
For the other endpoints, the response will come back 200 status but with the error statuses in the data payload itself.
Just FYI - I haven't tested this PR on device yet.
> 💸 Improve Add Cash funnel tracking

- src/screens/DepositModal.js
- src/screens/SavingsSheet.js
The issue was when you would deposit an asset whose underlying did not exist in the wallet - we were not passing along the underlying price from the Savings sheet for this scenario (only for withdrawals, not for deposits).
> Handle price when savings underlying does not exist in wallet

- src/parsers/newTransaction.js
- src/parsers/transactions.js
- src/raps/actions/depositCompound.js
- src/raps/actions/swap.js
- src/raps/actions/unlock.js
- src/raps/actions/withdrawCompound.js
- src/redux/data.js
This PR introduces a few things:
- fix appended transactions from using unnecessary "since last successful txn hash" logic
- instead, have the "received" transactions data payload use the last successful txn logic. Also, update this logic to include an extra 20 transactions in case any changes to recent transactions may have occurred
- be explicit about waiting for a rap to add the new pending txn to the txns list before continuing with the rest of the logic
Lastly,
After sending a transaction, the pending transaction watcher logic would run forever, even if the pending transactions have been resolved by Zerion. It was silently throwing an error "You attempted to set the key on an object that is meant to be immutable and has been frozen" because `const updatedTransactions = …
> Fix issues with pending txn watcher

- src/components/token-family/TokenFamilyHeader.js
Add width to truncate text correctly in the family header.
Result:
> Truncate text in family header

- src/components/coin-divider/CoinDividerOpenButton.js
- src/helpers/buildWalletSections.js
- src/parsers/transactions.js
- src/redux/data.js
- src/redux/explorer.js
* Remove unused logic in txn parser for "self" directed txns
* Fix error in txn removals that was trying to mutate the immutable transactions state
* Listen for txn changes (these can occur for instance after a txn has appended and gets an updated historical price)
> Listen for txn changes and fix txn removals

- src/components/add-cash/AddCashStatus.js
- src/handlers/wyre.js
- src/hooks/index.js
- src/hooks/useAddCashLimits.js
- src/hooks/usePurchaseTransactionStatus.js
- src/hooks/useWyreApplePay.js
- src/parsers/newTransaction.js
- src/parsers/transactions.js
- src/redux/addCash.js
- src/redux/data.js
- src/utils/ethereumUtils.js
* Fixes flash of "ETH on the way" after an Add Cash failure
* Handle polling of Wyre transfer hash outside of the hook (to prevent it from not being run if a user closes the Add Cash sheet too early)
* Rely on the pending txn watcher / Zerion for status updates (the Wyre endpoint for transfer status takes much longer)
> Improve Add Cash status polling logic

- src/components/add-cash/AddCashStatus.js
- src/handlers/wyre.js
- src/helpers/wyreStatusTypes.js
- src/hooks/useWyreApplePay.js
- src/redux/addCash.js
Previously we were showing completion on the Apple Pay sheet after it had finished running checks, but it can take a long time. Now, we will show a "Running checks..." status while it checks and complete the Apple Pay sheet sooner.
> Move up Apple Pay payment response completion and support "Running checks" status

- ios/TransactionListViewCell.swift
The status was previously not set properly for purchases (they were recognized as received before), but now that we set them properly, it was causing issues for the icon.
> Reuse received icon for purchase txns

- src/hooks/usePurchaseTransactionStatus.js
- src/hooks/useWyreApplePay.js
- src/redux/addCash.js
Since our Apple Pay sheet check has moved up, a user could close the modal during our order status checks.
> Move order status checks to redux as our Apple Pay sheet check has moved up

- ios/RCTConvert+TransactionList.h
- ios/Transaction.swift
- ios/TransactionListViewCell.swift
- src/components/coin-row/TransactionCoinRow.js
- src/components/coin-row/TransactionStatusBadge.js
- src/config/debug.js
- src/handlers/localstorage/accountLocal.js
- src/helpers/protocolTypes.js
- src/helpers/transactionDirectionTypes.js
- src/helpers/transactionTypes.js
- src/parsers/transactions.js
Move out txn title and description logic from components to parser.
Remove unnecessary logic from native txn list.
https://linear.app/rainbow/issue/RAI-603/only-show-label-txs-as-savings-if-tx-are-compound-related
> Differentiate between protocols for deposits and withdrawals

- src/handlers/uniswap.js
Before, we were always using the Uniswap SDK default max slippage value (which is 200 bips), even if a user had decided to move on with a transaction that has higher slippage than that (which would mean we would always let the txn fail). This slippage will now either use the default slippage value or the actual slippage (with some buffer), whichever is greater.
> Increase max slippage to Uniswap if needed

- src/screens/ChangeWalletSheet.js
Previously we were not saving any change if the wallet name was set to empty
> Allow wallet edition with empty names

- src/components/exchange/ExchangeField.js
- src/components/exchange/ExchangeInputField.js
- src/components/exchange/ExchangeOutputField.js
- src/components/layout/KeyboardFixedOpenLayout.js
Fix wrong heights and alignments of inputs on android.
I used some:
`const variableHeight = 20;`
`const variableHeightAndroid = 30;`
concept to differentiate between platforms but I will happily change that if there is some better way we can do it.
> Fix swap modal inputs

- ios/Podfile
- ios/Podfile.lock
- ios/Rainbow-Bridging-Header.h
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/TransactionListLoadingViewCell.swift
- ios/TransactionListLoadingViewCell.xib
- ios/TransactionListView.swift
- ios/TransactionListViewManager.m
- src/components/transaction-list/TransactionList.js
- src/screens/ProfileScreen.js
This PR removes the need to alternate between native & JS activity lists on runtime while the list is loading.
@christianbaroni  Feel free to play around tweaking [this values](https://github.com/rainbow-me/rainbow/compare/@bruno/native-skeleton-view?expand=1#diff-1b40412112b39eaa02911e5b7d22f1c2R24)
The explanation & defaults are [here](https://github.com/facebook/Shimmer/blob/bfeedb79a8aba946649ef48521eb4ae53d2eeb72/FBShimmering/FBShimmering.h#L31)
Also, you might wanna harcode [this](https://github.com/rainbow-me/rainbow/compare/@bruno/native-skeleton-view?expand=1#diff-060760b344069f6476991238fd60dc6bR195) to true while playing with it.
DEMO: http://recordit.co/PYoJOEYB1W
> Native skeleton + shimmer for activity list

- src/components/change-wallet/WalletList.js
- src/redux/wallets.js
This PR fixes these two blockers:
- https://linear.app/rainbow/issue/RAI-640/fix-possible-state-where-there-is-no-selected-wallet
- https://linear.app/rainbow/issue/RAI-642/duplicate-wallet-rows-in-multiwallet
> Multiwallet fixes

- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/CoinCheckButton.js
- src/components/coin-row/CoinRow.js
Fixes RAI-626 https://linear.app/rainbow/issue/RAI-626/fix-balancecoinrow-styles-no-longer-update-when-tokens-are-hidden
> Fix BalanceCoinRow not updating styles when toggling isHidden/isPinned

- src/components/expanded-state/ChartExpandedState.js
- src/components/sheet/sheet-action-buttons/SwapActionButton.js
- src/helpers/assetInputTypes.js
- src/hooks/useExpandedStateNavigation.js
- src/screens/SwapModal.js
Fixes RAI-649 https://linear.app/rainbow/issue/RAI-649/expanded-asset-state-should-populate-swap-input
> Pass along default input to swap from expanded state

- src/handlers/localstorage/globalSettings.js
- src/hoc/withAccountInfo.js
- src/hooks/useAccountProfile.js
- src/hooks/useAccountSettings.js
- src/hooks/useInitializeWallet.js
- src/redux/settings.js
We fetch the ENS name after loading the account address from the keychain into redux. However, we were never storing the ENS longterm anywhere. This adds the storage of the ENS name to localstorage for loading the next time.
We might want to consider including the ENS name in the extra keychain data and keeping the logic to update it when we load the account address from keychain. This way we can be sure the keychain and localstorage won't ever be out of sync.
> Save ENS after resolving

- src/App.js
- src/hooks/useLoadAccountData.js
- src/hooks/useResetAccountState.js
- src/redux/settings.js
- src/redux/walletconnect.js
- src/references/index.js
- src/screens/QRScannerScreenWithData.js
- Prevent scanning address QR codes with read only wallets - https://linear.app/rainbow/issue/RAI-644/disable-scanner-for-address-qr-code-when-wallet-is-read-only
- Reject and show alert for WC requests when using read only wallet - 
- App crash when switching accounts & WC session active https://linear.app/rainbow/issue/RAI-646/app-crashing-while-switching-wallets-with-active-wc-session
- Fix WC support for testnets
> Scanner & WalletConnect fixes for Multiwallet

- src/components/change-wallet/WalletList.js
- src/hooks/useInitializeWallet.js
- src/redux/settings.js
- src/screens/ChangeWalletSheet.js
- src/screens/WalletScreen.js
- Fixes "not scrolling to selected account sometimes"
- Fixes "sometimes seeing the top row slide down and replace some other row"
- Fixes skeleton not showing
- Fix switch to the wrong account bug
- Run migrations only on app launch (not when switching accounts)
- Migrate WalletList from RLV to Flatlist
> More multiwallet bugs

- src/screens/ChangeWalletSheet.js
Recording can be found: https://linear.app/rainbow/issue/RAI-653/improve-selected-checkmark-delay-when-selecting-a-new-wallet
Tested switching accounts, account creation, import existing wallet, deleting accounts, deleting the selected account
> Keep separate state on ChangeWalletList to update selected wallet quickly

- src/components/send/SendHeader.js
Fxies RAI-659 https://linear.app/rainbow/issue/RAI-659/crash-canceling-add-to-contacts-after-having-an-input-focused
> Fix app crashing when closing AddContactState modal

- src/handlers/opensea-api.js
Thanks to Wojtek's fixes, we can bump up the number of NFTs we fetch for a user without it destroying the app!
> Bump up max number of NFTs we get from OpenSea

- src/components/coin-row/BalanceCoinRow.js
Fixes the problem happening in this screenshot
> Prevent overlapping text in BalanceCoinRow when CoinName is very long

- src/components/savings/SavingsSheetEmptyState.js
- src/components/text/index.js
Fixes RAI-660 https://linear.app/rainbow/issue/RAI-660/pressing-the-deposit-button-from-the-savings-row-directly-on-wallet
> Fix app crash on press Deposit button

- src/screens/Routes/Routes.ios.js
this allows dismiss gestures outside of the sheet when it's scrolled. gestures on the header mostly work, seems like there are some issues deeper in the modals.
@osdnk I'm noticing that when a headerHeight is set, gestures on the header aren't immediately responded to if the list is scrolled. you need to hold your finger down or drag a couple times for it to catch the sheet
in this case, the sheet has a header height of 58. but setting it to anything higher than 46 causes it to interfere with swiping up at the very top of the list. oddly it doesn't interfere with swiping down. in this video it's set to 58:
https://www.dropbox.com/s/vsf0bpbmzzv76hv/Screen%20Recording%202020-05-25%20at%204.13.13%20AM.mov?dl=0
> Partially fix wallet sheet gesture when list is scrolled

- src/parsers/requests.js
Added a few safety checks for  WC requests data that was breaking the native TX list due to passing NaN through the bridge which is an invalid native type, resulting in the requests not shown.
This fixes the problem with defisaver.com (WC request not showing because the tx list was throwing and we were swallowing the error)
> Safety check for WC requests

- src/App.js
This PR fixes two issues:
- Deeplinks not being handled when Branch callback fails:
In this scenario we still lose the attribution but the deeplink should be handled properly
- WC TX requests via deeplink not showing up until restarting the app
We're now reloading all the WC connectors when the app comes back from background, so it has the same effect as relaunching the app
> WC fixes for mobile deeplinking

- src/references/token-overrides.json
zerion gives us HOLO as its symbol, HOT is the correct symbol
this makes it consistent with swap and fixes missing token icon
> Fix Holo token symbol (HOLO → HOT)

- src/model/firebase.js
Based on the docs we don't need to call this at all unless we disable it manually (which we are not doing)
https://github.com/invertase/react-native-firebase/blob/master/docs/messaging/usage/index.md#auto-initialization
This potentially fixes the bug that causes the app to get stuck at the rainbow logo on the splash screen and then crashes
> Remove unnecessary firebase registration

- src/handlers/localstorage/globalSettings.js
- src/hooks/useImageMetadata.js
- src/redux/imageMetadata.js
This fixes the loading of image meta data from localstorage into redux.
Since the dispatch in the loading function doesn't have an id passed into it and is passing along payload instead of metadata, the MERGE action will set the draft to look like draft[undefined] = undefined.
Given that draft cannot just be overwritten by the payload, I also added the imageMetadata item inside the initial state.
I also explicitly set the default value from localstorage for image metadata to empty object (default for getGlobal is [])
> Fix image metadata redux loading

- src/navigation/ExchangeModalNavigator.js
- src/screens/CurrencySelectModal.js
I observed that opacity listener sometimes does not call the "final" value. E.g. it stays on 0.998 instead of 1.0 or 0.1 instead on 0.0.
Actually, it's not guaranteed according to the implementation that the final must be really called. In order to fix it I just "manually" set the final result when the focus is changed. I haven't managed to reproduce it, but following my deduction, it should work. Definitely it's not breaking :)
> Force setting correct opacity after toggling focus

- src/navigation/Routes.android.js
- src/navigation/Routes.ios.js
- src/navigation/nativeStackHelpers.js
- src/screens/ImportSeedPhraseSheetWithData.js
We were getting a React hooks error that only happened in release mode, related to the use of pure from
recompact.
> Remove unnecessary ImportSeedPhraseSheetWithData

- src/components/AddFundsInterstitial.js
- src/components/coin-row/BalanceCoinRow.js
- src/components/fab/SendFab.js
- src/components/profile/ProfileMasthead.js
- src/components/sheet/sheet-action-buttons/SendActionButton.js
- src/components/transaction-list/TransactionList.js
- src/helpers/buildWalletSections.js
- src/navigation/routesNames.js
- src/screens/ChangeWalletSheet.js
- src/screens/QRScannerScreenWithData.js
I've separated out the commits such that you should be able to just walk through the commits.
The Import seed phrase sheet / navigator, send sheet / navigator, and add cash sheet / navigator need to have the route name in navigation.navigate(routeName) to be different depending on if native stacks are supported.
I've included extra routes in routesNames.js that takes care of this logic so that our code doesn't need to have it scattered in too many places.
There are some places that still require an isNativeStacksSupported check due to different param formats being passed in.
In some places, I removed the Platform ios check since the route would just use the fallback in the case that isNativeStacksSupported (which also checks ios platform) is false.
> Fix navigation that breaks for routes that have different names for non-native vs native stacks

- src/components/activity-list/RecyclerActivityList.js
- src/navigation/Routes.android.js
- src/navigation/effects.js
Fix 
1: https://linear.app/rainbow/issue/RAI-694/wallet-sheet-should-slide-up-from-bottom
2: https://linear.app/rainbow/issue/RAI-695/activity-list-empty-state-is-missing
> Fix animation for change wallet modal and add empty state on android

- src/parsers/newTransaction.js
- src/parsers/transactions.js
- src/redux/data.js
With the new title and description fields, we were updating the status but not the title in the pending txn watcher once it found the confirmed txn.
In the future, we should improve our txn parsing between parsers/transaction and parsers/newTransaction and pending txn watcher.
> Fix updating txn title after pending txn watcher completes

- src/components/change-wallet/WalletList.js
Just the account ID (address) was not unique enough for instances where an address could be added as both read-only and not-read-only.
> WalletList to extract unique key based on wallet id and account id

- src/model/wallet.js
- src/screens/ImportSeedPhraseSheet.js
Previously, we would only auto-fill the "new wallet" modal with ENS for read only addresses.
Now if a user imports a seed phrase / private key that has an ENS attached to it, we can auto-fill that in the "new wallet" modal as well.
Before: https://recordit.co/Z2qekfEr55
After: https://recordit.co/nnCkYr29Ug
Some logic is redundant, but didn't want to mess around with the init wallet flow just yet. Figured this may still be a useful feature for the user.
> Check for ENS name on import of a seed phrase

- src/components/coin-row/TransactionCoinRow.js
- src/components/transaction-list/TransactionList.js
- src/helpers/transactions.js
- only show address and 'add to contacts' if it's a vanilla send or receive. before we were showing it on all transactions, swaps, etc. user was confused about it
- add date of tx confirmation to context menu title
I noticed this logic is all duplicated for the native and JS lists. not sure it's worth cleaning up now, just a heads up
> Improve transaction context menu

- patches/react-native+0.62.2.patch
gives us better rounded corners on views if:
- all corners have equal radii of less than half smallest view dimension
- view doesn't have a border
- iOS 13+
> Patch RN to use continuous corners when possible

- src/App.js
- src/navigation/useStatusBarManaging.js
I observed that while popping the state (with component-based Status Bar API), we don't have any state pushed initially
> Fix status bar managing in Swap

- src/redux/web3listener.js
When we turn off the listener and then turn it back on again, while the network request to Infura is still 1 request, ethers.js will emit all the blocks since the last block number it remembers to the latest. We were making network requests based on each block number we were receiving, so this should be throttled.
Technically, since we don't use the block number, we don't even need to listen to blocks, we could just make this call happen every 10 seconds.
> Throttle the block listener for reserve updates

- src/components/asset-list/RecyclerViewTypes.js
This big PR resolve https://linear.app/rainbow/issue/RAI-732/on-ropsten-eth-coin-row-positioning-is-wrong
> Fix single row height in wallet screen when on testnet

- src/components/value-chart/ValueChart.js
@wojtus7 what do you think of this instead? seems a bit cleaner this way, and easier to modify
noticed in previous implementation the dot would suddenly jump to the edges when it got near them (more noticeable if you increased the `0.05 * width` number)
> Use interpolation for modified touchX variable

- src/hooks/useUniswapCurrencies.js
- src/screens/CurrencySelectModal.js
- src/screens/ExchangeModal.js
adds tracking for:
- toggling favorite
- selecting an asset after searching
- when slippage warning gets shown
- whether a swap was done even tho slippage warning was shown
Fixes RAI-284 https://linear.app/rainbow/issue/RAI-284/add-analytics-tracking-for-all-uniswap-search-queries
> add more tracking to swap flow

- src/utils/logger.js
addDataBreadcrumb expects an object instead of a string
> Fix sentry logs

- src/hooks/useUniswapMarketDetails.js
When the output amount is set to zero, we were "resetting" the input amount (which also resets the isInputAmountExact flag unless specified). This was causing it to switch from "updating input amount given output amount change" to instead "updating output amount given input amount change" which was not the aim when updating the output amount.
> If output amount is set to zero, do not flip the isInputAmountExact flag

- src/handlers/wyre.js
- src/hooks/useWyreApplePay.js
- src/references/wyre/orderExceptions.js
Note, this has only been tested on Kovan because Wyre is still working on making it ready for mainnet. It is breaking in mainnet, so I'll look into what to do while it isn't available.
Also note, if you want to test this, you'll need to get the latest dotenvs.
Fixes: https://linear.app/rainbow/issue/RAI-757/wyre-order-reservations-endpoint-required-by-aug-3rd
> Support Wyre order reservation

- src/hooks/useInitializeWallet.js
The poor internet connection can make init wallet logic get stuck up to 2 mins on 
```await dispatch(settingsLoadNetwork());```
resulting in veeeeeery long splash screen.
This PR tweak logic makes an emergency exit after a 10-sec timeout to hide the splash screen - after that fetching logic is not stopped, the app is able to open with cached data and still try to connect.
https://linear.app/rainbow/issue/RAI-756/with-poor-internet-connection-app-gets-stuck-on-splash-screen
> Tweak logic make emergency exit after 10 sec timeout on splash screen 

- src/raps/actions/swap.js
- src/raps/swapAndDepositCompound.js
- src/raps/unlockAndSwap.js
- src/screens/ExchangeModal.js
Remove check for input/output amount while calculating TxFee. 
Before if input/output was empty TxFee showed default value for `eth` what made it look strange while swapping different currencies.
https://linear.app/rainbow/issue/RAI-767/swap-gas-estimations-arent-accurate-till-you-type-an-amount
> Always calculate TxFee when entering swap screen.

- src/components/backup/BackupConfirmPasswordStep.js
- src/components/backup/BackupIcloudStep.js
- src/components/settings-menu/BackupSection/AlreadyBackedUpView.js
- src/hooks/useWalletCloudBackup.js
- src/screens/BackupSheet.js
Wanted to consolidate the iCloud backup logic that was shared across BackupConfirmPasswordStep, BackupIcloudStep, AlreadyBackedUpView, and BackupSheet. This helps make it easier to reason about.
For comparing logic, you can step through the original functions and see that the logic is still the same based on the params passed in. We can walk through them together as well!
> Consolidate icloud backup logic across multiple views

- src/navigation/routesNames.js
I wasn't able to launch the app on Android unless I rewrote this expression
> Fix android crash native stack

- src/components/savings/SavingsListRowAnimatedNumber.js
> fix styles for RainbowText in savings row for iphone 6's

- src/components/transaction/TransactionSheet.js
- src/components/transaction/sections/DefaultTransactionConfirmationSection.js
- src/components/transaction/sections/MessageSigningSection.js
- src/components/transaction/sections/TransactionConfirmationSection.js
- src/redux/gas.js
- src/screens/TransactionConfirmationScreen.js
- Transactions where failing cause we were passing gasLimit: 0
- Gas calculation was setting the default values before getting the new ones on every transaction, making the number go crazy
(now the default gas value is set only when there's no previous price)
- There was a bug preventing the tx fee to be updated when the estimated gas limit was the same for two tx requests
> Fix WC transaction issues

- package.json
- src/components/settings-menu/DevSection.js
- src/components/toasts/TestnetToast.js
- src/handlers/web3.js
- yarn.lock
This PR adds ganache as a dev dependency and a new npm script that will launch it (`yarn ganache`)
Once you launch the server you can connect to it via Settings => Developer Settings => Connect to Ganache
This will allow you to all types of transactions from a fake mainnet, without the need of paying real gas fees.
Tested with: 
- Send ETH (including ENS support)
- Send any token
- Swap any token
- WalletConnect send tx (via example.walletconnect.org)
- Uniswap v2 via WalletConnect
Some gotchas:
- Balances won't updated since they are still loaded from zerion (will fix soon)
- Won't persist during app sessions. If you restart the app you have to manually connect again
- There's no disconnect but you can achieve that by killing the app
- Swap tx never confirm in the UI cause (probably a …
> Add ganache support

- src/components/backup/BackupConfirmPasswordStep.js
- src/components/backup/BackupIcloudStep.js
- src/components/restore/RestoreIcloudStep.js
- src/hooks/useWalletCloudBackup.js
- src/hooks/useWallets.js
- src/screens/ChangeWalletSheet.js
move setIsWalletLoading into the useWallet hook 
💬️ i hate having `dispatch`'s all over the place and would rather have them handled by the hook handling that same activity
Utilize power of reselect instead of manual memoization inside of useWallets hook
💬️ i think that this pattern is cleaner. like conceptually i think that `selectors` should be responsible for handling any desired transformations of the selector output.
> move handling of setIsWalletLoading into the useWallets hook

- src/components/sheet/SheetHandleFixedToTop.js
- src/navigation/Routes.ios.js
- src/navigation/config.js
This allows us to create a config for the BackupSheet which has its height controlled by the route's current `step` param
> create config generator for cool-modals-related screens

- shim.js
- src/components/token-info/TokenInfoRow.js
```
PropTypes error in: TokenFamilyHeaderIcon.js:39 in TokenFamilyHeader.js:92 in View.js:34 in LayoutWithMargins.js:15 in TokenFamilyHeader.js:88 in View.js:34
```
instead of
```
Warning: Failed prop type: Invalid prop `align` of value `flex-end` supplied to `Flex`, expected one of ["baseline","center","end","start","stretch"].
in Flex (at LayoutWithMargins.js:15)
in ForwardRef(LayoutWithMargins) (created by Context.Consumer)
in StyledNativeComponent (created by AssetListItemSkeleton___c5)
in AssetListItemSkeleton___c5 (at AssetListItemSkeleton.js:142)
in RCTView (at View.js:34)
in View (at MaskedView.js:75)
in RNCMaskedView (at MaskedView.js:74)
in MaskedView (at AssetListItemSkeleton.js:164)
in RCTView (at View.js:34)
in View (created by Context.Consumer)
in StyledNativeComponent …
```
> Shorten proptypes error

- src/components/expanded-state/ChartExpandedState.js
Sometimes data's fallback is very poor. I think that if have less (or eq) than 5 points it's pointless (pun not intended) to display charts because data are very not reliable nor regular and it's better not to show anything
> Show charts only if contains more than 5 points

- patches/react-native-reanimated+2.0.0-alpha.5.patch
Looks like https://github.com/software-mansion/react-native-reanimated/pull/1187 include some fixes for crashes like we rarely face. This commit is def worth including for that.
I haven't faced any crash after this!
> Include react-native-reanimated#1187 fix for unregistering listeners

- src/components/expanded-state/ChartExpandedState.js
- src/react-native-animated-charts/src/ChartProvider.js
- src/react-native-animated-charts/src/helpers.js
- src/react-native-animated-charts/src/interpolations/bSplineInterpolation.js
- src/react-native-animated-charts/src/interpolations/monotoneCubicInterpolation.js
I observed that after interpolating it's possible that max and min value are no longer extremes after performing interpolations. Thus I added a parameter to persist it and extremes add after creating output result for drawing chart.
This issue is especially visible in stablecoins
Before:
After:
> Add includeExtremes to interpolations

- shim.js
I observed that InteractionManager sometimes has some uncleaned tasks. Most likely, it's a bug made us or some library. 
However, I think it's worth to assure that every interaction won't block the manager for longer than 2 seconds. I assume that none of our interactions/animations takes longer than 2 seconds and if it does, it's a bug.
> Tweak InteractionManager to finish all interactions at some point

- src/navigation/config.js
- src/react-native-cool-modals/NativeStackView.js
When `autoJumpToNewHeight` is enabled, the cool-modal will automatically `jumpToLong` whenever `longFormHeight` changes, or `jumpToShort` whenever `shortFormHeight` changes
> Create new "autoJumpToNewHeight" option for cool-modals

- src/components/secret-display/SecretDisplayCard.js
Fixes RAI-739 https://linear.app/rainbow/issue/RAI-739/cant-copy-private-key-in-backup-settings
> Add CopyTooltip to SecretDisplayCard

- src/hooks/useInitializeWallet.js
- src/model/wallet.ts
- src/screens/ImportSeedPhraseSheet.js
https://linear.app/rainbow/issue/RAI-775/reuse-the-already-created-wallet-object-for-ens-lookup-during
> Reuse wallet created during import

- src/screens/ChangeWalletSheet.js
✅ https://linear.app/rainbow/issue/RAI-774/after-creating-a-new-wallet-the-selected-wallet-checkmark-does-not ✅
> Fix checkmark during wallet creation

- src/components/change-wallet/AddressRow.js
After creating a new wallet the balance was showing ` ETH` when it should be `0 ETH`
Before the fix:
After the fix:
> Fix balance when creating new wallet

- shim.js
- src/hooks/useInitializeAccountData.js
- src/hooks/useSavingsAccount.js
- src/screens/SavingsSheet.js
- src/screens/SendSheet.js
- src/screens/TransactionConfirmationScreen.js
- Dont dismiss sheet if withdrawing / depositing with read only wallet (also prevents crash)
- Let interactions finish on its own on certain screens (savings, WC, sendsheet) where actions can take > 2 seconds
> Savings issues

- ios/Podfile
- ios/Podfile.lock
- src/react-native-cool-modals/ios/UIViewController+slack.swift
I have observed that using `object_setClass` leads to a ton of crashing because of some internal inconsistency in UIKit. 
Indeed, it's a bit hacky so I decided to remove this hack in favor of overriding `hitTest` with the method's swizzling. It doesn't have the impact unless the `hacked` flag is set (it happens only for screen that is dismissing to allow scrolling area under the screen) so is a no-op in the rest of usages.
> Ultimately solve crashes related to cool-modals

- ios/Rainbow/AppDelegate.mm
- patches/react-native+0.63.2.patch
- shim.js
We don't take any advantages of using the new architecture excluding using reanimated v2. However, I observed a ton of crashes. Hope that disabling every turbo module excluding reanimated will dramatically reduce the number of cxx crashes.
> Disable TurboModules excluding Native Reanimated

- src/components/settings-menu/SettingsSection.js
I've commented out unused vars to fix CI build, not sure if we want to just remove these for the time being. Here's the failed build for reference: [https://app.bitrise.io/build/b2e6863fdb6809f6#?tab=log](url)
> commented out unused vars for language Settings to fix CI build

- src/helpers/savings.js
Context: 
https://rainbowhaus.slack.com/archives/CGUDDJYNL/p1601641461079400
Before the fix:
After the fix:
> SAI is no longer a stablecoin

- src/components/buttons/PasteAddressButton.js
- src/components/send/SendContactList.js
- src/components/toasts/InvalidPasteToast.js
- src/components/toasts/ToastPositionContainer.js
- src/hooks/useInvalidPaste.js
- src/screens/ImportSeedPhraseSheet.js
Fixes these 3 issues reported by Christian in Slack
> Fix broken clipboard validation in PasteAddressButton

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/fab/FabWrapper.js
- src/components/fab/FloatingActionButton.js
- src/components/profile/AvatarCircle.js
- src/components/savings/SavingsListRow.js
- src/components/unique-token/UniqueTokenCard.js
- src/navigation/SwipeNavigator.js
Fixes ripples in:
1. Fabs
2. Savings sheet
3. Unique token
4. Profile Avatar
Now they are no bigger than the button size
tested and no regressions on ios
> Fix ripples in buttons on Android

- src/components/add-cash/AddCashForm.js
- src/handlers/wyre.js
- src/helpers/utilities.js
- src/hooks/useAddCashLimits.js
- src/hooks/useWyreApplePay.js
- src/screens/AddCashSheet.js
* Split up fees to show purchase vs network fee
* Use Wyre's quotation endpoint to get the final price we should be charging users in order for them to get their originally intended amount
* Alert user if we could not reserve the order or get a quote (required before requesting Apple Pay)
* Update weekly and annual limits (we used to have $250 daily and $1500 annual limits - now we have $500 daily / weekly limits, and $5000 annual limit)
> Updates to Wyre order minimums and limits

- src/components/coin-row/TransactionCoinRow.js
- src/components/expanded-state/chart/ChartContextButton.js
- src/components/transaction-list/TransactionList.js
We can just press on the background or use the physical button. There's no need for the 'cancel' button. 
Before: 
After:
> Remove "cancel" from charts menu on Android

- src/components/AddFundsInterstitial.js
- src/components/AppVersionStamp.js
- src/components/profile/ProfileMasthead.js
- src/components/transaction-list/TransactionList.js
- src/hooks/index.js
- src/hooks/useWallets.js
- src/hooks/useWalletsDebug.js
- src/screens/ChangeWalletSheet.js
- Mark the wallet as damaged to prevent funds to be deposited
- Attempt to restore while tapping on version stamp
To repro the interrupted wallet creation scenario, you need to:
1 -  clear the keychain
2 - Add   `return ;` in the line 569 of `src/model/wallet.ts`
3 - Restart the app
4 - Tap on "Get a new wallet"
> Handle interrupted wallet creation

- src/redux/wallets.js
- src/screens/ChangeWalletSheet.js
If a seed was backed up, new wallets created after the backup will now be backed up automatically.
> Backup new accounts

- src/react-native-cool-modals/ios/UIViewController+slack.swift
This should fix our #1 crash: https://console.firebase.google.com/u/0/project/rainbow-me/crashlytics/app/ios:me.rainbow/issues/e2c7a8f98e6729ddd4b0ae66eddaa48c?time=last-twenty-four-hours&sessionEventKey=c6fb827423744ba2b727e6b626483085_1462404963284403947
@skylarbarrera Can you play around with sheets / modals and see if everything looks normal?
> Fix optional unwrapping in cool-modals

- src/references/compound/saving-assets.json
doesn't have an icon because the UNI icon is a png that comes from Trust and not our coin icon package
> Add cUNI support

- src/components/asset-list/RecyclerAssetList.js
- src/components/asset-list/RecyclerViewTypes.js
- src/components/coin-row/SavingsCoinRow.js
- src/components/send/SendAssetList.js
I tried to replace all ✨magic numbers✨ with some sensibly named variable. 
Let me know if I overlooked any ✨number✨
Pools and savings are described by 4 super similar but separate variables. This is due to the fact that I wanted to keep original sizes without even a 1px change for any state. If you find it not readable I can simplify it, but not without some layout data loss
> Eliminate magic numbers from RLV ✨

- src/config/debug.js
- src/raps/actions/unlock.js
This is to help aid in testing the approval flow. It will assume all ERC20s need approvals and not do the allowance check.
> Expose debug config to always require token approval

- src/model/backup.ts
This PR fixes the scenario where non backed up wallets were being restored (bug) along with the ones that were backed up.
To check that this bug is fixed:
- Delete all backups from settings and wipe the keychain
- Import a pkey  (call it PKEY) and dont' back it up
- Import a read only (call it READONLY) and don't back it up
- Import another wallet, could be pkey or seed (call it SAFU) and back it up.
Wipe the device and restore from iCloud.
It should say that you have 1 wallet backed up. After reimporting only READONLY and SAFU should show (PKEY shouldn't be there)
> Restore only backedup and readonly wallets

- src/components/exchange/index.js
The linter is not complaining about the no-cycle error anymore, so we have to remove it in order to prevent an error.
> Fix linting errors

- src/components/exchange/ExchangeAssetList.js
this gives the swap asset list slightly more resources, enough that the list items render in time when scrolling quickly. would previously see white gaps in the list
> Optimize swap list

- src/components/modal/Modal.js
- src/screens/SettingsModal.js
Before it was possible to click like this
> Remove touchable backdrop on android

- src/components/buttons/MiniButton.js
> Fix border radius for ripple animation in Minibutton on Android

- e2e/importPrivateKeyFlow.spec.js
- src/components/settings-menu/DevSection.js
- src/hooks/useWalletsDebug.js
- src/model/wallet.ts
The ethers upgrade is more strict about the hex values it receives in certain functions (including the Wallet object creation). When we identify an input is a private key, we will now explicitly prefix it with 0x if needed before passing it along to the Wallet object.
> Add optional hex prefix for private keys when creating wallets

- src/handlers/deeplinks.js
- src/redux/requests.js
- src/redux/walletconnect.js
- src/screens/TransactionConfirmationScreen.js
This allows native apps to pass the scheme that we can use to redirect back. If they send it, we avoid the confirmation sheet and redirect back instead.
We can't really test this until https://github.com/WalletConnect/WalletConnectSwift/pull/34 and https://github.com/WalletConnect/WalletConnectSwift/pull/35 get merged, but here's the PoW: https://recordit.co/60R7Vj3a6E
@skylarbarrera  Just make sure this doesn't break any of the existing WC behavior (it shouldn't!)
> Allow automatic redirects for native apps

- patches/react-native-keychain+6.1.1.patch
This broke since we added the alternate domains for universal links.
react-native-keychain doesn't support specifying the domain / account via params, so it tries to fetch all the domains, and the ones on branch are outside of our control, so it gives an error.
I've patched the library to specify the domain / account we want to fetch credentials with for iCloud backups.
Before it wasn't able to fetch the password when:
- attempting to restore a wallet
- attempting to add a wallet to an existing backup
PoW: http://recordit.co/4J89LhlBhW
> Fix requestSharedWebCredentials

- src/App.js
- src/components/toasts/TestnetToast.js
- src/navigation/SwipeNavigator.js
This PR fixes two things:
- Moves the testnet toast to the top level views (Profile / wallet / scanner) to prevent overlap with other UI elements
- Fixes the bug that was preventing the ganache toast to not show up making e2e test fails.
All the iOS e2e tests are now passing locally.
> Ganache fixes

- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/components/fab/FabWrapper.js
- use heavy font weight for chart price label
- remove monospace setting on chart price label
- fix chart price label truncation when scrubbing by giving it a fixed width
- increase spacing between FABs
> Android branch fixes

- src/components/value-chart/Chart.js
Both iOS and Android props are the same, so there's no need to keep it.
This looks like it fixed the problem where the label "Today" was showing up ~ 1 second later after the sheet was opened.
Before the fix: http://recordit.co/VlMLP1s6H1
After the fix: https://recordit.co/G9UE4g0Sfu
> Fix charts

- src/components/coin-row/SavingsCoinRow.js
- src/screens/SavingsSheet.js
> Fix savings coin row

- src/components/AddFundsInterstitial.js
- src/components/floating-emojis/CopyFloatingEmojis.js
- src/components/header/BackButton.js
- src/components/header/HeaderButton.js
- src/components/profile/ProfileAction.js
- src/components/profile/ProfileMasthead.js
- src/components/qr-code/ShareButton.js
- src/screens/ProfileScreen.js
There are probably more but this takes care of what a brand new user sees for the first time.
- Fixes the height & shape and ripple effect area of the amount buttons
- Fixes the ripple area of the "other amount" button
- Fixes the ripple area of the "copy address" button
- Fixes the ripple area of the profile navbar buttons
- Fixes the ripple area of the profile header buttons
- Fixes the ripple area of the receive modal buttons
Before: http://recordit.co/sDGnLhpEXU
After:  http://recordit.co/qQ0IS7XYG2
> Fix ripple effect area across the app

- patches/@ethersproject+providers+5.0.12.patch
- patches/react-native-keychain+6.2.0.patch
- scripts/postinstall.sh
We were running the `patch-package` command on the postinstall script before `rn-nodeify` meaning that packages were being modified after being patched.  This was preventing the patch to be re-applied a second time since it didn't match with the original source.
To fix this I had to do two things:
- Regenerate affected patches AFTER running rn-nodeify
- Move the patch-package command at the end of the postinstall.sh script
> Patch packages properly

- e2e/ganacheTransactionFlow.spec.js
- e2e/helpers.js
- e2e/importPrivateKeyFlow.spec.js
- e2e/newWalletFlow.spec.js
- e2e/sendSheetFlow.spec.js
- e2e/swapSheetFlow.spec.js
- e2e/watchAddressFlow.spec.js
- package.json
- src/App.js
- src/components/activity-list/ActivityList.js
- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/backup/RestoreSheetFirstStep.js
- src/components/buttons/Button/Button.android.js
- src/components/header/ProfileHeaderButton.js
- src/components/numpad/Numpad.js
- src/config/debug.js
- src/screens/PinAuthenticationScreen.js
- src/screens/WelcomeScreen.js
- Fix e2e being stuck on WelcomeScreen
- Fix missing testID on Android BPAs
- Added missing empty state for activity list
- Handle PIN auth flow
- Update RN Logbox usage
- Fix Restore sheet interactions on e2e
```
PASS  e2e/newWalletFlow.spec.js (70.422 s)
New Wallet flow
✓ should show the welcome screen (71 ms)
✓ go to the wallet screen after pressing "Get a new wallet" button (54916 ms)
✓ should show the "Add funds" button (8 ms)
✓ should show "No transactions yet" in the activity list
PASS  e2e/watchAddressFlow.spec.js (66.915 s)
Watch address flow
✓ Should show the welcome screen (69 ms)
✓ Should show the "Restore Sheet" after tapping on "I already have a wallet" (3554 ms)
✓ show the "Import Sheet" when tapping on "Watch an Ethereum address" (3312 ms)
✓ Should show the "Add wallet …
```
> Android e2e improvements

- ios/Podfile.lock
- package.json
- shim.js
- yarn.lock
Fixes this warning:
After the fix the warning is gone, randomBytes doesn't get shimmed with an insecure source and also confirmed that random byte generation is working correctly for both OS
> Fix random byte generation

- src/components/expanded-state/ChartExpandedState.js
- src/navigation/config.js
- src/react-native-cool-modals/NativeStackView.js
I observe that:
1. If `jumpToLong` will be called then the size of the outer component will be evaluated then whether hasn't been previously.
2. Size of the outer component is evaluated lazily 
3. If `jumpToLong` will be called before mounting of the sheet it will have height `0`
4. Then it won't be visible
5. There's no sense in calling it on the initial mount because the purpose of the `useJumpingForm` there's no need to make it on the first render. 
Furthermore, `TEMPORARY_autoJumpToNewHeight` has been handled already in a different way and should be removed before (probably got restored during some merge)
> Fix sometimes not visible content of sheets

- src/navigation/Routes.android.js
- src/navigation/routesNames.js
this fixes an issue where the addContact modal would navigate back to walletScreen. Probably needs a few tweaks but this follows the pattern on iOS.
@brunobar79  @osdnk lmk if you guys want to pick up or what I should do to make better
> add sendFlowNavigator to android

- src/components/expanded-state/ChartExpandedState.js
- src/navigation/routesNames.js
- src/react-native-cool-modals/ios/UIViewController+slack.swift
@skylarbarrera told me that my previous PR made some regression that ExpandedChartState was not short when there're no charts data. 
So I reverted changes there and made it reliable on the native side i.e. I actively wait until the content render to perform jumping
> Fix not visible content #2

- src/components/change-wallet/AddressRow.js
- src/components/coin-row/SavingsCoinRow.js
- src/components/savings/SavingsListRow.js
- src/components/savings/SavingsListRowEmptyState.js
The nested onPress functions were being triggered multiple times, but we'd like to keep the row-level and button-level interactions.
This was causing an issue on the Change wallet list where editing a wallet would bring up the menu twice.
Also cleaned up some PropTypes.
> Update onPress redundancies

- src/components/coin-icon/CoinIconGroup.js
- src/components/coin-row/CoinRow.js
- src/components/expanded-state/LiquidityPoolExpandedState.js
- src/components/expanded-state/liquidity-pool/LiquidityPoolExpandedStateHeader.js
- src/components/investment-cards/UniswapInvestmentRow.js
- src/components/pools/PoolsListWrapper.js
- src/handlers/localstorage/uniswap.js
- src/handlers/uniswapLiquidity.ts
- src/helpers/utilities.ts
- src/hoc/uniswapLiquidityTokenInfoSelector.js
- src/hooks/useColorForAsset.js
- src/hooks/useImageMetadata.js
- src/redux/data.js
- src/redux/fallbackExplorer.js
- src/redux/uniswapLiquidity.js
- src/screens/SavingsSheet.js
- src/utils/ethereumUtils.js
This PR is to surface both Uniswap V1 and V2 liquidity pool tokens in the investments section.
V2 pools when involving ETH are actually all WETH based - I am showing WETH tokens as ETH when displaying the V2 pool data.
The order of the tokens for V2 are determined by the "sort order" from the Uniswap SDK (which compares contract addresses with each other.) The order of the tokens for V1 are to always have the ETH token be displayed second.
To help simplify the logic for when Zerion or fallback data is used, I parse out the token "type" for Uniswap LP tokens.
> Surface Uniswap V2 LP tokens

- src/components/expanded-state/chart/chart-data-labels/ChartHeaderSubtitle.js
I observed that sometimes chart is jumping up and down in long currency names like "Saint Fame: ICK Mask" that need to be shortened with "...", 
This makes the height fixed.
> Constant height of ChartHeaderSubtitle on Android

- android/app/build.gradle
Builds were getting rejected on the PlayStore because of missing / wrong config. 
After this PR I was able to submit the build with no errors.
> Fix 64 bit arch builds

- src/components/backup/BackupCloudStep.js
- src/components/fields/PasswordField.js
- src/screens/TransactionConfirmationScreen.js
- Fix wc sheet heights on android: https://recordit.co/pH5Zi34Qod
- Fix backup sheet input shadows on Android
before: 
after:
- fix wc cancel button on iOS
Before:
After:
> More fixes

- src/components/coin-divider/CoinDividerOpenButton.js
- src/components/send/SendAssetList.js
This was a side effect of fixing the button's ripple on Send Sheet
Before: https://cloud.skylarbarrera.com/Screenshot_20201120-181630_Rainbow.jpg
After:
- Android: https://cloud.skylarbarrera.com/Screen_Recording_20201120-180834.mp4
- iOS: https://cloud.skylarbarrera.com/Screen-Recording-2020-11-20-18-09-37.mp4
> fix coinDividerOpenButton styling

- src/components/exchange/CurrencySelectModalHeader.js
this back button was meant for android only
ios before/after:
> Restore iOS BackButton in CurrencySelectModal

- src/screens/SendSheet.js
Got pulled into the hole while doing QA, the keyboard area was intermittently staying open after keyboard was closed.
Saw this in the docs: https://cloud.skylarbarrera.com/Screen-Shot-2020-11-23-at-11.15.27-PM.png
I removed flag and it's working very well: https://cloud.skylarbarrera.com/Screen_Recording_20201123-231804.mp4
> remove isOpen flag in sendSheet Keyboard

- package.json
- src/screens/ExchangeModal.js
- yarn.lock
May be a better way to do this than using this package but this is what react-navigation suggests.
Here's the scenario:
If you're in the swap modal & have changed an input/output currency (i.e opened up the currencySelectionList), the physical back button on Android if pressed will take you back to the selectionList. I personally think the expected action is to go back to the WalletScreen. 
I am using the goBack button for detox on android since swiping isnt super reliable.
> add react-native-back-handler

- src/screens/SendSheet.js
There was a white gap under the send button on smaller devices because the KeyboardSizeView only considers the keyboard height of the alphabetic keyboard and ignores the height of the numeric one 🤷‍♂️  
Before the fix:  
After the fix:
> Fix sendsheet keyboard handling in smaller devices

- src/references/chains.json
We were missing the chain info for Goerli testnet, which was causing issues while using dapps via walletconnect.
Fixes #1377
After the fix:
> Fix goerli

- src/navigation/effects.js
We were using different opacity for modal overlays across the app (from 0.5 to 0.7).
I'm changing everything to 0.7
> Standarize overlay opacity

- .eslintrc.json
- e2e/helpers.js
- e2e/init.js
- shim.js
- src/utils/logger.js
This PR turns on the `no-console` eslint rule, so from now it will throw an error.
You can still logs it by importing `logger`
> disable usage of console

- src/components/exchange/ExchangeField.js
- src/components/exchange/ExchangeInput.js
- src/components/exchange/ExchangeInputField.js
- src/components/exchange/ExchangeOutputField.js
Replicate the iOS behavior where the input gets an ellipsis when it overflows without messing with the input cursor.
PoW: http://recordit.co/cdTYWPbxZi
This PR overrides #1399  because messing with the cursor has a lot of unwanted side effects
> Exchange input android mask

- src/navigation/Navigation.js
`navigate` takes care that routes are not duplicated
> Use CommonActions.navigate instead of StackActions.push ih handleAction

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateImage.js
- src/components/savings/AndroidAnimatedNumbers.js
- src/components/savings/SavingsListRowAnimatedNumber.js
2 small tweaks:
- Fix alignment of savings row:
Before: 
After:
- Add margin bottom to unique token image
Before:
After:
> Android paddings

- package.json
- yarn.lock
Version 1.1.7 enables credit/ debit cards. Version 1.1.5 restricts to just debit cards.
> Fixing the react-native-payments fork version to 1.1.5 until credit card support issues become resolved by Wyre

- android/sentry.properties
- ios/Podfile.lock
- ios/Rainbow.xcodeproj/project.pbxproj
- ios/Rainbow/AppDelegate.mm
- ios/sentry.properties
- package.json
- src/App.js
- yarn.lock
This PR does 3 things:
- Updates sentry to the latest version
- Fixes Android sourcemaps. PoW: https://sentry.io/organizations/rainbow-me/issues/2070924181/?project=1855565&query=os.name%3AAndroid+is%3Aunresolved&statsPeriod=24h
- Enables [Releases Health Monitoring](https://docs.sentry.io/platforms/react-native/#release-health)
> Update sentry & fix android source maps

- src/model/wallet.ts
- src/redux/wallets.js
For every new user who creates a wallet, we're incorrectly triggering an error on sentry like this one: https://sentry.io/organizations/rainbow-me/issues/2071346390/events/0b91c074bff74d14ae5f68862bf01bab/?project=1855565&query=release%3Ame.rainbow%401.0%2B5&statsPeriod=24h#threads
The reason is because the first time, the  entry "allWalletsKey" is not set yet, so we create a new wallet and call walletsLoadState again.
I added a short circuit for the firs time so we don't throw that error
> Fix fake error on wallet init

- ios/Podfile.lock
- package.json
- src/handlers/aesEncryption.js
- yarn.lock
- bumps react-native-aes-crypto which fixes cloud backups
- Updates AesEncryptor API to work on both OS
> Fix iCloud Backups

- src/components/send/SendAssetForm.js
- src/helpers/assetTypes.js
- src/hooks/useSavingsAccount.js
- src/redux/data.js
- src/redux/fallbackExplorer.js
We were removing assets with "compound" type as well  as anything with "compound" in the name in order for data from fallback explorer to match up with Zerion data. However, this second removal included the COMP token itself. Now the fallback explorer will parse the "compound" type (which includes cTokens but excludes the COMP itself)
> Update fallback explorer to include compound type

- src/components/buttons/MiniButton.js
before: http://cloud.skylarbarrera.com/Screen_Recording_20201208-202320.mp4
after:
🤖 :  http://cloud.skylarbarrera.com/Screen_Recording_20201208-210005.mp4
🍎 : http://cloud.skylarbarrera.com/Screen-Recording-2020-12-08-22-57-15.mp4
I can refactor to separate out for android but this works on both and parity makes me 😄
> Fix minibutton BPA on android & refactor for parity 

- src/components/savings/SavingsListWrapper.js
- src/helpers/buildWalletSections.js
If tokens are unavailable and the DAI market data (to show the default empty DAI savings state) is unavailable, a crash occurs. This fix is to not show the savings data until at least either the tokens or the empty DAI state (with corresponding rate data) is available.
Can test that the import of this address does not crash the wallet: 0xba2e7fed597fd0e3e70f5130bcdbbfe06bb94fe1 (it is the yYFI token contract, but it should still not crash)
> Handle error if savings info (including Dai market info) unavailable

- src/helpers/buildWalletSections.js
- src/hooks/useSavingsAccount.js
This fixes the red icon issue.
Also, when the "DAI market data" was not available, it was causing an issue where even the existing localstorage data didn't get a chance to be used (causing a long delay for existing users to see their savings tokens).
> Fix hook not loading from backup when subgraph data unavail

- src/screens/WalletScreen.js
added logic to follow empty wallet logic as the AssetList per @christianbaroni
> Disable FAB's

- src/components/activity-list/RecyclerActivityList.js
- src/parsers/transactions.js
There were a couple issues:
1. We were checksumming the asset address without checking if it was the eth address
2. When substituting zerion data with asset data, we were passing along internal assets with "address" instead of "asset_code" which messed up parsing downstream that expected "asset_code"
> Fix ETH icons on activity list

- src/handlers/localstorage/uniswap.js
Due to this localstorage argument error, we were not able to successfully subscribe to charts initially (we would only be able to subscribe once the user opened the chart) which causes a delay in fetching the chart data.
> Fix default value from lp tokens localstorage

- src/apollo/client.js
I think we're not taking advantages of this cache anyway (are we) and it let us release 40MB of 100MB that our app is using
> Remove apollo caching

- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/savings/APYPill.js
- src/components/savings/SavingsListRow.js
- src/handlers/localstorage/accountLocal.js
- src/hooks/useSavingsAccount.js
For a wallet that has no savings, showing the DAI savings deposit row would wait until fresh DAI market data arrived. Now, after the waiting for the DAI market data on the very first time of opening a wallet, any subsequent opening of the wallet will load from localstorage first.
> Save DAI market data to localstorage instead of waiting for fresh DAI rate data every time

- src/components/exchange/ExchangeInputField.js
- src/components/exchange/ExchangeNativeField.js
- src/components/fields/PasswordField.js
Fixes 2 issues:
Back up Inputs, shadowStack issue: 
Before: http://cloud.skylarbarrera.com/Screenshot_20201218-055618_Rainbow.jpg
After: http://cloud.skylarbarrera.com/Screenshot_20201218-074117_Rainbow.jpg
Native Currency Symbol alignment:
Before: http://cloud.skylarbarrera.com/Screenshot_20201218-073705_Rainbow-1-.jpg
After: http://cloud.skylarbarrera.com/Screenshot_20201218-072053_Rainbow-1-.jpg
Exchange Modal Reduce Height for 🤖 :
Before: http://cloud.skylarbarrera.com/Screenshot_20201218-105902.png
After: http://cloud.skylarbarrera.com/Screenshot_20201218-105243.png
>  🤖 ui fixes shadowStack & ExchangeModal

- src/handlers/uniswap.ts
- src/raps/actions/swap.js
- src/raps/actions/unlock.js
- src/raps/swapAndDepositCompound.js
- src/raps/unlockAndSwap.js
- src/utils/contract.js
- Some approvals were failing due to the lack of the account address (owner) being specified
- We were getting a lot of noise in the Sentry logs (and doing many unnecessary gas estimation calls) for swap gas estimations that would fail due to the approval not being available
- Generally improve Sentry logging (the extra data payload was often too large and hitting the size limit, preventing us from getting all the useful information for swap trade routes info)
> Swap and approval gas estimation improvements

- src/components/expanded-state/ChartExpandedState.js
this shortens the ChartExpandedState sheet if you don't have a balance of the asset (fixes RNBW-509)
before → after:
there's probably a cleaner way of doing this but seems to work without issue
also noticed this crash: https://sentry.io/organizations/rainbow-me/issues/2114720348/?project=1855565&query=is%3Aunresolved+level%3Afatal+null&statsPeriod=14d
so added `?.` operators throughout
> Shorten unowned asset sheet, prevent crashes

- src/helpers/buildWalletSections.js
- src/hooks/useSendSavingsAccount.js
- src/hooks/useUniswapCurrencies.js
- src/redux/data.js
- src/redux/explorer.js
- src/redux/gas.js
- src/utils/ethereumUtils.js
In some places, we were relying on the ETH price from the wallet account instead of subscribing to the ETH price separately and explicitly.
Some scenarios that were breaking (can test on 4th wallet of Poopcoin which has other assets but not ETH):
- Savings expanded state broken
- ETH expanded state prices broken
- Gas calculations broken for send/swap
> Handle ETH prices when no ETH in wallet

- src/components/savings/SavingsSheetEmptyState.js
SheetActionButton was missing this prop and was affecting Android 
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-05-15-18-01.65.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-05-15-17-45.78.png
> add fullWidth prop to Deposit - Android

- src/components/coin-icon/CoinIcon.js
Made the address for coin Icon to default fallback to ETH, this solves the issues and is more robust as a fallback, imo.
> default fallback to eth logo

- src/parsers/requests.js
All dapps that don't pass a nonce (most of them) weren't working because it was harcoded to 0 and that nonce has been already used.
PoW with Uniswap: http://recordit.co/BAmoRXvRDL
PoW WC example dapp: http://recordit.co/uEapUjUGfh
> Fix WC nonces

- src/raps/actions/unlock.js
The max uint constant from ethers is now a bignumber and we were storing that object instead of the stringified version in the allowances cache.
During a single session, if an approval and swap was attempted repeatedly, we would fail to recognize the approval value being sufficient. (If a user closes the app and comes back to do a swap, we would refetch the latest approval and then it would proceed to work as expected.)
Also fixed a bug that was not storing the allowances to the cache on the fetch from contract utils.
> Fix incorrect max int format saved after confirmed approval

- src/handlers/uniswap.ts
- src/helpers/utilities.ts
- src/hooks/useUniswapMarketDetails.ts
- src/raps/actions/swap.js
- src/raps/swapAndDepositCompound.js
- src/raps/unlockAndSwap.js
Previously, we were relying on the input / output currencies from the Uniswap SDK Trade object, but this trade object already has the ETH wrapped into WETH, so we cannot distinguish the original intent of the user to swap with or for ETH vs WETH. Now, we use the original input and output currencies selected by the user to determine the swap type.
I tested only with logs for estimation and execution (without actually executing) to see that the following swap types were chosen for these types of swaps:
ETH->DAI : eth for token (was working before)
ETH->WETH: eth for token (was working before)
DAI->ETH: token for eth (was working before)
DAI->WETH: token for token (was NOT working before)
WETH->ETH: token for eth (was NOT working before)
WETH->DAI: token for token (was NOT working before) …
> Use the original currencies to determine swap type for WETH and ETH

- src/model/wallet.ts
- src/raps/common.js
- src/redux/data.js
- src/screens/SpeedUpAndCancelSheet.js
This PR adds the ability to call `executeRap` again  to resume the remaining tasks, which fixes the scenario of speeding up one of the transactions of a rap like : 
- unlock + swap
- unlock + swap + deposit
PoW: http://recordit.co/Vz3xQcrD5u
Fixes RNBW-1009
> Allow to resume raps after speed up

- src/components/inputs/Input.js
- src/redux/explorer.js
It will improve the performance of the discover screen. I'm adding a dictionary of addresses of token that we're already subscribing and therefore there's no need to resubscribe
> Do not repeat subscription for already listened token

- src/components/images/ImgixImage.tsx
- Passed `forwardedRef` of type `React.Ref<any>` to `FastImage`.
- Without this prop fulfilled, `react-native-fast-image` is unable to find the native view node which throws errors when an animated implementation of the `ImgixImage` is mounted or unmounted.
> Prevent view node resolution errors for ImgixImage

- src/screens/TransactionConfirmationScreen.js
Fix the response for wc tx.  This was working before until I pushed #1546  and I forgot to pass the hash instead of the object
Before:  
After:
> Fix WC transaction

- package.json
- src/components/images/ImgixImage.tsx
- Automating the export of `FastImage`'s properties would cause render issues when an alternate render component i.e. `Animated.Image` was used as the render target. 
- This would throw an `unrecognized selector sent to instance...` error on launch of the application when there was not a serialized wallet to navigate to.
This fix manually destructures the required `static` attributes from `FastImage` and assigns these to the `ImgixImage`.
I've also spotted that `lint-staged` was not sensitive to the `.tsx` format, which ensures that `pre-commit` successfully terminates on badly formatted code.
> fix: prevent launch crash associated with overriding ImgixImage render prop

- src/components/discover-sheet/DiscoverSheetContent.js
- src/components/sheet/SlackSheet.js
Closing https://linear.app/rainbow/issue/RNBW-1005/add-top-padding-to-scroll-bar
> Add additionally insets for indicators in DiscoverSheet's ScrollView after mounting

- src/screens/TransactionConfirmationScreen.js
- Increased sheet height for android approvals
- hides divider on android when keyboard is open
Sheet Height
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-22-14-18-23.62.png
bumping approval from 120 -> 140: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-22-14-18-38.45.png
Divider Issue
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-22-14-24-27.21.png
after both fixes: http://cloud.skylarbarrera.com/Screen-Recording-2021-01-22-14-33-33.mp4
> small 🤖  WC tweaks

- src/hooks/index.js
- src/hooks/useSwapInputOutputTokens.ts
- src/hooks/useSwapInputRefs.ts
- src/hooks/useSwapInputs.js
- src/hooks/useSwapInputs.ts
- src/hooks/useUniswapCalls.ts
- src/hooks/useUniswapCurrencies.js
- src/hooks/useUniswapMarketDetails.ts
- src/hooks/useUniswapPairs.ts
- src/redux/gas.js
- src/redux/reducers.js
- src/redux/swap.ts
- src/screens/CurrencySelectModal.js
- src/screens/ExchangeModal.js
In the interest of not having a massive PR with lots of changes, I have created a swap redux and only moved the input and output currencies to the redux.
We will be able to move over pieces of state one by one in this manner.
I also updated some of the hooks to use Typescript.
Testing:
- Confirm that Compound deposit / withdrawals will display the correct input currency as expected
- Confirm that the swap modal interactions (choosing currencies, flipping input and output currencies, etc) all work
> Create initial swap redux with just input and output currencies

- src/hooks/index.js
- src/hooks/useSwapInputValues.ts
- src/hooks/useSwapInputs.ts
- src/hooks/useUniswapMarketDetails.ts
- src/redux/swap.ts
- src/screens/ExchangeModal.js
Moving the swap inputs (input, native input, output values) to redux state.
There will be proper improvements later, but for now I'm trying to make zero breaking changes.
Testing: all inputs (swap input, native input, output input) should work as expected and update each other as expected. Also, the inputs should respond fine on compound deposit / withdraw.
> Move swap input values to redux

- src/components/asset-list/RecyclerAssetList.js
- src/components/asset-list/RecyclerViewTypes.js
- src/components/coin-divider/CoinDivider.js
- src/components/coin-divider/CoinDividerAssetsValue.js
- src/helpers/assets.js
- src/helpers/buildWalletSections.js
- src/references/index.ts
- src/utils/index.js
- src/utils/urlConstants.js
* Fixed getting stuck in the edit button flow
* Simplified the logic for handling pinned, standard, small balance, hidden assets (and fixed some inconsistencies during edit mode)
* Removed the pin / unpin / hide states of the coinEditContextMenu (it is now only used to enter the edit mode if needed, but the regular coin divider edit row shows up) 
Recording with various scenarios:
https://recordit.co/x0lInSUq7a
> Coin edit improvements

- src/components/text/TruncatedText.js
> Fix bottom row text

- src/components/settings-menu/SettingsSection.js
Don't need these props, was causing the switch background to flicker when switching into/out of dark mode
> Fix dark mode switch

- ios/fastlane/Fastfile
Added the env var `SPACESHIP_SKIP_2FA_UPGRADE` to CI so we don't need this for now
> dont use account key

- src/components/exchange/ExchangeAssetList.js
We don't need this imported from RNGH and changing this fixes the issue
> Fix Low Liquidity header in ExchangeAssetList

- src/components/coin-icon/CoinIcon.js
This reverts commit 428d6e33af5486baee0e2afc3d23d8c92b1979ef.
Gonna move fix to coin-icon package
> Revert "fix android square token icons (#1716)"

- src/components/discover-sheet/UniswapPoolsSection.js
- src/hooks/useUniswapPools.js
Look like it's breaking for pools shorter than 30 days (e.g. Interest Bearing ETH - USDC).
and then pools were not displayed at all for me.
So I believe for those pools there is no way to display them on this card. I set `profit30d` to `undefined` and I added logic for filtering them.
> Fix displaying pools shorter than 30 days

- src/handlers/web3.js
- src/helpers/utilities.ts
- src/screens/SendSheet.js
- src/screens/TransactionConfirmationScreen.js
Before sending a tx, attempt to estimate gas and add 10% padding (WC & Send ERC20 / Collectibles)
For WC: If a dapp suggested a price, use whichever is higher.
Note: This doesn't affect the estimate that we show to the user
> Gas padding

- src/apollo/queries.js
- src/handlers/uniswap.ts
- src/hooks/useUniswapAssets.ts
- src/references/uniswap/rainbow-token-list.json
Previously, we were relying on the Uniswap subgraph to return all the tokens, and we would mark them as curated if we found them in the curated list.
Now, we always use the curated list and exclude these from the initial subgraph query for all tokens.
Also added POOL token to the curated list (updated rainbow-token-list package)
PoW: https://recordit.co/1xinos8AFP
Tested: SOCKS, stETH, and POOL all work as expected
> Always use curated list

- src/apollo/queries.js
Previously, when we were fetching all of the tokens with any liquidity, we were calculating the ETH value of the liquidity by multiplying liquidity * derivedETH. 
The orderBy totalLiquidity didn't matter that much since we were getting all the relevant assets and sorting them later.
Now, given the 5k skip limit, we should be a bit more selective about which assets we fetch via the orderBy, and USD trade volume seems to be the most accurate metric out of the fields available.
> Sort subgraph all tokens query by USD trade volume

- src/handlers/uniswap.ts
Previously we were not being precise about the concepts of price impact and slippage.
We should keep the slippage fixed at the same default Uniswap uses (0.5% or 50 bips). In the future, we may include UI to allow users to update the slippage they are comfortable with.
Please note that this is separate from "price impact" which is taken into account in the execution price we provide to the user.
> Keeping slippage fixed at 50 bips

- src/components/discover-sheet/DiscoverSheet.js
Now it looks slightly better (no "Lists" header visible) and on a small iPhone, it's not covering the scanner
> set height of the sheet

- metro.transform.js
Update [`madge`](https://github.com/pahen/madge) options to ensure TypeScript files are processed by the anisotropic transform.
> fix: ensure anisotropic transform sensitive to ts

- src/components/expanded-state/LiquidityPoolExpandedState.js
Closes https://linear.app/rainbow/issue/RNBW-1027/pool-expanded-state-sheet-is-cut-off-if-you-own-the-pool-asset
> Fix height of liquidity pools

- src/components/discover-sheet/DiscoverSearchContainer.js
- src/screens/QRScannerScreen.js
closes https://linear.app/rainbow/issue/RNBW-1028/tapping-search-fab-in-search-mode-should-refocus-search-input
> Fix on press searchFab button action + add jumping to long form

- src/components/discover-sheet/DiscoverSheet.js
Closes https://linear.app/rainbow/issue/RNBW-1023/discover-doesnt-reliably-scroll-to-top-when-entering-search-mode
Basically, animated scrolling can be interrupted by some rerenders. However, here this change does not to be explicitly animated since we are animating things with  `LayoutAnimations` here
> Fix discover doesn't reliably scroll to top when entering search mode

- src/components/discover-sheet/ListsSection.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/exchange/ExchangeAssetList.js
Closes: https://linear.app/rainbow/issue/RNBW-1019/tapping-the-status-bar-to-scroll-to-top-is-broken-everywhere-except-in
> Fix scrolling to top on Discover page

- src/components/exchange/ExchangeDetailsRow.js
- src/components/exchange/PriceImpactWarning.js
- src/components/expanded-state/SwapDetailsState.js
- src/components/expanded-state/swap-details/CurrencyTile.js
- src/components/expanded-state/swap-details/SwapDetailsContent.js
- src/components/expanded-state/swap-details/SwapDetailsMasthead.js
- src/components/expanded-state/swap-details/SwapDetailsSlippageMessage.js
- src/helpers/utilities.ts
- src/hooks/usePriceImpactDetails.ts
- src/hooks/useSwapAdjustedAmounts.ts
- src/screens/ExchangeModal.js
- If price impact is unavailable (because neither the input or output native prices can be found), then adjust the price impact message displayed to use the percentage instead of the native dollar amount lost
- Fix the tilda in the CurrencyTiles to match what is the estimated value (based on input being exact vs output being exact)
- For native price impact calculation, fill in the missing price if we have the other native price
> @jin/price impact native

- src/hooks/useMaxInputBalance.js
- src/hooks/useUpdateAssetOnchainBalance.js
- src/utils/ethereumUtils.js
We treat cTokens a bit differently from regular assets.
The change to ethereumUtils was assuming that any assets with a balance we might be interested in would be in the wallet asset data. However, since cTokens are separate and removed from the regular asset data, and their balances are explicitly set on their token data, we need to keep the balance check on the selected item and use the wallet assets data as a fallback.
PoW: https://recordit.co/8YK9qlJkax
> Fix logic for cTokens with explicit balance outside of wallet assets data

- src/hooks/useRefreshAccountData.js
- src/redux/uniswapLiquidity.js
We were doing two things wrong:
1. On a fresh "assets received", if the pool tokens were empty (e.g, user exits out of all pools / out of their last pool), we were ignoring updates
2. On an "assets removed" scenario, we weren't correctly updating the pools list (now we will filter out pools with 0 balances)
> Fix empty pools still showing

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
- src/hooks/useUniqueToken.ts
We are currently checking multimedia types based on animation_url which is not in the 721 or 1155 spec but rather something that people add to get support via OpenSea(https://docs.opensea.io/docs/metadata-standards). 
There's a few projects that don't do this (Ex. Pillheads) so in this case if there is no animation_url, we check for support using image_url and use that instead.
Before: http://cloud.skylarbarrera.com/Screen-Recording-2021-03-10-17-31-10.mp4 
After: http://cloud.skylarbarrera.com/Screen-Recording-2021-03-10-17-30-39.mp4
> use imageUrl if animation url is null

- src/hooks/useUniswapPools.js
We were trying to calculate 30d profit without checking if the price of eth 30d ago was available, and not recalculating after that. This fixes the bug where the column will show $0.00 for the entire column of the pool sections
> Fix 30d profit race condition

- package.json
- yarn.lock
update `react-coin-icons` to latest version which includes @osdnk's fix for shadows not getting updated https://github.com/mikedemarais/react-coin-icon/pull/12
> bump react-coin-icons dep

- e2e/ganacheTransactionFlow.spec.js
- ios/TransactionListViewCell.swift
We had an instance where ganache was not connected and the test suite sent the funds to our old dev wallet. I spent all morning trying to repro and running the tests locally. There is a situation where ganache fails to start/connect but the toast is still visible, We double check this by trying to send to an ENS domain which will not resolve in this state. Will keep an eye on it if this happens again but everything looks fine.
Code changes are so the tests don't fail due to duplicate testID's from the older transactions.
> update e2e - ganache flow

- src/components/exchange/ExchangeDetailsRow.js
- src/components/exchange/PriceImpactWarning.js
- src/components/expanded-state/SwapDetailsState.js
- src/components/expanded-state/swap-details/CurrencyTile.js
- src/components/expanded-state/swap-details/SwapDetailsContent.js
- src/components/expanded-state/swap-details/SwapDetailsMasthead.js
- src/components/expanded-state/swap-details/SwapDetailsSlippageMessage.js
- src/helpers/utilities.ts
- src/hooks/usePriceImpactDetails.ts
- src/hooks/useSwapDerivedOutputs.ts
- src/screens/ExchangeModal.js
- Calculate price impact based on native values and only display when the price impact is detrimental to the user
- Fixes rounding of derived values in swap
- Fixes flashing green when Price Impact Warning disappears
- If a price is missing for a currency, use a dash instead of $0.00 in the CurrencyTile in Swap details
PoW: https://recordit.co/HTFR9Nbb9a
PoW missing price in CurrencyTile: 
- We can only calculate the native price impact when both input and output currency prices are available. If one or neither are available, then we fallback to using the Unsiwap SDK generated price impact
- The Uniswap SDK generated price impact is precise (for the given trade route and pair reserves) but can give unintuitive results when a trade route uses a very low liquidity pair. For instance, for …
> Swap improvements

- patches/react-native+0.63.3.patch
now it stops breaking in reanimated while refreshing. Additionally, Bottom sheet seems to be a bit more reliable
> Increase reliability of fast refresh

- patches/react-native+0.63.3.patch
Reverts rainbow-me/rainbow#1876
It leaks a lot of memory while doing a fast refresh / reload
> Revert "Increase reliability of fast refresh"

- package.json
- yarn.lock
bumps react-coin-icons dep to 0.1.38 which includes new icons for YFI, NFTX, and RGT
> bump react-coin-icons to 0.1.38

- src/components/asset-list/RecyclerAssetList/index.tsx
- src/components/coin-divider/CoinDivider.js
- src/components/coin-row/BalanceCoinRow.js
- src/handlers/localstorage/accountLocal.js
- src/handlers/localstorage/globalSettings.js
- src/hooks/useOpenSavings.js
- src/hooks/useOpenSmallBalances.js
- src/redux/charts.js
- src/redux/data.js
- src/redux/explorer.js
- src/redux/fallbackExplorer.js
- src/redux/openStateSettings.js
- src/redux/reducers.js
- src/redux/showcaseTokens.js
- src/redux/uniswapLiquidity.js
- src/screens/WalletScreen.js
* Remove chart data from localstorage (and unused loading function from localstorage)
* Prefetch charts for only the top assets (anything that shows above the "All" button)
* Fetch all wallet charts when "All" button selected
* Clean up redux state for open state settings
* Fix the settings for savings open state (previously, it kept Savings closed even if you left it open and killed the app)
PoW: https://recordit.co/aC9ZZ26gdf
> Improvements for fetching charts

- ios/Podfile.lock
- src/components/investment-cards/UniswapPoolListRow.js
- src/hooks/useUniswapPools.js
This make preload LP charts and also shortens the LP list from 40 to 30 to make up for the memory allocated in charts without causing impact.
Also fixes the initial sheet height. We were always animating to the height corresponding to the sheet when the asset is in the wallet, creating an undesired jump for LP that you are not part of.
Now both animations (LP tokens in wallet or not) are smooth. 
PoW: http://recordit.co/RlJNvUQHga
Also updated the pod.lockfile
> Improve LP charts

- src/components/discover-sheet/UniswapPoolsSection.js
https://linear.app/rainbow/issue/RNBW-1019/tapping-the-status-bar-to-scroll-to-top-is-broken-everywhere-except-in
This issue became present again
> Fix scrollsToTop again

- src/redux/uniswapLiquidity.js
My previous updates had handled the LP tokens removal but missed when the last LP is removed, the info also needs to be updated.
> Fix when append or change has removed the last LP token

- src/apollo/client.js
This is what uniswap.info is currently using.
Fixes the issues of 24h volume not showing on some tokens like REP or Staked Ether.
> update uniswap graph url

- src/components/exchange/ConfirmExchangeButton.js
- src/hooks/useSwapDerivedOutputs.ts
- src/hooks/useSwapIsSufficientLiquidity.ts
- src/hooks/useUniswapPairs.ts
- src/screens/ExchangeModal.js
We were flashing Insufficient Funds when switching pairs and fetching the reserve details. Now we show "Fetching Details..." 
Also fixed the flashing of "Insufficient Funds" at the very beginning when selecting your first pair.
Recording:
https://recordit.co/7pYxBe9omW
> Show Fetching Details when reserves still loading

- package.json
- src/raps/common.ts
- src/screens/ExchangeModal.js
- yarn.lock
- Parse errors from ethers.js in rap execution and provide more meaningful alerts on failure (especially for INSUFFICIENT_FUNDS and UNPREDICTABLE_GAS_LIMIT errors)
- Add the error code explicitly in sentry logging because the error details gets cut off
Added some screenshots from "fake error throws" so you can see what it'll look like if it fails. Instead of navigating to the Profile Screen or getting stuck on authorizing, it will now display the alerts below:
> Fix stuck on authorizing bug in swap

- src/screens/ReceiveModal.js
Some user reported this. We were using a non checksummed address everywhere in the receive modal.
> use checksummed address when sharing

- src/components/expanded-state/SupportedCountriesExpandedState.js
updates list of states for card, ACH has different support so we'll need to bake that in when we get there.
source: https://support.sendwyre.com/hc/en-us/articles/360055233754-Geographic-Restrictions-
PoW: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-16-19-31-22.69.png
> update supported states

- src/screens/SettingsModal.js
After we added "Privacy" the version stamp got pushed out of the screen.
This PR increases the height of the modal so it fits again.
> increase settings modal height

- src/components/expanded-state/asset/ChartExpandedState.js
this logic makes more sense to me, may be missing something
before: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-27-16-28-40.27.png
after: http://cloud.skylarbarrera.com/Screen-Shot-2021-05-27-16-28-20.56.png
> fix hidden balance bug

- src/helpers/ScrollPager.js
- src/navigation/Routes.android.js
- src/navigation/Routes.ios.js
- src/screens/ChangeWalletSheet.js
- src/screens/WalletScreen.js
- src/screens/WelcomeScreen.js
the reason why it was crashing is that discover sheet was unmounted. It is not that trivial to fix so I made something else - now we're actually pushing the welcome screen on the top of swipe-navigator. This solves the issue 
Fixes RNBW-1106
> Fix crashes while removing the last wallet

- src/react-native-animated-charts/src/charts/linear/ChartPath.js
Test on DPI chart.
Now charts on the first frame are loaded w/o reanimated. Then I attach reanimated logic
> Fix blinking charts again

- src/screens/SpeedUpAndCancelSheet.js
Previously, users were able to submit the speed up/cancel sheet even before we got the tx info, resulting in fail attempts.
This PR adds a spinner until we get it to prevent that scenario.
PoW: https://recordit.co/uvq7VOL8qc
Fixes: https://sentry.io/organizations/rainbow-me/issues/2415058138/events/1e09622a081a4e009ed53027fa66c97a/?environment=Release&project=1855565&query=is%3Aunresolved&sort=user&statsPeriod=7d
> Fix speed up race condition

- e2e/init.js
This API call is one of the reasons the tests are taking forever. 
With this flag we're disabling synchronization for it, so it should run way faster
> Unblock detox

- src/apollo/queries.js
- src/hooks/useInitializeAccountData.js
- src/hooks/useInitializeWallet.js
- src/redux/usersPositions.ts
Also cleanup misspelling 
When switching wallets, we were fetching ALL of the Uniswap tokens again (many many pages worth of data).
Confirmed with logs that this no longer happens on switching wallets.
Just a note: we need to improve some logic regarding importing first time vs importing when adding new accounts / wallets (these actions will still trigger a refetch of all the Uniswap tokens). I'll make this improvement separately.
> Move fetching of all swap tokens out of account data init

- src/screens/SettingsModal.js
fixes RNBW-1254 : settings modal was overflowing on some smaller phones, now we calculate the height based on the phone's dimensions.
issue was reported on iphone 12 mini, now it is 👌 : https://cloud.skylarbarrera.com/Screen-Shot-2021-06-11-15-58-46.17.png
> tweak settings height

- src/handlers/uniswap.ts
We were adding a padding to the gas limit estimation of 1.1x, and then doing another padding of 1.2x. Removed the second padding as it is redundant.
I came across some improvements we can make on the padding logic, will make a ticket and a separate PR for this.
> Remove redundant gas limit padding

- src/components/exchange/ExchangeField.js
- src/components/exchange/ExchangeInput.js
- src/components/exchange/ExchangeInputField.js
- src/components/fab/ExchangeFab.js
- src/hooks/useMagicAutofocus.js
- src/hooks/useSwapCurrencyHandlers.js
- src/hooks/useSwapInputRefs.ts
- src/screens/ExchangeModal.js
fixes RNBW-1229 : Fixes 🤖 Initial focus on swap sheet 
- changed what makes the input editable and now we pass in ETH as the inputAsset
- there is a slight lag otherwise that causes issues with 🤖
fixes RNBW-1247 : Input/Output currency select focus
- At some point we broke changing the focus if you just selected input/output asset
- pretty sure this is expected behavior and there was a regression, lmk if not
also changes the android mask to only show if there is a value to mask, it was overlapping with the input indicator 
PoW:
iOS:  https://cloud.skylarbarrera.com/Screen-Recording-2021-06-09-18-53-07.mp4
android: https://cloud.skylarbarrera.com/androidfocus.mp4
> swap focus fixes

- src/components/unique-token/UniqueTokenImage.js
Crash caused by substr on null imageUrl when checking if it's a svg.
Example: dame.eth wallet, expanding the state for the Zora family (particularly, the Zora item with just the couch / lamp emojis), it would crash.
Before: https://recordit.co/nuMQrzDVHD
After: https://recordit.co/wCAHLukHcL
> Fix access on potentially null image url

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.js
switches the sharing link to use web profiles
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-06-23-11-32-16.mp4
links work the same as above, i removed the view on rainbow option as it triggers back to app via deep links
> share NFT via Rainbow Profiles

- src/components/expanded-state/LiquidityPoolExpandedState.js
- src/components/investment-cards/UniswapPoolListRow.js
Liquidity pool sheets weren't scrollable and didn't fit the screen on lower end devices with minor screen scales. All of that was fixed following the styles we have on other sheets as `ChartExpandedState`.
I also introduced a change that I wasn't sure why that was there on src/components/investment-cards/UniswapPoolListRow.js the route defined a height that was blocking the UI to be scrollable.
Working https://recordit.co/RMwJgHogFl
Fixes RNBW-1283
> Bugfix: android pools sheet

- ios/fastlane/Fastfile
- src/screens/WalletDiagnosticsSheet.js
- Temporarily remove custom steps from fastlane and fallback into xcode build phases
- Trigger an error from the Wallet Diagnostic sheets to be able to test it.
> soucemaps test

- src/navigation/bottom-sheet/types.d.ts
- src/navigation/bottom-sheet/views/BottomSheetRoute.tsx
On current production I can't scroll down on the send asset lists on my android
https://recordit.co/CugpOG7njH
I was only able to do so using two fingers to scroll.
I changed the `offsetY` on `BottomSheetRoute` for android, and is working now, 3 wasn't enough for android, I tried several offsets and I put there the smoother one IMO.
Fixes RNBW-1302
> bugfix: send scrollable asset list on android

- audit-ci.json
- package.json
- yarn.lock
looks like its effecting the native currency/swap price fetching. It will work slowly sometimes but most of the time not at all.
Ideally we bump socket.io-client but it looks like the same issues occur, hoping you can take a look.
the breaking changes are here: https://github.com/socketio/socket.io-parser/compare/3.3.1...3.3.2
vulnerability is here: https://www.npmjs.com/advisories/1763/versions
For now i am going to revert and add the vulnerability to the audit-ci file so the audit ignores and we have ci up and running
> revert socket-io for now

- src/components/change-wallet/AddressRow.js
- src/components/contacts/ContactAvatar.js
- src/components/contacts/ContactRow.js
- src/components/expanded-state/WalletProfileState.js
- src/components/profile/AvatarCircle.js
- src/components/showcase/ShowcaseHeader.js
- src/components/transaction-list/TransactionList.js
- src/helpers/utilities.ts
- src/hooks/useAccountProfile.js
- src/hooks/useImportingWallet.js
- src/hooks/useInitializeWallet.js
- src/hooks/useWebData.js
- src/model/migrations.js
- src/model/wallet.ts
- src/redux/wallets.js
- src/screens/AvatarBuilder.js
- src/screens/ChangeWalletSheet.js
- src/screens/ImportSeedPhraseSheet.js
- src/styles/colors.js
- src/styles/index.js
- src/utils/abbreviations.js
- src/utils/defaultProfileUtils.ts
- src/utils/index.js
This feature started as just adding deterministic emojis for new wallets but given a few other fixes being adjacent, this PR ends up including:
Add deterministic emojis to new wallets
Add deterministic emoji preview to watched and imported wallets
Make the color options in the emoji picker be all the web profile colors
Make color picker horizontally scrollable
Update web profile data with correct colors on change
Remove avatar preview from a new wallet since we don't have an address yet (Plan is to soon add a replacement "empty" avatar you can tap to choose color/emoji before creating)
Remove ability to tap the preview avatar in the edit/rename wallet modal to toggle background color (wasn't saving anyways)
Fix sporadic problems with wallet names/nicknames during the editing and importing …
> Default wallet emoji

- src/model/migrations.js
Fix in wallet accounts migration to migrate empty (emoji never selected) accounts to their address' default color/emoji combo.
> Migrate emojiless accts to addy's emoji/color

- src/screens/WalletScreen.js
Turn off auto-scrolling to avoid jumping around when tapping the NFT contract families.
> Disable auto-scrolling for AssetList

- src/hooks/useScanner.js
The issue with the QR scanner repeatedly scanning seems to be due to back-to-back navigation calls.  For some reason firing two navigation calls simultaneously does not update the `isFocused` flag in `QRScannerScreen.js` (from the `useIsFocused` hook coming from `@react-navigation`). This kept the QR Code camera open after navigating away from Discover page.
A tiny delay between navigation calls seems to allow the camera to close out.
> QR scanner navigation fix

- package.json
We don't wanna run the token list update script every time we generate an APK. 
We need to do it only when we generate the bundle, which is the artifact we release.
> Fix yarn:android:bundle

- src/model/keychain.ts
Keychain is intermittently failing on the [`getInternetCredentials` function](https://github.com/oblador/react-native-keychain#getinternetcredentialsserver--authenticationprompt-) where we read from secure storage. @brunobar79 mentioned he had similar issues with the `setInternetCredentials` function and solution that fixed it was doing a second request on that specific failure.
> Add a second keychain loadString read attempt

- src/components/asset-list/RecyclerAssetList/index.tsx
- src/helpers/assets.js
Any NFT family with more than 25 token rows (so 50 token cards, each row is 2 token cards) would get chunked to 4 rows, meaning only 8 token cards would get displayed. I've explanded this to chunk all families regardless of size by 50, meaning a max of 100 token cards will be displayed under a family. Assume this is a sensible number to use -- unsure of the downstream performance implications of this change, but it was not noticeable at all in simulator testing. I did see a *lot* of jumping around in the dev wallet with both the tokens and the ENS NFTs expanded.
fixes RNBW-1339
> Fix NFT capping issue

- src/hooks/useAccountProfile.js
This PR brings back the ENS fallback for people without account names who have reverse ENS configured. There was an issue with wallets with emoji but no label falling through this check.
> Simplify account name calculation

- src/hooks/useUniswapPools.js
Issue: `UNISWAP_PAIRS_HISTORICAL_BULK_QUERY` was returning empty data with an error message complaining about the block being passed in as a string instead of a number. Since this query was not returning any data, we were triggering 3 requests for every pair (for a total of 300 requests) to fetch for the missing historical data.
Confirmed via logs that the total additional requests for historical data that need to be done went from 300 down to 2.
QA: Please confirm how performance feels on Android.
> Fix bug that reduces 300 uniswap calls

- src/components/backup/BackupManualStep.js
On current android prod I can't press the button at the bottom of the manually back up screen as described here https://linear.app/rainbow/issue/RNBW-1300/back-up-manually-doesnt-fit-screen now that is visible for android screens adidng a margin to the footer
Fixes RNBW-1300
> bugfix: android backup footer view

- src/helpers/accountInfo.js
This shows the ENS handle if reverse ens is set up and the account has no label. This change got lost somewhere in the L2 branch (prob during rebasing).
> Reorg account name calc

- src/components/backup/BackupManualStep.js
- src/components/secret-display/SecretDisplaySection.js
Fix issues with privkey backup sheet overflowing on different devices. Fixes RNBW-1397.
Before: 
After:
iphone 12
iphone 8
> Fix layout on seed backup sheets

- src/redux/data.js
We were not resetting the generic assets handler so it keep polling forever and a new instance was created every time we switched accounts
> reset generic assets handle

- src/components/video/SimpleVideo.tsx
React 17 changed the `useEffect` cleanup function timing breaking the video unmount cleanup (https://reactjs.org/blog/2020/08/10/react-v17-rc.html#effect-cleanup-timing). Switch to `useLayoutEffect` instead. Fixes RNBW-1336.
> Fix video audio not stopping on unmount

- src/hooks/useUserAccounts.js
We were showing 0 eth for all wallets because we weren't passing the balances
> Fix sendsheet wallet balance

- src/components/asset-list/RecyclerAssetList/index.tsx
we were only checking if we need header if isCoinListEdited === true, so it would remain indefinitely after switching it off
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-09-00-45-30.mp4
> fix super sticky edit menu

- src/screens/ExchangeModal.js
we were calculating with the input amount which sometimes isnt readily available, now we use the output price which makes more sense IMO
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2021-07-27-15-10-53.mp4
> fix gas > value warning

- src/screens/ExchangeModal.js
During the L2 changes I've introduced a race condition where the fees are calculated before having the gas prices, which results in the "loading..." state.  I've fixed it for the send flow but I forgot to do it on the exchange modal.
PoW: https://recordit.co/rwE0tDOxvx
> Fix exchange modal gas estimations

- src/helpers/dappNameHandler.js
We were pulling an asset that doesnt exist, now we use the image they pass via WC.
PoW: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-05-10-12-22.88.png
> fix sushi dapp data

- src/redux/walletconnect.js
- src/screens/WalletConnectApprovalSheet.js
On `session_request` we weren't used the connection chainId, so every connection happening was showing Mainnet as network.
https://recordit.co/8u33kLgvRi
> WC use connection request chain id

- src/screens/SendSheet.js
Gas estimation was failing on send because we were missing one parameter.
> Add missing param

- src/components/coin-icon/CoinIcon.js
we we're not using the mainnet address to resolve icons, now we do 
before: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-12-15-59-12.93.png
after:  https://cloud.skylarbarrera.com/Screen-Shot-2021-08-12-16-00-05.75.png
> fix l2 icons 

- src/redux/walletconnect.js
- src/screens/WalletConnectApprovalSheet.js
If you dismiss the WC connect sheet while it's still loading, the connection failed sheet will show up 30 seconds later because we were not clearing the timeout
> Clear timeout when connect sheet is dismissed

- ios/Rainbow/Info.plist
- src/hooks/useScanner.js
Adding:
wc
URIs formatted as `rainbow.me/wc:...` weren't handling wallet connect deeplinks, instead were going to watch address section of the app, so added that support with the intent of using it from rainbow button an be able to scan the QR code from camera and be sent to the app instead of other apps supporting the `wc` url scheme
> add iOS bundle url schemes

- src/screens/TransactionConfirmationScreen.js
For some reason we weren't getting the native asset when we get a message signature request making the app look like this
(check the balance section)
now is back to
> Fix native asset on tx screen

- src/components/discover-sheet/DiscoverSheetContent.js
Everything works as before and the whole DiscoverSearch component is not rendered all the time anymore.
https://user-images.githubusercontent.com/1247834/129768080-361c9982-605b-4ff0-bd9b-3f9507b32094.MP4
> Prevent discover search permanent rendering

- src/components/contacts/ImageAvatar.js
- src/screens/SendConfirmationSheet.js
When passing an address to the Send Sheet confirmation, pull info from current wallets before defaulting to hashed defaults. Fixes RNBW-1457.
> @nico/sync send sheet contact info with wallet

- src/redux/walletconnect.js
Since we don't really accept adding new chains, this is just an alias for `wallet_addEthereumChain`
https://ethereum-magicians.org/t/eip-3326-wallet-switchethereumchain/5471
> Add support for wallet_switchEthereumChain

- src/screens/SendConfirmationSheet.js
We were resetting the "isAuthorizing" flag on failure AND success, so you could technically submit the same transaction twice if you tapped again before the sheet was dismissed.
Now we're only resetting on failure.
Fixes RNBW-1432
Fixes RNBW-1473
> Prevent double auth on send flow

- ios/DiscoverSheet/SlackBottomSheet.h
- ios/DiscoverSheet/SlackBottomSheet.m
- ios/DiscoverSheet/UIViewController+PanModalPresenter.swift
- ios/TransactionListView.swift
- src/react-native-cool-modals/ios/RNCMScreenStack.m
This commit should be conceptually no-op.
What do I do?
- clean-up. I got rid of many selectors (value for key) in favor of regular properties access. This should be better in type safety and probably allow for some performance enhancements. 
- Get rid of `object_setClass`. This is most likely the most reason for `NSInternalInconsistencyException` crashes. 
Currently, we use `object_setClass` for setting a new class for `UITransitionView`. This class is not public in UIKit. so `PossiblyTouchesPassableUIView` is not inheriting from `UITransitionView` and that is why we have this error. In order to fix this, I was initially trying to remove this change quickly in runtime but looks like this was not sufficient.
In this PR I decided to use a bit different approach. Instead of using …
> Get rid of object_setClass in DS

- src/components/discover-sheet/PulseIndexSection.js
- src/hooks/useUniswapPools.js
We are currently disabling DPI and pools info if we dont have chart info. We can still show both without. This also fixes CI if we arnt getting charts info 👼
DPI: shows without chart like the rest of the expanded states
Pools: we already had logic in place to handle removing the 30d movers section so we dont need to skip the query
before: https://cloud.skylarbarrera.com/Screen-Shot-2021-08-31-22-40-45.31.png
after: https://cloud.skylarbarrera.com/Screen-Recording-2021-08-31-23-34-47.mp4
> handle discover no charts scenario 

- src/App.js
- src/redux/walletconnect.js
this PR attempts to improve the interaction of wallet connect requests with the app by only recreating the WC `connectors` that are disconnected on `appStateChange` rather than recreating all connectors every time going from `background` to `active`
1 .requests lost going to the app, signing sheets not being displayed
2. requests lost on the app going to background (last part on before video)
3. dapps not reacting to signing interactions of the user on rainbow (sec 12 on before video)
videos on linear
https://linear.app/rainbow/issue/RNBW-1562/improve-requests-handlingresponse-time
Fixes RNBW-1562
> improve wc requests

- src/components/expanded-state/asset/ChartExpandedState.js
- src/hooks/useAsset.js
- src/hooks/useUniswapAssetsInWallet.js
- src/screens/CurrencySelectModal.js
@jinchung noticed we were calling `includes` on the all assets list every time this hook was being called. 
doing that, `uniswapAssetsInWallet` was being returned in 100 ms, now is 0 - 1 ms
as we are calling that in many places, and more importantly being called a lot while the assets are being loaded (around 40 times) this should improve overall performance of the app
@jinchung  🐐
> useUniswapAssetsInWallet performance improvement

- src/apollo/queries.js
- src/hooks/usePoolDetails.js
- src/hooks/useUniswapPools.js
- src/redux/additionalAssetsData.ts
It looks like there were multiple places where we were using `get2DayPercentChange` but didn't actually need the entire function calculated.
For testing: confirming that nothing breaks for pools related data (expanded state, Discover, etc)
> Removing unused calculations for pools related hooks

- src/navigation/bottom-sheet/views/BottomSheetRoute.tsx
- src/rainbow-fetch/index.js
Looks like while updating the BS library I ignored the fact, that 0 is no longer a valid snap point. Now, we use `enablePanDownToClose` prop instead and this is marked internally as the "-1" point. 
This PR fixes this and refactors consequently indices logic.
> Fix bottom sheet usage

- src/helpers/buildWalletSections.js
I was able to repro this on latest develop
https://github.com/rainbow-me/rainbow/compare/@esteban/fix-wallet-section?expand=1#diff-c4a5980e4dbe37999dd9bbabbf92f69e7d2a05fbf3b667f45abf662402858f44R120 is undefined on `asset` 
for ex.
``` 
{"cToken": {"address": "0x5d3a536e4d6dbd6114cc1ead35777bab948e3643", "decimals": 8, "name": "Compound DAI", "symbol": "cDAI"}, "exchangeRate": "0.021539942964407968", "supplyRate": "0.0236141697234528", "underlying": {"address": "0x6b175474e89094c44da98b954eedeac495271d0f", "decimals": 18, "name": "Dai", "symbol": "DAI"}}
```
making https://github.com/rainbow-me/rainbow/compare/@esteban/fix-wallet-section?expand=1#diff-c4a5980e4dbe37999dd9bbabbf92f69e7d2a05fbf3b667f45abf662402858f44R213 resolve to NaN
> fix NaN balances

- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/entities/nativeCurrencyTypes.ts
- src/handlers/localstorage/globalSettings.js
- src/helpers/nativeCurrencyTypes.ts
- src/redux/settings.js
This is a short PR to create a TypeScript module for typing currency keys, such as "USD," instead of typing out the strings directly. #2498 can then be updated to use this type.
Since the currencies are sourced from a JSON file, I couldn't find an easy way to generate a proper TypeScript `enum`. The options (I think) are therefore to define a type using the keys from that JSON (but still use literal strings) or generate an object that behaves like an enum. 
This works by creating an object with each key mapped to itself, and then using `NativeCurrencyKeys.USD` or similar instead of using a "USD" literal.
> Create `nativeCurrencyTypes` TS module for native currency keys like "USD."

- src/redux/polygonExplorer.js
We are currently blowing up when covalent doesn't have the contract name for a polygon token so no polygon assets are displayed in the wallet. 
One example of such a token is https://polygonscan.com/token/0x4259Abc22981480D81075b0E8C4Bb0b142be8EF8?a=0x3B3525F60eeea4a1eF554df5425912c2a532875D
```
{"balance": "999000000000000000000000000",
"balance_24h": "999000000000000000000000000",
"contract_address": "0x4259abc22981480d81075b0e8c4bb0b142be8ef8",
"contract_decimals": 0,
"contract_name": null,
"contract_ticker_symbol": null,
"last_transferred_at": "2021-11-01T15:22:59Z",
"logo_url": "https://logos.covalenthq.com/tokens/137/0x4259abc22981480d81075b0e8c4bb0b142be8ef8.png",
"nft_data": null,
"quote": 0,
"quote_24h": null,
"quote_rate": null,
"quote_rate_24h": null,
"supports_erc": ["erc20"], …
```
> RNBW-1830: Don't blow up on polygon assets that don't have a contract name in covalent

- src/handlers/web3.js
- src/utils/ethereumUtils.js
Since we are using node providers (Infura/Alchemy) with separate endpoints for various networks and not switching networks on a single provider, we can use the StaticJsonRpcProvider and avoid the additional eth_chainId call that is used for safety.
This has been verified that the eth_chainId call is not being triggered using logs.
Context: eth_chainId is called with every call we do to Infura. By specifying a network, we can remove this eth_chainId call from happening. Previously these calls took up about half of our total Infura network requests load.
> Use StaticJsonRpcProvider

- hardhat.config.js
Without this change all hardhat txs are rejected with the error:
`  Trying to send an incompatible EIP-155 transaction, signed for another chain.`
because we're signing txs for mainnet but hardhat's default chainId it's different.  This was previously working when I did #2510  because the provider was set to `any`
> Fix hardhat config

- e2e/discoverSheetFlow.spec.js
When zerion is down this test breaks because this section disappears so we can test it only if it's there
> e2e top movers optional test

- src/redux/fallbackExplorer.js
- src/redux/optimismExplorer.js
- src/redux/polygonExplorer.js
- src/references/index.ts
Optimism:
PoW: https://recordit.co/CyeyGd4mEY
After the initial loading of Optimism data, we were doing superficial copies of the asset data in a global const - causing the underlying values to be overwritten and then failing to detect a "change" (thereby skipping to write the new data to redux)
**Testing checklist:**
Send an asset on Optimism. The balance should update after 10 seconds of the txn confirming.
Loading and sending assets on polygon should still work.
> Improvements to L2 explorers

- src/entities/transactions/transaction.ts
txTo is required but not being used everywhere, ex: https://github.com/rainbow-me/rainbow/blob/0c28ee21dacabda78023bfb9af64bb5ad500469c/src/parsers/transactions.ts#L413
seems chill due to this comment: https://github.com/rainbow-me/rainbow/pull/2586#discussion_r756569460
> lint - optional txTo

- src/screens/SendSheet.js
the useEffect was re-running with null recipient so it was "wiping" the `toAddress` [here](https://github.com/rainbow-me/rainbow/compare/@bruno/fix-sendsheet-params?expand=1#diff-b39e437ce6cbc2452da927c2ecd100de213cd594ec3fd802347c44d512043346R427)
Also added a check to prevent this from happening before submitting the transaction which shows an alert like this along with some tracking for sentry:
To test:
- Go to https://www.the-qrcode-generator.com/ , choose "free text" and enter in the text field to generate a qr code`ethereum:0x3Cb462CDC5F809aeD0558FBEe151eD5dC3D3f608?value=000002250000000000`
then submit the transaction and it should show as a normal send on etherscan (not a contract deployment)
- Same but entering the following text to generate another QR code: …
> Fix hook issue and prevent tx without to

- src/components/expanded-state/UniqueTokenExpandedState.js
iOS was copying the url twice, now we only add to message on android.  fixes RNBW-1889
PoW iOS: https://cloud.skylarbarrera.com/Screen-Recording-2021-11-28-16-44-42.mp4
PoW 🤖 : https://cloud.skylarbarrera.com/Screen-Recording-2021-11-28-16-43-26.mp4
> only add the url to message on android

- e2e/deeplinks.spec.js
because covalent usually takes longer this tests are very flaky, so we're disabling it for now and will re-evaluate once l2 data  is coming from the backend.
> disable l2 deeplink e2e

- src/components/expanded-state/custom-gas/FeesPanel.js
Custom base fee and custom priority fee should always be updated together.
Instead of doing two separate setStates, we can consolidate into a single state object.
This helps prevent future changes from missing the fact that these need to be coupled and reduces rerenders.
PoW screen recording shows nothing has changed.
Will update once it uploads.
> Consolidate custom base fee and priority fee into a single state object.

- src/redux/gas.ts
Fixes RNBW-1949
Meteorology updates every 10 seconds, our client will update every 5 seconds. Previously, we were updating every 15 seconds.
PoW: https://recordit.co/RxikOGZd0c
The longer gaps can take around 15 seconds depending on timing
> Decrease interval for meteorology gas data

- src/components/gas/GasSpeedButton.js
Fixes RNBW-1945
This will now ensure that the `gasIsNotReady` flag is not set until the `price` is also ready
It was disjoint because `gasIsNotReady` is influenced by the existence of `selectedGasFee?.gasFee` while the `price` is influenced by `selectedGasFee?.gasFee?.estimatedFee` and there was a split second where the `estimatedFee` was missing, causing `gasIsNotReady` to be out of sync for a moment.
We should figure out why the `estimatedFee` was missing on the `selectedGasFee` object, but that can be addressed separately. 
PoW: https://recordit.co/GKUBRO2Prz
I have a screen recording of the custom menu gas speed button also behaving correctly, but it won't upload for some reason.
> Ensure gas readiness to be determined by price being available also

- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/entities/index.ts
- src/handlers/localstorage/globalSettings.js
- src/redux/settings.js
This is a small fix to the exports and imports of the `NativeCurrencyKeys` type to make it fall more in line with how other types are exported from `entities`. Other entities are exported from `src/entities/index` and subsequently imported from `@rainbow-me/entities` instead of referencing their specific file.
> Fix `NativeCurrencyKeys` to follow export pattern.

- e2e/hardhatTransactionFlow.spec.js
- package.json
- src/model/wallet.ts
- yarn.lock
There was a breaking change on Ethers 5.5.0 ([source](https://github.com/ethers-io/ethers.js/issues/1544#issuecomment-947237697)) affecting `eth_sign`. This PR fixes it
PoW: http://recordit.co/TXct78bmbi
Included a new e2e covering this so it's safe to merge
For QA in release regression:
* Please test critical path testing for message signing (various dapps etc)
> Fix eth_sign

- src/App.js
First try at 2 seconds
Second try at 5 seconds or 10 seconds if L2.
QA Instructions:
- After sending a transaction on mainnet balance should be updated in < 6 seconds (ideally in less than 3)
- After sending an l2 tx balances should be updated in less than 11 seconds (ideally in less than 3)
Fixes RNBW-1913
> Sync balances after tx sooner

- src/redux/explorer.js
- src/screens/SendSheet.js
These are in direct response to the comments I posted on the `@bruno/l2-backend` branch
Commit history can be read exactly in order - all commits are logically separate.
Here is a screenshot of the mainnet assets not being duplicated:
Here is a video of the SendSheet review button working:
https://user-images.githubusercontent.com/1285228/144736009-7a078a62-df86-4eaf-a655-833a27e09286.MP4
> Fixes for comments on L2 backend update

- src/redux/gas.ts
- src/screens/SendSheet.js
- src/screens/TransactionConfirmationScreen.js
Fixes RNBW-1966
Missed the change of l1Optimism gas fee, probably when rebasing. Now I'm passing `l1GasFeeOptimism` correctly to be added to the fee,
https://recordit.co/81or1niHbT
qa later?
> fix optimism fee

- src/parsers/gas.ts
Fixes RNBW-1974
Fix it taking the minimum between the max fee per gas and the current fee per gas to do this calculation
https://recordit.co/LWYEG3a6cy
Move the max fee to below the current base fee, the estimated fee should be the same to the max transaction fee. If the max base fee is above the current base fee, max transaction fee should be greater than the estimated fee
> fix estimated fee calculation when max fee is set below of current base fee

- package.json
- yarn.lock
Fixes the following `yarn audit` warning:
```
{
"resolution": {
"id": 1006764,
"path": "next",
"dev": false,
"optional": false,
"bundled": false
},
"advisory": {
"findings": [
{
"version": "12.0.1",
"paths": [
"next"
]
}
],
"metadata": null,
"vulnerable_versions": ">=12.0.0 <12.0.5",
"module_name": "next",
"severity": "high",
"github_advisory_id": "GHSA-25mp-g6fv-mqxx",
"cves": [
"CVE-2021-43803"
],
"access": "public",
"patched_versions": ">=12.0.5",
"updated": "2021-12-06T19:19:15.000Z",
"recommendation": "Upgrade to version 12.0.5 or later",
"cwe": "CWE-20",
"found_by": null,
"deleted": null,
"id": 1006764,
"references": "- https://github.com/vercel/next.js/security/advisories/GHSA-25mp-g6fv-mqxx\n- https://github.com/vercel/next.js/pull/32080\n- …
```
> Upgrade Next to fix dependency audit warning

- src/components/gas/GasSpeedButton.js
- src/handlers/web3.ts
- src/parsers/gas.ts
- src/parsers/index.ts
- src/redux/gas.ts
- src/screens/SpeedUpAndCancelSheet.js
- src/utils/gas.ts
Fixes RNBW-1984
Fixes RNBW-1985
- Specific network gas polling times
- Arbitrum and optimism default to NORMAL speed. In order to do this I had to update `parseL2GasPrices` since I was using the average price before.
- Changed `parseGasPricesEtherscan` to `parseL2GasPrices` just to be clear we don't user etherscan
- removed parse eth gas station
- 
> l2s default speeds and polling times

- src/components/expanded-state/custom-gas/FeesPanel.js
- src/parsers/gas.ts
- src/parsers/index.ts
- src/redux/gas.ts
- src/references/index.ts
Fixes RNBW-1989
We have fallback default gas prices in case we could not get updated gas prices from the network for L2s. This doesn't really make sense for our L2s.
Will add
Will add
> Remove hardcoded fallback gas prices for L2 networks

- src/redux/fallbackExplorer.js
- src/redux/optimismExplorer.js
Fixes RNBW-1980  ( randomly showing ETH balance = 0 )
- Use covalent assets over mainnet assets (which have no balance / price)
- Prevent assets state updates when balance is missing on mainnet
- Prevent assets state updates when balance is missing on optimism
Before: https://recordit.co/XvyI9hL2p3
After: http://recordit.co/UR6W9YiBqH
- Pull to refresh / assets updating after sending txs
- set forceFallbackProvider = true and confirm asset balances work fine.
> Fix balance update logic and fallbacks

- src/components/sheet/SlackSheet.js
Fixes RNBW-1995
this change was introduced here and doesn't seem to be used anywhere in the PR: https://github.com/rainbow-me/rainbow/pull/2616/files#diff-bf30c99888c562b993ab5dcbc65a70f1166d6902e33cbb675891796da592380aR157
before: 
after: https://cloud.skylarbarrera.com/Screenshot_20211208-161223.png
[x ] Added labels?
> remove borderRadius prop

- src/redux/gas.ts
Since we're now updating gas fees on each new prices information we get to the app, according to each networks polling, for optimism we need to consolidate the optimism fee and the L1 fees that right now are in different parts of the app, we get optimism fee from redux and the L1 fee from the transaction confirmation and send screens. Because of this I added the `l1GasFeeOptimism` to redux, so now we can calculate the complete fee in one place, and if `l1GasFeeOptimism` is not defined yet (because it comes from other component and takes a bit of time) we don't show any fee at all.
I started to clean the code and ended up in a refactor that I wouldn't want to merge so close to a release.
> fix optimism gasprices updates

- src/redux/gas.ts
- src/screens/SendSheet.js
Removing the `gasFeeParamsBySpeed` dep in useEffect which was triggering the gas limit estimation on new params, it was already there before EIP1559 https://github.com/rainbow-me/rainbow/blob/0f845d0bfffb6e9087289c26c101b2cd7bc154ec/src/screens/SendSheet.js#L781 but we don't need it anymore since we're checking for empty params inside the redux action https://github.com/rainbow-me/rainbow/blob/develop/src/redux/gas.ts#L585
now the gas limit estimation doesn't depend on new gas price data https://recordit.co/yFFfMC5kap
- gas prices still updating
> Remove unnecessary updateTxFee calls in SendSheet

- src/hooks/useUpdateAssetOnchainBalance.js
If the onchain balance fetch fails or throws an error, the balance returned is null, and could slip through this check before updating the balance (resulting in NaN in some places)
Will add
This is just a safety check no op for instances when the on chain balance checker fails on us.
While we were having this arbitrum token mapping issue, when switching to "Arbitrum Eth" in send flow, gas price in the gas speed button would remain $NaN.
> Fix: do not update balance if onchain fetch fails

- src/components/gas/GasSpeedButton.js
- src/redux/gas.ts
Fixes RNBW-1964
- https://github.com/rainbow-me/rainbow/pull/2660/files#diff-502b6a00522262b6f90cd051382ce813bebb752984a8741b66534da07f9f9168R424 passing the wrong object
- checking isNaN does the trick now on gasSpeedButton `formatGasPrice`
> fix gas fee txFee updates

- src/components/change-wallet/WalletList.js
Talked with christian and this is more annoying than useful 
removed the autoscroll to the current wallet
https://cloud.skylarbarrera.com/Screen-Recording-2021-12-10-10-35-43.mp4
should not autoscroll anymore 
> rm wallet list autoscroll

- src/components/transaction-list/TransactionList.js
Fixes RNBW-2016
our default case was to open the block explorer which is no good, we want to close the sheet for this case and only open the block explorer when its pressed
https://cloud.skylarbarrera.com/Screen-Recording-2021-12-10-12-45-57.mp4
menu items for tx list should work as expected
> fix android tx list menu

- src/redux/gas.ts
clearTimeout to avoid having two threads running at the same time. Try to repro going to the send screen and changing the asset between networks many times, at some point the prices start to act strange.
> add `clearTimeout` to gasPricesHandle in redux gas

- src/screens/TransactionConfirmationScreen.js
Fixes RNBW-1983
we now wait until we have set the network before checking the native balance for the request. 
before: https://cloud.skylarbarrera.com/Screen-Shot-2021-12-12-17-40-06.85.png
after: https://cloud.skylarbarrera.com/Screen-Recording-2021-12-12-22-49-08.mp4
> WC - delay checking native asset balance

- src/components/gas/GasSpeedButton.js
Fixes RNBW-2025
The time amount is now waiting for the animated number to render the price. Seems to be a delay inside the animation itself so I couldn't use `gasIsNotReady`
https://recordit.co/riK4AhzAdV
> gas speed button: load time and price at same time

- src/components/expanded-state/custom-gas/FeesPanel.js
- src/components/expanded-state/custom-gas/GweiInputPill.js
- src/components/gas/GasSpeedButton.js
- src/hooks/useFeesPanelInputRefs.ts
- Now if user puts a `.` or `,` it will be changed to `0.` or `0,` as we do in the exchange modal
- there's no need to update gas on custom
- - add a delay for focus to an input and don't focus to max base fee by default because `useFeesPanelInputRefs`  is a;lready doing it
- Fixes RNBW-2026 https://recordit.co/5dDbQitQcB
https://recordit.co/ZnXHfpxOEd
> @esteban/input polish from release

- src/components/expanded-state/CustomGasState.js
- src/components/gas/GasSpeedButton.js
Taking the first of the available speeds by default, this was causing to show NORMAL instead of urgent in speed ups and cancels
https://recordit.co/9UVBwwdCFQ
ignore the pending swaps, i did a bunch on hardhat and they're still there
> gas speed button: take the first speed or normal by default and height on smaller devices

- src/components/coin-icon/CoinIconFallback.js
- src/components/images/ImageWithCachedMetadata.js
Fixes https://rainbowhaus.slack.com/archives/CU889KPME/p1639550798277100
use local eth asset. 
I modified slightly `ImageWithCachedMetadata` to allow for rendering local images.
Open wallet on android 
> Fix eth icon on android after removing ReactCoinIcon

- src/hooks/useCurrentNonce.ts
- src/screens/TransactionConfirmationScreen.js
This is a tidy up PR to rename `network` to `currentNetwork` in the `TransactionConfirmationScreen`. This is for clarity as `network` is often used to describe the general app-wide `network` (such as mainnet or testnets), while `currentNetwork` is transaction specific and can support L2s.
Also updated `useCurrentNonce` to return `undefined` when the `currentNetwork` is not passed, as can be the case initially when the `currentNetwork` has not been set.
> @jin/tidy up

- src/helpers/buildWalletSections.js
- src/hooks/useInitializeAccountData.js
- src/screens/WalletScreen.js
In `buildWalletSections` we have two exports - one is the brief selector and the other is the original selector.
The brief selectors were mostly separate from the “old” selectors - except for one place, where a “brief” selector was still using an “old” selector
The commit history is clean - you can step through each commit, and it will be logically separate.
Other changes:
- moved the updating of pool positions to the "init account data" hook
- removed the passing along of "sections" data to the WalletScreen's asset list (as this is now using RAL2)
> Link brief small balances to the brief balances selector

- src/hooks/useAsset.js
The `useAsset` hook first checks if assets are in `useUniswapAssetsInWallet` which is a subset of assets in `allAssets` so we don't need to do this.
> Remove useUniswapAssetsInWallet check in useAsset hook

- e2e/importPrivateKeyFlow.spec.js
- e2e/importPrivateKeyFlow0x.spec.js
- src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
The `title` used to not be sent for the regular use of `AssetListHeader`.
With the asset list changes, we've started sending it as "Balances" but that caused the wallet selector to not appear.
Code of interest: https://github.com/rainbow-me/rainbow/blob/develop/src/components/asset-list/AssetListHeader.js#L134
The only place that was using the "Balances" title was the EmptyAssetList (and it still is) as can be seen here: https://github.com/rainbow-me/rainbow/blob/develop/src/components/asset-list/AssetList.js#L32
Before:
After:
Confirm that the wallet screen shows the drop down wallet selector
> Remove default balance title that was hiding wallet selector

- src/components/coin-row/BalanceCoinRow.js
- src/components/expanded-state/asset/ChartExpandedState.js
- src/hooks/charts/useChartData.js
Update BalanceCoinRow to use the assetUniqueIdentifier that it used to use as part of its equality check.
The old BalanceCoinRow used to have additional checks for pinned and hidden items - this is now part of the hook itself instead of props so will still update if the underlying data updates.
Also: remove `useAsset` call in `useChartData` hook. This reduces the number of calls to `useAsset` when opening up the ChartExpandedState.
> Memo for BalanceCoinRow

- src/components/coin-icon/CoinIconFallback.js
- src/components/expanded-state/UniqueTokenExpandedState.js
- src/navigation/Routes.android.js
- src/redux/data.js
Adjusted back up sheet timer ~ android loads/imports a lot slower than ios so the sheet was popping up way too soon
fix eth logo ~ added sizing ~ we need to add dimensions since we're using a larger image
improved the code regarding showing eth or usd for NFT priced
tweaked the height of the showcase sheet to better match ios
> smol android fixes

- src/hooks/useCoinListEditOptions.ts
Fixes RNBW-2061
Due to my mistake and the fact the mmkv library is catching errors, I didn't figure out that this is possible that the previous value of the state can be undefined what was causing an exception. Effectively, the pinned coins were not updating. 
Open a wallet, try to pin coins
> Fix pinning mode

- src/components/Tag.js
Fixes https://sentry.io/organizations/rainbow-me/discover/rainbow-wallet:7617bfdc4ee045c5973f422bc1f57bf7/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=device.name%3AGoro&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29
- css property `flex` only accepts numbers in react native. 
The app now doesn't crash in the wallet screen 
http://recordit.co/EOEPJowWhp
> Fix crash on android release apk

- src/components/coin-divider/CoinDivider.js
- src/components/coin-divider/CoinDividerOpenButton.js
- src/components/coin-row/CoinName.js
- src/components/discover-sheet/UniswapPoolsSection.js
- src/components/expanded-state/asset/ChartExpandedState.js
- src/components/send/SendAssetList.js
Fixes RNBW-2082
We are getting rid of all usages of reanimated v1. We find this an issue of the slowness of the Android app. 
The component is rewritten, waits for Christian polishes.
Doesn't block code review
Please observe the small `All / Less` in the main assets list + send sheet.
> Rewrite CoinDividerOpenButton to reanimated v2

- src/components/list/ListHeader.js
Fixes RNBW-2089
Disabled sticky header dividers on android + darkmode bc it was showing as a white border.
Before:
After:
Sticky headers shouldn't have any white border when in dark mode (android)
> @bruno/fix darkmode sticky headers android

- src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
Fixes RNBW-2080
"Collectibles" header no longer appears if the wallet doesn't have any NFTs
https://user-images.githubusercontent.com/15272675/146858402-a98dbbd1-91c7-4d02-8c1c-971569c5dd7b.mp4
> remove 'collectibles' header when wallet does not possess nfts

- src/components/expanded-state/UniqueTokenExpandedState.js
Fixes RNBW-2068
Example of problem: https://drive.google.com/file/d/15fXEwrXsOOGaTi_7eoRdG67gY77NAiQv/view
I disabled the nft expanded state BlurWrapper for android since it was causing a weird overlay issue as seen in this linear ticket, and because it isn't working on android anyways. The remaining nft expanded slack sheet is translucent, so I configured it to be opaque on android to compensate for the missing blur wrapper.
iPhone 13 Pro Max
https://user-images.githubusercontent.com/15272675/146632831-630010fe-6d99-49b6-8dd5-76d52e9f2694.mp4
Samsung Galaxy A52
https://user-images.githubusercontent.com/15272675/146632840-fcfdfb82-6865-460f-8fa0-b963d718f9a6.mp4
> Fix nft expanded state blur overlay offset on android

- src/screens/CurrencySelectModal.js
- src/utils/ethereumUtils.ts
Fixes RNBW-2084
`getBalanceAmount` was only taking the estimated params to calculate a max ETH value, so when you pressed max the tx wouldn't even leave the app because of not having enough balance
before https://recordit.co/RMfoBg8DSN
after https://recordit.co/X2Tc6tSMJG
> fix send max ETH with getBalanceAmount

- src/components/expanded-state/asset/ChartExpandedState.js
- src/components/sheet/sheet-action-buttons/BuyActionButton.js
- src/components/sheet/sheet-action-buttons/SendActionButton.js
- src/components/sheet/sheet-action-buttons/SwapActionButton.js
- src/hooks/useAsset.js
- src/hooks/useCollectible.js
- src/redux/optimismExplorer.js
- src/references/chain-assets.json
1. We weren't memo-izing some important objects inside of the ChartExpandedState.
This and the combo of not memo-izing the internal Send/Swap/BuyActionButtons were causing those buttons to re-render many times unnecessarily.
2. This PR also includes a small cleanup in useAsset for it to use the new useCollectible hook.
3. Fixes this crash: https://sentry.io/organizations/rainbow-me/issues/2882560935/?project=1855565&referrer=slack. Details in the commit.
The easiest way to review this PR is to follow the commit history.
Here are some before and afters with logs inside the respective Send/SwapActionButtons:
Before:
After:
There should be no changes
[X] Assigned individual reviewers?
[X] Added labels?
> Reduce rerenders on ChartExpandedState + Fix crash

- src/components/exchange/ConfirmExchangeButton.js
Fixes RNBW-2012
Token swap button would briefly flash to say "insufficient eth" when loading (see example in Linear ticket). I fixed this.
https://user-images.githubusercontent.com/15272675/146874428-74e3d9e4-5bc2-48f0-8aa8-96faa03b8037.mp4
> fix swap button briefly flashing to 'insufficient eth'

- src/redux/data.js
Fixes RNBW-2122
On the very first load when switching from the older `assets` redux data to the new `accountAssetsData` version for the very first time, there is a point where we load an empty state from localstorage and set the `isLoadingAssets` flag as `false`. This was causing us to add on the empty ETH asset in `buildCoinsList` though it does not exist in `useAccountAsset`.
There is a further fix required to properly handle the situation when a user does not have ETH in their wallet, but this will be done in a follow up PR.
At least for now, it should not crash for this scenario.
Please note that I had cleared the async storage cache right before running this PoW.
https://recordit.co/7wFBnCOLo7
1. Delete the app
2. Switch between wallets multiple times
3. There should be no crashing …
> Fix crashing when switching wallets for first time

- src/handlers/localstorage/nonceManager.ts
- src/screens/TransactionConfirmationScreen.js
Fixes RNBW-2125
We're using the account settings address instead of the wallet connect session address in `TransactionConfirmationScreen`, so the nonce manager is getting another nonce if those addresses are different. Changed it to use `accountInfo.address` instead.
> Use nonce manager with WC session address

- android/app/src/main/java/com/swmansion/gesturehandler/react/RNZoomableButtonManager.java
- ios/Button.swift
- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/expanded-state/custom-gas/FeesGweiInput.js
Fixes RNBW-2044
Improved the usage of longPress in iOS and fixed it on android
- https://github.com/rainbow-me/rainbow/commit/2ff86aba295f80c82a1587506189e941d3552429 `GweiStepButton` is only using `onPress` now (not `onPressStart`) and now the callbacks calls will depend on `shouldLongPressEndPress` inside `Button.swift`. Having both was making the callback trigger twice, I saw that pattern in other places where `onPress` and `onPressStart` are different, but here I need one method dependent on `shouldLongPressEndPress`.
- https://github.com/rainbow-me/rainbow/commit/476fd0a12e67280954721eba5fbe8c3e3dbaa05a added a `minLongPressDuration` of 100 because it was taking too long to trigger the longPress event and 69 way to short, I found myself pressing it just once but the event triggering …
> fix button long press

- src/App.js
- src/components/walletconnect-list/WalletConnectListItem.js
- src/redux/walletconnect.js
- src/screens/SendSheet.js
Fixes [RNBW-2077](https://linear.app/rainbow/issue/RNBW-2077/wrong-chain-showed-in-connected-apps-after-chain-switching-is)
Dapps that ask for a wallet to switch chains are successful, but the change is not displayed visually in our "Connected Apps" sheet (we always show them connected to Ethereum Mainnet). When users initiate a transaction, they see the expected chain.
_Note: this shouldn't be confused with chain switching **within** Rainbow_
- `chainId`s need to be converted from strings to numbers for `ethereumUtils.getNetworkFromChainId`. We do this in some places, but not others.
- wallet connection changes needed to be persisted to redux when listening for wallet connect chain adding/switching events, this is important for dapps on L2s to reflect correct chain in our "connected …
> Fix network switching issues with WC

- src/redux/gas.ts
Fixes RNBW-2129
We're sending many arbitrum tx that ends up failing because of `gas price too low` because we're using half of the gwei coming from the provider for the gas price value.
Watching txs in arbitrum seems like all txs are using the value that's coming from the provider, which is the double of what we're currently using, ending up paying around 85% of that value. For ex, gas price from provider is 1.2 gwei and the paid gas price is 0.96 gwei, in which case we'd be sending txs with 0.6 gwei, so our users are sending txs with a gas price that will never confirm the tx.
I'm changing the gas price to just use the plain value coming from the provider. If we want to cut a bit of that value we could use between 80% to 85% to be sure the txs will go through. 
[ ] Assigned individual …
> update arbitrum gas prices

- src/redux/data.js
we're removing the filtering for L2 assets with 0 price info as it was messing with showing new tokens.
instead we now rely on the scam token list to filter any out. 
I went through and added a bunch from my wallet, dame's and a few others, changes are live. 
note we are still auto-hiding url formatted token names on the app
PoW(this was hidden before): https://cloud.skylarbarrera.com/Screen-Shot-2021-12-29-16-45-56.08.png
L2 assets with pricing info should not be hidden, example Bsticks in dame.eth
> remove L2 no price filtering

- src/components/animations/RoundButtonSizeToggler.js
- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/CoinCheckButton.js
This button has a poor performance. It got introduced in https://github.com/rainbow-me/rainbow/pull/2378
to fix: https://linear.app/rainbow/issue/RNBW-1538/edit-mode-checkboxes-are-not-pressable-on-android
I fix the original issue, by getting rid of `isAbsolute: true` and then adjusting relative size by `left: 9.5`
https://streamable.com/g5zx4c
https://linear.app/rainbow/issue/RNBW-1538/edit-mode-checkboxes-are-not-pressable-on-android
Open edit mode and try to select / unselect things 
> Get rid of the reanimated button in edit mode

- src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
- src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx
- src/react-native-animated-charts/src/helpers/ChartContext.ts
Fixes RNBW-2130
Fixes RNBW-2123
I fixed a few issues with scrubbing:
1. `least` was not working correctly. It was producing off-by-one error sometimes
2. Now we firstly get the index of the closest x point (from `points`), then obtain the original x (`originalX`) point that is connected to the input data.
3. After that we adjust this x original point interpolating with the next closest x point (from the `points` set). E.g. if the point user's touching is ideally between two, we get their mean. We use reversed weighted mean by the distance to each point.
4. Then we connect this point to the closest point in the original data set (from `data`). Effectively, w have more precise scrubbing cause we're not ignoring native points. 
This is matching the behaviors from the previous implementation. …
> Fix scrubbing

- .yarnrc
Just a quick PR to add the ability to pin dependencies by default on `yarn add ...`
> Add `save-exact=true` to pin dependencies by default

- src/components/expanded-state/asset/ChartExpandedState.js
- src/hooks/useAccountAsset.js
- src/hooks/useAsset.js
Fixes RNBW-2145
ETH is the single asset that may not exist in account assets data but still be displayed to the user in the WalletScreen. The `WrapperBalanceCoinRow` previously relied on the `useAccountAsset` hook, which would not find the 0 balance ETH asset. We therefore need to do a fallback in this particular scenario to the generic assets data formatted as an account asset data.
I've updated the `useAccountAsset` hook itself to return the account asset if found, or the generic asset fallback, or the ETH placeholder fallback. I know that `useAccountAsset` is now a bit of a misnomer, but I updated the description for now until I think of a better name for this hook.
Add the poopcoin.eth wallet using the seedphrase and switch to one of the empty ETH (but with other asset) wallets. There …
> Include generic assets and placeholder ETH fallback logic in useAccountAsset

- src/redux/data.js
- src/redux/explorer.js
When switching wallets, often we do not need to re-emit generic assets as they are handled in the TokensListenedCache. When switching wallets however, we were still triggering the generic assets fallback even when no new asset prices were actually requested.
Locally ran logs where `ZERION IS DOWN! ENABLING GENERIC ASSETS FALLBACK` would show up after every wallet switch, and now it does not after the first wallet load.
N/A
[X] Assigned individual reviewers?
[X] Added labels?
> Skip unnecessary generic assets fallback

- src/hooks/useGenericAsset.js
- src/hooks/useSavingsAccount.js
- src/hooks/useWalletSectionsData.js
- src/redux/explorer.js
- src/utils/ethereumUtils.ts
Partially fixes RNBW-2120
I got rid of additional rerender because of `useEffect`. Additionally, I used mmkv for caching to avoid rerendering because of async local storage.
This function is still called a lot of times, because of `useWalletSelectionData` hook that should be done better (was 170, is 110).
Additionally, I fixed the usage of `useCoinListEdited` in `useWalletSelectionData`. This was cause rerenderns  
None
Make sure that the Savings section (total balances as well as expanded savings states) show correct price information (instead of just $0.00) when first opening the app or switching wallets.
[X] Assigned individual reviewers?
[X] Added labels?
> Refactor useSavingsAccount 

- ios/RainbowText.m
- src/components/savings/SavingsListRow.js
Fixes RNBW-2136
I noticed that timer was not invalidated and after some remounting that happens initially while loading. This was causing a crash. Now it's fixed.
(https://streamable.com/y61x4y
1. Open the wallet, open the section with savings, close the wallet, open the wallet, switch wallets - should not crash
2. Open the wallet, open the savings section, (leave it open), and then switch to another wallet - should not crash
> Fix crash in animated numbers

- ios/Rainbow.xcodeproj/project.pbxproj
#2753 changed a bunch of things, while we should only need to touch the PriceWidget and SelectTokenIntent (not the app)
> Only set release profile for widgets

- src/screens/BackupSheet.js
This fixes the missing `cloudPlatformName` key on the backup screen.
Before:
After:
> Fix key for cloud backup description.

- src/components/expanded-state/ContactProfileState.js
- src/components/expanded-state/WalletProfileState.js
- src/components/profile/ProfileMasthead.js
- src/components/send/SendHeader.js
- src/languages/_english.json
- src/languages/_french.json
- src/screens/SettingsModal.js
- src/screens/WelcomeScreen.js
Another quick PR with some i18n tag fixes. In this case, there were a few instances where the same tag ID was used multiple times and the original text it was supposed to represent was replaced.
Adds a few new tags to fix re-used tag issues.
The above used to say "Create Wallet" since a tag was reused incorrectly.
```
yarn check-translations
yarn run v1.22.17
$ ./scripts/check-translations.sh ./src './src/languages/*.json' lang.t
Checking file "./src/languages/_english.json":
✅ No errors found for "./src/languages/_english.json".
Checking file "./src/languages/_french.json":
✅ No errors found for "./src/languages/_french.json".
Note, this script currently **does not** support interpolated translations such as `lang.t(`my.${variable}.based.${path}`).
🔶 Manual check required for …
```
> Fix some i18n duplicate issues.

- src/components/expanded-state/chart/ChartExpandedStateHeader.js
- src/components/expanded-state/chart/chart-data-labels/ChartChangeDirectionArrow.js
- src/components/expanded-state/chart/chart-data-labels/ChartDateLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartPercentChangeLabel.js
- src/components/expanded-state/chart/chart-data-labels/ChartPriceLabel.js
- src/components/value-chart/Chart.js
- src/react-native-animated-charts/src/charts/linear/ChartLabels.tsx
Fixes RNBW-2065
Basically now we rely more on the JS thread instead. We run the code to format labels on the JS thread and only when scrubbing on the UI thread. Also, I used regular props for default values such as date label or initial price label. It did make it faster to render.
What has changed? Now we rely on real prop value. Previously it would be assigned to the shared value in useEffect. So now we have delay for that. And since UI Thread is busy rendering everything it's slower to appear.
But also this new change is the right implementation of this. Because there was no way to recreate worklet on some react-world value change. Now we can just add it as part of the worklet dependencies.
Also, another change i did in this PR - i optimized the re-render the chart labels to at the …
> Make Chart Labels faster to render

- src/components/coin-row/BalanceCoinRow.js
- src/components/coin-row/CoinRow.js
- src/components/send/SendAssetList.js
- src/screens/CurrencySelectModal.js
Fixes RNBW-2198
RLV changes added isHIdden to every coin row, while we only care if its hidden for the BalanceCoinRow
added removing hidden tokens form swap & send (updated POW)
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-11-22-49-32.mp4
hidden tokens in search or lists should be normal, should not be in send or swap
> pass hidden & pinned from balance row

- src/screens/TransactionConfirmationScreen.js
Fixes:
https://rainbowhaus.slack.com/archives/C02LPE7TYTX/p1642030157005900
Fixes RNBW-2212
Wrong key was being used for the gas button, it was using `network` instead of `currentNetwork`
Seems like it was broken here https://github.com/rainbow-me/rainbow/pull/2706/files#diff-f2aec906d3575ac26f0daf12a43661c34a7e0b1a4cdc082ca4c56ec0ad7bf404R1131
https://recordit.co/PPkfUbfQbk
Repeat steps Ibrahim took:
1. I went to https://rainbow-me.github.io/rainbow-button/
2. tapped on Optimism and connected
3. selected sendTransaction
4. on the sheet expand the gas options
> fix gas button network in txConfirmationScreen

- src/components/expanded-state/custom-gas/GweiInputPill.js
rainbow currently doesn't support dynamic text sizes via device setting. eventually it will, but for now we disable it in the few places it does work since it doesn't help much and tends to break the layout
it was enabled on the gas inputs, this PR disables it
before:
after:
> Disable font scaling on gas inputs

- src/navigation/onNavigationStateChange.js
Fixes RNBW-2156
I realized that the code is used on light mode, should be obviously running in both dark and light mode. 
I can post later, but I need QA this anyway 
Test on both themes, navigate to swap and discover sheet a few times, play with a keyboard.
> Fix keyboard handling on dark mode on android

- src/components/settings-menu/SettingsSection.js
- src/screens/ExplainSheet.js
Fixes RNBW-2226
when we moved to notion we changed the url from rainbow.me/learn -> learn.rainbow.me
check links
> update learn links 

- src/entities/uniqueAssets.ts
The `traits` property on `UniqueAsset` is currently defined as a single object when it's actually an array of these objects. You can see this in practice in the usage of prop-types in [`UniqueTokenAttributes`](https://github.com/rainbow-me/rainbow/blob/2cc33c0d511ec5c0d80c146ea6224cf16077b0bb/src/components/unique-token/UniqueTokenAttributes.js#L46-L51).
> Update traits type on UniqueAsset to be an array of trait objects

- src/handlers/ens.ts
Fixes RNBW-2223
we we're reseting ENS results only if query length < 2 when we actually want to reset if there is no result
can't really put a POW without https://github.com/rainbow-me/rainbow/pull/2827
code is pretty obvious tho
> fix reseting ENS results

- .eslintrc.js
- .prettierrc.js
- src/design-system/components/Box/Box.tsx
- src/design-system/docs/system/tokens.css.ts
The Prettier config in this repo doesn't match the rules embedded in eslint-config-rainbow (missing `quoteProps: 'consistent'`) making it impossible to pass both ESLint and Prettier checks unless disable/ignore comments are used on the offending lines. I ran into this issue when migrating RainbowKit to eslint-config-rainbow and realised that this project has the same problem.
> Align Prettier config with eslint-config-rainbow rules

- src/design-system/docs/next-env.d.ts
- src/design-system/docs/package.json
- src/design-system/docs/yarn.lock
A recent version of Next.js broke v1.x of the vanilla-extract plugin, resulting in an `options.postcss is not a function` error, but this is fixed in v2. Next.js must have been updated in our repo recently because we've started getting this error.
> Fix design system docs by upgrading vanilla-extract plugin

- src/components/asset-list/EmptyAssetList.js
I noticed that sometimes (maybe when there was no content before?) the main screen is while instead of showing `AddFundsInterstitial`. This is especially visible on my Samsung S21.
Before:
After:
Try to add a new wallet, maybe kill the app, run again, try a few times.
> Fix AddFundsInterstitial

- src/components/discover-sheet/PulseIndexSection.js
I noticed this small bug on my Samsung. 
Before:
After:
Observe the button. I think there's no need to run this because I cannot observe this on any other phone except Samsung S21
> Fix margins in PulseIndexSection

- src/react-native-animated-charts/src/charts/linear/ChartDot.tsx
- src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
- src/react-native-animated-charts/src/charts/linear/ChartPathProvider.tsx
Fixes RNBW-2180
Fixes RNBW-2250
The dot was persisting the previous position. Now, I reset the position while the gesture ends and if it's not set, I do not show the dot at all (one frame).
before: https://streamable.com/suvaht
after: https://streamable.com/npgb6g
Try to observe if there's no dot in the previous position while starting the gesture.
> Fix flashing of dot in charts

- src/screens/ExchangeModal.js
Fixes RNBW-2200
Our android specific styling was unneeded and didn't allow us to handle keyboard height properly
this POW is on a very small device which is what was broken (pixel 2)
before: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-19-at-3.37.08-PM.mov
after: https://cloud.skylarbarrera.com/Screen-Shot-2022-01-19-at-3.34.36-PM.png
mainly want Terry to double check this works properly on his device
> fix android xchange formatting

- src/languages/_english.json
- src/languages/_french.json
- src/screens/ExplainSheet.js
- src/utils/platform.ts
Fixes RNBW-2276.
Adds a new i18n key for the `BACKUP_EXPLAINER` text, with a variable to insert the correct platform name.
(There are some more strings in `ExplainerSheet` that I'll move into i18n in the next PR, but those are the same regardless of platform, so I'm using this smaller PR for the iOS/Android change.)
On iOS, the text uses "Apple iCloud":
Someone who is able to build for Android should ensure that the text says "Google." This should work though, since manually changing `ios` to `false` led to the Google text.
- Ensure that text reads "... Google password..." instead of referencing iCloud.
> Fix backup explainer platform name.

- src/components/asset-list/RecyclerAssetList/index.tsx
- src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
- src/components/asset-list/RecyclerAssetList2/core/ViewTypes.ts
- src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
- src/components/asset-list/RecyclerViewTypes.js
- src/components/coin-divider/CoinDivider.js
- src/helpers/assets.js
Fixes RNBW-2050
added an edit button for < 5 asset wallets, removed any xtra handling for coin dividers that isn't needed now
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-18-10-51-32.mp4
edit + hiding/pinning tokens should work as expected
> add default edit button

- src/helpers/assets.js
Fixes RNBW-2307
uid's were the same as the elements in the family so the styling was getting overridden
https://cloud.skylarbarrera.com/Screen-Shot-2022-01-20-at-3.24.46-PM.png
> fix showcase NFT uid overlap

- src/components/sheet/sheet-action-buttons/BuyActionButton.js
Fixes RNBW-2278
I fixed the flow, it was needed to wrap this into an additional navigator. 
https://streamable.com/hm0p2o
To test you can either make a wallet and send another token (not eth to it) or set `true` instead of `needsEth` to `src/components/expanded-state/asset/ChartExpandedState.js:361`.
> Fix add cash flow on android within BuyActionButton

- ios/TransactionListViewCell.swift
Fixes RNBW-2327
The icons on the transaction list broke. This change adds the correct prefixing to the assets.
- Make sure the coin icons are working on the transaction list
> Make icons work again!

- src/handlers/deeplinks.ts
If we receive an "empty" deeplink like  https://rnbwapp.com we try to validate for an ENS or address aven tho there's nothing to validate and since is an empty string it will show an alert saying the deeplink is invalid. https://twitter.com/dwr/status/1483907093144817666
This pr removes this validation of empty params if deeplink doesn't contain ENS or address
after https://recordit.co/3Vkto1c8lw
> handle empty deeplinks

- src/navigation/Routes.android.js
Fixes RNBW-2339
This is fixing the issue of navigating immediately to the main wallet. The reason was that the modal was opening in the main navigator that was underlying for the BS navigator, so while navigating there we had to dismiss the setting sheet. This needs to be done better because we cannot nest navigators on and on. The ultimate solution would be to another "underlying navigator" on top of this (with pin sheet navigated already as the initial screen of this navigator), but this is a task for a whole day we don't have. 
After: https://streamable.com/fa80i6
Init the wallet with no biometric (e.g., in the sim) and try to open seeds. Should be broken on develop, but working here. 
Test revealing seeds, signing transaction and creation of the first wallet
> Abstract  out PIN_AUTHENTICATION_SCREEN to a different stack

- src/redux/uniqueTokens.ts
Fixes RNBW-2391
we we're saving and overwriting NFT data if we ran into an error fetching from OS, now we only save data if there are no errors
to test you can rm the `!errorCheck` on line 338 and throw an error in fetchPage
> nft fetching error check

- src/components/AddFundsInterstitial.js
Fixes RNBW-1590
- Conditionally added bottom margin to container view depending on phone size (tiny/small)
[Comparison of iPhone 13 Pro and iPhone SE](https://drive.google.com/file/d/1gOnN5GsRRuAxGyamDo62dl5U95Xk9fXt/view?usp=sharing)
> Fix welcome screen getting cutoff on smaller phones

- src/components/secret-display/SecretDisplaySection.js
Fixes RNBW-1859
Fixes broken button alignment for "Show Recovery Phrase" button
Before:
After:
> Fix recovery phrase authentication button alignment

- src/components/AddFundsInterstitial.js
- src/components/Tag.js
This PR fixes an issue where the app was crashing on the AddFundsInterstitial screen after #2849, as well as fixing compatibility with the design system `Row` after #2891.
> Fix `bottom` styling type issue for AddFundsInterstitial & Row compatibility

- src/components/asset-list/EmptyAssetList.js
Fixes RNBW-2380
This PR fixes an issue where if the select wallet sheet overflowed, a user could not swipe down to dismiss the sheet.
Before:
After:
- On the select wallet sheet, when the wallet list overflows, ensure you can dismiss the sheet when you scroll down (after scrolling through the list)
> Fix issue where scrolling down on switch wallet sheet wouldn't dismiss the sheet

- src/components/qrcode-scanner/EmulatorPasteUriButton.js
- src/hooks/useScanner.js
Fixes RNBW-2436
Noticed that when we scan a wrong QR code we don't show the alert - seems like the API to show an alert was changed in some version of React Native and we never noticed. I updated the code of showing that alert to use the new API.
In the original issue, the QR code scanner would not work after some time. This was the cause: wrong API usage didn't throw any errors but we never called enableScanner. So after the very first wrong QR code - it no longer works for the user until the app restart.
https://drive.google.com/file/d/1PhiHQYKJotFWq4VZCy059xXepzlyIM57/view?usp=sharing
Scan different qr codes. Expect to see the "Wrong QR code" alert on the scan of the QR code below. It should work after pressing "okay".
> Make sure QR code scanner is always enabled

- src/styled-thing/index.js
Fixes RNBW-2466
Since our own faster implementation of styled components doesn't support CSS strings - we should make sure no one is using it. So from now on, it will throw an error if template literal syntax is used.
So this won't work:
```
const Container = styled.View``;
```
And this will work
```
const Container = styled.View({});
```
When we call the function with template literals instead of parenthesis 
```
syled`` 
```
it passes the template string and all the string interpolations (`${}`) as an array. So I check for an array to detect if we used template literal.
It should not break anything
> Throw an error when css strings is used with styled components

- src/parsers/accounts.js
Typically asset data retrieved from mainnet doesn't contain a `network` property. When a network property is included for mainnet values, the app crashes. This is a small change to prevent `accountAssetsData` from returning `undefined` when attempting to access mainnet assets that haven't omitted the network property.
Overwrite `config.data_endpoint` in `explorer.js` (line 87) to be `wss://refraction-1912.api.p.rainbow.me/`. Observe no crash on launch.
Check that the wallet screen displays normally when pointing to the actual `config.data_endpoint`.
> Prevent crash when mainnet assets contain 'network' property

- package.json
- src/App.js
- src/hooks/useDPI.ts
- src/hooks/useLoadGlobalLateData.js
- src/hooks/useUniswapPools.js
- src/hooks/useWalletBalances.js
- src/react-query/queryClient.ts
- tsconfig.json
- yarn.lock
Fixes RNBW-2545
This PR updates React Query from v1 to v3. The main motivation of updating React Query is because we are utilising it in the ENS profiles work for some async functions, and we would really benefit from certain features such as: deterministic boolean state variables (`isIdle`, `isLoading`, `isSuccess`, etc), and render optimisation (`notifyOnChangeProps`).
This PR also migrates existing instances of `useQuery` to the new v3 API. I have also added a global `notifyOnChangeProps` option (introduced in v3) to the query client which is set to `"tracked"`, so that queries only trigger a re-render whenever one of the tracked return values change. This will further improve the performance of current React Query usages as v1 triggered a re-render whenever any return value changed. …
> Chore: Update React Query to v3

- src/screens/ExternalLinkWarningSheet.tsx
Fixes RNBW-2591
The app was crashing when tapping on links in the markdown sections in the NFT expanded state. Turns out it's because there was a usage of styled-components in `ExternalLinkWarningSheet` that hadn't been migrated to the object syntax after we switched over to our custom styled-components implementation.
https://user-images.githubusercontent.com/696693/154574962-3ea111b4-3659-4d2a-af3d-1c5b9552deb0.mov
External links open the warning sheet and don't crash the app. Note that this warning sheet doesn't show for URLs from our [list of trusted domains.](https://github.com/rainbow-me/rainbow/blob/develop/src/navigation/useUntrustedUrlOpener.ts)
> Convert ExternalLinkWarningSheet styles to object syntax

- README.md
Removes CodePush from `README.md`
CodePush isn't found in the rest of the codebase so this removes any confusion relating to CodePush.
> Remove CodePush

- src/components/coin-row/ExchangeCoinRow.js
Fixes RNBW-2575
We have separate code for this button on iOS and on Android. On Android tap handler was passed incorrectly and in result it was never called.
1. Tap on swap button.
2. Tap on `Choose Token`.
3. Try to add/remove a favorite on the list.
> Fix favorite button on swap list on Android

- src/components/settings-menu/SettingsSection.js
- src/languages/_english.json
- src/languages/_french.json
Fixes RNBW-2257
Check settings on two kinds of screen size. It should be intact on big screen and on small screen a) scrolling should be available b) _Learn about Rainbow and Ethereum :)_ should become _Learn about Rainbow :)_
Note: make sure that settings modal is dismissable on bigger Android screen where is not big enough to "enable" scroll.
> Fix settings modal cut on narrow phones

- src/styled-thing/index.tsx
I didn't add proper types, just ran ts-migrate on `src/styled-thing` which was still a js file, causing problems when importing from ts files.
None
Linter shouldn't complain about `import styled from '@rainbow-me/styled-components';` to be at the top anymore.
> Convert src/styled-thing to typescript

- src/components/showcase/ShowcaseHeader.js
Fixes RNBW-2468, RNBW-2628
Check that the function `contextValue?.setIsSearchModeEnabled` exists before invoking it. This function doesn't exist if the wallet doesn't have an ens, which is what was causing the bug.
https://user-images.githubusercontent.com/15272675/155228346-6ca2a46b-c972-49e2-b96a-6822272a27f9.mp4
Make sure that wallets that don't have ens names can be watched.
> fix scanning QRs and adding wallets issue

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
Fixes RNBW-2571
we had disabled touch events for audio , video & 3d NFTs since the zoomableWrapper doesn't support them properly and we wanted to ship.  audio + 3d nft's work fine.There's more issues with videos atm so i'm fixing the easy ones for now 
https://cloud.skylarbarrera.com/RPReplay_Final1645569203.MP4
should work fine.  asset examples are in PoW
> only disable touch events for video NFTs

- patches/react-native-gesture-handler+1.10.3.patch
Fixes RNBW-2386
I noticed that pretty often, on my machine at least, scale animation buttons on the android emulator would stuck/freeze while still being able to fire events. A few times i've seen this on my Pixel 3 but i'm not able to reproduce it constantly to be sure it's the same issue. After some research, I found [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/1512) that fixes exactly that. Unfortunately, it's part of Gesture Handler 2 we can't use right now because we need to refactor these buttons to use the new kotlin based API. So i used patch instead.
TBA
- Buttons should work
- It's android only
> Add scale animations buttons patch

- src/hooks/useENSRegistrationActionHandler.ts
We want to use the `changedRecords` value for the commit/register phase. 
`changedRecords` represents only the changed records in the edit ENS flow. For the create ENS flow, `changedRecords` represents all records created.
> Profiles: Use `changedRecords` for commit phase

- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
- src/utils/getFullResUrl.ts
- src/utils/getLowResUrl.ts
Fixes RNBW-2344
- Function to get low res image URLs was not using Google's weird format. Fixed it to comply with their server-side scaling.
- Added an extra function to get full res image URLs from Google when saving NFTs to camera roll.
https://user-images.githubusercontent.com/6843656/156679597-67559874-4c27-40c7-b272-f58b3e995b59.mp4
Saving NFT photos.
> Fix downloaded NFTs from Google User Content being low res

- audit-ci.json
- package.json
- yarn.lock
Reverts rainbow-me/rainbow#3022
This breaks the bundler 
```
BUNDLE  ./index.js
/Users/bruno/repos/rainbow/node_modules/metro-hermes-compiler/src/emhermesc.js:77
throw ex;
^
RuntimeError: abort(TypeError: Cannot read property 'url' of undefined). Build with -s ASSERTIONS=1 for more info.
at process.abort (/Users/bruno/repos/rainbow/node_modules/metro-hermes-compiler/src/emhermesc.js:440:13)
at process.emit (events.js:412:35)
at processPromiseRejections (internal/process/promises.js:245:33)
at processTicksAndRejections (internal/process/task_queues.js:96:32)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  rainbow git:(develop) ✗ git log
```
> Revert "Fix deps"

- src/components/backup/BackupSheetSection.js
- src/components/header/DiscoverHeaderButton.js
Fixes RNBW-2736
Visual changes only.
- "Back up manually" button no longer has its shadow clipped at the bottom on Android.
- "Discover" button no longer has a collapsed padding on the right side on Android.
| iOS  | Android  |
|---|---|
| ![Simulator Screen Shot - iPhone 11 - 2022-03-08 at 01 30 05](https://user-images.githubusercontent.com/6843656/157143869-0c8b8eaf-5022-47c1-9a91-d3028f40f589.png) | ![Screenshot_20220308-013000](https://user-images.githubusercontent.com/6843656/157143894-28f10e6f-799c-4500-a877-e609a3c01c08.png) |
Opening the app for the first time and looking at the bottom sheet. Looking at the "Discover" button in the header.
> Fix BackupSheet shadow & fix Discover btn padding

- audit-ci.json
_This dev found one SIMPLE trick how to STOP socket.io from destroying CI. SEE HOW:_
> Change audit to use package name instead of ID

- src/handlers/ens.ts
- src/helpers/ens.ts
- src/hooks/useENSRegistrationActionHandler.ts
- src/raps/actions/ens.ts
- src/raps/common.ts
Fixes RNBW-2691
Added resolver address resolution for `setRecordsAction` which is the action triggered when editing profiles, we need to use the resolver that the ENS has. we still default to the public resolver when creating the profile.
> profiles: handle resolver when editing profile

- src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
- src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
- src/hooks/useENSRegistrationActionHandler.ts
- src/hooks/useSelectImageMenu.tsx
Fixes RNBW-2663
This PR implements a change where the user will no longer have to wait for the avatar/cover to be uploaded to continue with the registration process. Instead, it will upload in the background, and use the uploaded URL for the avatar/cover record if it has been uploaded by the time the user submits the form. If the photo has not been uploaded, then it will upload it at the time of form submission.
> Profiles: Defer image upload

- src/components/settings-menu/DevSection.js
- src/components/settings-menu/NetworkSection.js
- src/components/settings-menu/UserDevSection.js
- src/config/experimental.ts
- src/config/experimentalHooks.ts
- src/helpers/RainbowContext.js
- src/screens/SettingsModal.js
Fixes RNBW-2825
1. Exposed experimental section
2. Added Network toggler in the section (previously this was only in "prod" dev section so this is necessary not block testnets for TF users
3. Added params in which experimental options should be exposed to users. Currently, this is only "ENS Profiles"
4. Used nicer wording. 
Run in DEV mode and see what will happen. To make sure this works in TF the only 100% guarantee will be to actually make a TF release.
> Expose Dev section to TF users

- src/components/expanded-state/unique-token/ZoomableWrapper.js
- src/utils/getLowResUrl.ts
Fixes RNBW-2813 RNBW-2834 RNBW-2833
Fixed link. currently this was possible to have a non-integer value in the Google storage link. This is fixing nfts ratio, ens colors.
Also, fixed zoomable wrapper to respect changes in the newest reanimated.
https://streamable.com/wvr14l
Wipe everything (including mmkv, see tomek's newest PR) and try to repro bugs.
> Fix zoomable wrappers issues

- src/components/settings-menu/DevSection.js
- src/handlers/localstorage/accountLocal.ts
- src/hooks/usePersistentAspectRatio.ts
- src/hooks/usePersistentDominantColorFromImage.ts
- src/model/mmkv.ts
Fixes RNBW-2849
Currently we use several MMKV storages that go under different IDs. It is important for existing functionality to keep them separate, but we need a way for clearing all of them at once.
> Organize MMKV storage IDs

- package.json
- yarn.lock
`rainbow-token-list` was listed as a dependency but is not used anywhere as a package.
> Remove `rainbow-token-list` as a dependency

- ios/PriceWidgetExtension.entitlements
- ios/Rainbow/Rainbow.entitlements
- ios/Rainbow/RainbowDebug.entitlements
- ios/Rainbow/RainbowRelease.entitlements
- ios/SelectTokenIntent/SelectTokenIntent.entitlements
- src/redux/settings.ts
Fixes RNBW-2596
- widgets were unable to get currency setting from rainbow app. this rendered "default currency" option useless.
https://user-images.githubusercontent.com/15272675/158868680-1cff93b3-8b7c-4a2d-a5dc-5e62efbb1485.MP4
- make sure that widget's default currency option works, and switches immediately after the user changes the currency setting in the app.
> @benisgold/widget regression fixes

- src/components/expanded-state/UniqueTokenExpandedState.tsx
Reverts rainbow-me/rainbow#3024
after talking with @osdnk we decided there's too much inconsistency with this logic to display correct pricing.
> Revert "round last sale price"

- src/redux/data.ts
We now make sure to use the account address received in the response when persisting asset data.
You will need to watch a wallet with a lot of tokens in it (dame.eth worked well for me). Then quickly switch back and forth on the wallet screen between the heavy wallet and a nearly empty one. In prod you will eventually see assets from the heavy wallet make their way onto the other wallet's screen.
> [RNBW-2458][RNBW-2140][RNBW-2873] UI is mixing up my wallet balances

- src/screens/WyreWebview.js
Fixes RNBW-2674
instead of removing the button once, we remove this in intervals to make it not possible to press it at any time 
before: https://streamable.com/6u0v4j
after: https://streamable.com/le8tgi
Try to repro the bug from the first recording
> Repeat hiding CloseBtn in WyreWebview

- src/components/animations/ButtonPressAnimation/ButtonPressAnimation.android.js
- src/components/jelly-selector/JellySelector.js
Fixes RNBW-1521
it works. `onLayout` as not working with BPA on android.
> Fix jelly selector on Android

- src/config/index.ts
- src/hooks/index.js
- src/hooks/useImagePicker.tsx
- src/hooks/useOnAvatarPress.ts
- src/hooks/useSelectImageMenu.tsx
- src/languages/_english.json
Fixes RNBW-2742
Added a hook in charge of open the image picker, if there are no permission because user rejected it, it will show an alert directing them to settings
https://www.loom.com/share/8d73b52c7b544a1e9b41b9a8f6361773
> Profiles: Handle image picker permissions

- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
Fixes RNBW-3040
The API is sending ` ⚠️` in addition to the ENS name so the `useProfile` hook wasn't working as expected
> Profiles: fix expanded state in name with strange characters

- src/components/sheet/SlackSheet.js
Noticed that Android doesn't properly respect scroll position for the ZoomableWrapper in the NFT expanded state.
This is just a simple fix so that Android works properly with ZoomableWrapper.
Before:
https://www.loom.com/share/1002bed341bc4d889a27d769dbc13c7f
After:
https://www.loom.com/share/a561a110c454462ba09df028f41d18eb
- On Android, open the NFT expanded state and make sure the image expands to the center in all scroll positions
> Fix issue where zoomable wrapper wasn't respecting scroll position on Android

- e2e/registerENSFlow.spec.js
- src/hooks/useENSRegistrationActionHandler.ts
Fixes RNBW-2909
Added an additional flag to the `useENSRegistrationActionHandler` hook to when waiting the 60 secs from COMMIT tx.
The logic right now is just waiting 60 secs from the block the `commit` tx got in, this could cause issues if we're trying to send the `registerWithConfig` tx in a block where 60 secs or less has passed from the `commit` tx block.
- Lets' say we have a block `0xA` where it's timestamp is `const t = Date.now()`, so 0 secs have passed yet. 
- Then we wait for 55 secs and another block `0xB` with timestamp `t + 55 secs` was just included
- Another 5 secs passed and we try to include the `registerWithConfig` tx, but there aren't confirmed blocks with `t + 60 secs` as timestamp so that tx is going to fail. In our case it was blocking the gas estimation, since the …
> Profiles: 60 secs wait from COMMIT tx

- src/handlers/deeplinks.ts
Fixes RNBW-3038
- Deeplinks to wallets with ens names now route to profile sheet instead of showcase sheet
https://user-images.githubusercontent.com/15272675/161122088-fc07df1f-955f-467a-b306-b8e03d4b787e.mov
> deeplink route to profile sheet

- src/components/expanded-state/asset/ChartExpandedState.js
Fixes RNBW-3103
This is weird that this error is happening. Looks like this is possible that `delayedDescription` is defined and `description` is undefined. Otherwise, this logic should block the rendering of the component 
Maybe this is happening when the store is updated (and then some error is occurring or the description was removed by the provider)? 
Regardless of the issue, I now use `delayedDescription` if `description` is not defined. For extra safety, I default `text` prop to an empty string ( I guess this should never happen, but costs us nothing to make it)   
Set `text` to `undefined` and see if it's not breaking.
> Fix description crash

- package.json
- yarn.lock
In this PR I added a proper version of `react-devtools-core` to use with React Native.
The `react-devtools-core` package is part of `react-native` package. But the version included with the current version is out of date. This is why we specifically used the newer version that works with new versions of react-devtools.
The version used in this PR works properly with `react-devtools@4.24.1`.
- React devtools running using `npx react-devtools@4.24.1` should connect to the app in Dev
> Add react-devtools-core resolution

- src/design-system/color/palettes.ts
while testing profiles, noticed the light mode primary text color wasn't accurate in the design system
- changed the primary text color in light mode from `#3C4252` to `#25292E` to be consistent with the rest of the app
- added `secondary06` which we use relatively often as a button background color—lmk if there's a better way to add/use this color
- no associated tests afaik
- n/a
> Design system color edits

- src/screens/ENSConfirmRegisterSheet.js
Fixes RNBW-3130
This PR fixes an issue where the "Confirm Registration" button was displaying "Insufficient ETH" when not ready.
Added stricter equality to the `insufficientEth` condition.
> Profiles: Fix incorrect "Confirm Registration" placeholder

- src/components/ens-profile/ActionButtons/EditButton.tsx
- src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/components/inputs/InlineField.tsx
- src/hooks/useENSRecordDisplayProperties.tsx
- src/hooks/useOnAvatarPress.ts
- src/navigation/RegisterENSNavigator.js
- src/screens/ENSAssignRecordsSheet.js
Fixes RNBW-3118
Fixes RNBW-3119
This PR fixes an issue where Android was getting a [black screen](https://linear.app/rainbow/issue/RNBW-3118/qa-android-edit-from-ens-nft-has-weird-behavior) when attempting to edit an ENS profile. Previously, we started the registration process (`startRegistration` action) on initial mount of the screen, but now we are invoking it before transition to the screen.
Also fixed an issue where the [@ symbol](https://linear.app/rainbow/issue/RNBW-3119/android-in-records-is-misaligned) on the twitter field was misaligned on Android.
> Profiles: (Android) Fix issue when attempting to edit ENS profile

- scripts/postinstall.sh
I extracted duplicated code to a function and added error handling there. Usually we don't expect `.env` file to be half complete, but with recent introduction of codepush it can be broken for people and there's absolutely no error printed which lead me to debugging the script.
Plus IMO it looks cleaner.
Config files.
No.
If app builds we are fine.
> Refactor postinstall.sh to reduce code duplication and improve error handling

- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
- src/components/expanded-state/unique-token/ZoomableWrapper.android.js
- src/components/expanded-state/unique-token/ZoomableWrapper.js
- src/components/sheet/SlackSheet.js
Fixes RNBW-3057
* Added `onZoomIn` and `onZoomOut` callbacks to `ZoomableWrapper` component
* Added props `showsHorizontalScrollIndicator` and `showsVerticalScrollIndicator​` from ScrollView to `SlackSheet` component, props are passed to underlying `ScrollView` and `true` by default (like in ScrollView)
* Added state that replicates ZoomableWrapper zoomedIn state, which drives whether the scrollbars are visible or not + also drives whether scrolling is enabled (fixes pan scroll on the bottom of the zoom in overlay)
Forgot to record mouse clicks, but the effect is still visible, first I'm using scroll bar which disappears after changes, and I'm trying to pan just above the Bottom iOS system navigation bar
Before it was like this:
https://user-images.githubusercontent.com/16062886/161756272- …
> Fix possibility to scroll with scroll indicator on unique asset image preview

- src/languages/_english.json
Michał pointed to me that I accidentally added smile to the English version of Rainbow that was not there before (I took it from French one).
> Remove smile emoji from label

- src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
- src/hooks/useInterval.ts
Fixes RNBW-3192
This PR enables long pressing on the year duration field on the confirm registration sheet.
https://www.loom.com/share/730765f7982a4976b72915bb09ed3367
> Profiles: Enable long press on duration field

- src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
- src/components/asset-list/RecyclerAssetList2/core/ViewTypes.ts
- src/components/header/DiscoverHeaderButton.js
Addressing a couple of Phase 2 PR comments
> Profiles: Address Phase 2 PR comments

- src/model/wallet.ts
Fixes RNBW-2898
This bug is reproducible only for androids and only when biometrics is turned off.
When importing a wallet to monitor it, a pin is required. The watch wallet must be added without a pin
When creating a wallet, I validate its type on `readOnly` These wallets do not need a password. So in the following steps, we avoid  encrypting the seeds, we don't need to encrypt the private key for that wallet too
Before: https://streamable.com/2u9iat
After:  
- https://streamable.com/axr51e
- https://streamable.com/eqokwq
importing a watch wallets
> Remove PIN input while importing wallet in watch-only mode

- src/apollo/queries.ts
- src/components/discover-sheet/DiscoverSearch.js
- src/components/exchange/ExchangeAssetList.js
- src/handlers/ens.ts
- src/hooks/useFetchUniqueTokens.ts
Fixes RNBW-2878
Fixes RNBW-3182
Improved the ens search by
- Search will now work getting up to 8 ens names, we were querying for 75 and then cutting the array result to 3
- Results would need to start with the search query, this was making some ens names to not appear
- Added ens avatar images resolver, wanted to know what you think about this @jxom since we'll add a bit more wait to get the avatar but I didn't want to show an emoji while waiting for the avatar to load
- The new profile screen shows a loader so the comment from christian in the card was solved before
https://www.loom.com/share/67f28e772e924710b716b96636e82f46
> Profiles: improve ens search

- src/react-native-animated-charts/src/charts/linear/ChartPath.tsx
Fixes RNBW-1115
Sometimes opening charts would result in an empty chart. It can be related to some changes to the Reanimated 2 Scheduler in the latest 2.4.1 version. After some debugging, I noticed that we rerender charts many times during the first render
the log looks like this:
```
set path undefined
LOG  1
LOG  1
LOG  set path undefined
LOG  set path undefined
LOG  set path string
LOG  set path undefined
LOG  1
LOG  set path undefined
LOG  1
LOG  set path undefined
LOG  [1:26:09 пп] 😬 FallbackExplorer:: fetchOnchainBalances
LOG  set path string
```
where 1 is useAnimatedStyle with chart opacity
and set path - is useAnimatedProps
So we render chart many times and some of the renders with an empty chart path, so we pass `d: ''` as an animated prop. So since we pass an empty string and …
> Fix blank charts

- src/handlers/localstorage/ens.ts
- src/screens/ENSAssignRecordsSheet.js
Fixes RNBW-3194
This PR adds functionality to only show the ENS on-chain data disclaimer warning once per user.
> Profiles: Only show ENS on-chain data warning once per user

- src/components/3d/SimpleModelView.tsx
- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateContent.js
- src/components/unique-token/UniqueTokenCard.js
- src/components/unique-token/UniqueTokenImage.js
- src/components/video/SimpleVideo.tsx
- src/entities/uniqueAssets.ts
- src/handlers/imgix.ts
- src/hooks/usePersistentAspectRatio.ts
- src/hooks/usePersistentDominantColorFromImage.ts
- src/parsers/poap.js
- src/parsers/uniqueTokens.js
- src/utils/getFullSizeUrl.ts
- src/utils/getLowResUrl.ts
Fixes RNBW-2730 RNBW-2917
fixes some regressions from https://github.com/rainbow-me/rainbow/commit/3eac3a97f1980b61bb0380889c820ddd780a36b4 (low res image handling/progressive loading, certain NFTs not animating properly) 
as well as refactors image/svg handling/signing so its all in one place and is handled upfront rather than in 4 diff spots of the app 
all NFTs in `skillet.eth` (aside from genesis bags) should load on asset screen, and when opening the expanded state should open with the image already preloaded, colors & aspect ratios should be correct
few edge cases we want to check:
Loot in `dame.eth`
Max Pain in `0x58A4368a73196921e236f663388A96A209b64EE5`
Peaceful in `jdelman.eth`
- [] Added labels?
- [] If you added new files, did you update the CODEOWNERS file?
> image handling fixes + refactor

- src/redux/walletconnect.js
- src/screens/TransactionConfirmationScreen.js
Fixes RNBW-3234
Wallet connect callback `session_request` is loosing context of the whole method, so the var `meta` is always null outside the callback, the wc callback tries to update it but outside it `meta` will be always null. for some strange reason this is only happening on android, on ios the setTimeout that sends you to the disconnected explainer sheet is cleared correctly inside the wc callback
> Fix: android disconnecting messages

- src/design-system/color/palettes.ts
this color has an alpha value, should use rgba instead of rgb
> Fix sky06 color (rgb → rgba)

- src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
[While reading the documentation](https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/performance#2-key-prop-is-not-needed) of the recyclerlistview library noticed that we should not provide the key to RowRenderer because rows are being reused (updated with new props) instead of remounted as FlatList does.
It can be easily verified by adding this hook to `WrapperBalanceCoinRow`:
```js
useEffect(() => {
return () => {
console.log('Unmount');
};
}, []);
```
- it should not remount views
> Do not remount rows of RecyclerListView

- src/apollo/queries.ts
- src/handlers/ens.ts
Fixes RNBW-3278
This PR removes the dependency on fetching via `https://metadata.ens.domains` to retrieve the ENS NFT image + name, and instead rely on the graph to fetch an ENS name & fetching the image directly via `ImgixImage`.
> Profiles: Drop metadata.ens.domains fallback in favour of The Graph + ImgixImage

- src/components/discover-sheet/RegisterENSSection.tsx
- src/helpers/ens.ts
- src/screens/ENSAdditionalRecordsSheet.js
- src/screens/ENSAssignRecordsSheet.js
Fixes RNBW-3197
This PR ensures that the ordering of the selectable text records buttons matches the order of the text fields. 
I have also refactored to omit the `isPrimaryDisplayRecord` flag and instead take the first 9 records from `textRecordFields`. This ensures that if we chose to remove or add a field as a primary display button, then it wont affect the layout (button overflow or lack of buttons to display)
> Profiles: Make ordering of action buttons match order of fields

- src/components/discover-sheet/RegisterENSSection.tsx
- src/handlers/ens.ts
- src/hooks/useAccountENSDomains.ts
- src/screens/ExpandedAssetSheet.js
https://github.com/rainbow-me/rainbow/commit/a411ad53d8b3a4c9d93350f2b21f6b1ec32fbdeb added stale time to the query and I put the hook in the ens card so we fetch that info before going to the intro screen and the data is ready
https://github.com/rainbow-me/rainbow/commit/7e5512ea83972a90d70254dca23ff7d25e42b87f  we'll be revalidating nft in background only for ens nft that are unknown for opensea (we are still using the fallback correctly for ens nfts), we're doing it for all nfts now, @christianbaroni idea in the future is to have this action in a button somewhere in the ui for the rest of nfts
> Profiles polish

- ios/Podfile.lock
- package.json
- patches/imgix-core-js+2.3.2.patch
- yarn.lock
Fixes RNBW-3325
I used the MD5 function through JSI
Methodology:![image](https://user-images.githubusercontent.com/25709300/164233158-c9263bf3-a37c-434d-b2cb-90cf10443714.jpeg)
results:
Android:
before:
After
iOS:
before:
After:
Should be no-op, images should load 
Should be no-op
rel: https://github.com/rainbow-me/rainbow-scripts
> use MD5 through JSI with react-native-quick-md5

- src/apollo/queries.ts
- changed ens subgraph query to order by labelName (i.e. notben) instead of name (i.e. notben.eth). idk how ens subgraph sorts names behind the scenes, but for some reason this is more effective. one (potential?) caveat that I noticed is that ens subdomains are likely to end up search results. not necessarily a bad thing
before: 
after:
> Profiles: improve ens discovery

- src/react-native-cool-modals/ios/UIViewController+slack.swift
Fixes RNBW-2173
I noticed this was possible to send a dismissal command to a sheet that was not existing. I added an optional check for this. 
https://streamable.com/tzm8gt
See ticket for the broken state 
Make a swap visiting details sheet first. See the video 
Fedora will not work!
> Fix crash on details sheet

- src/redux/data.ts
Want to follow the same pattern of updating prices for the ETH USD value after the initial "received" price.
> Include price updates for ETH USD

- src/components/discover-sheet/RegisterENSSection.tsx
- src/handlers/localstorage/ens.ts
- src/hooks/index.js
- src/hooks/useAccountENSDomains.ts
- src/hooks/useAccountENSDomains.tsx
- src/screens/ENSIntroSheet.tsx
- src/screens/SelectENSSheet.tsx
Fixes RNBW-3411
Fixes RNBW-3412
Improving registration fetch
- images are now cached, before we were querying for avatar and cover images all the time
before: fetchImages was being called every time `fetchAccountENSDomains` is called, even tho that fetch was being cached 
https://recordit.co/L8os83EF1R
now we're saving those values to avoid unnecessary requests
https://recordit.co/F4ZwZ8idxC
- saving registration to local storage so we can use it as default while getting all the ens names of a wallet in the intro screen
in the video you can see at the beginning the data used to load the screen is the one saved in local storage, then data comes from subgraph and we use it instead
https://recordit.co/f8Pk5AWS7U
> Profiles: improve registrations fetch

- src/hooks/useENSRegistrationForm.ts
Fixes RNBW-3370
-` isLoading` in useENSRegistrationForm will be true until `profileQuery.isSuccess` is true
https://user-images.githubusercontent.com/15272675/164789457-1b610cf3-08bd-487b-ab5f-e1a020f320eb.mp4
> Profiles: tweak isLoading conditions in useENSRegistrationForm

- src/redux/data.ts
Fixes RNBW-3407
noticed we intermittently had the eth price revert back to USD when using a diff native currency. We subscribe to USD prices at the same time to keep the eth price in USD up to date which I imagine is causing this issue. 
We already do this check for `assetPricesReceived` 
change native currency to rupees, open swap eth -> dai.
in develop eventually it will revert and gas should show usd value
in this branch im unable to repro
> check native currency before updating assets 

- src/redux/wallets.js
- src/utils/profileUtils.ts
Fixes RNBW-3044
I couldn't really repro this issue but my guess is this is happening because the provider `lookupAddress` is failing on load, so the ens is not being resolved correctly.
This fix is just adding a retry logic to resolve the ens name in case of any failure.
> Fix: lookupAddress on wallet load

- package.json
- yarn.lock
fixes RNBW-2324
removed the old Data logo from react coin icon package
before: https://cloud.skylarbarrera.com/Screen-Shot-2022-05-02-15-08-05.28.png
after: https://cloud.skylarbarrera.com/Screen-Shot-2022-05-02-14-56-26.21.png
> bump react coin icon

- CODEOWNERS
- src/components/floating-emojis/FloatingEmoji.js
Fixes RNBW-3392
* Rewrote FloatingEmoji animation code with Reanimated 2 preserving all settings it had with Reanimated 1
Before:
https://streamable.com/93ul9w
After:
https://streamable.com/855urh
* open app
* swipe left
* copy address and see if it works just like with Reanimate 1.
> translate Floating Emoji from Reanimated 1 to Reanimated 2

- src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
- src/components/ens-registration/TextRecordsForm/TextRecordsForm.tsx
- src/components/inputs/InlineField.tsx
- src/hooks/useENSRegistrationCosts.ts
- src/screens/ENSAssignRecordsSheet.js
- src/screens/ENSConfirmRegisterSheet.js
- src/screens/ENSSearchSheet.js
Fixes RNBW-3488
When you change the registration name that you're using or coming back from a "In Progress" registration you can see that there's small lag from the moment the records form, avatar and cover is being updated to the correct values, since we are updating it "on focus".
I updated it to maintain the records values, avatar and cover up to date when the name is being changed, so there's no lag and the values update correctly in background when there's another `currentRegistrationName` in state.
Same case was happening with `prevDominantColor`, if an avatar `A.png` was set in a name, then you change the name or go to a ens nft without an avatar to extend or set name, the `prevDominantColor` would stay the one set with `A.png` even tho they're not related.
I also changed the stale …
> Profiles: fix records updates lag

- src/navigation/RegisterENSNavigator.js
- src/screens/ENSAssignRecordsSheet.js
same logic than before but i'm updating the wrapper style when going to a sheet with scroll enabled, if returning to a screen without scroll enabled i'm updating the state right away
for [72ec70ad92002264bcb99b3d4710187166917122](https://github.com/rainbow-me/rainbow/pull/3302/commits/72ec70ad92002264bcb99b3d4710187166917122) we're now using `initialRecords` to see if there's any record in the profile so we display `Edit` or `Create` + `your Profile`, together with that I added a useFocusEffect to set the correct accent color, this is useful when navigating through intro sheet and assign records sheet
before 
https://user-images.githubusercontent.com/12115171/166814401-90d09d26-b04c-4f66-90f5-5b8a12c711c5.mp4
after …
> Profiles: intro screen jump fix

- src/redux/data.ts
`checkForUpdatedNonce` did not account for situations where `transactionsReceived` is called, but no transactions are present. I also did some small clean up based on some guidance from @marco in the comments.
I don't know which situations would cause `transactionsReceived` to be called without transaction data. I could use some additional input on this. I think the changes are pretty minimal, though.
> [RNBW-2616] Cannot read property 'address_from' of undefined

- ios/Podfile.lock
- patches/react-native-fast-image+8.5.11.patch
Bumps react-native-fast-image's SDWebImage dependency to include this change: https://github.com/SDWebImage/SDWebImage/pull/3280
There's still an issue where if a GIF is in a sheet and you're dragging the sheet, the speed changes while dragging, but otherwise this fixes the issue
Fixes RNBW-2590
fast image looks like its not being maintained anymore so we've patched and updated the SDWebImage to better handle promotion displays
> Improve GIF playback speed on ProMotion devices

- src/hooks/useSwapInputHandlers.ts
needed to add proper handling for l2 assets to the max button, we now use the asset uid to get the account asset instead of using address
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-09-13-26-35.mp4
> use uniqueId

- src/handlers/deeplinks.ts
- src/navigation/RegisterENSNavigator.js
- src/redux/ensRegistration.ts
- src/screens/ENSAssignRecordsSheet.js
- src/screens/ENSSearchSheet.js
- src/utils/branch.ts
Fixed an issue where upon opening the edit profile sheet, it would show the loading skeleton placeholder indefinitely. 
Turns out we were using a `useEffect` in `ENSSearchSheet` that was setting the registration to a "create" state & since the ENS navigator is not lazy, it will invoke the `useEffect` on mount. Fixed by replacing with `useFocusEffect`.
Also fixed a couple of TS errors too.
> Profiles: Fix edit profile infinite loading state

- src/utils/getUrlForTrustIconFallback.ts
Created a new (default) branch on the assets repo where all the addresses are lowercased so we don't have to call the expensive function  `toChecksumAddress`
Before (checksummed): 
https://raw.githubusercontent.com/rainbow-me/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png
After (lowercase):
https://raw.githubusercontent.com/rainbow-me/assets/lowercase/blockchains/ethereum/assets/0x6b175474e89094c44da98b954eedeac495271d0f/logo.png
> Remove toChecksumAddress for assets urls

- src/components/asset-list/RecyclerAssetList2/core/RowRenderer.tsx
- src/components/images/ImgixImage.tsx
Fixes RNBW-3354
Previous PR was reverted due to duplicates of NFTs in the list. Found a cause for this.
Imgix class was mutating state, but it was actually doing it in componentDidUpdate that runs after the render, so it would only be applied on the next rerender (maybe, since it was mutating the state, there is no confidence in this).
I used the proper React API to update the state based on props - getDerivedStateFromProps.
There won't be noticeable performance improvements for the asset list after this change, but it's essential for future improvements.
- Wallet screen should look the same
> Reuse rows of recycler list instead of remounting them (attempt 2)

- src/components/asset-list/RecyclerAssetList2/core/Contexts.ts
- src/components/asset-list/RecyclerAssetList2/core/useMemoBriefSectionData.ts
- src/components/asset-list/RecyclerAssetList2/index.tsx
- src/hooks/useCollectible.js
- src/screens/ProfileSheet.tsx
Fixing an issue where the `address` value we were passing to the RAL context was overriding the `address` value in `additionalData`. I renamed `address` to `externalAddress` to be more clear that this address is not the current account address coming from redux state.
> Profiles: Fix & refactor `address` value in RAL context

- src/components/images/ImagePreviewOverlay.tsx
- src/ens-avatar/src/specs/erc721.ts
- src/handlers/simplehash.ts
There is an edge case where the ENS NFT avatar/cover image resolution won't work if OpenSea is down or the collection is removed from OpenSea. This PR adds a fallback to fetch the NFT image from the simplehash API (we are using this in the notifications project).
> Profiles: Fallback ENS avatar fetching to simplehash if OpenSea is down or collection is removed

- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/screens/ExchangeModal.js
Fixes RNBW-3639
If ens NFT is not in opensea yet (no link) don't show the "View on Opensea" button
> Profiles: fix swap estimation + opensea link for new ens

- src/components/ens-profile/ProfileAvatar/ProfileAvatar.tsx
- src/components/ens-profile/ProfileCover/ProfileCover.tsx
- src/components/images/ImagePreviewOverlay.tsx
- src/screens/ENSAssignRecordsSheet.tsx
- src/screens/ProfileSheet.tsx
Fixes RNBW-3640
Fixes RNBW-3641
- Fixed incorrectly aligned avatar/cover photo on the profile sheet
- Adjusted the height of the bottom actions sheet for small devices
> Profiles: More pixel pushing for small devices

- src/components/contacts/ContactRow.js
- src/components/expanded-state/ContactProfileState.js
- src/components/fields/AddressField.js
- src/components/send/SendHeader.js
- src/handlers/ens.ts
- src/hooks/useENSRegistrationActionHandler.ts
- src/hooks/useENSRegistrationForm.ts
- src/raps/actions/ens.ts
- src/screens/ENSConfirmRegisterSheet.tsx
Fixes RNBW-3635
1. when updating a profile the new records were not getting t the app because we're only using the internal state, changes it to use the ens data coming from ens profile query
2.  there's an issue estimating gas for set records transaction where putting a `from` param would make the gas estimation to fail in mainnet, so i removed it for multicall and setText txs
3. extend registration wasn't picking the right duration\
> Profiles: last qa fixes

- package.json
- patches/metro-react-native-babel-preset+0.68.0.patch
- yarn.lock
Since we're running RN 0.68 we can use Hermes 0.11 which supports lots of cool es2015+ things without transformation into slower es5 code.
You can see all the `if (!isHermes)` blocks in the preset file.
> Enable hermes transformer in metro rn babel preset

- src/hooks/useENSModifiedRegistration.ts
- src/hooks/useENSRegistrationCosts.ts
- src/hooks/useENSRegistrationForm.ts
- src/screens/ENSAssignRecordsSheet.tsx
Gas updates now update the fee registration panel. If the estimated fee changes because the user selects a new speed or the estimated fee gets updated from backend, the fees panel will update accordingly for new registrations and registration extension
https://user-images.githubusercontent.com/12115171/169664190-7c720714-439c-41a9-b5ea-609f70ae1279.mov
ENS edition show different form depending on the records the ENS has. Until now if the user had one record set, as the avatar, the form will be empty so no label / inputs would be shown, only an empty ENS would show the form. Now the last case will remain, but if the user only has an avatar and / or cover, the default form will be displayed as well (case for scamdog.eth and eminolar.eth in the video), if the user has some …
> Profiles: records and gas fee panel updates

- src/references/chain-assets.json
https://optimistic.etherscan.io/token/0x8700daec35af8ff88c16bdf0418774cb3d7599b4?a=0x7a3d05c70581bD345fe117c06e45f9669205384f
We didn't notice this, cause we override this with rainbow token list
> Fix decimals in Synthetix in Optimism

- src/apollo/queries.ts
- src/handlers/ens.ts
Fixes RNBW-3667
filtering out domains with no owner
eric.ethglobal.eth has no controller nor resolver but we were still showing it in the ens search
> profiles: filter non owned ens

- src/components/exchange/ExchangeInputField.js
- src/hooks/useSwapDerivedOutputs.ts
- src/screens/ExchangeModal.js
Fixes a few issues regarding input values.
the first is a bug where `useSwapDerivedOutputs` would return because the new quote was the same as the last quote when in fact they were different, I moved some logic around and it works as expected now
another is the handling of the prepending 0 scenario which was not working previously.
the last was handling zero/null values properly so that they clear the other inputs when the focused input is cleared
also passed the editable prop to native input to match the expected behavior
https://cloud.skylarbarrera.com/Screen-Recording-2022-05-24-00-53-49.mp4
> swap - fix derived values behavior

- src/hooks/usePersistentAspectRatio.ts
Fixes RNBW-3729
After the MMKV bump (that happened together with bumping RN), the behavior changes so the default value of `useMMKVNumber` is not `0`, but `undefined`. I adjust the logic for that. 
Reset everything (MMKV, local storage, image cache) and try to open some non-square NFT e.g. BlockCities.
> Fix incorrect aspect ratio calculating after MMKV bump

- src/components/ens-profile/ActionButtons/WatchButton.tsx
- src/hooks/useImportingWallet.js
- src/hooks/useWatchWallet.ts
This PR fixes an issue where watching and then immediately unwatching a profile wouldn't actually unwatch the profile.
I have removed the debounce functionality from the `WatchButton` component as we now have a prompt before unwatching now.
> Profiles: Fix watch button issue

- src/components/ens-registration/RegistrationReviewRows/RegistrationReviewRows.tsx
Fixes RNBW-3679
- loading placeholder was getting cut off vertically on registration confirmation screen
- this fix seems pretty janky so lmk if you have another idea
Before:
After:
> Profiles: fix loading placeholder

- src/components/step-indicator/StepIndicator.tsx
Fixes RNBW-3744
Changed the animation to use `translateX` based on screen dimensions rather than relative percentages with `left`.
@estebanmino & @ibrahimtaveras00  Please test the ENS registration flow on your Android devices because I couldn't repro the initial crash on a Pixel 6.
> Rework StepIndicator to stop crashing on Android

- src/redux/walletconnect.js
Meta reported that they were getting a disconnect event when THEY kill the session. This is a mistake from our end because we were using the same function whenever WE kill the session.
Added a flag to make sure we only do it when needed
e2e coverage is enough in this case
WC flow on android & ios
> kill session only if  we are the ones disconnecting

- src/ens-avatar/src/specs/erc1155.ts
- src/ens-avatar/src/specs/erc721.ts
- src/handlers/ens.ts
- src/hooks/useENSModifiedRegistration.ts
Fixes RNBW-3787, RNBW-3784
This PR fixes a avatar/cover resolution issue found when repetitively opening a profile. Turns out this is because we were being rate-limited from OpenSea. I added a workaround to fetch the image from storage if the OpenSea API fetching fails. We also weren't using the simplehash fallback for 1155's, so I added that too.
I also fixed the issue where a user could see a blurry cover photo upon opening "edit profile".
> Profiles: Fix avatar/cover resolution issues

- src/handlers/ens.ts
- src/parsers/uniqueTokens.js
Fixes RNBW-3748
It seems that when expanding an NFT, it would sometimes produce a duplicate.
Turns out this was an unexpected side-effect when revalidating a collectible. Revalidating collectibles should only happen for ENS NFTs only, and not all NFTs. 
The flag to enable revalidation was not guarding against non-ENS NFTs, so I have fixed the `isUnknownOpenSeaENS` function to filter out non-ENS NFTs.
> Profiles: Fix issue where expanding an NFT would sometimes produce a duplicate

- src/components/discover-sheet/ListsSection.js
Took me a while to track down a crash that happens very often when running detox, which was caused by these things on the DiscoverSheet section list.
- LayoutAnimation
- Gradients
Both are known for not playing well with Detox and we already disabled it on most places.
e2e test are green
Nothing really, doesn't change behavior, only disables certain animations on e2e.
> Disable animations and gradients on ListSections for e2e

- src/handlers/ens.ts
- src/handlers/localstorage/ens.ts
- src/hooks/useENSRegistrationActionHandler.ts
Fixes TEAM2-32
There are some cases where freshly registered ENS names will not be available in the subgraph yet. This PR implements a fallback to the device storage in order to get the freshly registered ENS name from a labelhash. We set this labelhash mapping upon commit.
> Profiles: Fix ENS fallback when not available in subgraph yet

- src/navigation/RegisterENSNavigator.tsx
Fixes TEAM2-36
Added an `overflow: hidden` to the container to prevent an unthemed blank area under that view when going back.
https://user-images.githubusercontent.com/6843656/173150415-f2b6f524-b047-4e33-b666-c0b02bc11ea6.mp4
Profiles editing/registration to make sure nothing else has been broken in the flow.
> Profiles: Fix ENS Registration Intro screen blank section

- src/screens/CurrencySelectModal.js
I see almost no precedent for using route name in view logic like this. Let me know if I'm doing something dumb or unaware of a different helper/hook.
I altered the `showList` prop to also take `activeRouteName` into account.
http://g.recordit.co/s5SAE4tfFW.gif
click that verified thingy -> observe intact list rendering behind the verified explainer
> [TEAM2-53] @rainbow-swaps / use route name to continue showing currency list

- src/hooks/useENSRegistrationForm.ts
This PR fixes a race condition which could end up not populating the avatar/cover records when editing a profile. It turns out we are initially setting the initial records twice (and the one which is removed in this PR was setting the wrong values).
Before:
https://user-images.githubusercontent.com/7336481/173284626-a4d285eb-f349-48da-8029-7243c2459fb7.MP4
After:
https://user-images.githubusercontent.com/7336481/173284635-d953bda8-2946-4e5b-a01b-2f19edcfdbfa.MP4
> Profiles: Fix edit mode default state race condition

- src/redux/data.ts
We have been seeing a regression from [this change](https://github.com/rainbow-me/rainbow/pull/3293/files#diff-3568b4eaf1ead5c20262106d9a20b6660576efe9097055edf9214b647742ccedR888) where addresses were not being lowercased before comparison, causing an empty transaction history if a user did not have a cached history. This PR just fixes up that issue.
Maybe we should spin up the app from a clear cache during QA?
Before:
After:
1. Open the app with a clear cache
2. Import a wallet and check if the txn history populated
> Fix empty txn history regression

- index.js
* Used wrong identifier to start measuring and never commited the identifier we actually wanted to track
> Fix wrong tracked identifier in Performance metrics

- src/components/contacts/ImageAvatar.js
- src/components/settings-menu/BackupSection/WalletSelectionView.js
Fixes TEAM2-26
- use ens avatars in backup sheet
- ImageAvatar shadows for size "smedium" are copy/pasted from ContactAvatar
- the other issues you see (incorrect wallet labels and non-ens avatars) are fixed in https://github.com/rainbow-me/rainbow/pull/3464
> Profiles: Use ens avatars in backup sheet

- package.json
- src/utils/CoinIcons/CoinIcon.js
- src/utils/CoinIcons/CoinIcons.android.js
- src/utils/CoinIcons/CoinIcons.js
- yarn.lock
Fixes RNBW-3343
Please, read firstly this. After @mikedemarais will merge this, we will change the ref in `package.json`
https://github.com/mikedemarais/react-coin-icon/pull/21
I use pngs (100px width) instead of svgs. They are way faster on Android. This was particularly important because currently, we use fallback which might give inconsistencies between platforms and ugly icons on Android.
See if the icons look good.
> Include pngs

- src/hooks/useENSRegistrationCosts.ts
Fixes TEAM2-1
This PR fixes an issue where sending an L2 asset to an intro screen profile wallet would cause a blank screen in the app. Turns out there were some undefined values floating around.
> Profiles: Fix issue where sending L2 asset on intro screen profile causes white screen

- src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
- src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
Fixes TEAM2-99
- if you start a registration too soon after uploading an avatar/cover image to your ens profile, the temporary image path gets saved to the ens registration instead of the pinata url. this can cause the images to disappear, because these temporary image paths are not guaranteed to persist. 
- the fix: disable the "Review" button until the image has fully uploaded
> Profiles: Prevent temp image paths from being included in ens registration

- src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
* Fixed the `<Bleed />` props that wrap the `<Pill />`
* Removed use of `<SwapDetailsRow />` and made `<SwapDetailsLabel />` a direct sibling of the rest of the row's content. This fixes 2 issues:
The vertical alignment between the label and value in `<SwapDetailsRow />` does not appear to behave as intended, but looks correct in most cases because the line-height of the label and value are the same. But now that `<SwapDetailsLabel />` is a direct sibling of the rest of the row's columns, the vertical alignment applies correctly.
Toggling between DEX's was causing row height issues on Android. I believe this was caused by passing in `<Columns>{...}</Columns>` rather than a string as `props.children` to `<SwapDetailsRow />`. 
https://user-images.githubusercontent.com/14877580/173995190-ecbf …
> [TEAM2-95] Swap review sheet -> more details: exchange row formatting

- src/components/layout/KeyboardFixedOpenLayout.js
- src/helpers/keyboardTypes.ts
- src/hooks/useKeyboardHeight.js
- src/screens/ExchangeModal.js
Fixes TEAM2-124
This PR fixes an issue where navigating from the currency select screen back to the swap screen would cause a pretty horrid layout shift on Android. This layout shift was being caused from the keyboard height cache setting a stale height when the screen was out of focus.
https://user-images.githubusercontent.com/7336481/173997803-bf91c76f-f822-44f3-8b58-c444d0760021.mp4
> Swaps: Fix android layout shift on the swap screen

- src/components/expanded-state/UniqueTokenExpandedState.tsx
Fixes RNBW-3795
* Added a `useFocusEffect` call that adds screen option for ExpandedAssetSheet screen to not hide the screen. .This prevents it from disappearing when we open 4th modal – custom gas sheet
Before:
https://streamable.com/qplqjm
After:
https://streamable.com/a0pfj8
* Go to a normal ExpandedAssetSheet check if everything is cool
* Go to Expanded asset sheet and try to cycle through like uniswap pools, we capped the max amount of open sheets allowed to prevent too many sheets being open when cycling through uniswap pools
* Pick ENS and try the flow where you extend the registration, see if the custom gas sheet has the keyboard properly handled and if the expanded asset sheet isn't dismissed in the background.
> Fix Keyboard dismiss and Expanded Asset Sheet hiding

- src/components/expanded-state/UniqueTokenExpandedState.tsx
Fixes TEAM2-142
- nonexistent ens profiles were being prefetched (and stored) for non-ens NFTs
- now only called if NFT is an ens
> Profiles: Don't prefetch profile for non-ens NFTs

- src/components/expanded-state/asset/ChartExpandedState.js
- src/components/expanded-state/swap-settings/SwapSettingsState.js
- src/components/layout/KeyboardFixedOpenLayout.js
- src/hooks/useSwapCurrencyHandlers.js
- src/screens/CurrencySelectModal.js
- src/screens/ExchangeModal.js
Fixes TEAM2-107
- flashbots switch in settings is only available on mainnet swaps, the height of settings will act accordingly
- added swap button to owned assets in wallet screen
- currently when you select an L2 asset to swap from the wallet screen, or going to swap from the fab swap button, the network swap will default to mainnet even tho the output asset is on L2 (you can check the before video), this PR fixes it
before
https://user-images.githubusercontent.com/12115171/174172089-9db95685-8116-443c-956b-e1db60650a58.mov
after
https://user-images.githubusercontent.com/12115171/174171399-4620f3a1-9e24-4545-9b76-daca95653172.mov
> swaps: token network fixes

- src/languages/_english.json
- src/screens/CurrencySelectModal.js
- src/screens/ExplainSheet.js
Added additional explainer sheet when the user selects an L2 output they don't have currency to swap for.
Ensure the new explainer prevents the user from selecting an L2 asset as output when they do not own other assets on that chain. Probably best to check that the changes did not affect other explainer sheet use cases.
> [TEAM2-113] Swap token list sheet: no tokens on [network] explainer sheet is missing

- src/components/value-chart/ExtremeLabels.js
Fixes RNBW-3821
Before:
https://user-images.githubusercontent.com/5769281/172926780-4d304e5e-d0be-43fd-bec3-f5fefeb3f3c4.mp4
After:
https://user-images.githubusercontent.com/5769281/172926793-4cbf3712-a71d-4ffb-b343-07f6328dc604.mp4
Check if the extreme labels (the small number over the maximum and minimum points) have correct font, appear in correct moment and work correctly on iOS and Android.
> Fix Android chart label

- src/hooks/useUniswapCurrencyList.ts
Fixes https://twitter.com/codeforreal_/status/1538513809639612419
Fixes TEAM2-140
It looks like those values can be undefined if the phone was offline.
Optional chaining
Before: See recording on Twitter 
After:
Turn on airplane mode, and see if searching fails. See the recording on Twitter.
> Fix crash while searching on the list

- src/hooks/useSwapCurrencyHandlers.js
Mainnet should be the implicit default whenever we do not see a network value on a token. We weren't supply a default, which caused this issue when switching to from L2 -> mainnet.
This flow also had some keyboard issues. I think the `InteractionManager` code block should wait for the keyboard to dismiss so I pulled it out.
Initiate swap flow with an L2 asset then attempt to swap it for a mainnet asset.
> [TEAM2-138] Switching to [network] sheet: sometimes the network is undefined

- src/handlers/cloudinary.ts
Fixes https://rainbowhaus.slack.com/archives/C01GD1F2ZTL/p1655913852370269
Looks like my list of ratios was not exhaustive (cause docs lie). I added a bit more "popular" ratios +  rounding for the remaining. Rounding should not happen very often - probably on some weird phone, but we cannot support everything perfectly. 
Check on Pixel 3, Pixel 5, just compare different phones.
> Fix not loading icons fro cloudinary on some phones

- src/screens/CurrencySelectModal.js
I added an additional value: `isTransitioning` to determine whether the currency selection modal's list should show. This is an incredibly hacky solution, but I spent far too much time looking for an elegant way to do this.
ensure you do not see the skeleton loader appear in place of the currency list when navigating away from the currency selection modal
> [TEAM2-154][RNBW-3894] Tokens list goes to loading state when going from token list to swap screen

- src/hooks/useSwapCurrencyHandlers.js
we were still seeing some "Switching to undefined" instances of the network change explainer sheet, this PR uses `ethereumUtils.getNetworkFromType` to get the network to give it to the explainer sheet
https://user-images.githubusercontent.com/12115171/175434313-445148d1-f1a6-4ae9-be58-56f6867ab941.mp4
> fix: use getNetworkFromType in switch network explainer

- src/hooks/useSwapDerivedOutputs.ts
- src/hooks/useSwapInputHandlers.ts
- src/redux/swap.ts
Fixes RNBW-3506
when pressing max on input we were showing all decimals available for the token
this PR rounds up the number for the input value but the underlying input value is still the amount with all decimals
users can still add as many decimals as they want in the input
https://user-images.githubusercontent.com/12115171/175422851-159e9118-0e3b-4249-a2c2-777cae720922.mp4
> swaps: round max input

- src/navigation/Routes.android.js
- src/navigation/onNavigationStateChange.js
Fixes RNBW-3879
Someone forgot to pass props from `SendFlowNavigator` to the screen. This resulted in a situation where SendSheet would never get the asset (or any other param) on Android.
Before:
https://user-images.githubusercontent.com/5769281/175315156-844370d8-3ebf-46a5-b139-3278abffc4b1.mp4
After:
https://user-images.githubusercontent.com/5769281/175315172-b403954d-c8e3-49ae-b992-ddb297dbb6a3.mp4
Try sending asset from expanded sheet.
On iOS it should look like it did in the past. No changes.
On Android it should now match iOS.
Because previously it didn't work on Android, there is a possibility that this fix uncovers another bug (see the After video, keyboard adjustment is very wrong; I am unsure if it was a temporary glitch or indeed a bug).
> Fix missing params passing to send sheet on Android

- src/handlers/imgix.ts
Comma character `,` was used as a separator in cache of images. Turns out that:
1. No one realized it is a legal URL character.
2. We didn't have any URLs using it.
3. Cloudinary does.
Image cache should work properly again.
Check that images you see in the app are the ones you are supposed to see. You will immediately notice if they are wrong.
> Fix image cache after introduction of images from Cloudinary

- src/components/exchange/ExchangeNotch.js
- src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
- src/components/expanded-state/swap-settings/SourcePicker.js
- src/components/expanded-state/swap-settings/SwapSettingsState.js
Fixes TEAM2-170
- Fixed: exchange % pill height
- Fixed: exchange icon stack not vertically aligned
- Fixed: swap screen input row has an offset margin instead of being edge-to-edge
- Fixed: exchange icon with no image text not vertically centered inside circle
> Swaps: Android layout fixes

- src/components/ens-registration/RegistrationAvatar/RegistrationAvatar.tsx
- src/components/ens-registration/RegistrationCover/RegistrationCover.tsx
Fixes TEAM2-126
- useFocusEffect was getting called after avatarUrl was already updated in onChangeImage, which caused avatarUrl to get updated a second time. i changed useFocusEffect to useEffect to make sure it only executed `setAvatarUpdateAllowed(true)` on the initial render.
> Profiles: Fix nft upload flash when editing profile

- src/hooks/useSwapDerivedOutputs.ts
Fixes TEAM2-172
our current getAssetPrice function doesn't account for L2 specific assets where there is no asset price on mainnet, we have all of this data in the asset object so we're falling back and double checking if we can't find the price
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-27-09-50-44.mp4
mainnet assets should work fine
L2 assets with mainnet matches should be fine
L2 assets not on mainnet should not have a price and fill the native input(most polygon tokens and OP)
> swaps - input price fallback

- src/hooks/index.js
- src/hooks/useSwapCurrencyHandlers.js
- src/hooks/useSwapDerivedOutputs.ts
- src/hooks/useSwapDerivedValues.ts
- src/redux/swap.ts
- src/screens/ExchangeModal.js
Fixes TEAM2-200
Fixes TEAM2-185
- TEAM2-200: native values in L2s weren't always returning, i'm adding https://github.com/rainbow-me/rainbow/compare/%40bruno/rainbow-swaps...%40esteban/flipping-behavior?expand=1#diff-1e8dc0a8297e67895c041ebe3ad9c31b8464c49c22ed70d9f3a71e2ccf011f4cR183 which is the same that we have in the discover search for tokens, so we get the mainnet asset to fallback to
- TEAM2-185 arbitrum flipping as ticket describes
- we have a bug with no ticket. Pressing flip when the native input is focused, the flip would put the native input value in as the output value
https://user-images.githubusercontent.com/12115171/176258474-d4839f36-d5b4-4e2a-b666-db04bef9606b.mp4
> swaps: flipping behavior changes

- src/handlers/web3.ts
- src/utils/ethereumUtils.ts
Fixes TEAM2-49
It seems that when sending some NFTs, the app would error displaying "Failed to send transaction". Upon further investigation, it seems that some of the newer OpenSea NFT collections do not have an `nft_version` populated (we rely on `nft_version === "3.0"` to perform a `transferFrom`). 
The solution I came up with is to fetch the contract ABI and determine if the correct transfer method _actually_ exists on the contract. Thought it would be better to query Etherscan for the ABI instead of relying on an OpenSea attribute – however, open to other ideas if this is not the most ideal solution.
- Sending older NFTs (that use `transfer(address,uint256)`) should work
- Sending newer NFTs (that use `transferFrom(address,address,uint256)`) should work
> Fix issue where sending NFT would show error

- src/raps/common.ts
- src/raps/index.ts
- src/screens/ExchangeModal.js
Fixes TEAM2-202
mapping between swap modal types & rap types was not set up correctly. I added some logic to change before we submit estimations + raps since I don't want to mess with the swap modal types
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-28-13-30-15.mp4
withdraw + savings should work now
> fix swap/savings rap types

- src/screens/ExplainSheet.js
Fixes TEAM2-178
note that these are gonna look weird on some android devices due to the inset issues 
samsung: 
https://user-images.githubusercontent.com/29204161/176067554-29dc05cd-9ede-4200-9eac-2615090a7dd4.mov
pixel: 
https://user-images.githubusercontent.com/29204161/176067573-1dbb4026-1506-4edb-97a5-ef472e6ea4ab.mov
> swaps - extra height android explainers

- src/components/exchange/ExchangeDetailsRow.js
- src/components/expanded-state/swap-settings/MaxToleranceInput.tsx
- src/languages/_english.json
- src/languages/_french.json
- src/screens/ExchangeModal.js
Fixes TEAM2-201
- small market warning now sends you to the review sheet
- settings slippage above 3% shows a warning in settings when moving it manually
https://user-images.githubusercontent.com/12115171/176331795-61535af1-4961-4bf2-b421-dfe34571df4f.mp4
- try to get the small market warning, you can make it appear typing a really big ETH amount, it should send you to the review sheet with the button disabled
- going to settings and putting a value > 3 should show a warning
> swaps: handle price impact warnings

- src/components/exchange/AnimatedExchangeFloatingPanels.js
- src/components/exchange/ExchangeFloatingPanels.js
- src/screens/ExchangeModal.js
Fixes TEAM2-184
This PR aligns the swap screen layout to what is seen in production right now.
Small screens:
Large screens:
> Swaps: Align swap layout to spec

- e2e/swapSheetFlow.spec.js
- src/hooks/useSwapInputHandlers.ts
Fixes TEAM2-209
we removed the alert and auto adjust automagically, I also added support for all native assets instead of just for mainnet
https://cloud.skylarbarrera.com/Screen-Recording-2022-06-29-15-01-20.mp4
auto adjusting should work on all networks
> swaps - auto adjust max for native assets

- src/components/expanded-state/swap-details/SwapDetailsFeeRow.js
sometimes the rainbow fee fiat value that we display in review sheet is `$NaN`, this is happening because `inputCurrency?.price && tradeDetails.sellAmount` in `useRainbowFee` if false so we default returning a `null` value, making  `rainbowFeeNativeDisplay` to be `$NaN`
in this PR i'm ignoring this case, since we don't know the native value so we'll only show the % rainbow fee
before 
https://user-images.githubusercontent.com/12115171/176714575-15503538-821e-4e5c-a6ba-b8bc6a0b2da8.mp4
after
https://user-images.githubusercontent.com/12115171/176714759-4cc7658e-8694-41bc-9c63-0cca2f58695f.mp4
- follow the video
- i've seen this in polygon tokens but doesn't always happen
> swaps: fix NaN rainbow fee

- src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
- src/helpers/utilities.ts
Fixes TEAM2-175
- Updated `convertAmountToPercentageDisplay` utility to support skip decimals option
- Updated margins and size of pill
https://user-images.githubusercontent.com/296775/176491079-58336f2c-09b3-458d-9883-809f6b6acf57.mp4
On the swap modal when more than one exchange is available: 
tap on the "Swapping via" row
> Fix swapping via exchanges alignment

- src/handlers/ens.ts
- src/parsers/uniqueTokens.js
Fixes RNBW-3851
Regression introduced here:
https://github.com/rainbow-me/rainbow/pull/3188/files
We lost `image_thumbnail_url` in the PR done by Skylar. I restore this and used `lowResUrl` we already have and should have cached from the main screen. 
Before:
After:
Try to send NFTs. Check if there are no those weird letters.
> Restore image_thumbnail_url

- e2e/swapSheetFlow.spec.js
- src/components/exchange/ConfirmExchangeButton.js
- src/components/exchange/PriceImpactWarning.js
- src/components/expanded-state/swap-settings/SwapSettingsState.js
- src/screens/ExchangeModal.js
Fixes TEAM2-187
- adding a debounce while calculating `isHighPriceImpact` to show the alert, so it doesn't appear often while typing new input values
- aligned the alert vertically to the `Flip` and `Settings` button
- we will only show the warning alert if the user has the funds to do the swap
original PR from @benisgold helped a lot with this so i'm pushing it against that branch
https://user-images.githubusercontent.com/12115171/176733638-985a2161-c857-4df8-9cbc-7df8b0648f0b.mp4
follow the video and you'll see now that the alert doesn't appear as often than before
> swaps: isHighPriceImpact debounce

- e2e/swapSheetFlow.spec.js
- src/components/exchange/ConfirmExchangeButton.js
- src/components/exchange/PriceImpactWarning.js
- src/components/expanded-state/swap-settings/SwapSettingsState.js
- src/helpers/tokenSectionTypes.ts
- src/hooks/useSwapCurrencyList.ts
- src/screens/ExchangeModal.js
If a user imports a mainnet token by entering an address, the token data will either be replaced by its duplicate in the verified section or will appear in the unverified section. The imported section has been removed.
Favorited + Verified + Imported behavior:
Verified + Imported Behavior:
Ensure you don't see duplicate token entries or the imported section.
> [TEAM2-198][TEAM2-212] Favorite duplicates when searching for an address / Deprecate Imported category in Swap search

- src/components/ens-registration/ConfirmContent/WaitENSConfirmationContent.tsx
Fixes TEAM2-97
Removed the bigger phone spacing and left only one for all phones
iPhone SE 3rd Gen (iPhone 8)
iPhone 11 (size like 12, 13 Pro etc)
The one it was reproduced in (X, Xs, 11 Pro)
* Go to ENS profiles section, try to register ENS and go to the phase where you have to wait 1 minute, check if the text is wrapped properly without hanging "do" at the very bottom line.
> Profiles: Fix text line break in wait one minute ENS registration state

- src/hooks/useSwapAdjustedAmounts.ts
- src/languages/_english.json
- src/references/index.ts
Fixes RNBW-3934, TEAM2-234
- if the native asset is being converted to or from it's wrapped version, the amount swapped needs to be converted from wei. this is now applied to MATIC/WMATIC in addition to ETH/WETH.
https://www.loom.com/share/98c2f36cf6974effb31bbfdcb51a3cbb
> Swap fixes

- src/hooks/useSwapCurrencyList.ts
I didn't catch this because I tested the API directly when evaluating mainnet token sorting, but we don't use that endpoint for the mainnet curated token list presented when the user hasn't provided a search query.
You won't see WETH prioritized in the curated list when no search query is present. This is because it's not currently classified as a 'curated' token. I added the WETH address into the sorting predicate in case we do decide to add it.
https://recordit.co/jyCs0WzoyE
Make sure these tokens are pinned at the top of the curated/verified sections when applicable: ETH, wETH, Dai, USDC, wBTC
> [TEAM2-238] Pinned tokens in mainnet swap search

- src/handlers/ens.ts
Fixes TEAM2-235
Seems that we were adding an unnessesary `".eth"` to the cached name.
> Profiles: fix .eth.eth issue

- src/components/sheet/sheet-action-buttons/SwapActionButton.js
Fixed location of `fromDiscover` inside `goToSwap` fn.
https://recordit.co/LoMa9YUjLH
* go to swap from wallet, switch network, the input is cleared out
* you will see Swap as header if you're choosing input and receive if choosing output
* from discover, pressing "get token" it will send you to choose output with the title Get {token} with
> [TEAM2-230] Token Expanded sheet Swap entry point bugs

- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/components/expanded-state/ens/ConfigurationSection.tsx
Fixes RNBW-3942
This PR puts the "Set as my ENS name" switch under the profiles feature flag.
> remove set primary name switch leak

- src/components/buttons/hold-to-authorize/HoldToAuthorizeButtonContent.tsx
@benisgold found a bug, pressing the swaps confirm button when is disabled is sometime crashing the app. It also behaves differently than other places where we use the button, it animates on every place even when is disabled
https://www.loom.com/share/79b3b8463f0f457ba2d24bc1f366231f
- send confirm button, when is disabled and enabled
- swap confirm button, when is disabled and enabled
> swaps: fix press disabled confirm

- src/components/token-family/TokenFamilyHeaderIcon.tsx
https://github.com/rainbow-me/rainbow/pull/3547 introduced a regression that increased the size of the NFT family icon from 30px to 40px
this returns it back to 30px
before/after:
> Fix NFT token family icon size

- src/components/asset-list/RecyclerAssetList2/FastComponents/FastCoinIcon.tsx
- src/components/asset-list/RecyclerAssetList2/FastComponents/FastFallbackCoinIconImage.tsx
Fixes RNBW-3946
There was a visual regression introduced with merge of balanced coin row refactor: some coin shadows were gone.
ETH icon shadow should be back together with some others (shiba inu for example).
> **NOTE:** as of now, those screenshots should be accurate as there were no code changes. However, they might turn out to be inaccurate because of human error (I messed up something while pasting) or some glitch (bundler not updating when switching branches). Use at your own risk.
||Before|Develop|Fix|
|--|--|--|--|
|Android light|![an_before_light](https://user-images.githubusercontent.com/5769281/177577186-cf8fd74e-b408-48fd-af7c-d8eb57fbd2b7.jpg)|![an_develop_light](https://user-images.githubusercontent.com/5769281/177577203-9564d6a5-b527-4889-8321-81178ccf3b10.jpg)|![an_now_ligh …
> Get shadows to display

- src/components/expanded-state/asset/ChartExpandedState.js
Fixes TEAM2-242
we now only want to show this component if the user does not have a balance
https://cloud.skylarbarrera.com/Screen-Recording-2022-07-11-11-37-27.mp4
see video
> swaps - available networks balance check

- src/components/exchange/ConfirmExchangeButton.js
- src/components/exchange/ExchangeField.js
- src/components/exchange/ExchangeNativeField.js
- src/handlers/uniswap.ts
- src/hooks/useSwapDerivedOutputs.ts
- src/screens/ExchangeModal.js
Fixes TEAM2-246
The `useSwapDerivedOutputs` hook had a `useEffect` listening to changes on any swap param to call `getTradeDetails`, this was producing a race condition if `getOutputAmount` or `getInputAmount` takes longer for any reason. One scenario to easily reproduce it (and related to the issue 1. in ticket) is erase the input very fast while the quote is being fetched.
https://user-images.githubusercontent.com/12115171/178374233-5e98d134-2d0e-4b24-9672-26fdcac1fe71.MP4
in order to fix this race condition and avoid multiple unneeded calls to the hook this PR introduces `useQuery` to deal with this logic instead.
for issue 2. i removed this condition https://github.com/rainbow-me/rainbow/pull/3687/files#diff-d7555f0c12b00ac091459b5a69d184f5582cd342c0c77b2bfc1d42a18 …
> swaps: improve useSwapDerivedOutputs

- src/components/buttons/TokenSelectionButton.js
- src/components/exchange/ExchangeField.js
Fixes TEAM2-171
Figma link (if any): see ticket
we now truncate the symbol if its over 6 digits. we also added right padding to the inputs.
https://cloud.skylarbarrera.com/Screen-Shot-2022-07-11-11-53-39.60.png
check long symbol names (eth2xfli), otherwise text should be normal
> swaps - truncate long token symbols 

- src/parsers/requests.js
Fixes RNBW-3963
Figma link (if any): N/A
The usage of the payload ID as timestamp is not officially supported
or documented in WalletConnect.
The timestamp is used on the clientside to be able to remove older
requests that have not been interacted with, so this does not
impact anything with the WC protocol.
Please see the test path details in the Linear ticket which has the corresponding OpenSea APK to test against.
> Remove undocumented usage of WC request payload ID as timestamp

- src/config/experimental.ts
- src/navigation/Routes.android.js
- src/navigation/Routes.ios.js
- src/navigation/routesNames.js
- src/screens/ProfileScreen.js
- src/screens/SettingsSheetV2.tsx
Fixes TEAM2-245
This PR adds a feature flag to hide all the upcoming notifications work. Since the upcoming work implements the new settings sheet designs (that we don't want to release yet), we are going to dupe the `SettingsSheet` component into a v2 variant, and then once the notifications feature flag is removed, we will prune the original components.
- When the feature flag is off, ensure that `SettingsSheet` is pushed to navigation stack
- When the feature flag is on, ensure that `SettingsSheetV2` is pushed to navigation stack
> Notifications: Feature flag

- src/utils/methodRegistry.ts
We changed the transactions list screen to use our metadata backend service in https://github.com/rainbow-me/rainbow/pull/2990, this PR extends the usage to the WC transaction confirmation screen. Still use the on-chain registry as a fallback, but should be rare to hit unless the backend is down/times out, backend also hits the on chain registry. This will allow us to more tightly control poor user experiences like this one:
Tested manually, no UI change.
Check that the function name on the WC confirmation screen is present. For some reason I can't always trigger the resolution, maybe sometimes the data passed in https://github.com/rainbow-me/rainbow/blob/68c2af6a019442bf3fe663eea723f321423bf763/src/screens/TransactionConfirmationScreen.js#L328 is empty? Not sure why.
> [TEAM2-19] Wallet connect confirmation screen should use metadata service

- src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
- src/components/exchange/ExchangeAssetList.js
Fixes https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1657701308401929
Looks like the previous logic "accidentally" worked - it was setting the favorite and opening sheet at the same time. For the second time, it was crashing because `onNewEmoji` was `undefined`. Now, I split this into two functions, and works ok! 
Another bug was not pressable buttons in the menu after pressing `i`  - incorrect prop name was used
After: https://streamable.com/pnr1sh
Before: See the linked message
Check the Search list and all buttons, the do the same with the Selection list for input and output currency for swap (this is the same component)
> Fix crash on double pressing add button

- src/hooks/useSwapCurrencyList.ts
sorting favorites by abc in `useSwapCurrencyList`
Ensure whether searching or viewing the default favorites list on the currency selection modal that favorites remain sorted alphabetically.
> [TEAM2-239] Sort swap currency list favorites alphabetically

- src/helpers/utilities.ts
Now `undefined` is not removed while pickFlatten
https://rainbowhaus.slack.com/archives/C02C2FVC6N6/p1657550240854639
> Allow undefined in pickShallow

- src/hooks/useSwapDerivedOutputs.ts
Ignoring the source=rainbow so it doesn't get pass to the backend ( we only support 0x and 1inch)
https://recordit.co/8bSV2YDbUp
Switch sources and look at the logs. When "Auto" is selected there shouldn't be a source in the quote
> Don't pass source=rainbow to the backend

- src/navigation/Routes.ios.js
- src/react-native-cool-modals/NativeStackView.js
- src/react-native-cool-modals/ios/RNCMScreen.h
- src/react-native-cool-modals/ios/RNCMScreen.m
- src/react-native-cool-modals/ios/UIViewController+slack.swift
Fixes TEAM2-216
In the exchange, modals there are two scrollviews - outer for the horizontal animation (not interactive with a gesture) and inner for the vertical scroll. Obviously, we want ot attach the logic to the inner. 
I added a small trick to let developers specify which scroll view ot use in the order of DFS traversing. In this case, this is the second, not the first one.  
In the preview it looks like this: 
outer: 
inner: 
So i added an option `relevantScrollViewDepth`. 
The behavior is expected: https://streamable.com/634wyp
To test changes, please open the Exchange modal and observe interactions. If they are ok, it's ok. You may check also other modals, e.g., switch wallet sheet or setting screen (or small phones), but I don't expect this is serious. I …
> Set custom depth of the scroll view in Exchange modal in RNCM

- src/components/coin-icon/CoinIconFallback.js
https://rainbowhaus.slack.com/archives/C01GD1F2ZTL/p1657718319952289
Before, I was not aware that this size is also used for the layout, not just URL generation 
before: 
After:
> Fix shadow in the expanded state

- src/components/asset-list/RecyclerAssetList2/FastComponents/FastCurrencySelectionRow.tsx
Fixes RNBW-3979
just using colors from theme, before colors was being used from @rainbow-me/styles so wasn't working well
https://www.loom.com/share/fa24d28403c3406f9d6d792bbd39774b?from_recorder=1&focus_title=1
> fix: use colors from theme for favStar

- src/parsers/uniqueTokens.js
Fixes TEAM2-251 RNBW-3645
polygon images stopped working in the app ~2 months ago, we had a ticket that should have made us aware but it got lost in triage handoff.
tldr: opensea only sends asset images under `metadata` now on the v2 endpoint
https://cloud.skylarbarrera.com/Screen-Recording-2022-07-14-18-03-18.mp4
visitors + 100t images should show up
misfitinternet.eth + skillet.eth
> fix polygon OS images

- src/screens/AddTokenSheet.js
- src/screens/SendConfirmationSheet.js
Fixes RNBW-3928
we missed a few spots for l2 icons, this fixes. I went through and tried to find more but I think this should cover the rest
1. send confirmation sheet needed the type to calculate the proper color
2. add token sheet needed the type to get the proper icon
1. https://cloud.skylarbarrera.com/Screen-Shot-2022-07-14-15-42-20.21.png
2. https://cloud.skylarbarrera.com/Screen-Shot-2022-07-14-15-44-32.49.png
the above
> fix remaining l2 color/icon issues

- src/redux/data.ts
l2 txs were getting stuck sorting in update nonce, I added a mainnet check. I also moved to using currentNetwork for the local network.
this also fixes an issue where the updated txs were being saved to local storage with L2 network types which will never get loaded. they are now saved under the global network as expected
https://cloud.skylarbarrera.com/Screen-Shot-2022-07-14-21-42-47.11.png
enable L2 txs, switch wallets and check persisting data
> fix l2 txs

- src/hooks/useSwapCurrencyHandlers.js
Fixes TEAM2-261
Flipping when the inputs are empty will add a `0` to the input is focused, video in ticket
fixed
https://www.loom.com/share/72f5536272d24cc98d5d82ce1d82e45d
- press flip when both of the inputs are empty, they should remain empty after the flip
> fix: empty input flipping behavior

- src/components/expanded-state/swap-details/SwapDetailsExchangeRow.js
Fixes TEAM2-262
I added some memo's and ensured that the error state is getting reset on a new url, seems to be working as expected. can't repro anymore
easiest on polygon to get multiple exchanges, open swap details and wait a bit for the quote to update.
> swaps: exchange icons memos + error reset

- src/model/config.ts
- src/screens/ExchangeModal.js
Added default slippage to remote config
Jumped on a call with @estebanmino to verify this works properly
You can change the value in the remote config, restart the app and it should be reflected in the slippage settings
> Add default slippage to remote config

- src/redux/data.ts
Fixes [TEAM2-237]
Transaction.status doesn't exist on the transaction confirmation object anymore. We now invoke txConfirmationObject.wait() to inspect the transaction receipt to determine the status.
https://docs.ethers.io/v5/api/providers/types/#providers-TransactionResponse
Screen recordings / screenshots
https://recordit.co/WMGFxVEjH6
https://github.com/rainbow-me/rainbow/tree/%40derHowie/check-tx-receipts-test-branch
The branch above cuts `gasLimit` in half on swaps and enabled the transaction watcher so that mainnet swaps will fail and we will see the changes in the pending transaction logic execute.
* ensure failed transactions appear correctly in the tx list on the branch above
* ensure successful transactions behave normally on the branch that isn't broken …
> Failed L2 swaps don't display Failed transaction activity state

- src/redux/uniswap.ts
We use the WETH address to get uniswap v2 metadata for ETH. We accommodated for ETH in this way but unintentionally prevented WETH from receiving appropriate metadata when favorited.
Make sure WETH appears in search even when favorited.
> [TEAM2-267] WETH not appearing on search

- src/components/exchange/ConfirmExchangeButton.js
Fixes TEAM2-268
- prevent user from clicking swap button more than once
https://user-images.githubusercontent.com/15272675/179844781-1c3bbf78-bda2-480a-b58d-45756a6f2a63.mp4
make sure you can't make duplicate tx's by spam clicking swap button
> disable swap button after pressed once

- src/model/config.ts
- src/screens/ExchangeModal.js
Fixes TEAM2-269
edited config to return a json object for slippage by network. note it gets returned in a string so we have to parse when it comes in
remote config: https://cloud.skylarbarrera.com/Screen-Shot-2022-07-19-14-54-52.10.png
confirmed loaded from remote: https://cloud.skylarbarrera.com/Screen-Shot-2022-07-19-14-55-06.71.png
PoW: https://cloud.skylarbarrera.com/Screen-Recording-2022-07-19-14-56-00.mp4
values have been restored to 100 for mainnet, 200 for l2s
check slippage on mainnet is 2
> swaps: remote slippage by network

- src/components/exchange/ConfirmExchangeButton.js
- src/hooks/useGas.ts
Fixes TEAM2-265
added a new state from `useGas` hook to know if the gas fee is ready to show a loading state in the confirm button when the gas is not calculated yet
pow https://www.loom.com/share/893760faa79a4c3b8175f95d659fd13a
> swaps: fix gas loading state

- src/components/buttons/hold-to-authorize/HoldToAuthorizeButtonContent.tsx
- src/components/exchange/ConfirmExchangeButton.js
Fixes TEAM2-264
wasn't able to repro but from the logic it seems we needed some loading checks to be added to prevent authorizing to be set to true to early
> swaps: add loading check to confirm button

- src/components/exchange/ExchangeNotch.js
- src/screens/ExchangeModal.js
Fixes RNBW-3987
Fixed glitched out `ExchangeModal` on Android
| before  | after  |
|---------|--------|
| ![image](https://user-images.githubusercontent.com/6843656/180069535-6b1ae5e7-cebe-4984-a50f-e589cd26c3bc.png)  |  ![image](https://user-images.githubusercontent.com/6843656/180069562-639c0c14-60a2-43cf-b636-949edf65af43.png) |
Check for any visual glitches on the swap sheet background on iOS and Android.
> Fix weird swap sheet clipping on Android

- src/screens/ExchangeModal.js
APK is not getting the values 
waiting for @ibrahimtaveras00  to confirm is working now
> swaps: check slippage remote config

- src/components/expanded-state/swap-settings/InputPill.js
did the same than @skylarbarrera here https://github.com/rainbow-me/rainbow/pull/3545
before 
after
> fix: slippage selection color android

- src/components/expanded-state/UniqueTokenExpandedState.tsx
- src/components/expanded-state/unique-token/NFTBriefTokenInfoRow.tsx
- src/components/expanded-state/unique-token/UniqueTokenExpandedStateHeader.tsx
- src/components/unique-token/Tag.js
- src/components/unique-token/UniqueTokenAttributes.tsx
- src/entities/uniqueAssets.ts
- src/handlers/ens.ts
- src/handlers/simplehash.ts
- src/languages/_english.json
- src/languages/_french.json
- src/navigation/useUntrustedUrlOpener.ts
- src/parsers/index.ts
- src/parsers/uniqueTokens.js
- src/redux/uniqueTokens.ts
This adds support for optimism and arbitrum NFTs.
The commit history is clean and is meant to be read in order.
Many items were tightly coupled with OpenSea, so many of the changes are nominal (name changes) or are updated to help the logic behave more generically.
Example wallets used: vitalik.eth, misfitinternet.eth, 0x6F829Fd52DF9B664DDa4DA2D1ce200A404Ae0B80
Please test NFTs on mainnet, polygon, optimism, and arbitrum.
Please make sure our POAPs and ENS still work as expected
Please go through each item in the NFT expanded state.
Details about the expanded state:
* Rainbow web URLs are supported only for mainnet and polygon.
* The Share button should be the Rainbow web URL for mainnet and polygon; it should be the permalink for arbitrum and optimism when available. If the permalink is …
> Optimism and Arbitrum NFT support

- src/components/asset-list/RecyclerAssetList2/core/RefreshControl.tsx
Conditionally rendering the refresh control seems to create a race condition, where the `refresh` function doesn't actually fire. Rather than rendering null in place of the refresh control, I am performing a NOOP if we see that assets are still loading.
https://recordit.co/IkR0fpYfu0
Switch wallets and attempt pull to refresh. If you're very fast, we may NOOP, but it will no longer get stuck if working appropriately.
> [TEAM2-285] Wallet pull to refresh is getting stuck

- src/screens/SpeedUpAndCancelSheet.js
The `CUSTOM` gas speed is only available for mainnet transactions now.
Example of speeding up a polygon transaction, that doesn't show custom option: https://recordit.co/X9ydyOYUYz
Example of speeding up a mainnet transaction, that continues to show a custom option: https://recordit.co/hqBZ4gSoRP
Ensure that you cannot navigate to the custom fees panel when attempting to speed up an L2 transaction. Also make sure that mainnet transactions can still leverage the custom fees panel.
> [TEAM2-18] Polygon custom gas choice in speed up tries to use EIP1559 and crashes

- src/components/coin-row/SendCoinRow.js
Fixes RNBW-4010
|Before|After|
|--|--|
|![IMG_73DA1D34D485-1](https://user-images.githubusercontent.com/5769281/180438990-2b686791-4b54-4e0c-bc92-c1e29cdfa54b.jpeg)|![IMG_2015E53C5FA0-1](https://user-images.githubusercontent.com/5769281/180439014-02333599-97ec-42b3-b212-8ff955b8c2f2.jpeg)|
Check if list of assets in the send sheet contains currency symbols when using currencies where symbol appear after the amount (for USD the format is `$1,000.00`, for other it might be `1,000.00X`).
The problem appeared only in amount `>100`, as we were truncating them.
Note that we are not dealing with proper number formatting here! So our usage of comma and dot is wrong for most locales, but we are not fixing it at the moment. See for more: [Currency …
> Fix displaying currency symbols that appear after amount

- src/components/gas/GasSpeedButton.js
Fixes RNBW-3995
Text formatting in `GasSpeedButton.js`.
|--|--|--|
|Android|![Screenshot_20220721-162242_Rainbow](https://user-images.githubusercontent.com/5769281/180224416-a38b2e5c-76db-4405-9b6a-3c4c487536e2.jpg)|![Screenshot_20220721-162308_Rainbow](https://user-images.githubusercontent.com/5769281/180224425-f0a11802-a408-442e-bfa8-114bf55f4136.jpg)|
|iOS|![IMG_0DF7BF950353-1](https://user-images.githubusercontent.com/5769281/180225831-f85c9ed1-0305-45b2-bbeb-3729dde0756e.jpeg)|![IMG_D3B93A2DDBB0-1](https://user-images.githubusercontent.com/5769281/180225816-d3862fc2-316c-40e6-bb95-e4b88def4810.jpeg)|
The only change is the way text is formatted in the gas speed section.
This can affect how the price values there display on different screen sizes …
> Fix wrong line breaking in fee estimation

- src/components/expanded-state/swap-details/CurrencyTile.js
Fixes TEAM2-296
we not use the native display value for the input value price
bad wifi rn can't upload, will post later
check swap details input price to match the native input value
> swaps: use native display value for swap details

- src/hooks/useSwapCurrencyList.ts
Fixes TEAM2-297
we were not adding imported assets on L2's now we do and I adjusted the filtering checks to include them
note I hard coded address since pasting is broken on sim
https://cloud.skylarbarrera.com/Screen-Recording-2022-07-25-14-13-35.mp4
try to import a token address on an L2
> swaps: fix l2 imported assets

- src/components/exchange/ExchangeAssetList.js
We went from favoriting doing nothing to working. I have a feeling if you rapidly tap shit it will cause weird behavior but this is a step in the right direction. TBD on whether we need an additional ticket to do this elegantly.
https://recordit.co/WY3hV7Rd30
check that favoriting works at all
> [TEAM2-298] Fix favoriting

- src/components/exchange/ConfirmExchangeButton.js
- src/screens/ExchangeModal.js
Fixes TEAM2-293
we weren't awaiting for the tx to be sent, including the unlocking of the wallet so it was crashing, and also if the biometrics failed or the user pressed Cancel on android dialog it would be stuck in "submitting" state even tho the tx wasn't submitted at all
https://www.loom.com/share/83f3793e3cc1440dafbd0e89d15e42ab
> swaps: team2-293

- src/components/send/SendAssetForm.js
Fixes RNBW-4012
The way layout is calculated in send sheet _on Android_.
|iOS|Android with keyboard|Android without|
|--|--|--|
|![IMG_EADD4259BDA9-1](https://user-images.githubusercontent.com/5769281/180429705-f733f9df-cb09-405d-87ea-4a250b9f948c.jpeg)|![Screenshot_20220722-142428_Rainbow](https://user-images.githubusercontent.com/5769281/180429748-0d1385dc-3bc8-4bc0-9e37-7e9254cf3423.jpg)|![Screenshot_20220722-142446_Rainbow](https://user-images.githubusercontent.com/5769281/180429744-a45c7167-b9ba-4647-a0db-90aac332d45c.jpg)|
Try as many different Android phones. The goal is to make sure that:
- There is no regression in how it looks visually (for example on screenshot with keyboard you can see a light grey area, but this is how it looks on this phone on develop so I am not touching …
> Fix layout of change sheet when keyboard is dismissed

- src/components/asset-list/RecyclerAssetList2/core/ExternalScrollView.tsx
Fixes RNBW-4032
Decrease bottom padding on wallet screen
Before: 
|iOS with notch|IOS without notch|Android|
|--|--|--|
|<img width="495" alt="Screenshot 2022-07-25 at 22 58 19" src="https://user-images.githubusercontent.com/48593211/180959791-c7d29994-fa18-4ccc-baf6-a3b642af99a4.png">|<img width="517" alt="Screenshot 2022-07-25 at 22 58 16" src="https://user-images.githubusercontent.com/48593211/180959905-d10db0fd-1e27-4518-acfa-72ad6dab317f.png">|![photo_2022-07-26 11 20 45](https://user-images.githubusercontent.com/48593211/180959993-d759dcb4-6e94-4f46-a48d-40113b5a3b9e.jpeg)|
After:
|iOS with notch|IOS without notch|Android|
|--|--|--|
|<img width="451" alt="Screenshot 2022-07-25 at 22 55 42" src="https://user-images.githubusercontent.com/48593211/180961600-763562f …
> Update bottom padding on wallet screen

- src/components/AddFundsInterstitial.js
Fixes RNBW-4036
Fix button scale for android on wallet screen. See `... Other amount` and `Copy address`
Before: https://user-images.githubusercontent.com/48593211/180956739-3474fcc6-d446-496f-911a-75b274ed8764.mp4
After: https://user-images.githubusercontent.com/48593211/180956790-81d1a7de-8178-4bc2-b9b3-b09bc1e6ae95.mp4
> Scale for `Other amount` and `Copy address` buttons

- e2e/swapSheetFlow.spec.js
- src/components/exchange/ConfirmExchangeButton.js
- src/hooks/useSwapDerivedOutputs.ts
- src/screens/ExchangeModal.js
Fixes TEAM2-302
Fixes TEAM2-301
bug videos in tickets 
- when you delete the value in one of the inputs, the other inputs’ state isn’t reliably cleared
- on optimism, ‘fetching quote’ is shown before typing any amounts
- added e2e to address the cases where the user clears an input
> swaps: input clearing + loading state

- src/components/profile/AvatarCircle.js
Fixes RNBW-4041
I messed a bit with text alignment. Also it appears that on iOS this is part of the native list (or at least those changes seemed to not affect iOS at all).
Old screenshots (still relevant; no changes):
|Before|After|
|--|--|
|![Screenshot_20220726-155244_Rainbow](https://user-images.githubusercontent.com/5769281/181010610-dac29272-3abb-40c5-8607-ee70b7cf754e.jpg)|![Screenshot_20220726-155217_Rainbow](https://user-images.githubusercontent.com/5769281/181010600-7a60d103-2964-4e33-b2df-6fe7c1893423.jpg)|
New screenshots (including iOS):
|--|--|--|
|iOS|![IMG_0589F57927A1-1](https://user-images.githubusercontent.com/5769281/181242440-55be44b5-23e4-41db-80e5-06e70bcca5f2.jpeg)|![IMG_463602AA2BBA-1](https://user-images.githubusercontent.com/5 …
> Center avatar emoji on Android

- src/components/expanded-state/swap-details/CurrencyTile.js
Fixes TEAM2-304
we weren't using CoinIcon correctly passing addresses
> fix: review coin icon

- src/components/expanded-state/SwapDetailsState.js
- src/screens/ExchangeModal.js
Fixes TEAM2-313
going to edit custom gas from the exhange modal was using the flashbots miner tip correctly but going to the review sheet and trying to modify the custom gas wasn't using the flashbots miner tip
now if flashbots is enabled we'll use the flashbots miner tip for review sheet as well
https://user-images.githubusercontent.com/12115171/181303965-6ea8aaf4-b134-4715-b458-95176142a7e2.mp4
> swaps: handle flashbot miner tip from review sheet

- src/components/profile/AvatarCircle.js
Somehow I didn't push the last commit I made for #3827, which added very important part that prevented breaking current iOS.
The change affected emoji picker.
|Current develop|With this branch|
|--|--|
|![IMG_BA2C0699F9B4-1](https://user-images.githubusercontent.com/5769281/181524214-2124b214-dbf9-46a3-b524-c6719a48bfed.jpeg)|![IMG_D2F88D1E37C0-1](https://user-images.githubusercontent.com/5769281/181524225-a047884c-8ba1-44a1-a05b-6249d4f9b399.jpeg)|
Check emoji avatar and emoji picker.
> Fix center avatar emoji

- android/app/src/main/AndroidManifest.xml
Fixes RNBW-4069
Disable screen splitting. Restrict changes that can be triggered by devices such as foldable phones
Before: https://rainbowhaus.slack.com/files/US31KAK8R/F03RVB2EDH6/nagranie_z_ekranu_2022-07-27_o_09.39.00.mov
After: https://rainbowhaus.slack.com/files/US31KAK8R/F03R60RR946/image_from_ios.mov
- Use any foldable phone. Start the app in a folded state and then unfold a phone. The app shouldn't resize to full screen automatically.
- Try to split the screen. It should be unavailable
> Restrict app resizing for android

- src/components/audio/AudioPlayer.js
safer code
fixes: https://sentry.io/organizations/rainbow-me/issues/2801990037/events/c5b1d80e08754057ac44e81113e1fc8f/?project=1855565&referrer=slack#exception
I'm not going to look into the why, but I fixed the how.
> [TEAM2-321] Audio Player Color Crash

- src/components/expanded-state/swap-settings/SwapSettingsState.js
Fixes TEAM2-315
doesn't make sense to have this on arbitrum atm
https://cloud.skylarbarrera.com/Screen-Recording-2022-07-27-14-33-59.mp4
source picker should show up in settings for every network except arbitrum
> swaps: disable source picker on arbis

- src/hooks/useSwapDerivedOutputs.ts
- src/performance/tracking/index.ts
- src/screens/ExchangeModal.js
- src/screens/WalletConnectApprovalSheet.js
Fixes: https://sentry.io/organizations/rainbow-me/issues/2582111149/?project=1855565&referrer=slack (I think)
I looked through every segment call and these are the lines that could produce NaN then attempt to write to JSON within the native module.
idk, please help
> [TEAM2-322] Do Not Pass NaN into Segment Analytics

- src/components/AddFundsInterstitial.js
Fixes RNBW-4056
I removed a space in front of the 'Other amount' string. As a bonus it removes extra space on iOS which looks odd if you look at it closely.
|--|--|--|
|iOS|![IMG_2BAFEBC4165F-1](https://user-images.githubusercontent.com/5769281/181504422-4c227b5a-2b29-4a88-8a1b-12f5769889ad.jpeg)|![IMG_16A75C1FF92D-1](https://user-images.githubusercontent.com/5769281/181504439-311a7f05-e2aa-43fd-8fa1-53c84fe3e75f.jpeg)|
|Android|![Screenshot_20220728-152227_Rainbow](https://user-images.githubusercontent.com/5769281/181504454-bceb3a80-3263-4b45-87d4-04bbb9e4ceb9.jpg)|![Screenshot_20220728-152138_Rainbow](https://user-images.githubusercontent.com/5769281/181504456-5ab095bd-f491-467e-9dbd-da05f3dcbbf2.jpg)|
'Other amount' button looks good.
> Fix unnecessary line break in 'Other amount'

- src/components/expanded-state/ens/InfoRow.tsx
Fixes RNBW-4031
A hack to convince Android text layout to stay in one line.
Is it ugly? Hell yea.
Is it a hack? Quite, uhm, yea, it's a dirty hack.
Am I proud of it? No.
Have I spent 3h trying all different crazy ways to fix it? Yes.
|--|--|--|
|iOS|![IMG_0A63099A7D6C-1](https://user-images.githubusercontent.com/5769281/181508913-12b51af7-56e4-4812-b2a4-8634c17ba786.jpeg)|![IMG_8E91AA6ADA74-1](https://user-images.githubusercontent.com/5769281/181508905-03580f34-8233-464f-9774-84a397004e27.jpeg)|
|Android|![Screenshot_20220728-154757_Rainbow](https://user-images.githubusercontent.com/5769281/181508889-d87c0fa8-3ae3-436c-a401-6cb2670db0ed.jpg)|![Screenshot_20220728-154625_Rainbow](https://user-images.githubusercontent.com/5769281/181508895-ea58fb57-cc88-4 …
> Fix linebreak in 'Owner'

- src/components/buttons/MiniButton.js
Fixes RNBW-4052
Button in seed phrase import modal.
|--|--|--|
|iOS|![IMG_5AD24E48C6B0-1](https://user-images.githubusercontent.com/5769281/181565978-f1991a7a-9a74-4bd7-a960-b671e535a7dd.jpeg)|![IMG_28656440579E-1](https://user-images.githubusercontent.com/5769281/181565981-79debda9-9019-4c43-b62c-8f0c2e4c9b62.jpeg)|
|Android|![Screenshot_20220728-174712_Rainbow](https://user-images.githubusercontent.com/5769281/181565969-cbc461d5-a97b-4af9-88a6-fd614a9de531.jpg)|![Screenshot_20220728-174552_Rainbow](https://user-images.githubusercontent.com/5769281/181565976-70f4e0cd-2cb7-4933-bc4d-057ddb73224c.jpg)|
Check out button in seed phrase import modal.
> Fix seed import shadow glitch

- src/components/expanded-state/chart/ChartExpandedStateHeader.js
Fixes RNBW-4034
That button doesn't make any sense since you can't add a pool to favorites.
- open any pool - there should be no "+" button
- open any token - there should be "+" button
> Hide + button in pool expanded state

- src/components/coin-row/FastTransactionCoinRow.tsx
Fixes RNBW-4104
This PR fixes L2 transaction icons in the refactored transaction list.
I found that `assetType` was missing in transaction items and @estebanmino suggested to use `network` instead.
|Before|After|
|--|--|
|![Screenshot_20220801-191815_Rainbow](https://user-images.githubusercontent.com/5769281/182196221-a78582e1-e331-46bf-96d2-4cb594dc539e.jpg)|![Screenshot_20220801-191742_Rainbow](https://user-images.githubusercontent.com/5769281/182196251-196ccb04-06c9-41f7-9aba-df7924948115.jpg)|
Enable L2 history in dev settings, go to `0xtester.eth` wallet and check that L2 transactions show up properly.
> Fix L2 transaction icons

- src/components/svg/SvgImage.js
Fixes RNBW-4097
I disabled selecting text in SVGs showed in webviews. Might potentially affect more than just NFTs, but I think it's still ok?
_* Imagine there's a screenshot of **before** with ENS NFT with selected text and then another one, **after**, which has no selected text highlight. *_
Make sure that you are not able to select text in NFTs.
> Disable selecting text in SVG NFTs

- src/components/sheet/sheet-action-buttons/SheetActionButton.js
Fixes RNBW-4072
Code for handling size and line height of text button.
|Before|After|
|--|--|
|![Screenshot_20220802-002357_Rainbow](https://user-images.githubusercontent.com/5769281/182249539-c449fed7-385b-4a9e-a80c-c9568c0e7bc1.jpg)|![Screenshot_20220802-005142_Rainbow](https://user-images.githubusercontent.com/5769281/182252467-63d171b9-cc7d-47cb-9f77-c9adc612da84.jpg)|
Check different tokens in token search and see if button breaks lines anywhere.
> Fix line break in get token button

- src/hooks/useAccountTransactions.ts
- src/hooks/useWalletSectionsData.ts
- src/screens/SelectUniqueTokenSheet.tsx
Fixes TEAM2-180
- remove videos from profile avatar/cover nft selection
- also random unrelated lint
https://user-images.githubusercontent.com/15272675/182487811-47540538-8c43-46b1-8a12-ee9314b8c349.mp4
> Profiles: remove videos from nft selection

- src/navigation/effects.js
- src/screens/AvatarBuilder.js
Fixes RNBW-4000
Placement of avatar circle in avatar picker on Android.
Before 
https://user-images.githubusercontent.com/5769281/182211025-fdcbf59d-14e3-46f1-b4cc-80e321d571b9.mp4
After
https://user-images.githubusercontent.com/5769281/182211057-2a058574-d6df-4966-a3ba-ffdd5fa916e7.mp4
Avatar picker on Android and iOS (looking for regression).
> Fix avatar placement in picker
